### ISSUE TITLE
New Model Number in Name is ahead of Original Model Numbering Stored in Models Folder

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [EdgeTX/edgetx#1005]
While creating a new model, the model number in the name is ahead of the real one. for example. If I have 3 models already, it can be confirmed from the model's folder in the Sd card. Now if I create another model, its name should be MODEL04, but its name is MODEL05.

**General information**
 - EdgeTX version 2.5.
 - Hardware RM TX16S.

**Comment by raphaelcoeffic** [comment]
This one has already been tackled as part of #549.
