### ISSUE TITLE
R9 FLEX unavailable even when firmware built with MODULE_PROTOCOL_FLEX=ON

### ISSUE THREAD

**Issue by shellixyz** [EdgeTX/edgetx#1008]
## tested on NV14 and T16

**Screenshots**

![IMG_20211107_232614](https://user-images.githubusercontent.com/4030264/140664215-7cf04ea4-6521-4399-9961-0eec169b9f63.jpg)

**General information**
 - EdgeTX release 2.5.0 and main as of today built with  MODULE_PROTOCOL_FLEX=ON
 - Hardware FlySky Nirvana / NV14 and T16. Probably existing issue on other radios as well

**Comment by pfeerick** [comment]
Have you tried both options anyway to see if it is cosmetic only? i.e. is FCC 868Mhz and EU 915Mhz ? 

I see also that the S.Port link state/option message isn't being displayed either... i.e. as shown here... https://youtu.be/OgvgzPm6moE?t=210

**Comment by shellixyz** [comment]
@pfeerick It is definitely not only cosmetic. Flex should have options to push the power to 1W with telemetry but it is not possible. In any case it is not because Flex is enabled that it should render FCC and LBT modes unusable.

Today I also flash my T16 and the same problem here so it is not NV14 specific like I originally thought. I guess all radios or perhaps only Horus type radio are impacted

![IMG_20211108_221921](https://user-images.githubusercontent.com/4030264/140820093-52cdda8f-fb91-43a7-8911-d2278efc1094.jpg)

![IMG_20211108_221940](https://user-images.githubusercontent.com/4030264/140820219-633c727e-53ef-447f-8d04-9cd4b824b44f.jpg)

![IMG_20211108_221956](https://user-images.githubusercontent.com/4030264/140820231-0b665e0e-11e8-4dbf-bd23-a604fea2eede.jpg)

**Comment by raphaelcoeffic** [comment]
@shellixyz i was thinking about removing that option and just enabling it by default, what do you think?

**Comment by shellixyz** [comment]
> @shellixyz i was thinking about removing that option and just enabling it by default, what do you think?

Sounds good to me. I wonder why it was made an option back when it was introduced

**Comment by raphaelcoeffic** [comment]
> > @shellixyz i was thinking about removing that option and just enabling it by default, what do you think?
> 
> Sounds good to me. I wonder why it was made an option back when it was introduced

Probably for radios shipped by FrSky to be compliant with some regulations. However, it all depends on the firmware installed on the module, so why bother?

**Comment by shellixyz** [comment]
> > > @shellixyz i was thinking about removing that option and just enabling it by default, what do you think?
> > 
> > 
> > Sounds good to me. I wonder why it was made an option back when it was introduced
> 
> Probably for radios shipped by FrSky to be compliant with some regulations. However, it all depends on the firmware installed on the module, so why bother?

Indeed must be the reason and since they don't ship their modules / radios with FLEX firmware it doesn't matter
