### ISSUE TITLE
Trainer inputs extended to 8 channels for FPV headtracking transmission

### ISSUE THREAD

**Issue by johaninpika** [EdgeTX/edgetx#1016]
i m using googles with headtracking supported over usb output. i make RaspberiPI based translator to ch5 and ch6   to JR connector. Now I realize only 1 to 4 channels available. Can someone add option to read more channels on trainer lnput, please. Using Nirvana radio and finaly edgetx has this great promise to move further some projects...

any other option, maybe over usb input??
best regards and thanks

**Comment by raphaelcoeffic** [comment]
No, you can use TRx inputs into sources and mixers. The first 4 channels are a bit more convenient to use, as it covers the most “normal” use case.

**Comment by gagarinlg** [comment]
closed, because it is possible to use more than 4 channels
