### ISSUE TITLE
User interface: pages don´t snap in using touch

### ISSUE THREAD

**Issue by 3DRacer** [EdgeTX/edgetx#1017]
**Describe the bug**
If you have set several pages (mainview 1, mainview 2, ....) in the user interface, the individual pages are no longer self centered when using the horizontal swipe. 

**To Reproduce**
set more than one page in user interface. Swipe through the pages using touchscreen. The view stops also between pages.

**Expected behavior**
every page should snap in whole view when the screen is not touched.

**General information**
 - EdgeTX version 2.6.0 3ad98ba (every Version since 07.11.2021)
 - Hardware RM TX16S

**Comment by pfeerick** [comment]
Thanks for the report. This will be fixed when https://github.com/EdgeTX/libopenui/commit/80fdba6afad87cb3aa4607f74b551e59372d6599 is used, it just hasn't been bumped yet.
