### ISSUE TITLE
Missing LUA constants for condition-types (function-types) of Logical Switches

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1020]
If one uses model.getLogicalSwitch() or model.setLogicalSwitch() there are no LUA constants for e.g. "a>x" as the function-type in the table. One has to use the "magic-value" 3 for e.g. "a>x".

Introduce some LUA-constants like

LSFUNC_SRC_GT_VALUE,
...
LSFUNC_STICKY,

for this.

**Comment by jfrickmann** [comment]
OK, added in #1223

**Comment by philmoz** [comment]
Can this be closed?

**Comment by jfrickmann** [comment]
Yes
