### ISSUE TITLE
x9d+ gimbals stop working 

### ISSUE THREAD

**Issue by bigrip** [EdgeTX/edgetx#1024]
hi first i flashed the wrong bootlader x9d+ 2019 instead of x9d+,
then i flashed the x9d+ bootlader and installed edgetx but my gimbals are not longer working.
then i flashed open tx but my gimbals are no longer working.
pls help me to get my radio working again

**Comment by raphaelcoeffic** [comment]
Have you tried to re-calibrate the gimbals?

**Comment by bigrip** [comment]
the radio is not responding to gimbal input or button´s , trimm buttons work.

**Comment by raphaelcoeffic** [comment]
> the radio is not responding to gimbal input or button´s , trimm buttons work.

You have most probably still the wrong target installed. If the menu / page / + / - don't work, this is the most probably cause. Please join us at our Discord server so we can sort it out with you.
