### ISSUE TITLE
Model templates

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#1026]
Wouldn’t be cool to be able to have some model templates including screen / widget settings? 

These could be defined in YAML easily now, and stored in a special directory, so that it would init the model with everything included there.

**Comment by pfeerick** [comment]
That is something I missed from OTX 2.1 days on B&W... there was a mix templates screen... don't know why colourlcd have never had that sort of option.

**Comment by pfeerick** [comment]
Similar: #351

**Comment by gagarinlg** [comment]
This is implemented with model templates, right?

**Comment by pfeerick** [comment]
Yes. There is a second part to this, but it'll be a while before that sees the light of day. 😆
