### ISSUE TITLE
Jumper t12 . If disconnect battery when radio is on , system not boot 

### ISSUE THREAD

**Issue by trnnwnnhe** [EdgeTX/edgetx#1028]
If disconnect battery when radio is on , system not boot ,
Jumper t12 ( flashed via dfu) https://youtu.be/0Y7hlngz83k

EdgeTX version 2.5.0 
 jumper t12

**Comment by pfeerick** [comment]
I believe this is a duplicate of https://github.com/EdgeTX/edgetx/issues/794 but is triggered a different way.

**Comment by raphaelcoeffic** [comment]
I tried a couple of times, does not seem to happen anymore on 2.8.0-rc3
