### ISSUE TITLE
Hardware analog input as switches

### ISSUE THREAD

**Issue by JyeSmith** [EdgeTX/edgetx#1030]
Is it possible to have the Hardware option to make sliders/pots any of the available switch options e.g. toggle, 2, or 3 position?

Sliders and pot options could also share the same Hardware options since they are just analog inputs e.g. either can be slider, pot, multiswitch.

Making the hardware more generic will allow users to mod handsets and abuse various inputs for other means... Like me who put a switch on the slider input because I had a plug that fit 😄 

Cheers

**Comment by raphaelcoeffic** [comment]
@JyeSmith hehe, looks like you're finally getting that feature ;-)

**Comment by JyeSmith** [comment]
Woohoo!  Thanks mate.

That'll make it easier throwing away useless sliders and replacing them with switches 😄
