### ISSUE TITLE
Preflight Checklist Switch Positions are not saved

### ISSUE THREAD

**Issue by PSi86** [EdgeTX/edgetx#1036]
On the model setup page under section "Preflight Checklist" you can select which switches should be checked by the radio.
Also the switch positions can be saved, but this is not happening.

**To Reproduce**
-Set switches to desired positions
-Go to Model Setup
-Scroll to the Switch Positions and activate the item (click the wheel).
-Scroll left to select all switches and click again.
-The arrows next to the switches now reflect the current positions of each.
-Exit the menu
-Load another model from Model List (or reboot radio)
-Go back to the model where you did the change.
-Check the preflight checklist switch postions - they are reset back to default.

**Expected behavior**
The switch positions should be saved to the model and retained on model change or reboot.

**Screenshots**
![screen-2021-11-12-141613](https://user-images.githubusercontent.com/5648573/141535091-36d8de43-ecc9-49b8-88f5-2e95bac9c4b2.png)

**General information**
 - nightly b4903d8
 - Frsky X9D+ 2019 (Access Version)

**Comment by PSi86** [comment]
Wow, this was quick! Will test with the next nightly once the commit is merged and report back here.

**Comment by raphaelcoeffic** [comment]
> Wow, this was quick! Will test with the next nightly once the commit is merged and report back here.

Normally we test *before* we merge. This is in fact a condition ;-)

**Comment by PSi86** [comment]
Will you supply a build for testing?

**Comment by raphaelcoeffic** [comment]
> Will you supply a build for testing?

It's in the PR. Head to "Checks", then you should see "Artifacts" at the bottom of the page.

**Comment by PSi86** [comment]
Thank you, that was NOT easy to find :)
Testing is done -> works almost perfectly.
What does this mean?
After installing the build all switch position checks were disabled in all models.
You then have to re-enable every single switch by clicking on each one and then again select all of them and click to store all current switch positions like you normally would.
I did not test the behaviour when models are converted from opentx but coming from an older EdgeTX version it would be better to have all switch checks in the default positions rather than having all checks disabled.

![screen-2021-11-13-182121](https://user-images.githubusercontent.com/5648573/141653227-22292bdc-2d17-41e5-ad17-174ad4bbdec7.png)

What do you think?

**Comment by raphaelcoeffic** [comment]
The problem here is that indeed, the positions were stored the wrong way. So your files were already borked. I tested the conversion from OTX and from ETX 2.5 and they seem fine.

**Comment by PSi86** [comment]
Ok, then: Case closed! Nice work!

**Comment by raphaelcoeffic** [comment]
@PSi86 issue are closed automatically when the code is merged ;-) we need @pfeerick to give it a hard time first 😋
