### ISSUE TITLE
NV14 Curves window when trying to set a value, CV1, crashes the transmitter, restart required

### ISSUE THREAD

**Issue by Outwide** [EdgeTX/edgetx#1045]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - EdgeTX version (e.g. 2.4.0 or nightly and #commit number)
 - Hardware (e.g. Frsky X9D+ or RM TX12S)

**Comment by Outwide** [comment]
NV14 Setting Curve values in the main window. Smooth selected, In Type field change Standard to Custom the screen fades away and no visible screen available, restart required. Edge TX 2.5

After restarting go back to the Curve values in the main window. Smooth selected, In Type field, press 5pts. New window showing Curve to be adjusted opens. Press anything in the adjustment field at the bottom and transmitter crashes, screen fades away again and no visible screen available, restart required. Pictures attached. 
![Picture 01](https://user-images.githubusercontent.com/89946386/141661914-e91c0ee9-7086-495a-81f3-b33076d8c3cd.jpg)
![Picture 02](https://user-images.githubusercontent.com/89946386/141661915-ef70fc29-af63-4f49-af19-b29758a48f9a.jpg)
![Picture 03](https://user-images.githubusercontent.com/89946386/141661918-e60c1d57-14b2-499e-a6bd-e5cb1601eb58.jpg)

![Picture 04](https://user-images.githubusercontent.com/89946386/141661919-ec8d676b-77da-440b-b74e-10c75704a87c.jpg)
![Picture 05](https://user-images.githubusercontent.com/89946386/141661921-038bb4d4-f85b-402c-b027-937c08e05f33.jpg)

**Comment by pfeerick** [comment]
This was fixed in the nighties about two weeks ago ;) https://github.com/EdgeTX/edgetx/pull/965

**Comment by Outwide** [comment]
I installed Edge TX 2.5 it yesterday afternoon.
I will do another clean install.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by pfeerick** [comment]
You will either have to run a nightly, or wait for 2.6.0.
