### ISSUE TITLE
Receiver ID wont show warning.

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [EdgeTX/edgetx#1052]
When we bind a new model, the receiver ID always starts from 0, unlike OpenTx, EdgeTx won't make a warning of an ID, if already being used, which makes it very easy to overwrite the old model receiver ID. Please solve it.

**General information**
 - EdgeTX version: 2.5.
 - Hardware: RM TX16S)

**Comment by pfeerick** [comment]
Duplicate of #1053
