### ISSUE TITLE
Backround garbage when wallpaper not screen resolution

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#1058]
When background.png is not 320x480 size garbage from previous screens are still displayed

![screen-2021-11-15-110211](https://user-images.githubusercontent.com/46420768/141758800-893658fe-0347-437b-aeb0-03b269d6bd45.png)

**Expected behavior**
Clear background with background theme color

 - EdgeTX version 2.6.0 nightly
 - Hardware NV14

**Comment by pfeerick** [comment]
I just renamed this is it's not NV14 specific - affects the TX16S if you apply a NV14 aspect ratio wallpaper to it. And thank you for identifying the bug that has been annoying me for around two weeks now with `simu` and NV14 as I've had this display garbage for a while now and couldn't place it! :)
