### ISSUE TITLE
Leaving Color theme editor with RTN does not show the yes(no dialog properly

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1064]
RTN is misbaving here: RTN-down shows the save dalog, RTN-release dismissis it without a chance to select the "Enter" option immediately.

Tested on simulator.

**Comment by pfeerick** [comment]
@kevinkoenig Was able to reproduce this on TX16s hardware also ;)

**Comment by kevinkoenig** [comment]
I will take a look. 

Sent from Mail for Windows
