### ISSUE TITLE
Make the internal model number as used in model00.bin or model01.yml usable in LUA

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1065]
Add a field model.getInfo().number that returns the number of the model used in building the .yml file

**Comment by wimalopaan** [comment]
Maybe there is more useful information one needs in lua scripts. But the model-number is quite crucial to generate filenames that are unique on the sd-card (like the model-files model<number>.yml)

**Comment by pfeerick** [comment]
I'm going to have a stab at this ... so would adding it as another return value for `model.getInfo()` be acceptable? Currently it returns the model name, and bitmap path... so seems like adding `modelId` as a third value is a good fit. 

I *think* this should do it...
```
 lua_pushtablenstring(L, "modelId", g_model.header.modelId);
```

**Comment by wimalopaan** [comment]
Well, I saw this in the sources, but the comments say this is the receiver number ...

**Comment by wimalopaan** [comment]
Maybe:

lua_pushtablenstring(L, "modelIfilename", g_model.header.modelFilename);

**Comment by raphaelcoeffic** [comment]
This is what you are looking for: `g_eeGeneral.currModel`.

**Comment by pfeerick** [comment]
Well, we can do the filename anyway, since it's 'model related'. Thank you for that hint re: `g_eeGeneral.currModel` ;)
