### ISSUE TITLE
Re-arrange models in the model select screen

### ISSUE THREAD

**Issue by knobbytrav** [EdgeTX/edgetx#1071]
Just looking for a way to re-arrange the models in the model select screen.  I don't see a way to do it other than creating a new folder and moving stuff back and forth....

AWESOME project, BTW....  I love this so much more than openTX in so many ways!

**Comment by dlktdr** [comment]
As of right now the only other way than what you mentioned is by rearranging them by hand editing the SDcard file RADIO/models.txt OR RADIO/models.yml. Depending on the version you are running. Recent nightly will be a .yml file.

Planned on for the new Model Select Screen. Also see #956
