### ISSUE TITLE
After the last change to libopenui scroll "inertia" feature is lost

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#1077]
**Describe the bug**
When scrolling the window, the motion stops immediately when the finger motion is stopped.

**To Reproduce**
Open Model Setup window and scroll to the bottom.
The scrolling stops when the finger is removed from the screen.

**Expected behavior**
"Inertia" was a very nice feature.

**General information**
 - EdgeTX current code
 - Hardware  RM TX16S

**Comment by gagarinlg** [comment]
this should be fixed with [https://github.com/EdgeTX/libopenui/pull/37](url)

**Comment by pfeerick** [comment]
I'm not sure yet this is 100% resolved, as inertia does seem to be back, it is still a bit *latchy*, but we'll see what others think at the next nightly...

**Comment by eshifri** [comment]
I think it used to be more convenient.
