### ISSUE TITLE
RM TX16s Initial convert to yaml LS and RS Calibration missing

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#1083]
**Describe the bug**
After updating to a version that uses yaml, LS and RS calibration was invalid.

**To Reproduce**
Start with binary model and radio files, have the RM TX16s do the SD Card conversion on startup. Check the LS and RS data in analog screen.

**Expected behavior**
LS and RS should be calibrated as they were before the SD Card upgrade.

After redoing the calibration and comparing the original converted yaml file to the yaml file after recalibration, LS and RS is clearly missing from the yaml file (on the left SD Card converted version, on the right, after recalibration):
![image](https://user-images.githubusercontent.com/485436/142594209-7a3fbfae-2f55-4739-84c6-a4c7ae56d89c.png)

**General information**
 - EdgeTX #8f55fb0f
 - RM TX16s

**Comment by onki69** [comment]
I have a similar problem. I can't even calibrate properly.
The lower part of the throw (-100 to 0) is completely missing.
Is this caused by this bug?
I can't find a way to get LS and RS back to full throw.

**Comment by NemesisXB** [comment]
> I have a similar problem. I can't even calibrate properly. The lower part of the throw (-100 to 0) is completely missing. Is this caused by this bug? I can't find a way to get LS and RS back to full throw.

Sounds like a different problem. Mine calibrated without issue.
