### ISSUE TITLE
Curve edit not working

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#1087]
**Describe the bug**
When accessing a curve through inputs tab, by editing an input with a curve attached and long pressing on the curve name, it opens the curve edit screen. Using the scroll wheel to edit the curve works, but using the popup keyboard that shows the << - + >> etc, If you click any of the items on the keyboard, the keyboard just closes and no change is made to the value.

**To Reproduce**

1. Go to the inputs tab.
2. Edit one of the inputs.
3. For curve, select cstm, and select a curve.
4. Long press on the curve name
5. Try to edit the curve data using the popup keyboard

**Expected behavior**
The keyboard should edit the value just like when editing the curve from the curves tab

**General information**
 - EdgeTX #8f55fb0f
 - RM TX16s

**Comment by pfeerick** [comment]
This is a change in behaviour from 2.5
