### ISSUE TITLE
Widget is stuck in full screen

### ISSUE THREAD

**Issue by oleg-sherman** [EdgeTX/edgetx#1091]
### Description
When users enters full screen for a single value widget, it is stuck in full screen, and the only way to go back is to turn off/on the radio.

### Steps to reproduce
1. Set single value telemetry
2. Open it in full screen
3. Can't get back from full screen

### Expected behavior
The user should be able to go back from full screen

### Workaround
Turn off and on the radio

### General information
 - EdgeTX version 2.5.0
 - Hardware TX16s

**Comment by NemesisXB** [comment]
Have you tried long pressing the RTN button?

**Comment by oleg-sherman** [comment]
Yep, that solves it, IMO long press is less intuitive, maybe changing it to regular press will be better...

**Comment by pfeerick** [comment]
Long RTN is used to exit both standalone scripts and fullscreen widgets, leaving a short RTN press for use within the app.
