### ISSUE TITLE
Top bar widgets update slower than reset of screen

### ISSUE THREAD

**Issue by oleg-sherman** [EdgeTX/edgetx#1096]
### Problem
Gauge widget is updated with delay, see the red gauge on the top bar:
 
![Untitled](https://user-images.githubusercontent.com/37136160/142720804-0abc3e42-c63f-48f9-b525-f2c3967c5b3e.gif)

**Comment by pfeerick** [comment]
It is not specific to the gauge widget - the top bar updates less frequently then the rest of the UI. There are no immediate plans to change the update speed of the top bar. Any fast updating widgets should be in the main display area.

**Comment by oleg-sherman** [comment]
Got it ,so maybe convert to enhancement.
