### ISSUE TITLE
NV14 UI scalable

### ISSUE THREAD

**Issue by nightflasher** [EdgeTX/edgetx#1098]
The current nightly of edgeTX is nice and seems to work well, but the UI is quite small and maybe you could import the sizes from openTX builds. Maybe you could make the UI scalable so the user can resize to his needs.
Sometimes the tick-boxes are too close/small to precisely change their values behavior (pre flight check, or telemetry screen).

**Comment by pfeerick** [comment]
I believe #980 touches on this, but more work on UI for NV14 is certainly needed

**Comment by gagarinlg** [comment]
This is coverd by the LVGL based UI
