### ISSUE TITLE
mixer setup - unvisible mixers - curve setting blocks other settings

### ISSUE THREAD

**Issue by lombartz** [EdgeTX/edgetx#1100]
- [x] Invisible mixers:

- setup some mixers in the mixers tab
- go to the first mixer and set the source to --- (none)

after that mixer 1 is not editable or deletable anymore and all the other mixers seem to be empty but they are not. They are just not visible, editable and deletable in the radio but in companion they are. If you define new mixers the unvisible mixers stay active and you cannot change that without companion. This leads to a incomprehensible behavior.

- [x] curve setting blocks other settings:

- enter mixer edit
- ad some expo or do anything other with the curve setting
- leave the mixer editing

after that mixer name is gone as well as all other settings wich are stored after the curve settings in the model.yml. 

TX16S Hall, latest nightly

**Comment by pfeerick** [comment]
> but in companion they are

This is a bit of a red herring, as if you are using latest nightly, radio firmware is using yaml to save settings, but Companion is reading and writing to the (older) bin files as it doesn't have support for yaml yet.

After setting a channel source, it looks like the row for it basically collapses to nothing - just a one pixel line for it and you can't select it. It looks like 2.5.0 is affected by this also, so yaml is innocent this time ;) This also seems to be specific to CH1 - i.e. doing the same to CH3 behaves just fine.
