### ISSUE TITLE
Include MPM protocol header when MPM is forwarded over a "Telem Mirror" serial port

### ISSUE THREAD

**Issue by stronnag** [EdgeTX/edgetx#1104]
The MPM telemetry protocol defines a two byte "protocol" header `M`. `P` to facilitate identification / demarcation of MPM telemetry packets. https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/acd8379077ed25a81e45d054c9e1ee2de0996874/Multiprotocol/Multiprotocol.h#L1168

When a serial port is used as a MPM "Telem Mirror", these two protocol / packet bytes are not included. This makes it harder to (a) auto-detect the stream type and (b) split the stream into packets.

Example of recorded data stream:

* The packet starts at offset 1 (02, 09) Frsky S-Port data.
* At offset 0x135 there is a Multimodule Status packet

Due to the unexceptional binary stream, it would be much easier to parse if the header were intact. 

Please consider including these these two header bytes in the mirrored stream in accordance with the [specification  above](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/acd8379077ed25a81e45d054c9e1ee2de0996874/Multiprotocol/Multiprotocol.h#L1168).

```
|00000000│ 00 02 09 1b 10 00 08 00 ┊ 00 00 00 e7 02 09 1b 10 │0•_••0•0┊000×•_••│
│00000010│ 00 08 00 00 00 80 67 02 ┊ 09 1b 10 10 01 de ff ff │0•000×g•┊_••••×××│
│00000020│ ff 00 02 09 ba 10 00 f0 ┊ 00 00 00 00 fe 02 09 1b │×0•_×•0×┊0000×•_•│
│00000030│ 10 40 08 aa 00 00 00 fc ┊ 02 09 1b 10 50 04 00 00 │•@•×000×┊•_••P•00│
│00000040│ 00 00 9b 02 09 1b 10 00 ┊ 07 fb ff ff ff ec 02 09 │00×•_••0┊•×××××•_│
│00000050│ 1b 10 10 07 f7 ff ff ff ┊ e0 02 09 ba 10 00 f0 00 │••••××××┊×•_×•0×0│
│00000060│ 00 00 00 fe 02 09 1b 10 ┊ 20 07 61 00 00 00 67 02 │000×•_••┊ •a000g•│
│00000070│ 09 1b 10 00 04 02 00 00 ┊ 00 e9 02 09 1b 10 10 04 │_••0••00┊0×•_••••│
│00000080│ 00 00 00 00 db 02 09 1b ┊ 10 20 04 00 00 00 00 cb │0000×•_•┊• •0000×│
│00000090│ 02 09 98 10 05 f1 02 23 ┊ 0f 00 c4 02 09 98 10 01 │•_×••×•#┊•0×•_×••│
│000000a0│ f1 51 e9 00 64 5d 02 09 ┊ 1b 10 20 08 5c f9 ff ff │×Q×0d]•_┊•• •\×××│
│000000b0│ 71 02 09 98 10 04 f1 01 ┊ 00 00 00 f8 02 09 ba 10 │q•_×••×•┊000×•_×•│
│000000c0│ 00 f0 00 00 00 00 fe 02 ┊ 09 1b 10 10 09 6a 01 00 │0×0000×•┊_•••_j•0│
│000000d0│ 00 6b 02 09 1b 10 60 04 ┊ 08 07 00 00 7c 02 09 1b │0k•_••`•┊••00|•_•│
│000000e0│ 10 30 08 00 00 00 00 b7 ┊ 02 09 1b 10 10 02 3f 04 │•0•0000×┊•_••••?•│
│000000f0│ 00 00 9a 02 09 1b 10 00 ┊ 02 00 00 00 00 ed 02 09 │00×•_••0┊•0000×•_│
│00000100│ ba 10 00 f0 00 00 00 00 ┊ fe 02 09 1b 10 00 01 00 │×•0×0000┊×•_••0•0│
│00000110│ 00 00 00 ee 02 09 1b 10 ┊ 00 06 2f 00 00 00 ba 02 │000×•_••┊0•/000×•│
│00000120│ 09 1b 10 00 08 00 00 00 ┊ 00 e7 02 09 1b 10 00 08 │_••0•000┊0×•_••0•│
│00000130│ 00 00 00 80 67 01 18 27 ┊ 01 03 03 00 e4 43 0f 46 │000×g••'┊•••0×C•F│
│00000140│ 72 53 6b 79 58 32 26 44 ┊ 31 36 00 20 20 20 00 02 │rSkyX2&D┊160   0•│
│00000150│ 09
```

**Comment by raphaelcoeffic** [comment]
Thx! This makes sense to me as well. We should possibly move to really just mirror the port instead of trying to be smart 😅
