### ISSUE TITLE
LUA functions not working properly

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#112]
**Describe the bug**
Tested four LUA functions
- getFieldInfo()
- getValue()
in conjunction with telemetry fields reading
also
- lcd.drawSwitch()
- lcd.drawSource()

**Screenshots**
Here is a test run
https://www.youtube.com/watch?v=w4Pv1VlF_M8

**General information**
EdgeTX version: e903a88f
Radio: RM TX16S

**Comment by raphaelcoeffic** [comment]
Your tool looks really good for testing! Can I have it please?

**Comment by raphaelcoeffic** [comment]
@JimB40 this one should fixed as well, with the code in 2.4, and my latest PR for the sensors.
