### ISSUE TITLE
Editing Curves on "Inputs"-Screen

### ISSUE THREAD

**Issue by notyourbiz** [EdgeTX/edgetx#1120]
*Before submitting,  search the open issue if there is already a report of the bug*
i did

**Describe the bug**
When trying to edit a preset Curve on "Input"-sereen, the editor field dissapears by pressing << / - / + / >>

**To Reproduce**
Edit a preset Curve on "Input"-Screen

**Expected behavior**
working function

**Screenshots**
N/A

**General information**
 - EdgeTX version 2.5 / 2.6
 - Hardware TX16S

**Comment by pfeerick** [comment]
Thanks for the report. Duplicate of #1087

**Comment by pfeerick** [comment]
Duplicate of #1087
