### ISSUE TITLE
Switch-State Tracks on Startup

### ISSUE THREAD

**Issue by notyourbiz** [EdgeTX/edgetx#1121]
**Is your feature request related to a problem? Please describe.**
Just my Ears... ;-)

**Describe the solution you'd like**
Selecable if Switch_State Tracks should be played on Startup or not

**Comment by raphaelcoeffic** [comment]
What do you mean actually with switch-state tracks? Are these the “play” functions set up in “special functions”?

**Comment by notyourbiz** [comment]
exactly...

could be a little annoying if the radio tells u every startup the actual state of every switch... i love to hear a track, if i change a switch-state, but not on startup for all switches...

**Comment by raphaelcoeffic** [comment]
Some do like it to know the state of the model switches before they turn it on. It’s probably a matter of taste.

**Comment by notyourbiz** [comment]
of course... thats why i suggested selectable...

somewhere in the Radio-Settings a checkbox [yes] [no] [maybe] ;-)

so anybody can choose...

**Comment by raphaelcoeffic** [comment]
> of course... thats why i suggested selectable...
> 
> somewhere in the Radio-Settings a checkbox [yes] [no] [maybe] ;-)
> 
> so anybody can choose...

Curious to know what you figured should happen with “maybe” 😅

**Comment by notyourbiz** [comment]
[maybe] is a future feature, like release 3.x, when its "really" talking to you...

Radio on startup: "hey, wanna hear the switches?"
You: "shut up, get me some coffee and start the planes engine..."

or so... :-)

**Comment by pfeerick** [comment]
There is a ! condition in the play track special function you can use, so that switch state is *not* played at startup. i.e. I have audio set up on four switches I regularly use (i.e. arming, modes switch 1, modes switch 2, gps modes, flip recovery, etc), and only some of those will talk at startup.

**Comment by notyourbiz** [comment]
@pfeerick: you really made my day!!! Awsome, thats what i was looking for... even better than my suggestion...

THX

**Comment by pfeerick** [comment]
No problem! Glad to help :)
