### ISSUE TITLE
"Welcome to EdgeTx" sound bug

### ISSUE THREAD

**Issue by MiroslavFPV** [EdgeTX/edgetx#1137]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**
A clear and concise description of what the bug is
"Welcome to EdgeTx" sound is played after "Throttle warning" and "Switch warning"

**To Reproduce**

**Expected behavior**
Play "Welcome to EdgeTx" first. At boot screen.
**Screenshots**

**General information**
 - EdgeTX version (e.g. 2.4.0 or nightly and #commit number)
 - Hardware (e.g. Frsky X9D+ or RM TX12S)
Version 2.5.0. Radiomaster TX16S.

**Comment by pfeerick** [comment]
Duplicate of #135
