### ISSUE TITLE
TX16S TQly and TRSS telemetry missing

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#1139]
I noticed that the TQly and TRSS telemetry sensors were suddenly dead in my models using FrSkyX2 D16 the last couple of days. I confirmed that something changed after Nov 20th because I flashed to a bin I compiled on the 20th and they are working again. Flashed back to a current nightly and they stop working again.

**Comment by eshifri** [comment]
Can you please try to run sensors rediscovery?

**Comment by rburrow87** [comment]
I should have mentioned, I did try deleting sensors and re-doing sensor discovery and they would not come back without flashing the firmware.

**Comment by pfeerick** [comment]
Thank you both... I meant to ask that yesterday. Ok, I'll try this locally - I got half-way there before getting distracted.... but something has probably changed in yaml to trip this up.

**Comment by eshifri** [comment]
There were also some changes in modules and telemetry. I have briefly looked into it and had not found anything suspicious, but...

**Comment by rburrow87** [comment]
This may be another clue. I was messing around with it more and I noticed that on the "good" build, if I'm using the internal multi module and I set the external module to something like CRSF and leave the internal on, TQly and TRSS break again.

**Comment by pfeerick** [comment]
Right, so binding an X8R via MPM on TX16S with todays nightly only yielded this:
![image](https://user-images.githubusercontent.com/5500713/143525642-0925691a-4f92-4dbe-89db-261ee2737fae.png)

Rolling back to 2.5.0, and configuring the MPM/rediscovering sensors yielded:

![image](https://user-images.githubusercontent.com/5500713/143525940-3dbb1965-c9d2-41d5-8c00-86ce89765118.png)

**Comment by koaxheli** [comment]
Has not changed anything in the telemetry to date.
TRSS and TQly still not recognized.
![screenshot_tx16s_21-12-19_17-46-39](https://user-images.githubusercontent.com/92114465/146683500-1ccd3130-b35b-4ab8-a5dc-ddfc219f9763.png)

**Comment by pfeerick** [comment]
I wonder if this is related to #1039 as that was from just around then.

**Comment by rburrow87** [comment]
I just noticed today, if I use an external multi module (Jumper JP4IN1 v1.3.3.0), they come back and work with the external module.

**Comment by raphaelcoeffic** [comment]
@rburrow87 Can you please confirm / infirm whether 1) this still happens, and 2) if this is only with the internal ISRM and/or MPM?

**Comment by rburrow87** [comment]
Checked with 2.7 nightly 7da7261e on my TX16S and it's still happening with the internal Multi. I've only seen these sensors with the MPM, not with the ISRM.

If I set the external RF to Multi, they start working again even if the RX is only connected to the internal module.

**Comment by pfeerick** [comment]
This gels with my earlier comment re external RF setting also messing with those sensors on 2.5, so it seems like we have a long-running issue that has been recently exacerbated.

**Comment by richardclli** [comment]
I have a friend used the RM receiver R161, and used the S.Port to send back telemetry, the included figures are from OpenTX 2.3.9 and compared to EdgeTX 2.6, EdgeTX has a lot of sensors missing.  And he tried EdgeTX 2.5.0 as well.  Similar result, a lot of sensors missing.

I am thinking if the Frsky Hub telemetry is broken from day 1 in the OpenTX 2.4 branch?  Maybe we need to compare the current OpenTX sources to see what happens.

![-4048e160eaeaaac9](https://user-images.githubusercontent.com/18414861/150479170-657feebf-b954-41b6-b819-a42f38874ab4.jpg)
![-6005bf5be15936e7](https://user-images.githubusercontent.com/18414861/150479177-9796f2f6-9d99-488e-8436-d4792f0848f0.jpg)

**Comment by raphaelcoeffic** [comment]
@richardclli how is the R161 connected? We don’t poll the sensors, it’s the module’s job.

**Comment by pfeerick** [comment]
Hm... I wonder if this has connection in some way... https://github.com/EdgeTX/edgetx/issues/1260
