### ISSUE TITLE
TBSAgentLite.lua Does Not Run

### ISSUE THREAD

**Issue by vileperson** [EdgeTX/edgetx#114]
**Describe the bug**
TBSAgentLite.lua fails to run on Jumper T16. It simply displays a "graphical glitch" type of screen. I am able to back out of it by long pressing RTN

**To Reproduce**
1. Load TBS Agent Light lua script and folder to SD Card per TBS instructions here. https://www.team-blacksheep.com/products/prod:agentx
2. Go to 'SDCARD'
3. Click on 'SCRIPTS', 'TOOLS'
4. Scroll down to 'TBSAgentLite.lua.'
5. Long press enter (scroll wheel), and select EXECUTE.
6. See graphic loading issue

**Expected behavior**
should load the main menu for the Agent Lite script

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/25247569/119982566-00d22c80-bf8d-11eb-9439-b5fe397f2297.jpg)

**General information**
 - t16-64330e3.bin
 - Jumper T16
 - TBS Agent Lite

**Comment by raphaelcoeffic** [comment]
@vileperson this will require the source code of the app, which I don't have right now. Need to get TBS approval first....

**Comment by raphaelcoeffic** [comment]
Ok, no approval from TBS, which means, it is TBS to fix it ;-)

From what I have seen so far, what is seen on the screen is basically the content of the LUA back-buffer, in which LUA routines draw before it gets copied to the real LCD buffer. This means that the script neither clears nor draws anything at this point.

**Comment by tbs-trappy** [comment]
We are looking into this on our end and will release a new revision from Agent Lite as soon as possible. thanks for reporting this bug!

**Comment by raphaelcoeffic** [comment]
> We are looking into this on our end and will release a new revision from Agent Lite as soon as possible. thanks for reporting this bug!

I would rather prefer have an explaination as to why it does not work, so I can fix in EdgeTX. The goal here is to have Apps compatible with OTX 2.3 work in EdgeTX without any modifications.

**Comment by tbs-trappy** [comment]
> I would rather prefer have an explaination as to why it does not work, so I can fix in EdgeTX. The goal here is to have Apps compatible with OTX 2.3 work in EdgeTX without any modifications.

Yes, will post our findings here. Right now we're just getting ready to reproduce the problem :)

**Comment by JimB40** [comment]
I've checked on T16 simulator and no trace of error.
Can you check if you have latest TBS AL build?
Open TBSAgentLite.lua from /SCRIPTS/TOOLS/ folder and chek for this line:

local run = loadScript('loader.lua','bt')('0.91')

**Comment by vileperson** [comment]
> I've checked on T16 simulator and no trace of error.
> Can you check if you have latest TBS AL build?
> Open TBSAgentLite.lua from /SCRIPTS/TOOLS/ folder and chek for this line:
> 
> local run = loadScript('loader.lua','bt')('0.91')

Yes, that line is the same in my version. I had pulled the latest AL before reporting the bug, just to be sure.

**Comment by JimB40** [comment]
Can you test again against latest build? @raphaelcoeffic pushed lot of LUA improvements lastly.
If bug persist we'll be tracing further.
Btw so far there is another bug that prevents communication LUA<->CRSF module but UI should load without glitch

**Comment by vileperson** [comment]
> Can you test again against latest build? @raphaelcoeffic pushed lot of LUA improvements lastly.
> If bug persist we'll be tracing further.
> Btw so far there is another bug that prevents communication LUA<->CRSF module but UI should load without glitch. Don't pay attention to colors as color indexes are under dev.
> ![image](https://user-images.githubusercontent.com/46420768/120238733-141b1b80-c25d-11eb-856e-37c45731077f.png)

same issue with the latest build...
![unnamed (1)](https://user-images.githubusercontent.com/25247569/120240573-e919d300-c22e-11eb-9c03-0d1197efaab3.jpg)
 It looks as though the T16 is trying to load the EdgeTX bootloader graphic for some reason, instead of the TBS AL graphic.

**Comment by raphaelcoeffic** [comment]
> It looks as though the T16 is trying to load the EdgeTX bootloader graphic for some reason, instead of the TBS AL graphic.

what you see is empty but not wiped screen buffer. It contains the last image produced by LUA content. Try to load another working LUA script before.

**Comment by vileperson** [comment]
If I run the regular crossfire lua first, and then try to run agent lite, it displays the crossfire lua screen. So yeah. That's exactly what it's doing... displaying the previously loaded screen.

**Comment by raphaelcoeffic** [comment]
Please note that this is not specific to T16, I have the same on the TX16S.

**Comment by JimB40** [comment]
okay so in response to LUA:
local bg = lcd.RGB(230,230,230)
local txt = lcd.RGB(0,0,0)

OpenTX returns:
2021-06-15 14:06:48 debug bg: 59196
2021-06-15 14:06:48 debug txt: 0

While EdgeTX
2021-06-15 16:08:07 debug bg: nil
2021-06-15 16:08:07 debug txt: nil
2021-06-15 16:08:07 /SCRIPTS/TOOLS/TBSAGENTLITE/splash.lua:24: bad argument #2 to 'setColor' (number expected, got nil)

**Comment by raphaelcoeffic** [comment]
@JimB40 that is easy to fix! Wait a sec!

**Comment by raphaelcoeffic** [comment]
seems 60517df3496 fixes it.

**Comment by vileperson** [comment]
Fix confirmed with release candidate, here.
