### ISSUE TITLE
LUA table.* library for NV14

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#1141]
Seem like LUA table.* library was added long ago to HORUS tagrets (thx @jfrickmann for finding) even luadoc states is not.
https://github.com/opentx/opentx/pull/7599
Still doesnt work on NV14

Looked at code and seems to me it's here.
https://github.com/EdgeTX/edgetx/blob/78fc55c06d175d0b6716215d2ff50819c0064aca/radio/src/thirdparty/Lua/src/linit.c#L56

btw @raphaelcoeffic adding this to color radios only is about memory usage?

**Comment by pfeerick** [comment]
It would be about runtime memory *AND* firmware size

**Comment by JimB40** [comment]
Still with NV14 should be no issue I think.
And that's funny because it will make LUA more compact on targets with more memory:)

**Comment by raphaelcoeffic** [comment]
I think the `#if defined` can just changed to `COLORLCD` instead of just `HORUS`.
