### ISSUE TITLE
User interface: pages don´t snap in using touch

### ISSUE THREAD

**Issue by 3DRacer** [EdgeTX/edgetx#1153]
Describe the bug
If you have set several pages (mainview 1, mainview 2, ....) in the user interface, the individual pages are no longer self centered when using the horizontal swipe.

To Reproduce
set more than one page in user interface. Swipe through the pages using touchscreen. The view stops also between pages.

Expected behavior
every page should snap in whole view when the screen is not touched.

General information

    EdgeTX version 2.6.0 d775e75
    Hardware RM TX16S

**Comment by pfeerick** [comment]
@gagarinlg This is part of what I was meaning before with slide being more snappier than before, and inertia not being as smooth.

**Comment by gagarinlg** [comment]
> @gagarinlg This is part of what I was meaning before with slide being more snappier than before, and inertia not being as smooth.

I think I found it. I only have to check, if the fix affects the touch off when backlight is dimmed function.

**Comment by gagarinlg** [comment]
this is fixed by [libopenui #38](https://github.com/EdgeTX/libopenui/pull/38)
