### ISSUE TITLE
T12: compilation broken with -DCROSSFIRE=OFF

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1159]
With lastest main it is not possible to deconfigure CRSF (on T12, maybe others).

```
cmake -DUSB_SERIAL=OFF -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X7 -DPCBREV=T12 -DINTERNAL_MODULE_MULTI=OFF -DLUA=YES -DGVARS=YES -DGHOST=OFF -DAFHDS3=OFF -DCROSSFIRE=OFF -DOVERRIDE_CHANNEL_FUNCTION=OFF ..
```

gives

```
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp: In Funktion »void intmoduleSendNextFrame()«:
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:746:47: Fehler: »union InternalModulePulsesData« hat kein Element namens »crossfire«
746 |       intmoduleSendBuffer(intmodulePulsesData.crossfire.pulses,
|                                               ^~~~~~~~~
/home/lmeier/Projekte/edgetx/edgetx/radio/src/pulses/pulses.cpp:747:47: Fehler: »union InternalModulePulsesData« hat kein Element namens »crossfire«
747 |                           intmodulePulsesData.crossfire.length);

```

**Comment by raphaelcoeffic** [comment]
Ok, the issue is that by using `-DCROSSFIRE=OFF`, you assumed it would disable the capability for CRSF as internal module. But this is not how it works. However, it was not really configurable, which is why I made #1161.

**Comment by raphaelcoeffic** [comment]
@wimalopaan but what it is actually you are trying to achieve, when disable MULTI, CRSF, GHOST and AFHDS3? What is actually left?

**Comment by wimalopaan** [comment]
Well, I only need MPM, and that works (as external module).

**Comment by raphaelcoeffic** [comment]
> 

So no internal modules at all??? Do you have one these very old T12 without internal module?

**Comment by wimalopaan** [comment]
Excactly: Jumper T12

**Comment by wimalopaan** [comment]
Just tested only with `-DINTERNAL_MODULE_CRSF=OFF` and that is ok now.
