### ISSUE TITLE
Special Function newly selected lua script needs radio reset

### ISSUE THREAD

**Issue by happy12** [EdgeTX/edgetx#1178]
In a Special Function that uses Lua Script, when selecting a different lua script for an Action, it does not play the new lua script until the radio is reset.

**Expected behavior**
to play the new lua script without resetting the radio

**General information**
 - EdgeTX version 2.6.0 (22112de3)
 - Hardware TX16S

**Comment by pfeerick** [comment]
Are you able to give the linked PR a try? Unfortunately it was submitted during a github outage so github actions haven't generated a build for it.
