### ISSUE TITLE
X10/S: Antenna configuration options missing

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1185]
**Describe the bug**
On OpenTX, there was an option to configure the Antenna options in RADIO/SYS -> Hardware. Values ranged between Internal, Ask, Per Model, External. Defaulted to "Per Model". This is missing. 

If Per Model selected, there was an option under 'XJT' in the Model -> Internal RF section for Antenna, which allowed choice of Internal, Ask, External. It appears that this is missing also. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5500713/143763741-9840222c-f2ac-4e5b-98d8-932f13e1842c.png)
![image](https://user-images.githubusercontent.com/5500713/143763763-29ab6bd6-700a-422d-9544-f2fb75d26bec.png)

https://github.com/opentx/opentx/blob/ee96cf282ed65d66a25594a4f0bcdf30429d0fc2/radio/src/gui/480x272/radio_hardware.cpp#L352-L367

**General information**
 - EdgeTX version 2.6.0 nighties
 - Hardware: Frsky X10/S

**Comment by brainbubblersbest** [comment]
Same on x12s. The last thing missing in access integration on edgeTX. 🙂

**Comment by maxxam4** [comment]
will there be a solution in 2.7 Black Pearl? 

EdgeTX version 2.7.0 nighties
Hardware: Frsky X12S

**Comment by pfeerick** [comment]
Probably not. I was working on code for this though, so I'll see if I can find it again and see what I got stuck on...

**Comment by maxxam4** [comment]
Thanks for the information. It would be nice to be able to switch antennas for the open air season.

**Comment by GWguzzi** [comment]
But one question, what is the current setting, is the external antenna output switched off?
May be it is a problem if no external antenna is connected at the Horus 12S while the output is switched on!

**Comment by pfeerick** [comment]
The current setting would depend on what you set it to prior to using ETX... since the setting would be migrated across. 

It seems from what Companion is default to that it defaults to internal - but you can always read your transmitters current settings in Companion and check - the setting is still there, and Companion should read it. 

![image](https://user-images.githubusercontent.com/5500713/163976854-5458e8da-a256-405d-b78c-a372195ed55b.png)
