### ISSUE TITLE
Model notes doesn't shows model.txt

### ISSUE THREAD

**Issue by tonims1** [EdgeTX/edgetx#1198]
Since the implementation of yawl It doesn't show  .txt model. it shows .Model.yml
RM TX16S

Nightlies 2.6
![IMG_20211201_183011](https://user-images.githubusercontent.com/7953406/144285178-8cca8162-da05-47c3-899e-ace6052a91f1.jpg)

**Comment by eshifri** [comment]
I cannot reproduce it.
I assume you have checked the model6.txt or Ultron1.txt file is still present in the Models folder?

**Comment by tonims1** [comment]
Yes. in the models folder I have the .txt and .yml files. but when I click to read the txt model It read the yml model

**Comment by eshifri** [comment]
Can you please clarify?
If you go into the Radio Settings->SD card->Models, click model6.txt, select Read from the menu model6.yml file opens?

**Comment by tonims1** [comment]
no. if I go to Radio Settings-> SD card-> Models, click model6.txt It reads well. but if I do it from the main screen click model notes its show me the yml fi
![IMG_20211201_201532](https://user-images.githubusercontent.com/7953406/144299351-2dc1c99c-775c-4736-812c-28beae0b27d1.jpg)
le

**Comment by eshifri** [comment]
Aha. I still cannot reproduce it.
When you start the radio or change the model, do you see the same problem?
(Sorry for so many questions - I'm just trying to put my finger on the place in the code where the problem might be.)
It is all very strange since the text viewer does not consider yml to be a text format.

**Comment by tonims1** [comment]
Yes it happens in all models . when I want to read the model notes from the main screen always read model .yml

**Comment by eshifri** [comment]
My question was a little bit different: when you change the model and the modelX.txt file is present for a newly selected model, it should be displayed. Do you see the YML file in this case as well?

**Comment by tonims1** [comment]
yes

**Comment by tonims1** [comment]
https://user-images.githubusercontent.com/7953406/144309249-f4f4433c-65b0-4094-8fb7-7b9238f1aaf8.mp4

**Comment by eshifri** [comment]
Thank you! 
I know what the problem is. Will fix it shortly.

**Comment by tonims1** [comment]
Thank you for your attention
