### ISSUE TITLE
compiled in spanish have a line above 

### ISSUE THREAD

**Issue by tonims1** [EdgeTX/edgetx#1199]
compiled in Spanish all the text comes out with a line above it

RM TX16S

2.5 , 2.6
![IMG_20211201_205004](https://user-images.githubusercontent.com/7953406/144305904-ad456000-5864-425b-9ca2-4980a9644e68.jpg)
.
![IMG_20211201_205029](https://user-images.githubusercontent.com/7953406/144305929-1e7763de-eb4b-447a-824a-d579b9f20618.jpg)
![IMG_20211201_205119](https://user-images.githubusercontent.com/7953406/144305947-7ac080b0-42f9-49ba-a41a-3601ce1bec6f.jpg)

**Comment by richardclli** [comment]
Interesting, let me take a look first.

**Comment by raphaelcoeffic** [comment]
> Interesting, let me take a look first.

I could bet this has something to do with the generated font that might have some black parts in it (maybe while extending the height for some special character, or whatever).

**Comment by richardclli** [comment]
font_9, font_15, font_16, font_bold16 has problems, need to figure out why.

**Comment by richardclli** [comment]
The problem is due to some y_offset is negative (ES is the case).  What I did is whenever y_offset is -ve, I will try to enlarge the image first and offset the y_offset back to 0, so that the final crop will not cause a black line.
