### ISSUE TITLE
Top bar widget setup focus / segfault trigger

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1203]
Reported on Discord by hawkeyed / @MervDale

With TX16S hardware and `simu`, if you try to select the first widget space in the top bar layout for setup, it will not gain focus. If you then try to exit via touch the transmitter will emergency mode / simu will segfault.

https://user-images.githubusercontent.com/5500713/144367460-6da8c95c-f969-45dc-9bf7-af3bcbdb645a.mp4

**Comment by eshifri** [comment]
Actually, the same crash occurs if you do not touch the first widget, but just exit with all widgets unselected.
If you play long enough with the top bar widgets setup you can also het another weird behavior: "exit" takes you to the "setup new screen" rather then top bar setup. 

I wonder whether this is related to #1180 ?
