### ISSUE TITLE
outputs page Requires improvement

### ISSUE THREAD

**Issue by natiho2** [EdgeTX/edgetx#1225]
I noticed that on the outputs page, when you're setting the endpoints there is no visual clue of which direction you need to adjust.
With the OpenTX you simply had to move the stick and the arrow would point to the correct direction for endpoint adjustment.

**Comment by micromega1966** [comment]
Confermo, sarebbe utile vedere la direzione con una freccia.

**Comment by natiho2** [comment]
Is there an update about this?

**Comment by raphaelcoeffic** [comment]
@natiho2 see #1385

**Comment by natiho2** [comment]
Thanks to the developers who solved this problem..today I updated the firmware and it works properly.

**Comment by pfeerick** [comment]
That would be @eshifri ;)
