### ISSUE TITLE
3.5mm jack stopped working

### ISSUE THREAD

**Issue by B-oket** [EdgeTX/edgetx#1238]
3.5mm jack not working anymore.

3.5mm jack stopped working since a few builds back.
Used to connect the 3.5mm jack to a USB dongle to run Realflight sim but the radio
is not recognized anymore, seems like there's no signal from the 3.5mm jack?

To Reproduce
Connect 3.5mm jack to USB dongle and run Realfligt (or any other sim/sw that uses 3,5mm jack)

 - EdgeTX version 2.6.0 nightly #48bd1ac
 - Radiomaster TX16S

**Comment by pfeerick** [comment]
You could be suffering from issues with the 3.5mm jack (TX16S is notorious for this - it has the wrong length 4-pole socket), or it could have stopped working again. If you revert to an older build, and it starts working again, that will at least eliminate the hardware being dodgy.

**Comment by tonims1** [comment]
tried the same version of nightly on a tx16s and it works for me

**Comment by B-oket** [comment]
> You could be suffering from issues with the 3.5mm jack (TX16S is notorious for this - it has the wrong length 4-pole socket), or it could have stopped working again. If you revert to an older build, and it starts working again, that will at least eliminate the hardware being dodgy.

Tried another cable and now it is working again...
Strange because the cables/jack are identical but different brand..

**Comment by B-oket** [comment]
Not a bug, hw issue.

**Comment by pfeerick** [comment]
One is probably a fraction longer than the other, or just seats better. I've opened all of my TX16S and my TX12, and squashed the bottom two contacts a little further, so that they make contact properly with standard TRS 3.5mm connectors... as before that they wouldn't work at all, or were intermittent.

**Comment by rotorman** [comment]
The signal contact on TX16S 3.5mm jack is actually the one before last (the tip-most ring of TRRS tip-ring-ring-sleeve) connection:

![grafik](https://user-images.githubusercontent.com/21011587/145593866-8d924803-04a4-41f7-8a2b-dc0e32d91e15.png)
