### ISSUE TITLE
NV14: Touch Handling problem of double or wrong touchevent 

### ISSUE THREAD

**Issue by uPz3TT3r** [EdgeTX/edgetx#1245]
**Describe the bug**
The touch handling of nv14 is nearly unuseable. If you want to Duplicate or select a model most of the times the system does 3 copies or Not select the correct model. On telemetrie tab of the model it is nearly impossible to Check the „disable telemetrie“ checkbox.

seems that often touch events are pointed to the wrong Position (Even sometimes 2-3cm deeper as the Original touch was).
And often seems Like „double touch event“ Even if it was single touch.

i have two nirvanas problem is reproducable on both 

**To Reproduce**
Try to duplicate a model 3 times… it takes „hours“

**Expected behavior**
Model should be duplicated, or selected of you choose that. But touchevent goes on other positions 

**Screenshots**

**General information**
 - EdgeTX version (nightly from 2021-12-11) c8025531
 - Hardware (Flysky nv14)

**Comment by gagarinlg** [comment]
This is fixed by #1242
