### ISSUE TITLE
Channel display position in the title bar of NV14

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#1246]
**Describe the bug**
The new channel display in the title bar feature on NV14 draws channel ID on top of the "mixer"
 
**To Reproduce**
On NV14 open any mixer.
Look at the title bar.
See CHxx printed on top of the word "mixer"

**Expected behavior**
Channel ID should be shifted to the right.

**General information**
 - EdgeTX current code
 - Hardware NV14

**Comment by eshifri** [comment]
Already fixed in #1231

**Comment by pfeerick** [comment]
Ah, woopsie... thanks for the reminder... I forgot to merge it after rebasing and cleaning out a libopenui hitch-hiker...
