### ISSUE TITLE
FrSky X10(S) Express + MPM some protocols (MPX and maybe others) missing.

### ISSUE THREAD

**Issue by nostromo123** [EdgeTX/edgetx#1252]
Radio FrSky X10S Express with EDGE v2.5 and nightly.

MPM module Jumper 4in1 clone with CKS32.
- has been flashed with flash-multi-0.6.1 and mm-stm-serial-taer-v1.3.3.0.bin
- CKS has been verified with STM32CubeProgrammer as STM32
- MPM working under OTX 2.3.14 and showing MPX protocol.

Issue is, that under EDGE MPX protocol not showing up, when scrolling protocols on radio.
(Made a list of visible protocols)

[EDGE nightly.txt](https://github.com/EdgeTX/edgetx/files/7720294/EDGE.nightly.txt)

In EDGE companion 2.6.0 MPX is available and can be saved and transferred to the radio.
(screenshot of protocols in companion)

![pic](https://user-images.githubusercontent.com/17964433/146207096-806c12d7-5519-48ad-9af1-44da7884fe74.jpg)

But when starting the radio, the message 'SCANNING PROTOCOLS' appears and no MPX shows up, when scrolling for the MPX protocol.

I posted in RCG (https://www.rcgroups.com/forums/showpost.php?p=48327043&postcount=1520)
hoping someone there can confirm or decline, but no answer till now.

In (https://frsky-forum.de/index.php?thread/6130-seit-kurzen-probleme-mit-otx-und-multimodul/&pageNo=1)
one user tested a MPM with his TX16S and EDGE v2.5 and nightly and had no problem with the MPX protocol.

br KH

**Comment by raphaelcoeffic** [comment]
The protocols offered on the radio are listed from the MPM itself. So the bigger question is: does your specific MPM and it’s firmware support this protocol?

please note that Companion has no idea of the protocols really supported, it just lists them all.

**Comment by raphaelcoeffic** [comment]
Sorry, it seems I cannot reproduce this. All the protos including those without sub-proto are included when testing with TX16S and MPM 1.3.3.0 (internal as well as external module). It is highly improbable it would be different with a X10, as there is nothing dependent on the radio type itself here.

**Comment by raphaelcoeffic** [comment]
@nostromo123 after checking the screenshots on RCG, it seems your module is not talking to the handset, so that the dynamic protocol list is probably not used, and thus the protocol is missing.

**Comment by nostromo123** [comment]
I think now, that I might have a crappy hardware in form of that MPM module here.That is the second MPM module, I ordered from China in the last two month. First one could not be flashed with the MPM firmware at all and went back. This one here now is a clone Jumper with a CKS32. Looked at first sight trustworthy. But seeing now also some erratic behavior under OTX, I'll close this here now.

Sorry for troubling you. 

br KH

**Comment by nostromo123** [comment]
Have another MPM module her on my table.IRangeX IRX4.

Now my X10S Express with edgeTX 2.6

**Comment by rotorman** [comment]
Please provide further info - your last message is not clear what you want to say.

Is the problem with missing MPX still there also with IRX4 ? Did you test it with X10S Express **and** TX16S and both behave similarly?

**Comment by nostromo123** [comment]
@rotorman 

Hi, I don't have a TX16S. Doing those experiment with my X10 S Express.

br

**Comment by nostromo123** [comment]
One step further ahead.

I did **not** update that new MPM module, I have now here on my desk.

I flashed my X9D+ from OTX 2-2-4 to edgeTX 2.6

![screen-2022-02-05-192704](https://user-images.githubusercontent.com/17964433/152655462-2f906762-ba02-4899-b587-e8994aae6b2c.jpg)
![screen-2022-02-05-192759](https://user-images.githubusercontent.com/17964433/152655473-d7ae1366-a965-4142-b90e-d57791d3e3ba.jpg)

Then I scrolled for M-Link! 

![screen-2022-02-05-193226](https://user-images.githubusercontent.com/17964433/152655498-0bf9cba7-dab9-4d21-8b7e-2399b0f4715e.jpg)
![screen-2022-02-05-193228](https://user-images.githubusercontent.com/17964433/152655502-aa985c24-850b-426e-aa49-764ffd80b5bf.jpg)

br KH

**Comment by pfeerick** [comment]
> raphael wrote ' it seems your module is not talking to the handset, so that the dynamic protocol list is probably not used, and thus the protocol is missing'

This was in relation to the screenshots you posted on RCG, as they both indicated 'No MULTI_TELEMETRY detected' which is an indication that the MPM module isn't even talking to the transmitter, so the radio firmware falls back to an internal list, and the EdgeTX internal protocol list is older than the one OpenTX is using (same list is used for B&W and colorlcd radios, does not have M Link as an option). However, when the MPM is talking to the radio, the radio can interrogate it for the list of support protocols that the specific firmware version the MPM is running supports, and options for each. 

On my TX16S with ETX 2.6, and 1.3.3.0 MPM firmware, M-Link shows up as an option. If I tell it have a MPM in the external bay (and there is none), the protocol list there does not show M-Link. i.e. as per your initial result, and is expected if the MPM is not working properly. Hopefully the fact your X9D+ is showing the M-Link entry means your X10 will also work with that particular MPM module, since this has come from the module. 

Are you able to update us any further as to status of this? If you do update the MPM firmware, you should also be able to revert since you can still download older versions of the MPM firmware, including the 1.3.2.61 it is currently running. So you should also be able to identify if something changed with a newer MPM version safely. I wouldn't think that is the case as I don't see any mention in the release notes for the MPM but can't discount the possibility.

**Comment by nostromo123** [comment]
Hi Peter.

- I have a back-up of the MPM firmware.

- I'll update the MPM to Pascals latest fw version 1.3.3.7
- I'll check with my X9Ds here under EdgeTX 2.6 MPX plus binding plus telemetry
and crosscheck with my X10S Express under EdgeTX 2.6 and come back.

but this week I am totally busy, maybe oncoming  weekend I can find some time.

But there is one other issue X10S Express <> MPM, this time OTX 2.3.14 with MPM
with reduced protocols ....

See https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/648

I did not test that under EdgeTX (MPX not showing!)

So I think, there could possibly be a **general** communication problem X10 **Express** <> MPM??

br KH

**Comment by pfeerick** [comment]
Oh, interesting... yes, that post would certainly suggest there is something fishy going on in the the X10, especially if you can use your X9D as a reference on what the X10 should be showing ;) Since if you can't update the firmware via the transmitter, and have the NO MULTI_TELEMETRY on the X10 then indeed the module and the X10 are not talking to each other, which is a bad start. 

No hurry, was just wondering on status of the issue.

**Comment by nostromo123** [comment]
Sorry for coming back here so late.

My radios X9D+ and X10S Express. OS on both radios EdgeTX 2.6.

MPM IrangeX IRX4 flashed with Pascals latest stable 1.3.3.7 TAER

**Test sequence on X9D+**

**M-Link selected and binding MPX RX**

![screen-2022-02-12-171221](https://user-images.githubusercontent.com/17964433/153723751-8bd22d8f-d254-4a42-ae97-570c7e7a73cb.jpg)

**Telemetry data receiving**

![screen-2022-02-12-171247](https://user-images.githubusercontent.com/17964433/153723796-32506c26-4d84-4e5d-a9f2-a2e74a7a2dfc.jpg)

**Wrinting the MPM fw from radio to module**

![screen-2022-02-12-174234](https://user-images.githubusercontent.com/17964433/153723821-7e238246-afd0-4a96-b36a-4a86d756c2ca.jpg)

Could not take screenshots from here, so I switched to my mobile.

![20220212_191004](https://user-images.githubusercontent.com/17964433/153723874-892b822f-ed03-4d7f-a6ce-625f5c57e8a6.jpg)


![20220212_191010](https://user-images.githubusercontent.com/17964433/153723882-14a66317-185f-4f51-8aaf-72bf4a7a331c.jpg)
![20220212_191015](https://user-images.githubusercontent.com/17964433/153723884-2c1b5d0f-14bc-49e2-a523-9f268d6a24b0.jpg)

So far, so good!

**Now that procedure on the X10S Express**

**NO M-LINK showing up**

![screen-2022-02-12-171845](https://user-images.githubusercontent.com/17964433/153723956-4ddd42a6-6cd3-471d-97d2-ea3fb921a72e.jpg)

**NO information on the radio info screen**

![screen-2022-02-12-172542](https://user-images.githubusercontent.com/17964433/153723999-5590cb33-7564-432a-be4d-e8812ea51fd3.jpg)

**Trying to flash the MPM from the radio**

![screen-2022-02-12-174238](https://user-images.githubusercontent.com/17964433/153724029-f6843ee5-3efe-4fbd-b39b-228b11b8e208.jpg)

![screen-2022-02-12-174247](https://user-images.githubusercontent.com/17964433/153724041-a28648d0-86d0-4556-ab32-913d827f05dd.jpg)

![Bildschirmfoto_2022-02-12_19-16-48](https://user-images.githubusercontent.com/17964433/153724047-f775c775-cc1f-4c89-ad44-018a0b3381de.jpg)

![Bildschirmfoto_2022-02-12_19-17-15](https://user-images.githubusercontent.com/17964433/153724051-9d03aafd-a39f-4228-9c5c-43dc53a16d03.jpg)

Tomorrow I'll try to do a run with the X10S Express/MPM and one of my FrSky receivers and post the result here ....

br KH

**Comment by nostromo123** [comment]
X10S Express/MPM and one FrSky D8R-IIplus

**Binding and settings**

![screen-2022-02-13-090015](https://user-images.githubusercontent.com/17964433/153744879-663aeed3-7b59-42bb-8312-3df32d9570f5.jpg)

**Telemetry data**

![screen-2022-02-13-085942](https://user-images.githubusercontent.com/17964433/153744882-12fe910d-a106-4556-b40c-4d0065e6596b.jpg)

**Servo on CH 4 and working**

![screen-2022-02-13-090049](https://user-images.githubusercontent.com/17964433/153744920-1cd7eb95-3812-4975-bf4e-043781330fa2.jpg)
![screen-2022-02-13-090052](https://user-images.githubusercontent.com/17964433/153744923-26c46b7a-f9a3-4549-b732-1c63082ec4e2.jpg)

No issue with that!

**Comment by nostromo123** [comment]
> But there is one other issue X10S Express <> MPM, this time OTX 2.3.14 with MPM with reduced protocols ....
> 
> See [pascallanger/DIY-Multiprotocol-TX-Module#648](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/648)

Just checked that point.

Modified Pascals 1.3.3.7 (the _Config.h file by commenting unwanted protocols) compiled it in Arduino IDE and uploaded it to the MPM and with my X9D+ this is working!

cu KH

**Comment by pfeerick** [comment]
Nice! Something weird is still going on though since you had it working with the X9D+ but not the X10, as well as the inability to update the firmware on the X10. Normally the answer would be 'bootloader isn't installed' but then you wouldn't be able to have update it on the X9D+ either then. 

As far as the module information screen, that seems _normal_, as the same is the case with the internal MPM with the TX16s. Would probably be better if it reported that it was MPM + version number or something, but not atm. 

What MPM did you get... is it the iRangeX IRX4 with the yellow knob on the back? I finally gave in and ordered one... have been meaning to get one for ages to use with my older transmitters.

**Comment by nostromo123** [comment]
That one

![20220215_115603](https://user-images.githubusercontent.com/17964433/154051292-f53510f6-49cc-4341-8546-6675dce2d93e.jpg)
![20220215_115615](https://user-images.githubusercontent.com/17964433/154051306-29c9b9cf-9ae2-44b4-af9c-839d4e0b55af.jpg)

br KH

**Comment by nostromo123** [comment]
The only issue I could spot with that MPM is, that it has an APM32, but you'll not get a MPM with a STM 32 from China now.

Tested this module with STM32 Cube and is recognized as a STM32. So this should not matter ...

![Unbenannt](https://user-images.githubusercontent.com/17964433/154070500-9b7dd077-10c2-4f3d-9879-993eceb1547d.JPG)

**Comment by pfeerick** [comment]
Ah, that probably explains the cryptic message about the one I ordered not having a STM32 but instead an "ARM CORTEX-M" .. but, er, that is what the STM32 is? lol I'm pretty sure it should be the same as the one you have, just with most of the missing components populated (buttons, knob, leds, USB port), so will at least be able to have a point of reference using the TX16S when it finally ships/arrives. As well as a use for one of my older transmitters again ;)

**Comment by pfeerick** [comment]
I received my "iRangeX IRX4 Plus" yesterday, so I can now hopefully add some more datapoints to help or confuse even more :grin: This is with RM TX16S. 

The module shipped with v1.2.0.22 firmware, and as expected, it didn't list M-Link. 
![image](https://user-images.githubusercontent.com/5500713/158002892-48f42476-13fd-4cfa-82b1-d7a96f3d9a05.png)
![image](https://user-images.githubusercontent.com/5500713/158002894-9a59dad0-b32f-42fe-a545-e5d492f7a989.png)

Upgrading the bootloader and firmware using Flash Multi v0.6.1, to v1.3.3.7 (as v1.3.3.0 is the version that introduced the protocol/subprotocol dynamic scan facility EdgeTX uses) and M-Link is now in the menu:

![image](https://user-images.githubusercontent.com/5500713/158002987-a4cbd4f7-67e6-4ff6-9690-94691859fc19.png)
![image](https://user-images.githubusercontent.com/5500713/158002989-efb9ac5a-74d9-4aae-a54d-9c4459b65a5f.png)

And just for reference, this is the internal MPM, which is still running v1.3.3.0:
![image](https://user-images.githubusercontent.com/5500713/158003026-3fa7222e-7435-44a0-a4c6-2541dc6df6f0.png)

And, on X9D+2019:
![image](https://user-images.githubusercontent.com/5500713/158003149-893f3c82-cb45-4a6d-968d-44bbffa88372.png)

I'll open it up later to see what's actually in it.

**Comment by nostromo123** [comment]
But not here with my X10S Express ..

With 1.3.3.7 TAER no M-Link showing up. With 2.6 release and with nightly.

Strange it is.

br

**Comment by pfeerick** [comment]
Ok, I've just thought of something "simple" we can try... what does the protocol list look like with and without the module inserted? You'll need to power cycle between module in and out state to ensure the dynamic protocol scan happens...  i.e. Without the module it should incorrectly have "verted" as the last protocol...

![image](https://user-images.githubusercontent.com/5500713/158040964-c2bc7869-728b-4781-aa78-37e5d1bbe8a9.png)

... whereas with the  module it's ZSX and you can see both the Wfly entries in order. If you don't, probably means that on the X10S the dynamic protocol scanning is not working (properly). 

![image](https://user-images.githubusercontent.com/5500713/158040951-47528604-82d2-476e-9035-8c847cba3b99.png)

For reference, this is the module I have, basically seems to be the same as yours:
![IMG_20220313_113526 (Large)](https://user-images.githubusercontent.com/5500713/158041144-f7c80980-0bdb-4dd6-bcc5-82e721f32443.jpg)
![IMG_20220313_113641 (Large)](https://user-images.githubusercontent.com/5500713/158041147-97d79c4d-bb7b-4eeb-9636-8e07fdd9f37d.jpg)
![IMG_20220313_113706 (Large)](https://user-images.githubusercontent.com/5500713/158041151-14d7fc30-39e1-4c9a-8323-a7dc6b8edefa.jpg)
![IMG_20220313_113802 (Large)](https://user-images.githubusercontent.com/5500713/158041153-5eaf64e8-a777-45b0-9029-825ac1896450.jpg)

**Comment by nostromo123** [comment]
Your MPM seems to be identical, just missing some hardware ...

Did the short test as proposed.

No MPM inserted, ext. module select

![screen-2022-03-13-110041](https://user-images.githubusercontent.com/17964433/158055065-8859f23e-74d1-48d3-9bb2-0b34c95e1a69.jpg)

Scroll to last line in protocol selection

![screen-2022-03-13-110057](https://user-images.githubusercontent.com/17964433/158055118-66daa703-338d-4af0-963c-470a80430f71.jpg)

Radio off, insert MPM, on again, select MPM in ext. module.

![screen-2022-03-13-110147](https://user-images.githubusercontent.com/17964433/158055215-e6ba7985-0f22-47d8-892b-7f2547e59c4e.jpg)

and the last line in protocols

![screen-2022-03-13-110210](https://user-images.githubusercontent.com/17964433/158055247-c6f72758-96d3-4431-941d-afd82f066a90.jpg)

In my eyes, that looks like a specific issue with those X10(S) Express radios!?

br KH

**Comment by pfeerick** [comment]
Damn, it looks like it. From the looks of yours it seems to be using the internal list, so the protocol scanning isn't working properly... I'll have to poke Raphael after 2.7 is out as I'm pretty sure he has X10 hardware so should be able to figure it out.

**Comment by nostromo123** [comment]
... and as under OTX 2.3.14 I do see M-Link, that issue is not a hardware defect of my radio here. I am quite sure.

Thank you for being so persistent ;-)

**Comment by pfeerick** [comment]
OTX has been maintaining the internal list of protocols for the MPM, which probably explains why you see it there. We instead opted to use the dynamic scan, which would make it so there would not be a need to keep updating ETX firmware... but obviously there is no a problem if it the two are not talking properly on this.

**Comment by pfeerick** [comment]
Are you able to try a build from this PR? https://github.com/EdgeTX/edgetx/pull/1705 I updated the static list of protocols and would be curious to know if MLink now "works"... meaning we still need to find out why the dynamic protocol scan is not working, but because its in the default list it at least shows up now when scanning doesn't happen.

**Comment by nostromo123** [comment]
It is not enclosed in the current nightly, I guess? So I think, I have to load the nightly source and exchange some files there and then build. Normally no problem, but at the moment it is not clear to me, which to replace in the source ....

Or modify 2.6 source and test with that?

**Comment by pfeerick** [comment]
No, because it's not been merged yet. But all PRs are built automatically still (via the Checks tab at the top of the PR). 

Anyway, link to a zip file with all the builds will be at the bottom of this page : https://github.com/EdgeTX/edgetx/actions/runs/2008365108

**Comment by nostromo123** [comment]
OK. ;-)

![screen-2022-03-21-105904](https://user-images.githubusercontent.com/17964433/159241723-3a981527-3b0e-4024-9d4b-564096eaa7a1.jpg)

![screen-2022-03-21-105921](https://user-images.githubusercontent.com/17964433/159241754-4ad17946-1063-46bc-93b5-8da98d3a25f8.jpg)


![screen-2022-03-21-105939](https://user-images.githubusercontent.com/17964433/159241776-a2b35fe9-40fc-4d3c-92ef-5c9f60a947c6.jpg)

**Comment by pfeerick** [comment]
By rights, it should show M-Link regardless of whatever the MPM is inserted or not, as I still don't think scanning is working properly, but because M-Link is in the fallback list now, it should show up (and hopefully work)... The giveaway for me atm is that if the MPM scanning is working, Assan is the first protocol listed , otherwise some some other protocol starting with B is the first one... Thanks for confirming that part at least is working for you! :)

**Comment by nostromo123** [comment]
Anything else, I can do/test/try at the moment?

br KH

**Comment by pfeerick** [comment]
Not just yet... In a week or two once 2.7 is out of the way I'll poke Raphael to see what he can make of it...

**Comment by donkeydog67** [comment]
Any updates about the issue?

**Comment by raphaelcoeffic** [comment]
This is a very old issue, is that even still an issue?

**Comment by nostromo123** [comment]
OK, then I'll close it. Think, the issue has been solved.

br KH
