### ISSUE TITLE
GVARS=NO Outputs Issue

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#1254]
I noticed that editing outputs with -DGVARS=NO is a little broken. The min/max starts off at 0 even though they're actually at -100/+100. This makes it so the minimum can only be reduced and maximum can only be increased (so you can only increase throw in either direction).

This is with a brand new model file.

![screen-2021-12-15-143458](https://user-images.githubusercontent.com/1323809/146277056-dc517c48-8724-4a5d-a916-cb4107a8bb91.png)

![screen-2021-12-15-143502](https://user-images.githubusercontent.com/1323809/146277057-37bde2ea-1cfc-4d19-946b-8ab32dd020f9.png)

**Comment by jmxp69** [comment]
Confirmed on my radio. Gvars also disabled.
