### ISSUE TITLE
TELEMETRY screen EDGE v2.5 'Telemetry type' option missing 

### ISSUE THREAD

**Issue by nostromo123** [EdgeTX/edgetx#1260]
This is the telemetry screen on my X10(s) Express with OTX 2.3.14
![20211216_155737](https://user-images.githubusercontent.com/17964433/146402586-e7788531-7afc-4ede-9231-7e0dbb9b0cc8.jpg)
and this is with EDGE v2.5
![20211216_154725](https://user-images.githubusercontent.com/17964433/146402764-a4dd2f50-784d-451c-873c-c6ca6ae401be.jpg)

We are using a MPX HF modules with a MPX to FrSky converter for telemetry data.

Could activate telemetry by selecting in EDGE companion v2.6 that 'Telemetry type' option and transfer the model data to the radio, as under EDGE companion the option 'Protocol' is available.
![Bildschirmfoto_2021-12-16_15-45-59](https://user-images.githubusercontent.com/17964433/146403959-23ed6de8-b4b6-495a-9d6d-d8c675010a36.png)

br KH

**Comment by raphaelcoeffic** [comment]
For my own education: does someone know what this option is supposed to do? I had the feeling that the telemetry protocol is determined by the module/source of the telemetry data. It is not clear to me what this setting is supposed to do. Is that forcing a telemetry protocol for what is received on a particular serial port? If it is the case, which one?

**Comment by pfeerick** [comment]
Yes, it was something I use/used to use on 9XR-PRO, and was to do with how the telemetry was fed into the radio - in my case it was "Frsky D (via cable)" IIRC. 

![image](https://user-images.githubusercontent.com/5500713/146514079-46285825-2c3b-4fab-b8f7-28c94972e010.png)

Interestingly, this issue suggests it was never implemented for horus targets... which nostromo123 was the opener off. So I would be curious to know when this became an option in OTX for colorlcd targets since it was not the case in 2.2, and under what configuration settings it becomes available. 

https://github.com/opentx/opentx/issues/4613

**Comment by nostromo123** [comment]
Started in 2015
https://openrcforums.com/forum/viewtopic.php?f=96&t=7275#p99610

We shifted over to a German forum in 2016
https://www.rc-network.de/threads/opentx-multiplex-mlink-konverter.581603/

Only seems to be used by users in Germany with their reliable MPX HF
equipment.
Up to you here, if you consider this obsolete .... ;-)




Am 17.12.21 um 09:37 schrieb Peter Feerick:

**Comment by raphaelcoeffic** [comment]
> Up to you here, if you consider this obsolete .... ;-)

Not trying to! I was just curious where the telemetry data are fed into the handset. So, where do you plug the converter into the handset?

**Comment by nostromo123** [comment]
Just to give an impression, some pics ....

My Taranis with ext converter Arduino pro mini 5V/16MHz

and inside another MPX HFMG3 module with converter based on ATTiny 841

Am 17.12.21 um 11:50 schrieb Raphael Coeffic:

**Comment by pfeerick** [comment]
Pictures don't come through on email ;)

On the 9XR-PRO, it was via the futaba style trainer port... not sure how you did it on the Taranis (so I also will be interested to see! :) )

**Comment by nostromo123** [comment]
Just realized that. ;-)

Taranis here

![20211217_123254](https://user-images.githubusercontent.com/17964433/146540801-11ade3d8-6e55-4fc7-bdd9-d442981624de.jpg)

and this I use on my X10 Express

![Konverter HFMG3_2](https://user-images.githubusercontent.com/17964433/146540985-775e8c43-f616-4ed7-9cd4-49a6a6b45be6.jpg)

![Konverter HFMG3_1](https://user-images.githubusercontent.com/17964433/146541014-d93a904a-c163-4f99-b89d-5c75c263f049.jpg)

**Comment by AlphaCharlyX** [comment]
Hello,

I have the same issue. I can't use my two MPX HF modules with my telemetry-converter because it is not possible under EDGE to select the right needed 'Telemetry type' FrSky D protocol in the option section of the radio.

PLZ add this feature soon. In OpenTX using the Telemetry type FrSky D and so the MPX HF modules with a telemetry-converter is no problem!

THX Alpha

**Comment by raphaelcoeffic** [comment]
Ok, so we are talking essentially about connecting this converter to the telemetry/S.PORT pin of the module bay, correct?

**Comment by nostromo123** [comment]
Yes, you can connect it like I did on the Taranis in the battery bay with an external Arduino pro mini as converter (could place the Arduino inside the MPX module also, but for me it was a bit cramped inside ;-)) or, as I did with the ATTiny in the module box.

**Comment by raphaelcoeffic** [comment]
> Yes, you can connect it like I did on the Taranis in the battery bay with an external Arduino pro mini as converter (could place the Arduino inside the MPX module also, but for me it was a bit cramped inside ;-)) or, as I did with the ATTiny in the module box.

Yes, but that uses another setting, as far as I can see (serial port set to "Telemetry In").

**Comment by nostromo123** [comment]
Your are right.
 My old Taranis with OTX 2.2.4
![20211217_153401](https://user-images.githubusercontent.com/17964433/146560723-4a055f2e-d88f-4f13-84a1-52039b3fe0cd.jpg)

**Comment by koaxheli** [comment]
Radiomaster TX16S "Santa" v2.6.0

Hello,

I have the same problem. I cannot use my TGS Jeti module with my telemetry converter as it is not possible under EDGE to select the 'Telemetry type' FrSky D protocol in the options section of the radio.

Please add this function soon. In OpenTX, using the telemetry type FrSky D and thus the Jeti HF module with telemetry converter is no problem!

**Comment by mha1** [comment]
This should be obsolete now as #3352 added native telemetry support of external M-Link HF modules.

**Comment by pfeerick** [comment]
Nice catch, yes, that should resolve this particular instance...
