### ISSUE TITLE
Api Color Lcd: this looks like it went wrong :)

### ISSUE THREAD

**Issue by olliw42** [EdgeTX/edgetx#127]
@raphaelcoeffic  pl look at 

https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/lua/api_colorlcd.cpp#L297-L305

looks like something went wrong :)

(the if can't execute, and the code looks strangely different to functions before :))

**Comment by raphaelcoeffic** [comment]
@olliw42 nice catch, thx!
