### ISSUE TITLE
LUA Virtual Exit event missing?

### ISSUE THREAD

**Issue by lshems** [EdgeTX/edgetx#128]
How do you guys manage the deselection of an item selected for editing?

I used to use EVT_EXIT_BREAK (33 on my taranis in the sim), but it isn't triggered (anymore). 

I get a 97, but is this still linked to a key constant?

Don't want to hardcode, as this is again one of the magic numbers that may change between releases and vary between radios....
??

**Comment by raphaelcoeffic** [comment]
@lshems you should use the virtual constants, so basically `EVT_VIRTUAL_EXIT`. I think `EVT_EXIT_BREAK` is not defined at all.

**Comment by raphaelcoeffic** [comment]
> Don't want to hardcode, as this is again one of the magic numbers that may change between releases and vary between radios....

This should be checked and fixed, that's right. But I can assure you that the virtual `EXIT` event works.

**Comment by lshems** [comment]
Unfortunately the event on exit gives 97 first, and in my scripts I never arrive at the 33. The 33 does come indeed after the 97 in a simple one time test script. 

Seems my script gets aborted before it reaches the 33. OK, i'll search further on my side.
