### ISSUE TITLE
Mixer line names get not loaded in simulator from companion

### ISSUE THREAD

**Issue by lshems** [EdgeTX/edgetx#1287]
[XD9+.zip](https://github.com/EdgeTX/edgetx/files/7765482/XD9%2B.zip)
2.6.0 RC1.0

when loading this model in companion and starting the simu, some mixer line names will not be available in the simu mixer lines.

Check mixer 31, line 3 for instance. In companion it shows "Roll" as name for the mixer line.
When starting the radio simulator, the name for mixer line 31,3 is [gone.]()

**Comment by raphaelcoeffic** [comment]
@lshems which Companion build did you use?

**Comment by lshems** [comment]
As noted 2.6.0 rc1.0 from the action artefacts on window companion.

**Comment by lshems** [comment]
https://github.com/EdgeTX/edgetx/actions/runs/1601646319 on arm64 update

**Comment by raphaelcoeffic** [comment]
@lshems is this correct?
<img width="521" alt="Screenshot 2021-12-26 at 08 42 56" src="https://user-images.githubusercontent.com/1050031/147402042-c08c39a8-b9f5-4780-9673-aa5a4265edca.png">

**Comment by lshems** [comment]
This is indeed exact the issue

**Comment by elecpower** [comment]
@raphaelcoeffic I vote for moving forward and focus on yaml

**Comment by lshems** [comment]
I think with a yaml interpreter in lua, we could ditch the standard GUI if there would be a reload yaml file function. 

Everybody could create his favorit layout and behaviour just using LUA!!!

**Comment by raphaelcoeffic** [comment]
@lshems not sure it would be so efficient. That being said, it would also require quite some stuff to offer all the capabilities of the C++ code. Also, it’s a bit off-topic for this issue 😜

**Comment by lshems** [comment]
Would a reload function in lua be possible? Then I assure you it can be in done (quite easily).

**Comment by lshems** [comment]
Thanks
