### ISSUE TITLE
Changing radio settings hardware internal module doesn't update each existing model internal rf mode

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#1299]
**Describe the bug**
Radio settings changing hardware internal module does reset / update each existing model internal rf mode or warn they are incompatible.

**To Reproduce**
Steps using RM TX16S sim
Edit Internal module in hardware settings say from MULTI to CRSF and exit
Open an existing model setup
Go to Internal Rf and mode is for previous internal module along with all the supporting settings.
Click on the mode value and the drop down selection is only those compatible with new internal module.

**Expected behaviour**
At the time of changing the hardware internal module reset every model internal rf mode to OFF or warn that the model settings are incompatible.

**Screenshots**
![screenshot_tx16s_21-12-27_08-01-48](https://user-images.githubusercontent.com/15316949/147420097-6241fa98-117b-4be4-8e4f-d9c391b55bdd.png)

**General information**
 - EdgeTX version main branch
 - Hardware simulated RM TX16S

**Comment by raphaelcoeffic** [comment]
Yeah, it was never really intended to update all the models. It might be a bit tricky as well, as it might require additional settings which would not be available anyway. Let’s call this a known limitation.

**Comment by elecpower** [comment]
The safe approach would be to set all internal Rf modes to OFF then no need to worry about mode specific settings.

**Comment by raphaelcoeffic** [comment]
> The safe approach would be to set all internal Rf modes to OFF then no need to worry about mode specific settings.

You mean when a model with an incompatible module type set is loaded? That should be doable easily, indeed. And normally, when the module is set to OFF, you notice soon enough ;-)

**Comment by elecpower** [comment]
Better for a model not to operate than to operate unexpectedly or potentially dangerously

**Comment by pfeerick** [comment]
Ok, so at time of model load, if the internal RF module != configured hardware model, internal RF == OFF.

**Comment by elecpower** [comment]
Also YAML files and the ability to manipulate outside official code is going to create opportunities for data integrity issues. So this critical test needs to occur on model load.

**Comment by pfeerick** [comment]
After actually looking though this further, this only applies to the *active* model - there is already some safeguard that sets the type to MODULE_TYPE_NONE if `g_eeGeneral.internalModule` doesn't match - probably `isInternalModuleAvailable()` - which kicks in as soon as you change models, or power cycle... so the only change that is needed is for the internal RF to be turned off when the module setting is changed in the hardware settings...
