### ISSUE TITLE
Touch interface (make more fields listboxes)

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#13]
It looks like the input for 'Pwr Off delay' has a limited range of options - 0s, 1s, 2s and 3s - or at least it does on the Radiomaster TX-16s firmware. Making it a list like say 'Backlight Mode' would make it more accessible for touch. 

Below is a non-exhaustive list of the various entries that seem to have ranges, so potential drop down list candidates

# Radio Settings
## Radio Setup
* Date - Year, Month, Day
* Time - Hour, Minutes, Seconds
* Variometer - Pitch zero, Pitch max, Repeat zero
* Alarms - Battery low
* Pwr Off delay
* GPS - Time zone
* Play delay
## Trainer
* Multiplier

# Model Settings
## Model Setup
Internal RF (Multi) - Channel Range (start and end) + others depending on mode selected
External RF( XJT) - Channel Range (start and end) + others depending on mode selected
Trainer - Channel Range (start and end)

**Comment by raphaelcoeffic** [comment]
> It looks like the input for 'Pwr Off delay' has a limited range of options - 0s, 1s, 2s and 3s - or at least it does on the Radiomaster TX-16s firmware. Making it a list like say 'Backlight Mode' would make it more accessible for touch.

Thx for feedback / input. There are more of these. Luckily, it should en easy to convert these fields into drop-downs.

**Comment by pfeerick** [comment]
I've tweaked the title, and added more fields I think are worth _considering_ for listbox entries... it's not a list of demands! 😁

**Comment by philmoz** [comment]
Many of these would result in very long lists, so I'm not sure they would be good candidates:

Date - year: current range is 2018 - 2100 (83 entries)
Time - minute & second - 60 entries

I think it would look odd to have some parts of the date as numbers and some as lists. I would leave them all as numbers.

Vario - pitch zero - 81 entries, pitch max - 141 entries, repeat zero - 81 entries.
Alarm - battery low - 91 entries.
Play delay - 101 entries.

All of these would he hard to navigate as lists.

I don't have GPS in my radio; but I'm guessing 24 entries. Could go either way.

Power off delay has already been converted.

**Comment by gagarinlg** [comment]
![Screenshot_20230118-063802](https://user-images.githubusercontent.com/54738901/213093009-98b11688-a795-48ac-97a8-d93acb3368f4.png)
This might work for the time entry, even without touch, when implemented right.

For the year, the list could be shortened.

For the others, you are right in my opinion.

**Comment by pfeerick** [comment]
Given the plans to overhaul the UI nearly entirely, this issue probably no longer has a place anymore anyway. Thus the decision (and blame) on what controls are best for each input are in hands of the guys working on the UI :grin:
