### ISSUE TITLE
In the character set at EDGE the special characters are missing

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#1310]
In the character set at EDGE the special characters are missing
Decimal from 147 to 158.
In OTX they are present see screenshot
![screenshot_tx16s_21-12-28_18-07-34](https://user-images.githubusercontent.com/92114465/147590396-b4412872-9302-489c-a35b-4cc0a1c5cb77.png)
.

**Comment by pfeerick** [comment]
Since this seems to be a Lua script, can we get the source for that as well so that the fault can be reproduced locally? ;)

**Comment by koaxheli** [comment]
Here is the Lua to the missing special characters.
With Edge 2.6 Nightly
Path: \SCRIPTS\TOOLS\WizardTest.lua
![screenshot_tx16s_EDGE_21-12-29_10-03-55](https://user-images.githubusercontent.com/92114465/147648704-b469f67e-30ac-48b6-a9dc-2564e100f716.png)
![screenshot_tx16s_OTX_21-12-29_10-23-34](https://user-images.githubusercontent.com/92114465/147648716-0ac2647f-f324-4bc8-80a2-3cc780dc47a0.png)
[WizardTest.zip](https://github.com/EdgeTX/edgetx/files/7788210/WizardTest.zip)

**Comment by pfeerick** [comment]
Excellent! Thanks for that! :) @richardclli Is there any chance this is related to translation handling in some way? I've verified this on TX16S on `main` and also against v2.5.0, so it's not a new breakage.

**Comment by koaxheli** [comment]
The shift of two digits is not the problem, but from 149 on there are no more characters.
The special characters like ä, ö and ü are missing.

**Comment by pfeerick** [comment]
I didn't say it is **the** problem... ;)

>*There is also*

**Comment by koaxheli** [comment]
Hello,
And where can I get the German translation?

All the best in the new year and a happy new year 2022

**Comment by pfeerick** [comment]
Self-build with the `-DTRANSLATIONS=DE` flag. Or tell me the build options, target radio (from companion) and preferred version, and a build will magically appear here within 24 hours hours 😁

**Comment by koaxheli** [comment]
The target radio is a Radiomaster TX16S, preferred version.
EdgeTX "Santa" 2.6.0 latest
The latest status is see attachment.
![screen-2022-01-01-140212](https://user-images.githubusercontent.com/92114465/147851674-f6c0d910-d8fc-42d7-82b6-3e8bdc7b969c.png)
.
![image](https://user-images.githubusercontent.com/92114465/147851704-77fe03c6-00f1-4437-8134-ac97a6c1fd06.png)

**Comment by pfeerick** [comment]
Ok, maybe not 24 hours! Flex won't be needed, as that is on by default, And just a clarification - is LUA ticked because you want the lua custom mixer support, or because you want lua (as that checkbox is really for the lua mixer scripts - which isn't confusing *at all*). Either way, both are attached. I'll do another build probably tomorrow since RC2 is likely to be out then. 

`cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DTRANSLATIONS=DE -DBLUETOOTH=Y ..`
`cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DTRANSLATIONS=DE -DBLUETOOTH=Y -DLUA_MIXER=Y ..`

[build-TX16S.zip](https://github.com/EdgeTX/edgetx/files/7800878/build-TX16S.zip)

**Comment by koaxheli** [comment]
Since the EdgeTX "Santa Claus" v2.6.0 is released I could have a version with Bluetooth and in German, thanks.

**Comment by pfeerick** [comment]
Yes, I'll be building all the language variants today, so you will get it soon :)

**Comment by richardclli** [comment]
> Excellent! Thanks for that! :) @richardclli Is there any chance this is related to translation handling in some way? I've verified this on TX16S on `main` and also against v2.5.0, so it's not a new breakage. There is also a two character shift present between OTX and ETX... i.e. the down arrow is 129 on OTX, but 131 on ETX.

ETX translations are complete different from OTX,  OTX used a fixed mapping of special characters besides En and extra (icons).  Now because of B/W uses fixed font files, a fixed mapping of special characters are used per translation.  But color lcd uses a dymanic approach, CJK and other languages used the same method that will parse thee translation files and obtain a custom set of special characters.

**Comment by jfrickmann** [comment]
Please see #1169. I believe that it makes this one redundant. Please try this script:
```
local charNames = {
  "CHAR_RIGHT",
  "CHAR_LEFT",
  "CHAR_UP",
  "CHAR_DOWN",
  "CHAR_DELTA",
  "CHAR_STICK",
  "CHAR_POT",
  "CHAR_SLIDER",
  "CHAR_SWITCH",
  "CHAR_TRIM",
  "CHAR_INPUT",
  "CHAR_FUNCTION",
  "CHAR_CYC",
  "CHAR_TRAINER",
  "CHAR_CHANNEL",
  "CHAR_TELEMETRY",
  "CHAR_LUA"
}

local chars = {
  CHAR_RIGHT,
  CHAR_LEFT,
  CHAR_UP,
  CHAR_DOWN,
  CHAR_DELTA,
  CHAR_STICK,
  CHAR_POT,
  CHAR_SLIDER,
  CHAR_SWITCH,
  CHAR_TRIM,
  CHAR_INPUT,
  CHAR_FUNCTION,
  CHAR_CYC,
  CHAR_TRAINER,
  CHAR_CHANNEL,
  CHAR_TELEMETRY,
  CHAR_LUA
}

local function run(event)
  local x, y = 0, 0
  lcd.clear()
  for i = 1, #chars do
    lcd.drawText(x, y, charNames[i] .. " = " .. chars[i])
    y = y + 20
    if y > LCD_H - 20 then
      x = x + 160
      y = 0
    end
  end
  
  return 0
end

return { run = run }
```

**Comment by pfeerick** [comment]
> Since the EdgeTX "Santa Claus" v2.6.0 is released I could have a version with Bluetooth and in German, thanks. Transmitter: TX16S

Done! I had heli on the brain so did a noheli build before I realised you wanted bluetooth=y,  not `heli=n` lol... so you can have both bluetooth with or without heli. 

[firmware_tx16s.zip](https://github.com/EdgeTX/edgetx/files/7930512/firmware_tx16s.zip)

**Comment by JimB40** [comment]
> local charNames = {
>   "CHAR_RIGHT",
>   "CHAR_LEFT",
>   "CHAR_UP",
>   "CHAR_DOWN",
>   "CHAR_DELTA",
>   "CHAR_STICK",
>   "CHAR_POT",
>   "CHAR_SLIDER",
>   "CHAR_SWITCH",
>   "CHAR_TRIM",
>   "CHAR_INPUT",
>   "CHAR_FUNCTION",
>   "CHAR_CYC",
>   "CHAR_TRAINER",
>   "CHAR_CHANNEL",
>   "CHAR_TELEMETRY",
>   "CHAR_LUA"
> }

Hey Jesper,
Up to date I had it hardcoded with \xxx syntax
Testing it but once SMLSIZE flag is set those symbols do not appear on screen.
Haven't tested yet but I think setting any font size flag will do the same.

**Comment by jfrickmann** [comment]
I am not sure that the char codes are the same on all transmitters, that’s why the constants are handy. 
And in any case, the special chars are only available for standard and BOLD fonts.

**Comment by koaxheli** [comment]
This compilation would be ideal.
Thanks

cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DTRANSLATIONS=DE -DBLUETOOTH=Y -DLUA_MIXER=Y ..

**Comment by pfeerick** [comment]
Done... here you go ;)

[firmware.zip](https://github.com/EdgeTX/edgetx/files/7962716/firmware.zip)

**Comment by koaxheli** [comment]
Thank you very much

**Comment by gagarinlg** [comment]
Is there any reason this issue is still open?
