### ISSUE TITLE
LVGL libopenui integration

### ISSUE THREAD

**Issue by gagarinlg** [EdgeTX/edgetx#1324]
libopenui and all widgets need to be ported to lvgl.

This issue needs some discussion on the software design.

- What is libopenui needed for in the future
- use lvgl screens. One screen, that is always there, for the main view, create a new screen and make that active for menus, warning screens, ...
- make that screen handling part of libopenui
- ...

**Comment by Linjieqiang** [comment]
Why not only use the LVGL as the edgetx GUI, not include libopengi?

**Comment by raphaelcoeffic** [comment]
> Why not only use the LVGL as the edgetx GUI, not include libopenui?

Because that amounts to a full re-write of the UI. Might happen in the future, but it would be good if we could avoid that.
