### ISSUE TITLE
Yaapu screen not not populating

### ISSUE THREAD

**Issue by Flierman1945** [EdgeTX/edgetx#1325]
- EdgeTX version (e.g. 2.6.0 or nightly and #commit number)
 - Hardware  RM TX16S)
 
Selecting the Yaapu config, yaapu maps, or Yaapu debug, the variable values are visable when scrolled, but there is no left menu items.  Also the main yaapu sereen that displays maps bat volts home etc is no populating correctly

**Comment by gagarinlg** [comment]
Is this an issue with 2.8.1?

**Comment by Flierman1945** [comment]
I am on  Edge ver 2.8.0 and Yappu ver 1.3.0 and it all works ok.
With Edge ver 2.8.1 I have no info as I have not updated my test tx

**Comment by pfeerick** [comment]
It should be no different for 2.8.1 (but please let us know if that's not the case!). Closing as obviously the situation has changed since 2.6.0 ;)
