### ISSUE TITLE
Error in building main under Ubuntu 20.04

### ISSUE THREAD

**Issue by nostromo123** [EdgeTX/edgetx#1327]
Fresh and updated Xubuntu 20.04 in vbox under Debian Bullseye host.

Building environment set up according to Instruction

https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Ubuntu-20.04

Errors show up when executing

$ make -j`nproc` firmware

Please could someone here have a look.

[Neue Datei.txt](https://github.com/EdgeTX/edgetx/files/7796476/Neue.Datei.txt)

**Comment by raphaelcoeffic** [comment]
The important part is here:
```
clang.cindex.LibclangError: libclang-11.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

Did you update your system recently? Can you please check which versions of LLVM / clang are installed?

**Comment by gagarinlg** [comment]
I had the same problem on Ubuntu 20.04 a few days ago. Installing libclang11-dev solved it. Some new build dependency must have ween intr2.

**Comment by nostromo123** [comment]
The Xubuntu 20.04 system is absolutely fresh and updated.

Please see attached pic
![Bildschirmfoto_2021-12-31_16-38-03](https://user-images.githubusercontent.com/17964433/147830804-e219b2cf-4431-4305-a526-979a170fbc2b.png)

**Comment by nostromo123** [comment]
OK. I'll purge clang-10 and change to clang-11 and report back ....

**Comment by raphaelcoeffic** [comment]
> OK. I'll purge clang-10 and change to clang-11 and report back ....

It's probably the python module which was updated.

**Comment by nostromo123** [comment]
@gagarinlg

Your info did it. Thx!

The following packages were installed:

![Bildschirmfoto_2021-12-31_17-14-02](https://user-images.githubusercontent.com/17964433/147832008-690fb9d5-3a07-49d5-8685-413f2d921b60.png)

I am not up to find the source of that issue, but now the command 

$ make -j`nproc` firmware

worked! Hope, this is the only issue ;-)
