### ISSUE TITLE
Fill mixer-script-line %-value with useful information

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1330]
What should be the purpose of the %-value at the end of each mixer-script line? 

It displays the member `ScriptInternalData.instructions`. This maybe a usefull information to get an overview how computational intense a script can be, but this field is never  gets filled with something. 
In `luaTask()` a measure is calulated but I can't find a way to reference the script data structure.

**Comment by wimalopaan** [comment]
@jfrickmann Do you have any hints here?
If not, then I suggest to remove this value at all for the moment.

**Comment by jfrickmann** [comment]
No, I suggest that we remove it

**Comment by pfeerick** [comment]
I agree, it should go if there is nothing useful to fill that space.

**Comment by wimalopaan** [comment]
Fixed in #1317

**Comment by wimalopaan** [comment]
Maybe #1340  is of interest also.
