### ISSUE TITLE
Mode 2 and Mode 4 options are swapped over

### ISSUE THREAD

**Issue by Aaronsss** [EdgeTX/edgetx#1334]
**Describe the bug**
Mode 2 and Mode 4 options seem to be the wrong way around. I tried playing about with the default channel order on the radio but it didn't seem to change anything

Mode 2 should be throttle and yaw on the left stick, pitch and roll on the right stick

**General information**
 - EdgeTX version (e.g. 2.4.0 or nightly and #commit number) 2.6.0 RC1
 - Hardware (e.g. Frsky X9D+ or RM TX12S) NV14

**Comment by eshifri** [comment]
Can you please provide some details/describe the sequence?
I cannot reproduce it: for mode 2 throttle is channel 3 and is on the left stick; rudder is channel 4 is on the left stick as well.

**Comment by Aaronsss** [comment]
With the left stick pushed to top right:
With mode 2 selected on the radio:
![image](https://user-images.githubusercontent.com/23297034/147858929-96ded4c5-26ab-41d6-b238-c9a69acbfc51.png)
With mode 4 selected on the radio:
![image](https://user-images.githubusercontent.com/23297034/147858910-d8d37f94-1d69-4456-b784-94df7ea7da73.png)

The transmitter has been set to AETR as well.

**Comment by eshifri** [comment]
Thank you!
Can you please take a look at the channel monitor on the thee TX as well?

**Comment by Aaronsss** [comment]
Mode 2
![IMG_20220101_195815](https://user-images.githubusercontent.com/23297034/147859127-31c028a8-9d5e-4774-987a-4ad887c280e2.jpg)

Mode 4
![IMG_20220101_195753](https://user-images.githubusercontent.com/23297034/147859138-986915bc-c08e-4f53-afba-21a84fccdf35.jpg)

**Comment by eshifri** [comment]
Looks convincing, but I still cannot reproduce it. :-)

**Comment by rotorman** [comment]
@Aaronsss what EdgeTX FW version you are running? What does the Info tab say (GitHub commit hash)?

**Comment by Aaronsss** [comment]
![IMG_20220101_202448](https://user-images.githubusercontent.com/23297034/147859526-cdd0ca95-72f8-4c97-aa54-c5e476584cd0.jpg)

**Comment by rotorman** [comment]
Thank you for the pic above! How is the mapping on the analogs diagnose page? Which channel corresponds to which stick and axis?

**Comment by Aaronsss** [comment]
On the analogs test page:
01 = yaw
02 = throttle
03 = pitch
04 = roll
05 = VRA
06 = VBR

**Comment by rotorman** [comment]
The order of sticks matches my FlySky gimbal order, thus I wonder if you just have some settings wrong.
Can you try the following - take the SD card of your NV and rename \MODELS to \MODELS_old and \RADIO to \RADIO_old. Put the card back in radio and re-run the calib, set your more and stick order and create a test model. Do the channels match now?

**Comment by Aaronsss** [comment]
Ok I have figured out what has happened. When I flashed the radio the default channel map was RETA. I updated to AETR but from this point on I was copying the model01. 

Is there a way to update the channel map of each model that has already been created? It has taken me the best part of 2 days to get my models back to almost where they were on the old flysky version so don't want to do that again.

**Comment by rotorman** [comment]
The radio and model settings of 2.6.0rc1 are in YAML - a human readable file that you can edit with a text editor (just make a backup first, in case you mess something up, you can always go back to old state).

**Comment by Aaronsss** [comment]
Ah I have figured it out I just need to swap RUD and AIL on the inputs tab so that fixes the issue for me.

Is it worth altering the code so that AETR is the default upon first flash to prevent others having the same problem?

**Comment by raphaelcoeffic** [comment]
> Ah I have figured it out I just need to swap RUD and AIL on the inputs tab so that fixes the issue for me.
> 
> Is it worth altering the code so that AETR is the default upon first flash to prevent others having the same problem?

The order you enter applies only to new models, not in general, as you can freely map whatever you want to the channels you want.

what would make sense however would be to ask the user for that setting before creating the first model.

**Comment by pfeerick** [comment]
Indeed... and if this isn't an issue already was something I mentioned early on... I'll work on this... as I want to sort out the calibration page anyway... has one or two things I really find annoying...
