### ISSUE TITLE
Latency issue with santa 2.6

### ISSUE THREAD

**Issue by bjou12** [EdgeTX/edgetx#1336]
quad feel not locked in lots of latency

**Comment by pfeerick** [comment]
Need a little more information before anything can be done about that. Out of the questions from the template you've said what version of the firmware you're running. What transmitter is this on? What RF system (protocol/tx module and receiver)? What version of betaflight? Is this new behaviour? If so, what did you change?

**Comment by gagarinlg** [comment]
closed, no response
