### ISSUE TITLE
invalid node in radio.yml message after successfull conversion to Santa 2.6 RC2

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#1349]
I've convert the edgetx 2.5 SD Card with simulator succesfull. After restarting the simulator I got this message:
![image](https://user-images.githubusercontent.com/15068446/148194443-a36f2761-19d9-4ffe-8ca7-7a29e4b93b32.png)

Is this a generally issue or only my radio.yml file?

**Comment by raphaelcoeffic** [comment]
We would need to see the files (binaries you converted from, and resulting YAML files). When you say you "convert[ed] the edgetx 2.5 SD Card with simulator succesfull[y]", do you mean in Companion? Or in the standalone simulation? How exactly did you proceed?

**Comment by ParkerEde** [comment]
I mean the standalone simulator in
"C:\Program Files\EdgeTX\Companion 2.6\simulator.exe"
with DataSource "SD Path"
The SD Card Path contains the edgeTX 2.5 files (with bin files).
The first launch shows a message "SD card conversion required". This procedure ends with success. Then I close the simulator and start it again. Then the message with invalid node appears.
[RADIO.zip](https://github.com/EdgeTX/edgetx/files/7814247/RADIO.zip)
