### ISSUE TITLE
Mainview 1-5 all options (Top bar, Flight mode...) are deactivated in 2.6 RC2

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#1351]
I open an otx file created in edgetx 2.5 where the Main view 1-5 options like Top bar, Flight mode, Sliders and so on was activated.
In edgetx 2.6 all these options are deactivated.
After conversion with the standalone simulator, these options are deactivated too.
It seems, that there is a migration 2.5 to 2.6 issue regarding the main view options and colors.
Edit: HorusX10 Express

**Comment by dwheel** [comment]
Jumper T16, and Radiomaster Tx16 are in use here. I only have 1 view, but it does not load correctly in the companion simulator. It does load correctly in the transmitters.

I will attach the model and radio files:
[model2.zip](https://github.com/EdgeTX/edgetx/files/7816097/model2.zip)
[radio.zip](https://github.com/EdgeTX/edgetx/files/7816098/radio.zip)
.

**Comment by koaxheli** [comment]
Transmitter Radiomaster TX16S
In the companion all option fields are returned with 0.
In the transmitter, it is OK.
ScreenData: 
   0:
      LayoutId: "Layout1x1"
      layoutData: 
         Zones: 
            0:
               WidgetName: "showal0.9"
               widgetData: 
                  Options: 
                     0:
                        type: Boolean
                        value: 
                           bool value: 1
                     1:
                        type: color
                        value: 
                           Color: 0xF8FCF8
                     2:
                        Type: color
                        Value: 
                           Color: 0x0000
         Options: 
            0:
               Type: Boolean
               value: 
                  bool value: 1
            1:
               type: Bool
               value: 
                  boolValue: 0
            2:
               type: Bool
               value: 
                  boolValue: 1
            3:
               type: Bool
               value: 
                  boolValue: 1
            4:
               type: Bool
               value: 
                  boolValue: 0
![screenshot_tx16s_22-01-05_20-52-51](https://user-images.githubusercontent.com/92114465/148282748-bb552a9a-cd16-4a07-bbe6-337f76157b7b.png)
![screenshot_tx16s_22-01-05_20-53-00](https://user-images.githubusercontent.com/92114465/148282771-85078ec8-aeb7-4ca6-9f13-61925cc3e81b.png)
![screenshot_tx16s_22-01-05_20-53-10](https://user-images.githubusercontent.com/92114465/148282791-d3bb175d-26e1-491a-89b5-5c514b2dd162.png)
![screenshot_tx16s_22-01-05_20-53-30](https://user-images.githubusercontent.com/92114465/148282824-8b5c483a-03c2-43a7-9065-599747a71549.png)

**Comment by raphaelcoeffic** [comment]
From what I can tell, this seems windows specific. It could not be reproduced on Linux or Mac.
