### ISSUE TITLE
Tx16s update the internal module with EdgeTX

### ISSUE THREAD

**Issue by KirkTz** [EdgeTX/edgetx#1355]
hi ,new user to Edgetx 2.5 (Tx16s) ,i need to update the internal module ,i just download the latest .. mm-stm-ppm-aetr-v1.3.3.0.bin but i 'm getting thiserror msg when i try to flash it,any ideas ?? what i'm missing ,,and also can i copy and run the lua scripts that was in the opentx scripts folder ?? 
![IMG_20220105_210621](https://user-images.githubusercontent.com/97219749/148350541-e280e0e4-ada0-41ac-992b-2faf3e28508d.jpg)
?

**Comment by pfeerick** [comment]
`mm-stm-ppm` is the *wrong* firmware for the internal MPM on the TX16S. Go back to the [MPM Firmware Download](https://downloads.multi-module.org/) page, make sure you pick the RadioMaster TX16S, and you'll get the correct firmware for your TX16S internal MPM. You can also then get the current/matching version of the Lua scripts. 

![image](https://user-images.githubusercontent.com/5500713/148369229-210bced9-069f-4dbb-bb32-79ff37d7a443.png)

**Comment by KirkTz** [comment]
Thank you very much
