### ISSUE TITLE
Spectrum analyzer shows spurious data w/o RF-Modules

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#136]
Tested f9aeebca on RM TX16S that has internal Multimodule removed. JR-Bay is empty. The spectrum analyzer page shows spurious data:
https://www.youtube.com/watch?v=Uiw_UYmUM9k

**Comment by raphaelcoeffic** [comment]
Looks like the “re-usable buffer” is not blanked on start-up of the tool.
