### ISSUE TITLE
No access to the internal modul in 2.6 RC2

### ISSUE THREAD

**Issue by weixelgeist** [EdgeTX/edgetx#1369]
On my Radiomaster TX16S I cannot switch on the Internal RF in 2.6 RC2
In the mode scroll down menu is only one option: OFF
In the External RF scroll down menu all options are present

![PXL_20220107_090212856](https://user-images.githubusercontent.com/57415068/148519924-61c00d4b-e2ac-4828-a05e-95e4ebc92aa2.jpg)

**Comment by pfeerick** [comment]
Try the following and see if that fixes it for you:

https://user-images.githubusercontent.com/5500713/148522714-1129777c-fb3c-441f-b354-1950ee3018cf.mp4

**Comment by raphaelcoeffic** [comment]
@weixelgeist where did you update from? Some nightly build, 2.5, or something else?

**Comment by weixelgeist** [comment]
The following did fix it:
Radio Settings => Hardware tab => Internal module => MULTI
Thank you
