### ISSUE TITLE
Radio Settings - Global Functions  - Play Track - Sound Files unavailable

### ISSUE THREAD

**Issue by MRC3742** [EdgeTX/edgetx#137]
**Describe the bug**
Radio Settings - Global Functions  - Play Track - Sound Files unavailable.
Only two letter wav files will be displayed (ie lq.wav) but won't play.

**To Reproduce**
1. Select "Radio Settings"
2. Scroll to "GLOBAL FUNCTIONS"
3. Select a switch and position
4. Select "Play Track"
5. Under "Value" only "--" and "lq.wav" are displayed
6. Selecting "lq.wav" is available but will not play using assigned switch position

**General information**
 - EdgeTX: version 2.4.0 (f9aeebca) 2021-05-31
 - Hardware: Jumper T16

**Comment by TMac54** [comment]
This is also mentioned in Issue writeup #118
