### ISSUE TITLE
Companion displays RX # as Size 

### ISSUE THREAD

**Issue by piotrva** [EdgeTX/edgetx#1375]
**Describe the bug**
Companion displays RX # as Size, while Size is not displayed for any of the models.

**Screenshots**
![image](https://user-images.githubusercontent.com/5657414/148566493-6522d1f0-8dd8-405b-91b2-0f6292d5f346.png)

**General information**
 - EdgeTX version: PR #1341
 - Hardware: Radiomaster TX12
 - Companion: 2.7.0 dev PR #1362

**Comment by elecpower** [comment]
Size was for radios that stored their settings in eeprom which has a total size limit and with the move to yaml for all radios the need to keep track of per model and total size is no longer necessary.
Also the calculation has a high overhead on performance and memory.
