### ISSUE TITLE
Please add HARDWARE_TOUCH option for T18/TX18S build

### ISSUE THREAD

**Issue by Ender1967** [EdgeTX/edgetx#138]
set(HARDWARE_TOUCH YES)
T18 and T1X18S have hardware touch interface, some models just don't have the touch layer on top of the LCD screen installed.
RadioKing TX18S has the same hardware as Jumper T18 and can use the same image and had the touch screen installed.
Please consider adding the hardware touch option for T18/TX18S.

**Comment by Ender1967** [comment]
set(HARDWARE_TOUCH YES)
T18 and T1X18S have hardware touch interface, some models just don't have the touch layer on top of the LCD screen installed.
RadioKing TX18S has the same hardware as Jumper T18 and can use the same image and had the touch screen installed.
Please consider adding the hardware touch option for T18/TX18S.

**Comment by raphaelcoeffic** [comment]
@Ender1967 ATM, the GT911 is not configured the right way. Feel free to use the binaries in the PR to check what I mean. We will have to wait for Jumper (or somebody else) to come up with the proper configuration, as I have other bugs to fix first.
