### ISSUE TITLE
X9D+ models incorrect internal module protocol choices

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#1382]
**Describe the bug**
When editing a model setup the only available choices are OFF and Multi in radio sim and OFF in Companion.
Note: this radio does not have Internal module support in hardware settings.

**To Reproduce**
Edit a model and try to change the Internal RF (radio) or Internal Module Protocol (Companion).

**Expected behavior**
Choices appropriate for the radio.

**Screenshots**
![screenshot_x9d+_22-01-08_07-55-17](https://user-images.githubusercontent.com/15316949/148606601-8295b80d-7c49-4b08-bd59-e87c9bb71e04.png)

**General information**
 - EdgeTX version 2.6 main
 - Hardware simulator Frsky X9D+
 - Companion version 2.6 main

**Comment by pfeerick** [comment]
I've having trouble reproducing, but I'm using the #1342 Companion/Simulator if it is version specific - I've tried X9D+2019, X9D+ and X9D and all seem to be correctly going through OFF, ACCESS/ACCST,XJT as options?

**Comment by elecpower** [comment]
By bad, the radio sim behaves after I performed a clean build of everything. Can only assume a cached entry.
However Companion is not functioning as expected so up to me to fix.
