### ISSUE TITLE
Nirvana - Ghost Support is missing

### ISSUE THREAD

**Issue by stefan73** [EdgeTX/edgetx#1387]
EdgeTX 2.5 release: Cannot select ImmersionRC ghost as protocol for external module

**To Reproduce**
Try to select ghost as protocol within model settings. Note: It is available in the companion in NV14 mode but setting from there also does not work.

**Expected behavior**
Ghost selectable & works.

**General information**
EdgeTX 2.5 release

**Comment by eshifri** [comment]
Are you saying it is not available in the list?
It is present in the 2.6.

**Comment by pfeerick** [comment]
It was not enabled in the stock builds for 2.5 - was a couple of weeks ago it was turned on for 2.6

**Comment by stefan73** [comment]
Confirmed - it works in 2.6
