### ISSUE TITLE
Support Flysky Gimbal Mod

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#140]
Flysky has a full aluminum gimbal, that is very cool to mod it in T16/TX16S, etc.  It has serial output, so it is possible to reconfigure the gimbal port for USART4 connection.

I will make a branch and commit the changes as build option,

**Comment by raphaelcoeffic** [comment]
@richardclli I'd be happy to include this mod as a compilation option, no issue on my end.

**Comment by richardclli** [comment]
Please review my pull request about this fix, I have already tested with my TX16S.
