### ISSUE TITLE
Companion should display commit number of compiled binary.

### ISSUE THREAD

**Issue by piotrva** [EdgeTX/edgetx#1405]
**Describe the bug**
In my opinion, in order to make issue reporting easier Companion should include commit number of the build in "About" screen.
This is how firmware version is presented in radios, where in addition to defined version you can see also commit number.

Also can fix year to 2022 ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/5657414/148767672-5ca00e0a-7eb1-45a5-ada9-0a25c86fae76.png)

**General information**
 - Companion: 2.7.0 "dev", Jan 10 2022, #1402

**Comment by Eldenroot** [comment]
Yes, also a github report link should be added

**Comment by pfeerick** [comment]
Thanks for this... I was just thinking that the other day :)
