### ISSUE TITLE
 Touch screen does not work in the shutdown confirmation with the model still powered (2.6RC2)

### ISSUE THREAD

**Issue by RipperGOT** [EdgeTX/edgetx#1428]
Only works the wheel for confirmation.

**To Reproduce**
-Turn on TX 
-Turn on RX 
-Turn off TX and try to press the touch screen for confirmate the shut down.

 - EdgeTX 2.6 RC2
 - TX16S

**Comment by pfeerick** [comment]
Is this related? It seems the LCD being off when the poweroff triggered is the issue there :  https://github.com/EdgeTX/edgetx/issues/1335

**Comment by RipperGOT** [comment]
> Is this related? It seems the LCD being off when the poweroff triggered is the issue there : #1335

Omg! I did a good search... Sorry!!!!🤦‍♂️

Yes it's the same but backwards.  
If I have the screen on and try to turn it off, the touch screen does not work.
With the screen off:  turn off the radio, the screen does not appear until you move a stick, the screen turns on and the touch works. 

Close it if you consider that it is duplicated.

**Comment by pfeerick** [comment]
Duplicate, but also different... since I thought touch still worked if screen was on, so it's probably not what I thought it was causing it...

**Comment by gagarinlg** [comment]
I'll take a look
