### ISSUE TITLE
1kHz RC rates

### ISSUE THREAD

**Issue by JyeSmith** [EdgeTX/edgetx#1432]
Looks like ExpressLRS is getting ready for 1kHz :muscle: 

https://github.com/ExpressLRS/ExpressLRS/pull/1277

The mixer might need some work to support it :grinning: 

https://github.com/EdgeTX/edgetx/blob/fc2142ec78b81b763c8143395cf1a3ddf14271b0/radio/src/mixer_scheduler.h#L28

**Comment by pfeerick** [comment]
"Tell him he's dreaming" 😆

**Comment by raphaelcoeffic** [comment]
@JyeSmith we might even need some means to either:
- enforce some minimalistic version so we can guarantee runtimes
- or, have some measurements showing if the current settings allows for keeping up
