### ISSUE TITLE
Logical switch Edge not working correctly

### ISSUE THREAD

**Issue by borsti2000** [EdgeTX/edgetx#1439]
Bug description:
New Model in 2.6.0 RC3
Creation of logical switches L01-L09 --> Edge, V1 SG down, V2 0,0 / imeadedly,  L01 -1 sec L02 -2 sec L03 -3 sec .....
Input in Mixers 1-9 (CH1 l01 / CH2 L02....)

Expected:  Switch SG down, all chanel otput to 100% and switch off after 1 to 9 sec

Result : No changes on CH1. 

Additional Test: change of L01 to 5 sec. It seems that L01 is input of CH2.

**Comment by eshifri** [comment]
HW details, please?

**Comment by borsti2000** [comment]
Oh sorry. TX16s. You need more info?

**Comment by borsti2000** [comment]
I still try to test hats happens.
Now I have some additional info.
I seems that for example the Log.switch #L05 use the parameter of the line from L04.
To test it, I create two Lines (L05 + L04) with Edge and the same parameters. Exept the time (L05 --> 1 sec / L04 --> 5 sec)
In the chanal I use only the L05 (which should have 1 sec) but in simulation the output chanal is 5 sec "on"

**Comment by eshifri** [comment]
Interesting: looks like I cannot reproduce it on TX16S. At least the LS works - did not try to manipulate channels.

**Comment by pfeerick** [comment]
I've not tried this on hardware yet, but simulator is screwy with this config (which I "think" is what @borsti2000 is describing?). The config file reads fine, just simu is misbehaving on the mixes page (logical switches all seem fine). 

![image](https://user-images.githubusercontent.com/5500713/149650809-bfde6b15-0e0a-417b-a61e-e706f750171f.png)

[issue1439.etx.zip](https://github.com/EdgeTX/edgetx/files/7876528/issue1439.etx.zip)
