### ISSUE TITLE
Several settings getting lost / changed when using companion. 2.6RC3

### ISSUE THREAD

**Issue by jeffhendrix** [EdgeTX/edgetx#1447]
After reading models and settings, several settings get changed.
Just reading and writing models back out will make the changes

Some of the issues seen
Backlight OFF brightness gets set to lowest value (OFF)
Pwr Off delay gets set back to 2s (after changing it to 0 on radio)

In Flight Modes, Trims set to Trim disabled are shown blank and always set back to Own Trim when written back to radio

In logical switches, "Trim 6 Up" is changed to "Trim 6 Down" and "Trim 6 Down" is changed to "Trim 5 Up"

Trainer port is changed from "Master/Bluetooth" to "Master/Jack"

**General information**
 - EdgeTX version 2.6RC3 #fac0eed6
 - Hardware (RM TX16S)
 
![settings](https://user-images.githubusercontent.com/7000366/149650680-53dfefd3-56fb-407e-8f3e-64c3e58ad472.png)
![trims in flight mode](https://user-images.githubusercontent.com/7000366/149650684-07eccad6-6be0-464a-8ffd-21beeac99495.png)
![logical trims](https://user-images.githubusercontent.com/7000366/149650679-fd360465-094e-48d0-9a6a-52b0c3b4efdc.png)
![trainer port](https://user-images.githubusercontent.com/7000366/149650682-2af37ec2-2d5e-4ec5-945a-ad33c6450873.png)

**Comment by raphaelcoeffic** [comment]
> Trainer port is changed from "Master/Bluetooth" to "Master/Jack"

This one probably roots from the simulator not supporting bluetooth (check the radio settings, the bluetooth mode is not shown). This move the simulator to cancel the trainer setting as it is considered invalid.
