### ISSUE TITLE
Rebind Flysky rx

### ISSUE THREAD

**Issue by Mikey1968** [EdgeTX/edgetx#1458]
I been using the flysky rxs in myy planes for weeks using version 2.5 , but when I updated to 2.6 RC2 , I have to rebind my rxs everytime I fly . Not sure if this is a bug or what

**Comment by pfeerick** [comment]
D8 or D16? As it seems there may be a bug affecting both OpenTX and EdgeTX for D8 receivers as I've seen a few mentions now of this, and that turning the internal module on and off again seems to fix it (no rebind necessary). 

What Transmitter? And you're on RC2, not RC3?

**Comment by Mikey1968** [comment]
Jumper T18 pro2 
There was no RC3 at the time I used RC2
I went back to 2.5 until there's a fix

**Comment by pfeerick** [comment]
I've just been using a FS-iA6B receiver with effectively 2.6.0-RC3 and had no issues with needing to rebind. Changing models and power cycling the radio. TX16S+MPM.

**Comment by kasatka60** [comment]
EdgeTX 2.6, Jumper T-lite multimodule, flysky resiver. You always have to bind the receiver when you change the model

**Comment by kasatka60** [comment]
Can this bug be fixed?

**Comment by Mikey1968** [comment]
That's not the problem. I did that in 2.5 but when you upgrade to 2.6 then you have to rebind every time. I went back to 2.5 and works fine

**Comment by kasatka60** [comment]
Tomorrow / the day after tomorrow I will check again at my place.

**Comment by pfeerick** [comment]
Can you be more specific about the receiver than just "Flysky receiver"? Anyone have any idea as to what model of receiver your are using? i.e. I have been using genuine Flysky FS-iA6B and FS-iA10B receivers and haven't needed to rebind, but in my case it has been with TX16S, haven't tried the T-Lite yet.

**Comment by kasatka60** [comment]
jumper t-lite edgetx 2.6 multimodule 1.3.3.7, Flysky X6B, FlySky FS-iA10B, FlySky FS-iA6B

**Comment by kasatka60** [comment]
Everything works fine for me.

**Comment by tommp100** [comment]
I am having a similar experience with 2 Flysky receivers (FS-IA6B) and a Radiomaster TX16S.  Only one will retain its binding (the one last bound).  If I attempt to bind the second receiver it will retain its binding but the first one will lose its binding.  I've assigned discrete numbers to the receivers (field next to 'bind') with no effect. I have not attempted using a different version of EdgeTX

**Comment by tommp100** [comment]
f

**Comment by kasatka60** [comment]
Change the receiver number in the settings and everything will work.

**Comment by tommp100** [comment]
Changing the receiver number worked.
Thanks for the prodding.  I had given up on ever using my second Flysky FS-IA6B with the TX16S.
Just for anyone reading this:
The first thing I did was power up the model that was bound.
When I changed the receiver number I got the "telemetry lost" announcement.
So I put it  back to the original receiver number and got the "telemetry recovered" announcement.
I put in the bind plug on the unbound Flysky receiver.
I changed the receiver number as you suggested.
Powered up the receiver and bound it as usual.
I tested both receivers and the telemetry to each seems to be rock solid and independent.
Thank you.

**Comment by pfeerick** [comment]
Glad you got it working, good to know for myself also. I knew on the upcoming EL18 with AFHDS3 rebinding with the same RX number was a problem (as there are settings stored in each slot), but as I didn't realise this would clobber on the MPM with AFHDS2A.
