### ISSUE TITLE
V 2.6 On-screen Keyboard and Character list

### ISSUE THREAD

**Issue by chucky-whiskers** [EdgeTX/edgetx#1464]
The keyboard, as well as the character list selected by the scroll wheel on my TX16S Max are missing some very valuable characters such as punctuation or various symbols such as degrees°; percent%; comma,; period.; parentheses(); and ampersand&. I frequently used some of these in OpenTX and was disappointed to find they are not available in EdgeTX yet.

**Comment by raphaelcoeffic** [comment]
Just so you know: we are migrating to a better system, including a better character set support, so that we should be able to have some more in 2.7.

**Comment by gagarinlg** [comment]
You might want to check the next nightly, but it is not flight ready yet.

**Comment by chucky-whiskers** [comment]
Thanks for reaching out!

**Comment by gagarinlg** [comment]
close, because we are now using the LVGL keyboard, which has the missing characters
