### ISSUE TITLE
Ghost 12bit Check box missing

### ISSUE THREAD

**Issue by rcquad808** [EdgeTX/edgetx#1471]
Installed 2.7.0  (dcbdde2b) Nightly build 

There is no "Check box" selection for "12bit" in the "Model Setup" menu screen.

Radiomaster TX16S
![IMG_8869](https://user-images.githubusercontent.com/25781020/149992728-dd7b4d48-ec41-4287-8971-0fa0421de922.JPG)
![IMG_8868](https://user-images.githubusercontent.com/25781020/149992734-ced3817d-b156-41cc-bfce-08744f0a5a05.JPG)

**Comment by raphaelcoeffic** [comment]
PR #1233 is not yet merged, so this is absolutely normal.
