### ISSUE TITLE
Trim6 up/down missing in logical switches after conversion from otx/bin

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#1472]
EdgeTX 2.6.0RC3
1. Open a OTX File in Companion with a model that has a logical switch OR Trim6u Trim6d. So far it's okay.
![image](https://user-images.githubusercontent.com/15068446/150108683-24223acf-d6b2-48a0-95f4-721729a671b4.png)

2. Save the file in etx file format
3. open the new etx file in companion, check the logical switches => Trim6 up is missing
![image](https://user-images.githubusercontent.com/15068446/150108866-b7cefbef-69bf-4436-8769-52a73d3fad87.png)

4. start companion simulator of this model, check the logical switches => Trim6 down is missing
![image](https://user-images.githubusercontent.com/15068446/150109020-b3309692-a351-48e3-8d86-f57fb4b071dd.png)

Same with the standalone Simulator after converting models.

Please see attached otx and etx file
[EdgeTX_Trim6_bug.zip](https://github.com/EdgeTX/edgetx/files/7896099/EdgeTX_Trim6_bug.zip)

**Comment by ParkerEde** [comment]
Trim5 up/down is okay in Companion after conversion:
![image](https://user-images.githubusercontent.com/15068446/150122430-bd34db12-ee0b-4153-ba20-196894f1c8a2.png)

But the simulator shows this:
![image](https://user-images.githubusercontent.com/15068446/150122485-95de3f9f-a121-42e9-b6c8-2088fa0cf960.png)

There seems to be a shift of the switches here.

**Comment by pfeerick** [comment]
I believe this was fixed in #1449, which will either be part of RC4 or the final 2.6.0 release. 

If you are on Windows you can download the installer for the latest 2.6.0 branch Companion here => https://github.com/EdgeTX/edgetx/suites/4969517456/artifacts/144868852

**Comment by ParkerEde** [comment]
thank you. This companion works correctly. Sorry for the double post.

**Comment by ParkerEde** [comment]
Hi @pfeerick . To prevent double posts, do you think it is possible, that the companion will also be find in ASSETS of the nightlies?
Kind regards

**Comment by pfeerick** [comment]
Probably not, as it takes too long to build. I'll look if there is some way to link to already built versions though.

If people are running beta versions then there is *some* expectation they use the latest version GitHub actions has built if there is an issue and also look at commit logs before opening issues (or at least tried). And if that happens and an issue still gets opened, so be it.
