### ISSUE TITLE
Different UART setting for SBUS on horus and taranis

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1473]
Looking into the UART initialization code for SBUS input I found different settings:

Horus: 2 stop bits
Taranis 1 stop bit

AFAIK the 2 stop bits are correct.

(see also: #1462 )

**Comment by gagarinlg** [comment]
is this still an issue?

**Comment by richardclli** [comment]
> is this still an issue?

I do not think it is still there after @raphaelcoeffic changed the serial module API, all code should be shared now,.  @wimalopaan Any comments?

**Comment by wimalopaan** [comment]
I think it is fixed by the rewrite. But I did not make any checks ...
