### ISSUE TITLE
Fields are filled incorrectly in the companion

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#1474]
Transmitter TX16S 
cpn V2.6.0rc3

In the companion the sources in the mixers are
are not read in correctly or not at all.
It concerns the logical switches

![Schalter](https://user-images.githubusercontent.com/92114465/150137430-daae6934-1943-4e4a-9ee2-a23c4d36b2b7.PNG)

 - EdgeTX version (e.g. 2.6.0 rc3)
 - Hardware (e.g. RM TX16S)

**Comment by pfeerick** [comment]
Can you check if the build of Companion mentioned here (sorry, on phone and can't link it directly) has this problem still?
 https://github.com/EdgeTX/edgetx/issues/1472#issuecomment-1016389617

**Comment by ParkerEde** [comment]
Hi @pfeerick, yes I will check....

**Comment by ParkerEde** [comment]
I verified otx / etx file. It looks good to me:
![image](https://user-images.githubusercontent.com/15068446/150297396-f762e3bb-8ece-4714-a335-846f366c1920.png)

Is this test okay so far, or should I test anything else in this case, or in another way?

**Comment by ParkerEde** [comment]
hi again,
If I use LS for sources in mixes (as you wrote) then L64 is missing after saving in etx format and reopen:
![image](https://user-images.githubusercontent.com/15068446/150300238-dfab0766-1ba8-4a4c-a012-40fbe37cf821.png)
