### ISSUE TITLE
Not possible to flash iXJT module on 2.6.0RC3/Nightly

### ISSUE THREAD

**Issue by mhon44** [EdgeTX/edgetx#1482]
Hello, 

I have run into a problem with flashing Frsky firmware to radio

**Describe the bug**
Since updating to RC3, even latest nightly, not possible to flash internal module on Frsky X-Lite.
Reverted FW back to 2.5 - all went good.

**To Reproduce**
Update to 2.6.0RC3 on radio with iXJT module.
Flash internal module.

**Expected behavior**
Update of the internal iXJT ACCST module to version 2.x 

**General information**
 - EdgeTX version 2.6.0RC3 / Nightly (e.g. 2.4.0 or nightly and #commit number)
 - Hardware FrSky X-Lite

**Comment by raphaelcoeffic** [comment]
@mhon44 where is it exactly failing to flash? Can you please add a screenshot?

**Comment by raphaelcoeffic** [comment]
By the way, have you tried to flash a receiver via S.PORT? It is basically the same code being used at both places. The only difference is which power is line is turned on. It is the exact same S.PORT line used to flash a internal module, external module or a receiver via S.PORT output.

**Comment by mhon44** [comment]
> @mhon44 where is it exactly failing to flash? Can you please add a screenshot?

Right at the beginning - FW sync error not responding. Unfortunately don't have screenshot

Receiver via S.Port worked without any issues.

**Comment by Nerenye** [comment]
I tried with horus x12s and it works for me
