### ISSUE TITLE
Frsky D16 Protocol s.port Telemetry Missing

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#1491]
I have a friend used the RM receiver R161, and used the S.Port to send back telemetry, the included figures are from OpenTX 2.3.9 and compared to EdgeTX 2.6.0 released version, EdgeTX has a lot of sensors missing.  And he tried EdgeTX 2.5.0 as well.  Similar result, a lot of sensors missing.

OpenTX 2.3.9
![150479170-657feebf-b954-41b6-b819-a42f38874ab4](https://user-images.githubusercontent.com/18414861/150726147-0de1b385-e57c-4e7f-8bee-8acab4163a99.jpg)

EdgeTX 2.6.0
![IMG 002](https://user-images.githubusercontent.com/18414861/150726166-c84dcbcf-3f5a-4e20-8f60-c54e2fc1b1bd.png)

I am thinking if the Frsky Hub telemetry is broken from day 1 in the OpenTX 2.4 branch?

And this is not related to https://github.com/EdgeTX/edgetx/issues/1139

**General information**
 - EdgeTX 2.6.0 release
 - Hardware RM TX16S

**Comment by pfeerick** [comment]
But possible correlation / link to https://github.com/EdgeTX/edgetx/issues/1260

**Comment by CNzhangsir** [comment]
This problem is the problem I encountered, because I used the Yaapu lua script on the OpenTX 2.3.9 version before. When using the frsky D16 protocol in the all-in-one tuner built in the TX16s, I can use the s of the Radiomaster R161 receiver. The port's telemetry returns a lot of sensor data from the Pixhawk's Ardupilot firmware and provides it to Yaapu's HUI. Now, I tested various versions from EdgeTX 2.4, 2.5, 2.6RC1-3 and found that none of them solved the problem.

The backhaul telemetry of TBS crsf on each version of edgeTX is normal.

**Comment by pfeerick** [comment]
So to be clear:
- Transmitter: TX16S, using MPM
- Receiver: R161
- Telemetry source: Pixhawk Ardupilot, feeding into R161 SPort

And only those five sensors show up on EdgeTX (which look to be the top rows on OpenTX view). 

On interesting thing which I'm not sure of the relevance / importance of is that they don't have an ID number... all the missing ones are '0' ... just thinking that there had better not be something in the code around the telemetry that ignores `0` 😆

**Comment by richardclli** [comment]
I think this is the case:

In tememetry_sensors.cpp:

bool TelemetrySensor::isAvailable() const
{
  return ZLEN(label) > 0;
}

And in model_telemetry.cpp:

  for (uint8_t idx = 0, count = 0; idx < MAX_TELEMETRY_SENSORS; idx++) {
    if (g_model.telemetrySensors[idx].isAvailable()) {
      auto txt = new StaticText(window, grid.getLabelSlot(), std::to_string(idx), BUTTON_BACKGROUND, CENTERED | COLOR_THEME_PRIMARY1);
      Button * button = new SensorButton(window, grid.getFieldSlot(), idx, ++count);

Well, for ID = 0, label = NULL and ...... Opts out.

**Comment by richardclli** [comment]
When ID is not found in the known list, the ID is a custom ID and the ID will be decoded to become a 4 chars label.  In this case, the isAvailable() should return true.  The problem is not in the display?

**Comment by pfeerick** [comment]
Matek F765-WSE which can run Ardupilot arrived today and I have R161 receivers so hopefully I can reproduce this in the next couple of days.

**Comment by pfeerick** [comment]
I think I finally have ardupilot and sport telemetry going with the R161 and  F765-WSE ... in addition to the four telemetry elements from the R161 receiver itself, I only get GPS from Ardupilot (i.e. as shown in the OP screenshot) - so hopefully there are more telementry elements coming down the feed and I'm just not see them. Just need to double check on either a B&W radio or possibly OTX and then might have some chance of finding out what is going on.

**Comment by pfeerick** [comment]
Right, so with Yappu, and frsky sport (4), you get telemetry sensors, but yappu doesn't seem happy with that by default. 

If I set it to frsky sport (10), you only get five sensors, but yappu is now happy, and if you run the yapuu frsky debug tool you see the data it is looking for is coming in...

![image](https://user-images.githubusercontent.com/5500713/153733551-bbb17be9-e0a6-4856-a3c9-ed1a21aeb9cd.png)
![image](https://user-images.githubusercontent.com/5500713/153733565-13d55376-0c5b-4b99-8144-ac7c88827451.png)
![image](https://user-images.githubusercontent.com/5500713/153733571-70f8441e-802d-494a-9025-36b775dba8a7.png)

With frsky sport (4) the yappu frsky debug tool shows no data.

**Comment by richardclli** [comment]
@CNzhangsir  So this can be closed?

**Comment by gagarinlg** [comment]
closed, no response
