### ISSUE TITLE
2.6.0 Switch Warnings on Pots

### ISSUE THREAD

**Issue by techfixpros** [EdgeTX/edgetx#1504]
eTx 2.6.0 b338d4d2
Taranis X9D (built in gitpod: cmake -DPCB=X9D -DDEFAULT_MODE=2 -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DLUA_MIXER=YES -DHAPTIC=YES -DCMAKE_BUILD_TYPE=Release ../)

On bootup, switch warning pops up and no switch/pots is shown when all switches are in correct position and Pot Warning:Manual is enabled. Disabling Pot Warning corrects issue. 

With Pot Warning set to Manual and warning is shown (without indicating which pot is in the wrong position), toggling a switch will show the switch position, and S1 - S2 being in the incorrect position. Cycling through all pot positions does not clear either pot from the warning state. Toggling switch to default position clears the warning indication for the switch, and S1 - S2 disappear without clearing the warning prompt.

Functioned properly in 2.5.0.

**Comment by dududu76** [comment]
Additionnally, the status of pots warnings are not correctly read/restored when backed-up to computer using companion.

**Comment by elecpower** [comment]
From X9D+ libsim

![screenshot_x9d+_22-05-20_21-19-00](https://user-images.githubusercontent.com/15316949/169517354-d410c225-ff16-4f07-ae57-59e63c789dfa.png)
