### ISSUE TITLE
point scrolling in curves settings does not work

### ISSUE THREAD

**Issue by Rip-Hunter** [EdgeTX/edgetx#1527]
**Describe the bug**
If you create a curve and set 6 or more points in it, then you cannot scroll the points to set the sixth and higher.
--------
Если создать кривую и в ней настроить 6 и больше точек, то прокрутить точки для настройки шестой и выше нельзя

**General information**
 - EdgeTX version 2.7.0 (5aa866ac)
 - Hardware flysky nv14

**Comment by pfeerick** [comment]
Sorry about that... It was actually fixed part of the way through 2.6.0 and then got overwritten in another PR... fix is in place again as indicated above and will be in next nightly or 2.6.1
