### ISSUE TITLE
background color depth

### ISSUE THREAD

**Issue by atazx** [EdgeTX/edgetx#1529]
**Describe the bug**
background image is not displayed correctly, maybe too low color depth? with opentx it was displayed correctly. the issue can also be viewed by taking a screenshot

**To Reproduce**
set a custom background image

**Expected behavior**
the image should be displayed correctly

**Screenshots**
backgound image used
![background used](https://user-images.githubusercontent.com/98708156/151712596-2e444114-b282-49dd-ac6d-36db4af98eb5.png)
screenshot
![screenshot](https://user-images.githubusercontent.com/98708156/151712821-aa96729b-2670-4ca2-8bef-1c654f1ac566.png)

**General information**
 - EdgeTX version 2.6
 - Hardware radiomaster tx16s

**Comment by atazx** [comment]
still present also in version 2.7.
How can I solve?

**Comment by rotorman** [comment]
The radio display is hooked up via RGB565, meaning 5 bits for red, 6 for green and 5 for blue, and thus the color output is somewhat limited, when compared to a normal PC with at least 8-bits per color.

See Sec. 2.7 of the TX16S schematic: https://www.rcgroups.com/forums/showthread.php?3869543-Blog-17-RadioMaster-TX16S-schematic-diagram

**Comment by atazx** [comment]
Ok, but the colors on opentx are a lot better...
i just flashed opentx and took a picture.
please see the attached picture:

OPENTX
![opentx](https://user-images.githubusercontent.com/98708156/165394738-55c053e8-eede-4de1-a26a-7384090a9b25.jpg)

EDGETX
![edgetx](https://user-images.githubusercontent.com/98708156/165394705-305d05ec-3b23-48d5-9b78-8c0caf3b8571.jpg)

**Comment by atazx** [comment]
As you can see from the two photos the ELRS logo is displayed differently, with lower quality on edgetx. The problem is therefore not limited only to the background but to all the images.
Should I change the title? or open another issue?
Am I the only one with this problem? how could i fix it? what other tests can i do?

**Comment by pfeerick** [comment]
You can change the title as it applies across the board to PNG image handling. It has been mentioned before, and I think it was worked around by saving the PNG differently. AFAIK it is a limitation of the image processing code that OTX switched to for 2.4, which may or may no be overcome in the transistion to LVGL that is in progress.
