### ISSUE TITLE
TouchUI Select model dialog in the models "folder"

### ISSUE THREAD

**Issue by jasc76** [EdgeTX/edgetx#1537]
Hi all

I want to propose a redesign in the select model touch UI. I often create unwanted models because the select and create iteams are so close. Is it possible to do a big select button and smaller create etc menus. 
Maybe like this:
![grafik](https://user-images.githubusercontent.com/42022027/151964211-55d94c28-0120-4132-b5b5-9319f9d78308.png)

**Comment by Eldenroot** [comment]
Or add a confirnation dialog

**Comment by pfeerick** [comment]
Have a look at #1374 - will be a bit different ;)

**Comment by jasc76** [comment]
looks good
