### ISSUE TITLE
Global Functions inverted Switches

### ISSUE THREAD

**Issue by skytra** [EdgeTX/edgetx#1538]
**General information**
 - EdgeTX version 2.6.0 338d4d2
 - Hardware Eachine (Radiomaster) TX16S

when you want to setup a global Fuction and Filter the list by Switches you only can select "positive" Switchevents
if you want to select an inverted switch you must deselect the Filter.

Switches Filtered 
![switch_filter](https://user-images.githubusercontent.com/40788187/152035883-ecb50f0d-c96e-456c-80ba-25882634e7d1.jpg)

no Filter selected
![inverted_switches](https://user-images.githubusercontent.com/40788187/152035879-f7e8353a-bab1-4707-9b12-b4551ec87bf7.jpg)

**Comment by eshifri** [comment]
Long press on the Enter or touch screen inverts the selection.
