### ISSUE TITLE
EdgeTX splash: 212x64 and 128x64 needed 

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#154]
Some testers have complained that we don't have any splash screens for the following screen types:
- 4-bit greyscale `212x64` (X9D).
- 1-bit black/white `128x64` (X7, T-Lite and pals).

Please submit your designs here!

**Comment by MRC3742** [comment]
Here is just a simple change from the OpenTX logos.

![Splash01_QX7](https://user-images.githubusercontent.com/26642502/120963092-f9e6af00-c72e-11eb-8b9c-2cca0ce2054b.png)

![splash01_X9D](https://user-images.githubusercontent.com/26642502/120963080-f7845500-c72e-11eb-8719-02f3081e7908.png)

Or possibly inverted for a similar but unique look!

![Splash02_QX7](https://user-images.githubusercontent.com/26642502/120963345-6661ae00-c72f-11eb-9bf6-36bd2561a5fa.png)

![splash02_X9D](https://user-images.githubusercontent.com/26642502/120963386-7da09b80-c72f-11eb-9aea-ae6b24bc2df2.png)

**Comment by pfeerick** [comment]
Since these are monochrome screens ... The inverted look is probably better.. but either/or look good! :)

**Comment by pfeerick** [comment]
In addition to the splash screen, there is one more place that logo is needed... on the X9(D) series at least, the default model image is the FrSKY logo with OPENTX underneath ;) Aspect ratio looks like it's just a smaller version of the splash screen.

**Comment by raphaelcoeffic** [comment]
@MRC3742 @pfeerick I just created a PR to try these out. I selected the inverted ones for now (white background).

**Comment by pfeerick** [comment]
Jesus... you have good timing... I've just reset my X9D+ back to OTX, and was about to let ETX loose on it again... now I'll wait for the PR to finish building! ;)

**Comment by MRC3742** [comment]
I could update the logo.png as well for the 212x64 screen later today.

Glad to hear that these splash screens are what you were looking for.
Without access to the font for "EDGE" I had to draw it from the 480x272 image.
I could try to clean it up a little better if it looks choppy on the 212 screen.
The 128 screen is going to be a little choppy with only two colors to work with.

Rich

**Comment by raphaelcoeffic** [comment]
> I could update the logo.png as well for the 212x64 screen later today.

Thx, I just did the resizing, let's see how that works.
