### ISSUE TITLE
Cannot calibrate FrSky receivers - BMPs with receiver position not displayed, cannot proceed to next step

### ISSUE THREAD

**Issue by kienzen87** [EdgeTX/edgetx#1547]
**Describe the bug**
When I try to run the offical "SxR_R9S_Calibrate.lua" script my RadioMaster TX16 does not display the BMP pictures of the required receiver position. When I click ENTER (multiple times) to get to the next step, I does not proceed (nothing happens), so its not just the pictures missing. Total showstopper - I cannot calibrate my FrSky receivers.

**To Reproduce**
Run SxR_R9S_Calibrate.lua on Radiomaster TX16 with FrSky S6R receiver.

**Expected behavior**
Calibration should be possible, BMP pictures should display

**Screenshots**
![272641627_1015730905955919_4891708307661411429_n](https://user-images.githubusercontent.com/98391383/152227541-35c44937-dbfc-473f-a0eb-8f6f93d652fd.jpg)

**General information**
 - FrSky Lua scripts: https://www.frsky-rc.com/wp-content/uploads/Downloads/TOOL/R9S-SxR%28lua%29/FrSky%20SxR_R9S.zip
 - EdgeTX version 2.6.0
 - Hardware: Radiomaster TX16S

**Comment by gagarinlg** [comment]
Can anybody confirm this?
