### ISSUE TITLE
Mixer output is incorrect when weight = -GV

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#1556]
EdgeTX 2.6 / Companion / TX16S

The setup has two channels, with the same aileron input. 

- One channel has a negative weight. 
- The other has a positive weight.
- Both weights are supplied by the same GV

_Expected_: negative weight generate negative mixer output
_Actual_: negative weight generate positive mixer output

To see this, load attached .ETX file  (remove .zip extension) into ETX Companion 2.6 and run the sim.

[f3f_A2FBug.etx.zip](https://github.com/EdgeTX/edgetx/files/8005696/f3f_A2FBug.etx.zip)

**Comment by pfeerick** [comment]
This may be related to/have been fixed in #1516, if so will be in 2.6.1 Will check the ETX later to confirm.

**Comment by pfeerick** [comment]
Ok, yes it is. If you check the GVAR that simulator is using for the mixer weight, you'll see it's using the wrong one for the -GV, hence why it is behaving that way. The radio firmware will similarly mangle it, so you will need the 2.6.1 firmware to fix this.

https://user-images.githubusercontent.com/5500713/152636969-a049ffaa-ed6b-44a1-ba2a-e1d073f32cc3.mp4

**Comment by RC-SOAR** [comment]
Great, thanks for fixing.

**Comment by pfeerick** [comment]
Credit goes to Jesper @jfrickmann as he did the PR fixing it last week ;) I'll close this as it is already merged and already scheduled for 2.6.1
