### ISSUE TITLE
Companion 2.6 doesn't read/write the parameters of the telemetry screens on X7/X9D+

### ISSUE THREAD

**Issue by nmare99** [EdgeTX/edgetx#1557]
Companion 2.6 doesn't read/write the parameters of the telemetry screens from/to the transmitter.
This was revealed on taranis X7 and X9D+
Screenshots of the companion and the edgetx screen are attached

![1](https://user-images.githubusercontent.com/82212750/152612491-f13bbd7c-6c8a-4a13-a47b-6fd380907de7.gif)
![2](https://user-images.githubusercontent.com/82212750/152612488-009cb395-88cb-4558-a2af-8ea1b2135017.gif)
![3](https://user-images.githubusercontent.com/82212750/152612487-75948233-5c15-4a7e-99a2-2420d5fe6a4b.gif)
![4](https://user-images.githubusercontent.com/82212750/152612492-e7d889df-0e39-4742-a53b-1b7e20100cf4.gif)
![5](https://user-images.githubusercontent.com/82212750/152612494-c5b630b8-0621-4d2c-9e28-94a60bdf82f4.gif)
![6](https://user-images.githubusercontent.com/82212750/152612493-fdfb5f42-f450-4a9b-a441-0185dd6648fa.gif)
![7](https://user-images.githubusercontent.com/82212750/152612501-f72e7ff4-cc62-4c57-83be-67b24c69c5cb.gif)

![8](https://user-images.githubusercontent.com/82212750/152612498-269d8080-9105-43ac-8ca1-9d21d390845c.gif)
![9](https://user-images.githubusercontent.com/82212750/152612495-009ab3aa-9160-4ea7-a23c-95eeef188219.gif)

**Comment by pfeerick** [comment]
Confirmed with T-Lite also - when reading Companion is mangling the telemetry screen data:

![image](https://user-images.githubusercontent.com/5500713/152636333-645cea6d-431c-4763-9e14-e2e0877d5448.png)

This zip from the radio when loaded in Companion is also demonstrating the failure. 
[radio.zip](https://github.com/EdgeTX/edgetx/files/8007724/radio.zip)

**Comment by elecpower** [comment]
Issue also affects screen type Bars
