### ISSUE TITLE
Trainer settings not transferred between Companion and radios

### ISSUE THREAD

**Issue by elekSENDER** [EdgeTX/edgetx#1559]
**Describe the bug**
no matter which parameter setting of trainer mode in the TX16S, it always read Master/Jack from the TX16S
no matter which parameter setting of trainer mode in companion, it always write Master/Jack to the TX16S

**To Reproduce**
change setting of trainer mode in companion and load it to TX16S
change setting of trainer mode in TX16s und read it to companion

**Expected behavior**
no unexpected change of settings after transfer

**Screenshots**
![grafik](https://user-images.githubusercontent.com/98912034/152654084-d27751f5-ff05-48ce-97b8-7e1f98937574.png)

**General information**
 - EdgeTX version (2.6.0 tx16s-338d4d2)
 - Hardware Radiomaster TX16S

**Comment by elecpower** [comment]
Confirmed yaml mapping on Companion side
