### ISSUE TITLE
Displaying of "Master/Multi" Trainer Mode  in X10s firmware and companion

### ISSUE THREAD

**Issue by elekSENDER** [EdgeTX/edgetx#1563]
I´ve understand there is a transfer issue for Trainer Settings between companion and radios.
But I noticed an issue in my Horus X10s which I think is not related to companion.

**Describe the bug**
I can select Trainer Mode in the X10s to Master/Multi.
Master/Multi makes in the X10s afaik no sense due to hardware limitation.

**To Reproduce**
Select Master/Multi in Trainer Mode on radio.

**Expected behavior**
No possibility to select Master/Multi on radio.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/98912034/152673568-bc2ccd0d-9676-4354-bd7e-39e6d02555ab.png)
![grafik](https://user-images.githubusercontent.com/98912034/152673626-f314f1a4-d2ff-4e8e-ac7f-b5378d8cae87.png)

**General information**
 - EdgeTX version (2.6.0 x10-338d4d2)
 - Hardware (Frsky Horus X10s)

**Comment by ZS-Man** [comment]
Hi,
Multi trainer is possible on X10S express with external MPM module and minor HW mod on radio RF module.
If this option will be removed, leave the option for ETX manual compilation, please.  (-DALLOW_TRAINER_MULTI=YES   ?)
Thanks.

**Comment by pfeerick** [comment]
It's more likely it will be left as it is if that is the case, or possibly an option added to the HW page so a custom build isn't needed.

**Comment by ZS-Man** [comment]
There is info about this HW modification:

https://www.rcgroups.com/forums/showpost.php?p=44546553&postcount=17686

https://github.com/opentx/opentx/issues/7181

**Comment by pfeerick** [comment]
Given that:
- when using an external MPM, Master/Multi is a valid option
- when using a radio that either as stock, or after a simple modification MPM, "Master/Multi" is valid

I propose the following:
1) that companion be a bit smarter - if a external MPM is configured, "Master/Multi" should be an option
2) that the firmware also be the same... i.e. it already knows what internal module is set, so the same can happen for external (if this is not the case already, that is)

**Comment by elekSENDER** [comment]
Yes, makes absolutly sense, good idea.
So you have just one firmware adjusted by parameter.
