### ISSUE TITLE
Special Function Haptic wrong transferred between Companion and radios

### ISSUE THREAD

**Issue by elekSENDER** [EdgeTX/edgetx#1564]
**Describe the bug**
Tranferred settings of Special Funktion Haptic are unequal between companion and radios TX16s, X10s

**To Reproduce**
change setting of Special Funktion Haptic in companion and load it to radios
change setting of Special Funktion Haptic in radios and read it to companion

**Expected behavior**
no unexpected change of settings after transfer

**Screenshots**

Companion:

![grafik](https://user-images.githubusercontent.com/98912034/152674957-826ea3da-af5a-4353-a3a8-d4e1561d3194.png)

Radio after writing:

![grafik](https://user-images.githubusercontent.com/98912034/152675187-33b47193-8bc4-4bf0-8a33-c49b3b9c8a1b.png)

Maybe there are parameter Value and Repeat swaped?

![grafik](https://user-images.githubusercontent.com/98912034/152675262-aad51f73-d243-4a08-9ad1-6cfa0cc9dca3.png)

**General information**
 - EdgeTX version (2.6.0 tx16s/x10-338d4d2)
 - Hardware (Frsky X10s, Radiomaster TX16S)

**Comment by elecpower** [comment]
Confirmed issue using main branch

TS16S simulator
![tx16s](https://user-images.githubusercontent.com/15316949/152773619-d881e9e2-d6a2-4bf5-a63b-5ff763289109.png)

Companion
![cpn](https://user-images.githubusercontent.com/15316949/152773626-4141afd7-9d90-4363-813b-dc266cab8a2c.png)
