### ISSUE TITLE
Wrong max bauds transferred between Companion and multiple radios

### ISSUE THREAD

**Issue by elekSENDER** [EdgeTX/edgetx#1566]
**Describe the bug**
In Radio Settings/Hardware Parameter Max bauds values are not the same between companion and X10s.
Companion 400000 -> X10s 115k 
Companion 115200 -> X10s 400k
and the same vice versa X10s -> companion

**To Reproduce**
read/write companion/Horus by changing Parameter Max Baud

**Expected behavior**
no changing after transferring

**Screenshots**

Companion:
![grafik](https://user-images.githubusercontent.com/98912034/152684060-8825bdcb-9430-4e8c-a5bc-3ee773523267.png)

after writing to X10s:
![grafik](https://user-images.githubusercontent.com/98912034/152684576-65b056d2-5526-438c-a9fc-7a86befed97e.png)

**General information**
 - EdgeTX version (2.6.0 x10-338d4d2)
 - Hardware (Frsky Horus X10s)

**Comment by elecpower** [comment]
Confirmed issue affects multiple radios and thus the change to the title
