### ISSUE TITLE
LUA script configurations not handled correctly in companion/simulator

### ISSUE THREAD

**Issue by bug400** [EdgeTX/edgetx#1576]
**Describe the bug**
I have an otx model file with several models. Each model has a telemetry script (swmuxm.lua) and a mixer script (swmuxt.lua).
Companion26 loads the otx file correctly. The telemetry script name is shown correctly in the Telemetry Screen 1 of "Custom Screens".
The configuration of the mixer script cannot be checked in companion, but after saving the project as a etx file I see, that both script names exist in the modelxx.yml files of the etx file.
If I start the Taranis Q X7 Access simulator neither the mixer nor the telemetry scripts are configured in any model. 
I can configure the scripts now manually in the simulator and everything works.

**To Reproduce**
- start companion
- load otx file
- start simulator of the Taranis Q x7 Access
- check LUA Script page: empty
- check custom telemetry page: no script name

**Expected behavior**
Telemetry and mixer scripts are configured in the simulator just as configured in companion.

My model otx file is attached. [otx.zip](https://github.com/EdgeTX/edgetx/files/8023223/otx.zip)

EDGETX 2.6 commit dc19cdee8415ec91b1a9834df15dc1aebf199cf3
Built on linux with cmake-options
-DPCB=X7 -DPCBREV=ACCESS -DHELI=NO -DPXX1=YES -DMULTIMODULE=NO -DCROSSFIRE=NO -DAFHDS3=NO -DPPM_UNIT=US -DLUA=YES -DLUA_MIXER=YES -DGVARS=YES -DFAI=CHOICE -DOVERRIDE_CHANNEL_FUNCTION=YES -DTRANSLATIONS=DE -DCMAKE_BUILD_TYPE=Release 

for the Taranix Q X7 Access. Not tested on radio so far.

**Comment by elecpower** [comment]
The telemetry configuration should be fixed by #1562 which is slated for maintenance release 2.6.1
