### ISSUE TITLE
Tx16s internal bluetooth build issues

### ISSUE THREAD

**Issue by bsh314** [EdgeTX/edgetx#1579]
Hello! 

I was trying to build edgetx firmware myself using Gitpod the 2.6 branch with internal bluetooth module enabled using this parameters:
`cmake -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=NO -DLUA=YES -DBLUETOOTH=YES -DCMAKE_BUILD_TYPE=Release ../`
after downloading the bin file and putting it on my tx16s sd card, i've flashed the bootloader and afterwards got into bootmenu to flash the firmware. After flashing the firmware my radio did not wanted to boot until I've flashed the latest prebuilt image from bootmenu again.

Do anyone sees any obvious error of mine here?

**Comment by pfeerick** [comment]
Nothing obvious no. I suppose you want more than just bluetooth on, as I see HELI=NO flag is there also? Otherwise, see if the bluetooth build here works => https://files.portabledev.xyz/d/bf957dbe31f04e4a95a4/

**Comment by bsh314** [comment]
I'll check if i can do that

**Comment by bsh314** [comment]
> Nothing obvious no. I suppose you want more than just bluetooth on, as I see HELI=NO flag is there also? Otherwise, see if the bluetooth build here works => https://files.portabledev.xyz/d/bf957dbe31f04e4a95a4/

Thank you! just wanted to have Heli removed.

**Comment by HazzaHFPV** [comment]
Is there an easy tutorial on how to compile EdgeTX? I'd like to compile it for my Jumper T16 with Bluetooth enabled but not quite sure how to go about it.

**Comment by rotorman** [comment]
@HazzaHFPV See https://github.com/EdgeTX/edgetx/wiki/Building-radio-firmware-in-a-webbrowser-with-Gitpod and go with:
```
cmake -DPCB=X10 -DPCBREV=T16 -DDEFAULT_MODE=2 -DBLUETOOTH=YES -DCMAKE_BUILD_TYPE=Release ../
```
