### ISSUE TITLE
SYS>Info Lock up

### ISSUE THREAD

**Issue by JohnNikl** [EdgeTX/edgetx#1582]
**Describe the bug**
If you go to SYS>VERSION>Modules / RX version - and press "PAGE>" or "PAGE<" and then press enter to EXIT, the radio locks up.

**To Reproduce**
SYS>VERSION>Modules / RX version - and press "PAGE>" or "PAGE<" and then press enter to EXIT

**Expected behavior**
Nothing, Thees buttons shouldn't do anything.

**Screenshots**

**General information**
 - EdgeTX version 2.6.0 (338d4d2c)
 - Hardware Radiomaster TX16S

**Comment by pfeerick** [comment]
Oh, nasty! Looks like the underlying page still has input focus, as PAGE
makes it switch tabs, which is what then causes the crash when you try to
close the info dialog.
