### ISSUE TITLE
Copyright notice for triangle draw func omitted

### ISSUE THREAD

**Issue by olliw42** [EdgeTX/edgetx#160]
This is an issue with the drawFilledTriangle() function in libopenui, but libopenui repo doesn't have issues, hence raised here.

The drawFilledTriangle() function originates from code from the AdaFruit gfx library, and a respective notice should have been put in.

That's largely my fault since while I do have such a comment in my original OpenTx-based branch, I was not copying it over to my EdgeTx/libopenui PR, from which it was taken over for another PR which was then merged.

As a guide, in my original branch I have a comment 

```
//THANKS to Adafruit and its GFX library !
</span>https://learn.adafruit.com/adafruit-gfx-graphics-library
```

I think a similar notice should be added.

**Comment by raphaelcoeffic** [comment]
I believe this is actually the copyright notice that should be there: https://github.com/adafruit/Adafruit-GFX-Library/blob/master/license.txt

**Comment by raphaelcoeffic** [comment]
And as it is BSD, we need to place it is as well somewhere in the “documentation”, which covers the binary re-distribution.

**Comment by raphaelcoeffic** [comment]
Resolved here: https://github.com/EdgeTX/libopenui/commit/f2330a3059e84c5ea7cb2ed5991a0a205f3045f9
