### ISSUE TITLE
(NV14) OUTPUTS / ADD all trims to Subtrims

### ISSUE THREAD

**Issue by Outwide** [EdgeTX/edgetx#1628]
In OUTPUTS / ADD all trims to Subtrims channel 1 seem ok but if you try to set other channels for the negative field (-100)
you can change it up 1 then it jumps to the name field and it can crash in either the negative field (-100) or name field area. this is where you get the fault crashes and enter emergency mode or freezes as you try to get it back . You may cannot turn off so remove batteries.
Also not easy or possible to type in the name field at top as other character appear, cannot clear the field to replace.

Expected behavior
To be able to type on the field selected and make changes easily.

General information
Edgetx 2.7
Edgetx-firmware-nightly-67d4a29e 
FLYSKY NV14

**Comment by Xavitorradas** [comment]
It also happens with TX16S firmware.

**Comment by Outwide** [comment]
Hi good to hear from you. I have also noticed high battery usage when it crashes and when charging the batteries in the transmitter and try the check how much recharging has been done it it show on the screen, emergency mode. I ask have noticed this aswell.On 28 Feb 2022 3:31 am, Xavitorradas ***@***.***> wrote:
It also happens with TX16S firmware.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

On 28 Feb 2022 3:31 am, Xavitorradas ***@***.***> wrote:
It also happens with TX16S firmware.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

On 28 Feb 2022 3:31 am, Xavitorradas ***@***.***> wrote:
It also happens with TX16S firmware.

**Comment by Xavitorradas** [comment]
There are some else issues but i did not take note of them. I'm looking for them. As soon as I get them I'll write.
Nice to hear you too.

**Comment by eshifri** [comment]
I think this must be fixed by #1657

**Comment by pfeerick** [comment]
Yeah, I think so... I got tricked by the mention of "ADD all trims to Subtrims". Thanks ;)

**Comment by pfeerick** [comment]
btw, long press of enter will give a 'clear' option
