### ISSUE TITLE
(NV14) VRA switch top left (S1)

### ISSUE THREAD

**Issue by Outwide** [EdgeTX/edgetx#1629]
VRA switch top left (S1) when assigned in MIXES, Adjustment is too large, example; Small movement has a big adjustment and is not possible to get fine adjust is the usual way. VRB switch top Right (S2) may also need looking at as well.

The original Opentx no problem.

General information
Edgetx 2.7
Edgetx-firmware-nightly-67d4a29e 
FLYSKY NV14

**Comment by eshifri** [comment]
Can you please check calibration of the VRA?

**Comment by Outwide** [comment]
Hi peter I have just done this and it fix to S1 and S2 pots.

Thanks Geoff

Brisbane.

**Comment by Outwide** [comment]
Hi eshifri I have just done this and it fix to S1 and S2 pots.

Thanks Geoff

**Comment by pfeerick** [comment]
Excellent! :) And lol... I'm up the coast from you... stay dry! :)
