### ISSUE TITLE
Throttle warning confirmation

### ISSUE THREAD

**Issue by GWguzzi** [EdgeTX/edgetx#1633]
**Describe the bug**
Throttle warning can not be confirmed by "any" key

**To Reproduce**
start the system with throttle warning active, get the warning text. The texts says that "any" key confirmes the warning, but only the "RTN" button of the FrSky Horus 12S works and confirmes. 

**Expected behavior**
Any button, as the warning text says, should work. (does work in openTX)

**General information**
 - EdgeTX version ( 2.6.0 r)
 - Hardware (e.g. Frsky 12S)

**Comment by gagarinlg** [comment]
is this still a problem with the current nightlies?
(make a backup of your SD card before testing!)

**Comment by gagarinlg** [comment]
No response since March
