### ISSUE TITLE
Add MIN as source

### ISSUE THREAD

**Issue by kristjanbjarni** [EdgeTX/edgetx#1635]
Currently in EdgeTX if you want a fixed value for a source input you can use MAX as source if need +100 but if want -100 there is currently no source for that available.

So I propose a MIN source like MAX expect with constant value of -100

There is currently no alternate except to use some other source that happens to have a value of -100, but that is sometimes not guaranted, especially with switches.

**Comment by eshifri** [comment]
Can't yo use weight -100 to achieve this?

**Comment by kristjanbjarni** [comment]
> Can't yo use weight -100 to achieve this?

There is no weight when selecting value source in "Global functions"

**Comment by eshifri** [comment]
So the problem is with GF only?
How about creating an Input with MAX as a source and weight -100?

**Comment by pfeerick** [comment]
I believe this is specific to GF/SF Adjust GV by Source? Although a complementary MIN to the MAX is probably useful generally.
