### ISSUE TITLE
Naming individual channels in Outputs Tab triggers Emergency Mode & potential lockups.

### ISSUE THREAD

**Issue by ZZ-Cat** [EdgeTX/edgetx#1639]
**Describe the bug**
Emergency Mode is triggered, when a name is set for any individual channels in the Outputs Tab. Not only that, the name itself comes out as though it's been written backwards.

I have also managed to completely lock my controller up by testing this. Not even holding the Power Button down to switch it off could save it, as that too became non-responsive.
I have included recovery instructions, in case this happens to you.

**To Reproduce**
- Go to Model Settings.
- Tap on the Outputs Tab.
- Pick a channel, any channel will do. I triggered it on Channel 1.
- Tap on "Name" & type in a name as you normally would, & press "Enter" on the keypad.
- Emergency Mode will trigger shortly after the controller has locked up for a few seconds.
-  If your controller has completely locked up, like I have described, follow the recovery steps below.

**Be aware:** As I have repeatedly stated, this could potentially cause your controller to stop responding to literally _everything_, including pressing the power button.
If that happens, your only escape here is to do the following:
- Unplug the battery from the underside of your controller.
- Wait three seconds.
- Reconnect the battery.
- Restart your controller. It will inevitably start up in Emergency Mode, as it should do.
- Restart your controller again, & by now you should be in EdgeTX like normal.

**Expected behavior**
Short answer: None of this. Clearly.
Nah, what's supposed to happen is the individual channel names should appear as, for example, Naming Channel 1 "AIL" should appear as "AIL", not "LIA" & Emergency Mode shouldn't even be encountered here; & even less so, this should never cause the controller to stop responding (AKA lockup).

**Screenshots**
![screen-2022-02-27-133245.png](https://user-images.githubusercontent.com/48301275/155864271-de3ea1bf-e7c5-4a8c-be1a-6b3205d25121.png)
![screen-2022-02-27-133301.png](https://user-images.githubusercontent.com/48301275/155864274-ff8bf8d8-da38-4834-9e69-a088654cc017.png)
![screen-2022-02-27-133745.png](https://user-images.githubusercontent.com/48301275/155864295-9027126c-a65f-4cbe-af14-976455eeba7f.png)

**General information**
 - EdgeTX version 2.7.0 nightly 357ae888.
 - Hardware: RadioMaster TX16S Max Edition.

**Update (6 March 2022):**
I am closing this issue, because the commits in the latest nightly c4fa8c1 fixed it.
I'm sorry for those that were unable to reproduce this issue on their end. I did have a hunch that this issue _may_ have been unique to my controller, for some reason.
However, another issue showed up that was _very_ similar to mine & those that resolved that issue has had a flow-on effect onto resolving my issue at the same time.
I want to give a big thanks to those that were able to get it sorted. =^/.^=

**Update (2 March 2022):**
I found out that the same thing happens, whenever I try to set the subtrims in the Outputs Tab.

**Comment by pfeerick** [comment]
Excellent! I was *hoping* that PR would fix it, but inability to reproduce meant I wasn't going to make that jump just yet! :) Now that I know what actually caused the bug, most likely bumping (or shaking)the stick for the channel being named would have the culprit whilst trying to enter the name.
