### ISSUE TITLE
build brocken with option -DGVARS=NO

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#1644]
**Describe the bug**
I would make a new built for my Zorro.
But since #1602 the build option`-DGVARS=NO` breaks the buildprocess.
@jfrickmann pls can you check this

![build-DGVARS=NO](https://user-images.githubusercontent.com/29702171/155895835-3d292f93-425a-49d3-8c86-b1798952650b.jpg)

**To Reproduce**
try a build with latest master and build option `-DGVARS=NO`

**Expected behavior**
clean build with working `-DGVARS=NO` option

**General information**
 - EdgeTX version 2.7.0 nightly latest master
 - RM Zorro

**Comment by jfrickmann** [comment]
Thanks @pfeerick !
