### ISSUE TITLE
Update to 2.6.0 on TX16s, Internal RF doesn't recognize internal module

### ISSUE THREAD

**Issue by oleg-sherman** [EdgeTX/edgetx#1646]
### Issue
After updating to EdgeTX 2.6.0, in the model setup menu -> **Internal** RF mode, has only `OFF` option.

### Expected 
Model setup menu -> internal RF mode, should have `OFF` and `MULTI` options.

### Workaround 
Downgrade to EdgeTX 2.5.0 solves the issue.

### Notes
- Updating internal module firmware did't help.
- **External** RF seems to work fine.
- Used Radiomaster TX16s Max

**Comment by pfeerick** [comment]
See if this fixes it:

https://github.com/EdgeTX/edgetx/discussions/1619#discussioncomment-2232886

**Comment by oleg-sherman** [comment]
@pfeerick 
> Can you see if this fixes it:
> 
> [#1619 (comment)](https://github.com/EdgeTX/edgetx/discussions/1619#discussioncomment-2232886)

This do not fix the issue, EdgeTX companion 2.6 also missing the `MULTI` option:
![Screen Shot 2022-02-28 at 11 57 56](https://user-images.githubusercontent.com/37136160/155963326-78556383-99d2-48f1-9e26-18d757fbd29a.png)

**Comment by pfeerick** [comment]
So when you went to the Radio Settings -> Hardware tab, and went down the "Internal module" as shown in that video, what options did you get? 

Until you can change that setting from OFF to MULTI, the model internal RF setting will not let you pick anything other than... well, OFF. 

For the equivalent setting in Companion (which appeared to work for the other person) you want:

![image](https://user-images.githubusercontent.com/5500713/155972976-e3cd62ac-1f61-4ae1-b64b-a0d164371461.png)

![image](https://user-images.githubusercontent.com/5500713/155973194-97e92afd-a506-4de3-bdde-1efd4abf489b.png)

**Comment by oleg-sherman** [comment]
@pfeerick 
> So when you went to the Radio Settings -> Hardware tab, and went down the "Internal module" 

This workaround works, Thanks!

**Comment by pfeerick** [comment]
Its not really a workaround - as that setting, introduced in 2.6, is what governs what module is used as the internal module - i.e. if you modify the transmitter, you would change that option. 

When you went to the Radio Settings -> Hardware tab, and went down the "Internal module" on the transmitter as shown in that video, what options did you get?

**Comment by gagarinlg** [comment]
I think this can be closed, right?
