### ISSUE TITLE
Issue with RTC delayed about half second every time zorro reboot.

### ISSUE THREAD

**Issue by arhifisyant** [EdgeTX/edgetx#1653]
This bugs is different than issue #1588

in Radiomaster zorro, if I syncronize the time with trusted source ( I use time.is), to the exact second value. Then reboot the transmitter (shutdown, then turn it back on properly using power button), the time will lag behind (delay) about half seconds. 

Here is what I found. After the time syncronize, I reboot the tx 4 times. The result is the zorro's time lag 2 second behind. I did multiple attemp to make sure this problem occur, the result is the same. It is lag about two seconds. So furthermore, in a daily usage, after many times we powercycle the transmitter, the time difference will be noticeable. 

note : I save the RTC properly ( After setting the date and time, I go to the main screen first, then go back to date setting again, just to make sure the second value match the time.is, then I reboot the transmitter)

Im on edgetx 0e41200
My hardware is radiomaster zorro+ betafpv nano elrs module.

**Comment by gagarinlg** [comment]
can you please retest with the current nightlies?
(make a backup of your SD card before testing)

**Comment by gagarinlg** [comment]
any news?
