### ISSUE TITLE
X9D 2016 - radio setup gets reset upon power off occasionally.

### ISSUE THREAD

**Issue by onecooler** [EdgeTX/edgetx#1654]
Once in a while radio setup gets reset occasionally. There are no steps identified to reproduce. About once a week I find my radio reset to defaults (like no switches assigned, radio in mod 1, sticks not calibrated) upon power on. No other issues.
FW version:
2.6.0
edgetx-x9d+
There were no similar issues with opentx, so probably it is not hardware related.
 
Please contact me if any other information is needed.

**Comment by dennisvr** [comment]
I have the same issue
FW version:
2.7.0
edgetx-x9d+

**Comment by dennisvr** [comment]
i've replaced the SD card, problem seems to be gone now.

**Comment by pfeerick** [comment]
Please update with how you go after a week or so. However I suspect that will have resolved the issue, as EdgeTX 2.6.0 onwards uses the SD card for radio and model settings, so if the SD card is marginal, you'll have had intermittent issues with it.

**Comment by dennisvr** [comment]
I haven't encountered the issue since replacing the SD card.
