### ISSUE TITLE
Make function switches selectable in Inputs and Mixes tabs in Companion, for Jumper T-Pro

### ISSUE THREAD

**Issue by Batambatam** [EdgeTX/edgetx#1655]
In Companion, for Jumper T-Pro radio : 
Function Switches (SW1 to SW6, in Setup tab, while editing model) are currently not selectable in Inputs and Mixes tabs.

However, they are selectable in the 2.7.0 firmware.

Jumper T-Pro would be more manageable in Companion with this feature.

Seems that nobody is working on this yet since this comment https://github.com/EdgeTX/edgetx/pull/1230#issuecomment-989819020

**Comment by elecpower** [comment]
Requires a port of https://github.com/opentx/opentx/pull/8847

**Comment by Batambatam** [comment]
Ported it :) https://github.com/EdgeTX/edgetx/pull/1694
