### ISSUE TITLE
Model-Setup: Pots&Slider-Check: Auto has no function

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1660]
The pots&slider check button in model setup has three values: OFF, ON, AUTO.

Setting to ON saves actual position of all selected pots and sliders.

Setting to AUTO is not handled in source code (not even in B&W radios) in any way.

Before removing this option: does anybody know what the intend of AUTO was (hostorically)?.

**Comment by rotorman** [comment]
Auto should remember the last position when the radio was turned off, or a model changed.

**Comment by wimalopaan** [comment]
Looks like that doesn't work, at least in simulator.
Grep-ing thru the code I can't find meaningful usages of POTS_WARN_AUTO.

**Comment by wimalopaan** [comment]
Mmh, in simulator that does not work, I think

**Comment by wimalopaan** [comment]
Ok, I misinterpreted the function: AUTO-save does its work for all pots/sliders, that are not checked.
Is that intentional???

**Comment by wimalopaan** [comment]
I think it is intentional, because it allows to mix explicit setting and auto setting.
