### ISSUE TITLE
Emergency Mode when trying to change name of model categories

### ISSUE THREAD

**Issue by nostromo123** [EdgeTX/edgetx#1666]
FrSky X10S Express with edgeTX 2.6

Trying to change a name in that window here constantly results in an emergency mode.

![20220306_140643](https://user-images.githubusercontent.com/17964433/156924961-69b06328-e335-46af-ae0e-439fbcf9de11.jpg)
 
Can present a video if requested.

Sorry, if that issue has been reported earlier ;-)

br KH

**Comment by pfeerick** [comment]
I have this suspicion it was, but it might has been part of another issue. Either way, single item issues are easier to digest ;)

**Comment by pfeerick** [comment]
If you get a chance a video would be great, as I haven't been able to repo this yet.

**Comment by pfeerick** [comment]
Actually, I reverted to 2.6 as I'm on a nightly atm, and it crashed while I was fiddling with it. So can you try with a nightly and see if this is indeed fixed, as it looks like it was fixed already. Also, how did you get the `_` in, as it doesn't seem to be a valid character atm.

**Comment by nostromo123** [comment]
Hi, I do all my programming with companion, not on the radio. So I did it that way with the '_'.

No video necessary, as I understand!? I'll try nightly, but at the moment I am quite busy. Maybe tomorrow ....

I'll report back :-)

cu KH

**Comment by nostromo123** [comment]
Nightly on the radio, and no issue anymore!

![20220308_194243](https://user-images.githubusercontent.com/17964433/157304734-3419c3ab-1818-4a83-9ec1-e1ad5f67b878.jpg)

I'll close this issue. Thank you again for giving a hand.

Have a nice day.

br KH

**Comment by pfeerick** [comment]
Ah, that makes sense (Companion)... I was thinking it might have been a manual edit... so will have to look at why it's not in the list presented on the radio at some point...
