### ISSUE TITLE
X9D+, Mix name garbage - possibly related to new model wizard

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#167]
FrSKY X9D+, x9dp-70379b5.bin (most recent build of PR#161), still running OTX SD pack. 

Created a new model, using the new model wizard (tested plane and multicopter), accepting all defaults. Now go into model setup -> Mixes  and the mix names on the end are garbage characters. However, skipping the wizard will create just the first four channels in default order specified, and they seem to be correctly blanked. 

Going to test with the new SD card pack in case in the hope the new model wizard is a file from that and is already fixed. Edit: Nope, still present in current SD pack.

**Comment by raphaelcoeffic** [comment]
Very good hint! It seems the LUA names are still translated into ZCHARs then, I'll have a look.

**Comment by pfeerick** [comment]
Closed by #171
