### ISSUE TITLE
Turning on internal MPM screws the synchronization with the external ELRS module

### ISSUE THREAD

**Issue by drtrigon** [EdgeTX/edgetx#1671]
**Describe the bug**
When using an external ELRS module it is not possible to use the internal MPM as wireless trainer link. Consider e.g. following setting:

`use the external ELRS as link to a model and the internal MPM as wireless trainer link to a spectrum transmitter`

As discussed on discord with @raphaelcoeffic (pafleraf) and @3djc, currently "you cannot synchronize on 2 modules at the same time. At least not if it triggers the mixer as now. The current implementation synchronizes on the internal module if ON, and on the external otherwise." "The fact that the internal MPM is turned on screws the synchronization with the external ELRS module!" "Ideally, we should disable the synchronization on the MPM when it works as a RX." "That should be enough to overcome the issue."

**To Reproduce**
1. use ELRS as external module
2. https://www.expresslrs.org/2.0/quick-start/transmitters/tx-prep/ states at multiple places "NOTE: Make sure the internal module is turned off."
3. so the internal MPM cannot be used at all

**Expected behavior**
It should be possible to use the internal MPM even when there is an ELRS external module present and used (active).

**Screenshots**
(none)

**General information**
 - OpenTX version: 2.3.14
 - Hardware: Radiomaster TX16S
 - OpenTX Companion: -
 - (ELRS: 2.2.0)

**Comment by drtrigon** [comment]
https://github.com/opentx/opentx/issues/8874

**Comment by drtrigon** [comment]
Looking at:
- https://github.com/EdgeTX/edgetx/blob/main/radio/src/trainer.h
- https://github.com/EdgeTX/edgetx/blob/main/radio/src/trainer.cpp

I cannot find any code for wireless trainer using the internal module - I guess that needs to be done first. Is that correct or do I miss something?

**Comment by raphaelcoeffic** [comment]
But the real issue here at hand is actually *by design*. The synchro code considers that the internal has **always** a higher priority, which is here obviously a bit unfortunate.

**Comment by drtrigon** [comment]
@raphaelcoeffic: What about adding an option to the model menu (close to the internal and external module settings) that allows to define the priority by the user? Or may be the trainer module could have separate entries for internal and external module?

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic: What about adding an option to the model menu (close to the internal and external module settings) that allows to define the priority by the user? Or may be the trainer mode selection could have separate entries for internal and external module?

Yeah, something along these lines will be needed. I would just prefer something "automatic". Here we need to set a different prio based on whether the MPM is working in "normal" or RX mode.

**Comment by drtrigon** [comment]
I had a look into the code but am not into it enough to figure out an easy way to test `whether the MPM is working in "normal" or RX mode`.

**Comment by pascallanger** [comment]
@raphaelcoeffic You know that the multi module is in RX mode simply if you have incoming telemetry packets which are trainer formatted. Isn't it enough?

**Comment by raphaelcoeffic** [comment]
> @raphaelcoeffic You know that the multi module is in RX mode simply if you have incoming telemetry packets which are trainer formatted. Isn't it enough?

It does not send these when the connection is not available (trainer signal missing).

ideally a sync with 0 period should be sent, that would solve many issues.

**Comment by drtrigon** [comment]
(Thanks for solving!)

**Comment by mha1** [comment]
@pfeerick @eshifri I hope I may use this to place a follow-up question. I'm experimenting with redundant RF paths, like having the internal MPM on some MPM protocol (e.g. FrSky) and the external module bay equipped with a ELRS module. After activating both, both modules talk to their respective receivers and even telemetry from both receivers is received and discoverable. 

Setting ELRS to 500Hz I'd expect a mixer task frequency of 500Hz as it is with just the ELRS module activated (MPM off). Having both modules activated the mixer task frequency drops to 143Hz (= 7000us) which is the default for MPM. The reason is as you explained the logic in getMixerSchedulerPeriod() which prioritizes the internal module. 

Think it'd be a reasonable way to have the logic changed to "if both modules are present return max(internalModulePeriod, externalModulePeriod". It seems to work but are there any concerns running the MPM with a mixer task other than 143Hz, e.g. 500Hz?

**Comment by eshifri** [comment]
I'm not sure, but I strongly suspect MPM does not support communication speed that high.

**Comment by mha1** [comment]
> I'm not sure, but I strongly suspect MPM does not support communication speed that high.

You are right. I tried and the MPM doesn't work at 500Hz but both work at 143Hz even if the ELRS module set at 500Hz packet rate requests communication at 500Hz update rate. Surprisingly everything works fine for both modules, even telemetry is received from both modules and is discoverable.

I believe to allow an internal and external module to run concurrently at their proper rates doesnt require a lot of changes.

To minimize latency it is wise to run the mixer calculations at the highest rate any of the two modules require. So in case of an external ELRS module set at 500Hz packet rate and internal module turned off the mixer task needs to be run at 500Hz too. In the mixer task the pulse generation for the external and internal module is called every mixer task activation (tasks.cpp) embedded between `doMixerCalculations();` and `doMixerPeriodicUpdates();`

```
      doMixerCalculations();
      sendSynchronousPulses((1 << INTERNAL_MODULE) | (1 << EXTERNAL_MODULE));
      doMixerPeriodicUpdates();
```

And here's the problem. Pulses for the internal and external module are generated at the same rate. Now assume you have the internal module activated in addition to the let's say the external ELRS module set at 500Hz packet rate. This leads to pulse generation for the internal module also at 500Hz, which is not what the internal module was asking for.

A solution to allow both modules to work at their requested period (e.g. ELRS at 500Hz, MPM at 143Hz) would be in breaking the direct link from mixer task period (which should run at the highest requested rate) and the pulse generation for the modules. Simple pseudo code:

```
      set mixer task to run at max(period internal module, period external module)
      
      doMixerCalculations();

      if timeElapsedinternalModulePeriod
          sendSynchronousPulses(1 << INTERNAL_MODULE);

      if timeElapsedextarnalModulePeriod
          sendSynchronousPulses(1 << EXTERNAL_MODULE);

      doMixerPeriodicUpdates();
```

This would allow communication with both modules at different rates. 

PS: What is the highest mixer task rate you'd expect? 500Hz? 1kHz?
