### ISSUE TITLE
TBS Tracer Doesn't Want to Stay Bound in Trainer Mode

### ISSUE THREAD

**Issue by Sossy-Dubois** [EdgeTX/edgetx#1677]
TBS Tracer establishes and then quickly loses bind with RX while in trainer mode.

To reproduce: Use a Jumper T18 V2 radio as a master connected to a slave Taranis QX7 using "FrskyRX" on the jumpers internal 4in1 module and the D8 protocol on the QX7. Use a TBS Tracer module in the Jumper to connect to the mini-quad. The Tracer module binds and then immediately loses it's bind. Both radios are using a baud rate of 115k and when I switch the baud rate on the master radio, the tracer will re-establish it's bind and then immediately lose it again.

I'm able to get the Tracer to stay bound by switching the baud rate from 115k to any other baud rate and then quickly switching it back to 115k before it loses it's bind again. 

Both radios are running EdgeTX 2.6.0.

**Comment by raphaelcoeffic** [comment]
Maybe this should be asked to TBS: loosing the sync should not make the module loose connection to the receiver.

that being said: it is clear that enabling internal MPM will make Tracer loose the sync (CRSFshot).
