### ISSUE TITLE
Zorro in USB Serial mode "device can't start"

### ISSUE THREAD

**Issue by maxbl4** [EdgeTX/edgetx#1679]
Hi, just got new Radiomaster Zorro, flahed EdgeTx 2.6 release and trying to flash internal elrs tx.
All other modes (joystick and usb storage) work fine, but when I connect in USB Debug mode, first it said, there is no driver for Zorro device. Than I used Zadig to install WinUSB driver, now Windows says "Device can't start".
Do I need some special driver for Etx passthough?

**Comment by pfeerick** [comment]
Just for reference, as I think I was involved in another discussion on this, Windows is sometimes useless at picking at the correct driver that a device needs, even when it is a driver it should know about. As a result, it may be necessary to download and install the driver from https://www.st.com/en/development-tools/stsw-stm32102.html to knock some sense into said OS.
