### ISSUE TITLE
On B&W radios, deleting models in companion doesn't actually work

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1696]
Due to how models are handled differently on B&W radios, the actual model.yml files need to be deleted in order for them to be removed from the list on the radio... which companion currently isn't doing. 

So either we need to:

1) use a models.yml on B&W radios, so companion can alter just the index file like with colorlcd
2) actually delete the model files on B&W radios

I think option 2 is reasonable, as well as for companion to delete model files no longer in use on colorlcd... given the warnings that writing to the transmitter is "destructive / overwrites settings"...

**Comment by elecpower** [comment]
Unlikely option #1 as @raphaelcoeffic would have standardised with the move to yaml so option #2 it is.
