### ISSUE TITLE
Companion "Telemetry" and "Act" items in logical switches are not correctly read back

### ISSUE THREAD

**Issue by dududu76** [EdgeTX/edgetx#1697]
The item "Telemetry" in logical switches dropdown list, is not correctly saved by Companion.

**Steps to reproduce the behavior**
In Companion, edit a model, and go to "Logical Switches" tab.
Define a new logical switch with
- Function set to "AND" or "OR".
- V1 parameter set to "Telemetry" or "!Telemetry".
- Other fields can be left empty.

Save the .etx file ( File -> Save ).

Close the file (File -> Close).
Re-open it : the "Telemetry" V1 parameter Has disappered.

Additionnally, when pushing to the radio, "!Telemetry" parameters are transformed into "Telemetry".

**Expected behavior**
The "Telemetry" (or !Telemetry") parameter should be correctly saved.
Also, all "!Telemetry" parameters should not be turned into "Telemetry" when pushed to the radio.

**General information**
 - EdgeTX release version (2.6.0)
 - Hardware : Frsky X9D+
 - OS : Windows64

**Comment by elecpower** [comment]
Confirmed and issue also affects 'Act' and '!Act'

**Comment by elecpower** [comment]
model.yml
>logicalSw:
  0:
    func: FUNC_AND
    def: "!RADIO_ACTIVITY,RADIO_ACTIVITY"
    delay: 0
    duration: 0
    andsw: "!RADIO_ACTIVITY"
  1:
    func: FUNC_OR
    def: TELEMETRY_STREAMING,!TELEMETRY_STREAMING
    delay: 0
    duration: 0
    andsw: TELEMETRY_STREAMING

![screenshot_x9d+_22-03-17_08-04-45](https://user-images.githubusercontent.com/15316949/158691337-f254116a-9c43-4cfd-9d8a-0d3affe3b11d.png)
