### ISSUE TITLE
Windows 10, Companion 2.5 simulator no sound.

### ISSUE THREAD

**Issue by dwheel** [EdgeTX/edgetx#1699]
While setting up a model and assigning sounds in special functions, all of the sounds play normally when I click on the play icon. However, when running the companion simulator none of the sounds play. I hear a small portion of the first sound after starting the simulator, but from that poing on there is no sound at all. 

All sounds play normally on the transmitter.

**Comment by MervDale** [comment]
I think you will find that companion 2.6 is the current version with 2.7 not to far away and as I have found the sounds are fine in the simulator.
