### ISSUE TITLE
Touch interface - back button

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#17]
The back button for a lot of menus is currently overlaid over the logo in the right corner... sort of. 

![IMG_20210515_153610](https://user-images.githubusercontent.com/5500713/118349437-fdee3980-b593-11eb-96f8-f8979371599c.jpg)

I actually think it should be kept where it is, but make it bigger and blank that logo off completely. Then it becomes "press the logo" (and/or top row) of the screen for options, and then when in the menus press that same spot to go back. 

tx16s-edgetx-60726891, #85ebb168

**Comment by raphaelcoeffic** [comment]
I was think to actually make the "back button" disappear, and have the "opentx logo" be the "home / back" button. The hitbox is a bit small now, so I'll extend it to cover the complete logo, so it is easier to "click" on it.

**Comment by pfeerick** [comment]
I like the idea, but putting myself in the shoes of someone who isn't familiar with that behavior yet (i.e. new user), I would have to ask what cue/clue is there that pressing the logo would take me back to the previous screen/menu? i.e. how can it be made intuitive to use?

**Comment by raphaelcoeffic** [comment]
Very good question! I have no answer right now.

**Comment by raphaelcoeffic** [comment]
Looks like we are heading towards a "Home" button. It should look like a "Home" button obviously. Artwork is welcome :-)

**Comment by lshems** [comment]
For any touch interface, menu structures are the main underlying framework, together with a popup keyboard for numbers or letters to enter data, if not ranged.

So I would think any attribute needs to be findable by clicking only, and then either show a popup list, number keyboard or letter keyboard.

Just thinking.

**Comment by pfeerick** [comment]
This was basically resolved between https://github.com/EdgeTX/edgetx/pull/533 and https://github.com/EdgeTX/edgetx/pull/584

There isn't a back 'icon' as such, but the screen that could not be backed out of via touch can now be backed out of by pressing the EdgeTX logo, thus consistent with the rest of the UX.
