### ISSUE TITLE
Adding whitespace between fields & increasing fields' size

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#170]
This another thing we may consider to add to 2.4

Currently going to any MODEL/RADIO tab we have (depending on TAB) 9 parameters lines, so it's quite tight. 
In terms of touchUI it creates errors due to too small vertical space.

I'd go with 8 lines visible (2-3 px) . Maybe 7 lines but then we may loose some 'data overview' advantage.

**Comment by raphaelcoeffic** [comment]
> I'd go with 8 lines visible (2-3 px) . Maybe 7 lines but then we may loose some 'data overview' advantage.

We can try different settings and find the sweet spot.

**Comment by raphaelcoeffic** [comment]
@JimB40 I promised someone to give it a shot for 2.4.0, but if I don't succeed fast, I'd rather move it to 2.4.1.

**Comment by JimB40** [comment]
As stated in schedule we should try to address it in 2.6
This UI element height is kind general setting?
Or every UI field/element on every TAB needs to accessed separately?

**Comment by JimB40** [comment]
Connects & solves #376

**Comment by raphaelcoeffic** [comment]
> As stated in schedule we should try to address it in 2.6 This UI element height is kind general setting? Or every UI field/element on every TAB needs to accessed separately?

Somehow general. However, it is linked to the line height and centering inside the fields.... So a bit of tweak is necessary to make it work generally.

**Comment by gagarinlg** [comment]
Is this still valid with LVGL and the upcoming 3.0 UI changes?

**Comment by gagarinlg** [comment]
fixed with LVGL and also stale
