### ISSUE TITLE
EdgeTX 2.6 Cpn + Zorro: message 'File board ... does not match current profile board

### ISSUE THREAD

**Issue by VaBarefootBoy** [EdgeTX/edgetx#1700]
Issue previously reported by
[RC-SOAR](https://github.com/RC-SOAR) commented [on Feb 1](https://github.com/EdgeTX/edgetx/issues/1541#issue-1121278357)
reported 
Fixed by [#1572](https://github.com/EdgeTX/edgetx/pull/1572)

When transferring models from Zorro transmitter into ETX Companion 2.6 I get an error message, also regarding “File board (Radiomaster TX16S) does not match…”
To reproduce:
	1.	Connect to Companion via USB
	2.	Menu 'Read Models and Settings from Radio'
	3.	Then I get this message
	
<img width="409" alt="Screen Shot 2022-03-16 at 10 49 39 PM" src="https://user-images.githubusercontent.com/101781416/158732769-d3934ac9-d1f4-4fe3-b918-2410de3a5819.png">

At first I selected NO and got 

<img width="435" alt="Screen Shot 2022-03-16 at 10 49 58 PM" src="https://user-images.githubusercontent.com/101781416/158732802-8d21e05f-f8cd-4743-901d-703a311a7860.png">

I went in an confirmed I had setup a NEW radio for the ZOR

- - - Radio Type Radiomaster ZORRO

I tried again selected “YES” and it seemed to work

BUT  after on session while changing mixes in a quad…..

When I disconnected and went into BetaFlight I found my 
Rudder channel had become pegged to the RIGHT.

I looked at the ZORRO Ch map and indeed my Rudder input was completely to the right ,
pegged at +100
and any stick movement was disregarded or showed no monitored movement.

I tried another Model but the same Rudder Input was there as well.
I tried Calibration but can not Center Rudder.
I tried re-flashing with no positive results.
I deleted Ch1 RUD and the re-program ch as RUD.
The TRIM will move the down as FAR AS +74 - - BUT
STILL NO MOVEMENT WHEN THE STICK IS MOVED.

Presently I am left with an inoperable ZORRO Rudder Ch.

All firmware and SD were backed up as they came shipped if any of that might come in handy.
 
Thanks for you help in advance.

**Comment by eshifri** [comment]
Fix #1572 went into 2.6.1 nad, consequently, into 2.7.
2.6 has the bug.

**Comment by VaBarefootBoy** [comment]
Maybe not you territory but do you have any suggestions on how to get the RUD ch, Ch 1 on this ZORRO FIXED / unscrewed ??

On the FliPhone
Godspeed & God bless
Stephen B. Caldwell

**Comment by eshifri** [comment]
To be honest, I'm not sure.
You can try to use nightly build.
Or fix the model on the TX without companion.
O have never had Zorro in my hands, so ....

**Comment by raphaelcoeffic** [comment]
@VaBarefootBoy Just in case: have you tried calibrating the sticks? Does it move during calibration?

**Comment by VaBarefootBoy** [comment]
Thanks. 
I am going to give a nightly build a try but I think something has been corrupted in the ZORRO TX. 

I will as around. 

On the FliPhone
Godspeed & God bless
Stephen B. Caldwell

**Comment by VaBarefootBoy** [comment]
> @VaBarefootBoy Just in case: have you tried calibrating the sticks? Does it move during calibration?

Yes I went to Calibration. Ch1, Rud, the monitor shows he stick left stick/RUD full right +100. the sticks can not be centered to begin calibration - well at least they can not be shown centered. 

I will try it with the monitor still far right and see what that does.

**Comment by eshifri** [comment]
Are we talking about channel monitor or HW calibration?
If the stick cannot be centered in the HW Calibration window, most likely, it is a HW problem. (Maybe a cable connection.)

**Comment by pfeerick** [comment]
Try this build of 2.7 companion for Mac - it's the latest build at present -  https://github.com/EdgeTX/edgetx/actions/runs/1997574086

**Comment by VaBarefootBoy** [comment]
I might give it a go. Thank you. 

I re-flashed the Zorro w the latest 2.6, & LUA and replaced my 1.3.9 Companion and after all that they began to work to get her. 

The official 2.7 comes out at the end of the month, I think, so I might just hold off for it to be released. 

Y’all have been very helpful. 
Thank you very much. 

On the FliPhone
Godspeed & God bless
Stephen B. Caldwell

**Comment by pfeerick** [comment]
Yes, it was scheduled for 20/MAR but will most likely be thinking of first release candidate next week... glad it is all starting to work properly now though :)

**Comment by brunweil** [comment]
Slightly different message:
"settings files board (RADIOMASTER TX16S) does not match current profile board (XXX)"
XXX = What I put in the radio setup model, connecting a RADIOMASTER TX12 MK2 ELRS.
The same occur on Mac OS 10.15 and Windows 10 with EdgeTX companion 2.7.1

**Comment by pfeerick** [comment]
This is because the TX12 MK2 is not supported until 2.8 - you need to be running a 2.8 Companion (and firmware). Due to legacy reasons when there is a mismatch Compaion always complains about it being TX16S, rather than the value in the actual settings file.
