### ISSUE TITLE
Frsky XJT Lite module support

### ISSUE THREAD

**Issue by lion13ch** [EdgeTX/edgetx#1703]
Need Frsky XJT Lite module support for Jumper T-Pro radio.

**Comment by pfeerick** [comment]
I actually had this problem last night, and was told the TPro doesn't have the required hardware capability... (as the XJT Lite uses the TX/RX nano module pins, not just the sport like most others). I'll find out more for you.

**Comment by brainbubblersbest** [comment]
Yes thats True. No two wire Serial is physical available.
Only Sport and sbus gnd and vbat.

**Comment by pfeerick** [comment]
Indeed. It seems that a hardware modification similar to that needed on other radios for ACCESS modules (the so called [externalaccessmod](https://github.com/opentx/opentx/wiki/Externalaccessmod)) will be needed on the TPro in order to use the XJT Lite module with it. The Zorro on the other hand as the requisite hardware support right out of the box.

**Comment by brainbubblersbest** [comment]
It's a bit strange that a Radio with x-lite bay, (which was introduced by frsky) doesnt support that Frskyish connection. 🙈 It wouldnt bring much disadvantages to the other Radio Models either, beside loosing one spare uart.

**Comment by gagarinlg** [comment]
> A few weeks ago, I came to the idea that sort of a reference circuit Design published under Creative Commons/opensource licence, that every Radio Company can use for Free would bring some Real benefits.
People from here like Risto and Olli would be perfect for such a Thing.

This idea is in siome peoples head for a while now

**Comment by brainbubblersbest** [comment]
If I remember right, @rotorman is almost into work like that.
But here for a custom tx16 Mainboard.
Maybe it would make more sense to Design a Radio around some predefined pcb Design. Instead of Creating a Board into a Predefined Radio Design. 🤔🤷‍♂️

**Comment by rotorman** [comment]
My vision for a future radio is in the vains of:

![grafik](https://user-images.githubusercontent.com/21011587/159068175-7d683377-3c9f-4f48-94a6-b367050f5316.png)

where the User Interface (UI) part could also easily be a Cortex-A, Raspberry Pi Compute Module, Smartphone instead of STM32H7 and the RealTime (RT) part could be a PSoC or FPGA instead of STM32F3/F4.

This is a long term goal though, as the codebase would need to be split up between the UI and RT parts to achieve this.

**Comment by brainbubblersbest** [comment]
Wow. 😅
Really Interesting 😯
My Thougts  were more on the Moduleish point of view, comparable with https://en.wikipedia.org/wiki/Modular_smartphone?wprov=sfla1

**Comment by gagarinlg** [comment]
maybe we can start have some layer separation...
But this is kinf of off-topic. Maybe this discussion should go to the discord server, or a new enhancement issue

**Comment by joymonkey** [comment]
> Indeed. It seems that a hardware modification similar to that needed on other radios for ACCESS modules (the so called [externalaccessmod](https://github.com/opentx/opentx/wiki/Externalaccessmod)) will be needed on the TPro in order to use the XJT Lite module with it. The Zorro on the other hand has the requisite hardware support right out of the box (and does work).

I've got a Radiomaster Zorro with internal ELRS, running EdgeTX 2.6.0. Would like to use an XJT Lite module but not seeing it in the External RF Mode menu. Is it supported in the current nightlys?

**Comment by pfeerick** [comment]
Yes. Support for modules like the XJT lite which use serial instead of sport interface was only enabled about a month ago on the Zorro.

**Comment by raphaelcoeffic** [comment]
> Yes. Support for modules like the XJT lite which use serial instead of sport interface was only enabled about a month ago on the Zorro.

And thus will be in 2.7

**Comment by qeorqer** [comment]
Does this issues still exist for jumper t-pro elrs version?

**Comment by pfeerick** [comment]
Yes, as it is a design limitation of the radio. i.e. a hardware mod (which hasn't been researched) would be needed before EdgeTX would be able to support the serial ACCESS protocol used by the XJT Lite

**Comment by qeorqer** [comment]
Got it, thanks. Can you recommend what to use instead? My goal is to connect remote to drone with frSky built in. Probably a noob question, but I am just starting out

**Comment by raphaelcoeffic** [comment]
A Multi-Protocol module (MPM) seems most appropriate.

**Comment by pfeerick** [comment]
You can get MPM modules in the Nano module bay format (i.e. IRangeX IRX4 LITE) which will do Frsky D16, etc without a issue, and will also talk V1 and V2, FCC/LBT so you won't even need to worry about what firmware version is on your RXs ;)

**Comment by qeorqer** [comment]
Thank you, guys. Ordered an MPM

**Comment by qeorqer** [comment]
Thank you, guys. Ordered MPM

**Comment by shashfrankenstien** [comment]
IRX4 LITE works very well. This thread seems to be the only source that points in the right direction

**Comment by pfeerick** [comment]
Welcome :) 

Going to close this issue now as it is a hardware limitation, and there hasn't been any further progress on RE of the TPro enough to determine the feasibility of a workaround.

**Comment by christhomas** [comment]
I am also having a problem with the betafpv literadio 3 pro and the xjt lite nano tx module. Is the problem the same? Because it has 8 pins and 8 connectors on the module. So physically it seems like it does plug together. So then what is the problem? The sport or serial interface you mentioned? Is there anything I can do? Or should I just send the module back and get a different one instead? It's totally incompatible?

**Comment by raphaelcoeffic** [comment]
@christhomas unfortunately, the lr3pro does not have the required serial port at the required pins on the external module interface. So, like many radios with a lite bay, it "looks" compatible, but isn't. The XJT lite uses exclusively bi-directional serial communication over PPM/HEARTBEAT pins, also labeled TX / RX in some pinout diagrams for the lite bay.

**Comment by christhomas** [comment]
Urgh, this pin compatibility thing is dammed annoying, not the first time I’ve bought something and then found that just because the connector is the same, doesn’t mean it will work :(

**Comment by christhomas** [comment]
Would you be so kind as to tell me whether with this radio the “IRangeX IRX4 LITE” will work? I thought I knew what I was doing but clearly I don’t. It would help me a lot. Cheers

**Comment by pfeerick** [comment]
Also, if you are interested, the Radiomaster now also do a 4IN1 module in Nano bay form factor, and it also comes with an adapter plate to use it in the JR Micro module bay radios also ;)
