### ISSUE TITLE
Failsafe Custom Set Bug

### ISSUE THREAD

**Issue by Xavitorradas** [EdgeTX/edgetx#1707]
**Describe the bug**
### MODEL SETTINGS 
When Failsafe Custom setting and editing a channel, before exiting from editing, if you push over the channel value whised it jumps two channels back. I did it in some channels from CH12, but when arriving to channel 5 it stop jumping,
  Also Missing Failsafe Option in PC EdgeTX. You Can see in last Photo added. 

**To Reproduce**
1- Enter in Failsafe-> Cusom-> Set
2- Select one channel, in my case ch12, ch10, Ch8 and Ch6. 
3- Appears rectangle at bottom and you can edit Channel value
4- Before exiting from editing, if you push over de range number it jumps back 2 channels.

**Expected behavior**
If you push over the range number you want to modify it must change as blue line ( input value ) to red line and value edited and mantain channel, but in spite of this, it doen't change as in Opent TX happens. In openTX If you adjust blue line in failsafe custom set  and push wheel ( enter) the value is automaticaly insertet in the failsafe value.

**Screenshots**

**General information**
 - EdgeTX version (nightly tx16s-6c41350 and also tx16s-7ba936b)
 - Hardware (TX16S and Frsky S8R reciever)

### **ENTER FAILSAFE IN MODEL SETTINGS** 
![FS1](https://user-images.githubusercontent.com/82335501/159076233-57a79e1e-7968-4f6a-a3d4-f81c467e5541.png)
### **EDIT VALUE**
![FS2](https://user-images.githubusercontent.com/82335501/159076237-183f40b0-41e4-45db-87af-2cec02579fbb.png)
### **PUSHING OVER VALUE BEFORE EXITING EDITION**
![FS3](https://user-images.githubusercontent.com/82335501/159076238-a0e19df5-28eb-4569-91e6-506544e2d80c.png)
### **JUMPS 2 CHANNELS BACK**
![FS4](https://user-images.githubusercontent.com/82335501/159076239-b4482f88-8a56-4885-93ed-6fc0a52fdba4.png)
### **MISSING FAILSAFE IN PC SIMULATION RADIO**
![FS5](https://user-images.githubusercontent.com/82335501/159076241-7e5d23e4-a537-422d-8910-5a0ee7e2cc2f.png)
### GIF OF BUG
![FSBUG](https://user-images.githubusercontent.com/82335501/159080138-62e7ffe9-c4a2-47f8-8a77-9b7cce706721.gif)

**Comment by pfeerick** [comment]
To the best of my knowledge, this was resolved in an unlinked PR done during 2.8 along with fixes to the failsafe page generally. Simulator as of 2.8.x shows the failsafe options, and on the radio, there are now buttons for each channel to either set configurable options for each channel (Hold, None, Preset) and to set the custom value to the current channel value. 

#2170 and #2507 have some bearing on this. But the bulk of the fixes probably came in as part of the LVGL rewrite of 2.7 and 2.8.
