### ISSUE TITLE
new MPM protocol list entry displayed as ???

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#1717]
**Describe the bug**
MPM protocol from latest master c327c6c not correct listed.
All new entries are displayed as ??? .

**To Reproduce**
use companion c327c6c

**Screenshots**

![MPM_protocol_list](https://user-images.githubusercontent.com/29702171/159294401-cfdb327a-375c-4337-a103-b5850333c669.jpg)

@pfeerick pls can you check whats wrong.

**Comment by elecpower** [comment]
https://github.com/EdgeTX/edgetx/commit/c327c6c0dbbf344a54edaa925baad67888253b1a was incomplete and also found another issue whilst investigating
