### ISSUE TITLE
info line shows only 3 instead of 4 widget

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#1718]
**Describe the bug**
since #1089 the info line shows only 3 widget instead of 4 as before, on my tx16s

**To Reproduce**
using latest master 

**Screenshots**
![screen-2022-03-21-211026](https://user-images.githubusercontent.com/29702171/159355794-4dca3440-3e0e-4d04-bfaf-bb0f14bef47c.png)

**General information**
 - EdgeTX 2.7.0 latest master
 - RM TX16S

**Comment by pfeerick** [comment]
This is mainly due to the GPS icon also being enabled dynamically at runtime now, which is to the left of the battery and speaker icons... but I'll see if it's possible to get that space back if the GPS mode is not enabled.

**Comment by TheIsotopes** [comment]
aaahhh, ok. so not a bug. Thanks for clarification.

closed.

**Comment by pfeerick** [comment]
Well, lets just say unintended side effect... :grin: ... easily fixed... you have can the forth zone back if the internal GPS is not enabled, and it will be taken away again if it is as that space is needed. Some better management (and options?) will be needed if remaining unimplemented icons are actually implemented... i.e. receiver battery icon, model altitude
