### ISSUE TITLE
Preflight Checks Pots & Sliders Auto Not Saved

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#1730]
Running 2.6 release firmware on TX16s.

Pots & Sliders Check Options: Off, On, Auto. Auto is supposed to save the positions of highlighted pots and sliders on model change or power off. This function does not appear to work. The values can be changed by deselecting and reselecting the pot/slider/6p; however, absent toggling off/on, updated values are not automatically stored on power off.

**Comment by wimalopaan** [comment]
Duplicate #1663
