### ISSUE TITLE
Yaml conversion of mixer with GV1 as offset leads to corrupt .yml file

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#1734]
OpenTX 2.3.14
EdgeTX 2.7.0-rc1 (289b1168)
Radiomaster TX16s

[GV1YAML.OTX](https://github.com/EdgeTX/edgetx/files/8353007/GV1YAML.OTX.zip) defines a simple model with a mix line "source=SG, weight GV1, offset GV1:

![image](https://user-images.githubusercontent.com/5615068/160178991-be10c58d-0faa-4f0f-a0fd-31db18d22b19.png)

After conversion with firmware simulator the resulting [model1.yml](https://github.com/EdgeTX/edgetx/files/8353015/model1.yml.zip) defines the mixer offset as "-GV0 instead of "GV1". Please see line 88 of the attached .yml file.

![image](https://user-images.githubusercontent.com/5615068/160180891-bc654aaa-f790-426f-af41-94ce4fa8647b.png)

Error message after restarting firmware simulator:

![image](https://user-images.githubusercontent.com/5615068/160181205-d0f1d759-b2c1-48e2-b4a7-5fdd7eeca194.png)

**Comment by mha1** [comment]
Seems like mixers with any (positive) GV in the range GV1 to GV9 do have the problem. 

To reproduce clear RADIO and MODELS folder on the SD card and use the attached .otx file [GV1YAML1.otx.zip](https://github.com/EdgeTX/edgetx/files/8355304/GV1YAML1.otx.zip) to put radio.bin and models.txt in your RADIO folder, model1.bin into the MODELS folder. Turn on your radio and let 2.7.0 do its conversion work. Turn radio off and on again. Does it complain about a bad radio1.yml file? Check radio1.yml in the MODELS folder of the SD Card for strange mixer offsets, e.g. "-GV0", "1025" or "1032".

**Comment by pfeerick** [comment]
Yup, it looks like we have another variation of #1516 rearing it's ugly head

**Comment by mha1** [comment]
@jfrickmann can you please have a look at this. Seems you are the expert. This bug looks to be related to https://github.com/EdgeTX/edgetx/pull/1516 and https://github.com/EdgeTX/edgetx/pull/1500 but this time conversion from OTX to YAML misbehaves for mixer offsets using GV's. Edgetx radio generated .yml's seem to be written and read ok. This bug looks to be OTX -> YAML conversion specific.

**Comment by pfeerick** [comment]
BIN => YAML conversion, radio side only. As you say, companion seems fine.

**Comment by mha1** [comment]
Just a side note: I tried to reproduce this with 2.6. 2.6 conversion also messes up mixer offsets using GVAR'S. For example a mixer with weight GV1, offset GV1 turns out as weight GV1, offset -GV1.

**Comment by pfeerick** [comment]
>I tried to reproduce this with 2.6

Can you clarify what you mean by that... do you mean as in 2.6 -> 2.7, or 2.5 -> 2.6? As the latter would be no surprise, but the former is a problem...

**Comment by raphaelcoeffic** [comment]
In fact you can do the following on radio:
- use GV1 in mix line offset
- reboot or change to another model and back
- check the offset value (spoiler, it will be 0)

**Comment by mha1** [comment]
> > I tried to reproduce this with 2.6
> 
> Can you clarify what you mean by that... do you mean as in 2.6 -> 2.7, or 2.5 -> 2.6? As the latter would be no surprise, but the former is a problem...

Sorry for being not precise. I meant converting OpenTX 2.3.14 generated .bin's with EdgeTX 2.6 release

**Comment by mha1** [comment]
> In fact you can do the following on radio:
> 
>     * use GV1 in mix line offset
> 
>     * reboot or change to another model and back
> 
>     * check the offset value (spoiler, it will be 0)

What scenario do you mean?

**Comment by pfeerick** [comment]
> * check the offset value (spoiler, it will be 0)

I'm not seeing this on 2.6.0 TX16S with a power cycle... remains GV1. But I do get it (reset to 0% weight) with -GV9, but not with 2.7.0 since most of the -GV issues were fixed already.
