### ISSUE TITLE
Setting compile-time option TIMERS=1 gives compilation error 

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#1735]
In `view_statistics.cpp`  the element `timersStates[2].val` is used unconditionally.

**Comment by raphaelcoeffic** [comment]
And I believe the YAML parser would need to be regenerated before, but this is just one aspect.

**Comment by gagarinlg** [comment]
Do we want to remove the TIMERS compilation option?

**Comment by pfeerick** [comment]
That, or we simply make that displaying that field conditional, as `#if TIMERS > 2` is used elsewhere also. Need to know why having only two timers would be relevant now, as I *think* this is legacy from the sky9x targets.
