### ISSUE TITLE
! switch state not working with timers and missing !switches

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#175]
Affects both X9D+, TX16S, and T-Lite.

The !switch states are not correctly triggering timers in either the Start, ON or THs states. If I set Timer1 to ON, with !SAup as the switch state, it does not matter what position I put the switch in, the timer keeps counting regardless.

Additionally, !SC and !D are missing on the T-Lite. For completeness, !SH is also missing from the X9D+ and TX16S.

**Comment by raphaelcoeffic** [comment]
> !SC and !D are missing on the T-Lite. For completeness, !SH is also missing from the X9D+ and TX16S.

@pfeerick I'll fix that one as well right away
