### ISSUE TITLE
NV14: extra bottom padding if touchscreen

### ISSUE THREAD

**Issue by Ktr128** [EdgeTX/edgetx#1751]
Extra bottom padding if touchscreen doesn't work on radio ->hardware screen.
I tried to remove the condition for the compiler in the radio_hardware.cpp file 

#if defined HARDWARE_TOUCH...
It did not help.
Padding appeared after adding a line
486: new Subtitle(window, grid.getLineSlot(), "temp", 0, COLOR_THEME_PRIMARY1);

NV14
[v2.7.0-rc1]

![Снимок экрана от 2022-03-28 16-27-11](https://user-images.githubusercontent.com/98200485/160394074-21c27fe0-e769-4b08-92c8-869ac7738c08.png)

**Comment by JimB40** [comment]
TBH I would add Bottom Bar like Top Bar (with HARDWARE), Even empty ATM.
30 pixels less in horizontal will not make difference still sucessful touch on anything placed like "Analogs" or "Keys" is long term quest now.
