### ISSUE TITLE
Theme with no text following "info :" crashes Companion after opening model using this theme 

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#1762]
Radiomaster TX16s, FW EdgeTX 2.7.0-rc1.

To reproduce:  Unzip [Black.zip](https://github.com/EdgeTX/edgetx/files/8374446/Black.zip) to SD Card THEMES folder. Select model, select theme Black. Connect radio to USB. Duplicate SD card to PC. Start companion and read models and settings from radio. Save as documentxx.etx. Point settings/settings/SD structure path to copy of SD card. File/open saved documentxx.etx, select model having black theme.

**Comment by elecpower** [comment]
Running Companion in debug mode

> terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  yaml-cpp: error at line 7, column 1: bad conversion

Adding any character for the info label value results in no crash.
