### ISSUE TITLE
View text and model notes have line breaks at 60% of screen width on TX16s 

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#1768]
Radiomaster TX16s, FW 2.7.0-rc1

View text and model notes break [TESTHoTT.txt](https://github.com/EdgeTX/edgetx/files/8381208/TESTHoTT.txt) much to early.

![screen-2022-03-30-150359](https://user-images.githubusercontent.com/5615068/160853737-6de3dbf9-047e-48cd-b48c-0338bc329fc9.png)

**Comment by raphaelcoeffic** [comment]
Nice test text :-D I think we should wait for LVGL port to complete, as the library has support for all this, and we don't need to care ourselves about it.

**Comment by eshifri** [comment]
This   is a side effect of using TT fonts: we need to know the length of the string before displaying it and with variable width of a letter we have to estimate for the worst case.

**Comment by pfeerick** [comment]
ty for spotting... yes, closed by lvgl and #2070

**Comment by mha1** [comment]
Thanks to both of you
