### ISSUE TITLE
Typo in SF Func selection list (SetFailsfe)

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#1772]
Radiomaster TX16s, FW 2.7.0-rc1 - as some other texts in the same list are longer I think it is safe to change this to SetFailsafe 

![screenshot_tx16s_22-03-30_18-35-46](https://user-images.githubusercontent.com/5615068/160886649-1ab06dcb-9f5b-4e32-8461-49b61dc4d696.png)

**Comment by mha1** [comment]
better to change to "Set Failsafe"?

**Comment by gagarinlg** [comment]
not yet, give me a moment ;)

**Comment by mha1** [comment]
I don't mind at all you taking two moments.

**Comment by gagarinlg** [comment]
as soon as some approves my PR, it will be fixed.
