### ISSUE TITLE
Companion - can not set Trainer Mode to OFF and Master/Multi

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#1796]
**Describe the bug**
Trainer mode cannot be set to Master/Multi in the Companion, but it works on the transmitter.

**To Reproduce**
using latest EdgeTX on Zorro and latest Companion

**Screenshots**

![Screenshot 2022-04-03 095542](https://user-images.githubusercontent.com/29702171/161417507-67fd8384-3f20-4683-9393-d9d915051268.png)

**General information**
 - EdgeTX 2.7 https://github.com/EdgeTX/edgetx/commit/092acd2d96955e2551292185631c3de391830206
 - Companion 2.7 https://github.com/EdgeTX/edgetx/commit/1cda6e6ddd20078dba39e9d5b1f9a559b526f881
 - Zorro

**Comment by elecpower** [comment]
Master/Multi also missing in Companion

**Comment by TheIsotopes** [comment]
@elecpower I looked at it again on OpenTX, `OFF` is not displayed either there.
From my point of view switching it `OFF` is not intended, imo it shouldn't be in the list then. 

So only the Master/Multi entry is missing.

**Comment by pfeerick** [comment]
This is not OpenTX :-P 

Companion should reflect the radios, which *do* have an off option now, and that is intended - Master is not the same as Off. 

All radios should have OFF as an option now, it is not restricted to being the NV14 only.

**Comment by TheIsotopes** [comment]
ok then leave it in, I'm not mad about it either, find it even better
It just looked a bit unintentional since it's called `Off` and not `OFF` like everyone else.
