### ISSUE TITLE
Bug: Touch Screen - Top bar setup widgets - can't get back

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#18]
Earning my keep, breaking stuff...

1. Top bar
2. Screens setup
3. Setup widgets
4. Select any of four boxes
5. Select widget
6. Select any widget
7. Press some other part of of the screen other than a top bar widget
8. Press return until the cows come home with no luck
9. Press on one of the top bar widget boxes
10. Press away from the options
11. Pressing return will now work

Showing stuff is working, and not working... with a interruption in the middle... first 'crash' I've had so far... early days...
https://youtu.be/DZvhjHDHnAA

There _may_ appears to be a similar state related bug... otherwise I'd open another issue. At step 3, you can still get into any of other menus by pressing the top bar (other than a widget box), meaning you can go into the menus whilst in edit mode... 

Sorry for the off-angle video... was looking at the Tx screen, not the phone...
https://youtu.be/ABwXsHME0fY

tx16s-edgetx-60726891, #85ebb168

**Comment by pfeerick** [comment]
Eirik "grep boy" Toft on the discord did a video showing this: https://youtu.be/t6h5e1KAylk

**Comment by raphaelcoeffic** [comment]
I think the "RTN" (weird name when actually "EXIT" is meant.....) button should do that, but many more input is allowed whereby it should not. The fix looks like this: forbid other inputs so the UI does not get input that bugs state.

**Comment by pfeerick** [comment]
Part of that should since you are editing the top widgets, to lock out touch input outside of the top bar ;)

**Comment by pfeerick** [comment]
I can confirm... no more escaping from the widget setup! :)
