### ISSUE TITLE
Select model screen does not display an odd number of models more than three.

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#180]
**Describe the bug**
Select model screen does not display an odd number of models more than three.  So if you have four models all our shown.  If you have 5 models, you only see 4 and cannot scroll to the 5th.  If you add a 6th model, you will now see all 6 models. Testing on TX16s

**To Reproduce**
1. Go to model select screen
2. Copy any model until you should have 5 models in total
3. Try to scroll either with touch or scroll wheel to see the 5th model, you will not be able to.
4. Create another model copy
5. You will now be able to scroll to see 5th and 6th model

**Expected behavior**
You should be able to see the 5th model without having a 6th model

**Screenshots**

**General information**
 - OpenTX version /2.4.0 (fee3ca7b)
 - Hardware Radiomaster TX16s
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by pfeerick** [comment]
lol... god, so I wasn't going nuts earlier... I thought something weird was going on with the selection menu when I was creating several models in succession... just didn't place it at the time. Thanks!
