### ISSUE TITLE
GPS widget text colour 

### ISSUE THREAD

**Issue by Flying-Potatoes** [EdgeTX/edgetx#1802]
Hi

I have a theme on my TX16S Max which makes it difficult to see black text in widgets. So I have set the text colour to white, but with the GPS widget colour defaults to black on power up. I have to go to widget settings, do absolutely nothing, and then out of settings to get the colour to white. Tried 2.7 rc1, and subsequent nightlies. Thanks for all your work! 

Tia
Flying Potatoes.

**Comment by pfeerick** [comment]
Can you give a little more information... which GPS widget is this? Or is this another widget such as the Value widget, set to read from the GPS sensor?

**Comment by Flying-Potatoes** [comment]
Peter

Its the Moschotto OpenTX/EdgeTX GPS telemetry lua. I don't have my tx to hand right now, but will have later. 

Thanks.

**Comment by pfeerick** [comment]
That's ok... that's what I needed to know. I'll have a look, and will either raise an issue or fix over there, as it's most likely a bug in the initalisation of his script... i.e. it's reverting to a default color, rather than the one configured in the widget options.

**Comment by pfeerick** [comment]
It's a minor bug in the widget - the configured colour is only being processed when the widget options are updated... moschotto/OpenTX_GPS_Telemetry#24

**Comment by Flying-Potatoes** [comment]
Thank you very much indeed for your intervention. I saw what you were doing but wasn't able to respond till lunchtime. 

Best, 
David

**Comment by Flying-Potatoes** [comment]
Peter

Thank you very much!

Best,
David.

**Comment by Flying-Potatoes** [comment]
Peter

I feel slightly stupid, but am unable still to get this to work. I have
redownloaded the widget from releases with no joy. How do I get a version
with the merged patch?

Best,
David.

**Comment by Flying-Potatoes** [comment]
Sorted via delete, copy, paste.


Sorry to be a nuisance,
David.

**Comment by pfeerick** [comment]
Glad you got it working... that was exactly what I was going to recommend... happy flying! :)
