### ISSUE TITLE
lcd.drawAnnulus display bugs using in widgets

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#1808]
Since I've started to use this func in FM2M Widgets Pack (timer & clock) I found it's behaviing oddly

During scroll Annulus is drawn on "other" main screen

![screen-2022-03-31-071028](https://user-images.githubusercontent.com/46420768/161796493-3095f23d-275f-4251-a86e-2a2592876608.png)
![screen-2022-03-31-071131](https://user-images.githubusercontent.com/46420768/161796574-773f2c03-be1b-4ba7-948e-11c2c52c84b9.png)

Right position on timers
![screen-2022-03-31-071147](https://user-images.githubusercontent.com/46420768/161796724-2b429109-f451-4746-9993-4ec3feeb1d2b.png)

Ghosted on next main view
![screen-2022-03-31-071155](https://user-images.githubusercontent.com/46420768/161796794-935a611d-dc4a-47bf-b234-3e77111f4037.png)

Also function ignores widget size and draws outside widget. Where other lcd.draw functions are clipped correctly
![screen-2022-03-31-071257](https://user-images.githubusercontent.com/46420768/161797111-74f8aef8-4a00-4a63-8166-99229aff237e.png)

@pfeerick tried to find who made PR but can't.
Seems like ETX add-on but not sure. @jfrickmann you know something about it?

**General information**
 - EdgeTX version 2.7.0 RC1
 - Hardware RM TX16S

**Comment by jfrickmann** [comment]
When I found it in the code, I added some documentation, but I believe that the underlying drawing function was implemented in https://github.com/EdgeTX/libopenui/commit/df766a4da41a103dff983e7d52ff38f339bc37fa

**Comment by pfeerick** [comment]
Yes, new/related to EdgeTX - PR https://github.com/EdgeTX/edgetx/pull/147

![image](https://user-images.githubusercontent.com/5500713/161873561-215131be-07d1-487a-a1b9-315e14263b50.png)

![image](https://user-images.githubusercontent.com/5500713/161873291-07bfad75-071d-4d9c-95de-cc09d8571aaa.png)

**Comment by JimB40** [comment]
Hmm nice. not goinig to ask auhor :) 
So @raphaelcoeffic you just merged or have some idea how it works?

**Comment by gagarinlg** [comment]
Do you know if this still happens with the current nightlies?

**Comment by jfrickmann** [comment]
No, sorry!

**Comment by pfeerick** [comment]
No, tested with today's nightly (e40e7ccc) on TX16S using the Clock widget from Robert's [FM2M Widget Pack](http://fm2m.jimb40.com/WidgetsPack.html) and this is good now (it had bad screen artefacts before). The only issue now is one of performance... i.e. as long as there is a widget on the active screen using `drawAnnulus`, overall radio performance seems to be sluggish. Yet you can switch to another screen that doesn't have a widget using `drawAnnulus` present, and all is good, until you switch back. Part of the "why is widget running when in settings?" question I think you raised before.

**Comment by gagarinlg** [comment]
Just take a look at the LVGL code to draw this stuff and you will understand the speed. ☹️
