### ISSUE TITLE
Timer name not displayed in v2.7.0-rc2

### ISSUE THREAD

**Issue by Salto42** [EdgeTX/edgetx#1816]
Timer2 named "Batterie" is not displayed in v2.7.0-rc2, OK in v2.7.0-rc1 on T16 and TX16S.
I choose the value display.

![v2 7 0-rc1](https://user-images.githubusercontent.com/19374604/162452035-43298128-a9a6-4b47-9d5e-d355a50db3e8.jpg)

![v2 7 0-rc2](https://user-images.githubusercontent.com/19374604/162452043-73411d11-2265-4323-bf8c-4c6d565b529f.jpg)

**Comment by eshifri** [comment]
Can it be related to #1770 ?
