### ISSUE TITLE
Jumper T16 - Telemetry button does not show screen setup (User interface/setup Widget)

### ISSUE THREAD

**Issue by Tom-ahawk** [EdgeTX/edgetx#1829]
**The bug**
The "TELE"-button on the transmitter does not got to "Screen setup" (User interface/setup Widget). It in stead displays the same as pressing the "SYS"-button (system setup - Tools/SD-HC-CARD/RADIO SETUP/THEMES....).

I just cant find the "User interface/setup Widget" on my Jumper T16.

**To Reproduce**

**Expected behavior**
The "TELE"-button  should show Screen setup" (User interface/setup Widget)

**Screenshots**

**General information**
 - EdgeTX version 2.7.0 (f4c09285)
 - Jumper T16
 - Coming from OpenTX this version of EdgeTX ( V2.7.0 (f4c09285) is the first EdgeTX on my transmitter.

**Comment by pfeerick** [comment]
In the interim, you should be able to use the carousel menu to get the screen settings... and unfortunately I can't repo this on simulator, so there is either something different happening on hardware, or possibly something wrong with input (i.e. ribbon cable)... 

https://user-images.githubusercontent.com/5500713/163499891-ae0b615c-2cac-4f84-a52c-627964058ca8.mp4

Does the keys diagnostics page show the tele (and other) key being read properly?

https://user-images.githubusercontent.com/5500713/163500803-4b70d422-2734-4a55-8d9b-95637f7f4c99.mp4

**Comment by Tom-ahawk** [comment]
It was the #$*&&! ribbon cable. I relay hate this radio.

**Comment by pfeerick** [comment]
Well, f$%k... ribbon cable strikes again... but to be fair, I've had a switch issue on the TX16S as well... but for sure, Jumper had some major ribbon issues :grin: Glad it is working properly for you now though! Early in the piece Jumper was offering to send out replacement "premium" ribbon cables... might be worth seeing if they still do that, just in case you need it in the future.
