### ISSUE TITLE
After having mounted SD, LUA widgets lists not populated correctly. 

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#183]
TX16S, gh action build for head, https://github.com/EdgeTX/edgetx/commit/4627b3c3240844dd3e07f06d845565c7cb9debd4

When I go to either...

```
Menu -> Screen Settings -> User Interface (Top Bar) -> Setup widgets -> select a place for a widget -> Select widget
Menu -> Screen Settings -> Main View 1 (Layout)     -> Setup widgets -> select a place for a widget -> Select widget
```
... after having connected USB Storage mode, the lists sometimes have garbage values... and it changes every time. I have four 'widgets' in my `/WIDGETS` folder, and the first of the four screenshots correctly shows the list correctly ((I didn't connect USB storage for that one).

![image](https://user-images.githubusercontent.com/5500713/121626040-03b63c80-cab8-11eb-9aa3-fcf8356620f4.png)
![image](https://user-images.githubusercontent.com/5500713/121622429-54766700-cab1-11eb-8f78-da409e2321f9.png)
![image](https://user-images.githubusercontent.com/5500713/121625776-7e328c80-cab7-11eb-88b1-a1d96ae734e1.png)
![image](https://user-images.githubusercontent.com/5500713/121625786-81c61380-cab7-11eb-833a-149f13152c6d.png)

**Comment by JimB40** [comment]
Same on my TX16S. Haven't time yesterday to post it :)
