### ISSUE TITLE
Deselect battery and loudspeaker symbol in system settings.

### ISSUE THREAD

**Issue by Tom-ahawk** [EdgeTX/edgetx#1834]
Why not make place for a new top bar widget placeholder if the user can deselect in the system options, the standard battery and loudspeaker symbol.

The transmitters battery or/and volume level can then  be put in a more customized way in a widgets. 

![image](https://user-images.githubusercontent.com/35527507/163594729-3242cd2d-7b30-4dbb-b0dc-951188f53e7a.png)

**Comment by philmoz** [comment]
Handled in PR #3700

**Comment by raphaelcoeffic** [comment]
To be released in `2.10`, available today in nightly builds.
