### ISSUE TITLE
NV14 Top bar icon graphics 

### ISSUE THREAD

**Issue by Outwide** [EdgeTX/edgetx#1837]
Describe the bug
In the Top menu bar you can see the date etc. Was not shown before.

To Reproduce
1: When in Model setting / Radio settings and scrolling top bar left and right visible numbers, (the Date). See picture attached 

Expected behavior
When in Model setting / Radio settings just see the icons only.

Screenshots
![IMG_20220416_181359](https://user-images.githubusercontent.com/89946386/163668788-1a57cd55-ca5c-48ef-b41a-06ddeb3d96c9.jpg)

I like Edgetx.
General information
EdgeTX v2.7.0 Nightly-ddf011ff 
FLYSKY NV14 
FS-iA6B

**Comment by gagarinlg** [comment]
fixed with 2.8
