### ISSUE TITLE
Remove Helicopter Tab from Model Menu

### ISSUE THREAD

**Issue by Anton33455** [EdgeTX/edgetx#1841]
EdgeTX companion does not allow installation of firmware yet, the only option is Flasher
But unfortunately, Flasher Software does not have an option to remove Helicopter Tab from model menu.
Please add this feature to the flasher.  Most of the people in RC community do not fly Helicopters and 
having that tab coming back from old OpenTX is confusing and adds unnecessary complexity for new pilots.

Other than that EdgeTX is the best thing since sliced bread.

**Comment by pfeerick** [comment]
It is planned that in 2.8 it will be possible to turn specific tabs off as an actual option in the firmware at the , as well as starting to move towards being able to turn whole groups of features off... i.e. remove all references to GV if you don't use them, flight modes, etc. Issue tracking that is https://github.com/EdgeTX/edgetx/issues/1692

However, at the present time, check out the multilingual NOHELI builds in the "Unofficial builds" section of the release notes. It's not quite as simple, as you'll need to download the zip for your transmitter, and then grab the firmware for your chosen language, but given you would normally at most do that every three months if you're following the release version, it's not that awkward.
