### ISSUE TITLE
Pot warnings not properly read from radio in Companion 2.6 and 2.7

### ISSUE THREAD

**Issue by mrduncan626** [EdgeTX/edgetx#1843]
I see this issue was reported and closed several months ago but I didn't see what the conclusion was..  

I was having issues with Companion not properly reading the pot warning settings from the radio in Companion 2.6.  I just upgraded to 2.7 and this issue still exits.

I only have 2 pots warnings setup on my radio but when Companion reads the models from my radio, all the pot warning are activated.  I then have to turn off the pot warning on all the models I'm not using before I write the model changes back to the radio. 

If I only had a couple of models setup, this would be much of a problem.  But, I have 25+ models on my radio.

My radio is a RadioMaster TX16s.

**Comment by elecpower** [comment]
Confirmed still unresolved. There are in fact multiple issues:
1. Companion yaml handling
2. B&W and color radio firmwares/simulators store and interpret the bit set value differently eg B&W zero = all on whereas Color zero = all off
3. Companion always assumes B&W
4. Settings conversion between B&W and Color radios is affected (likely both Companion and radio firmware)
