### ISSUE TITLE
Support for internal gyro on horus x12s

### ISSUE THREAD

**Issue by Luznatural** [EdgeTX/edgetx#1852]
We have been wayting for this issue for three years in opentx. All Horus users (Frsky X12S) are very upset with opentx. They abandoned us forever.
It would be nice to get internal gyro working on Frsky X12S using Egde TX
I kindly request to try it
Thanks in advance
V/R

**Comment by gagarinlg** [comment]
I am not sure if any Dev has one, I do not have one.
What do you expect from the gyro? Just have the gyro axis as additional inputs, like sticks and sliders?

**Comment by rotorman** [comment]
@Luznatural Work is underway in PR #1744 , please have just a little bit more patience.

**Comment by Luznatural** [comment]
In theory, and always as advertised by frsky, this feature should permit to operate servos (i.e. gimbals for a camera) just by moving or inclining the transmitter. In other words, use the transmitter itself as a joystick.

**Comment by 1Sven** [comment]
The gyro means for me "Bierschalter"... pafleraf will do that in the near future, really, it is coming!

**Comment by Luznatural** [comment]
Thanks to all of you on behalf of all Horus X12S users!!!

**Comment by Luznatural** [comment]
Frsky X12S has an internal GPS and a 6-axis sensor (3-axis gyro and 3-axis accelerator) according the instruction manual and the advertised especificatrions.

**Comment by 1Sven** [comment]
Oh, ein Traum geht in Erfüllung... Super!

Raphael Coeffic ***@***.***> schrieb am Sa., 25. Juni 2022,
16:09:

**Comment by Luznatural** [comment]
Thank you very much!!!
