### ISSUE TITLE
X9D+ (2015):  splash screen and backlight color incorrect on startup

### ISSUE THREAD

**Issue by malinhiles** [EdgeTX/edgetx#1856]
**Describe the bug**
-On radio startup, the "EdgeTX" splash screen is shown for 2 seconds even though it is disabled in the radio settings. 
-While the radio is displaying this splash screen, the screen backlight is (incorrectly) the stock "deep blue" hue, and not the "white" hue as set by user in radio settings. After the radio has booted past the splash screen, the user defined "white" backlight color resumes.

**Steps to reproduce the behavior:**
1. Turn on radio
2. Observe startup behavior

**Expected behavior**
On radio startup, the "EdgeTX" splash screen should not be shown if disabled in radio settings. If the splash screen were to be enabled by the user, the radio should use the user defined backlight color from radio settings. 

**Screenshots**
 Here are some quick photos of the issue. This first photo shows the splash screen (that shouldn't be there because it's disabled) and the undesired "deep blue" backlight color on startup.
![IMG-2055](https://user-images.githubusercontent.com/93371446/163957403-a6b0b263-cde3-40f3-9205-d3146e39435c.jpg)

This photo shows that once past the splash screen, my "white" backlight color and intensity as set in the radio settings, resumes. 
![IMG-2056](https://user-images.githubusercontent.com/93371446/163957411-e0f5cf5b-f23f-4b15-be00-cd639bd5135e.jpg)

**General information**
 - EdgeTX version 2.7.0, commit 7ce8738
 - FrSky X9D+ 2015

**Comment by pfeerick** [comment]
Is this still an issue? There have been quite a few changes around startup and splash screen code, and I've never actually experienced this myself on X9D+ (I don't think).

**Comment by malinhiles** [comment]
Can no longer confirm on my own radio, I sold it 9 months ago.
