### ISSUE TITLE
Pregnant pause between two words when you play value

### ISSUE THREAD

**Issue by miggy1952** [EdgeTX/edgetx#1862]
Using EdgeTx Version 2.6 on Radiomaster Zorro.

Using any switch to play a value, you get for example 4.4..........(pause) ..... Volts

**Comment by pfeerick** [comment]
This sounds like a issue with the voice-pack - have you tried re-installing it? I believe RM shipped with the un-processed files from https://github.com/EdgeTX/edgetx-sdcard-sounds rather than than the release zip files, so they weren't trimmed or normalised.

**Comment by miggy1952** [comment]
Thanks Peter, your advice was 100% correct. All is now good.
