### ISSUE TITLE
[Bug]: Companion internal module cant be changed (Companion 2.7)

### ISSUE THREAD

**Issue by jasc76** [EdgeTX/edgetx#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![grafik](https://user-images.githubusercontent.com/42022027/164381709-e52af4b0-8787-4527-935f-3df46a8e085c.png)

I try to set multi in radio profile but it always reverts back to CSRF. 
2.7 Release Version
RM Zorro 4-1 

### Expected Behavior

Set internal module to MULTI 

### Steps To Reproduce

Open radio profile
set internal module
leave
open profile again
module is set back to CRSF

### Version

2.7.0

### Transmitter

Radiomaster Zorro

**Comment by pfeerick** [comment]
I can reproduce this, and is not limited to the Zorro, also applies if for instance you try to set TX16S to CRSF. Upon re-openeing the profile page it will revert to MULTI. 

![image](https://user-images.githubusercontent.com/5500713/164385472-b8bf7b73-9767-40a0-bfcc-915290badd3b.png)

**Comment by jasc76** [comment]
I also tried by loading settings from radio and hitting "save to current profile". Also does not work
