### ISSUE TITLE
B&W : Sorting of tools menu

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#1886]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Tools menu is currently sorted by the order files are added onto the SD card, i.e. in file system index order. 

### Describe the solution you'd like

It should be sorted alphabetically, like is now done on colorlcd radios since v2.6

**Comment by JimB40** [comment]
![Screenshot 2022-04-24 at 06 42 48](https://user-images.githubusercontent.com/46420768/164957388-5a81a9df-793f-4bb6-a3aa-90ec4c06c841.png)
![screenshot_x9d+2019_22-04-24_06-44-52](https://user-images.githubusercontent.com/46420768/164957390-0a65ff06-4cd7-4565-b1f0-5deec39378b8.png)

Remark: 
If TNS|<script name>|TNE is not found in script -> filename should be taken as name and storted with properly with other names.
