### ISSUE TITLE
Timer count direction option?

### ISSUE THREAD

**Issue by Daannoa** [EdgeTX/edgetx#1926]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently if we do not define a "start" time in the timers they count upward.(no notification when time is up because no time is set in "start")
If we define a "start" time in the timers they count downward and prevent me when the time set in “start” is past.

Personally, when I fly, I don't find this count down intuitive (you have to do a subtraction to find out how much time has passed) 
But I like to be notified when the time is up.

### Describe the solution you'd like

Would it be possible to have an option that would allow us to define in which direction the timer counts? (Count up / count down)

This would allow us to have a more intuitive timer (=> Count up)  AND be notified when the time is up.

### Describe alternatives you've considered

Currently I'm using logical switches to get the job done, but it's also not intuitive to set the "timer time" in the logical switch.

**Comment by eshifri** [comment]
Just set the starting value for timer to zero.

**Comment by pfeerick** [comment]
Title was a bit misleading @eshifri ... he is aware of setting it to zero, but wants to be able to count up to a time so don't have to do the math to figure out time elapsed.

Interesting idea... could be implemented with a choice (so you can can "Count direction: Up/Down", and then have the timer logic take that into consideration... zero for the time would then just mean no alarm if counting up.

**Comment by eshifri** [comment]
Aha, now I see. Personally, I think  this is counterintuitive: time left is more interesting, than time elapsed. But why not? :-)

**Comment by lshems** [comment]
Suggestion: leave all as it is, and just create a display option that shows timer setting minus remaining time.

Call the setting 'display' with options 'elapsed' and 'remaining'.

I do that in all my apps where I need an elapsed time, which is useful when you 'think' in target times that may vary.

**Comment by lshems** [comment]
This would prevent creating two sets of logic which only differ by the reference frame.

Voice commands should follow displayed value, or do you want to be able to set that independent? Yet another variable. Lol.

**Comment by pfeerick** [comment]
True, it is only the display logic that needs to change, not the actual timer logic - and there is no reason for the voice prompts to change - they only state the time :)

**Comment by eshifri** [comment]
I have functionality implemented, but with UI and storage I will wait for lvgl coming in.

**Comment by eshifri** [comment]
BTW, what do you think will be a better UI implementation: checkBox show elapsed or Choice: show Elapsed/show Left?

**Comment by pfeerick** [comment]
IMO a choice of "Show Elapsed / Show Remaining" ... no guessing as to what it shows then ;)

**Comment by eshifri** [comment]
Next question: color LCD only, or B/W radios as well?
I would think that for small screen radios this TAB is already overloaded with options...

**Comment by elecpower** [comment]
IMO having functionality differences between radios should only be due to radio capability not because the ui would be cluttered. If we have differences in settings then we have to add conversion code too and deal with the ongoing why doesn't this work or setting 'x' is missing on radio 'y'

**Comment by MervDale** [comment]
What is the difference with having the timer count up as it will announce the minutes, if you want to fly for six minutes then start your landing procedure at the five minute call.  I use the countdown timer every flight and just reset timer before every flight or it can be reset at engine off switch. Total flight time can be kept on another timer and manually rest if wanted

**Comment by eshifri** [comment]
The difference is the timer will expire, change color and announce expiration.
Personally, I doubt I would ever use it, but somebody finds it convenient - why not?

**Comment by lshems** [comment]
In competition flying you sometimes need to fly a certain time several times within a working window. Counting down to what you still need to fly is then for some much more intuitive to focus on then how much you have flown already. Also, it means that the countdown to do a quick turnaround for the next flight will always be the same countdown to zero. This will lessen the thinking, certainly on targets that are not whole minutes.
