### ISSUE TITLE
Sequence of Trims in flight modes menu not obvious

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#1928]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem? No

![image](https://user-images.githubusercontent.com/5615068/166253491-f41caacb-012b-4918-b380-7606acc5a27b.png)

The order of Trims to be manipulated can not be identified by looking at the Trims entry. This is frustrating and forces the use companion to adjust the trims behavior.

According to https://doc.open-tx.org/opentx-taranis-manual/software-overview/model_menus/flight_modes the order is RETA and most likely T5 and T6. This is an arbitrary order and only somewhat intuitive for a single control mode.  And who reads manuals, right?

### Describe the solution you'd like

If there is space enough the simplest solution might be to add the character representing the control that's manipulated with each entry, e.g.:
R=0, E+2, T=0, A=0, T5=0, T6=0 instead of =0, +2, =0, =0, =0, =0 

### Describe alternatives you've considered

Alternative might be a headline but this would limit the number of flight modes on screen to two. I could live with that in favor of clarity.

![image](https://user-images.githubusercontent.com/5615068/166263470-51dc9c4e-4a1d-4663-8a92-4cecfb1c1886.png)

### Additional context

For comparison check out Taranis b&w display and TX16s OpenTX display with clear indication of control to trim.

![image](https://user-images.githubusercontent.com/5615068/166301761-5d3de348-cb57-42d4-8d31-fee56f5e51e4.png)
![image](https://user-images.githubusercontent.com/5615068/166303609-e4509de6-9d11-459e-b058-e54eb936e2a9.png)

**Comment by pfeerick** [comment]
Duplicate of https://github.com/EdgeTX/edgetx/issues/1788

**Comment by mha1** [comment]
You want me to close it in favor of https://github.com/EdgeTX/edgetx/issues/1788?

**Comment by pfeerick** [comment]
Yeah, I think it is safe to do so... as mentioned in that one this is something likely to be fixed as part of the LVGL UI re-write. and there was some mention of exactly this the other night (but for performance reasons), so one way or another this will happen. Regardless, this adds to that issue since it's cross-referenced. 😉

**Comment by mha1** [comment]
Closed in favor of https://github.com/EdgeTX/edgetx/issues/1788
