### ISSUE TITLE
Horus x12s OneBit mode

### ISSUE THREAD

**Issue by jaroszmm** [EdgeTX/edgetx#1949]
I can't find the OneBit option in the hardware page. Updated from OpenTX so I would not need the hardware mod of the radio but can't find that option... Weird.

**Comment by pfeerick** [comment]
OneBit was only implemented for the X7 and X9 transmitters. ;) However, there was some discussion about it possibly being needed for X10 in #1188 - so it may be a good idea to do some testing to see if it's needed for more models. 

https://github.com/EdgeTX/edgetx.github.io/wiki/OneBit-Mode-for-X7-and-X9D-Radios

**Comment by gagarinlg** [comment]
done by #1994
