### ISSUE TITLE
Numeric fields edit navigation bug

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#197]
**Describe the bug**
Pressing RTN while in edit-mode closes view instead of going back to field focused state.
As far as I tested only numerical fields are affected and not all of them. If field id in group it works as expected

**To Reproduce**
1. Goto edit mode with any not grouped numerical field
2. Press RTN

**Expected behavior**
Pressing RTN while in edit-mode should go back to field focused state.

**General information**
 - EdgeTX 2.4   d99e7a04
 - RM TX16S

**Comment by pfeerick** [comment]
i.e. `Sys -> Radio Setup` and pressing `ENT` on any of the date or time fields to select it. Pressing `RET` jumps out of the menu rather than out of the field.

**Comment by eshifri** [comment]
It is the same behavior for sliders.

**Comment by eshifri** [comment]
The pull request did not go through.

The change is in the libopenui.

The fix is to add

  case EVT_KEY_FIRST(KEY_EXIT):
    return;

after line 104 in numberedit.cpp
