### ISSUE TITLE
Telemetry sensor logging doesn't log strings (CRSF FM)

### ISSUE THREAD

**Issue by tonyyng** [EdgeTX/edgetx#1991]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

CRSF uses strings for FM (!ERR, ACRO, WAIT, ANGL, etc.)  This gets logged as 0.

This issue was reported in OpenTX:
https://github.com/opentx/opentx/issues/6413

Apologies to teckel12 for borrowing his issue content.

### Expected Behavior

The log should contain the correct sensor values

### Steps To Reproduce

1. Use Crossfire telemetry
2. Enable logging of telemetry sensors, specifically FM (flight mode)
3. Set custom function to log telemetry
4. Review telemetry log and FM sensor values which are all zeros

### Version

2.7.0

### Transmitter

Jumper T16

### Anything else?

[Talon.250g-2022-05-23-172023.csv](https://github.com/EdgeTX/edgetx/files/8763472/Talon.250g-2022-05-23-172023.csv)

**Comment by stronnag** [comment]
It sees to me that the log writer does not cover the case of `UNIT_TEXT`, causing the default `value` / 0 to be written, rather than the text element of the union.
