### ISSUE TITLE
Missing options in Custom Failsafe mode settings screen

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2000]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Some protocols like FrSky and HoTT allow setting fail safe modes (Hold, Position, no Pulse) for individual channels. OpenTX allowed to set those under model settings, Failsafe mode, Custom, Set. EdgeTX doesn't have means of setting the modes. Here's what it looks like in OpenTX:

![c2](https://user-images.githubusercontent.com/5615068/170883889-facf27d1-27f1-4041-b74d-b485afcaf3d0.PNG)

OpenTX user interface: long pressing return at a highlighted field toggles to the next mode (Position with position in %, hold, None for no pulse)

EdgeTX only allows changing of the position value. There is no means of selecting Hold or None.

 

### Expected Behavior

Allow selecting Hold and None as fail safe modes for individual channels.

### Steps To Reproduce

1. go to model settings
2. select internal Multi andHoTT or FrSky as protocol
3. select Failsafe mode Custom, press Set

### Version

2.7.0

### Transmitter

Radiomaster TX16S

**Comment by raphaelcoeffic** [comment]
@mha1 i think we do have this page. I remember having to fix it a couple of releases ago.

**Comment by mha1** [comment]
Then I need a little advice how to select hold and none. In OTX you longpress enter while being in the respective channel's field

**Comment by raphaelcoeffic** [comment]
@mha1 Maybe I did not understand your question properly, but did you mean this?

<img width="476" alt="Screenshot 2022-06-20 at 09 14 59" src="https://user-images.githubusercontent.com/1050031/174545636-d032ee56-f359-4634-b9f4-659b218f441b.png">

The long-press on OTX is basically something to set the failsafe channels to the current values, right?
<img width="474" alt="Screenshot 2022-06-20 at 09 16 33" src="https://user-images.githubusercontent.com/1050031/174545926-cc44305f-6380-49a4-b7c6-d38596c760e7.png">

**Comment by raphaelcoeffic** [comment]
@mha1 thx, now I see what you mean.

**Comment by mha1** [comment]
@raphaelcoeffic  can you please take this out of triage

**Comment by mha1** [comment]
@raphaelcoeffic  this seems to be fixed by the rework done to the Failsafe mode/Custom/Set page, right?

**Comment by pfeerick** [comment]
It looks like it's mostly fixed... I think there is a bug of sorts around being able to set the failsafe values without a touchscreen... ie. when using the rotary encoder it scrolls between the parts of the number rather than changing the value... *somebody* forgot not all radios have touchscreens! :-P 😆 

![image](https://user-images.githubusercontent.com/5500713/182052347-a38528f7-2ae0-41fa-b508-beffa2477052.png)

https://user-images.githubusercontent.com/5500713/182052987-e5306543-8e2a-457a-8f40-0b3db70e570b.mp4

**Comment by raphaelcoeffic** [comment]
@pfeerick it seems there is some bug preventing the `NumberEdit` event call-back to be installed properly. I'm on it.

**Comment by raphaelcoeffic** [comment]
@pfeerick should be fixed now with EdgeTX/libopenui@fb01cf7ef9753e05d69

**Comment by pfeerick** [comment]
Yup, that did it...  :)
