### ISSUE TITLE
Baudrate / ‘max bauds’ setting is missing from GHST

### ISSUE THREAD

**Issue by int3fpv** [EdgeTX/edgetx#2005]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Baudrate option is missing from model menu in 2.7.1 when using GHST external receiver, switching protocol to CRSF shows the setting - see photo 

### Expected Behavior

Baudrate should be configurable for GHST?

### Steps To Reproduce

On 2.7.1 - Make a model, select GHST as external receiver and observe no Baudrate option 

### Version

2.7.0

### Transmitter

FrSky X9D+

### Anything else?

![F1D6019F-464C-4BE6-A66B-06D7DB101AE8](https://user-images.githubusercontent.com/106757616/171655166-ada877a7-5168-457e-ba13-42f94e0122bc.jpeg)

**Comment by pfeerick** [comment]
No, that is correct. Ghost does *not* supported configurable baud rate - it should always be set to 115k (or more accurately, the channels will be sent at 400k, and telemetry at 115k). Whereas TBS Crossfire supports 115k and 400k, and ELRS 115k to 5.25mb
