### ISSUE TITLE
Jumper T12 says Throtlle Warning every model change

### ISSUE THREAD

**Issue by nangel0** [EdgeTX/edgetx#201]
Jumper T12 flashed with latest 2.4 or lastest nightly trigers throtlle warning alert every time i change from a model to another. calibration doesnt change anything

**Comment by raphaelcoeffic** [comment]
@nangel0 are you sure correct mode is set? (Mode1 vs. mode2?)

**Comment by nangel0** [comment]
🤔 Not sure... 

Your are right, I set it up the first time when following the wiki forgot that after the second flash... It was mode 1...
