### ISSUE TITLE
Companion: Invalid read-write YAML settings when using external DSM Module

### ISSUE THREAD

**Issue by MRC3742** [EdgeTX/edgetx#2014]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Conversion from OTX.bin files to ETX.yml files on the radio appears to be working correctly.

When reading to Companion (v2.7.1 or a current self build 06/08/22 [33845b9d])
Any radio model with the external DSM Module set to subtype DSM2 loads and will write back to the radio correctly.
If the radio model external DSM module subtype is set to DSMX and read into Companion the external module is shown as "OFF"

On the radio model.yml file lists
moduleData:   1: 
type:  TYPE_DSM2
subtype: DSMX

Any saved file or write back to the radio changes the model.yml file to subtype:  "" 

The external DSM (Hack) Module info:
Three subtypes available: LP45, DSM2, DSMX
Limited to six channels only: normally CH1 to CH6
Only Receiver Numbers Allowed: 0 to 20

### Expected Behavior

When writing back to the radio module settings don't change.

### Steps To Reproduce

Setup a model on the radio with external module set to DSM and subtype to DSMX.
model yml file on the radio is written correctly as subtype: DSMX.
Read into companion and external module will now show as "OFF"
In Companion change the external module from OFF to DSMX and save the file or write back to the radio.
model.yml will now show subtype: "" 
The radio will show selected subtype  as LP45 

### Version

Other (Please specify below)

### Transmitter

Jumper T16

### Anything else?

EdgeTX Version 2.8.0 selfbuild (33845b9d) 2022-06-08

**Comment by pfeerick** [comment]
Reproducible (`simu` on the left, `companion` on the right) ... 
![image](https://user-images.githubusercontent.com/5500713/172593977-146c5649-f80d-4f84-8887-bcbe3616b832.png)

... and fix being pushed... damn typo!
