### ISSUE TITLE
Disable touch events on arm option

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#202]
*Before suggesting a new feature here, please search the open issue if there is already a request for the feature*

**Is your feature request related to a problem? Please describe.**
Several users have expresed concerns with accidental touch events happening when they are flying. Although I think that the likelyhood of this happening is rare, I can understand why people would want this option.

**Describe the solution you'd like**
1. An option to disable the touchscreen
and/or
2. An option to diable touch events on arm.
and/or
3. An option to disable touch events that is mappable to a switch.

**Describe alternatives you've considered**
The only alternative would be to not use ETX and stay with OTX :(

**Additional context**
I do not think that anything else is needed.

**Comment by pfeerick** [comment]
This is a duplicate of https://github.com/EdgeTX/edgetx/issues/185
