### ISSUE TITLE
SBUS Trainer in reboots radio

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#203]
Tested with RM TX16S 9faea55a with internalgps option built in.

HeadTracker with SBUS output ( https://github.com/dlktdr/HeadTracker/wiki/SBUS-Output ) connected to TX16S AUX1.
SYSTEM -> HARDWARE -> Serial port set to SBUS Trainer
Going in MODEL -> MODEL SETUP -> Trainer Mode and selecting Master/Serial, immediately reboots the radio.

GPS was not connected to AUX2 during the test.

**Comment by rotorman** [comment]
Retested with 26b15d4d, where INTERNAL_GPS and UNEXPECTED_SHUTDOWN were not specified and nothing connected to AUX1.
Same result, when SYSTEM -> HARDWARE -> Serial port is set to SBUS Trainer, as soon as under MODEL -> MODEL SETUP -> Trainer Mode is selected to Master/Serial -> Emergency Mode is shown.

**Comment by rotorman** [comment]
Hooked up to Segger Ozone via SWD, interestingly no HardFault or error on reboot, debugger does not even abort, the execution just continues after restart (with Ozone, have the UNEXPECTED_SHUTDOWN=NO built in).
Need more investigation what happens here.

**Comment by raphaelcoeffic** [comment]
> Hooked up to Segger Ozone via SWD, interestingly no HardFault or error on reboot, debugger does not even abort, the execution just continues after restart (with Ozone, have the UNEXPECTED_SHUTDOWN=NO built in).
> Need more investigation what happens here.

This is probably a watchdog reboot. Does it take 1-2 sec until it reboots? If yes, then watchdog.

**Comment by rotorman** [comment]
Nope, unfortunately the reboot is pretty immediate, when ran without stepping.
Due to lack of trace I have not yet pinpointed it.

Until so far I see that, after selecting Master/Serial, in aux_serial_driver.cpp auxSerialInit() is called and UART_MODE_SBUS_TRAINER() case is executed. It then lands in auxSerialSetup() where it reboots. It looks to me as if auxSerialSetup() is executed twice and on the second run it reboots.

**Comment by rotorman** [comment]
No additional hw is required to test this: set SYSTEM -> HARDWARE -> Serial port to SBUS Trainer, and as soon as under MODEL -> MODEL SETUP -> Trainer Mode is selected to Master/Serial, at least with RM TX16S you should have a reboot or Emergency Mode (according to UNEXPECTED_SHUTDOWN cmake option).

**Comment by pfeerick** [comment]
TX16S, Emergency Mode, recent https://github.com/EdgeTX/edgetx/pull/193 build. 
X9D+, Master/Serial is not an Model setup option
T-Lite, Doesn't have a serial option

**Comment by raphaelcoeffic** [comment]
This seems to be fixed for me with f3fbed5a1bad. Not sure why exactly, but we'll see.

**Comment by rotorman** [comment]
Solved by f3fbed5. Thx @raphaelcoeffic !
