### ISSUE TITLE
RTC voltage decimal in wrong position

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2032]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

RTC voltage shows 29.8v

### Expected Behavior

Should be 2.98v

### Steps To Reproduce

Check RTC voltage in the radio settings -> hardware menu

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Version 2.8 self build
![version](https://user-images.githubusercontent.com/1323809/173239673-fa3332a8-f5f7-471c-90fa-700c89b94e66.png)

![screen-2022-06-12-065913](https://user-images.githubusercontent.com/1323809/173239524-55440373-0fd0-4aa5-b942-c49c4e746f3c.jpg)

**Comment by raphaelcoeffic** [comment]
Please retry with current `Main`, was fixed this afternoon as well.

**Comment by rburrow87** [comment]
This also looks good now!
