### ISSUE TITLE
Home screen widget margins incorrect 

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2033]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The home screen widget margins are incorrect with various combinations of Flight mode/Sliders/Trims toggles.

### Expected Behavior

Widget margins should change appropriately when various combinations of Flight mode/Sliders/Trims are enabled.

### Steps To Reproduce

Have widgets on the home screen and toggle the different options in that view.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Version 2.8 self build
![image](https://user-images.githubusercontent.com/1323809/173239979-53650e23-83db-4f58-bf9f-4c2200135e41.png)

Screenshots of settings and the result below.

1:
![1_1](https://user-images.githubusercontent.com/1323809/173240050-777777e3-f3d6-4cfd-83dd-b70618eb0ce8.png)
![1_2](https://user-images.githubusercontent.com/1323809/173240052-bff15e6a-9a84-45b4-9356-dfebc7b9605f.png)

2:
![2_1](https://user-images.githubusercontent.com/1323809/173240054-2bc84c4b-c40a-48c1-a0f4-f9f9079f8d4c.png)
![2_2](https://user-images.githubusercontent.com/1323809/173240055-4e464e12-cc8b-4f9e-a250-33e720f6e9c1.png)

3:
![3_1](https://user-images.githubusercontent.com/1323809/173240057-56e9e385-8592-4fea-b307-f2ca1a153a18.png)
![3_2](https://user-images.githubusercontent.com/1323809/173240060-79823685-4146-457e-9a2e-3e678bf7d55a.png)

4:
![4_1](https://user-images.githubusercontent.com/1323809/173240062-f1a35743-a096-494b-a16c-6ea38521c6d0.png)
![4_2](https://user-images.githubusercontent.com/1323809/173240063-3c51c660-1992-4039-b5df-0b8bca5de48a.png)

5:
![5_1](https://user-images.githubusercontent.com/1323809/173240066-de871097-4f4e-4ab9-9a44-5064bc19ff13.png)
![5_2](https://user-images.githubusercontent.com/1323809/173240068-e662387e-f036-40f8-8b71-60ad429ce728.png)

**Comment by raphaelcoeffic** [comment]
@rburrow87 would you mind retrying with `main` again? I believe this has been fixed this afternoon.

**Comment by rburrow87** [comment]
Looks good now!
