### ISSUE TITLE
Use Horus X12S Internal GPS to set time, timezone

### ISSUE THREAD

**Issue by andytransonic** [EdgeTX/edgetx#204]
X12S Internal GPS support
 Internal hour auto-adjust from GPS date / time
 For auto-adjust, timezone setting should be in increments of quarter hour (For Nepal it's 5Hrs:45 mins)

**Comment by Luznatural** [comment]
Not only for autoadjust from GPS date/time, but for many other features: Distance to the plane, angle-off, plane localizing, etc

**Comment by raphaelcoeffic** [comment]
> Not only for autoadjust from GPS date/time, but for many other features: Distance to the plane, angle-off, plane localizing, etc

AFAIK, internal GPS is already supported on X12S. This issue is really just about being able to set the timezone properly.

**Comment by raphaelcoeffic** [comment]
Implemented in #3406
