### ISSUE TITLE
Pull OpenTX LUA ghostTelemetryPop() & ghostTelemetryPush() functions

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#2053]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No problem

### Describe the solution you'd like

This was introduced in OpenTx 2.3.15 and allows LUA scripts like BF Config to work properly wirh Ghost RCLink

**Comment by raphaelcoeffic** [comment]
Already implemented with #1377

**Comment by raphaelcoeffic** [comment]
And released since 2.7.0:
<img width="448" alt="Screenshot 2022-06-21 at 08 11 15" src="https://user-images.githubusercontent.com/1050031/174728579-18169f51-814f-4571-9bae-932948d281a7.png">
