### ISSUE TITLE
Select Model is showing only 2 columns of model-pics with nightly

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#2055]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Radiomaster TX16S
nightly #ebcd61f (2022-06-16T03:27:00Z)

Menu 'SELECT MODEL' is now showing only 2 columns

Release 2.7.1  is showing 3 columns - i have checkt this and reflashed version

Regards

### Expected Behavior

I expect 3 colums as in Release 2.7.1 

### Steps To Reproduce

1 tap screen 
2 choose SELECT MODEL

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by raphaelcoeffic** [comment]
Fixed with ba757bd41fcded9e
