### ISSUE TITLE
Add Companion installer to Nightlies.

### ISSUE THREAD

**Issue by dwheeld** [EdgeTX/edgetx#2067]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No. 

### Describe the solution you'd like

I would like to be able to download the current Companion installer while downloading nightly firmware.

**Comment by pfeerick** [comment]
Sorry, that will *not* be an option in the near future, as the github actions are taking long enough as it is. However, having said that PRs and merges into main that touch companion, already provide builds of companion, and have done for several months... 

https://github.com/EdgeTX/edgetx/actions/workflows/win_cpn-64.yml
https://github.com/EdgeTX/edgetx/actions/workflows/macosx_cpn.yml
https://github.com/EdgeTX/edgetx/actions/workflows/linux_cpn.yml
