### ISSUE TITLE
Add option to erase EEPROM data

### ISSUE THREAD

**Issue by gagarinlg** [EdgeTX/edgetx#2069]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When a radio that has been set up with a pre-YAML firmware it is impossible to do a reset to defaults, because the EEPROM data will be converted and used again.

### Describe the solution you'd like

Add an option, either in the boot loader or somewhere else (radio settings) to allow the users to erase the EEPROM.

**Comment by pfeerick** [comment]
That would also be a good time to handle re-adding https://github.com/EdgeTX/edgetx/issues/1521

**Comment by gagarinlg** [comment]
closed, because 2.9 does not support binary conversion anymore
