### ISSUE TITLE
Global functions - some values are not highlighted when activated

### ISSUE THREAD

**Issue by Eldenroot** [EdgeTX/edgetx#2087]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Set a new global function:
A) switch: S1 or 6P1
B) set backlight or volume function
C) try to switch to 6P2-6 and back - no highlighted even is activated on 6P1

This is inconsistent - why? Set Volume function on S2 -> it is highlighted all the time

### Expected Behavior

It should foolow activated/deactivated status

### Steps To Reproduce

Check above

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
The active/inactive state is dependent on the source set for 'switch'. So if you set use 'ON' as the switch source, and the function type is 'volume' or 'backlight', once you enable that function, it *is* always on/active/enabled.  ;) And setting the switch source to 6P1 is correctly showing active/inactive - so if that is not working for you, I suggest you double check you calibrated the 6POS when doing your stick calibration - as all analogs need to be calibrated, including sliders, pots and 6POS as it's a analog input also.
