### ISSUE TITLE
Flying modes - use trim value from previous mode is missing

### ISSUE THREAD

**Issue by Eldenroot** [EdgeTX/edgetx#2089]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Use value for trims from the previous flying mode option is missing...

### Expected Behavior

There should be this option.

### Steps To Reproduce

See above

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
Do you mean this? As it's not missing for me on TX16S and v2.7.1 - `=` will correctly use the trim from the other flight mode and `+` will correctly work in additive fashion. 

![image](https://user-images.githubusercontent.com/5500713/176402043-7bc16540-2f96-4b53-83aa-bd778f9bdc9e.png)
