### ISSUE TITLE
Curves - wasted space on the right side

### ISSUE THREAD

**Issue by Eldenroot** [EdgeTX/edgetx#2090]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

A lot of wasted and unused space on the right side.

### Describe the solution you'd like

We should display values, number of points etc.

### Describe alternatives you've considered

---

**Comment by ulfhedlund** [comment]
The right hand side seems to be the only place to click to be able to edit and remove a curve. This took me a while to figure out. Maybe it is intentional but to me it is not intuitive.

**Comment by Eldenroot** [comment]
#2508 - maybe these two could be connected

**Comment by pfeerick** [comment]
Possibly. It's really up to whoever decides to work on these, as while it it related to curves, they are two completely different screens, and different levels of complexity to implement. You are more than welcome to contribute some code towards this.

**Comment by gagarinlg** [comment]
Please check the current nightlies. The curves page hsa been redone.
