### ISSUE TITLE
Scrollbar visible when not needed

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#211]
**Describe the bug**
![Screen Shot 2021-06-14 at 20 16 52](https://user-images.githubusercontent.com/46420768/121939608-7c81f680-cd4d-11eb-9b4e-8d3e4be1b8d4.png)
Different non-scrollable popups across OS

**To Reproduce**
Open non-scrollable popup

**Expected behavior**
Scrollbar hidden

**General information**
-  EdgeTX 77b5a3a
 - RM TX16S

**Comment by raphaelcoeffic** [comment]
@JimB40 I believe there must one pixel too much in the calculation somewhere.
