### ISSUE TITLE
Pop up header?

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#212]
**Describe the bug**
![Screen Shot 2021-06-14 at 20 18 58](https://user-images.githubusercontent.com/46420768/121939879-c8cd3680-cd4d-11eb-8a20-cc714f85f450.png)
Header information is redundant and wrong color sheme

**Expected behavior**
![usb_popup](https://user-images.githubusercontent.com/46420768/121939983-e9958c00-cd4d-11eb-866c-7b45d3274626.png)

a. Scratch pop-up header
b. Adjust color and change header text to Call-To-Action type

**General information**
- EdgeTX 77b5a3a
- RM TX16S

**Comment by pfeerick** [comment]
Right, I'm in a position to change the colours on this... I just need to know what theme ids to use... 

i.e. This is using `COLOR_THEME_SECONDARY1` for the titlebar background, and `COLOR_THEME_PRIMARY1` for the titlebar text. 
![image](https://user-images.githubusercontent.com/5500713/140841424-c85acd44-5021-4e51-bd78-246c4a908a7c.png)

For the actual text in that titlebar, I would suggest "Select mode" as this is consistent with the B&W radios.

**Comment by pfeerick** [comment]
I.e. if I instead use `COLOR_THEME_PRIMARY2` for the titlebar text... it seems like that combination is readable across several themes?
![image](https://user-images.githubusercontent.com/5500713/140842316-a8df5177-a454-4eec-93c9-47bf9cd6a90c.png)
![image](https://user-images.githubusercontent.com/5500713/140842337-762545be-019e-4cca-be97-d89ae9160ad2.png)
![image](https://user-images.githubusercontent.com/5500713/140842358-05e18d11-0aa2-4e89-a041-4a7aa2b4c075.png)

**Comment by JimB40** [comment]
@pfeerick is this reusable piece of code?
I think I saw som pop-up lists without header.

**Comment by pfeerick** [comment]
It is the same menu, but without a titlebar set. All I need to know is what color theme parameter to use for the titlebar and what colour theme parameter to use for the titlebar text.

**Comment by JimB40** [comment]
So:
1. Pop-up background is SECONDARY3
![Screenshot 2021-11-11 at 05 02 47](https://user-images.githubusercontent.com/46420768/141235010-2144bf83-6ff4-440a-ac2f-afb163aca291.png)


not much visible in above examples (only as 1 pixel lines between selectable list items)
Once pop-up has options on the left it's better visible
![Screenshot 2021-11-11 at 04 56 35](https://user-images.githubusercontent.com/46420768/141234446-d2a8ff17-bd46-4802-affc-72948a40de0a.png)
Not 100% sure but it seems wrong color is used now.

2. Not focused list item
- background - PRIMARY2
- text color - PRIMARY3

3. Focused list item
- background - FOCUS
- text color - PRIMARY2

4. Header
- background - SECONDARY1
- text color - PRIMARY2

5. Pop-up frame (frame all around pop up) SECONDARY1

**Comment by pfeerick** [comment]
Sounds good, I'll try and look at that tomorrow :)

**Comment by pfeerick** [comment]
Ok, so things are not quite how they seem... :grin: Don't be confused with thinking things like the background for the menu is visible on the side... that is the toolbar background... which coincidentally is SECONDARY3... ;) And it would probably be a good idea to compare with current version of the firmware, as things like the lines between entries are not present any more ;)

Scroll maker is set to PRIMARY3. 

![snapshot_20](https://user-images.githubusercontent.com/5500713/141459031-b874d8b2-3742-46a3-8e10-01cf39b25c7b.png)

![snapshot_22](https://user-images.githubusercontent.com/5500713/141459057-d58806e9-9187-4e7b-9b31-7a1ee5b493b3.png)

![snapshot_21](https://user-images.githubusercontent.com/5500713/141459078-969ca281-5bd9-43c7-957d-db5478a8d2c7.png)

Using your UI testing theme:

![snapshot_23](https://user-images.githubusercontent.com/5500713/141459265-c7f785ae-e0e9-4a5e-b361-23df0c087df9.png)

![snapshot_24](https://user-images.githubusercontent.com/5500713/141459281-18c919cd-20a4-4ef2-a003-2819763a7a0e.png)

![snapshot_25](https://user-images.githubusercontent.com/5500713/141459295-46803921-b683-4135-8730-909d281ce3b0.png)

**Comment by JimB40** [comment]
Looks okay Peter. 
What I'd change is that scroll marker is lying on background not on list items obscuring them.
Technically what I do in TBS AL is that I'm not changing width of list (not to hassle with window size) but I draw rectangle underneath scroll marker. Rectangle height = list height & witdh = 1-2px more than scroll marker, color = window background color. So rectangle is clipping right part of list but gives right background color and nice 1-2px whitespace / separation in background color from list items.

Regarding 'Toolbar' it ma have own color but if not defined should be transparent (window background color)

**Comment by kevinkoenig** [comment]
Peter,
The lines not being there between entries looks like something I was playing with a while ago.  I thought I abandoned that, but you might find that this was a change I inadvertently made.

Kevin

Sent from Mail for Windows

**Comment by pfeerick** [comment]
I'm not entirely sure on that... I don't actually think they were supposed to be there in the first place, as I noticed there are calls to a... I think it was callled removeLines...  function over on the ETX side... so the lines probably shouldn't be there... But I think when you added the ability to add separators it was also changed then also. But for the better really, as if you look at any other menu ui, the only lines are those separating groups of entries, not each individual entry.

**Comment by JimB40** [comment]
This aestethic more than UX guys.
So as Bono said "With or without you" .... just be consistent :)

**Comment by pfeerick** [comment]
Resolved via 38308f6bef242673a0d4d0b094d51f9bbe5784bd
