### ISSUE TITLE
Special Function to set page of the home screen

### ISSUE THREAD

**Issue by MadMonkey87** [EdgeTX/edgetx#2135]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

On my homescreen I have different pages with a different purpose. For example during a regular flight it is important to keep the battery stats in sight so there is a page with relvant infos for this flight mode. During landing however this is less important, so for this flight mode I have a dedicated page showing speed, altitute and so on. What really would be helpfull is to have an option to set the active page directly. So switching to the landing flight mode would automatically switch the currently active page on the homescreen. 

### Describe the solution you'd like

This is how I imagine this: Provide a new special function with the following parameters:
 - Switch: trigger for the function, i.e in my scenario I would set this to a dedicated flight mode switch
 - PageIndex: number of the homescreen page that should be set

To be discussed: what should happend if there is currently a widget displayed in fullscreen mode (maybe as further parameter for the special function)? 
Option 1: don't do anything
Option 2: exit the full screen mode and switch to the desired page

### Describe alternatives you've considered

1. if there would be an possibility to set the current page from a lua script I also could do it that way: use the "lua" special function and trigger it i.e. for the landing flight mode. The script then would set the desired page

**Comment by eshifri** [comment]
If I read the code correctly, this can be done for color LCD TXs. For B/W the switching across telemetry screen is sequential: you can go to next/previous, but not to the arbitrary screen.
