### ISSUE TITLE
Model name editing painfully slow

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#214]
**Describe the bug**
https://youtu.be/F2AaCe0mnV4

**General information**
- EdgeTX 77b5a3a
- RM TX16S

**Comment by pfeerick** [comment]
Can you try again with the current head build - https://github.com/EdgeTX/edgetx/commit/802127852e401633512dcf75f5ee5c1d6eac7b41 or https://github.com/EdgeTX/edgetx/runs/2822429567 - as it seems to be gone now.

**Comment by raphaelcoeffic** [comment]
@JimB40 can you please re-test so we know if we can close it?

**Comment by JimB40** [comment]
Still slow with - 8021278

**Comment by raphaelcoeffic** [comment]
@JimB40 this is really strange, it works perfectly for me! (just tried on T18, I'll re-try on TX16S)

**Comment by pfeerick** [comment]
I'm still on https://github.com/EdgeTX/edgetx/commit/802127852e401633512dcf75f5ee5c1d6eac7b41 on my TX16S, and I don't have the problem shown in the video... character scroll speed is just fine for me... so this really is weird... 

Video will be viewable in a minute or two: https://youtu.be/OduMayUbtZk

**Comment by oryfoxer** [comment]
Can confirm, just updated to nightly and model naming is slow on TX16S

**Comment by JimB40** [comment]
2 vs 2 :)

**Comment by raphaelcoeffic** [comment]
@JimB40 have you tried without any LUA widgets installed? That might be related.

**Comment by JimB40** [comment]
Good track. Only it's about widgets being set. Not only lua.
I have one screen with this set
![image](https://user-images.githubusercontent.com/46420768/122044107-696a3780-cddc-11eb-9999-7d3617aa162b.jpeg)
None of them is LUA.
Once deleted Model name edit is fast.

**Comment by JimB40** [comment]
Checked again deleting one by one. It's ModelBmp widget that slows it down.

**Comment by pfeerick** [comment]
Oh, nice catch! I can repo that. It's a fluke I didn't repo it before, as I usually have ModelBmp enabled, but haven't set it up again for the models I'm testing on.

**Comment by raphaelcoeffic** [comment]
> Checked again deleting one by one. It's ModelBmp widget that slows it down.

Thx! This is something I can deal with. The refresh rate is probably way to fast!
