### ISSUE TITLE
Companion Simulator: Selecting Channels=>Failsafe button in the Failsafe Setting menu crashes W10 Companion, Simulator and radio

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2143]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion, Simulator, Firmware (#2162)

### Current Behavior

Selecting `Channels=>Failsafe` button in the Failsafe Settig menu crashes Companion.

### Expected Behavior

Companion not crashing, current Inputs are stored as failsafe values

### Steps To Reproduce

1. Open Companion and create new model
2. Open newly created model
3.  In the Setup tab select `Internal Radio`  `System Multi` and select `Multi Radio Protocol` `HoTT ` (alphabetically sorted list would be much nicer)
4. Click `Simulate`
5. In the simulated radio screen select `Model Setup` and click the `Internal RF button`
6. Scroll down to `Failsafe mode` and select `Custom` the click on the `Set` button
7. In the FAILSAFE SETTINGS (not all capitals would be nicer) screen click on the `Channels=>Failsafe` button
8. Observe Companion crashing

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Main branch - commit 18db00d8

~~I haven't checked radio firmware, fault might be present in firmware too.~~ Confirmed firmware too.

**Comment by mha1** [comment]
for radio see https://github.com/EdgeTX/edgetx/issues/2162

@elecpower @pfeerick can we take this out of triage please

**Comment by mha1** [comment]
@pfeerick Thank you

**Comment by pfeerick** [comment]
Since this fix didn't touch companion specific code, it won't be visible there until the next companion build is triggered.
