### ISSUE TITLE
FrSky X12S ISRM/ACCESS missing receiver number option

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2146]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There is no receiver number option in model setup with ISRM ACCESS.

### Expected Behavior

There should be a receiver number option when using ISRM ACCESS.

### Steps To Reproduce

With the internal module set to ISRM, go to model setup and choose ISRM ACCESS.

### Version

2.7.1

### Transmitter

FrSky X12

### Anything else?

This is present in both 2.7.1 official build and tonight's main nightly f31f06b3

Model setup in EdgeTX 2.7.1 official build:
![screen-2022-07-19-211837](https://user-images.githubusercontent.com/1323809/179897858-49d981b7-431a-47e1-8935-eb62b22ca70d.png)

Model setup in OpenTX 2.3.15:
![screen-2022-07-19-210408](https://user-images.githubusercontent.com/1323809/179897885-bcdfc5ae-bf1d-494e-a2ee-4a2df9f59d78.png)

**Comment by elekSENDER** [comment]
Same issue on a X10s (not express) with an upgrade-ISRM-module.
