### ISSUE TITLE
ExpressLRS telemetry on simulator

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#2156]
### Companion Simulator Telemetry
Now the expressLRS is more and more integrative in edgeTx,
is is very hard to debug lua script that support expressLRS 

### suggested solution

enhance the "telemetry" screen on the companion simulator with the elrs default telemetry
that will be easier to build and debug lua script that support expressLRS as well

add the following:
![image](https://user-images.githubusercontent.com/7026911/180605474-b63cb0f0-1077-497f-9612-86afe18e5523.png)

add them to here:
![image](https://user-images.githubusercontent.com/7026911/180605494-b9afa1d3-9958-4d24-8f47-a96b33b591d4.png)

**Comment by ggoraa** [comment]
This is a good suggestion! afaik this telemetry simulator was not updated in a long time, that's why it doesn't have a lot of fields

**Comment by rotorman** [comment]
https://edgetx.org/contest_crsf_telem_simulation/
