### ISSUE TITLE
Change USB screen to preserve radio battery

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#216]
Existing screen

![2021-06-14 20 33 47](https://user-images.githubusercontent.com/46420768/121944517-08e2e800-cd53-11eb-8c9a-182ccbc61273.jpg)

Proposed
![Frame 1](https://user-images.githubusercontent.com/46420768/121944631-23b55c80-cd53-11eb-8ea5-84ce90126f13.png)
![Group 13](https://user-images.githubusercontent.com/46420768/121944642-26b04d00-cd53-11eb-9932-b498044f19ec.png)

Don't know if OS is working while in USB mode. If so second screen provide possibility to check visually radio battery level
If it's possible to add text with USB mode selected it will provide visual error check (Why there is no disk mounted??? when pressed Joystick by mistake)

**Comment by raphaelcoeffic** [comment]
@JimB40 the icon is not bad, indeed! Do you have it separately?

**Comment by rotorman** [comment]
Love the proposed new logo - much more appropriate than the old one in a USB-stick form.
I would add text "USB" to make it clear.

**Comment by pfeerick** [comment]
I was going to suggest something similar when 2.4.0 was released, namely that the USB modes be more aligned with what the B&W radios can do... You can see the battery level, time, stick and switch widgets etc. 

I.e. in USB Storage mode you could just show an icon like with the joystick mode, and lock touchscreen input and buttons/roller so you can't go into menus.

**Comment by raphaelcoeffic** [comment]
Oh ok! For my part I thought this would be better for the mass forage mode, as you should believe you can use the menus of anything else while in that mode. For the 2 others, you can still use the radio normally.

**Comment by pfeerick** [comment]
Proposition 2 can be another 'thing' for 2.4.1... just keep the prettier icon for now, and probably dim the screen a bit...

**Comment by pfeerick** [comment]
@JimB40 Do you still have the source graphic for this and can it be freely used? Otherwise, this will be moved to 2.11.

**Comment by richardclli** [comment]
Well, changing the graphics cannot preserve the battery on a LCD display.  If you really want to preserve the battery, then you need to lower the brightness instead.

**Comment by pfeerick** [comment]
Indeed... as it is the backlight brightness that determines the power draw, not the content of the display. I was just focusing on the graphic though for this... if Robert still has it, great as it looks nicer, if not, close and move on.

**Comment by richardclli** [comment]
But power will be different if OLED display is used instead.  However, no color radio is using an OLED display right now.
