### ISSUE TITLE
Failsafe Error

### ISSUE THREAD

**Issue by tonims1** [EdgeTX/edgetx#2162]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

when you press channels = failsafe inside internal rf, set .always gives emergency mode
Latest nightly

### Expected Behavior

I would have to save the positions

### Steps To Reproduce

model settings ,internal RF ,failsafe mode .set. push channels = failsafe

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

https://user-images.githubusercontent.com/7953406/180949436-dbe365ab-dcff-47bb-838a-23f0b5a6a3e7.mp4

**Comment by mha1** [comment]
I reported this for companion/simulator with https://github.com/EdgeTX/edgetx/issues/2143 and suspected it would crash the radio too.
