### ISSUE TITLE
Irritating little display bug

### ISSUE THREAD

**Issue by MirlynG** [EdgeTX/edgetx#2164]
Upgraded to 2.7.1 on my TX16S (mk1). All good except for this irritating bug. 
When I tap the main model screen in the area of any of the widgets, instead of the menu options coming up, the widget gets highlighted with a dotted line like it does in the widgets editing page. Touching again does nothing.
On leaving it for about 5 seconds, the highlight flashes a few times and goes away. Touching again simply brings up the highlight again. Clicking the "return" button will remove the highlight at any point.
This behaviour only occurs if trying to use the touch screen in the widgets area. Touching the screen along the top (menu bar), or along the bottom or sides (trim and slider area) works fine and brings up the expected options.

The same thing occurs in the same way if I inadvertently scroll the jog dial, even just one click. However, if I now click the jog dial, I get the "Full Screen or Widget Settings" options dialogue. Touching either of these takes you to its respective screen. Again, hitting the return button will return you to the main screen but the highlight is still showing, but will then flash a few times and disappear as above. 
Not a major issue but really annoying.
Very grateful for help to resolve this.

**Comment by pfeerick** [comment]
Correct, it was deliberate to highlight that you were about to interact with a widget (and which one). However, that is not the case in how the UI was re-implemented for 2.8... the highlight is only shown for non-touch navigation (and you have to press and hold the roller/ENT for the "interactive" mode to be enabled there. For touch interaction you'll instead get the widget menu when you long press on it, without the dotted outline box showing up.
