### ISSUE TITLE
Add acoustic feedback for SYS/RTN/PAGE/TELE and MDL hard keys

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2194]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No problem and seems to be as is implemented in 2.7.1.

### Describe the solution you'd like

For consistency I propose to add acoustic/haptic feedback just like for the roller enter key, depending on radio setup Sound/Haptic settings "All".

**Comment by Eldenroot** [comment]
Good idea, why not

**Comment by mha1** [comment]
clesed with https://github.com/EdgeTX/edgetx/pull/2201 and https://github.com/EdgeTX/edgetx/pull/2193
