### ISSUE TITLE
TX12 MKII switch warning labels just show "S" instead of switch letter

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2202]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Switch warning settings on the transmitter just show "S" for all the switches.

### Expected Behavior

Should show B/C/E/F instead of "S".

### Steps To Reproduce

Go into model settings and look at the switch warning setup.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2

### Anything else?

Or maybe this is pulling it up in snake language instead of English?

Nightly c41de59

![screen-2022-08-11-203636](https://user-images.githubusercontent.com/1323809/184282033-a9593449-6c22-47f0-ba29-51bc2a869498.png)

**Comment by pfeerick** [comment]
Well, that's just being fussy :P What's wrong with them being 'S' and you having to guess which is which? 😆

**Comment by pfeerick** [comment]
That seems to have fixed it... looks like it was an overlooked LVGL/UTF-8 change... there's an extra character there now that mucks things up every now and then.
