### ISSUE TITLE
Use GV name if assigned instead of GVx 

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#2215]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If we edit a global variable GVx and give it a name: FLT then add that global variable as a widget using Value that global variable is displayed on the screen as GVx and not FLT. 

### Describe the solution you'd like

I believe if a user assigns a name to a GV, the name should be used throughout. We do the same thing with Curves. If we use no curve name, CVx is used. If we assign a name, that name is used throughout.

### Describe alternatives you've considered

Buying pfeerick a stack raffle tickets for EdgeTX Fest giveaways.

**Comment by pfeerick** [comment]
I'm afraid you'd probably have to do it in person, with a bunch of disguises and false names... given I'm part of the project my name won't be in the draw ;) 

Oh, interesting... the name *is* shown when it's a GV only list ...
![image](https://user-images.githubusercontent.com/5500713/185577604-f893d3b2-9c96-4d60-a27f-cc4bcd68b6fc.png)

... but not when it's a source list ... interesting, and not very consistent! 😆 
![image](https://user-images.githubusercontent.com/5500713/185578921-d7d0d2aa-6eda-4ff0-92ac-151a2bc3bd05.png)

**Comment by pfeerick** [comment]
This just seems to leave it so you need to see an un-named one before you realise they're the GVs...

![image](https://user-images.githubusercontent.com/5500713/185584712-eec00c82-9cec-4a1e-beed-f6fe29953deb.png)

**Comment by gagarinlg** [comment]
> I wonder if it would be better to show like with Companion in this instance... i.e so you know it's a GV...

This is what I would opt for, but is there enough screen space on the B&W radios?

**Comment by pfeerick** [comment]
Yeah, that's what I was thinking afterward, so am going to avoid that problem for now. 😆 On B&W they'll just have to continue to suffer with `GV#` as the UI there changes in place, rather than via a popup list.

**Comment by jmxp69** [comment]
> I'm afraid you'd probably have to do it in person, with a bunch of disguises and false names... given I'm part of the project my name won't be in the draw ;)

AWWW - I'll just have to find my kryptonite elsewhere I guess. 

> 
> Oh, interesting... the name _is_ shown when it's a GV only list ... ![image](https://user-images.githubusercontent.com/5500713/185577604-f893d3b2-9c96-4d60-a27f-cc4bcd68b6fc.png)
> 
> ... but not when it's a source list ... very interesting indeed, and not very consistent! 😆 ![image](https://user-images.githubusercontent.com/5500713/185578921-d7d0d2aa-6eda-4ff0-92ac-151a2bc3bd05.png)
> 
> Hm... this looks like where to fix it... and the nice thing is it should apply to B&W and Colorlcd radios if done there... I wonder if it would be better to show like with Companion in this instance... i.e so you know it's a GV...
> 
> ![image](https://user-images.githubusercontent.com/5500713/185581297-5a401628-4053-407f-98e9-e2940ee1fdde.png)
> 
> https://github.com/EdgeTX/edgetx/blob/6648dffc8c89d34fd26aba544e507d3cf3b20e47/radio/src/strhelpers.cpp#L677-L678

Why does your curve 2 and 3 have 4 characters hmmmm????? I saw that....

**Comment by gjhaynes** [comment]
Hi Peter, I don't mind if the user-defined name is prefixed with GV: when it appears in a drop down list, but would prefer to display only the user-defined name when it is used in a widget for example. At that point I don't need to know that the displayed value's source is a GV, I just want it to have a meaningful label. 
Cheers, Geoff.
