### ISSUE TITLE
R9M Power Level Auto Opt

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2238]
![16616026190214535478226564474575](https://user-images.githubusercontent.com/48190425/187029913-d27d7cdd-704d-4bc9-b7f0-849d30803e73.jpg)
![16616026586984914432484178707188](https://user-images.githubusercontent.com/48190425/187029933-8935b83f-d39b-46fd-bb4b-2ed4a344a748.jpg)
![16616027127426267552290425721742](https://user-images.githubusercontent.com/48190425/187029962-73567458-2e61-4a7e-a13f-a0642350c299.jpg)

Maybe one thing at least.
On opentx with flex firmware, (if I remember right) the Automatic Power Level was somehow declared? Can anyone check this? I just hear from the louder buzzing that the power regulation is active working.

And is that normal that I got telemetry lost/recovered when in the module firmware versions menu?

Ill test dual receiver configuration now.

_Originally posted by @brainbubblersbest in https://github.com/EdgeTX/edgetx/issues/2211#issuecomment-1229181726_

**Comment by brainbubblersbest** [comment]
Ok. A Friend checked that on his TX16S. 
![received_1202685183610496](https://user-images.githubusercontent.com/48190425/187070774-add3665d-7938-4289-99a3-cbd59d86642f.jpeg)

So it seems that
[10]
[100]
[500]
[1000(auto)]
Settings are related only to the old R9 with Accst.
That Frsky sh*t is still confusing in 2022.
Issue can be closed.
