### ISSUE TITLE
FlySky NV14 layout files

### ISSUE THREAD

**Issue by nightflasher** [EdgeTX/edgetx#2246]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

the screen layouts are mostly for widescreen radios, but the nv14 has a portrait screen, so the screen layout selectors are a bit misleading and can be some kind of disappointing. 

### Describe the solution you'd like

include portrait mode icons (made them already in 20x25px)
![mask_layout1+2](https://user-images.githubusercontent.com/3342605/187182234-3f5fd4fe-58e1-423d-8479-892b2504d453.png)
![mask_layout1+3](https://user-images.githubusercontent.com/3342605/187182257-615bc5f9-28b2-4bb6-a041-23482765151f.png)
![mask_layout1x1](https://user-images.githubusercontent.com/3342605/187182264-4ac79e0b-0b09-4bca-a702-84a61d243a04.png)
![mask_layout1x2](https://user-images.githubusercontent.com/3342605/187182266-3cd6388e-001d-4d47-94be-05c764f778b8.png)
![mask_layout1x3](https://user-images.githubusercontent.com/3342605/187182268-65c3de6c-0747-4a20-8e69-bebcaa04cbba.png)
![mask_layout1x4](https://user-images.githubusercontent.com/3342605/187182270-5995d115-5f9d-4ab9-8b03-43169272c32b.png)
![mask_layout2+1](https://user-images.githubusercontent.com/3342605/187182273-e6ed9f29-fade-4ef3-bc52-56cc6f997864.png)
![mask_layout2+3](https://user-images.githubusercontent.com/3342605/187182275-a50c4e90-3671-499b-abe2-f77aec62ef62.png)
![mask_layout2x1](https://user-images.githubusercontent.com/3342605/187182277-641da352-6833-4ff1-b28d-6eb0604c4226.png)
![mask_layout2x2](https://user-images.githubusercontent.com/3342605/187182279-7539dd8c-28dd-44a5-bea0-3983b5d2cac4.png)
![mask_layout2x3](https://user-images.githubusercontent.com/3342605/187182281-03a66867-b21c-44ef-bea0-3a212625ce5e.png)
![mask_layout2x4](https://user-images.githubusercontent.com/3342605/187182283-9da4216a-ff27-42d8-9082-2eecd4e3f168.png)
![mask_layout4+2](https://user-images.githubusercontent.com/3342605/187182286-c17e1b67-aab4-4e56-8d62-b8ad86d5d8e2.png)

**Comment by raphaelcoeffic** [comment]
I believe these should be computed rather than included as fixed bitmaps. Should would allow for more flexibility. In general, it seems to me that the screen layouts for NV14 are not very well adapted in general. This is something we should revisit probably.

**Comment by richardclli** [comment]
Seems this is related to https://github.com/EdgeTX/edgetx/pull/3282
Is this PR solves the problem properly? @nightflasher

**Comment by nightflasher** [comment]
![IMG_20230322_082209_589](https://user-images.githubusercontent.com/3342605/226830027-682a32bd-86b0-4fcc-87a0-d81c34e5e9a9.jpg)
No, it doesn't work. It's only a ratio thing.

**Comment by philmoz** [comment]
> No, it doesn't work. It's only a aspect ratio thing.

Are you sure you tested the right build?
It should look like this on the NV14:
![Screen Shot 2023-03-22 at 7 56 02 pm](https://user-images.githubusercontent.com/9474356/226851530-3ba5253b-3f8a-4412-8289-f5aa54a4a7ea.png)

**Comment by nightflasher** [comment]
EdgeTX 2.8.1 - which one should it be? Also, my NV14 still identifies itself as EL18

**Comment by pfeerick** [comment]
main branch, so a nightly. Or wait for 2.9 ;)

**Comment by pfeerick** [comment]
Resolved by https://github.com/EdgeTX/edgetx/pull/3282

**Comment by nightflasher** [comment]
oh okay - there is no nightly for the NIRVANA :'(

**Comment by pfeerick** [comment]
On Buddy, you'll be after the Flysky EL18 - make sure you've ticked off show pre-releases under filters if you want to see nightlies. 

![image](https://user-images.githubusercontent.com/5500713/227067207-7d3b3251-f6a6-4cc2-8870-e69a92c0534f.png)

The firmware is identical for the EL18 and NV14, it auto-detects which hardware it is on at runtime, and makes some adjustments accordingly. Only gotcha is the firmware will in some places state it is the el18 (i.e. because that is the firmware file that was flashed, not the radio model that is being displayed).
