### ISSUE TITLE
No simulation on Companion

### ISSUE THREAD

**Issue by Billy60** [EdgeTX/edgetx#2247]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Companion (latest) opens but the simulator feature is not active. The Outputs are non active.
The TX works fine for the rest.

### Expected Behavior

Normally, the Outputs are simulated as on the Tx. They move with the sticks and according to mixes.

### Steps To Reproduce

Open companion, load a model, midify the ùmodel and try to simulate. Nothing happens.

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
I can't reproduce this. With Companion 2.7.1 on Windows (11), if I load a ETX file for TX16S (or create a new one with a un-customised model), and then simulate it, both mixes and outputs are working in the radio outputs window.
