### ISSUE TITLE
Custom switch names not displayed

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#225]
I think it was done & closed once?

![Screen Shot 2021-06-16 at 14 18 26](https://user-images.githubusercontent.com/46420768/122217472-bd911c80-cead-11eb-8bd0-9b248d28828b.png)
 

**General information**
- EdgeTX 2.4 RC1
- RM TX16S

**Comment by raphaelcoeffic** [comment]
@JimB40 I found some more rests of the old ZCHAR.... Scanning the code, it seems now to be gone for good.

**Comment by JimB40** [comment]
ZCHAR seems to be reclutant to be wiped off 😂

**Comment by raphaelcoeffic** [comment]
@JimB40 a bit like zombies, or something like that....
