### ISSUE TITLE
Trainer(Jack) Malfunction after 2.7.0

### ISSUE THREAD

**Issue by mrzhima** [EdgeTX/edgetx#2252]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Trainer through 3.5mm Jack, both Master and Slave, won't work after 2.7.0 (also 2.7.1 and nightly 20220830). Master/BT works fine. If roll back to 2.6.0, it would work fine.

### Expected Behavior

Transmitter can send/recieve trainer control signal to/from another radio or arduino based headtracker.

### Steps To Reproduce

1. Update to 2.7.0 or later firmware
2. Set trainer function to Master Jack or Slave Jack
3. Set trainer function of another edgetx radio to Slave Jack or Master Jack
4. Connect to another edgetx radio using 3.5mm audio cable
5. Trainer function won't work

### Version

2.7.1

### Transmitter

FrSky X9 Lite / Lite S

**Comment by gagarinlg** [comment]
Can anyone confirm for 2.8 or the current nightlies?
