### ISSUE TITLE
Corrupted custom splash screen

### ISSUE THREAD

**Issue by ZZ-Cat** [EdgeTX/edgetx#2261]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On startup, the splash screen is corrupted & appears to be dominated by "red-scale" (like grayscale, but instead of black-&-white, it's red-&-white).

I have included photos of my custom splash screen, plus four variants that I have created specifically to test this issue.
Fair warning: I couldn't get proper screencaps of the splash screen itself. So, "old fashioned screenshots" it is. 

![20220902_110820](https://user-images.githubusercontent.com/48301275/188036408-21754158-e3e6-4ba6-9d57-543ec554bfe0.jpg)
**Above:** This is how my custom splash screen currently appears.

**Below:** I created these variations of my splash screen specifically to test this issue & they all appear similar to my splash screen above.
![20220902_110952](https://user-images.githubusercontent.com/48301275/188036424-cf01329e-f174-4f76-86fb-ef71090703e6.jpg)
![20220902_111120](https://user-images.githubusercontent.com/48301275/188036428-c81d1d2d-8c9a-4c5d-a68f-d4de15ab855b.jpg)
![20220902_111239](https://user-images.githubusercontent.com/48301275/188036434-bfda3f5f-353c-467a-b388-d9f786b611d4.jpg)
![20220902_111418](https://user-images.githubusercontent.com/48301275/188036439-4d72a756-5c81-4ac9-9d39-ba59e4dc0906.jpg)

### Expected Behavior

Literally this...
![20220902_115623](https://user-images.githubusercontent.com/48301275/188038460-069d9fca-9b4d-41d2-afed-3c46c7efd490.jpg)
**Above:** This is how my splash screen *should* be displayed.

**Below:** The same four variants of my splash screen, but this is how thar supposed to appear.
![20220902_115743](https://user-images.githubusercontent.com/48301275/188038480-a29854b3-626b-4404-a4fd-1f7d80d83286.jpg)
![20220902_115905](https://user-images.githubusercontent.com/48301275/188038497-bc564099-045f-4710-885f-aedbc2b9c167.jpg)
![20220902_120028](https://user-images.githubusercontent.com/48301275/188038508-2116dc62-90dc-4393-800a-47840fae865e.jpg)
![20220902_120144](https://user-images.githubusercontent.com/48301275/188038514-07634179-2e29-4860-bbb7-06601eaf8c2f.jpg)

#### Preparation:
If you're already using a custom splash screen, start from step 4 & go straight to testing.
1. Grab one of the custom splash screens that I have provided under "Resources for Testing".
2. Name your custom splash screen "splash".
3. Copy your splash screen over to the ```IMAGES``` folder in your uSD Card's directory.
4. Flash your controller with any nightly build from 5d399b0 (June 13, 2022) onward.

#### Testing:
1. Power up your controller.
2. ?
3. Blazing red splash screen!

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

#### Resources for Testing:
Here are a couple of example custom splash screens for testing this issue. These aren't necessary for you, if you're already using a custom splash screen.
![splash_1_9-02-2022](https://user-images.githubusercontent.com/48301275/188040265-ee38e8c1-2612-4a54-89a3-17a6b6cee953.png)
![splash_3_9-02-2022](https://user-images.githubusercontent.com/48301275/188039838-ff9cb077-8107-4144-9944-75e1ef6b4d79.png)

#### Extras:
- The default splash screen is unaffected by this bug.
- This is another bug that has persisted since the user interface rewrite.
- This bug is present in every nighly build, since 5d399b0 from June 13, 2022 up to the latest nightly build.
- The last known nightly where this bug is not present is 33845b9 from June 6, 2022.

#### The bit on the side (miscellaneous trivia):
- The "blued-out" controller is a heavily color-graded photograph of my RadioMaster TX16S Max Edition (before I upgraded the gimbals).
- The custom splash screen that I'm currently using features an old concept logo that was suggested around about the time that the current EdgeTX logo was being designed. I liked the look of it, & it stuck ever since. =^/.~=

**Comment by raphaelcoeffic** [comment]
Looks like this is caused by the LVGL image loader… at least the date you mention is suspicious in that regard.

**Comment by pfeerick** [comment]
This sounds like the same issue that was being discussed [off topic in another PR](https://github.com/EdgeTX/edgetx/pull/2100#issuecomment-1209961108) - in that case if you re-saved the logo, but as 24 bit color (rather than 32bit) this issue went away. And it's not like you'd have any chance of seeing that color difference anyway with these screens...

**Comment by raphaelcoeffic** [comment]
The broader question is probably: can we come up with some code mods that would effect proper color mapping?

**Comment by ZZ-Cat** [comment]
> This sounds like the same issue that was being discussed [off topic in another PR](https://github.com/EdgeTX/edgetx/pull/2100#issuecomment-1209961108) - in that case if you re-saved the logo, but as 24 bit color (rather than 32bit) this issue went away. And it's not like you'd have any chance of seeing that color difference anyway with these screens...
> 
> 

=O/,..,O=
I just tried a 24-bit version of my splash screen & that worked. It shows up properly (not even the color banding, that I previously had, either).
Heh. The more ya know.

It seems weird that 32-bit depth images for the splash screen become corrupted like that, when they had previously worked with the old layout.

But, hey. Physically, I don't see any differences (that are significant enough to care about) between 32-bit or 24-bit on my RadioMaster's display panel, anyways. So, I'm happy to roll with 24-bit.

**Comment by raphaelcoeffic** [comment]
> It seems weird that 32-bit depth images for the splash screen become corrupted like that, when they had previously worked with the old layout.

It's not the same PNG loader code that is used.

**Comment by gagarinlg** [comment]
> The broader question is probably: can we come up with some code mods that would effect proper color mapping?

I think the message from the PNG lib people was something like: less code, less compatibility, less complexity instead of a full blown 100% compatible, but very complex parser.
I never did PNG, so I have no idea how complex it would be to add more compatibility



> But, hey. Physically, I don't see any differences (that are significant enough to care about) between 32-bit or 24-bit on my RadioMaster's display panel, anyways. So, I'm happy to roll with 24-bit.

The display has a 16 bit interface.
