### ISSUE TITLE
some model functions still causing problems in LUA due to conversion issues T16

### ISSUE THREAD

**Issue by lshems** [EdgeTX/edgetx#227]
Just loaded the preleased and I'm impressed (8cc5e77).

I'm still struggling to find my resources and info though.
My scripts run mostly fine, except for those using a lot of model functions. I cannot really debug, since I have to load the code on the radio and have no LUA debug window there. 

So is there a way to debug lua scripts?
Secondly, where do I find the info on how to use the keys in a full screen widget? or is it not added yet? That would help debugging also, since I can then at least use the widgets interactively and add some error catching perhaps in lua itself.

Thanks again for all effort.

**Comment by raphaelcoeffic** [comment]
@lshems may I help you with something? The easiest for me so far has been to use the standalone simulator called „simu” in a terminal. Please PM me on discord in case you need to give me some code to test and check.

**Comment by lshems** [comment]
Code checking is really difficult for someone else. Its 400+ files of lua. 
I created an entire library of stuff to make things easy. I don't have an issue with sharing, but it's really not helpful. I am willing to put my own effort in, and I have the simu running on windows all the time for opentx. But where to find it for Edge?

Discussion on discord then? I can create a wiki page on how to do things once I figured it all out.

**Comment by pfeerick** [comment]
Simu on windows is probably going to be a pain since we can't currently build companion24, simulator24 or simu on Windows... so your best bet at present is to build and run `simu` on Linux. You can build it on WSL2, but then the inability to easily run GUI stuff gets you ... although that *may* be resolved in the next week or after the June 24 Windows announcement, since among other things, the X11 GUI stuff  - WSLg "is going to be generally available alongside the upcoming release of Windows" ... 

It is entirely possible though, although like pulling teeth, to run simu right now on Windows via WSL2... 
Follow [these instructions](https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3) to get the X11 server up and running. It's up to you if you make it so stuff runs as startup, or if you just create the vcxsrv shortcut, and vbs file, and then just run them manually when you want the GUI. 

Build and make the simulator - it's the `simu` target, rather than the `firmware target`... I use the docker build environment, so for me it's something like (when the present working directory is the root of the edgetx repo):
```
docker run -it --rm -v $(pwd):/src ghcr.io/edgetx/edgetx-dev bash
cd /src/build (mkdir /src/build and cd /src/build if it's missing) 
cmake -DPCB=X10 -DPCBREV=TX16S -DLUA=YES -DCMAKE_BUILD_TYPE=Release ..
make -j4 simu
exit
./simu
```

You'll probably run into the libfox shared library error, so run `sudo apt install libfox-1.6-0` to fix that. 

![image](https://user-images.githubusercontent.com/5500713/122311582-dead4800-cf55-11eb-8816-e7a082440cbb.png)

**Comment by raphaelcoeffic** [comment]
@lshems you might be interested in re-testing with a newer version, as there are some fixes in d10563d08b2 concerning the labels used in such model functions.

**Comment by lshems** [comment]
Yeah, saw that. Nice. Will do.

Op do 17 jun. 2021 08:43 schreef Raphael Coeffic ***@***.***>:

**Comment by lshems** [comment]
OK, no big improvements after the update. Im writing a small menu page to show all possible key-values for all possible screen objects (inputs, mixers, outputs, LS, SF I have up and running on the sim in OpenTX, just find the time to test on the radio.)
![screenshot_x10_21-06-17_12-44-06](https://user-images.githubusercontent.com/12395806/122381982-bc252a00-cf69-11eb-8382-7583f32e25ec.png)

**Comment by lshems** [comment]
> Simu on windows is probably going to be a pain since we can't currently build companion24, simulator24 or simu on Windows... so your best bet at present is to build and run `simu` on Linux. You can build it on WSL2, but then the inability to easily run GUI stuff gets you ... although that _may_ be resolved in the next week or so after the June 24 Windows announcement, since among other things, the X11 GUI stuff - WSLg "is going to be generally available alongside the upcoming release of Windows" ...
> 
> It is entirely possible though, although like pulling teeth, to run simu right now on Windows via WSL2...
> Follow [these instructions](https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3) to get the X11 server up and running. It's up to you if you make it so stuff runs as startup, or if you just create the vcxsrv shortcut, and vbs file, and then just run them manually when you want the GUI.
> 
> Build and make the simulator - it's the `simu` target, rather than the `firmware target`... I use the docker build environment, so for me it's something like (when the present working directory is the root of the edgetx repo):
> 
> ```
> docker run -it --rm -v $(pwd):/src ghcr.io/edgetx/edgetx-dev bash
> cd /src/build (mkdir /src/build and cd /src/build if it's missing) 
> cmake -DPCB=X10 -DPCBREV=TX16S -DLUA=YES -DCMAKE_BUILD_TYPE=Release ..
> make -j4 simu
> exit
> ./simu
> ```
> 
> You'll probably run into the libfox shared library error, so run `sudo apt install libfox-1.6-0` to fix that.
> 
> ![image](https://user-images.githubusercontent.com/5500713/122311582-dead4800-cf55-11eb-8816-e7a082440cbb.png)

OK, going that route now. But can someone share perhaps a precompiled simu, as it would save me the complexity to test the WSL2 also for compiling

**Comment by raphaelcoeffic** [comment]
> OK, no big improvements after the update. Im writing a small menu page to show all possible key-values for all possible screen objects (inputs, mixers, outputs, LS, SF I have up and running on the sim in OpenTX, just find the time to test on the radio.)
> ![screenshot_x10_21-06-17_12-44-06](https://user-images.githubusercontent.com/12395806/122381982-bc252a00-cf69-11eb-8382-7583f32e25ec.png)

If you provide your test script, I can have a look what   Is not working properly.

**Comment by lshems** [comment]
OK, fianlly got a working simu with lua debug. now I can work again :).

First issue: on inputs, the name attribute is empty. This causes my scripts to crash because I look for inputs with a certain name. the InputName is populated, but name is not.
![image](https://user-images.githubusercontent.com/12395806/122482927-c975ff00-cfd1-11eb-98ca-ce5ffbac0472.png)

**Comment by lshems** [comment]
It seems a conversion issue, as I can populate it myself:
![image](https://user-images.githubusercontent.com/12395806/122483149-3ab5b200-cfd2-11eb-8e5e-6e41d05f0f71.png)
![image](https://user-images.githubusercontent.com/12395806/122483191-53be6300-cfd2-11eb-9e51-c650c99d6a0a.png)
![image](https://user-images.githubusercontent.com/12395806/122483233-6a64ba00-cfd2-11eb-9f22-c8e834940e1a.png)

**Comment by lshems** [comment]
Perhaps the other errors are also caused by conversion issues. I'll check, and will change the titel?

**Comment by lshems** [comment]
Also, this means that the long standing bug is fixed, with no access to the inputname and line name as seperate parameters on inputs from LUA.

Nice

**Comment by lshems** [comment]
I will close this issue, and create clean issues for what results from further testing.

So I will create a new issue for the input line names not being converted properly.
