### ISSUE TITLE
Editing Widgets can trigger Emergency Mode

### ISSUE THREAD

**Issue by CarlKnox** [EdgeTX/edgetx#2276]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Pressing TELE while editing Widget setting brings up new widget selector. Changing widget results in Emergency Mode when backing out.
Doesn't seem to cause a problem if you backout and don't change widget.

### Expected Behavior

Disallow TELE when configuring widget settings.

### Steps To Reproduce

1. Press TELE
2.  Add main view
3. Layout Fullscreen
4. Setup widgets
5. Touch screen
6. Select widget
7. Select Gauge
8. Widget settings (don't close)
9. Press TELE
10. Setup widgets
11.  Touch screen
12.  Select widget
13.  Select Models
14.  RTN RTN RTN RTN ... (lost count)
15.  See error

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

2.8.0-nightly (ba814db3)
Sept 4, 2022

**Comment by pfeerick** [comment]
Fixed by #2354 as TELE no longer works while widget settings dialog is shown. Thanks! :)
