### ISSUE TITLE
Popup list filters need more work

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#228]
For want of a better word, the category/filter icons that appear on the side of lists ... 

![image](https://user-images.githubusercontent.com/5500713/122314517-aa3c8a80-cf5b-11eb-938e-4f137f7dd6f7.png)

... can make it so you can't see all the list, i.e. if you press the top one for switches, it will only show the 'positive' switch states, not any of the not states, and the second one will only show the sticks... so if you use either filter, you loose access to the not switch states, 'Tele' and 'Act' etc in this examble. Another is if you were in the global functions screen, if you hit one of the filter icons, you can't get at the ON state unless you close and reopen the list - as is see here... => https://youtu.be/Y9OvW9XCjOs?t=1440

Perhaps at minimum an 'all' option is needed so you can always get the full unfiltered list back?

**Comment by pfeerick** [comment]
Another suggestion was that the GVs, LSs and a Misc or something for things like Batt, and Timers

**Comment by JimB40** [comment]
Partially done in https://github.com/EdgeTX/edgetx/pull/2435

**Comment by JimB40** [comment]
- [ ] Reaarange sources' filter icons in two columns so in horizontal layout icons scrolling is not needed.
- [ ] Add top bar with variable name for clarity what is actually changed
- [ ] Add close button on topbar for UI clarity (tapping ouside the the list still works)

**Comment by pfeerick** [comment]
Negative. the changes in #2435 don't relate to this issue, and it's a close issues anyway ;)

**Comment by Eldenroot** [comment]
It is always frustrating to scroll over all items... nightmare, I hope it will be improved in 2.9 somehow :) some QoL improvements are welcomed!
