### ISSUE TITLE
Model labels with commas malformed against models

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#2282]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion and Radio firmware

### Current Behavior

![screenshot_tx16s_22-09-06_23-20-50](https://user-images.githubusercontent.com/15316949/188646415-69473157-e6ea-4ef0-8ae4-c618b47ac28b.png)
![Screenshot from 2022-09-06 23-11-55](https://user-images.githubusercontent.com/15316949/188644366-c026c968-ac17-4898-9ef4-97084a78f63d.png)

Same for Win 10 and Ubuntu 20.04

### Expected Behavior

Model labels match list

### Steps To Reproduce

1. Create new model file
2. Create new model
3. Amend Favorites to x,x

4. Select model
5. Select x,x label

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

Commit [58a6239a](https://github.com/EdgeTX/edgetx/commit/58a6239a)

**Comment by dlktdr** [comment]
I'll get it to show the extra comma, it's showing the escaped commas CSV line what would be seen in the yml file.
