### ISSUE TITLE
Inputs Source selection - Key presses being ignored

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2286]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I see this with both my TX16S and FrSky X12.

When editing/adding an Input, if you try to pick a source without using a touchscreen, key presses can get ignored.

### Expected Behavior

Key presses should react instantly.

### Steps To Reproduce

Go to Inputs, add a new or edit an existing input, and try selecting a source without using the touchscreen.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12, Radiomaster TX16S

### Anything else?

It was actually much worse when I wasn't trying to record it:

https://www.youtube.com/watch?v=Qcl3qk2bVow

**Comment by eshifri** [comment]
ChoiceEx class is using openUI events rather than lvgl events.
Can it be the problem?
