### ISSUE TITLE
Touchscreen sometimes becomes completely unresponsive 

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#229]
Just documenting this as I've had it happen a couple times as well - no repeatable reason as yet - but it did always 'seem' to be when in model settings. Only solution was to power cycle radio. 

https://youtu.be/Y9OvW9XCjOs?t=1753

**Comment by raphaelcoeffic** [comment]
@pfeerick this is going to be a rough one.... we need to find some way to trigger it, so I can check what's happening.

**Comment by pfeerick** [comment]
Exactly... it happens every now and then, just enough to remind you it can do it, not enough to actually start pinning down the commonality. I don't see it being a **big** issue since touch is only complementary to the button interface, there's nothing it alone allows you to access AFAIK. It's just a matter of finding out where it's getting stuck ;)

**Comment by phileville** [comment]
I also had this happen yesterday - also when I was on the model configuration screen - but I could not recreate it again and it only happened once.  Another user from FB also mentioned it. I asked him for more information.

**Comment by raphaelcoeffic** [comment]
> Just documenting this as I've had it happen a couple times as well - no repeatable reason as yet - but it did always 'seem' to be when in model settings. Only solution was to power cycle radio.
> 
> https://youtu.be/Y9OvW9XCjOs?t=1753

Did you use any of the screen settings during the same session? Anything with exchanging a widget, selecting a model with Toolbar widgets?
