### ISSUE TITLE
Certain FS2A (AFHDS 2A) receivers not binding

### ISSUE THREAD

**Issue by cmlarsen** [EdgeTX/edgetx#2291]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have bound my transmitter with many FS2A receivers in the past - usually getting them from sellers on Ali Express - and all has been fine.
However, the most recent batch I got has a different MCU than past chips and will not bind with my Radiomaster Zorro Multi-protocol.  Friends who also got a batch of FS2As with the large chip (from a different Ali Express seller) have _also_ not been able to bind to them with their Zorros and Jumper T-Lites.  However, we have all been able to bind to the suspect FS2As with  Turnigy Evolutions and Flysky FS-i6X.

Normally I'd say this is an issue with the receivers, however since I am able to bind them as expected with a Turnigy or Flysky radio and _unable_ to bind to them from several different OpenTX/EdgeTX, it makes me think there is something in the way binding is supported in OpenTx/EdgeTX.

The FSA2s that will bind are on the right (small chips) and the ones that will not bind on an OpenTX/EdgeTx Mulit protocol radio are on the left (big chips).
![20220905_140632](https://user-images.githubusercontent.com/4974259/188901355-3a476cc6-d6f5-4949-91ed-a7c984c95cde.jpg)

### Expected Behavior

The FS2A receiver _should_ bind with the EdgeTx radio.

### Steps To Reproduce

Attempt to bind to the FS2A receiver:
1) Enable Internal RX, Mode Multi
2) Select Type 'FlSky2A'  (other Flysky types don't work either)
3) Enter bind mode
4) Power on RX while holding down bind button
5) See fast flashing light
6) Exit bind mode on the transmitter
7) EXPECT to see solid light on FS2A (as is usual with _other_ FS2As)
8) ACTUALLY see RX is still in bind mode. 

Repeat the same process except with a Turnigy Evolution and the bind process is successful. 

### Version

2.6.0

### Transmitter

Radiomaster Zorro

### Anything else?
Other firmware we've seen the issue on: opentx-tpro-2.3.14, opentx-tlite-2.3.11

Edit: fix typo, add additional firmwares

**Comment by pfeerick** [comment]
Ok, so the real question that needs answering here is - have you tried this with a MultiProtocol Module - as I am more inclined to think if there is a bind issue, the issue with the [MultiProtocol Module firmware](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module), since OpenTX/EdgeTX do not control the RF side - this is all managed by the MPM. That would also mean it might be worth checking what version of the MPM firmware you are running... 1.3.3.14 is the current... just in case there was a fix there in relation to Flysky AFHDS2A - there have been some minor fixes over the last year or so. 

They look like a handy small receiver to have, and I am partial to Flysky gear atm... is this the same seller? https://www.aliexpress.com/item/1005004326228779.html

**Comment by cmlarsen** [comment]
@pfeerick Yep, that is the seller. However the RX from this seller (as of Feb 2022) haven't had any issues: https://www.aliexpress.com/item/2255800925784345.html

I don't have an external MPM to test with - but I could send you one if you have one you'd like test.

**Comment by pfeerick** [comment]
I was about to say it would possibly be better to find out if Pascal from MPM knows anything about this, but I just spotted someone else asking about it ... https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/730 ... so I think we should both watch and wait ;)

**Comment by pascallanger** [comment]
@cmlarsen Could you send me one of these RXs which don't bind? From there I'll try to see where the bind process fails.

**Comment by cmlarsen** [comment]
@pascallanger happily. Let me know the best way to get it to you.

**Comment by pascallanger** [comment]
You can contact me by PM on rcgroups username hpnuts. If you don't have an account there, use the email account used for the donation on my github page.

**Comment by cmlarsen** [comment]
@pascallanger PM sent via rcgroups.

**Comment by pascallanger** [comment]
Replied by email as suggested

**Comment by pfeerick** [comment]
I'm closing this issue, but will continue to follow it over on the MPM side, since I'm pretty sure this is a MPM / RX issue. I also have some information to add to this issue so will add an upate over there.

**Comment by lleduc53** [comment]
I use EdgeTX 2..8.1 and had the same issue as pfeerick but found out that the binding works if choosing Flysky AFHDS 2A with sub type PWM and IBUS. Do not use the other entry "Flysky AFHDS 2A RX". This one doesn't work. So confusing ! Hope that this will help someone looking for an answer.

**Comment by gagarinlg** [comment]
The "RX" protocols are used to have the MPM as a receiver, so that you can make a wireless buddy box setup.

**Comment by pfeerick** [comment]
Yes. btw, this was a different issue... newer clone 4CH RXs are coming out with some slightly different firmware on them, and the MPM needed an update to take that into account. The fix is present as of https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/commit/5148449066ce87b0093f99c38e64c1d477a240ed but you need to run nightly firmware to use that at present as there hasn't been an updated release of the MPM firmware since that change was made. 

As gagarinlg said, RX protocols are for using the MPM as a receiver (ostensibly for wireless trainer, but really you could use it for anything) - DSM (Spektrum), Frsky, Flysky AFHSD2A and Bayang.

**Comment by TomTech2004** [comment]
Hello
Can someone tell me what pins of the processor the channels are connected to?
Thanks

**Comment by Jesman27** [comment]
FS2A 4CH rompe mis servos.
Lo tengo trabajando en AFHDS-2A.
Alguien me puede ayudar?

**Comment by lleduc53** [comment]
No problem now with this cheap but really good AFHDS 2A receiver. Il binds
well and permits fail safe (motor cut) by holding the bind button for some
seconds

**Comment by Jesman27** [comment]
Gracias por tu respuesta. El proceso de BIND lo realizo bien, pero en los 4 Receptores que he comprado me ocurre lo mismo, al cabo de unos instantes de prueba con ellos  los servosdejan de funcionar. En algunos de ellos veo como se prende fuego por la parte de abajo. Llevo unos 10 en total quemados.  No sé que más probar.
Saludos.

**Comment by pfeerick** [comment]
Bottom part of the servo? That sounds like perhaps a fault with the servos,
not the receivers... Receiver only gives the 5v power from the  ESC/BEC and
signal to tell servo how much to move... Nothing that should make a servo
burn.

**Comment by Jesman27** [comment]
Bueno, creo que he encontrado el problema.
He probado con un nuevo ESC, y he vuelto a romper otros dos servos. Pero los he colocado en un probador de servos y me he dado cuenta que uno de ellos funcionaba más o menos normal hasta llegar a un extremo y allí parecía volverse loco. He recordado que todos se estropeaban al llegar a uno de los extremos de la palanca de mi radio Flysky. Por lo que he tocado los valores de END POINTS en el menú SETTINGS a un valor del 95% ( en lugar del 100% que está por defecto).
He probado con dos servos nuevos y parece que todo funciona bien ahora.
 Deduzco que es un fallo del firmware actual del receptor FS2A-4CH, que le obliga a adoptar una posición demasiado forzada en los extremos del recorrido de los engranajes del servo y provocando una averia eléctrica de algún componente de su placa.
Espero que sirva a alguien con el mismo problema. A mi me ha costado romper 12 servos y comprar 4 receptores que se han comportado todos de la misma manera.
A ver si puedo seguir sin sobresaltos con mi montaje. Saludos.
