### ISSUE TITLE
Panel mirroring option does nothing (immediately)

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#230]
The Mirror option under Screen Settings -> Main view appears to do nothing. Expected behaviour was that it would mirror the layout. 

![image](https://user-images.githubusercontent.com/5500713/122315892-42d40a00-cf5e-11eb-9d70-f78d47322568.png)

Seen in this video https://youtu.be/Y9OvW9XCjOs?t=2721 and reproduced locally on TX16S and on simu.

**Comment by JimB40** [comment]
It is mirroring. Still widget visual output stay at the same UI place until you edit it.

**Comment by pfeerick** [comment]
Or until you power the radio off... I just saw it had applied on a power cycle. So in other words, unlike all the other checkboxes on that screen, that one does not apply 'immediately'. So you can either power cycle the radio, or bring up the widget settings to get it to refresh the layout mirroring setting.

**Comment by raphaelcoeffic** [comment]
> Or [stays the same] until you power the radio off... I just saw it had applied on a power cycle. So in other words, unlike all the other checkboxes on that screen, that one does not apply 'immediately'. So you can either power cycle the radio, or bring up the widget settings to get it to refresh the layout mirroring setting.

Thx, no problem, that should be easy to fix.
