### ISSUE TITLE
Buttons look different for Model Setup and 

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2304]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion Simulator

### Current Behavior

Button in Radio Setup with Background:
![image](https://user-images.githubusercontent.com/5615068/189514977-1064dbc7-1b09-422d-b826-26195ee7df83.png)

Same button type in Radio Settings e.g. TOOLS and RADIO SETUP without background:
![image](https://user-images.githubusercontent.com/5615068/189514992-e37f3576-2fc3-41d9-950b-f4937bf2325f.png)
![image](https://user-images.githubusercontent.com/5615068/189515041-b0a840d8-bdf7-4159-94e6-0f24d92f2710.png)

### Expected Behavior

consistent graphical represantation

### Steps To Reproduce

Browse through menus

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
Ah, good point... looks like they are using different colors - can actually see it side by side here with the labels button ;)

![image](https://user-images.githubusercontent.com/5500713/189555593-1350fe76-fa3c-436a-a26d-da0aa0e0af8b.png)
![image](https://user-images.githubusercontent.com/5500713/189555605-01f3c99f-2a2b-4515-b675-5d88c7a32568.png)

**Comment by pfeerick** [comment]
I suspect the top three "model setup" buttons were done that way to signify active/inactive, but not sure about all the other buttons.

**Comment by mha1** [comment]
comparing for example the Internal RF button with the Betaflight setup button in your screen shots I'd say they use different background colors. Same conclusion when looking at my screen shots.

**Comment by eshifri** [comment]
Buttons on the setup screen are based on lvgl button; on the tool screen -  lvgl label. (openUI Button and TextButton).

**Comment by mha1** [comment]
> Buttons on the setup screen are based on lvgl button; on the tool screen - lvgl label. (openUI Button and TextButton).

Hi, what does that mean in terms of a solution?

**Comment by eshifri** [comment]
I do not know, to be honest. :-)
Just a hint to somebody who implemented it.

**Comment by raphaelcoeffic** [comment]
These are basically 2 kinds of buttons:
- those that can have 2 states (i.e. status indicator; internal module, trainer, etc...)
- those that have only 1 state (simple push buttons)

If everyone agrees the second type should have the same color as the first in "unactivated state", then let's do it this way.

**Comment by pfeerick** [comment]
Well, it's three of the everyone *present*, since he suggested it :-P

**Comment by gagarinlg** [comment]
Four 😉
