### ISSUE TITLE
Switch invert on long press does not work when using buttons

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#2312]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Long press on the switch button in LS edit and other screens has no effect.

### Expected Behavior

Long press on switch should set it to !Switch.

### Steps To Reproduce

1. Create new LS.
2. For input select SA_UP.
3. Select this input and Long press ENTER.
4. The menu will open with SA_UP selected instead of !SA_UP.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

I think the problem is ChoiceEx implementation was not converted to lvgl.

**Comment by raphaelcoeffic** [comment]
@eshifri `ENTER` long press needs to be handled differently indeed.
