### ISSUE TITLE
Module / RX version pop up doesn't look nice

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2320]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

"Multimodule" shouldn't be wrapped like that.

![image](https://user-images.githubusercontent.com/5615068/190450833-b1ae8d08-101a-4f28-a9d5-c8acb5f4aaeb.png)

### Expected Behavior

no breaking words

### Steps To Reproduce

select Radio Settings, Version, Models / RX version

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

### Anything else?

build 9fbf0b7b

**Comment by pfeerick** [comment]
I thought this was mentioned in another issue recently, as I commented it's even worse on the NV14 due to the portrait screen... basically is a table with three columns, so is wrapping. It may be better to change it to two colums, and have a second line. At the moment it says Module (but I think it could also say "Receiver" in some instances). So instead it could be 
```
Module: Multimodule
Status: No MULTI_TELEMETRY detected
```
Even if it that wrapped (i.e. on the NV14) it should look a lot better. 

Anyway, the version dialog is here => `radio/src/gui/colorlcd/radio_version.cpp`

**Comment by mha1** [comment]
I changed the popup to two columns and two separate lines for type and status.

Here's a picture to show the full scrollable layout (receiver made temporarily visible):
 
![image](https://user-images.githubusercontent.com/5615068/190643591-fbbf538d-214d-44b9-abb6-17835ea7c164.png)
![image](https://user-images.githubusercontent.com/5615068/190643697-d55f0541-6e55-43b9-a020-20ef755aeae6.png)

Internal module MPM, external module OFF and receiver made hidden again (depends on hardware presence):

![image](https://user-images.githubusercontent.com/5615068/190644977-87f2310d-07d4-4653-b419-d841fa54ef61.png)

Internal MPM, external module CSRF:

![image](https://user-images.githubusercontent.com/5615068/190645504-1790f084-3126-40dc-8e0d-8cf580f15583.png)

Internal module OFF, external module  FLYSKY:

![image](https://user-images.githubusercontent.com/5615068/190646118-b32a97a6-22fc-4d29-b1d5-52c70ae817fd.png)

Concerning the "no information" external modules I found no code that outputs the name of the external module for modules other than MPM, CSRF and PXX2. One improvement could be to use `g_model.moduleData[module].type` to show at least the name of the enabled (model settings) external module, e.g. one of those:

```
  MODULE_TYPE_PPM,
  MODULE_TYPE_XJT_PXX1,
  MODULE_TYPE_DSM2,
  MODULE_TYPE_R9M_PXX1,  // R9M
  MODULE_TYPE_R9M_LITE_PXX1,  //R9MLite
  MODULE_TYPE_R9M_LITE_PXX2,  //R9MLP                
  MODULE_TYPE_GHOST,
  MODULE_TYPE_R9M_LITE_PRO_PXX2,
  MODULE_TYPE_SBUS,
  MODULE_TYPE_FLYSKY,
  MODULE_TYPE_LEMON_DSMP,
```

Btw: do R9M_LITE_PXX2 and  R9M_LITE_PRO_PXX2 not count as PXX2?

```
inline bool isModulePXX2(uint8_t idx)
{
  return isModuleISRM(idx) || isModuleR9MAccess(idx) || isModuleXJTLite(idx);
}
```

**Comment by gagarinlg** [comment]
Can you please test the NV14/EL18 via the simulator or simu?

**Comment by mha1** [comment]
NV14 internal module FLYSKY, external module CSRF. Don't really know why it breaks "no information". But if we follow my proposal we would show "FLYSKY"

![image](https://user-images.githubusercontent.com/5615068/190650823-44accfdd-97c3-4fb0-b0dc-40e07c6bda01.png)

**Comment by mha1** [comment]
Oops, this looks totally unchanged to current main, i.e. module and status concatenated in a single line. I just edited radio\src\gui\colorlcd\radio_version.cpp. Is NV14 treated separately?

**Comment by mha1** [comment]
Sorry again. Me dummy forgot to build for the NV14. I'll try again

**Comment by gagarinlg** [comment]
This looks good!

**Comment by mha1** [comment]
got rid of "no information" module names. Module names are now identical to the settings internal and external RF dialog, expect PXX2 which sets name depending on hw info.

![image](https://user-images.githubusercontent.com/5615068/190724684-4832f763-065e-44c6-af24-6fb095363703.png)

**Comment by pfeerick** [comment]
That looks a lot better! 😍

**Comment by mha1** [comment]
@pfeerick anything else I can do?

**Comment by pfeerick** [comment]
Hm... how about we hide the status line when there is nothing to show? i.e. `int_module_status_w` and `ext_module_name_w` can go bye bye if `MODULE_TYPE_NONE` ("OFF" should be sufficient there! 😆 ) or a module type that doesn't give any status.

**Comment by mha1** [comment]
Actually that was the reason I put all the _w in the class definition because I thought of being able to hide/unhide lines like the PXX2 stuff. I'll try an update for the status lines. And thanks for pointing out my most favorite oops. The famous copy with incomplete edit after paste error

**Comment by mha1** [comment]
![image](https://user-images.githubusercontent.com/5615068/191011741-ce3c3bf1-c9e5-4029-8d7c-820f30a3f34f.png)
![image](https://user-images.githubusercontent.com/5615068/191012210-e1f4aaa1-2c0f-4c62-9916-6fd549acf832.png)
![image](https://user-images.githubusercontent.com/5615068/191012049-35b1fc4f-276c-4df2-b1aa-1141400658fb.png)

**Comment by pfeerick** [comment]
Perfecto! :)
