### ISSUE TITLE
wrong values ​​on logical switches

### ISSUE THREAD

**Issue by tonims1** [EdgeTX/edgetx#233]
If I want to have a 10% throtle to activate the timer.  in v1 I put thr and in V2 I should be able to put -90.  Well, you can't. It only gives me the option to put from 0 to 250

**Comment by tonims1** [comment]
Reported for another person. sorry

**Comment by tonims1** [comment]
bug opened by someone else .sorry

**Comment by pfeerick** [comment]
No harm in making sure it doesn't get missed ;)

**Comment by raphaelcoeffic** [comment]
> No harm in making sure it doesn't get missed ;)

It's even already fixed ;-) (see 87610b8449e6)
