### ISSUE TITLE
Nightly 2.8 - Yaapu LUA screen slightly off-center

### ISSUE THREAD

**Issue by robustini** [EdgeTX/edgetx#2339]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

As you can see from the image I posted, Yaapu LUA's screen is slightly off-center to the right, as can be seen from the vertical white band on the left.
It is absolutely a small thing but it would be better to bring it back to center.
I believe that the same imperfection also exists with other LUAs.

### Expected Behavior

That the image was centered

### Steps To Reproduce

1. Flash the latest nightly build
2. Install Yaapu LUA script
3. Add the Yaapu widget on a new fullscreen screen layout with no other controls shown , and switch to that screen

### Version

Nightly (7e54059)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

![rn_image_picker_lib_temp_5ab86b51-d4d1-4738-9305-6865dd5d4262](https://user-images.githubusercontent.com/3864712/191471141-98579806-54bb-4aa1-ba38-d7255b2183e3.jpg)

**Comment by pfeerick** [comment]
Reproducible with Yaapu telemetry widget 1.9.6-dev-4265d2f. The red outline frame which is shown if there is no telemetry is also off-screen by one column.

**Comment by stronnag** [comment]
Save affect is seen with the INAV telemetry widget.

**Comment by pfeerick** [comment]
I noticed an interesting behaviour - if you make the widget enter full-screen (interactive) mode... it then aligns properly... 🤔 

i.e. on the left it's just "normal" fullscreen, and you can see that 1px sliver on the left. I then press 'n held, choose "full screen" and now on the right it's correctly positioned as you can see the full red outline for 'no telem'

![image](https://user-images.githubusercontent.com/5500713/192140377-574c9555-1cc1-4937-a6c5-5891a439e0f6.png)

**Comment by stronnag** [comment]
Me too!!!!
INAV widget behaves the same way (looks correct on manual Full Screen).

**Comment by robustini** [comment]
@yaapu what do you think?

**Comment by raphaelcoeffic** [comment]
Smells like LVGL style border or similar.

**Comment by banyaszg** [comment]
It is reproducible with a simple full screen widget which just fills the area with a color. The left line is the background image.
