### ISSUE TITLE
Telemetry tab disco.

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#234]
https://youtu.be/KAR-4Z0gxSM

Since telemetry fields have more dynamic active state, we have kind of disco effect.

Solution
1. Add background music ;) 
2. Active color should be used for consistency so maybe 1-2 seconds off delay will do the trick.

**Comment by raphaelcoeffic** [comment]
@JimB40 the refresh is now at about 100ms, I can make that longer, if it is better.

**Comment by JimB40** [comment]
2 sec timeout to switch off active state should be okay. If next telemetry packet comes withon this time it stays yellow

**Comment by raphaelcoeffic** [comment]
@JimB40 I've just made a small change that should make it a slow disco ;-) Now it should be yellow until "sensor lost".
