### ISSUE TITLE
Nightly 2.8 - The acceleration of the encoder is now unmanageable

### ISSUE THREAD

**Issue by robustini** [EdgeTX/edgetx#2341]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Thanks to @raphaelcoeffic for reintroducing acceleration on encoder rotation, but after [that commit](https://github.com/EdgeTX/edgetx/commit/c2b1b6febf96b2c6c86f772f28f1fe8cc4854e96) it became unmanageable.
As soon as it accelerates it starts like a rocket.
Convenient when setting colors in RGB perhaps but unmanageable in all the other menus of the tx.

### Expected Behavior

Acceleration should be more proportional.

### Steps To Reproduce

1. Flash the latest nightly build
2. Check the rotary encoder speed

### Version

Nightly (7e54059)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

It would also be interesting if the acceleration speed was configurable in the tx settings.

**Comment by pfeerick** [comment]
#2341 Should have resolved this... acceleration is now limited to number edit fields and the popup choice lists.
