### ISSUE TITLE
Companion not work with ext. XJT Lite in Zorro

### ISSUE THREAD

**Issue by meyer1111** [EdgeTX/edgetx#2343]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

XJT Lite module works fine with radiomaster zorro. But not with companion (tested with 2.7.0 and 2.7.1).
error message:
"Warning: The internal module protocol **FrSky XJT lite (D16)** is incompatible with the hardware internal module **MULTI** and has been set to **OFF**!!

But, i will not use internal module. External module works fine. I can bind FrSky Receiver without problems.

### Expected Behavior

companion shall **not replace** "XJT Lite D16" with "FrSky XJT (D16)".

### Steps To Reproduce

1. edit model with companion

### Version

2.7.1

### Transmitter

Radiomaster Zorro

### Anything else?

![errorEdgeTX_FrSkyXJT_lite](https://user-images.githubusercontent.com/114142710/191703965-cd50c7a1-ddb1-44f8-b874-7e12df5602d7.jpg)
![no_XJT_Lite](https://user-images.githubusercontent.com/114142710/191703994-82fca0cc-c7f9-48e3-b746-6cfe31786f70.jpg)
![Zorro_XJT](https://user-images.githubusercontent.com/114142710/191704018-7d9a4de2-fe38-4465-ab2a-e392d7a160ec.jpg)
![Zorro_XJT_Lite_display](https://user-images.githubusercontent.com/114142710/191704049-2015a182-b7b4-43af-8c2f-404c3daa45ae.jpg)

**Comment by pfeerick** [comment]
I can reproduce this on my ELRS Zorro with both 2.7 and 2.8-dev Companion when the default Int. module is set to CRSF and radio settings as read from the radio agree that int. is CRSF. XJTLite is not even an option for internal anyway, so Companion seems to be mis-reading something. It seems somewhat specific to the XJTLite setting as setting Ext. to GHST was processed fine. 

![image](https://user-images.githubusercontent.com/5500713/191729354-1f7edf70-454c-4d2b-bfaf-87ad517a4775.png)

[zorro-xjtlite.etx.zip](https://github.com/EdgeTX/edgetx/files/9624971/zorro-xjtlite.etx.zip)

**Comment by pfeerick** [comment]
This should be fixed for 2.8, which will hopefully be going into RC soon. You should be able to get away with grabbing a 2.8-dev build of companion still though in about two hours if you need it now ;)

Companion (main branch): 
- Windows =>  https://github.com/EdgeTX/edgetx/actions/workflows/win_cpn-64.yml?query=branch%3Amain
- Mac => https://github.com/EdgeTX/edgetx/actions/workflows/macosx_cpn.yml?query=branch%3Amain
- Linux => https://github.com/EdgeTX/edgetx/actions/workflows/linux_cpn.yml?query=branch%3Amain

**Comment by meyer1111** [comment]
Many thanks for your help!

**Comment by pfeerick** [comment]
Many thanks for reporting it! 😄
