### ISSUE TITLE
Potential MPM Protocol list bug

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2355]
I found a problem in long scrolling list.  e.g. The protocol selection in MPM, everytime trying to scroll fast to reach the OMP protocol, nothing can be selected in the list and cannot exit the selection as well.  Will give more details when necessary.

_Originally posted by @richardclli in https://github.com/EdgeTX/edgetx/issues/2182#issuecomment-1247276784_

**Comment by richardclli** [comment]
This is gone in 2.8.0
