### ISSUE TITLE
Companion: Update Interface error on startup

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2365]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

After releasing v2.8.0-rc1, every time I run the 2.8.0-RC1 build of Companion, I get this:

![image](https://user-images.githubusercontent.com/5500713/192253580-4a5f4f4e-d985-42de-9f36-2d35b0365156.png)

regardless of what settings I have set - i.e. I can even have the update check set to "manual"

It doesn't appear if I run a prior `main` build of companion for win64. 😭 

### Expected Behavior

It not have the error!

### Steps To Reproduce

1. Install Companion for win64 from https://github.com/EdgeTX/edgetx/releases/tag/v2.8.0-rc1
2. Run Companion and be greeted with aforementioned error.

### Version

Other (Please specify below)

### Transmitter

Other (Please specify below)

### Anything else?

I've not tried the linux build, but I also tried the win32 build for giggles, and same message there.

**Comment by elecpower** [comment]
On mobile so some guesses as to cause.
Error 301 is a URL redirect. The 1st step is to retrieve the release metadata and there has not been any redirect in the prior releases.
This maybe a temporary issue tied to the release changing status from draft or a cache not refreshed yet.

**Comment by elecpower** [comment]
Ignore what I wrote above. The issue is triggered by compiler directive that has been actioned in the switch to release mode and the bug not picked up in testing as it worked like a dream.
