### ISSUE TITLE
Font space width differs between <2.8 and 2.8

### ISSUE THREAD

**Issue by gagarinlg** [EdgeTX/edgetx#2372]
The space sizes are now dynamic, depending on the font size, this breaks some Lua scripts with pixel exact positioning of things

The old font to bitmap tool creates always 4 pixel wide spaces, the LVGL font converter does it correctly and uses the space width from the font file.

By replacing the space character (0x20) by smaller space characters (somewhere in 0x2000 to 0x200F) it would be possible to reduce the space sizes for the larger fonts and reduce the differences between versions

The picture shows the width of one space char as they are currently rendered.

![grafik](https://user-images.githubusercontent.com/54738901/192361434-5933e3c4-6770-47e2-a4f3-d240a5e68888.png)
![grafik](https://user-images.githubusercontent.com/54738901/192361510-0cb813a8-4e95-4fc6-ba43-b69c6b600a5d.png)

A decision has to be made on how to proceed

**Comment by pfeerick** [comment]
What say you @JimB40 @jfrickmann @stronnag @yaapu @CapnBry ?

Fixed width spaces or font size proportional spaces?

**Comment by gagarinlg** [comment]
No fixed width, but closer to the 4 pixel. Fixed width wouldn't work without manually/scriptually (is this a word?) editing the generated lvgl font files, which I refuse to do.

**Comment by CapnBry** [comment]
Proportionalllllllllllllll if someone is using spacebar spacebar spacebar to line up their elements, they're their own problem :-D

**Comment by gagarinlg** [comment]
I totally agree, but I think some just do not have enough room for it.
How about adding the different space widths to the fonts, that's costs only a few bytes of flash for the descriptor and map all of those codepoints to the standard space for B&W radios?
Then the Lua people (sounds like a band to me) can decide which space they want. Except that that totally breaks compatibility with older versions.

**Comment by raphaelcoeffic** [comment]
Guys, do we really want to support broken stuff for ever? ATM, we are already providing backward compat for broken font baselines. Do we really now want to have support for broken spaces?

**Comment by gagarinlg** [comment]
> Guys, do we really want to support broken stuff for ever? ATM, we are already providing backward compat for broken font baselines. Do we really now want to have support for broken spaces?

I would prefer having the 0x20 space as it is default for that font and add 0x2009 (THIN SPACE) and 0x200A (HAIR SPACE) to the fonts, so that it is possible to select smaller spaces, when needed.
The other space variants are also proportional, but smaller than the normal space.
Do we all, including the people that have to adapt their scripts, agree to do it that way? OpenTX is mostly dead anyways (now I am going to get hit) and we have to start cleaning things up. There is not enough man power and masochism available to maintain compatibility to broken stuff for ever.

**Comment by pfeerick** [comment]
For ever - no... that's what 3.0 is expected to break a lot of... that's the time to break all the old APIs ;) I have no problem with the proposed suggestion, but I'm not a script author ;)

**Comment by JimB40** [comment]
@gagarinlg I have yesterday nightly with your PR 
So to confirm. Both on 2.7 and 2.8 have now 4px spaces?
While 2.7 looks like it has 2.8 nighly seems to have proportional

![screenshot_tx16s_22-09-28_09-47-35](https://user-images.githubusercontent.com/46420768/192720131-2e53fc14-7e01-4b55-b004-27a82dc9c6bb.png)

![screenshot_tx16s_22-09-28_09-47-13](https://user-images.githubusercontent.com/46420768/192720128-e2a4a07e-aa4c-484a-9290-ed584d44e946.png)

**Comment by gagarinlg** [comment]
I did not make any change to the space width yet, I am waiting for the discussion to finish.

**Comment by JimB40** [comment]
Thing is as you can see on screenshot that if space settings are the same (4px) it seems LVGL renders space properly.
Moreover I've checked 4-5 scripts (not INAV) and all of them look okay. 
To my eye 2.8 (LVGL) is  1-2% mode compact (kerning). But with different render enginge I doubt we will pinpoint extact same look. 

Left 2.7.1 - Right 2.8 nightly

![IMG_9378](https://user-images.githubusercontent.com/46420768/192727735-be487f3d-1f8c-4e7e-9e80-dda587bec940.png)
![IMG_9379](https://user-images.githubusercontent.com/46420768/192727756-a243a745-b476-4a7c-adc3-f6187ecf64cf.png)
![IMG_9380](https://user-images.githubusercontent.com/46420768/192727777-73a5e9f7-6444-4103-ab65-69cd3cb20f6d.png)

**Comment by JimB40** [comment]
Yes here is a proof it's slighlty more compact. Pay attention to multi line text boxes on the right 
![IMG_9382](https://user-images.githubusercontent.com/46420768/192731143-277ddb31-479d-44d0-a7e3-c6a43d2fa204.png)

**Comment by gagarinlg** [comment]
The kerning difference is probably, that before 2.8 no real kerning was done.

**Comment by gagarinlg** [comment]
> Yes here is a proof it's slighlty more compact. Pay attention to multi line text boxes on the right (SMLSIZE used) ![IMG_9382](https://user-images.githubusercontent.com/46420768/192731143-277ddb31-479d-44d0-a7e3-c6a43d2fa204.png)

There two things come together. The space width for SML is slightly smaller with 2.8 (3 instead of 4) and the kerning differences.
I do not think we will get it to render pixel exact identical on 2.8 as it was before

**Comment by JimB40** [comment]
And I can see now lineHeight is rendered bigger on 2.8. At least for SMLSIZE font size (13)
You can see that on screenshot and because it's rendered bigger last line with 'wrong target' disappeared.
But this will affect only multiline fields.
If .line_height is equal to 13 in both 2.7 & 2.8 it's about LVGL render engine 

![IMG_9383](https://user-images.githubusercontent.com/46420768/192732423-0d06e1b8-11e6-4883-8582-316ee9ceb316.png)

**Comment by gagarinlg** [comment]
This can probably be set somewhere for the multi line text field

**Comment by JimB40** [comment]
For me is not a problem, using multi-line twice.
But let others speak. Just run scripts you have and look if things look good.

**Comment by gagarinlg** [comment]
> I checked my scripts and text placement is ok, except for the known issue about the v-align and left offset
> 
> ![image](https://user-images.githubusercontent.com/30294218/192739872-a970f658-d71f-4135-be87-c543c4ab50b1.png) ![image](https://user-images.githubusercontent.com/30294218/192746715-84d21abc-261d-49af-a283-a41057eb4198.png)

when you use a nightly the vertical text alignment and the 1 pixel offset should be fixed

**Comment by jfrickmann** [comment]
> Guys, do we really want to support broken stuff for ever? ATM, we are already providing backward compat for broken font baselines. Do we really now want to have support for broken spaces?

I would say that it should be fixed once and for all, and then we just have to suck it up and update our Lua scripts. But this means that the fix should be tested carefully, so we do not see a number of changes and have to change the Lua scripts over and over again. And if we have to update the Lua scripts, then let's get rid of that offset business in Lua as well!

As a general philosophy, I think that we should keep it backwards compatible if feasible. But sometimes this is not possible, and then we just have to update our scrips - that's the price of progress!

Jesper

**Comment by stronnag** [comment]
Hard choices. 

If one maintains a complex script that works on both OpenTX and EdgeTX and the majority of users are on OpenTX, then there will be a difficult decision to be made if maintaining backwards compatibility is not easy.

**Comment by gagarinlg** [comment]
As @JimB40 is happy the way it is now, when none of you is requesting changes, I will leave it as it is. If someone really needs a change of the space sizes, I will add the smaller space characters and you can use those.

If no one complains until tomorrow evening (my timezone, CEST/GMT+2), I will close the ticket

**Comment by gagarinlg** [comment]
Time is up. This issue will be closed and script writers have to adapt to the LVGL font renderer space sizes.
