### ISSUE TITLE
In the flight modes menu, can't tell which trim is being edited

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#2376]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

TX16S, EdgeTX 2.7.1

The Flight Modes menu has six fields for editing the properties of the trims. However the fields lack a label, so it's impossible to know with any certainly which field goes with which trim (my guess is that the order is AETR, T5, T6...  but it's only a guess...).

Maybe have a submenu for the trims which would give more room for explanatory text. Or else a label at the top which displays the name of the trim with the focus.

I'm calling this a bug rather than a feature request, because the feature is already there, but is missing an essential element.

### Expected Behavior

See above

### Steps To Reproduce

See above

### Version

2.7.1

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
Have a look at 2.8-rc1 and see what you think ;)

![image](https://user-images.githubusercontent.com/5500713/192404662-a9069759-8dda-407b-a61b-4c7418633fe5.png)
became
![image](https://user-images.githubusercontent.com/5500713/192404691-0e16af52-eb51-4fe3-9fcc-6669c9530f31.png)

**Comment by RC-SOAR** [comment]
Looks good!

**Comment by pfeerick** [comment]
Fantastic! Any suggestions you have regarding the UI would be appreciated as we move onto 2.9 and finishing the LVGL migration.
