### ISSUE TITLE
Companion treating X12S ACCESS ISRM like XJT

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#2383]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

I just realized I never submitted this as a bug and was probably forgotten in a PR comment from a while back https://github.com/EdgeTX/edgetx/pull/2019#issuecomment-1207302870

>Okay now that you made me look at my old post, maybe it's caused by something else 😛 Almost seems like it's treating the X12S like the internal module is set to XJT instead of ISRM even though it's set to ISRM.
>
>This is what the X12S ISRM radio writes:
>```
>moduleData: 
>   0:
>      type: TYPE_ISRM_PXX2
>      subType: ACCESS
>      channelsStart: 0
>      channelsCount: 16
>      failsafeMode: NOPULSES
>      mod: 
>         pxx2: 
>            receivers: 0
>            racingMode: 0
>            receiverName: 
>               0:
>                  val: "SR6"
>```
>
>This is how Companion 2.8 reads it in (notice it offers the `Antenna` option as if it's treating it like the internal module is set to `XJT` and not `ISRM` (and I made sure it's set to `ISRM`)):
>
>![image](https://user-images.githubusercontent.com/1323809/183269476-c4d0e90b-9576-4473-8c64-b517a52f57ea.png)
>
>So this is how Companion 2.8 writes it back out:
>```
>moduleData:
>  0:
>    type: TYPE_ISRM_PXX2
>    subType: ACCESS
>    channelsStart: 0
>    channelsCount: 16
>    failsafeMode: NOPULSES
>    mod:
>      pxx2:
>        receivers: 0
>        racingMode: 0
>```
>
>But Companion 2.8 still reads in and writes out fine with my X9D+2019:
>
>![image](https://user-images.githubusercontent.com/1323809/183269555-aea80df6-bd0a-4bb9-bfe4-55c14e3e7f1f.png)

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12 w/ISRM upgrade

**Comment by pfeerick** [comment]
Need to consider https://github.com/EdgeTX/edgetx/pull/1765 and associated PR for that latter point I think.

**Comment by elecpower** [comment]
Looks like best for me to wait until 1765 is merged and see what Companion tweaks are necessary to match the radios
