### ISSUE TITLE
Logical switch monitor

### ISSUE THREAD

**Issue by djabmal** [EdgeTX/edgetx#2396]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the channel monitor section the switch monitor does not show the logical switches used

### Expected Behavior

see the logical switches lit

### Steps To Reproduce

1. go in channel monitor
2. go to logical switches monitor
3.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S

**Comment by pfeerick** [comment]
Possible duplicate / related to #2384
