### ISSUE TITLE
T18  KEYS BACKLIGHT

### ISSUE THREAD

**Issue by norulers** [EdgeTX/edgetx#240]
![20210617203931](https://user-images.githubusercontent.com/5206964/122398600-9ec57f80-cfac-11eb-8b43-647ed349f9e6.png)
Image from opentx 2.3，There is a circle of key backlight around T18. need to add a menu to enable or disable it。

The Hal. H file has the definition of key backlight，I think it's just the lack of a menu。

**Comment by raphaelcoeffic** [comment]
@norulers that should be easy! Thx for the hint!
