### ISSUE TITLE
Error message when launching Companion 2.8 on M1 mac mini with Monterey 12.6 OS

### ISSUE THREAD

**Issue by Dweinbach** [EdgeTX/edgetx#2405]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When launching macOS companion , error message box displays 'Unable to download Meta Data. Error:301 Protocol "" is unknown.'

![image](https://user-images.githubusercontent.com/29680000/192851260-7a8eb5db-a024-4b18-9aba-2346f2b5ba2f.png)

### Expected Behavior

there should not be an error when launching, or error message should explain what actions to take to correct

### Steps To Reproduce

1. install companion on macOS system that already has working copy of 2.7.1
2. launch companion 2.8

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S

### Anything else?

![image](https://user-images.githubusercontent.com/29680000/192851832-235691b9-acf9-4e81-906e-0541e6df5612.png)

![image](https://user-images.githubusercontent.com/29680000/192852123-de64238a-4379-4aad-8909-d4088e71afac.png)

**Comment by elecpower** [comment]
Fixed in RC2 refer #2378
