### ISSUE TITLE
Failsafe UI doesn't allow copying of channel value to failsafe for individual channels

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#2416]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Running 2.8.0 RC-1 on TX16S

In OTX, when using the MPM with FrSky and FlySky protocols, there's a way to copy _individual_ channel values to failsafe. However this option is lacking in EdgeTX (you can only copy _all_ channels to failsafe, as in OTX).

In OTX, the interface works as follows (non-touch, TX16S). 
1. Go to Model Setup menu
2. Select Failsafe mode = custom
3. Choose 'set'. Takes you to the failsafe menu with all channels displayed
4. Highlight the channel 
5. Click {ok} to place in edit mode
6. Long press {ok}. The channel value is copied, with beep to confirm. Alternatively, you can set the value manually.

The Zorro / OTX has the option to 'Channel=>Failsafe' in a dropdown (other options include 'None', 'Hold', 'Channel**_s_**=>Failsafe')

 

### Expected Behavior

See above

### Steps To Reproduce

See above

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

TX16S / 2.8.0 RC-1

**Comment by raphaelcoeffic** [comment]
@RC-SOAR what about having a second button copying the current channel value?

<img width="377" alt="Screenshot 2022-10-01 at 10 05 38" src="https://user-images.githubusercontent.com/1050031/193399677-109c7838-5892-4ac6-b4ed-7129c9f8f8e1.png">

I'd have to find a suitable icon in those already in the font.

**Comment by pfeerick** [comment]
Have a look at #2417 also if you're fiddling with the failsafe page ;)

**Comment by RC-SOAR** [comment]
@raphaelcoeffic Yes, that would work. 
Another suggestion: is just have it as an additional action when you hit the gear icon - a tap would immediately copy the channel value into the failsafe value field.
