### ISSUE TITLE
No acceleration (or acceleration very weak) when changing failsafe values with roller.

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#2417]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Running 2.8.0 RC-1 on TX16S.

In the failsafe menu it's possible to alter a channel's failsafe value using the roller, however the click increment is only 0.1, and the acceleration is very weak. This makes it very slow go from one end of the range to the other.

### Expected Behavior

It should be possible to span the range -100 to +100 in a few seconds.

### Steps To Reproduce

1. In MPM options, choose FrSky D16 protocol
2. Open the Failsafe menu
3. Use the roller to change a failsafe value

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

TX16S / 2.8.0 RC-1

**Comment by pfeerick** [comment]
Ok, so need to check if #2356 needs extending to another component.

**Comment by raphaelcoeffic** [comment]
The basic issue here is that the value range is quite different.

Most values have a range between `-100` and `+100`, while these limits have a range from `-1024` to `+1024`. So we would need to detect this and apply some multiplication factor.
