### ISSUE TITLE
Companion - B&W - EEPROM Size

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2424]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Just noticed in the Model print view for B&W it still mentions EEPROM size... and doesn't seem to relate to the yaml file size either.

![image](https://user-images.githubusercontent.com/5500713/193236100-c48d41e4-b89c-4d70-85dc-d157701c2c59.png)

### Expected Behavior

Probably for it to go away, as yaml file size probably isn't of much use. 

### Steps To Reproduce

Create a new model in a B&W radio profile
Look at the "Print Model" preview

### Version

Nightly (Please give date/commit below)

### Transmitter

iFlight Commando8, RadioMaster TX12 / TX12MK2

**Comment by elecpower** [comment]
Agree it can go bye bye
