### ISSUE TITLE
Shortcut keys for visual text keyboard

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2425]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The new keyboard in 2.8.0 has become much more cumbersome for radios without a touch function than it was before. To allow a little easier input, I would like to propose something.

### Describe the solution you'd like

The buttons SYS, MDL, TELE and PgUp/Dn are currently without function. How about assigning the following functions to these buttons:
SYS = Arrow left
TELE = Arrow right
MDL = toggle CapsLock activ/inactiv

Horus X10
PgUp/Dn = toggle marked letter uppercase/lowercase

Horus X12
PgUp = marked letter to uppercase
PgDn = marked letter to lowercase

**Comment by Eldenroot** [comment]
Great idea!

**Comment by ParkerEde** [comment]
@philmoz what do you think about this?

**Comment by philmoz** [comment]
I've added PR #4355 for this.

Please see the PR for the shortcut mappings I have chosen (different to what was suggested here).

**Comment by ParkerEde** [comment]
Basically, the shortcuts work. However, the keys/buttons are different from those in the description above. Would you please use the keys according to this list?
SYS = Arrow left (not Backspace)
TELE = Arrow right
MDL = toggle CapsLock activ/inactiv

Horus X10:
PgUp/Dn = toggle marked letter uppercase/lowercase

Horus X12:
PgUp = marked letter to uppercase
PgDn = marked letter to lowercase

**Comment by philmoz** [comment]
I chose the shortcuts for the following reasons:
- The PG keys are normally associated with movement so it made sense to have them move the cursor.
- Using two buttons to change case is redundant, you only need a single button to flip the case. I chose TELE.
- There are four keyboard layout, not just upper and lower alpha. SYS made sense to do this (changing keyboard SYStem)
- That left the MDL button for backspace/delete.

**Comment by ParkerEde** [comment]
My thoughts were that these shortcuts would primarily benefit the non-touch radios. Hence this wish
![image](https://github.com/EdgeTX/edgetx/assets/15068446/faea7069-e918-41aa-b770-7eebdc95d962)
In my opinion, this is the most intuitive way

**Comment by philmoz** [comment]
> My thoughts were that these shortcuts would primarily benefit the non-touch radios. In my opinion, this is the most intuitive way

Thanks, I understand now (not having any of these radios makes is harder to visualise when I'm madly coding away).

This is what I'm thinking:
- Radios with only a single PGUP/DN key - your mapping as shown in the image above, plus LONG MDL = backspace and LONG PGDN = Delete
- X12S - as above; but PGUP also toggles case
- Radios with both PGUP and PGDN (except X12S) - mapping as per PR.

**Comment by philmoz** [comment]
For the number keyboard.

Radios with a single PGUP/DN button and X12S:
- SYS = '-'
- LONG SYS = 'MIN'
- TELE = '+'
- LONG TELE = 'MAX'
- MDL = '<<'
- LONG MDL = '+/-'
- PGUP/DN = '>>'
- LONG PGUP/DN = 'DEF'

Radios with separate PGUP/PGN buttons:
- SYS = '<<'
- LONG SYS = 'MIN'
- MDL = '>>'
- LONG MDL = 'MAX'
- PGDN = '+'
- PGUP = '-'
- TELE = '+/-'
- LONG TELE = 'DEF'

**Comment by pfeerick** [comment]
Just for reference, the colorlcd radios without touch are
- FrSky X10
- FrSky X12
- Jumper T16/T18
- RM TX16S (early)


So the physical button layouts could be

X10
![image](https://github.com/EdgeTX/edgetx/assets/5500713/c50a3a85-ab92-42db-b4d0-91aff77213a1)

X12
![image](https://github.com/EdgeTX/edgetx/assets/5500713/31d404b6-2fc4-479b-a5e7-539f5efa228e)

T16 (T18 is effectively the same)
![image](https://github.com/EdgeTX/edgetx/assets/5500713/a1768700-bfb3-4f48-97ea-627fd0c9679f)

TX16
![image](https://github.com/EdgeTX/edgetx/assets/5500713/d7951217-f14d-4784-8aa9-0684f06b8a9e)

So while this is layout is optimised for the X10, should work just fine for the X12, and be quite usable on the T16 & TX16

**Comment by philmoz** [comment]
I've updated the PR with the alternate key mappings (current mappings are in the PR).

**Comment by ParkerEde** [comment]
Tested with X10SExpress,RMTX16 and T18. Good job. Thx
