### ISSUE TITLE
cpn: Available trainer modes should be dynamically generated

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2431]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Depending on the radio capabilities, and configured RF module, the possible trainer modes could vary, yet Companion doesn't vary that list. The radio will however filter that list somewhat.

### Describe the solution you'd like

It would be better that invalid / not available options weren't shown in the first place.

### Describe alternatives you've considered

I don't use trainer mode, so I could just ignore this :grin:

**Comment by elecpower** [comment]
@pfeerick can you give me an example or two
