### ISSUE TITLE
2.8RC1 ELRS Lua BLE Joystick stops working when long press exit

### ISSUE THREAD

**Issue by RipperGOT** [EdgeTX/edgetx#2436]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In 2.7 when you activate the BLE joystick you can do a long press to exit lua and it stays active. In 2.8 if you long press to exit, it stops working. 
Sometimes I get this error: Script syntax error ?:0: attempt to index field '?' (to nil value) 
I also see the Lua a little lazy

### Expected Behavior

You could long press RTN to exit the LUA and keep it active.

### Steps To Reproduce

1 Enter in ELRS LUA-BLE Joystick and activate
2 Long press RTN to exit to model screen
3 BLE stop working

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![IMG_20221001_155608](https://user-images.githubusercontent.com/86242264/193413385-f299c355-fcd9-491c-97f1-c217bfa7cf58.jpg)

**Comment by RipperGOT** [comment]
In RC3 the ELRS lua is still lazy and the BLE joystick crashes from time to time. I also can't get out of the BLE without it disconnecting.

**Comment by pfeerick** [comment]
By lazy, do you mean slow? As I've noticed that also, and it's not LVGL specific as B&W also seems sluggish at times.

**Comment by pfeerick** [comment]
PK from ELRS just commented that we must be sending the `EVT_VIRTUAL_EXIT` event on exit (which I think we are), whereas 2.7 just killed the script. So somehow that is probably triggering the stopping of wifi/ble that would happen on a short RTN press.

**Comment by RipperGOT** [comment]
Exactly, it's slow. It looks like lag.

**Comment by raphaelcoeffic** [comment]
> Exactly, it's slow. It looks like lag.

This is caused by the fact that we switched to LVGL, and the LUA script does a full redraw on each frame. It is faster on radios that do not require the screen buffer to be inverted in software (T18, NV14, EL18). The screen inversion (180° rotation) in software costs us around 20ms on each frame. That does add up to the rest, which makes it look slower.

**Comment by raphaelcoeffic** [comment]
> PK from ELRS just commented that we must be sending the `EVT_VIRTUAL_EXIT` event on exit (which I think we are), whereas 2.7 just killed the script. So somehow that is probably triggering the stopping of wifi/ble that would happen on a short RTN press.

This is probably caused by the fact the event still gets passed to the script while we actually kill it. I can check if there isn't some weirdness here.

**Comment by gagarinlg** [comment]
Long term goal: expose the UI API to Lua in a way, that LVGL handles partialnredraws of Lua scripts
