### ISSUE TITLE
Portrait screen - spacing and update tweaks

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2442]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

- [ ] The buttons on the Model Setup tab are not as nicely shown on the NV14 as the TX16. 
![image](https://user-images.githubusercontent.com/5500713/193440386-0acf1142-7344-45c2-b4a6-638e2d4643d4.png)

- [x] https://github.com/EdgeTX/edgetx/pull/2489
The outputs page has some visual quirks, which seems to go away as soon as you scroll... btw, when I tried to screenshot it on hw, the screenshot showed what it *should* look like... but simu did capture it properly. And it's not theme related, the same happens with the default theme. 
![image](https://user-images.githubusercontent.com/5500713/193440465-8a4ea474-868a-449d-b4e6-7805a8a9be45.png)
![image](https://user-images.githubusercontent.com/5500713/193440478-0ae9ccb6-c837-4afa-801a-7671a930c5fa.png)

### Expected Behavior

1. I'm in two minds about whether it just needs a little more padding between each the first two and the third button of each group, or if it should be put in a grid, and the grid changed depending on screen dimensions (i.e. like the flight mode tab). 

2. ~~That it look the same as it does after scrolling when you first enter the page~~ (fixed by #2489)

### Steps To Reproduce

1. Go into the model setting page

2. Go to the outputs tab, inspect and then scroll a bit. 

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky NV14

**Comment by banyaszg** [comment]
The channel monitor is also not centered, and there are big gaps. Maybe a one column version would be better.
![image](https://user-images.githubusercontent.com/36520141/194406263-8bb847b5-f752-45f8-ba38-a7fb6af2046f.png)

**Comment by pfeerick** [comment]
I actually think it would be better to increase the number of channels shown to 16, and reduce the number of tabs, but sure will look at single column as would be easier to implement.

**Comment by pfeerick** [comment]
> The channel monitor is also not centered, and there are big gaps. Maybe a one column version would be better. ![image]

Just looking at this - the off-centering is deliberate - there are icons shown on the left side for reversing and channel override... it looks like they got pushed too far to the left though at some point though 😮 

![image](https://user-images.githubusercontent.com/5500713/194753427-d4405f56-f47d-494e-87e7-b93015dd46ba.png)

**Comment by raphaelcoeffic** [comment]
> there are icons shown on the left side for reversing and channel override...

These icons really don't look good. Maybe we could just use another color for "override" channels? (`WARNING` red?).
For the channel reverse, frankly, I don't think you need anything: you just see that it moves the opposite way...

**Comment by pfeerick** [comment]
Yeah, there are probably better ways to do it. The icons *are* aligned now though... I couldn't leave them where they were since I was fiddling around there. 😆

**Comment by richardclli** [comment]
The file listing did not make use of full screen.

![IMG 019](https://user-images.githubusercontent.com/18414861/196338367-a2bf95d5-8925-47d4-9011-0071f88b858c.png)

**Comment by eshifri** [comment]
The area in the bottom is used to display model images, if you go into MODELS folder. This is similar to the empty right side for horizontal screen.

**Comment by pfeerick** [comment]
Button alignment was fixed in a 2.9 PR
