### ISSUE TITLE
Built-in widget names are not translated

### ISSUE THREAD

**Issue by robustini** [EdgeTX/edgetx#2443]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I don't know if it's a bug or if these selections are hard-coded, but I don't think so.
I believe instead that they are translated but they remain in English despite having chosen Italian.

### Expected Behavior

They should appear in the chosen language.

### Steps To Reproduce

1. Go to TELE, User Interface, Set Widget
2. Choose a box
3. Click on "select widget"

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

![20221002_082228](https://user-images.githubusercontent.com/3864712/193441301-6cd461ed-3353-4dee-9008-5f36c9a46274.jpg)

**Comment by pfeerick** [comment]
They are hard coded
i.e. 
https://github.com/EdgeTX/edgetx/blob/823e515392498cdc2e559e1d617b6f564a6a86dc/radio/src/gui/colorlcd/widgets/gauge.cpp#L85
https://github.com/EdgeTX/edgetx/blob/823e515392498cdc2e559e1d617b6f564a6a86dc/radio/src/gui/colorlcd/widgets/value.cpp#L153

**Comment by Eldenroot** [comment]
Can we make it into 2.8 final? I can prepare Czech translations...

**Comment by gagarinlg** [comment]
> Can we make it into 2.8 final? I can prepare Czech translations...

When you make a PR that adds the necessary defines to all languages and modify the widgets to use the defines, you might or might not get lucky.
But it has to be quick
