### ISSUE TITLE
[SOH]+imagefilename in hash from labels.yml

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2444]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

For two of my models is the hash in labels.yml a little strange. It looks so:
![image](https://user-images.githubusercontent.com/15068446/193448758-d27cdfca-8b50-4514-b12c-4383ef8aae7c.png)

When I delete the hash and correct the name, the new builded hash will looks like before.
I will attach imagefile, labels.yml and model25.yml

[files.zip](https://github.com/EdgeTX/edgetx/files/9692238/files.zip)

### Expected Behavior

the hash should created without [SOH] and image filename in labels.yml

### Steps To Reproduce

copy the attached files to a X10 based radio, cleanup the hash and name in labels.yml, change model several times and power off/on the radio.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

2.8.0 selfbuild eff7bfae

**Comment by ParkerEde** [comment]
it is also reproducible with the standalone simulator. It is enough to start it only in SD card mode and immediately afterwards these SOH entries are back.

**Comment by ParkerEde** [comment]
It seems to be the name itself. When I change it to "Slick Superlit", the problem no longer occurs. The same problem happens when a model is named "TigerMoth 1,86m".
![image](https://user-images.githubusercontent.com/15068446/193451667-55ddcc99-1119-4a94-97f2-e36cb489f468.png)

**Comment by gagarinlg** [comment]
So it is the Comma?

**Comment by pfeerick** [comment]
I have a feeling feeling 1,86m is a ANSI code... or maybe the syntax is just close enough to screw things up nicely. 

If I load just the model file into simulator for TX16S (i.e. no `labels.yml` at all so it gets generated afresh) I get....

![image](https://user-images.githubusercontent.com/5500713/193453296-9db09bc9-a6cf-45d7-8914-689f99c51934.png)

ASCII 0x01 is SOH, Start of Header... so that still matches what ParkerEde is seeing...

**Comment by dlktdr** [comment]
Looks like it's the length of the model name. The value isn't null terminated when it's exactly 15.

![image](https://user-images.githubusercontent.com/281145/193453576-f25fdbb3-2e70-4ae2-b584-a9ff687dcf5a.png)

This seems to fix it, will make a PR

**Comment by gagarinlg** [comment]
> Looks like it's the length of the model name. The value isn't null terminated when it's exactly 15.

that is a common pratice in the EdgeTX/OpenTX code base to save RAM

**Comment by dlktdr** [comment]
See PR# 2448
