### ISSUE TITLE
Custom curves aren't remembering their saved values

### ISSUE THREAD

**Issue by ZZ-Cat** [EdgeTX/edgetx#2452]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When you set up a custom curve & come back to it after editing it, the curve doesn't remember the values that you have configured for it.
Instead, the curve points jump to random values & this messes up the custom curves... badly.

### Expected Behavior

Custom curves are supposed to recall the values that you have entered, when you come back to the curve editor.

### Steps To Reproduce

On your controller (in my case, my RadioMaster TX16S Max Edition)...
1.) Model Settings -> Curves.
2.) Pick a curve slot. Any curve slot.
3.) Set the curve type to "Custom".
4.) With the default 5-point curve (although this is applicable to any number of curve points), you set the curve points to any number of your choosing. Just as long as it differs from the values used in your "standard curves". EG Set Point 2's vertical axis to -27 & the horizontal axis to -42; Set Point 4's horizontal axis to 69 & its vertical axis to 42. Leave the endpoints where they are.
5.) Write those numbers down, so you can compare them later.
6.) Exit out of the curve editor. Then, come back to the same curve you just edited. If this bug isn't visible the first time around, repeat this step a couple of times & it should be apparent after the second time you repeat it.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Firmware for this is 2.8.0-RC2 although this bug, from what I understand, has been present since the U.I. rewrite & I have a hunch that it's similar to another custom curve issue that has since been fixed.

**Comment by pfeerick** [comment]
Reproducible in simulator also. *Seems* more prone to happen if give radio enough time to save the curve before re-entering curve editor 🤷
