### ISSUE TITLE
Lua: Touch evnts kill EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV evnts

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2457]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

It seems that after a touch event, ETX stops sending EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV events. However, other events like EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV still continue to fire correctly, as well as other touch events.

### Expected Behavior

For @CapnBry to report bugs when he finds them. No keeping them for a rainy day :-P

And, you know, for touch events not hog the whole show, and leave room for EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV to work when you roll the rotary encoder. 

### Steps To Reproduce

Use this script to see events - touch events aren't actually handled, so only the ID numbers will come up. 

First, scroll the rotary encoder back and forwards, you should get `EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV` events. And for good measure, a press of PAGE and PAGE BACK will get you some `EVT_VIRTUAL_PREV_PAGE / EVT_VIRTUAL_NEXT_PAGE` action. Now touch the screen, a couple of times (or even just *once*) and try that again... `EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV` no longer detected. 

```lua
local toolName = "TNS|EventDemo|TNE"
local lastEvent = 0
local eventTime = 0

-- String identifying events
local function evt2str(event)
  if event == EVT_VIRTUAL_PREV then return "EVT_VIRTUAL_PREV"
  elseif event == EVT_VIRTUAL_NEXT then return "EVT_VIRTUAL_NEXT"
  elseif event == EVT_VIRTUAL_DEC then return "EVT_VIRTUAL_DEC"
  elseif event == EVT_VIRTUAL_INC then return "EVT_VIRTUAL_INC"
  elseif event == EVT_VIRTUAL_PREV_PAGE then return "EVT_VIRTUAL_PREV_PAGE"
  elseif event == EVT_VIRTUAL_NEXT_PAGE then return "EVT_VIRTUAL_NEXT_PAGE"
  elseif event == EVT_VIRTUAL_MENU then return "EVT_VIRTUAL_MENU"
  elseif event == EVT_VIRTUAL_ENTER then return "EVT_VIRTUAL_ENTER"
  elseif event == EVT_VIRTUAL_MENU_LONG then return "EVT_VIRTUAL_MENU_LONG"
  elseif event == EVT_VIRTUAL_ENTER_LONG then return "EVT_VIRTUAL_ENTER_LONG"
  elseif event == EVT_VIRTUAL_EXIT then return "EVT_VIRTUAL_EXIT"
  else 
    local txt = string.format("Event = %i", event)
    return txt
  end
end

local function run(event)
  
  lcd.clear()

  if event ~= 0 then -- We got a new event
    -- Save the event for subsequent cycles and mark the time
    lastEvent = event
    eventTime = getTime()
  end

  -- Show the last event for 1 sec. in the upper left corner
  if getTime() - eventTime < 100 then
    lcd.drawText(3, 3, evt2str(lastEvent))
  end

  return 0
end

return {run = run}
```

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

v2.7.1 doesn't have this issue, and it was reported that #2100 didn't either. And it does appear that later versions of simulator exhibit the same behaviour.

**Comment by CapnBry** [comment]
> For @CapnBry to report bugs when he finds them. No keeping them for a rainy day :-P

😊 I thought it was just my builds for some reason, and I made a note to check in on it later but it never was rainy enough it seems. Did you mention me because I brought it up on [discord](https://discord.com/channels/839849772864503828/842693696629899274/1006200595444678818) or because you just hold me in that high regard?
