### ISSUE TITLE
macOS (osX) Dark Mode in radio simulator (TX16s) does not look good, very hard to read

### ISSUE THREAD

**Issue by Dweinbach** [EdgeTX/edgetx#2459]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

When mac is in dark mode, simulator is hard to read due to low contrast, particularly between switch labels and background (Radiomaster TX16s)

![image](https://user-images.githubusercontent.com/29680000/193557063-27c1688e-f41d-486b-893e-a1b410b4e09e.png)

### Expected Behavior

better readability and appearance

### Steps To Reproduce

1. put computer in dark mode (mine is automatic based on time of day)
2. launch companion
3. launch TX16s Simulator

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

this is the same in 2.7.1

Companion 2.8.0RC2

**Comment by philmoz** [comment]
I may be missing somethings; but I can't see anything in the code to handle dark mode and adjust colours. So the app is relying on whatever Qt is doing internally.

In the absence of proper colour management in the app would a suitable workaround be to add NSRequiresAquaSystemAppearance = true to the MacOS info.plist to force companion and the simulator to use light mode regardless of the user setting for MacOS?

I tried this on my Mac and it does make the simulator much easier to read.
