### ISSUE TITLE
Trainer option Master/Serial lists unnecessarily Channel Range for import (that is not used)

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#246]
Tested with da8e1022 on RM TX16S.

When using SBUS trainer input (via TX16S AUX1/AUX2) and selecting Trainer Mode `Master/Serial`, the channel range selection remains IMHO unnecessarily available: 
<img src="https://raw.githubusercontent.com/wiki/dlktdr/HeadTracker/media/sbus/sbus_edgetx_step2.png">

The values of the channel range have no impact - always all 16 SBUS channels are imported.

In comparison OTX 2.3.12 hides the channel range selection for Trainer mode `Master/Serial`, which IMHO is the correct behaviour:
<img src="https://raw.githubusercontent.com/wiki/dlktdr/HeadTracker/media/sbus/sbus_opentx_step2.png">

**Comment by pfeerick** [comment]
Looks like this was fixed in #686
