### ISSUE TITLE
R9M 2019 ACCESS doesn't work in X10S Express

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2461]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

My R9M 2019 ACCESS Module dosen't work in Horus X10S Express.
I've tryed a selfbuild 2.8.0 50b7df0 with and without HARDWARE_EXTERNAL_ACCESS_MOD.

When I select R9M 2019 ACCESS on the external module and go to the module options, I don't get any feedback.
![image](https://user-images.githubusercontent.com/15068446/193577472-c057d476-09f5-4985-9af5-78e72b7b1aea.png)
![image](https://user-images.githubusercontent.com/15068446/193577626-d54d8b5d-248e-442d-afc2-5d5a7646caf6.png)

Even if I go into the transmitter settings and retrieve the "module/RX version", I get at the "external module", "module type" only a dash.
![image](https://user-images.githubusercontent.com/15068446/193577786-22be0f17-3b48-4221-8476-7a76f5c40c6d.png)
![image](https://user-images.githubusercontent.com/15068446/193577913-59181333-d953-4319-bcd5-620e5dd398bc.png)

In comparison, when I use the module in the Taranis QX7S ACCESS with **OTX 2.3.14**, the info is displayed correctly. So it can not be the module itself.
![image](https://user-images.githubusercontent.com/15068446/193578036-19ebb619-789b-483c-8cd3-e372cd333c9c.png)
![image](https://user-images.githubusercontent.com/15068446/193578173-6bafa4bd-c582-4aa4-947f-013880b5664a.png)

### Expected Behavior

R9M 2019 ACCESS should work

### Steps To Reproduce

1. use R9M 2019ACCESS external Modul
2. try to get Modul Options

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

selfbuild 2.8.0 50b7df0

**Comment by robustini** [comment]
Problem confirmed, same thing here with X10S Express and R9M 2019 with latest ACCESS FLEX firmware.
In the module options it remains on "waiting for module".
