### ISSUE TITLE
Menu build delay while PgUp/Dn (colorlcd)

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2469]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

when I switch through the menus (Modelsettings or Systemsettings) with the PgUp/Dn button, I notice that the radio hardly gets behind, because apparently in EdgeTx the menu pages require more computing time than OTX. Some keystrokes are then ignored and smooth operation is not really possible.
E.g. to get to the servo output menu in Modelsettings, you have to press the PgUp/Dn key 5 times.

### Describe the solution you'd like

I would suggest that the settings pages are built only after a short delay (e.g. 50ms). This way you can quickly jump to the desired menu item, and after this delay time the menu is built up.
It would be perfect if you could configure the delay time according to your own discretion

**Comment by gagarinlg** [comment]
Menu build times have been reduced in the nightlies, I think this is not an issue anymore.
