### ISSUE TITLE
Preflight Checks Pots and Sliders Not Working 2.8

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#2477]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The power-on preflight checks for Pots and Sliders appears to be broken. It is not honoring values set and creating boot pause screen asking for adjustment or override. The 6p switch is also affected which brings up another question. As the 6p switch is always set to 1 on radio boot, should it be removed as a preflight position check?

### Expected Behavior

In model settings under preflight checks in the Pots & Sliders section with pots & sliders turned on, a pot or slider should be positioned anywhere in its sweep before activating the corresponding control: S1/6P/S2/LS/RS. When that control is activated the current position should become the reference position/preflight position during boot.

When booting/resetting flight if the pot or slider is not in that reference position, the radio should present a screen warning the pot or slider is not in position. I confirmed this exact behavior in 2.7.1.

### Steps To Reproduce

1. Model Setup -> Preflight Checks ->  Pots & Sliders = ON
2. Set Pot or Slider to Desired Position
3. Press Pot/Slider button/control to activate
5. Exit model setup
6. Change pot/slider position to trigger alert
7. Reboot radio/reset flight
8. Boot process **should** (but doesn't) pause with screen asking for adjustment to pot/slider or return to override.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

2.8.0 Self Build 40149c48

**Comment by pfeerick** [comment]
> The 6p switch is also affected which brings up another question. As the 6p switch is always set to 1 on radio boot, should it be removed as a preflight position check?

No, not really. This only affects the T16/TX16S/T18 as other radios with 6POS are knobs. Also, it's a togglable option which you don't have to turn on if you don't care. But what if you *want* to have it in say POS3 for a particular model, so having the option is perfectly valid ;)

But yes, this seems completely inoperative atm 😮
