### ISSUE TITLE
2.8 Output Editor - Highlight Weight for Stick Movement

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#2478]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When editing an output the Min Max value should highlight according to stick movement.

i.e. If I move the stick right the Max label should be bold or inverted or somehow colorized to indicate the output weight that should be adjusted corresponding to that stick movement. On the outputs page this behavior is evident. Stick movement causes a weight to highlight in bold. 

### Describe the solution you'd like

In the output editor, the weight corresponding to stick movement should be highlighted like it does on the outputs page.

### Describe alternatives you've considered

This feature exists in 2.7.1. It appears to be a regression.

**Comment by gagarinlg** [comment]
![grafik](https://user-images.githubusercontent.com/54738901/193902340-ca8e2a3c-8316-4b7f-a1ef-a941aa3f7efd.png)

PR is made
Maybe it is enough to highlight the label and not the edit field and the button?

**Comment by jmxp69** [comment]
Yeah, any highlight would be sufficient. Definitely take the path of least resistance.

**Comment by Eldenroot** [comment]
Hmm, not visible at all (at least for people wearing glasses/outside during sunny day)... there should be used different background color + bold text...

**Comment by gagarinlg** [comment]
like this:
![grafik](https://user-images.githubusercontent.com/54738901/194103758-cc10b061-173c-45e5-9ea6-5639b919fcd7.png)

**Comment by Eldenroot** [comment]
Yes, just maybe use different background color (not same as selection color) and make also the value bold

**Comment by gagarinlg** [comment]
There is only so many different color options available...
![grafik](https://user-images.githubusercontent.com/54738901/194105156-2d2249f9-3238-4830-9b35-71a68da4376f.png)

**Comment by Eldenroot** [comment]
Coool
