### ISSUE TITLE
Chanel monitor error!

### ISSUE THREAD

**Issue by Airfiddler** [EdgeTX/edgetx#2481]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If a servo is reversed ie: Throttle servo, the channel monitor still shows movement as if the servo is not reversed. If my throttle is -100 I would expect the monitor to reflect that, by lighting the left side of the monitor. Currently the 2.8 rc2 release lights up the right side of the monitor at low throttle, even with a reversed servo. Quite confusing if you didn't remember the Throttle servo was reversed.

Excellent work on this update.

### Expected Behavior

Throttle stick low ( with a reversed servo) = -100 or left side of channel monitor lit up.

### Steps To Reproduce

1: Reverse throttle servo.
2: Observe channel monitor.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

October 3rd nightly build

**Comment by eshifri** [comment]
"Reversed servo" means reversed output?
Please notice that channel and output are not the same.

**Comment by Airfiddler** [comment]
Thank you for your reply.  I believe as you say, everything is working
properly. My confusion was in the channel output monitor, when reverse
throttle (CH 3)was selected. My apologies. You guy's are doing amazing
work. Please close this issue. Thanks again for your help.

**Comment by pfeerick** [comment]
It's always good to do a sanity check... Some of the options like that one are "strange" since they are there for specific purposes. :)
