### ISSUE TITLE
Update Companion 2.8.0

### ISSUE THREAD

**Issue by Charlevia** [EdgeTX/edgetx#2487]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Access denied.

### Expected Behavior

Update

### Steps To Reproduce

Request update from Companion 2.8.0
Ubuntu latest.

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![image](https://user-images.githubusercontent.com/54204450/194226747-7c5a1254-584d-484b-b6c2-9ddc01833acf.png)

**Comment by elecpower** [comment]
@Charlevia are you using RC or self build?

**Comment by Charlevia** [comment]
RC?   I am old and have trouble with acronyms.
RC then, self build is not on my list.

**Comment by gagarinlg** [comment]
> RC? I am old and have trouble with acronyms. RC then, self build is not on my list.

RC = Release Candidate
