### ISSUE TITLE
Problème affichage image dans la barre du haut

### ISSUE THREAD

**Issue by BartJr26** [EdgeTX/edgetx#249]
Bonsoir, nouveau testeur français d'EdgeTx je viens de constater une anomalie mineure: lorsque je souhaite afficher l'image de mon modèle par le widget dans la barre du haut, j'ai un carré blanc a la place de celle-ci.

[pfeerick - Google Translate] Good evening, new French EdgeTx tester, I just noticed a minor anomaly: when I want to display the image of my model by the widget in the top bar, I have a white square instead of it. 

EdgeTx Version 2.4.0 (7e28102d)
RadioMaster TX16s

**Comment by raphaelcoeffic** [comment]
@BartJr26 merci! And thx for adding the translation ;-) I’m French, so no issue for me, but not everyone is here 😌

**Comment by raphaelcoeffic** [comment]
@BartJr26 this is now fixed with 869bcc09b70f18.
