### ISSUE TITLE
Logical Switches V1 selection

### ISSUE THREAD

**Issue by CarlKnox** [EdgeTX/edgetx#2502]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Selecting V1 opens a selection window.
Selecting an icon on the left colors the icon according to theme and filters by that type (like sticks will display the 4 sticks) on the right.
Selecting another icon highlights that icon and filters for that type (like trims).
The problem is that sticks will remain highlighted but don't show.
Note only trims are displayed.
![image](https://user-images.githubusercontent.com/8898791/194791145-80ba979f-549f-4e57-80d9-24836070dd04.png)

Second problem,
Deselecting one of the selected icons (sticks for instance) removes all filters, even with trims still selected.

### Expected Behavior

Options:

- Deactivate the first icon
- Apply AND logic to display combined filter

### Steps To Reproduce

Models button
Logical Switches
Select any free LS
Select V1
Select multiple icons (sticks and trims shown in example above)

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

v2.8.0-rc2

**Comment by pfeerick** [comment]
Mentioned in #2447. Both issues and more were fixed in #2445 and thus be in the next RC. 

Thanks for the report :)
