### ISSUE TITLE
Translation of view layout Fullscreen

### ISSUE THREAD

**Issue by ulfhedlund** [EdgeTX/edgetx#2503]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This would add a translation for view layout "Fullscreen", related to #2454 where other widget strings were made translatable.

### Describe the solution you'd like

The view layout "Fullscreen" should be translatable.

I have fixed this in a local branch but since I don't know the string naming conventions or where the string should preferably be located in the various translation files (*.h, translations.cpp and translations.h) I am reluctant to create a PR. 

Should I wait for the experienced programmers suggestions for the above or create a PR with my solution?

I have named the string STR_VIEW_LAYOUT_FULLSCREEN and located it under STR_WIDGET_VALUE, in the if colorlcd section.

**Comment by pfeerick** [comment]
It really doesn't matter that much where it goes, or what is is called. I would probably have been be more inclined to place it next to `TR_WIDGET_SETTINGS` since that is the other string in that menu. There is a helper python script that generates all the translation stubs:
```
radio/src/translations/translation.py
```

which when run like this
```
python3 translation.py --before TR_WIDGET_SETTINGS --name WIDGET_FULLSCREEN "Full screen"
```
Modifies all the files like so
```
/home/pfeerick/repos/edgetx/radio/src/translations/de.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/es.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/da.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/tw.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/cz.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/it.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/pl.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/se.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/en.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/fi.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/pt.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/cn.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/fr.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations/nl.h #define TR_WIDGET_FULLSCREEN           "Full screen"
/home/pfeerick/repos/edgetx/radio/src/translations.h extern const char STR_WIDGET_FULLSCREEN[];
/home/pfeerick/repos/edgetx/radio/src/translations.cpp const char STR_WIDGET_FULLSCREEN[] = TR_WIDGET_FULLSCREEN;
```

And the change to `radio/src/gui/colorlcd/widget.cpp` on line 62 so it uses STR_WIDGET_FULLSCREEN ... and fixing line 65 as the S is missing - should be `STR_WIDGET_SETTINGS`, not `TR_WIDGET_SETTINGS`
