### ISSUE TITLE
"Time" does not show anything on widget

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#251]
**Describe the bug**
When "Time" is selected for widget, the widget shows the word "time", but not ant value.

 - EdgeTX version  2.4.0 current code compiled.
 - Hardware RM TX12S

**Comment by pfeerick** [comment]
A `Value` widget with the source set to `Time`? Confirmed on RM TX16S, 2.4.0 RC1

**Comment by eshifri** [comment]
Yes, Value widget and RM T16S (not TX12)

**Comment by eshifri** [comment]
File /widgets/value.cpp contains Timer field and does not have Time field.

**Comment by eshifri** [comment]
The following addition to values.cpp around line 93 fixis it:

      if (field == MIXSRC_TX_TIME) {
        drawTimer(dc, xValue, yValue, getValue(MIXSRC_TX_TIME),
                  attrValue | FONT(XL) | CUSTOM_COLOR);
      }
