### ISSUE TITLE
Companion and Lua Custom Scripts

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#2521]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

If trying to load a model that has had Lua custom/mixer scripts configured (meaning it is a custom-build firmware enabling that option), Companion will halt with this rather unhelpful error message.

![image](https://user-images.githubusercontent.com/5500713/195250531-bcea2b18-14e3-42d8-a01e-a24743d2adc9.png)

### Expected Behavior

That even if Companion has no configuration options for them (I have no idea if it does or doesn't), that the configuration values are read and written back silently.

### Steps To Reproduce

In Companion, try to read from the transmitter with the following model config:
[model1.yml.txt](https://github.com/EdgeTX/edgetx/files/9761535/model1.yml.txt)

Removing the following from the file will clear the error. 
```
scriptsData: 
   0:
      file: "GtStd"
      name: ""
```

This is a regression, as it seems this fix is no longer working: https://github.com/EdgeTX/edgetx/pull/2016

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Latest `main` and 2.8.0-rc2 builds

**Comment by raphaelcoeffic** [comment]
It seems the code assumes the presence of the `inputs` tag without checking it is actually there...

https://github.com/EdgeTX/edgetx/blob/6f494e109c70e880dcec5652988be7690ec6804a/companion/src/firmwares/edgetx/yaml_modeldata.cpp#L541-L555
