### ISSUE TITLE
Special Function Adjust does not have additional setting line

### ISSUE THREAD

**Issue by jrwieland** [EdgeTX/edgetx#253]
In Special Functions Trying to adjust a global variable via trim
There is no option to select what to adjust (i.e. Global Variable 1-9)

There is a switch selection
Adjust & enable

![IMG_20210617_201706464](https://user-images.githubusercontent.com/20526716/122487485-65d7db80-cfa9-11eb-8203-a9b54ad51cd1.jpg)

 - EdgeTX version (e.g. 2.4.0 (36870928)
 - Hardware ( RM TX16S)

**Comment by raphaelcoeffic** [comment]
@jrwieland thx! You really did a hell of a testing job! Will be fixed one-by-one!

**Comment by jrwieland** [comment]
The target of the adjust is still there (set prior to conversion) and works properly if you don't try and edit it.  However, if you edit it the target is lost.  and there is no way to reassign it.
