### ISSUE TITLE
Selecting MPM Protocol will stuck in certain point

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#2530]
Radio: TPro
Firmware: 2.8 latest
MPM version: 1.3.3.20

It cannot get pass FrskyRx, once reached that point will got stuck and encoder scroll cannot change the protocol anymore.

**Comment by richardclli** [comment]
https://user-images.githubusercontent.com/18414861/195384521-b7d870f2-f1e9-4c5e-9023-9e76165361ea.mp4

**Comment by richardclli** [comment]
More discovered.  This happens with 2.8 bootloader with 2.8 firmware.  If changed to 2.7 bootloader and 2.8 firmware the problem gone.

**Comment by richardclli** [comment]
This is report by others.  Maybe the module just not switched on?  Or failure.

**Comment by pfeerick** [comment]
Yeah, it is possible something went wrong with the communications ... I had the MPM go completely stupid the other day when adjusting the fine tune very fast (instead of RX number which is what I intended to change)... it dropped communication and I needed to power cycle the MPM to make it behave.

**Comment by richardclli** [comment]
I think this is fixed by #3112
