### ISSUE TITLE
Padding is missing on some model setting pages

### ISSUE THREAD

**Issue by banyaszg** [EdgeTX/edgetx#2534]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The paddings are missing on some pages which open from the Model Setup pagetab (Color UI). So the texts are too left and up. These are the affected pages:
- Preflight Checks
- Trims
- Throttle

### Expected Behavior

They should be the same like the RF setting and Timer pages.

### Steps To Reproduce

Just open them from the Model Setup page.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
I'm going to be cheeky and add a "Statistics screen" has a padding issue also - i.e. when you touch (and only touch) the `[ENTER] to reset` button at the bottom the whole screen jumps up a bit and the left, and actually looks to be aligned properly then
