### ISSUE TITLE
Curve Names not saved

### ISSUE THREAD

**Issue by jrwieland** [EdgeTX/edgetx#255]
While going though all of the settings to ensure proper conversion
The Curve names were missing from the mixes
went to curves, Cleared the name (since it would not let me edit what was converted (blank characters of some sort)
added names to the curves ( Low, Med, Hi, Bla)
checked the mixes and they were there again
Changed models and returned to the previous model
Curve names had reverted to no name ((blank characters of some sort) again could not edit without clearing

Tried 3 times/ways  to set the curve names
set curve names 
Return to main screen
Power off
edited names not saved

 - EdgeTX version ( 2.4.0 #36870928 )
 - Hardware ( RM TX16S)

**Comment by jrwieland** [comment]
After clearing the curves completely and starting from scratch I did get the names and setting to save.

**Comment by pfeerick** [comment]
What was the reason for restarting between each curve? I'm probably still running the RC1 build, but I was just able to add three curves in succession with unique three letter names and they were fine, and they showed up when I went both the input and mixer settings... this was on a new model though, not an imported one though, so it's either conversion related still or a regression I haven't yet...

**Comment by raphaelcoeffic** [comment]
> What was the reason for restarting between each curve? I'm probably still running the RC1 build, but I was just able to add three curves in succession with unique three letter names and they were fine, and they showed up when I went both the input and mixer settings... this was on a new model though, not an imported one though, so it's either conversion related still or a regression I haven't yet...

My gut feeling tells me this is a conversion issue.

**Comment by jrwieland** [comment]
@raphaelcoeffic your gut is correct it is a conversion issue.  I get to load a fresh version of Edge tonight (related to issue #253) so I'll take screenshots to show what is happening with the names and actual curves on conversion.  
Converted models are from V. 2.3.12.

**Comment by jrwieland** [comment]
ok here is what is happening to the curves 
1.  install edgeTX,/SD Card Conversion takes place
2. Go to curves (no Names, values are correct though)
![Curves after conversion](https://user-images.githubusercontent.com/20526716/122625771-cda72880-d074-11eb-8da7-857165bf0730.jpg)
3.  Name curves 1-4
![crv 2 named](https://user-images.githubusercontent.com/20526716/122625801-f0d1d800-d074-11eb-8507-adc44304355f.jpg)
 4.  Check the mixes - everything looks good
 5. Power off the radio and restart
 6. Names are gone and mix values have been changed on all curves edited prior to the power cycle
 ![cv2 after power cycle](https://user-images.githubusercontent.com/20526716/122625832-2e366580-d075-11eb-8131-bfa1959e6e82.jpg)
