### ISSUE TITLE
Ghost Menu  cannot be operated.

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#2559]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Unfortunately, the ghost menu can no longer be operated with the scroll wheel since 2.8 RC1, but everything still worked in 2.7.

### Expected Behavior

working ghost menu

### Version

2.8 RC3

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

On the Zorro with 2.8 RC3 it runs without problems.

**Comment by raphaelcoeffic** [comment]
@tonycake would you mind to please have a look at this? I believe this needs to be converted to the new paradigms used with LVGL & event handling.

**Comment by pfeerick** [comment]
The ghost menu wlll show up, so comms with the module are fine, it's just there is no response to input (roller, ENT)
![image](https://user-images.githubusercontent.com/5500713/195977535-d2ba5d9e-1cdb-4812-9948-e942370e8504.png)
