### ISSUE TITLE
Widget background color has no effect

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#256]
**Describe the bug**
Changing Widget background color has no effect.

**General information**
 - EdgeTX version 2.4.0 current code compiled.
 - Hardware RM TX16S

**Comment by pfeerick** [comment]
What are the steps? How do you change the widget background colour?

**Comment by eshifri** [comment]
Push "TELEMETRY" button -> push "Next Page" twice (we are on the second telemetry screen) -> select 2x6 widget template.
There will be options to change background color of two columns independently.  
This option does not have any effect.

**Comment by pfeerick** [comment]
Oh, _noice_... layout background colours! And yeah, I'm see that also... There are options for Panel 1 and Panel 2 backgrounds, for the 2x4 layout, but they don't seem to do anything. 

![image](https://user-images.githubusercontent.com/5500713/122529085-6a130000-d060-11eb-8991-de5c52e0d975.png)
![image](https://user-images.githubusercontent.com/5500713/122529111-7434fe80-d060-11eb-889b-fbaa8a0a9122.png)

**Comment by eshifri** [comment]
Looks like widget::background in widget.h does not have implementation:
virtual void background() {}

**Comment by raphaelcoeffic** [comment]
> Looks like widget::background in widget.h does not have implementation:
> virtual void background() {}

Sorry, this one is for something else ;-) You should have a look at the layout itself. You should be able to override `paint()` and thus get what you need ;-)

**Comment by eshifri** [comment]
Yes,  thank you, I have realized this, but I still cannot figure whow the Layout is refreshed/painted. In the NV14 version there was a refresh() function - here I do not see anything for drawing in the Layout.

**Comment by raphaelcoeffic** [comment]
All the layouts are inherited from this:
```
class WidgetsContainer: public FormGroup
```

So basically, as any `Window` (`FormGroup` is a window), you can just override `void paint(BitmapBuffer* dc)`.

**Comment by eshifri** [comment]
Thank you! This was helpful.
A pull request for the fix created. :-)

**Comment by pfeerick** [comment]
Closed by #272
