### ISSUE TITLE
total loss telemetry 

### ISSUE THREAD

**Issue by stubugs** [EdgeTX/edgetx#2565]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

t16s running 2.8 rc 3
crsf 6.19
flying  ar wing with 2.7.1 10 miles no problems on any model 
tried 2.8.rc3 lost all telemetry even signal strength on main top right corner at about 2 miles
 yet in goggles lq 1;100 
but tx reads as if reciever not connected yet still full control and inav lua script stopped recieving data this was not a problem in 2.8 rc1 as you can see by sig quality in 2,8 rc1 lowest tqly 98
2.8 rc 3   0 lowest yet in googles lq 1 100
![20221016_045118](https://user-images.githubusercontent.com/34194921/196017131-bf879ce9-701c-4749-83ac-cd4c0fe8cb19.jpg)
![20221016_045053](https://user-images.githubusercontent.com/34194921/196017140-c6b3c08e-0520-4130-9f9b-8cf79e8aa358.jpg)

### Expected Behavior

keep telemetry as in 2.7.1

### Steps To Reproduce

flew out as i have before same place 
at  about 2 miles all tx indications ie telem sig strengh stops as if reciever not conected but still flew home 

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

in tx quality log from 0 to 100 through out the flight yet lq in goggles as normal around 96 to 97 and controll was still there and no fail safes

**Comment by EhAye** [comment]
is it a matek h743-wing by any chance?

**Comment by stubugs** [comment]
No it's a matek 405 wing works fine on 2.7.1 10 miles plus
