### ISSUE TITLE
EMERGENCY MODE error when pressing bottom of themes list

### ISSUE THREAD

**Issue by Alex6892** [EdgeTX/edgetx#2566]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

EMERGENCY MODE error when exiting mode (themes), touch color LCD.

### Expected Behavior

Exit

### Steps To Reproduce

RМ TX16S 2.8.0-RC3
Attached video.

https://user-images.githubusercontent.com/115475444/196026364-ead435cc-c570-4766-b2ea-3092e42f92c7.mp4

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

RМ TX16S 2.8.0-RC3

**Comment by raphaelcoeffic** [comment]
Fix has been pushed to `main` & `2.8`

**Comment by Alex6892** [comment]
Sorry for my English.
I'm a little dumb.

**Comment by gagarinlg** [comment]
Most people here are not english native speakers. Nothing to be ashamed of

**Comment by pfeerick** [comment]
Definitely nothing to be ashamed off (English proficiency) ... and the bug report was perfect with a video to easily reproduce ;)
