### ISSUE TITLE
Emergency Mode Crash on selecting models

### ISSUE THREAD

**Issue by MervDale** [EdgeTX/edgetx#257]
On my Eachine TX16 S in RC1 I get Emergency Mode Crashes/Lockups with a loud buzzer noise when selecting models even if I return out and go to the model page and then go back to select another model. It will happen if I just change my mind in what model I select using the touch screen and normal switches  (enter, return, Model)

**Comment by raphaelcoeffic** [comment]
@MervDale This is probably related to your models / configuration. Could you please upload the content of RADIO and MODELS on your SD card? (ZIP file with these 2 directories)
