### ISSUE TITLE
Firmware edgetx 2.71 bluetooth

### ISSUE THREAD

**Issue by chappulin72** [EdgeTX/edgetx#2570]
Good day, I can not compile firmware 2.71 with bluetooth.
Could you help me?
I tried to compile a firmware and I get many alerts.
That would be acceptable?

As an example step one:

/workspace/edgegetx/radio/src/gui/colorlcd/access_settings.cpp: In member function 'virtual void pxx2::BindWaitDialog::checkEvents()':
/workspace/edgetx/radio/src/gui/colorlcd/access_settings.cpp:156:8: warning: unused variable 'form' [-Wunused-variable]
   156 | auto form = &content->form;

Could you guide me?

1- Compile with bluetooth for radiomaster tx16s mk2
2- I ignore the warnings?

Thank you

Translated by Google

**Comment by raphaelcoeffic** [comment]
@chappulin72 we will need your full `cmake` command line. Also, did you try with `2.8.0-rc3`?

**Comment by pfeerick** [comment]
This is what you want for bluetooth and TX16S:

`cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DBLUETOOTH=Y ..`

This worked for 2.7.1, and works for the current 2.8-RC3 code.
