### ISSUE TITLE
elrs setting up working extremely slow while yaapu script in on running.

### ISSUE THREAD

**Issue by xixijoe** [EdgeTX/edgetx#2571]
I found elrs lua script for setting is extremely slow while yaapu is running on the edgeTX system. and elrs setting back to normal if yaapu script is turned off.

**Comment by raphaelcoeffic** [comment]
@xixijoe @Flierman1945 which version are you guys using? Have you tested with `2.80-rc3`?

**Comment by Flierman1945** [comment]
> I found elrs lua script for setting is extremely slow while yaapu is running on the edgeTX system. and elrs setting back to normal if yaapu script is turned off.

Hello,
I did find if Yappu was running, elrs script would not even start. Closing yaapu and the script started and remained working if yaapu was restarted. But in the ens, I took yaapu off.

**Comment by pfeerick** [comment]
@Flierman1945 Please retest with 2.8.0-rc3 if you get a chance, as it should be resolved now.

**Comment by xixijoe** [comment]
> @xixijoe @Flierman1945 which version are you guys using? Have you tested with `2.8.0-rc3`?

it was 2.7. I have not tried 2.8

**Comment by Flierman1945** [comment]
I am on 2.7.1. Going flying tomorrow and will do the update to 2.8rc3 after and report.

**Comment by pfeerick** [comment]
Closing as I'm pretty sure this was resolved.
