### ISSUE TITLE
Zorro & TX12mkII simulator has double key bindings

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#2593]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Key <-  and  ->  are stated in help 
1. as SYS and TELE 
2. as roller left and roller right

so SYS & TELE are ovveriden by roller bindings

### Expected Behavior

To maintain compability with other targets
Bindigns should be
SYS <- (left arrow key)
TELE -> (right arrow key)
roller left '-' (minus key)
roller right '+' (plus key)

### Steps To Reproduce

press <- or -> on keboard while in simulator

### Version

2.7.1

### Transmitter

Radiomaster Zorro

**Comment by JimB40** [comment]
Same for TX12 MkII simulator.
@elecpower can you check those targets with roller and SYS key?
Seems like it the same bug or copy/paste code problem, so other targets can be affected too
Lack of Key binding for SYS is quite painful when testing in sim.

**Comment by raphaelcoeffic** [comment]
@JimB40 is that only the simulator, or the radio as well?

**Comment by JimB40** [comment]
Companion only. It's about keyboard keys bindinds
