### ISSUE TITLE
Home screen in 2.8: revert to stacking LS and EX1 sliders in same column?

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#2600]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In 2.8.0, an extra column is used up for the display of EX1/2 and this reduces the available drawing width. This can in turn cause problems with widgets designed for the wider screen area. 

Is there any chance of reverting to the behaviour in 2.7, where EX1 is stacked on top of the existing LS display? That way, users who upgrade their hardware will not run the risk of breaking their widgets.

![screenshot_tx16s_22-10-18_12-41-02](https://user-images.githubusercontent.com/6317479/196426245-915cc573-1c49-4779-be29-e9207e9396b2.png)

![screenshot_tx16s_22-10-18_12-40-58](https://user-images.githubusercontent.com/6317479/196426227-ac4e1d9d-db7a-4e73-b222-e3000f280d10.png)

### Describe the solution you'd like

See above

**Comment by raphaelcoeffic** [comment]
Should be possible, just takes someone spending on thoughts on how to do it best.

**Comment by Eldenroot** [comment]
I like ot how it was in 2.7

Or better way - you can (from my Spektrum era) disable this trim elementa and hide them. For example if you fly drones, you dont need trims in major cases. This also disablea trim buttons.

**Comment by raphaelcoeffic** [comment]
You can hide them already, but they won’t be disabled. They can be disabled one by one in each input though.

**Comment by Eldenroot** [comment]
Ok, but I still more like the 2.7 look.  Saving space :)

**Comment by RC-SOAR** [comment]
Yes, the issue is widgets breaking when using the non-stacked 2.8 format, due to the reduced drawing width.

**Comment by gagarinlg** [comment]
Maybe I will take a look this weekend

**Comment by RC-SOAR** [comment]
Many thanks!
