### ISSUE TITLE
Telemetry widgets setup screen and Page> & Page< navigation

### ISSUE THREAD

**Issue by jurgelenas** [EdgeTX/edgetx#2621]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When inside the telemetry widget setup for each screen:

![image](https://user-images.githubusercontent.com/1081265/197364866-e185151b-08a2-4ee8-aa90-0a86f4ef504b.png)

I can navigate through different screens, but it does retain the same widget outlines from the previous screens.

### Expected Behavior

Navigation using Page> and Page< buttons when in widget setup mode should work as expected. 

### Steps To Reproduce

-

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

I am using 2.8 RC3 EdgeTX version.

**Comment by eshifri** [comment]
Can you please describe the sequence? This does not look like a setup screen.

**Comment by jurgelenas** [comment]
> Can you please describe the sequence? This does not look like a setup screen.

1. Go to telemetry menu by pressing "TELE" button
2. Click "Setup widgets" button in any view (except for "top bar" probably)
3. Try navigating using PAGE> or PAGE< buttons when you have multiple views in place

**Comment by eshifri** [comment]
I did not know these buttons work in the widget setup screen :-), but they do work for me.
Can you please give it another try on the new model?

**Comment by pfeerick** [comment]
> I did not know these buttons work in the widget setup screen :-)

I don't think they are supposed to... IMO it doesn't make sense to be able to page between widget screens when you explicitly pressed setup widgets for a specific view. 2.7.1 doesn't behave this way. But I'm not against the idea if that is what people want.  :grin: I setup two views with different layouts, and while `PAGE>`/`PAGE<` did do something, it wasn't right (basically the same as what Jurg showed - outline for selected view stacked ontop of the second view content) 😆
