### ISSUE TITLE
Conversion from OTX 2.3.12 to EDGETX 2.4.0 loses input line names

### ISSUE THREAD

**Issue by lshems** [EdgeTX/edgetx#264]
When converting from OTX 2.3.12 to EDGETX 2.4.0, the line names are lost in conversion.

Every input has an 'inputName' attribute.
For every line belonging to an input, there is the attribute 'name', that becomes cleared o, conversion.

**Comment by raphaelcoeffic** [comment]
> When converting from OTX 2.3.12 to EDGETX 2.4.0, the line names are lost in conversion.
> 
> Every input has an 'inputName' attribute.
> For every line belonging to an input, there is the attribute 'name', that becomes cleared o, conversion.

Could you please please add an example model file (incl. models.txt, and radio.bin), that would help greatly to debug it.

**Comment by lshems** [comment]
can we add OTX as permitted file type, by the way?

[t16_23.zip](https://github.com/EdgeTX/edgetx/files/6680426/t16_23.zip)

**Comment by raphaelcoeffic** [comment]
Thx for the files! The OTX support can be discussed in your new issue.

**Comment by raphaelcoeffic** [comment]
> For every line belonging to an input, there is the attribute 'name', that becomes cleared o, conversion.

I do see some of them, could you please tell me which ones are missing?

<img width="296" alt="Screenshot 2021-06-19 at 15 01 46" src="https://user-images.githubusercontent.com/1050031/122643304-57a3cf80-d10f-11eb-9943-a2ebc5cc3e5c.png">
