### ISSUE TITLE
Outputs widget shows wrong channel order.

### ISSUE THREAD

**Issue by KevinFairgrieve** [EdgeTX/edgetx#266]
Vers: 2.4.0 (952bc12b)
Date: 2021-06-18
Time: 08:26:36
EEPR: 220

Horus X12S

I have my hardware set up to TAER.

When I add a widget to the screen as I do for nearly all my models. The Outputs widget shows the stick order as RETA.

Under OTX this showed what the hardware is set to.

Is this a bug or intentional? I for one would rather the widget showed what the hardware was set to.
![IMG_20210619_094438](https://user-images.githubusercontent.com/20424058/122637067-8d7f8e80-d0e4-11eb-810c-59c40d991c2b.jpg)
![IMG_20210619_094454](https://user-images.githubusercontent.com/20424058/122637071-983a2380-d0e4-11eb-9dbc-3793d33e0bbe.jpg)
![IMG_20210619_094504](https://user-images.githubusercontent.com/20424058/122637074-9d976e00-d0e4-11eb-8812-4a42f7627efb.jpg)

**Comment by lshems** [comment]
The RETA option only defines the default INPUT and OUTPUT order when setting up a new model.

Change the order of your mixer lines to what you want.

If you created a NEW model with RETA activated, and this is shown, it is a bug on the CREATION wizard, not on the outputs widget.

**Comment by lshems** [comment]
Stick order is set with MODE in a radio level.
Mode 2 is left stick rudder throttle, right stick elevator aileron.

Is indépendant of RETA.

**Comment by lshems** [comment]
see also
Can we get rid of the last functional legacy terminology of MODE and RETA definitions? #67

**Comment by raphaelcoeffic** [comment]
> see also
> Can we get rid of the last functional legacy terminology of MODE and RETA definitions? #67

What is 100% sure is that we need to ask these settings on first boot / factory reset, no matter what the names are. We can even ask which names you prefer and set custom names for you.
