### ISSUE TITLE
Outputs screen doesn't update after channel "reset"

### ISSUE THREAD

**Issue by EhAye** [EdgeTX/edgetx#2660]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After clicking "reset" on a channel, it appears like none of the settings were actually reset.
The settings are correctly reset and applied immediately... its just a display issue.
It only displays the new settings after changing screens.

2.8.0 RC3

### Expected Behavior

after clicking reset, the channel's new settings should appear

### Steps To Reproduce

1. Open Outputs Screen
2. Click Channel 1, Click Edit
3. Modify some settings (PPM Center to 1600 for example)
4. click Back to the Outputs screen
5. Click Channel 1, Click Reset

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

There's also an unrelated display bug on the 8-option screen menu.

When i click the upper left EdgeTX logo to open the 8 option menu, "Select Model" and "Channel Monitor" quickly become "Select" and "Channel" (they lose the second  line of text) but all of the other options are fine, including the other 2-line options.
It only happens on some of my models, so im gonna play around with it and figure out what causes it exactly

**Comment by pfeerick** [comment]
> When i click the upper left EdgeTX logo to open the 8 option menu, "Select Model" and "Channel Monitor" quickly become "Select" and "Channel" (they lose the second line of text) but all of the other options are fine, including the other 2-line options.
It only happens on some of my models, so im gonna play around with it and figure out what causes it exactly

Have just started seeing that recently - seems to be something to do with widgets underneath - i.e. outputs widget is a good culprit
