### ISSUE TITLE
Tbs Crossfire reconnect 

### ISSUE THREAD

**Issue by Capcom58** [EdgeTX/edgetx#270]
**Describe the bug**
Hello i noticed every time i swapp a lipo pack the crossfire module reconnects briefly then disconnects i have to completely remove the module and put it back to get it back working.

**General information**
 - *EdgeTX version (e.g. 2.4.0 or nightly and #commit number)*
 - *Hardware (e.g. Frsky X9D+ or RM TX12S)*

**Comment by raphaelcoeffic** [comment]
@Capcom58 can you please describe a bit more? Maybe edit to tell us which hardware, which firmware version for the crossfire module, etc. I'm a bit puzzled because we have quite some folks using crossfire here.

**Comment by Capcom58** [comment]
yeah i was thinking the same it could just be a isolated issue im running the latest nightly crossfire micro latest firmware also Tx16s  i may completely reflash and see what happens

**Comment by JimB40** [comment]
What exact CRSF Module version you use and what FW version is flashed into it?

**Comment by Capcom58** [comment]
I Think its all good now after the reflash everything works
