### ISSUE TITLE
AdjustRTC Checkbox and timezone are missing in Radiofirmware/Simulator

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2727]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I miss in the radio firmware, as well as in the simulator in the radio basic settings, the checkbox to set the time automatically and the field "timezone". I think it is about the flag "adjustRTC" and "timezone" in radio.yml. In Companion, however, it is displayed:

![image](https://user-images.githubusercontent.com/15068446/201534280-7ed776f0-44bc-4733-8988-6c7c00b346f5.png)

In Firmware I miss this
![image](https://user-images.githubusercontent.com/15068446/201534356-2f449230-6fa3-44c6-bf14-c9c2ea535ea0.png)

### Expected Behavior

"adjustRTC" and "timezone" should be configurable in Radio

### Steps To Reproduce

1. open Radio Settings
2. try to adjust timezone and adjustRTC

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

2.8.0 selfbuild

**Comment by pfeerick** [comment]
Not missing... just moved ;) Check under the GPS button, since these are GPS options ;)

![companion_O51ZE0xD5w](https://user-images.githubusercontent.com/5500713/201550417-3a44e0c8-1797-4599-9885-f2020b48f68b.gif)

**Comment by ParkerEde** [comment]
@pfeerick Thank you for your response. I don't have the GPS button on my HorusX10 Express. What do I have to do to get the GPS button?

**Comment by pfeerick** [comment]
Hm... probably need to enable internal GPS support then as it's probably not enabled at all for that target... I'll check and get back to you soon...

**Comment by pfeerick** [comment]
Ok, yes, so it's dependent on `INTERNAL_GPS` being defined. And it seems like it's not valid for that target... so the next question is "under what circumstances is it valid for the radio to show those options?" ... as I suspect it's not, and it's actually Companion that shouldn't be showing them?

**Comment by ParkerEde** [comment]
This option must always be displayed on all transmitters, because it uses the time only from the GPS telemetry sensor. The internal GPS module has nothing to do with the time determination.

**Comment by pfeerick** [comment]
Well, ouch... so it does... and the code even says it comes from telemetry, not internal GPS 🤦 I'm just glad it wasn't me that changed that code 🤣 Yes, this needs to be re-opened, and at least re-enabled until implemented differently.

**Comment by ParkerEde** [comment]
Can we still get that into the 2.8?
