### ISSUE TITLE
EdgeTX Companion 2.6/2.7 gives "unable to find radio sd card" error in MacOS Ventura

### ISSUE THREAD

**Issue by stgordon** [EdgeTX/edgetx#2742]
EdgeTX Companion gives "unable to find radio sd card" error in MacOS Ventura when attempting to read models from radio (Jumper T-Pro).

**Comment by pfeerick** [comment]
Support for the changes Apple made in MacOS 13 / Ventura was implemented in #2564 for EdgeTX 2.8.
