### ISSUE TITLE
R9m Access for tx18s 

### ISSUE THREAD

**Issue by EnriqueBelli** [EdgeTX/edgetx#2744]
Hi,
Does anyone have the .Bin file of the edgetx firmware for a Radioking tx18s? (the same as the jumper T18) My radio has the access mode (hardware modification). I have already tried the different firmware proposed on this page and either I manage to register and bind my receiver (R9sx) and I have no output in S.Port (pwm) or I manage to register it but not bind it. I live in europe and I also tested the Fcc as recommended above it works but with a lot of latency and it's even dangerous 😐 (thanks to the 4G antenna at the bottom of my street) I don't really know much about programming or firmware modification so if someone would have the file thanks in advance ;-)

_Originally posted by @EnriqueBelli in https://github.com/EdgeTX/edgetx/issues/260#issuecomment-1314545025_

**Comment by Helipro** [comment]
You would need to compile your own version of edgetx.
https://www.youtube.com/watch?v=F6Jb2Zyw7f0
Try: 
cmake -Wno-dev -DPCB=X10 -DPCBREV=T18 -DDEFAULT_MODE=2 -DGVARS=YES  -DPPM_UNIT=US -DBLUETOOTH=YES  -DHARDWARE_EXTERNAL_ACCESS_MOD=ON    -DLUA=ON  -DOVERRIDE_CHANNEL_FUNCTION=OFF  -DHELI=NO  -DCMAKE_BUILD_TYPE=Release ../

**Comment by EnriqueBelli** [comment]
> You would need to compile your own version of edgetx.
> https://www.youtube.com/watch?v=F6Jb2Zyw7f0
> Try: 
> cmake -Wno-dev -DPCB=X10 -DPCBREV=T18 -DDEFAULT_MODE=2 -DGVARS=YES  -DPPM_UNIT=US -DBLUETOOTH=YES  -DHARDWARE_EXTERNAL_ACCESS_MOD=ON    -DLUA=ON  -DOVERRIDE_CHANNEL_FUNCTION=OFF  -DHELI=NO  -DCMAKE_BUILD_TYPE=Release ../

->Yea, I successfully made my hown version and disable the Bluetooth for an internal GPS. I also change the serial port (GPS) to 115200 and everything work well since 2 week now.
Thanks for your help though, it might help someone else.👍

**Comment by rotorman** [comment]
@EnriqueBelli Thus, the issue here can be closed?

**Comment by EnriqueBelli** [comment]
> @EnriqueBelli Thus, the issue here can be closed?

Yep. 
The only problem left is the R9m Sx bin but that's another topic and it works by first keeping the model connection information under opentx and it remains bind when the file is transformed from bin to yml under edge TX (I'm putting this here if it can help other people) 
But yes, you can close the issue 👍
