### ISSUE TITLE
SF Adjust resets GV to "0"

### ISSUE THREAD

**Issue by jrwieland** [EdgeTX/edgetx#277]
Special Functions "Adjust" parameter.
The target of the adjust is now present (Thank you)
However, it now resets the GV back to zero instead of the incremental increase/decrease or set to number parameter that was originally present.
The additional value line of the Adjust parameter is missing 

**General information**
 - EdgeTX version (e.g. 2.4.0  #869bcc09)
 - Hardware (RM TX16S)

**Comment by raphaelcoeffic** [comment]
@jrwieland I must have missed it reading the old code, thx for re-testing and reporting!
