### ISSUE TITLE
Emergency Mode when trying to adjust colors in Themes 

### ISSUE THREAD

**Issue by planemann2000** [EdgeTX/edgetx#2785]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Transmitter goes into Emergency Mode, or it may lock the radio up when changing color in Themes page 

### Expected Behavior

Should not go into to emergency mode

### Steps To Reproduce

1 Enter themes (I am using RCVR USA theme)
2 Enter edit
3 Open up a category to edit the color
4 If the cat. opens go to the next category will go into emergency mode or it may lock up

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Nightly ts16s94f955.bin creates the bug. I have flashed this nightly in both of my transmitters with the same results.

**Comment by Kevltan** [comment]
I had this problem to, only seems to like the themes that come on the 2.8 SD card update. I think there about 4 or 5 themes including defualt! Since I have used these I have had no Emergency mode exits.

**Comment by planemann2000** [comment]
I flashed an earlier nightly and everything is good to go. Deleted 940f955.bin.

**Comment by Kevltan** [comment]
Nice one👍

**Comment by pfeerick** [comment]
So, I couldn't reproduce this with a blank model, but I could reproduce it with one based on the F3K SoarETX template, so not to pick on SoarETX, but at least it seems it made a reproducible test case for both both simu and radio.

**Comment by eshifri** [comment]
I think it happens if you start with editing current theme.
If you edit any other theme - no problem.
If after that you try to edit the current theme - no problem as well.

**Comment by pfeerick** [comment]
Interesting... with the test config that I managed to get it to crash with, it actually doesn't matter whether it's a non-active or active theme you go into first... both will hard EM. So might be a matter of change (i.e. what the pointer is actually pointing to at the time). Either way, the PR fixes this for me on radio and `simu`
