### ISSUE TITLE
Missing Chinese Option on Canpanion 2.8's Radio Profile 

### ISSUE THREAD

**Issue by CCNUI** [EdgeTX/edgetx#2791]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/88219502/204297081-712ab6ce-7e33-4fd2-9177-0bef6895ed84.png)

I Hope "cn"(Chinese Simplified) could be a Option on the "Radio Profile" page, "Menu Language". Thanks.

### Describe the solution you'd like

Add "cn" option, Thanks
![image](https://user-images.githubusercontent.com/88219502/204308729-f7668d05-59e6-4d8e-afb1-1262bd717c9b.png)

**Comment by arthurson** [comment]
it also miss hk and tw option

**Comment by elecpower** [comment]
#3587 fixes radio ui languages
