### ISSUE TITLE
Trouble when set a high baudrate (≥921k) to my External RF in ELRS v3.1.0

### ISSUE THREAD

**Issue by CCNUI** [EdgeTX/edgetx#2798]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm always frustrated when I set a high baudrate (≥921k) to my External RF.
Like this picure:
![Like_This](https://user-images.githubusercontent.com/88219502/204795151-d4aea2d7-bacd-447f-a0a9-f71a8bcbb0c9.png)

Extranal RF module: ExpressLRS BETAFPV 2.4G TX Micro 1000mW
ELRS Version: v3.1.0 or 3.x.x-maintenance
Transmitter: RadioMaster TX16S MAX
EdgeTX Version: v2.8.0 (fed140e)

🤔

**Comment by lesharodin** [comment]
Try this
https://github.com/ExpressLRS/ExpressLRS/issues/1952#issuecomment-1332843863

**Comment by pfeerick** [comment]
This should be resolved as of 2.8.1. Please comment further this not the case and the issue can be reopened
