### ISSUE TITLE
Insufficient accuracy of GPS telemetry

### ISSUE THREAD

**Issue by Scratch1983** [EdgeTX/edgetx#281]
Insufficient accuracy of displaying GPS coordinates. XX°XX' YY°YY' is a 1km x 1km square.

1) It is necessary to improve the display accuracy.
2) On the home screen widget, it would be better to display coordinates in 2 lines.

 - EdgeTX version 68986020
 - RM TX16S
 
![screen-2021-06-20-121339](https://user-images.githubusercontent.com/13181013/122666041-731ce200-d1c4-11eb-9c52-622877aa218d.jpg)

**Comment by lshems** [comment]
I need to make work of the GPS WIDGET. 

It would have an option to show coordinates in several formats, including miles/km/meters from pilot ref. That is true only thing that makes sense to show in my opinion. Why would you want to have the GPS coordinates readable in this earth circumference scale.

There will be a QR code to scan for portable apps.

**Comment by lshems** [comment]
One format will also be distance and bearing

**Comment by Scratch1983** [comment]
At the moment, the main problem is low display accuracy.

**Comment by lshems** [comment]
If I could, I would seperate the Lat and Lon part and lake it seperate sensors. The entire idea of this sensor list is to show they are there and working, not to show the value per se. That is done in a widget

**Comment by Scratch1983** [comment]
The widget also has low accuracy. If you are planning to make another widget, then ok.

**Comment by lshems** [comment]
Well, that is the idea.

**Comment by Scratch1983** [comment]
![screen-2021-06-22-165300](https://user-images.githubusercontent.com/13181013/122921233-b077a000-d37b-11eb-9c3c-5b52efb8c6bc.jpg)
This is OpenTX. Do the same in EdgeTX, please.

**Comment by pfeerick** [comment]
Perhaps that's a side effect of the GPS settings being removed from the radio setup menu? As one of the options was `Coordinate format` which allowed you to toggle between DMS and NMEA (the other two options being `Timezone` and `Adjust RTC`).

**Comment by Scratch1983** [comment]
I don't think the problem is in the format.
You need to add the number of digits after the decimal point.

**Comment by raphaelcoeffic** [comment]
> I don't think the problem is in the format.
> You need to add the number of digits after the decimal point.

This is just a minor issue, we have the data, so it’s only about displaying them.

**Comment by raphaelcoeffic** [comment]
@Scratch1983 I re-added the "minutes" part of the GPS position. You should be able to see them now in the "Value" widget.

**Comment by ChrisOhara57** [comment]
Have you considered to use Open Location code as an alternative format for display.
An accuracy of 3.5 to 3.5m would only need 8 characters in the short version.
Nine character would already give an accuracy of 0.9 to 0.9 m.
And it's only one value instead of two.

**Comment by pfeerick** [comment]
Probably not for this - but it would something good to do as a dedicated Lua GPS widget.

**Comment by ChrisOhara57** [comment]
> Probably not for this - but it would something good to do as a dedicated Lua GPS widget.

A dedicated LUA Script does already exist.
https://github.com/opentx/opentx/issues/8539

**Comment by pfeerick** [comment]
Sweet! Feel free to submit it as an addition to https://github.com/EdgeTX/edgetx-sdcard

**Comment by ChrisOhara57** [comment]
> Sweet! Feel free to submit it as an addition to https://github.com/EdgeTX/edgetx-sdcard

Is this done by writing a pull request and attaching the script?

**Comment by pfeerick** [comment]
Sort of, yes. If you're not familiar with github enough to do a PR, open an issue and attach the zip file there - and I'll do a PR to add it later. Remind me what transmitters it suits also.

**Comment by ChrisOhara57** [comment]
> Sort of, yes. A PR is more a suggested change, so would actually have any new files or changes in place. If you're not familiar with github enough to do a PR, open an issue and attach the zip file there instead - and I'll do a PR to add it later. Remind me what transmitters it suits also.

Thank you, but I try myself if a pull equest is the right way.
