### ISSUE TITLE
Missing czech special chars

### ISSUE THREAD

**Issue by Celo75** [EdgeTX/edgetx#2811]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The menu in the Czech language does not display letters written with diacritics. Letters with diacritics do not appear in all menu tabs. For example: Čeština is displayed as estina, or všechny is displayed as vechny.

### Expected Behavior

Displaying accented characters.

### Steps To Reproduce

1. Firmware in Czech language.
2. Viewing, for example, a telemetry card.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![IMG_20221203_135700-1](https://user-images.githubusercontent.com/87942302/205443190-7fbe52a2-62bc-4e01-8a02-cad17a544fd0.jpg)
![IMG_20221203_135559-1](https://user-images.githubusercontent.com/87942302/205443194-4368f2ea-6a18-4b03-87cd-c0f702ddddec.jpg)

**Comment by raphaelcoeffic** [comment]
@Celo75 seems like the Latin1-Extended-A charset was missing, which is mostly (but not exclusively) affecting the Czech translation.

**Comment by pfeerick** [comment]
Should be fixed in the next nightly and 2.8.1 when released.
