### ISSUE TITLE
main screen - flight mode text and 6pos slider not centered

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#2818]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Both the flight mode text and 6pos slider are not centered. Here's an example comparing a flight mode with text length of 1 character to a flight mode with the max text length of 10 character:

![flight mode and 6pos slider not aligned](https://user-images.githubusercontent.com/5615068/205715400-8029618c-a4f6-4cc7-af3b-475c8a1235fb.png)

### Expected Behavior

flight mode indicator is centered wrt the screen no matter the number of characters
6pos indicator is always centered wrt the screen 

### Steps To Reproduce

Enter "1" as flight mode 0 text
Enter "1234567890" as flight mode 1 text
Add switch to flight mode 1
toggle switch to see difference in alignment

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Edit: was working fine in 2.7.1

**Comment by mha1** [comment]
I'm willing to help and tried to find a fix just to realize I'm lacking lvgl know how. Focusing on one sub-problem at a time I started with the flight mode text which is all but centered. Flight mode text handling is done in `view_main_decorations.cpp`. The constructor of class ViewMainDecoration defines five layout boxes, one located at the bottom mid  `w_bc = create_layout_box(parent, LV_ALIGN_BOTTOM_MID, LV_FLEX_FLOW_COLUMN);` which is used for creating a dynamic text field for showing the flight mode text. The dynamic text is cyclically updated by getFM:

```
void ViewMainDecoration::createFlightMode(Window* bc)
{
  std::function<std::string()> getFM = []() -> std::string {
      return stringFromNtString(g_model.flightModeData[mixerCurrentFlightMode].name);
  };

  flightMode = new DynamicText(bc, rect_t{}, getFM, COLOR_THEME_SECONDARY1);
}
```

At instantiation class DynamicText (which inherits StaticText) is passed a textFlags parameter, here the text color. I found other text flags amongst them `CENTERED` but instantiating the DynamicText using `flightMode = new DynamicText(bc, rect_t{}, getFM, COLOR_THEME_SECONDARY1 | CENTERED);` doesn't change anything.

I'd appreciate some insight and tips on how to tackle this rather minor problem.

**Comment by mha1** [comment]
I'll activate the bat signal: @pfeerick

**Comment by mha1** [comment]
![044A2BB2-74BB-4ACC-B97C-4932E77A73DA](https://user-images.githubusercontent.com/5615068/207419701-790fb708-45a2-4f37-b614-49190c0cf86c.jpeg)

**Comment by eshifri** [comment]
The problem is here:
https://github.com/EdgeTX/edgetx/blob/37e07ec95d230d89184bc68005d8b134fc2c83da/radio/src/gui/colorlcd/layouts/sliders.cpp#L92

The name of the FM is bigger than the length of the 6P switch. FlexLayout adjusts the size of the window to accommodate the mode name.
The drawing of the switch starts from the left border of the window.
You may want to center the switch inside the window instead.

**Comment by mha1** [comment]
Thanks for your response.  It's been kinda lonely here :-)

Yes, I know. But there is an underlying problem. If you look at my comparsion between the shortest FM name "1" and the longest possible name "1234567890" you'll find they are already not centered. And as the switch representation is drawn relative to the window start this will not be centered at well.

So problem #1 - just looking at the FM text - is centering the FM text for all possible name lengths. It seems as if creating the window sets a default width for this window. Setting a text shorter than the window width places the text left aligned. And if the name is to long the window width gets extended to the required width with re-centering the window. This is causing the short names like "1" to move to the left. A solution could be to create a window with 0 width and let setting the text adjust the window width. This would lead to centered FM texts for any text length. 

Do you know how to create a window with a 0 default width? 

`view_main_decoration.cpp  ` creates the bottom centered window as `w_bc = create_layout_box(parent, LV_ALIGN_BOTTOM_MID, LV_FLEX_FLOW_COLUMN);`. Looking at create_layout_box() it sets the width using `lv_obj_set_size(box, LV_SIZE_CONTENT, LV_SIZE_CONTENT);`  with `#define LV_SIZE_CONTENT         LV_COORD_SET_SPEC(2001)`. And this is where I got lost.

**Comment by gagarinlg** [comment]
> Do you know how to create a window with a 0 default width?

You should be able to set a min_width for the lv_object using the lv_style... functions.

**Comment by eshifri** [comment]
I think there may be two problems with this approach:
1. 6P switch and FM name are in the same window, so its size will be adjusted according to the longest one and the other will be shifted.
2. Trying to control these things manually breaks the idea of Flex layout. :-)

**Comment by mha1** [comment]
so what's the right strategy?

**Comment by eshifri** [comment]
I do not know. At least at this time. :-)

**Comment by eshifri** [comment]
I think this line:
lv_obj_set_style_flex_cross_place(w_bc->getLvObj(), LV_FLEX_ALIGN_CENTER, 0);

added to 
ViewMainDecoration::ViewMainDecoration(Window* parent)
solves the issue.

**Comment by gagarinlg** [comment]
I think this removes that object from the normal placement calculation and it is drawn independently of all the other objects.
Which is, in my opinion, OK.

**Comment by eshifri** [comment]
Isn't it just changes the alignment of the child objects inside the w_bc?

**Comment by gagarinlg** [comment]
I am not sure if it sets this as a style for w_bc, how it is placed in its parent, or if it arranges the children inside.
I think it is applied to the placement of w_bc

**Comment by mha1** [comment]
This actually works. Can you please elaborate on what's the magic behind this line?

![image](https://user-images.githubusercontent.com/5615068/208256333-fb4184a1-5d9c-4012-87bc-d3d8ad1f5659.png)
![image](https://user-images.githubusercontent.com/5615068/208256351-6be37e58-8f35-43ae-ab10-082ec0cc8877.png)

**Comment by eshifri** [comment]
To manage the placement of the **children** use lv_obj_set_flex_align(obj,  main_place, cross_place, track_cross_place)
https://docs.lvgl.io/master/layouts/flex.html?highlight=lv_flex_align_center#_CPPv4N15lv_flex_align_t20LV_FLEX_ALIGN_CENTERE

The lv_obj_set_style_flex_cross_place() is listed as an API on the same page.
lv_obj_set_flex_align(w_bc->getLvObj(), LV_FLEX_ALIGN_CENTER,
                        LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
gives the same effect.

**Comment by gagarinlg** [comment]
> This actually works. Can you please elaborate on what's the magic behind this line?
> 

Try to read the LVGL style documentation. It helped me a lot when we started this endeavour.

**Comment by mha1** [comment]
@eshifri
```
lv_obj_set_flex_align(w_bc->getLvObj(), LV_FLEX_ALIGN_CENTER,
LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
```
I can confirm this works too and will use it as it reads closer to what it does.

@gagarinlg will do

**Comment by mha1** [comment]
Hi, while trying to fix this I noticed the 6Pos indicator has 7 ticks for 6 positions. As I didn't like the ticks anyway I changed the ticks to numbers. I mean it's position numbers not ticks as for trims.

Let me know if you like what you see. If so, I have a PR  ready to issue that solves this issue and changes the 6POS indicator to show numbers rather than ticks.

@philmoz: thanks, we noted the same problem: number in box not centered. I also addressed this, see video.

https://user-images.githubusercontent.com/5615068/208297473-a06fd614-19a1-4bcd-9d67-371043910773.mp4

**Comment by eshifri** [comment]
Looks good to me.

**Comment by mha1** [comment]
@pfeerick: I think it's up to you to decide if this 6Pos representation is worthy

**Comment by mha1** [comment]
@pfeerick can we put this in 2.8.1?
