### ISSUE TITLE
USB Mode (VCP) doesn't work with Jumper Lite V2 - Edge TX 2.8+

### ISSUE THREAD

**Issue by jmrobles** [EdgeTX/edgetx#2837]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Trying to do passtrough, after I select the VCP mode on the TX, I see the `/dev/ttyACM0` device and I can connect with it via minicom... but if I use the passthrough.py script in order to reflash the internal ELRS module, edgetx doesn't respond to any command (including echo to each keystroke). 

### Expected Behavior

Accept commands like the CLI.

### Steps To Reproduce

1. Power on the TX
2. Connect the USB to the Host (Ubuntu 22)
3. Select "USB Serial (VCP)" on the TX
4. Run the python [pass.py](https://gist.github.com/jmrobles/4acbc459620ae7ca9c145906bf61698f#file-pass-py) script
5 .Console shows the folloging error
<pre>$ python3 pass.py 
  ** Searching flight controllers **
      > FC found from '/dev/ttyACM0'

Detected the following serial ports on this system:
  /dev/ttyACM0

======== PASSTHROUGH INIT ========
  Trying to initialize /dev/ttyACM0 @ 115200
Traceback (most recent call last):
  File "/home/chema/pass.py", line 75, in <module>
    etx_passthrough_init(args.port, args.baud)
  File "/home/chema/pass.py", line 36, in etx_passthrough_init
    rl.expect_bytes(b"set: ", timeout=1.0)
  File "/usr/local/lib/python3.10/dist-packages/streamexpect.py", line 514, in expect_bytes
    return self.expect(BytesSearcher(b), timeout)
  File "/usr/local/lib/python3.10/dist-packages/streamexpect.py", line 664, in expect
    incoming = self._stream_adapter.poll(end - time.time())
  File "/usr/local/lib/python3.10/dist-packages/streamexpect.py", line 453, in poll
    raise ExpectTimeout()
streamexpect.ExpectTimeout
</pre>

### Version

2.8.0

### Transmitter

Jumper T-Lite

**Comment by pfeerick** [comment]
Have you double-checked RADIO/SYS -> Hardware -> USB-VCP is set to CLI? 

![image](https://user-images.githubusercontent.com/5500713/206887096-93a28c79-c9f4-4443-a528-b056a897f849.png)

I haven't tried to flash ELRS on Linux at all, so don't know what the exact requirements are there (permissions, dependencies, etc), but on Windows 11, with a Jumper T-Lite V2 running v2.8.0 I was able to update to ELRS v3.1.1
