### ISSUE TITLE
Special characters umlauts DE - German missing

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#2838]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Umlauts for Ä, ä, Ö, ö, Ü, ü are missing again with EdgeTX v 2.8.0
![Sonderzeichen DEUTSCH_EdgeTX_v2 8 0](https://user-images.githubusercontent.com/92114465/206693701-d01a8f7d-e0c2-4354-9af0-5196b33e40c4.PNG)

### Expected Behavior

As with EdgeTX 2.7.0
![Sonderzeichen DEUTSCH_EdgeTX_v2 7 0](https://user-images.githubusercontent.com/92114465/206693922-32961979-1929-425d-90ac-eeea4867d4a8.PNG)

### Steps To Reproduce

Special characters are missing in LUA scripts.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by raphaelcoeffic** [comment]
@koaxheli you need to compile the german firmware to have these characters (`-DTRANSLATIONS=DE`).

**Comment by koaxheli** [comment]
I have made on
https://gitpod.io/#https://github.com/EdgeTX/edgetx/tree/2.8

cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DHELI=YES -DTRANSLATIONS=DE -DBLUETOOTH=YES -DINTERNAL_GPS=YES -DCMAKE_BUILD_TYPE=Release ../

**Comment by koaxheli** [comment]
But the umlauts will not be created as it was done with the first
version of EdgeTX 2.5.

**Comment by gagarinlg** [comment]
> I have made on https://gitpod.io/#https://github.com/EdgeTX/edgetx/tree/2.8
> 
> cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DHELI=YES -DTRANSLATIONS=DE -DBLUETOOTH=YES -DINTERNAL_GPS=YES -DCMAKE_BUILD_TYPE=Release ../

You have to use the correct unicode code points from 2.8 on

**Comment by gagarinlg** [comment]
The complete UI on the color LCD radios is now unicode, instead of the pita the old chracter encoding was. With future radios we will then be able to have multi language firmwares

**Comment by gagarinlg** [comment]
Did you try using utf-8?

**Comment by koaxheli** [comment]
Where and how to use the utf-8 special character set
is called.

**Comment by gagarinlg** [comment]
You can just use a modern editor, like notepad++, set it to utf-8 and then enter the umlauts.
This should just work

**Comment by koaxheli** [comment]
Thanks, for the tip with UTF-8 encoding has worked with the special characters.
