### ISSUE TITLE
EdgeTx 2.8 X9E firmware does not start

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#2855]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Taranis X9E with Hall Gimbal
download firmware x9e-hall-f6d140.bin
flashed in radio
after restart display remains white the only way to switch-off the radio is disconnect battery
second attempt 
self build firmware from 2.8 branch
behaviour remains the same

### Expected Behavior

normal radio start after flashing new firmware

### Steps To Reproduce

download firmware from edgetx web site

### Version

2.8.0

### Transmitter

FrSky X9E / X9E Hall

### Anything else?

compilation options
-DPCB=X9E -DDEFAULT_MODE=1 -DGVARS=YES -DSTICKS=HORUS -DPPM_UNIT=PERCENT_PREC1 -DHELI=NO -DLUA=YES -DTRANSLATIONS=IT -DCMAKE_BUILD_TYPE=Debug ../

**Comment by Gerold68** [comment]
I have no problems with all the 2.8 nighlies flashing via bootloader.

**Comment by MicheleVilla** [comment]
I have tried with all possibility (Bootloader flasher and buddy with official and nightly) Edgetx 2.7.1 and 2.8.0, EdgeTx and openTx bootloader
In every cases my X9e restart with a white screen
only OpenTx 2.3.15 run without problems
Where am I wrong?

On my other X9D edgetx it is happily working

**Comment by Gerold68** [comment]
At the beginning I had also a lot of trouble move from opentx to edgetx with my 9XE.
The conversion from the eeprom data (model and system bins) to model and system yml files went wrong.
The result was always a white screen.
Try to use the actual beta (2.9) , the conversion was removed.
Delete on you pc the model.yml in Models folder and the radio.yml in Radio radio folder of your sd-card.
The radio then comes up with the calibration screen. Finish the calibration and the radio is a fresh clean radio.

I still have trouble syncing with companion. If the radio.yml is synced with the radio, it ends up with the white screen.
If you work with the radio standalone. It works fine.

**Comment by MicheleVilla** [comment]
@Gerold68 
IT WORKS
Thankyou for your solution
at this point the problem is the conversion of the EEPROM
BUT I didn't understand, however, how to convert all the stored models without losing them

**Comment by pfeerick** [comment]
The safest way to do that would be to use OpenTX companion with OpenTX firmware on the radio, read the radio models and settings to an OTX file, and then use EdgeTX companion to write that to the radio once you reflash it with EdgeTX (assuming you didn't have any OTX backups saved already). 

It seems from Gerold68's comment above the `RADIO/radio.yml` file as written by EdgeTX companion seems to have some issue that locks up the radio - so ideally you would backup that file before letting companion write to the radio, and then copy back the backup file once companion has done its work. It would probably be a good idea to get a copy of the before and after of those files to us as well (actually, probably both the RADIO and MODELS folders before and after, zipped up) to see if we can identify what is going on there.

**Comment by MicheleVilla** [comment]
[Files.zip](https://github.com/EdgeTX/edgetx/files/10302649/Files.zip)
in files.zip all files captured before and after upgrade
in files_descriptions.txt the mean of every file
I hope this help

Thank you

**Comment by MicheleVilla** [comment]
before upgrade to edgetx I upload radio and models by companion openTx 3,3,15
once upgraded to Edgetx I have open file otx with companion EdgeTx 2.9 nightly and subsequently downloaded to the radio by USB connection
The result are the same : white screen
the only way to get the radio working again is delete all yml file and make again the calibration
at this point I have to re-enter all the models by hand
All radio and models data are stored only in yml files?
it is possible to choose whether to save also in EEPROM?
How it works?
Thank you

**Comment by Gerold68** [comment]
Ciao Michele,
today i tried a lot of import tests. Importing models from X16S (2.9) to X9E (2.9) with companion 2.9.
Nothing has worked. If I switch to an imported model, then the radio boots into the previous model.
Same import method has worked with my Zorro. It seems to be a rare X9E problem and we are just a view X9E users :-(
I have not given up yet :-) I'm trying to find out which content of the yml model file are causing the crash.
Regards
Gerold

**Comment by MicheleVilla** [comment]
Hi Gerold
Happy new year
a modify in yml file need a checksum recalculation
How test it?
In my radio is configured multipos switch and it's calibration in (wrong)radio.yml is
  POT3:
    mid: 3077
    spanNeg: 9500
    spanPos: 24373
is correct?
is very different than other

**Comment by pfeerick** [comment]
> a modify in yml file need a checksum recalculation

This is what the second option, `manuallyEdited: 0` is for - set it to `1` if you manually edit the file. Checksum check will be skipped, and new checksum generated ;)

**Comment by MicheleVilla** [comment]
Thank you Pfeerick
take the opportunity for another question
in companion if I choose save in yml format pupup is closed without error but no files are saved
I'm on Linux mint

**Comment by pfeerick** [comment]
You might need to add `.yml` to the filename when saving... there is a bugfix for that for 2.8.1 Companion, but it might be MacOS only... not sure now.

**Comment by pfeerick** [comment]
It's usually a bit slow to start, especially with more files to load/check if they exist (i.e. all the sound files, lots of models, etc).

**Comment by MicheleVilla** [comment]
> You might need to add `.yml` to the filename when saving... there is a bugfix for that for 2.8.1 Companion, but it might be MacOS only... not sure now.
when saving form is open and you choose yml format  .yml is added automatically to filename

**Comment by Gerold68** [comment]
Hello guys,

I have made some progress investigating #2950 (https://github.com/EdgeTX/edgetx/issues/2950) but posting here. Hope pfeerick monitors this issue here.

I have modified and compared model yml files until the radio stuck during boot or reboots with the previous model.
Is seems that parameter "switchWarningState:" triggers the issue.
If "switchWarningState:"  is not "" e.g. AuB-CuDuEuFuGu then the loading of the model fails. If the model is the active model then the boot fails.

All my transfered models from TX16S are now working properly after I have set "switchWarningState:" to "".
On the TX16S switchWarningState: AuB-CuDuEuFuGu is no issue.

Regards
Gerold

**Comment by MicheleVilla** [comment]
Great job Gerold68
In my  model.yml
switchwarningstate is 
IuJuKuLuMuNuOuPuQuRu 
different in some models, but in all cases switch are not installed
delete in all yml that parameter radio show an error but at restart all model are present 
I will check every models, for the moment only name is missing
i confirm the problem is SwitchWarningState wrong file are in my recent post

**Comment by Lionheart113** [comment]
is there a solution to reboot after updating firmware to 2.8 on x9e????

**Comment by Gerold68** [comment]
Hello,
depends of what you did before the crash has happened. Try this:
- Open the radio and pull the battery plug
- take the sd card and delete the radio and model yml files on your pc.
- put sd card back
- connect battery again
- Push power button and follow the instruction to calibrate the sticks and all pods.
If you set the above mentioned switchWarningState with the radio or companion, the radio will stuck again.

**Comment by Lionheart113** [comment]
It's working but all of my models and settings are gone and I can't install them again only manual via radio 😳🤔

**Comment by Gerold68** [comment]
You can work with companion but ensure that  
![grafik](https://user-images.githubusercontent.com/46866517/211163933-3d7eec30-6ee5-4a16-8e8d-1cba821492ca.png)
all are off.
Existing modelxx.yml can be modified so that switchWarningState: ""

**Comment by MicheleVilla** [comment]
Every time I change (from the radio menu) the switch alarm the radio freezes
then I have to manually change the switchWarningState parameter in the SD to make the radio operational again
this happens with a newly created model
I hope the problem gets fixed  or at least understand what is wrong with my installation

**Comment by pfeerick** [comment]
Probably related issue : #3107
