### ISSUE TITLE
EL18 cannot achieve 5.25M BAUD for CRSF

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#2861]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Can only achieve 1.87M BAUD, error occurs when trying to use 3.75M BAUD or 5.25M BAUD.

### Expected Behavior

Hardware is similar to TX16S, both uses USART2, it should works the same way as TX16S

### Steps To Reproduce

1. External Module
2. Select CRSF
3. Select BAUD to 3.75M BAUD or 5.35M BAUD
4. ELRS will report connection problem.

### Version

2.8.0

### Transmitter

Flysky EL18

**Comment by richardclli** [comment]
I think it is because it uses its own telemetry driver, should unify to horus driver to support same features.  Will work out a PR soon.

**Comment by richardclli** [comment]
@pfeerick I think this need to be fixed in 2.8.1

**Comment by richardclli** [comment]
I will work out another PR forv2.8 branch

**Comment by richardclli** [comment]
Added a PR for branch 2.8

**Comment by richardclli** [comment]
@pfeerick I think this can be closed, as the new serial driver solves this problem in main and 2.8 already has the fix applied.

**Comment by pfeerick** [comment]
Ah yes, thanks... yeah, the PR got close since the serial driver changes superceeded it.
