### ISSUE TITLE
Support Flysky FRM303

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#2863]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

FRM303 is currently not working in any radios, seems the drivers are not properly configured.

FRM303 used the same protocol as the IRM301 in the EL18 with the following information:
1. Radio TX used the PPM pin
2. Radio RX used the heartbeat pin
3. UART bit rate is 1.5M BAUD
4. Signaling is non-inverted (Idle high)

I think supporting this should be easy, just tweaks a bit on the init and config.

### Describe the solution you'd like

Please update the init and config for AFHDS3 ext module to support it properly.

**Comment by richardclli** [comment]
@pfeerick See if this can put to 2.8.1

**Comment by pfeerick** [comment]
I would prefer 2.9, although since this primarily only affects the AFHDS3 driver even if there is a bug/regression here, it will have limited impact?

Were you able to test this on any other radios than the EL18/NV14 to see if it works anywhere else?

**Comment by rotorman** [comment]
Also interesting to know would be if FRM302 still functions or not (I do not have it to test it myself).

**Comment by richardclli** [comment]
> Also interesting to know would be if FRM302 still functions or not (I do not have FMR302 to test it myself).

No, Raphael replaced the FRM302 code completely because FRM302 uses the old protocol that the state machine is completely different.

However, for best compatibility, I think it may worth to pull back the old code and make FRM302 works again.  And we may need to think how to organize all these Flysky modules:

FRM302: old protocol
IRM303 (EL18): new protocol with module ID = 0x05
FRM303: new protocol with module ID = 0x04

So for completeness, AFHDS3 should provides 3 sub-protocols: FRM302, IRM3003, FRM303

**Comment by richardclli** [comment]
> I would prefer 2.9, although since this primarily only affects the AFHDS3 driver even if there is a bug/regression here, it will have limited impact?
> 
> Were you able to test this on any other radios than the EL18/NV14 to see if it works anywhere else?

FRM303 can only works with Flysky radios because of current hardware limitation and FRM303 firmware support.

In details, besides  generic protocols PPM and SBUS, FRM303 supports opensource UART protocol with 1.5M and 115.2k BAUD.  And the signal is "non inverted".  The serial port connection uses the PPM and heartbeat line in the external module header.

And that is why the X10 PCB series radio, with heartbeat line hardware bug and forced inverted signal may not work with current FRM303 firmware.

I already asked Flysky to add another choice in FRM303 protocol that can make use the S.PORT line to communicate in half duplex just like ELRS did.  Before this, I think it will be hard to get FRM303 supported in other non-Flysky radios.

**Comment by richardclli** [comment]
And I have already tested the FRM303 works in NV14/EL18 and PL18.

**Comment by richardclli** [comment]
TX16S with ACCESS mod (diode fixed) tested using FRM303 115.2k BAUD opensource protocol option, not working properly.

**Comment by rotorman** [comment]
Could you check with a logic analyzer or oscilloscope if the issue stems still from the signal on TX16S Heartbeat line, even after the diode mod, or from something else.

For this you could measure the RF_HB track:

![grafik](https://user-images.githubusercontent.com/21011587/211143877-127e8701-7b4e-4cce-9d65-0c23ecbcc642.png)

RF_HB track highlighted here (top layer of TX16S mainboard):

![grafik](https://user-images.githubusercontent.com/21011587/211143954-71638a5a-0a4c-4f5c-bc6d-a0b414441aae.png)

**Comment by richardclli** [comment]
TX16S Int module chained a 2.2k resistor to the Heartbeat pin.  Well, I think better wait for FRM303 firmware update before working out TX16S support.

**Comment by richardclli** [comment]
@pfeerick I have made another PR for 2.8 branch as well.

**Comment by xiaoyigg** [comment]
I want use radiomaster boxer with frm303
that's ok ?

**Comment by richardclli** [comment]
> I want use radiomaster boxer with frm303 that's ok ?

Not supported yet.  Need firmware update in FRM303, or hardware mod.

**Comment by Kai2510** [comment]
> > Also interesting to know would be if FRM302 still functions or not (I do not have FMR302 to test it myself).
> 
> No, Raphael replaced the FRM302 code completely because FRM302 uses the old protocol that the state machine is completely different.
> 
> However, for best compatibility, I think it may worth to pull back the old code and make FRM302 works again. And we may need to think how to organize all these Flysky modules:
> 
> FRM302: old protocol IRM301 (EL18): new protocol with module ID = 0x05 FRM303: new protocol with module ID = 0x04
> 
> So for completeness, AFHDS3 should provides 3 sub-protocols: FRM302, IRM301, FRM303

It would be better if FRM302 can be driven again, and there's an option to select different protocols. OpenTX 2.3.10 supported FRM302, but sadly now it's removed. Could you further explain the reason, the state machine...?

**Comment by richardclli** [comment]
> > > Also interesting to know would be if FRM302 still functions or not (I do not have FMR302 to test it myself).
> > 
> > 
> > No, Raphael replaced the FRM302 code completely because FRM302 uses the old protocol that the state machine is completely different.
> > However, for best compatibility, I think it may worth to pull back the old code and make FRM302 works again. And we may need to think how to organize all these Flysky modules:
> > FRM302: old protocol IRM301 (EL18): new protocol with module ID = 0x05 FRM303: new protocol with module ID = 0x04
> > So for completeness, AFHDS3 should provides 3 sub-protocols: FRM302, IRM301, FRM303
> 
> It would be better if FRM302 can be driven again, and there's an option to select different protocols. OpenTX 2.3.14 supported FRM302, but sadly now it's removed. Could you further explain the reason, the state machine...?

It is always possible if anyone want to code this, but since FRM302 is already discontinued and it can never supports ibus2, so it is out of my interest.
