### ISSUE TITLE
Tx16s: Potis missing in global functions (S1/S2)

### ISSUE THREAD

**Issue by Betriebsrat** [EdgeTX/edgetx#288]
**Is your feature request related to a problem? Please describe.**
Tried to bind the volume to S1 or S2 on global functions. S1 and S2 are not selectable

**Describe the solution you'd like**
S1 and S2 added

**Comment by raphaelcoeffic** [comment]
@Betriebsrat Can you please state which exact version you tested on please?

**Comment by Betriebsrat** [comment]
Aww forgot the most important part sorry....
It was branch 2.4 (non-rc) via flasher tool.

**Comment by Betriebsrat** [comment]
2.4.0 (78a0a457)
2021-06-20
18:15:08

**Comment by pfeerick** [comment]
Just double checking this... 'value', not the 'switch' that you set the pots on... and I can still set them (as the value, not the switch) with RC2 on TX16S

![image](https://user-images.githubusercontent.com/5500713/122743054-f70cc200-d2c9-11eb-8bbf-c6a7a1f50ddd.png)

**Comment by Betriebsrat** [comment]
user error in my part sorry.

**Comment by pfeerick** [comment]
All good... I won't mention the number of times I've complained to Raphael about something and he said I was doing it wrong! :rofl:
