### ISSUE TITLE
EdgeTX: Emergency Lock after long-press model mainscreen

### ISSUE THREAD

**Issue by ReneNwnhs** [EdgeTX/edgetx#2880]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In Companion i setup a new heli-model, without a main screen and saved it to the TX. In the TX i selected the model and long-pressed the (empty) main screen. The "Emergency Lock" appeared and all i could do was turning the TX off. I know it does not affect the flying mode but only the maintenance interface. A "loose end" maybe?

Regards,

René

### Expected Behavior

An error-message or opening the model setup.

### Steps To Reproduce

Create a model without a mainscreen.
Select it in the TX
Longpress the mainscreen.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by gagarinlg** [comment]
I can confirm this, when all screens are removed from the xaml file, a long press on the main screen crashes the radio
