### ISSUE TITLE
Ability to invert EXT pots

### ISSUE THREAD

**Issue by JenusL** [EdgeTX/edgetx#2888]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When using a 3-axis stick, like the FrSKY 3-axis Gimbal , on RadioMaster TX16 and plug it in to SI (EXT1 in EdgeTX) the rotation direction is reversed to what one would expect. Since this is an hall-effect pot, the wires can't be reversed.
This can of course be compensated for in Mixer or Output of the models, but I would like it to be reversed at the hardware level so that calibration and vertical sliders are moving in the correct direction as well.

### Describe the solution you'd like

Ability to individually invert the EXT1 and EXT2 pots in the Hardware menu.

**Comment by raphaelcoeffic** [comment]
Implemented by #3870
