### ISSUE TITLE
Companion "File/Download Components" fails

### ISSUE THREAD

**Issue by Gerd-St** [EdgeTX/edgetx#2918]
I just installed the final Companion 2.8 to my Ubuntu 22.04.1 system and also updated my X-Lite Pro radio.
When I tried the function "File/Download Components" I get error messages, see screnshots.

![Bildschirmfoto vom 2022-11-27 15-17-34](https://user-images.githubusercontent.com/56171110/204140430-b768f43e-8ad9-4545-9fa3-3fee9f08d9dc.png)
![Bildschirmfoto vom 2022-11-27 15-38-42](https://user-images.githubusercontent.com/56171110/204141115-3989c806-05fb-4ce3-8f5d-83866ca5e0c1.png)

**Comment by elecpower** [comment]
Should be fixed in 2.9
