### ISSUE TITLE
2.8 Companion Update Keeps Looking for (MacOS Companion) on Windows Machine

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#2923]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Companion 2.8 Update Button yields error "No assets found in release 'EdgeTX "Black Pearl" v2.7.2 (MacOS Companion)' using filter '^edgetx-cpn-win64'

This is on a Windows machine. Update settings for Companion shows "Current Release: EdgeTX "FlyingDutchman" v.2.8.0

Curious where the MacOS is coming from and what is v2.7.2

I have "cleared" the current release--error repeats.

### Expected Behavior

With an empty updates folder, I would expect the update button in Companion to pull down the latest release of everything--at least to match the filter.

### Steps To Reproduce

Update Settings
Clear All "Current Release" fields.
Set any update path.
Close settings.
Hit update icon.
Error

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![macos companion](https://user-images.githubusercontent.com/378637/209041968-2645224e-4e07-42cf-a3e3-44e575ee5481.jpg)
![update](https://user-images.githubusercontent.com/378637/209041980-63d43e02-1943-46ee-9b40-c6c64b857f23.jpg)
![settings](https://user-images.githubusercontent.com/378637/209041989-8a13a62b-3903-477f-8e7e-971039e535eb.jpg)

**Comment by elecpower** [comment]
Fixed in https://github.com/EdgeTX/edgetx/pull/2823
