### ISSUE TITLE
Screenshot previews does not display correctly

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#293]
**Describe the bug**
Screenshot previews does not display correctly. The image is correct, just not displayed correctly.

**To Reproduce**
Make a screenshot. Go to SYS > SD Card > Screenshots > view a screenshot

**Expected behavior**
Expecting the screenshot preview to look like the actual screenshot

**Screenshots**
Screenshot of the screenshot preview
![screen-2021-06-22-154804](https://user-images.githubusercontent.com/485436/122773333-91f4a480-d2a8-11eb-807a-e0995d0d2d26.jpg)
The actual screenshot shown in the preview
![screen-2021-06-22-154038](https://user-images.githubusercontent.com/485436/122773341-9456fe80-d2a8-11eb-9155-f9bab539b1e7.jpg)

**General information**
 - EdgeTX version (2.4.0-RC2r)
 - Hardware (RM TX16S)

**Comment by raphaelcoeffic** [comment]
@NemesisXB probably another surprise for using the newest Stb lib.... I would love to drop BMPs as well, and use PNGs (if the compression code fits).

**Comment by NemesisXB** [comment]
> @NemesisXB probably another surprise for using the newest Stb lib.... I would love to drop BMPs as well, and use PNGs (if the compression code fits).

It is obviously low priority. just thought I would create the issue so it is at least logged somewhere. And PNG would be awesome. I couldn't even load the screenshot directly onto gihub because github does not support BMP, had to convert it first.

**Comment by pfeerick** [comment]
> I couldn't even load the screenshot directly onto gihub because github does not support BMP, had to convert it first.

Indeed... it's annoying that you can't drag and drop the files into an issue... Have to keep opening in gimp so I can copy 'n paste... :-/

And yes, I have the reddish screenshot previews also, just hadn't gotten around to lodging an issue.

**Comment by LimitlessGreen** [comment]
I suggest imagemagic. It's an oneliner: `convert a.ext1 b.ext2`
If you really want to drop a BMP here, just zip it. :-)
