### ISSUE TITLE
In Companion, when saving back to the Tx, there is no indication that anything is happening until it completes.

### ISSUE THREAD

**Issue by dismaldunc** [EdgeTX/edgetx#2932]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

when saving models back to the radio in companion (even tho my pc is quite quick and i have a sandisk SD card in the radio)

There is no indication that it is happening until the "finished " dialog pops up.

I have unplugged my radio prematurely after leaving the room and thought it had finished

### Describe the solution you'd like

I would like a dialog box with "file copy in progress" to display whilst saving.

This is really a VERY minor issue, just a nice to have really!

**Comment by pfeerick** [comment]
Indeed... either just a static dialog _"I'M BUSY!"_, or maybe even a progress bar since it could be informed by each of the model files having been written would be nice.
