### ISSUE TITLE
SerialPort Config in X10SExpress

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#2933]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

I'm not sure what exactly would be correct here. But between the old X10 and the X10-Express there is the difference that the serial port for the configuration is displayed differently:
X10:
![x10](https://user-images.githubusercontent.com/15068446/209325581-cda315de-7847-425f-968e-3a19ba41a85d.jpg)

X10Express:
![x10Express](https://user-images.githubusercontent.com/15068446/209325595-871ba263-2fb5-4d8c-a06d-7515a99b59f9.jpg)

### Expected Behavior

If it is correct that no configuration can be done on the X10Express, then the headline itself should be hidden.
Otherwise, should be made accessible to configuration

### Steps To Reproduce

Open Hardwaresettings on X10 and X10Express and compare

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 / X10S (ACCST), FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

nightly 2.9.0

**Comment by donkeydog67** [comment]
Is this a bug? I also have the same issue. Does X10S Express handle it internally? I have no idea

**Comment by donkeydog67** [comment]
Does X10S Express handle it internally? Did someone fix the issue?

**Comment by donkeydog67** [comment]
Is this bug solved or stil exist?

**Comment by brainbubblersbest** [comment]
The serial is used for the express/externalaccess Functionality.
On X10Express Radios straight from Factory.
On that Radio you cant unwire the serial.
But it would make sense to use the serial by connecting Hardware in the HF Bay. 😄

**Comment by raphaelcoeffic** [comment]
I believe there should be at least `USB-VCP` as an additional line there, but maybe this is a glitch in the simulation.

**Comment by ParkerEde** [comment]
> I believe there should be at least `USB-VCP` as an additional line there, but maybe this is a glitch in the simulation.

yes that's right. On the real radio, there is "USB-VCP"

**Comment by ParkerEde** [comment]
USB-VCP is now in Simu. So we can close here
