### ISSUE TITLE
SD Card Browser - implement Paste within same folder (duplicate)

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#294]
Copy paste doesn't work - *within the same folder as the source*

**General information**
 - EdgeTX version 2.4.0 RC2
  - TX16S

**Comment by raphaelcoeffic** [comment]
> Copy paste doesn't work
> 
> **General information**
> 
> * EdgeTX version 2.4.0 RC2
> * TX16S

It works for me, do you have a specific example? Please note that the pasted file is displayed at the end of the list (no sorting).

**Comment by pfeerick** [comment]
Anything further on this, or has this been and gone?
