### ISSUE TITLE
RADIO - GLOBAL VARIABLES bugs

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#295]
1. GV name not visible when GV was at least once active
![screen-2021-06-21-164830](https://user-images.githubusercontent.com/46420768/122797789-24ed0900-d2c0-11eb-86ac-165a6806c975.png)

2. No "Override' function in Func list

3. After 'Clear' command issued from pop-up background and '---' still visible.
It goes away once 'Edit' and RTN or user goes to other tab then returns to Global Variables TAB
![screen-2021-06-21-170902](https://user-images.githubusercontent.com/46420768/122798111-801efb80-d2c0-11eb-8191-df69d8a42bcb.png)

 
**General information**
 - EdgeTX version 2.4.0 RC2
  - TX16S

**Comment by raphaelcoeffic** [comment]
> No "Override' function in Func list

I think this is intentional. The "Override" function has always been considered "harmful". But let's see, could be just a compilation option (I think it is).

**Comment by JimB40** [comment]
I know tt is is compilation option 'nooverridech' 
But then if you compiled with this why there is 'Override' function in MODEL -> SPECIAL FUNCTIONS and there is no in RADIO -> GLOBAL FUNCTIONS

**Comment by raphaelcoeffic** [comment]
> I know. It is is Companion/compilation option 'nooverridech'
> But then if you compiled with this why there is 'Override' function in MODEL -> SPECIAL FUNCTIONS and there is no in RADIO -> GLOBAL FUNCTIONS

Now I see. This is again intentional, because global functions are more related to "radio", and thus Override is allowed only model functions.

**Comment by raphaelcoeffic** [comment]
@JimB40 and it seems to be the title color has already been fixed (I use 2.4 HEAD, and the title is visible, not like in your screenshot).

**Comment by JimB40** [comment]
testing 68cb9c2
still exist.
1. GV name disappear in edit mode if GV was active then deactivated (test with Toggle switch)
3. Same empty leftover after Clear command.

**Comment by raphaelcoeffic** [comment]
> testing [68cb9c2](https://github.com/EdgeTX/edgetx/commit/68cb9c2d92cb6bfefb79dd8f2395a0e6b0562006)
> still exist.
> 
> 1. GV name disappear in edit mode if GV was active then deactivated (test with Toggle switch)
> 2. Same empty leftover after Clear command.

Can we make a new one, that was quite a package.
