### ISSUE TITLE
EM when 'Telem Mirror' selected

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#296]
1. Go to RADIO -> HARDWARE
2. Select 'Telem Mirror' in either Serial Port or Serial Port 2

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by raphaelcoeffic** [comment]
@JimB40 I will need some more details. For now I cannot reproduce.

Here is what I tried:
- external module OFF: all settings for Serial/Serial2
- external module ON (CRSF): all settings for Serial/Serial2

So far, not crash, reboot, EM or anything like that.

**Comment by raphaelcoeffic** [comment]
Fixed by 53261ad067e6f7 & c2908e67d236f565faa2

**Comment by JimB40** [comment]
Still EM in 1e73101a.
When 'Telem Mirror' selected in both serials

**Comment by JimB40** [comment]
Okay tested with latest 68cb9c2. seems to be gone. don't re-open
