### ISSUE TITLE
full screen widget lost 13% area to spaces

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#2961]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

the full screen widget have unneeded spaces around it, 
when they are not needed
I think it is the decision of the widget developer if a spaces are needed, and how match of the them

![image](https://user-images.githubusercontent.com/7026911/210097284-0ac6a5ed-d12e-4de3-bdac-891ecb8005f3.png)

### Expected Behavior

as it was in 2.7
the widget should be allow to consume 100% of the available screen (480x227)

![image](https://user-images.githubusercontent.com/7026911/210097367-bfe8cbfd-8440-4499-9fa6-449e926f174f.png)

### Steps To Reproduce

create a widget that need the 480x227 pixels and try to display it without cuts

### Version

2.8.0

### Transmitter

FrSky X10 / X10S (ACCST), FrSky X10 Express / X10S Express (ACCESS), FrSky X12, Jumper T18, Radiomaster TX16S / TX16SMK2

**Comment by offer-shmuely** [comment]
this calculation show a 13% of screen space lost for spaces

![image](https://user-images.githubusercontent.com/7026911/210097741-a71fd884-d357-427d-87b2-f17bc89ef3f1.png)

**Comment by philmoz** [comment]
I suspect the problem is in line 122 of layout_factory_impl.cpp
      if (decorationSettings & 0x7) {
should be
      if (decorationSettings & 0xE) {
