### ISSUE TITLE
Special Function "SD Logs" time value 0.0 does not create any log entries.

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#2965]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When configuring the "SD Logs" special function, the "Value" option, when left at 0.0s will not create any log file.  Only when configured at 0.1 or above will it create a log file. I think that this is misleading - 0.0s I would interpret as continuous.

Additionally, the label "Value" is a very poor secription of this options.. maybe switch to something more descriptive like "frequency".

Tested in both v2.8 and 30.12.2022 nightly build

### Expected Behavior

I would expect that either the configurable "value" options are 0.1 and higher, or 0.0 is continuous logging. 

### Steps To Reproduce

Configure special function for SD Logs
set "value" to 0.0.
Trigger switch to active the special function
look at your logs and see no log file is produced.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by offer-shmuely** [comment]
Interval is more appropriate here
