### ISSUE TITLE
[Solved] RadioMaster TX12 MkII Companion connection problem

### ISSUE THREAD

**Issue by hdlbq** [EdgeTX/edgetx#2968]
Hi,
I start my TX12 in Bootloader mode 2.8.0.
I connect the USB cable to the TX12 and the PC, and the TX12 displays : USB Connected.
EdgeTX Companion displays the "Unable to find Radio SD Card" as soon as I try any of the actions of the Read/Write Menu.

The problem remains after installing the universal driver replacement software Zadig.exe from https://zadig.akeo.ie/, as specified in the TX12 User's manual.

I'm pretty sure that the cable is a "good" one, since Windows shows a "RadioMaster TX12 Bootloader device"

Software Versions:

    Edge Companion 2.8.0 on Windows 10
    TX12 Bootloader 2.8.0
    Thanks for your help.

### Expected Behavior

I expect to be able to backup my TX12 contents

### Steps To Reproduce

As explained above, I start my TX12 in Bootloader mode 2.8.0.
I connect the USB cable to the TX12 and the PC, and the TX12 displays : USB Connected.
EdgeTX Companion displays the "Unable to find Radio SD Card" as soon as I try any of the actions of the Read/Write Menu.

### Version

2.8.0

### Transmitter

RadioMaster TX12 / TX12MK2

### Problem was due to the installation of the Zadig drivers
Issue can be closed

**Comment by pfeerick** [comment]
Fantastic. Glad you got it working :)
