### ISSUE TITLE
RADIO HARDWARE missing TopBar text

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#297]
Goto RADIO -> HARDWARE

1. Press Analogs
![screen-2021-06-21-172213](https://user-images.githubusercontent.com/46420768/122798713-2f5bd280-d2c1-11eb-812e-a6a252aa77b9.png)

Should display:
HARDWARE
Analog inputs test

2. Press Keys
![screen-2021-06-21-172736](https://user-images.githubusercontent.com/46420768/122798936-721daa80-d2c1-11eb-8c2d-b273570ccffb.png)

Should display:
HARDWARE
Keys & switches test

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by raphaelcoeffic** [comment]
At least someone is testing 🤓

**Comment by eshifri** [comment]
BTW, PGUP and PGDN sensors are swapped: when PGUP is pressed PGDN is set to 1.

**Comment by raphaelcoeffic** [comment]
Fixed by #305

**Comment by raphaelcoeffic** [comment]
> BTW, PGUP and PGDN sensors are swapped: when PGUP is pressed PGDN is set to 1.

I think this is correct, I just checked. It is however sometime a bit mind-boggling. To the right is considered "Down", which is why "PGDN" is "Next Page" (I think, at least).
