### ISSUE TITLE
RADIO VERSION keys stuck

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#298]
1. Go to RADIO VERSION
2. Touch the screen

PAGE>   PAGE<   &  EXIT doesn't work anymore

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by raphaelcoeffic** [comment]
Oh! 😳

**Comment by eshifri** [comment]
I cannot reproduce it: all buttons are working for me.

**Comment by raphaelcoeffic** [comment]
> I cannot reproduce it: all buttons are working for me.

Neither can I.

**Comment by pfeerick** [comment]
Sorry, I can't repo it either on RC2.

**Comment by raphaelcoeffic** [comment]
> Sorry, I can't repo it either on RC2. If you can't pin it down as consistently happening, or perhaps being related to touching a particular part of the screen implying there's a focus issue, this issue can probably be closed for now.

I can reproduce it. I’ll check what it does actually to the focus.

**Comment by pfeerick** [comment]
I've been able to repo this also - seems more prevalent on the Radio => Version screen, but I have also been able to repo it once on the hardware tab also. Seemed to be something to do with touching around the "VERSION" title bar, so maybe there's like a one pixel focus gap? 😆

**Comment by pfeerick** [comment]
I believe I found the trigger method for this... it's if you slide or swipe in the top bar.

**Comment by gagarinlg** [comment]
I can confirm this. It is also the same problem for all windows that use tabs-

**Comment by eshifri** [comment]
Interestingly enough touch buttons are still working.

**Comment by gagarinlg** [comment]
> Interestingly enough touch buttons are still working.


The slide event is not handled by the top bar. So what happens is that the degault window slide handler takes over and sets the focus to the top bar part of the tabs window. But the top bar does not handle the input key events, so the keys are essentially dead, until you press on an icon without sliding. Then everything is back to normal.
