### ISSUE TITLE
MODEL -> SETUP can't select proper channel range

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#299]
1. Go to MODEL -> SETUP

- [ ] 2. Select as External RF Mode: GHST 
2a. Select end channel in Channel Range lower then 8th
2b. Try to select 8th again.
Stuck at 7th as max channel

- [ ] 3. Select as External RF Mode: SBUS 
3a. Select end channel in Channel Range lower then 8th
3b. Try to select 8th again.
Stuck at 7th as max channel

- [ ] 4. Select as External RF Mode: CRSF 
End channel in Channel Range can't be selected
It keeps channel range selected in other mode.

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by raphaelcoeffic** [comment]
> 1. Go to MODEL -> SETUP
> 2. Select as External RF Mode: GHST
>    2a. Select end channel in Channel Range lower then 8th
>    2b. Try to select 8th again.
>    Stuck at 7th as max channel
> 3. Select as External RF Mode: SBUS
>    3a. Select end channel in Channel Range lower then 8th
>    3b. Try to select 8th again.
>    Stuck at 7th as max channel
> 4. Select as External RF Mode: CRSF
>    End channel in Channel Range can't be selected
>    It keeps channel range selected in other mode.
> 
> **General information**
> 
> * EdgeTX version 2.4.0 RC2
> * TX16S

I think they just fixed something like that in OTX. Should be easy to fix though.

**Comment by phileville** [comment]
Also, with the internal MPM, you cannot select a channel above 12.

**Comment by nm17** [comment]
@pfeerick @phileville can confirm this still happens on nightly, please look into it.

**Comment by pfeerick** [comment]
I can also confirm for CRSF (and GHOST IIRC) it's cosmetic as you can't change it from the model setup. But thank you for confirming it's still there.
