### ISSUE TITLE
System locked when RTC data is broken

### ISSUE THREAD

**Issue by padcom** [EdgeTX/edgetx#3005]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When the RTC data is broken, the transmitter will not turn on. The bootloader starts ok. No indication of the situation of broken RTC data.

### Expected Behavior

The transmitter turns on.

### Steps To Reproduce

1. Get a transmitter with broken RTC data
2. Turn the transmitter on
3. Observe it is locked

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

The problem is with `__mktime_internal` and its processing:

https://github.com/EdgeTX/edgetx/blob/1bffd260a029aab4d84c85d1699d4a9bf45a2d2a/radio/src/rtc.cpp#L396-L407

With broken data this loop never finishes.

**Comment by raphaelcoeffic** [comment]
We should probably add some unit tests for `gmktime` to test this properly with invalid values.

**Comment by padcom** [comment]
The idea behind this PR is to know when the problem occurs to help diagnose it - not to fix the underlying problem. It occurs rarely and at present finding out what happened is next to impossible for users without programming skills.

I presume there will be another PR, done by someone who has much deeper knowledge about the platform, that will try to address the root cause of the problem.
