### ISSUE TITLE
Copy-Paste buffer not cleared - EM !!!

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#301]
Pouwer up RADIO
1. Go to MODEL -> MIXES
2. Select line with data
3. Copy
4. Go to MODEL -> INPUTS
5. Press ENTER (Paste is shown even no input was copied)
6. Paste
Now different things happen including EM

**General information**
- EdgeTX version 2.4.0 RC2
- TX16S

**Comment by JimB40** [comment]
Still active 68cb9c2

**Comment by raphaelcoeffic** [comment]
> Still active [68cb9c2](https://github.com/EdgeTX/edgetx/commit/68cb9c2d92cb6bfefb79dd8f2395a0e6b0562006)

Between Mixers and Inputs? Really? I tried any combination. Or did you find another?

**Comment by pfeerick** [comment]
I think this is the wrong issue Jim ;)

**Comment by JimB40** [comment]
It is :) need video for proof?
This time copied line in INPUTS and pasted in MIXES -> EM

**Comment by pfeerick** [comment]
If you're still running RC2, yes, but if you run the latest nightly, which includes that commit it shouldn't. I can't reproduce it, as the paste option disappears as soon as you change from INPUT -> MIXES tab with either touch or page buttons.

**Comment by JimB40** [comment]
Okay took 5d9498e8 and it's gone.
I had no RC2 but the build from yesterday. Still thx for pointing
Then I change my test workflow to use only night builds. Otherwise it's waste of time for testing and issue submiting.
