### ISSUE TITLE
Change "Edit Labels" to "Assign Labels"

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3014]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Feature allows to assign label not edit. Editing labels is different feature.
![screenshot_tx16s_23-01-11_12-27-22](https://user-images.githubusercontent.com/46420768/211795806-2dc2762a-c4ad-4ad7-980c-52659a3dc2fd.png)

### Describe the solution you'd like

Change menu option from "Edit Labels" to "Assign Labels"

**Comment by gagarinlg** [comment]
It is not only assign, but also unassign, so if you want to make a change, it might be "change labels", but not "assign labels"
Maybe the native english speakers could offer their opinion?

**Comment by philmoz** [comment]
Label is a verb as well as a noun so perhaps using 'Label model' might work and is consistent with the options above it.
