### ISSUE TITLE
Select Model - name change

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3015]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

This screen now serves as set of features that allows different tasks (not only selecting)
Adding model, Selecting active model, Deleting model etc. 
So name doesn't reflect content.
![screenshot_tx16s_23-01-11_12-33-23](https://user-images.githubusercontent.com/46420768/211796793-74bcbe2e-40d4-4698-a70c-48a34d9d5e6a.png)
![screenshot_tx16s_23-01-11_12-37-46](https://user-images.githubusercontent.com/46420768/211796996-64241437-9610-493d-9749-6a2231c7ccff.png)

### Describe the solution you'd like

Change name from "Select Model" to "Models Manager"

**Comment by pfeerick** [comment]
"Models Manage", or "Manage Models"?

**Comment by JimB40** [comment]
Yep all of them will fit. "Configurator" is too long.
If not "Models Manager" I prefer "Manage Models"

**Comment by MicheleVilla** [comment]
the same question could be proposed for Radio Setting
It also contains tools like Spectrum analyzer and more that might deserve a separate section or a different name

**Comment by pfeerick** [comment]
The Tools tab is going to be split out to its own icon/section at some point.

**Comment by JimB40** [comment]
At last called "APPS" :)

**Comment by gagarinlg** [comment]
Do we need to make a poll to decide if this change is going to happen?

**Comment by JimB40** [comment]
@gagarinlg Don't think so. As much as I understand power of habits, generic name reflects better what's inside this module. 
Btw in computer apps what we see on topbar is "File' not 'Open file'.  In 3.0 UI there will be feature to create 'shortcuts' in quick menu so user will have possibilty to place 'Select model'. Still OS navigation tree names will remain generic.
