### ISSUE TITLE
Proper ACTIVE color in Inputs/Mixes lists style

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3021]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Active line background for Inputs and Mixes list has wrong style. 
![screenshot_tx16s_23-01-12_07-35-53](https://user-images.githubusercontent.com/46420768/211997253-cb2bd9d3-1ac0-4900-98f4-bc2b58becd45.png)

### Expected Behavior

Active line should have proper styling
Active line background - ACTIVE
Active line text - SECONDARY1
Active line frame
 - if not focused - SECONDARY 2
 - if focused - SECONDARY 1
 
 @raphaelcoeffic can you make this change guiding @philmoz about this style change. Where, how to

### Steps To Reproduce

-

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
Close per request
