### ISSUE TITLE
Logical switch issues with 'Edge' and 'Timer' functions.

### ISSUE THREAD

**Issue by philmoz** [EdgeTX/edgetx#3022]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The values set for V1 and V2 when using the 'Edge' and 'Timer' functions change after restarting or switching models.

Example - Edge function:
When creating a logical switch
![Screen Shot 2023-01-12 at 9 00 14 pm](https://user-images.githubusercontent.com/9474356/212038160-67417567-0fa9-488e-899f-2fc6f8339622.png)
After restart or model switch
![Screen Shot 2023-01-12 at 8 59 39 pm](https://user-images.githubusercontent.com/9474356/212038272-9be00cc0-8dc8-4397-a3cf-66269c082bef.png)

Example - Timer function:
When creating a logical switch
![Screen Shot 2023-01-12 at 9 00 43 pm](https://user-images.githubusercontent.com/9474356/212038366-cb173bff-82c6-4103-9871-1028dfbc87a4.png)
After restart or model switch
![Screen Shot 2023-01-12 at 9 01 50 pm](https://user-images.githubusercontent.com/9474356/212038400-6fd30962-7034-4b34-9705-006dab993658.png)

### Expected Behavior

V1 and V2 values should be unchanged after restart or model switch.

### Steps To Reproduce

1. Create a logical switch with the 'Edge' or 'Timer' function
2. Set V1 and/or V2 to MAX value
3. Restart or switch model (then switch back)
4. Observe changed values

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by JimB40** [comment]
Yep. There are bugs in code there. 
Now you recalled me I was struggling with remember when I was coding LUA app to move Logical switches
