### ISSUE TITLE
Companion does not save yml file 

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#3023]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Companion 2.8
When I try to save model and radio in yml format no file are generated
Tested with companion in Wondows 10 and Linux Mint 20
selected name for file is document1.yml 

### Expected Behavior

Generation of yml file 

### Steps To Reproduce

generate a new model
open menu save
select .yml file
name of file is document1.yml
save

no file are generated

### Version

2.8.0

**Comment by elecpower** [comment]
Saves for me on Win 10. Are you trying to save to local drive or remote location?

**Comment by MicheleVilla** [comment]
local drive
on desktop directory in both OS
windows 10 and linux mint are on different PC
can you suggest the right step for save file?

**Comment by elecpower** [comment]
Oops I missed the file extension you're trying to use. You should be saving using the default etx extension. yml is for saving single model files and not models and settings.

I need to check the code as to whether the option to save to yml should still be a choice, I suspect not.
