### ISSUE TITLE
edge tx2.8.0

### ISSUE THREAD

**Issue by seokmankim** [EdgeTX/edgetx#3034]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After a few days after the update, 1.sd card contents are deleted 2.Welcome sound does not play 3.elrs script deletion cause unknown

### Expected Behavior

What happens when the battery is fully charged for a long time?

### Steps To Reproduce

There is no special movement, and it is always used as a joystick for simulators.

### Version

2.8.0

### Transmitter

Jumper T-Pro

**Comment by gagarinlg** [comment]
Sounds like a broken SD card to me.
