### ISSUE TITLE
adcRead() location

### ISSUE THREAD

**Issue by JyeSmith** [EdgeTX/edgetx#304]
Looks like this commit reverted a PR to reduce jitter.  Is it worth a discussion to find another fix?

https://github.com/EdgeTX/edgetx/commit/f7d36cd6951637a3ddec27e44eaeea405b847d91

https://github.com/opentx/opentx/pull/8480

**Comment by raphaelcoeffic** [comment]
> Looks like this commit reverted a PR to reduce jitter. Is it worth a discussion to find another fix?
> 
> [f7d36cd](https://github.com/EdgeTX/edgetx/commit/f7d36cd6951637a3ddec27e44eaeea405b847d91)
> 
> [opentx/opentx#8480](https://github.com/opentx/opentx/pull/8480)

The point is: after migrating to FreeRTOS, we should be able to get guaranties that ISR is giving control directly to the mixer task, so that we should be able to kill all jitter, and thus continue starting the ADC from the mixer task. This should be a fixed delay then.
