### ISSUE TITLE
Edge parameter change after edit and exit. #3035

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#3048]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If in edge command you edit the delay time and exit with for instance [1.5:<<] the second parameter reverts to "39.5" [1.6:39.5]. You have to reselect the [<<] parameter before exiting or come back in and change back afterwards. It does work but it is strange that you have to revisit this and check that it has remained as set.

### Expected Behavior

Change the parameter selected in edge and expect no change to second parameter when exiting.

### Steps To Reproduce

in 2.9.0 nighltly but expect is also in be 2.8.0

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### Anything else?

14-01-23
![screen-2023-01-14-145244](https://user-images.githubusercontent.com/56512603/212576482-9ba78843-77bb-4cda-a740-2db932d0b5c2.png)
Before edit
![screen-2023-01-14-145316](https://user-images.githubusercontent.com/56512603/212576490-4b2bff29-425e-4fe0-b1de-f77df080afdb.png)
After editing (1.5 to 1.6 for example) and exiting "<<" changes to "39.5", surely should have remained "<<" and believe should not have to reselect or revisit and change after exit.

**Comment by philmoz** [comment]
I've created a PR to fix this - it might take a little while to get merged into the nightly build.

**Comment by Kevltan** [comment]
Thankyou 😊

**Comment by Kevltan** [comment]
Made edit to firmware as indicated rebuilt and tested and now works fine. Thanks Phil 👍
