### ISSUE TITLE
Crash to emergency mode when changing model while still connected.

### ISSUE THREAD

**Issue by philmoz** [EdgeTX/edgetx#3065]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If you try and change model while still connected to the receiver the radio opens the 'Model Still Powered' alert dialog; but then goes into an infinite loop playing the alert sound over and over.

The alert can't be dismissed and eventually the radio crashes into emergency mode.

### Expected Behavior

Should not crash.

### Steps To Reproduce

1. Power on and connect to a model.
2. Try and change model while still connected.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by Dronitoni** [comment]
I see the same with my new radio TX16s. Emergeny mode is showing up when I tap on the main screen and select the "manage models" icon. It's repeatable, I tried it several times.
Version 2.9.2
I flashed this file: tx16s-8faf131.bin
