### ISSUE TITLE
Display Real-time Value of Channel on OUTPUTs page

### ISSUE THREAD

**Issue by grepboy** [EdgeTX/edgetx#307]
On current build of OpenTX 2.3.11, the OUTPUTs page on theTX16S displays real-time the value of the highlighted channel.  
See example picture, output value is circled in Yellow.

Please include this feature in EdgeTX.

![unknown](https://user-images.githubusercontent.com/81554588/122869035-87560180-d2e0-11eb-8810-c055b8de7668.png)

**Comment by jmil-dev** [comment]
I'd add to this that because the new interface screen uses % values rather than uSec there's no way to know what the output values are limited between

**Comment by pfeerick** [comment]
Actually, there probably is, but it is still admittedly clunky. 
![image](https://user-images.githubusercontent.com/5500713/124402404-75aa3a80-dd73-11eb-82cf-dc4362052501.png)

**Comment by JimB40** [comment]
Let's bring it back.
It's real pain in the ass to setup properly Output not seeing actual micro secs value while changing outputs ends
Bottom Bar is right place for informations.

**Comment by raphaelcoeffic** [comment]
This can be implemented easily by integrating the different `ChannelBar` classes here:
https://github.com/EdgeTX/edgetx/blob/493c90d792f7815e89608fb65aa2d426e06485f8/radio/src/gui/colorlcd/channel_bar.h#L37-L48

**Comment by pfeerick** [comment]
I think #1664 does this, and better, as it shows multiple channels rather than just the highlighted one. An option to show just a highlighted channel's value may still get implemented in the future though.
