### ISSUE TITLE
Lua standalone scripts and error messages

### ISSUE THREAD

**Issue by jfrickmann** [EdgeTX/edgetx#308]
On COLORLCD, errors in standalone scripts are not handled right, and the error messages also do not look right on X9D. This was probably introduced by #285 and I am working to sort it out. So please assign this one to me!

**Comment by raphaelcoeffic** [comment]
> On COLORLCD, errors in standalone scripts are not handled right, and the error messages also do not look right on X9D. This was probably introduced by #285 and I am working to sort it out. So please assign this one to me!

With pleasure!

**Comment by jfrickmann** [comment]
This issue has been fixed in #285.
