### ISSUE TITLE
Curve Edit page / x-axis and y-axis values have different alignment

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3088]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Standard: all x-axis values are center aligned, y-axis values are left aligned. 
Custom: changeable x-axis values are left aligned, non-changeable x-axis values are center aligned, y-axis values are left aligned

![Standard](https://user-images.githubusercontent.com/5615068/214089190-10584d22-8fe4-4f54-9070-6035021fa205.JPG)
![Custom](https://user-images.githubusercontent.com/5615068/214089211-e6881100-6a40-47da-b4fd-5c1570ceaf13.JPG)

### Expected Behavior

all x/y values have the same alignment, e.g. left aligned.

### Steps To Reproduce

1. open Model Curve settings
2. add curve
3. observe different alignments
4. change to Custom curve
5. observe different alignments

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

present in current main

**Comment by philmoz** [comment]
Left aligned and center aligned examples below - which do you prefer?
(Note: it is not possible to perfectly align everything with center alignment.)

Left:
![Screen Shot 2023-01-24 at 8 14 12 am](https://user-images.githubusercontent.com/9474356/214151394-660752bf-4d78-4911-a662-45d30a7b9923.png)

Center:
![Screen Shot 2023-01-24 at 8 13 03 am](https://user-images.githubusercontent.com/9474356/214151428-d9aa84af-aa46-433a-a272-a149c3db09ce.png)

**Comment by mha1** [comment]
Thanks for looking into this. Centered looks good to me.
