### ISSUE TITLE
X-Lite Pro's S1/S2 have no responses in edgetx 2.8.0

### ISSUE THREAD

**Issue by kaji331** [EdgeTX/edgetx#3089]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

No signal responses in main screen, input/mix/output menu for S1/S2.

### Expected Behavior

In 2.4.0, I can use S1/S2 wheels for my X-Lite Pro.

### Steps To Reproduce

1. Completely replace your SD card's content with 2.8.0 bw 128x64 zip
2. copy xlites-f6d140e.bin to sd card's FIRMWARE directory
3. select the firmware in the transmitter for bootloader writing
4. press cross button and start transmitter, then write the firmware

### Version

2.8.0

### Transmitter

FrSky X-Lite / S / Pro

**Comment by pfeerick** [comment]
Have you tried calibrating them since they're an analog input? i.e. RADIO/SYS -> Hardware -> Calibration, centre them when centring the sticks, and then move them full range when moving the sticks.

**Comment by kaji331** [comment]
> Have you tried calibrating them since they're an analog input? i.e. RADIO/SYS -> Hardware -> Calibration, centre them when centring the sticks, and then move them full range when moving the sticks.

Thank you very much!

**Comment by Talha909** [comment]
> > Have you tried calibrating them since they're an analog input? i.e. RADIO/SYS -> Hardware -> Calibration, centre them when centring the sticks, and then move them full range when moving the sticks.
> 
> Thank you very much!

I have the same issue. did you find the solution. I already try the calibration screen. But nothing is now in calibration screen. Like there are alwasys two bars between the joystick but they are missing now.

**Comment by pfeerick** [comment]
> But nothing is now in calibration screen. Like there are alwasys two bars between the joystick but they are missing now.

With what firmware version?
