### ISSUE TITLE
From switch L on wards, settings are lost after reboot on X9E Hall radio

### ISSUE THREAD

**Issue by Bratski** [EdgeTX/edgetx#3107]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Activating the switches from "switch L" on wards, the settings are lost after rebooting the radio. 

### Expected Behavior

Not loosing these settings after reboot.

### Steps To Reproduce

System menu, hardware,
Activate switches from L on wards, changing settings from None to Toggle, 3Pos or 2Pos.
Turn off radio
Turn on radio
Settings lost, but just saved until "switch K"
  

### Version

2.8.0

### Transmitter

FrSky X9E / X9E Hall

**Comment by gagarinlg** [comment]
confirmed on a non hall X9E

**Comment by Gerold68** [comment]
Please take also a look into https://discord.com/channels/839849772864503828/1061346267646660768/1061346267646660768

I am quite sure that all these issues have the same root cause.

Regards
Gerold

**Comment by gagarinlg** [comment]
Thnks, i will do that. We specifically baought a used X9E (non hall) to have something to test with
