### ISSUE TITLE
Problem saving specials functions

### ISSUE THREAD

**Issue by kitsen13** [EdgeTX/edgetx#3131]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

In companion, specials functions  setting "Set Main Screen" are not saved.

On a line, declare a "Set Main Screen" to anything else than 1 for example '2', save , close model window .
Re-open model  window "Set Main Screen" remains to 1.

### Expected Behavior

Save value.

### Steps To Reproduce

On a line, declare a "Set Main Screen" to anything else than 1 for example '2', save , close model window .
Re-open model  window "Set Main Screen" remains to 1.

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by eshifri** [comment]
How many screens are defined for this model?

**Comment by elecpower** [comment]
@kitsen13 @eshifri confirmed as a bug. Wrong field being used for save.

**Comment by elecpower** [comment]
Correction not saved at all
