### ISSUE TITLE
Unable compile latest firmware in CZ language via Gitpod

### ISSUE THREAD

**Issue by japanel** [EdgeTX/edgetx#3145]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

When I try compile latest firmware in CZ language via Gitpod, it is end with error.
I am use https://gitpod.io/#https://github.com/edgetx/edgetx/tree/main.
Then I write:
1. cmake -Wno-dev -DTRANSLATIONS=CZ -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=1 -DGVARS=YES -DHELI=NO -DPPM_UNIT=US -DCMAKE_BUILD_TYPE=Release ../
2. make configure
3. make -C arm-none-eabi -j`nproc` firmware

After 90% of compiling stop and failed.

When tried "-DTRANSLATIONS=DE" firmware compilation was success (but I didnt tried flash to radio).

### Expected Behavior

Compile firmware without error.

### Steps To Reproduce

Try compile firmware in CZ language for TX16S via Gitpod.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![gitpoderror](https://user-images.githubusercontent.com/123984406/216779225-7d01dc74-ae2b-4dfe-b16b-3c4e584f2c5f.png)

**Comment by pfeerick** [comment]
Hm... there's a different code taken for three languages to re-order the words... given the first parameter is a const string that is probably the issue there. 
![image](https://user-images.githubusercontent.com/5500713/216793603-153c46cc-e1dd-4644-a136-70298867d111.png)

**Comment by japanel** [comment]
Thx, it is ok now.
