### ISSUE TITLE
Bad layout in telemetry options CZ language

### ISSUE THREAD

**Issue by japanel** [EdgeTX/edgetx#3153]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Uncomplete text in telemetry options. Missing characters. Text is too long for this layout.

### Expected Behavior

Change layout to see complete text.

### Steps To Reproduce

See page telemetry in CZ language firmware (TX16S).

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

![IMG_20230206_083209](https://user-images.githubusercontent.com/123984406/216911335-d09489e4-8725-446e-ad42-36020f62d4b6.jpg)

**Comment by Eldenroot** [comment]
It needs to be two pine text?
