### ISSUE TITLE
Edgetx touch screen does not work

### ISSUE THREAD

**Issue by Ale758122** [EdgeTX/edgetx#3158]
After updating to version 2.8 my touch screen works at times, as soon as I turn on the tx16s the touch works, but after a touch on the display it goes back to not working, it would be easier to send you a video to show you, how can I do it? With the keys everything works and does not crash, in version 2.7.1 I have not had any problems. Thanks

**Comment by Mike-i-b** [comment]
Touch screen stopped working on my tx16s too after 2.8 update. TX is new; only had it a couple of weeks. I don't think it worked at all after update - I've gone back to 2.7 so I can't experiment at present.

**Comment by gagarinlg** [comment]
> After updating to version 2.8 my touch screen works at times, as soon as I turn on the tx16s the touch works, but after a touch on the display it goes back to not working, it would be easier to send you a video to show you, how can I do it? With the keys everything works and does not crash, in version 2.7.1 I have not had any problems. Thanks

You could upload the video to YouTube and share a link

**Comment by Ale758122** [comment]
> > Dopo l'aggiornamento alla versione 2.8 il mio touch screen funziona a volte, appena accendo il tx16s il touch funziona, ma dopo un tocco sul display torna a non funzionare, sarebbe più semplice inviarti un video da mostrarti, come posso farlo? Con i tasti tutto funziona e non va in crash, nella versione 2.7.1 non ho avuto problemi. Grazie
> 
> Puoi caricare il video su YouTube e condividere un link

https://youtu.be/UOILRpCxb50

**Comment by gagarinlg** [comment]
I think I know what you did.
Take a look at the back light settings and set the mode to keys or both or on.

You have the back light brightness for back light on and off at the same level. When the back light is "off" the Touchscreen is disabled. Since the wakeup is set to only controls, touching screen does not wake up the radio.

**Comment by Ale758122** [comment]
No the lighting has nothing to do, the settings are the same, and after using the radio several times it seems to have unlocked itself, in fact the touch works now, but the first time I went out with my drone it had me a strange defect when switching from one drone model to another, namely a momentary block and then release of the voice and a slowdown in model change, now that you told me to check the display lighting, I turned on the radio and the touch works perfectly 🤷🏻‍♂️

**Comment by gagarinlg** [comment]
How large are the images you have for you drones? This can cause problems, when they ae not scaled down.

I am pretty sure, that the backlight mode is the problem. At least I could reproduce the exact same behavior by setting the backlight mode to "controls"

Can you please upload an archive with the images, models and radio folders? You can upload files by just dropping them here

**Comment by Mike-i-b** [comment]
I just re-flashed 2.8 - touch screen working ok now. Bad flash? User error? Who knows.

**Comment by Ale758122** [comment]
> Quanto sono grandi le immagini che avete per voi droni? Ciò può causare problemi, quando non vengono ridimensionati.
> 
> Sono abbastanza sicuro che la modalità di retroilluminazione sia il problema. Almeno potrei riprodurre lo stesso identico comportamento impostando la modalità di retroilluminazione su "controlli"
> 
> Puoi caricare un archivio con le immagini, i modelli e le cartelle radio? Puoi caricare i file semplicemente rilasciandoli qui

I resized the images and the resolution is the same as the other models, same thing on the splash screen images, if they are larger than the original they don't even appear on the display, and not even on the models, I flashed the firmware correctly, both on the Edge tx site via Buddy, and both on the program to install on windows 10 which does the same thing

**Comment by pfeerick** [comment]
> Please upload an archive with the images, models and radio folders? You can upload files by just dropping them here

If you do this, we'll be able to look at the settings and hopefully get a better understanding of what is going on. 

Touch can be disabled (by design, not a bug) by both a special function, and also disabled when the backlight mode is set to "Controls" rather than "Keys" or "Both", once the backlight timer has elapsed.

**Comment by Ale758122** [comment]
>

**Comment by Ale758122** [comment]
> > Si prega di caricare un archivio con le immagini, i modelli e le cartelle radio? Puoi caricare i file semplicemente rilasciandoli qui
> 
> Se lo fai, saremo in grado di esaminare le impostazioni e, si spera, ottenere una migliore comprensione di ciò che sta accadendo.
> 
> Il tocco può essere disabilitato (in base alla progettazione, non è un bug) da entrambe le funzioni speciali, e anche disabilitato quando la modalità di retroilluminazione è impostata su "Controlli" anziché "Tasti" o "Entrambi", una volta trascorso il timer di retroilluminazione.

![photo_2023-02-15_10-58-55](https://user-images.githubusercontent.com/124431116/218996501-29cc0455-ded0-4b18-ba8b-48b0d189c486.jpg)
![photo_2023-02-15_10-58-56](https://user-images.githubusercontent.com/124431116/218996506-6cf55f5e-8a63-4139-917b-9470a8568ce2.jpg)
![photo_2023-02-15_10-58-57](https://user-images.githubusercontent.com/124431116/218996510-812ed45b-c842-4935-a515-5fff31958140.jpg)
![photo_2023-02-15_10-58-58 (2)](https://user-images.githubusercontent.com/124431116/218996513-8e94fe37-58fb-4135-b80c-5a1fe9857806.jpg)
![photo_2023-02-15_10-58-58](https://user-images.githubusercontent.com/124431116/218996516-829dd4ed-eb4f-4a82-9489-0191e8b5a847.jpg)
![photo_2023-02-15_10-58-59](https://user-images.githubusercontent.com/124431116/218996517-289e667c-149f-4cd5-a581-4dfb1df48aca.jpg)
![photo_2023-02-15_10-59-00](https://user-images.githubusercontent.com/124431116/218996518-447aae6c-7452-4e57-a4b2-1841bf89f631.jpg)
![photo_2023-02-15_10-59-01](https://user-images.githubusercontent.com/124431116/218996521-e02e0b94-55ab-4222-8335-8b3236c8ac9d.jpg)

**Comment by Ale758122** [comment]
![Apex](https://user-images.githubusercontent.com/124431116/218998095-2ef58e02-cc03-4c73-94b4-79cf6bb88709.png)
![Libra v2](https://user-images.githubusercontent.com/124431116/218998104-6762d5d0-74c4-4a99-af97-eaed6da894a5.png)
![simulatore](https://user-images.githubusercontent.com/124431116/218998108-a3abce9e-a59e-4c4a-b396-a0391695ec6f.png)
![splash](https://user-images.githubusercontent.com/124431116/218998110-922dc72b-9a66-46e6-8f4b-203817a889c0.png)
![Squirt v2](https://user-images.githubusercontent.com/124431116/218998113-d780aafb-b424-46b1-bc1c-dcc4b41cb9bf.png)
![Tinyhawk2](https://user-images.githubusercontent.com/124431116/218998116-9dbb12ad-991a-4834-b275-62162648fc45.png)

**Comment by gagarinlg** [comment]
As I said, backlight us set to "controls"

**Comment by Ale758122** [comment]
> Come ho detto, la retroilluminazione ci imposta su "controlli"

it is already on controls

**Comment by gagarinlg** [comment]
yes, that is wrong. Set it to "keys", "both" or "ON", but NOT to "controls"

**Comment by gagarinlg** [comment]
> > > Si prega di caricare un archivio con le immagini, i modelli e le cartelle radio? Puoi caricare i file semplicemente rilasciandoli qui
> > 
> > 
> > Se lo fai, saremo in grado di esaminare le impostazioni e, si spera, ottenere una migliore comprensione di ciò che sta accadendo.
> > Il tocco può essere disabilitato (in base alla progettazione, non è un bug) da entrambe le funzioni speciali, e anche disabilitato quando la modalità di retroilluminazione è impostata su "Controlli" anziché "Tasti" o "Entrambi", una volta trascorso il timer di retroilluminazione.
> > as you see from the properties they are all resized, the splash is smaller than the templates and is the same size as the original splash
> > ![op](https://user-images.githubusercontent.com/124431116/218999452-02ba3e43-ef86-40ff-8c73-132df54a6b47.JPG)

Model images should have those dimensions: 192×114 px

**Comment by Ale758122** [comment]
ok i changed to "on" is that ok?
![photo_2023-02-15_11-28-38](https://user-images.githubusercontent.com/124431116/219002314-648df5b7-57e9-4cff-9d8c-2e00759d692e.jpg)

**Comment by gagarinlg** [comment]
> ok i changed to "on" is that ok? ![photo_2023-02-15_11-28-38](https://user-images.githubusercontent.com/124431116/219002314-648df5b7-57e9-4cff-9d8c-2e00759d692e.jpg)

yes, now the touch screen will work correctly, also with 2.8

**Comment by Ale758122** [comment]
> > ok ho cambiato in "on" va bene? ![photo_2023-02-15_11-28-38](https://user-images.githubusercontent.com/124431116/219002314-648df5b7-57e9-4cff-9d8c-2e00759d692e.jpg)
> 
> Sì, ora il touch screen funzionerà correttamente, anche con 2.8
ok for the moment thanks, I'll update you later, I go out almost every day with my drone, if any problems arise, I'll let you know immediately, even if I only use the touch when I set the power of the tx or if I change the model of drone, obviously not every day

**Comment by pfeerick** [comment]
You might want to read this later so you better understand what those (and other) options do ;)

https://edgetx.gitbook.io/edgetx-user-manual/edgetx-user-manual/user-manual-for-color-screen-radios/radio-settings/radio-setup/additional-radio-settings#backlight

**Comment by Ale758122** [comment]
> Potresti voler leggere questo più tardi in modo da capire meglio cosa fanno quelle (e altre) opzioni ;)
> 
> https://edgetx.gitbook.io/edgetx-user-manual/edgetx-user-manual/user-manual-for-color-screen-radios/radio-settings/radio-setup/additional-radio-settings#backlight

thanks for the explanation and thanks for the link, if I hadn't asked you for help, not even the Italian youtuber who makes tutorials and explanations knew anything about it, he wasn't able to help me and what's worse, he abandoned me without giving an answer, not knowing that I can't all things always go well and that some problems can always arise, he didn't even tell me to open a ticket on the Github site, I would have done it immediately, instead I went looking for Edge tx developers through the site! oh well useless people that goes on just to catch likes!

**Comment by pfeerick** [comment]
No problem at all. You can also get help via our Discord forum - linked on the front readme page - https://discord.gg/wF9wUKnZ6H
