### ISSUE TITLE
Error loading models in Companion 2.8 Mac

### ISSUE THREAD

**Issue by SirDrSpiderpig** [EdgeTX/edgetx#3167]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

I upgraded to firmware 2.8 on my radiomaster Zorro and then opened the 2.8 companion app.  I tried to read the model from the radio but got the error: "Cannot load Models/model01.yml: yaml-cpp: error at line 269, column 11: illegal map value"
![Screenshot 2023-02-09 at 7 07 11 PM](https://user-images.githubusercontent.com/70244153/217969034-2b30a68b-6e73-4f00-8e3b-df5a5d2c73d7.png)

I'm on macOS Ventura.

### Expected Behavior

I expected to be able to see my models and modify them.

### Steps To Reproduce

1. Turn on Zorro
2. Plug in usb-c cable to data jack
3. Open EdgeTX Companion 2.8 
4. Click "Read Models and Settings from Radio"
5. Error appears

### Version

2.8.0

### Transmitter

Radiomaster Zorro

**Comment by philmoz** [comment]
@SirDrSpiderpig Can you upload the problem model01.yml file here please.

**Comment by ThoFl** [comment]
I have the same error in the same situation on a radiomaster boxer.
Radio: 2.8.4
Companion: 2.8.4

Cannot load MODELS/model03.yml:
yaml-cpp: error at line 264, column 11: illegal map value

<img width="448" alt="Screenshot 2023-06-26 at 18 26 52" src="https://github.com/EdgeTX/edgetx/assets/121870889/7c0a6327-5d21-425b-9703-7599f5fea639">

Here a copy of the model:
[model03.yml.zip](https://github.com/EdgeTX/edgetx/files/11871568/model03.yml.zip)

**Comment by gagarinlg** [comment]
Can you please select the model on the radio, change a setting, change it back and try again from companion?
One of the models on the SD card is created with a pre-release Software.

**Comment by ThoFl** [comment]
I have in the mean time manually removed the model from the SD card and now it gets past the error.
Thanks for the support!

**Comment by mha1** [comment]
Your model03.yml file is corrupt as it has an illegal character in line 263 which is responsible for the radio or companion rejecting this model. I have no answer to the obvious question: why is it corrupt? Did you ever edit this .yml manually? 

![image](https://github.com/EdgeTX/edgetx/assets/5615068/bf9a6f09-8742-408f-99ee-25dd365848b7)

Here's a corrected version of your model file which hopefully will load normally.

[model03.zip](https://github.com/EdgeTX/edgetx/files/11872023/model03.zip)

**Comment by mha1** [comment]
You're welcome. Hope it worked,

**Comment by cengiztanc** [comment]
I am having this issue, sometimes just one model is affected, other times I have to manually erase almost all models off SD card before Edgetx Companion will successfully read models off radio. Thankfully I have a build backed up on laptop, which I then open in Companion and write to radio. After I fly I come back hook up and bam, models corrupted with little errors.
