### ISSUE TITLE
TX16s FRSKY X8R bind mode not retained

### ISSUE THREAD

**Issue by gysmitty** [EdgeTX/edgetx#3187]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After a successful bind to a Frsky X8R reciever in FrSky X2 mode and either power cycle the transmitter or switch to another model the transmitter reverts back to FrSky protocol and is no longer bound to this receiver.

If I open the transmitter in Companion make the change and send to the transmitter, the setting is retained properly.

The reciever has 2.0.0 firmware(X8R_ACCST_2.1.0_FCC) and the TX16S is running (edgetx-tx16s vers v2.8.0 "Flying Dutchman")

### Expected Behavior

The bind mode will be retained in the TX upon power cycle or model switch and the receiver would remain properly bound.

### Steps To Reproduce

1. Bind to X8R receiver in  FrSky X2 mode
2. Cycle power on transmitter and receiver
3. The receiver will no longer be bound and the roiginal bind mode reverts to "FrSky"

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by philmoz** [comment]
@gysmitty What is the receiver ID set to in the module setup?

I recall initially having this issue if the receiver ID was set to 0.

**Comment by gysmitty** [comment]
Hey, thanks so much for getting back to me.

I think that it was set to 0. I'll check tomorrow and update the issue if
so.

Geoff Smith

**Comment by raphaelcoeffic** [comment]
@philmoz could this simply be a missing “storage dirty” flag?

**Comment by aivisbush** [comment]
Hi! I have similar issue.
Device: tx16s
FW: EdgeTX "Flying Dutchman" v2.8.2 (clean install, without any backup cfg)
Scenario:
1. Select Internal module: MULTI - FrSkyX
2. Restart tx16s
Expected: After restart mode stays FrSkyX
Result: Mode is reset to to ESky. Also if you bind e.g XM+, bind is lost

Devs, is there any workaround? Or maybe I should flash back to some older version, but which?

**Comment by aivisbush** [comment]
Found solution. Problem was that MULTI module FW was out of date. Updated to the latest, following steps https://downloads.multi-module.org.
And now I cannot reporduce this issue.
I think, this issue can be closed if @gysmitty won't report back...

**Comment by pfeerick** [comment]
That would explain why I've never been able to reproduce this, so yes, unless there is further information to suggest this is a bug on our side, this issue will get closed soon. Thanks for the followup :)

**Comment by gysmitty** [comment]
Sorry for my lack of response, emails were going to spam folder. I will try the Multimodule firmware update and report back. Thanks to you all who put the time into making this platform better.
