### ISSUE TITLE
EL18 bind with INr6-HS,Telemetry data problem

### ISSUE THREAD

**Issue by lolfling** [EdgeTX/edgetx#3196]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

![EL18-2023-2-15](https://user-images.githubusercontent.com/118271761/219027542-a183be1e-3970-4d09-9f03-302a1bbdc3b1.png)

### Expected Behavior

Please check the picture content。

### Steps To Reproduce

1、Bind With INr6-HS
2、View the Telemetry page

### Version

2.8.0

### Transmitter

Flysky EL18

### Anything else?

No response

**Comment by raphaelcoeffic** [comment]
Apparently, the sensor data format changed since AFHDS2 as we parse them. Let's see if we can get a definition from FlySky.

**Comment by pfeerick** [comment]
So this is mainly an AFHDS3 telemetry parsing issue then? Not that surprising since the AFHDS3 stuff is all pretty new here. :grin:

**Comment by CharlesGauci** [comment]
I have the same issue with the FTR10 receiver on the EL18.

**Comment by CharlesGauci** [comment]
These errors are similar to the NV14 readings before September 2020, until qba667 made some updates and solved the problem. You can see the history in RCGroups 'Underground FPV Dark Knight Radio' pages 247 to 249. Eshifri used to follow these updates, maybe he can help.

**Comment by pfeerick** [comment]
Link to p247 for ease of access: https://www.rcgroups.com/forums/showthread.php?3023832-UndergroundFPV-Dark-Knight-Radio/page247

**Comment by CharlesGauci** [comment]
Github changes are mentioned in page 250 by 'yds,',  report number 3741. Sorry, I do not know how to create a link 😓

https://github.com/open-flysky/Flysky-OpenTX-Test-Branch/commits/pulses23?after=517cb176179e691644432db3b8516905b65864ba+69&branch=pulses23&qualified_name=refs%2Fheads%2Fpulses23
