### ISSUE TITLE
with the current "main f76aea3" no sound is played anymore

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3241]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

with the current "main f76aea3" no sound is played anymore. In addition, the entire simulator runs much slower than that of the previous "mains". Keystrokes such as Enter are not always recognised/executed.

### Expected Behavior

1. Sounds should play
2. the reaction speed should be the same as before.

### Steps To Reproduce

just use the simulator. I could reproduce it with X10S Express and TX16S

### Version

Other (Please specify below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS), Radiomaster TX16S / TX16SMK2

### Anything else?

main f76aea3

**Comment by ParkerEde** [comment]
I use Windows Companion / Simulator

**Comment by gagarinlg** [comment]
Did you install SDL2?
You can do this manually or by running the system specific prepare script.

**Comment by ParkerEde** [comment]
No. Where I have to install SDL2, in Windows or in MSYS2 environment?

**Comment by gagarinlg** [comment]
See this discord message https://discord.com/channels/839849772864503828/839856795781431317/1077911635571789895

**Comment by rotorman** [comment]
Short version: run `pacman -S --noconfirm mingw-w64-x86_64-SDL2` in your MSYS2 and use -DSDL2_LIBRARY_PATH instead of -DSDL_LIBRARY_PATH (w/o 2 in the name) on the CMake line.

**Comment by ParkerEde** [comment]
ah okay thank you very much. build is running...

**Comment by raphaelcoeffic** [comment]
> Did you install SDL2?
> You can do this manually or by running the system specific prepare script.

Isn’t it distributed with Companion?

**Comment by ParkerEde** [comment]
yes, now it runs as expected, and sound works too. 
Is it correct that the Companion is now just under 90MB in size instead of 25MB before?

**Comment by raphaelcoeffic** [comment]
> yes, now it runs as expected, and sound works too. Is it correct that the Companion-Setup file is now just under 90MB in size instead of 25MB before?

The archive is around 30MB, which is about what we had lately. Did you happen to have compiled it yourself? If yes, it may be missing the stripping of debug information, which use a lot of space.

**Comment by ParkerEde** [comment]
Yes, I build myself. How can I stop the debug information?
My selfbuilds were only 25MB before I made the changes mentioned above.

**Comment by ParkerEde** [comment]
there are many lib*.dll files now in the installed Companion-folder.
Here a verfication 2.9 before and after
[after.txt](https://github.com/EdgeTX/edgetx/files/10805285/after.txt)
[before.txt](https://github.com/EdgeTX/edgetx/files/10805286/before.txt)

**Comment by rotorman** [comment]
run 'strip <filename>'

**Comment by ParkerEde** [comment]
I think companion.exe and simulator.exe are not the problem, they are still about the same size (about 20 MB) before and after. The problem is that there are many new lib*.dll files. If you tell me that is ok and these are now needed, then it is ok with me. 
I just want to avoid unnecessary DLLs being delivered and the setup becoming unnecessarily large.

**Comment by ParkerEde** [comment]
OK. Thank you very much. Then I can close the ticket?

**Comment by gagarinlg** [comment]
I think so
