### ISSUE TITLE
Flysky EL18 is missing in Companion

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3247]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Radio Type do not have the choice of Flysky EL18.

### Expected Behavior

Radio Type has the choice of Flysky EL18.

### Steps To Reproduce

1. Open Companion
2. Settings -> Settings
3. Radio Type field do not have the choice of Flysky EL18

### Version

2.8.0

### Transmitter

Flysky EL18

**Comment by richardclli** [comment]
@pfeerick Who can help this out?

**Comment by pfeerick** [comment]
Present as of 2.10, with simulator
