### ISSUE TITLE
Touch UI back button does tot function when editing Top Widgets

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#326]
**Describe the bug**
When editing the top bar widgets, the touch back button does not work. The only way to get out of the edit mode it is to use the hardware rtn button. This give the users the false impression that the touch screen is locked up, since you cannot swipe the main screen as well when in this mode.   

**To Reproduce**
Go to screen settings, select the TOP Bar setup widgets, notice that you cannot use theTouch UI Back button.

**Expected behavior**
Tough UI back button should work in this mode as well

**Screenshots**
Not needed

**General information**
 - EdgeTX version 5d9498e8
 - Hardware RMTX16s

**Comment by pfeerick** [comment]
Also when editing the panels, not just the top bar... ;)

**Comment by gagarinlg** [comment]
This can be closed, right?

**Comment by pfeerick** [comment]
Yes, I think this was fixed back in 2.7, but the fix not linked. Regardless, I can't repo either case this on 2.7.1 or `main` anymore.
