### ISSUE TITLE
Switch to emergency mode when selecting: system, hardware in 2.8.1 FR

### ISSUE THREAD

**Issue by Salto42** [EdgeTX/edgetx#3266]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Switch to emergency mode when selecting: system, hardware in 2.8.1 FR

### Expected Behavior

 To get the hardware menu

### Steps To Reproduce

Select: system, hardware in 2.8.1 FR

### Version

Other (Please specify below)

### Transmitter

Jumper T16, Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
This fix will be available in 2.8.2 unless you self-build the 2.8 branch
