### ISSUE TITLE
Horus Battery Percentage Widget not visible

### ISSUE THREAD

**Issue by 3DRacer** [EdgeTX/edgetx#328]
**Describe the bug**
Horus Battery Percentage Widget is not shown on screen.

**To Reproduce**
Install widget shown in https://hobby4life.nl/?p=86
The widget can be configured, but remains invisible

**Expected behavior**
The widget should be visible on the screen.

**General information**
 - EdgeTX version  2.4.0 RC2
 - Hardware RM TX16S

**Comment by JimB40** [comment]
This is external LUA widget.
I suggest to contact author to make adjustments for EdgeTX

**Comment by lshems** [comment]
He is really responsive. Should be good to get him onboard for these kind of widgets.

**Comment by 3DRacer** [comment]
I have since followed the advice and wrote to the author about a solution. Now it remains to be seen

**Comment by rotorman** [comment]
I had a quick look at the LUA widget at https://hobby4life.nl/?p=86
It is missing a fallback case in the ScreenUpdate() function if LiveVolt > 0.
To fix this just comment out the last elseif and change it to else.

Thus find the following line (if you copy pasted it from the website, then it should be line 240):
`elseif LocalContext.zone.w == 160 and LocalContext.zone.h == 32 then`
and change to just
`else`
That should make it to display the content again.

**Comment by pfeerick** [comment]
> It is missing a fallback case in the _ScreenUpdate()_ function if _LiveVolt > 0_.
> To fix this, just change the last _elseif_ to _else_.

Thanks for that @rotorman At least it's not a bug introduced by ETX ;)
