### ISSUE TITLE
Pots & sliders preflight check menu items not translated

### ISSUE THREAD

**Issue by ulfhedlund** [EdgeTX/edgetx#3280]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The preflight check menu items for pots & sliders can not be translated. 
They are hard coded to "OFF","ON",AUTO" for color radios and "Off","Man","Auto" for B&W radios.

### Expected Behavior

The menu items should be possible to translate and preferably also the same for color and B&W radios.

### Steps To Reproduce

Go to preflight checks under radio settings and click in the menu for pots and sliders.

### Version

2.8.0

### Transmitter

Other (Please specify below)

### Anything else?

The issue is the same for all radios.

**Comment by Pat6874** [comment]
no translation necessary, the terms are clear and understandable for FR
