### ISSUE TITLE
UI 2.9 Pages header unification

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3284]
This issue is to unify header information which allow later (3.0) to convert it to proper breadcrumb (ie GROUP>PAGE>SUBPAGE). Follows https://github.com/EdgeTX/edgetx/pull/3238 
There are varoius fixes like
- Missing or wrong title
- Wrong letter type (capital vs small)

I think I've reviewed all pages but if you find inconsistency somwhere elsle please add in comment.

## RADIO SETTINGS

- [x] RADIO SETTINGS/TOOLS/Spectrum Analyser (sub page)
![screenshot_tx16s_23-03-01_08-53-14](https://user-images.githubusercontent.com/46420768/222093536-5a53191a-1994-44d2-a921-79311f1623ed.png)
title1: TOOLS
title2: Spectrum Analyser

- [x] RADIO SETUP/Sound (sub page)
![screenshot_tx16s_23-03-01_10-11-48](https://user-images.githubusercontent.com/46420768/222094695-3e2fdffc-b861-4e3e-9be8-b98f190b4d98.png)
title1: RADIO SETUP
title2: Sound

- [x] RADIO SETUP/Variometer (sub page)
![screenshot_tx16s_23-03-01_10-13-06](https://user-images.githubusercontent.com/46420768/222094906-d5571f7d-8136-467c-a785-33247fa027a8.png)
title1: RADIO SETUP
title2: Variometer

- [x] RADIO SETUP/Haptic (sub page)
![screenshot_tx16s_23-03-01_10-13-35](https://user-images.githubusercontent.com/46420768/222095032-ce8886e7-c80a-4442-8528-e746dd770541.png)
title1: RADIO SETUP
title2: Haptic

- [x] RADIO SETUP/Alarms (sub page)
![screenshot_tx16s_23-03-01_10-14-16](https://user-images.githubusercontent.com/46420768/222095208-3910f4a0-8e70-4bd5-bf1f-513d1d71b6c2.png)
title1: RADIO SETUP
title2: Alarms
- [x] On RADIO SETUP page change button name from 'Alarm' to 'Alarms' to unify.

- [x] RADIO SETUP/Backlight (sub page)
![screenshot_tx16s_23-03-01_10-16-04](https://user-images.githubusercontent.com/46420768/222095622-1ba6074b-4796-4a94-a978-08dbd2034064.png)
title1: RADIO SETUP
title2: Backlight

- [x] RADIO SETUP/GPS (sub page)
![screenshot_tx16s_23-03-01_10-16-44](https://user-images.githubusercontent.com/46420768/222095823-e909c5a0-f0e2-45fb-8d95-01e449ef7ac3.png)
title1: RADIO SETUP
title2: GPS

- [ ] HARDWARE/CALIBRATION (sub page)
![screenshot_tx16s_23-03-01_11-09-53](https://user-images.githubusercontent.com/46420768/222108950-9844f93a-cf22-4e10-8762-95397e977899.png)
title1: HARDWARE
title2: Calibration
This one requires to move information about current calibration step from header title2 variable to variable placed above graphical representation of sticks.

- [ ] HARDWARE/ANALOGS/Calibrated Analogs (sub page) - sub-pages navigation to change/discuss

- [ ] HARDWARE/ANALOGS/Filtered raw analogs with deviation (sub page) - sub-pages navigation to change/discuss

- [ ] HARDWARE/ANALOGS/Unfiltered raw analogs (sub page) - sub-pages navigation to change/discuss

- [ ] HARDWARE/ANALOGS/Min, max. and range (sub page) - sub-pages navigation to change/discuss

- [x] HARDWARE/Keys/SWITCHES TEST (sub page) - 2.8 version no change
![screenshot_tx16s_23-03-01_10-23-03](https://user-images.githubusercontent.com/46420768/222097722-e86a5606-5af7-4c2b-80ec-b61bddfb8d6b.png)
title1: HARDWARE
title2: Keys

## MODEL SETTINGS

- [x] MODEL SETUP/Internal RF (sub page)
![screenshot_tx16s_23-03-01_10-29-43](https://user-images.githubusercontent.com/46420768/222098939-64879c40-6f90-4dd2-be24-484f474e97df.png)
title1: MODEL SETUP
title2: Internal RF
 
- [x] MODEL SETUP/External RF (sub page)
![screenshot_tx16s_23-03-01_10-30-45](https://user-images.githubusercontent.com/46420768/222099207-531f01ff-5891-447d-a148-7ef3dd9b862c.png)
title1: MODEL SETUP
title2: External RF
 
- [x] MODEL SETUP/Trainer(sub page)
![screenshot_tx16s_23-03-01_10-31-23](https://user-images.githubusercontent.com/46420768/222099396-00ad258e-dd6c-499b-ba83-9d7f4b1915f0.png)
title1: MODEL SETUP
title2: Trainer

- [x] MODEL SETUP/Timer 1-3 (sub page)
![screenshot_tx16s_23-03-01_10-33-09](https://user-images.githubusercontent.com/46420768/222099733-5d428b54-28fe-4c82-b5b2-dc0eaf0a6e9e.png)
title1: MODEL SETUP
title2: Timer 1 (for other timer pages Timer 2 & Timer 3)

- [x] MODEL SETUP/Preflight Checks (sub page)
![screenshot_tx16s_23-03-01_10-33-27](https://user-images.githubusercontent.com/46420768/222099819-d1df239e-30c3-4c9c-9cb0-bdf39030abd7.png)
title1: MODEL SETUP
title2: Preflight Checks

- [x] MODEL SETUP/Trims (sub page)
![screenshot_tx16s_23-03-01_10-33-49](https://user-images.githubusercontent.com/46420768/222099891-308b7de9-9e15-4304-80a9-e6e631426aa1.png)
title1: MODEL SETUP
title2: Trims

- [x] MODEL SETUP/Throttle (sub page)
![screenshot_tx16s_23-03-01_10-34-13](https://user-images.githubusercontent.com/46420768/222099984-72164021-2149-4f60-92d5-7d0ad8bc918e.png)
title1: MODEL SETUP
title2: Throttle

- [x] FLIGHT MODE 0-8 (Flight mode edit page)
![screenshot_tx16s_23-03-01_10-35-00](https://user-images.githubusercontent.com/46420768/222100162-43c373e1-5114-4cce-8649-be2aee7b59d9.png)
title1: FLIGHT MODES
title2: FM0 (for other pages FM1, FM2, FM3, FM4, FM5, FM6, FM7, FM8) 

- [x] MIXES (Mixes edit page1 & page2)
![screenshot_tx16s_23-03-01_10-42-04](https://user-images.githubusercontent.com/46420768/222101900-dae76b7b-e7aa-4cc8-bd67-7ff4c018a178.png)
![screenshot_tx16s_23-03-01_10-42-11](https://user-images.githubusercontent.com/46420768/222101911-d2527742-aeee-4cd5-a23c-bcc7288608ec.png)
title1: MIXES
title2: CH1 (for ther pages CHxx) 

- [x] OUTPUTS (Output edit page) - page with no header
![screenshot_tx16s_23-03-01_10-42-36](https://user-images.githubusercontent.com/46420768/222102425-3e1fb259-2ecf-4a49-94bc-d7832261f173.png)
title1: OUTPUTS
title2: CH1 (for ther pages CHxx) 

- [x] CURVE (Curve edit page)
![screenshot_tx16s_23-03-01_10-45-28](https://user-images.githubusercontent.com/46420768/222102811-e1665dcd-7e5f-4880-8ab8-008663f50080.png)
title1: CURVES (parent name: CURVES not as now CURVE)
title2: CV1 (for ther pages CVxx) 

- [x] GLOBAL VARIABLES/Global Variable (Global Variable edit page)
title1: GLOBAL VARIABLES (parent name: GLOBAL VARIABLES not as now Global Variable, Capital letters)
title2: GV1 (for ther pages GVxx) 

- [x] TELEMETRY/SENSOR (telemetry sensor edit page) 
![screenshot_tx16s_23-03-01_10-55-53](https://user-images.githubusercontent.com/46420768/222105486-c77b17c7-1107-4f7d-b574-097448adf2df.png)
title1: TELEMETRY
title2: SENSOR 1 (for ther pages SENSOR x) 

## MODEL MANAGER

- [x] Select Model (Models browsig)
![screenshot_tx16s_23-03-01_10-58-42](https://user-images.githubusercontent.com/46420768/222106417-056d07c5-c4df-4d05-8463-531576e493f9.png)
title1: MODEL MANAGER
title2: Active _model_name_ (Active instead of Current) 

- [x] Select Model/Select a template folder (New Model creation) https://github.com/EdgeTX/edgetx/pull/3076
![screenshot_tx16s_23-03-01_11-02-06](https://user-images.githubusercontent.com/46420768/222107511-c94f98c2-42ce-4760-8576-8fa08476fe32.png)
title1: MODEL MANGER
title2: New Model

## STATISTICS

- [ ] Statictics (sub page) - sub-pages navigation to change/discuss
- [ ] Debug (sub page) - sub-pages navigation to change/discuss

**Comment by HThuren** [comment]
Impressive work in this PR
