### ISSUE TITLE
2.8.1 in french

### ISSUE THREAD

**Issue by Pat6874** [EdgeTX/edgetx#3289]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

version 2.8.1 in french does not allow to choose a model. In addition, if you choose "radio settings" the radio goes into security mode

### Expected Behavior

choose model
access to radio settings

### Steps To Reproduce

1 choose model
2 select radio settings

### Version

2.8.0

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
Item 2 (emergency mode on entering radio settings) will be resolved in 2.8.2. Can you elaborate further on the first point?
