### ISSUE TITLE
Zorro- Display time on Main and Telemetry screen.

### ISSUE THREAD

**Issue by KC748** [EdgeTX/edgetx#3303]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

 Zorro's main screen does not display the Time.

Relate:d https://github.com/EdgeTX/edgetx/discussions/3190

### Describe the solution you'd like

I realize there isn't a lot of real estate on Zorro's screen, but if possible...

1. By default, display the Time on the main screen. Next to the Voltage display would be ideal. Smaller text size for the Time and Timers would be OK.

![MainScreen](https://user-images.githubusercontent.com/39738927/222923129-dcd19e84-9c21-434c-b649-fd17f8bc56f9.jpg)

2. Also by default, display the Time on the Telemetry Display screen. Ideally, at the very top, before or after the Battery Voltage.

![Telemetry](https://user-images.githubusercontent.com/39738927/222924031-7862abfb-c640-48ba-acfb-e54bdd3944ce.jpg)

### Describe alternatives you've considered

1. On the main screen, have the option to select Time, the way Timers are selected. 
2. On the Telemetry screen, the Time is a selectable option, to be displayed, from the Display screen. This is OK as is.  

### Additional context

A quick glance at the clock on the main screen is a convenient way to squeeze in the last minute of flying before having to pack it up to stay on schedule and not upset the wife. :)

**Comment by philmoz** [comment]
There's not really a lot of room to play with.
The flight mode and RSSI are displayed next to the battery, and a long model name will fill the top section.

![Screen Shot 2023-03-05 at 9 39 46 am](https://user-images.githubusercontent.com/9474356/222931800-94089a22-d8fd-446f-bc25-c34169221871.png)

**Comment by philmoz** [comment]
The telemetry screen would display timer 0 to the right of the battery voltage if the code did not have a bug in it.

![Screen Shot 2023-03-05 at 9 42 35 am](https://user-images.githubusercontent.com/9474356/222931872-8210ada2-317b-4922-b8d7-38b6dfc86684.png)

**Comment by KC748** [comment]
Oh I see. The Main screen is jammed full. I guess I'll continue using the Telemetry screen for the Time.
Thanks, Phil.

**Comment by philmoz** [comment]
I can squeeze the time in on the main screen with a bit of re-arrangment. It's crowded if you have long model names.
I had to move the 'unexpected shutdown' indicator (!) to the top left.
Also the left vertical trim box will slightly overlap the model name when set to max trim (which should be uncommon I would think).

![Screen Shot 2023-03-05 at 11 15 06 am](https://user-images.githubusercontent.com/9474356/222934778-da59aafc-8139-4c9e-918b-1daa6b845755.png)

**Comment by philmoz** [comment]
I can move the battery to fit timer0 and current time on the telemetry screen.

![Screen Shot 2023-03-05 at 11 25 02 am](https://user-images.githubusercontent.com/9474356/222935027-000031f9-08c1-4f9f-bffb-fdf088de5658.png)

**Comment by pfeerick** [comment]
Funnily enough, I want a longer model name on B&W  ... `TinyTrainer` instead of `TinyTraine` ... which would make things even worse! 🤣 

I wonder if we can play with the timer display main view... it only shows two of the three configured times, so if you push the second timer over to the right so it's aligned with the first, could shove a clock in there? 

![image](https://user-images.githubusercontent.com/5500713/222939358-15f408a3-4534-42ba-91ad-7348d9f15207.png)

**Comment by philmoz** [comment]
What about this - if we make the trim bars slightly shorter and put the time between them
This way the time is visible on all the screens (except channel monitor).

![Screen Shot 2023-03-05 at 2 27 31 pm](https://user-images.githubusercontent.com/9474356/222940088-9fc06780-de1a-4739-bb28-080484b96c92.png)

**Comment by pfeerick** [comment]
That works :) Yes, it'll be smaller on the smaller LCDs like the T-Lite... but no smaller than the other text... reading the time is the least of the problems there! 😆

**Comment by Eldenroot** [comment]
Cool

**Comment by KC748** [comment]
Oh, wow! Thanks guys. That’s perfect.
