### ISSUE TITLE
Wrong case used for units of time

### ISSUE THREAD

**Issue by MarkusPfaff** [EdgeTX/edgetx#3304]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Units of time are written wrong: They are written as "uS" instead of "us" and "mS" instead of "ms"

uS means microsiemens
mS means millisiemens

The definition is in file companion/src/sensordata.cpp (seems to be used for Tx as well as companion).

### Expected Behavior

Usage of correct SI unit notation.

### Steps To Reproduce

Look up the given file and search for 

uS
mS

### Version

2.8.0

### Transmitter

any

**Comment by Eldenroot** [comment]
I will create a new PR
