### ISSUE TITLE
Selecting ID while adding new Input - UI consistency

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3313]
### Is your feature request related to a problem?

Adding new Input will assign fist free ID.
All other lists have 2 step adding proces.
1. Tapping "+"
2. Selecting free slot (ID)

### Describe the solution you'd like

After tapping "+" list of free slots should be displayed.

This will 
1. unify adding item to the list across OS 
2. Will make adding 2 step allowing to cancel process if "+" was selected by aciddent.

**Comment by pfeerick** [comment]
To clarify, what Robert means is to make the `+` at the bottom of the Inputs page the same as how it behaves on the Mixes, LS and SF pages - whereby it shows the menu listing available slots.
