### ISSUE TITLE
Widget does not receive events or updated zone dimensions in fullscreen mode

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#332]
Lua-widget does nor receive any events when set in full-screen mode

**Comment by wimalopaan** [comment]
And additionally the new zone-dimensions are not given to refresh()

**Comment by jfrickmann** [comment]
This issue addresses my question on the Lua forum on Discord.

**Comment by jfrickmann** [comment]
I think that we can close this one now.
