### ISSUE TITLE
RTC bridge is not disabled, if "Check RTC voltage" is not enabled

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#333]
@Thx to tip by Mike Blandford in RCGroups https://www.rcgroups.com/forums/showpost.php?p=47360301&postcount=82

If SYSTEM -> HARDWARE -> _Check RTC voltage_ is disabled, the VBatBridge is enabled during adcInit():
https://github.com/EdgeTX/edgetx/blob/5d9498e88be70cb8d34bac4f08bcac8cc9e5452f/radio/src/targets/common/arm/stm32/adc_driver.cpp#L145

but never disabled, causing unnecessary strain on the coin cell (roughly 60 µA).

If, on the other hand, _Check RTC voltage_ is enabled, after first checkRTCBattery() call:
https://github.com/EdgeTX/edgetx/blob/5d9498e88be70cb8d34bac4f08bcac8cc9e5452f/radio/src/opentx.cpp#L695-L703
disableVBatBridge() is called:
https://github.com/EdgeTX/edgetx/blob/5d9498e88be70cb8d34bac4f08bcac8cc9e5452f/radio/src/targets/common/arm/stm32/board_common.h#L120-L123
removing the bridge.

Tested on RM TX16S - one sees jumpy values of RTC Batt when starting a radio with _Check RTC voltage_ disabled - meaning the value is sampled constantly. On the other hand when enabling _Check RTC voltage_, reboot and then checking the RTC Battery value - it is rock solid, thus being sampled only once, during start.

**Comment by rotorman** [comment]
See also https://github.com/opentx/opentx/issues/8571

**Comment by rotorman** [comment]
I created a current measurement rig for coin cell on RM TX16S by soldering a second CR 1220 holder in parallel, where I put the battery and then putting a current meter in series to the pinheader on the positive rail:

![TX16S coin cell current measurement](https://user-images.githubusercontent.com/21011587/123542994-db337100-d74c-11eb-8ad9-8002d53592d6.JPG)

My current meter can do in most sensitive range 400µA measurements with 100nA resolution. Testing with 5d9498e8.
When radio is off, I measure 0.7 to 0.8 µA, likely the current is even lower, just my device cannot do better.

When radio is powered on and under SYSTEM -> HARDWARE -> "Check RTC voltage" is ticked, the voltage reading behind _RTC Batt_ stays constant and the measurement reads still ca. 0 to 0.1 µA (thus less when radio is off).

When on the other hand "Check RTC voltage" is NOT checked, I see _RTC Batt_ value toggle and read 24.9 to 25.0 µA on the current meter.

**Comment by pfeerick** [comment]
And let me guess... it's not a rechargeable coin cell? So in "checking" the RTC battery voltage, it's actively being flattened? 😢

**Comment by raphaelcoeffic** [comment]
> And let me guess... it's not a rechargeable coin cell? So in _not_ "checking" the RTC battery voltage, it's actively being flattened? 😢

Exactly!

**Comment by rotorman** [comment]
Solved by #360.
