### ISSUE TITLE
Zorro ETX 2.8.1: MPM Problem "XK", Subtype X450 "Prot. Invalid", no problem on prior versions

### ISSUE THREAD

**Issue by bernd25** [EdgeTX/edgetx#3343]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Since the ETX 2.8.1 DE (language vers.) update for Zorro 4in1 I can no longer use my VTOL (X450) from WLtoys. Under XK, subtype X450, it now says 'Prot. Invalid'. When I flash to the older ETX version 2.8.0 I don't have this problem. The behavior is independent of the MMP version. 
Even if the corresponding protocol on Github MPM is described as problematic, I was always able to control my VTOL X450 without any problems, also no problem with the binding. If this behavior should persist in later ETX versions, I couldn't no longer make updates.

### Expected Behavior

I expect that when I select the MP 'KX' , it will be available again for my model and I can select the X450 subtype again.

### Steps To Reproduce

Choose model's options
Go to Internal HF-Modul
Modus: Multi
Go to protocol "XK"
Now, you can't go on anymore.
You can't fly the model.

### Version

Other (Please specify below)

### Transmitter

Radiomaster Zorro

**Comment by richardclli** [comment]
Duplicated with https://github.com/EdgeTX/edgetx/issues/3264
