### ISSUE TITLE
Zorro- While selecting Protocol Type, Unable to scroll in reverse from Config.

### ISSUE THREAD

**Issue by KC748** [EdgeTX/edgetx#3356]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In Model Setup, it is possible to scroll past the last protocol, (XK currently) to the beginning of the list, Config. However, from Config, it is not possible to scroll in reverse back to the last protocol.

Over shooting the last protocol is quite easy and it's a little annoying having to scroll all the way back to the end of the list from the beginning. 

![ProtocolConfig](https://user-images.githubusercontent.com/39738927/225350956-213a31fd-9e78-4ddc-8444-5e2d76edc802.jpg)

### Describe the solution you'd like

Allow scrolling in reverse from Config to the end of the protocol list. 

### Describe alternatives you've considered

1. Place a hard stop at the end of the protocol list with a haptic and/or beep to signal the end.

**Comment by 3djc** [comment]
I think that would require a multi module firmware change, as on BW screen, the module pilots the behaviour

**Comment by KC748** [comment]
Ah, ok. Thanks.
