### ISSUE TITLE
Visual dependencies in INPUTS / MIXES

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#337]
TX16S, RC3
please add dependencies like for SPECIAL FUNCTIONS (yellow highlighting) also for INPUTS and MIXES.
e.g. true for Switch SD is up and true -> yellow background
Without it is hard to test correct functions

**Comment by pfeerick** [comment]
RC3, TX16S: This is actually a regression from OTX behaviour... as I have a model that has some convoluted flight mode, logical switches, and also physical switch interactions across both the input and mixes pages, and OTX 2.3.10/11 showed me which of the combo inputs or mixes was active depending on what flight mode, switch, and logical switch was active. Flight modes, logical switches and special functions screens are all fine, it's just the input and mixes pages that don't highlight in any way. 

RC3, T-Lite and X9D+ are both fine.
