### ISSUE TITLE
EdgeTX support for TBS Mambo

### ISSUE THREAD

**Issue by socalengineer** [EdgeTX/edgetx#3377]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The TBS Mambo has been waiting for an EdgeTX release date for quite some time, what are the issues to getting this rolled out?

### Describe the solution you'd like

A version of EdgeTX that supports the TBS Mambo target/hardware.

### Describe alternatives you've considered

1. Contacted the TBS team and they mentioned they are working with EdgeTX developers on the issue, but have yet to see any release or progress. It has been on YouTube for over 1-year yet there are no updates.

**Comment by gagarinlg** [comment]
TBS said that they are working on this, but we did not see any progress for way over a year, please ask them.
They need some special code for their gimbals that is not EdgeTX compatible and they have to update that code.
