### ISSUE TITLE
EL18 internal RF interface display suggestions

### ISSUE THREAD

**Issue by lolfling** [EdgeTX/edgetx#3391]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The interface display is disordered
![image](https://user-images.githubusercontent.com/118271761/226893415-40de4b32-b24f-4aa0-be46-1b435374d4f6.png)

### Describe the solution you'd like

Keep options organized

### Describe alternatives you've considered

Model setup-> internal RF \External RF\Trainer\Trmer1\Timer2\Timer3...

### Additional context

No response

**Comment by pfeerick** [comment]
Actually, now that I think of it, for that screen orientation, having one button per row probably wouldn't hurt at all...

**Comment by pfeerick** [comment]
Actually, no, this is outdated sorry - the layout issue has been improved in 2.9 by changing it to three columns for portrait screen.
