### ISSUE TITLE
Signal polarity different to 2.8.1 for LemonDSP, DSM2 and PPM external modules

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3413]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The "polarity" of signals sent to external modules LemonDSP, DSM2 and PPM are reversed compared to 2.8.1.

Example DSM2 outgoing signal recorded at CCPM pin of the module bay with 2.8.1 firmware is idle high
![DSM2_2 8 1](https://user-images.githubusercontent.com/5615068/228334774-ac986d30-ce83-44d7-a54a-dac5986dec77.JPG)

 with 2.9.1. the signal is idle low
![DSM2_2 9](https://user-images.githubusercontent.com/5615068/228334911-b4061b13-5660-4f2a-bf90-f98eded24e41.JPG)

The same is true for external modules LemonDSP and PPM. At least external DSM2 and LemonDSP modules shouldn't work in 2.9 as of now. I'd ask LemonDSP and DSM2 owners to confirm.

### Expected Behavior

Same signal polarity as in 2.8.1

### Steps To Reproduce

- Hook up logic analyzer or scope to GND and CCPM pins of the module bay
- select external modules LemonDSP, DSM2 and PPM
- compare idle levels between 2.8.1 and 2.9 current nightly 

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

Firmware versions used:
- 2.8.1 release tx16s-d9d4a8a.bin
- 2.9 nightly tx16s-5465984.bin

**Comment by pfeerick** [comment]
In case you check before I do, for PPM, does changing - to + still work (but basically be reversed to 2.8?)

**Comment by pfeerick** [comment]
Ok, so a walk down all the external modes, 2.9 yesterdays nightly vs 2.8.1, indicates:

Inverted:
- PPM neg
- PPM pos
- DSM2
- LemonRX DSMP

Unchanged:
- XJT 
- MULTI
- CRSF
- R9M
- SBUS normal
- SBUS not inverted
- GHST

Broken?
- Flysky

Saleae Logic 8 captures:
[3413-2.8.1.zip](http://files.portabledev.xyz/f/68b557a7282b45608e9f/?dl=1)
[3413-2.9.zip](http://files.portabledev.xyz/f/af69f9ab3f764c838a96/?dl=1)

**Comment by mha1** [comment]
Correct, confirms my measurements.

Please do me a favor while you have the LA hooked up:
- 2.9
- choose external modul SBUS
- confirm it's idle low. If not change polarity in SBUS external module settings (normal/inverted)
- record 5s of data
- zoom out and check pattern
- any unexpected garbage between SBUS frames?
- repeat a few times

**Comment by pfeerick** [comment]
Sorry, no. Even when doing a 60 second capture and monitoring analog it still seemed clear. Using same 2.9 nightly as before.
[SBUS-60sec.zip (digital only)](https://github.com/EdgeTX/edgetx/files/11096896/SBUS-60sec.zip)

**Comment by mha1** [comment]
That's alright, just means less work.

**Comment by mha1** [comment]
Not sure about external Flysky. It is initialized with  ` .direction = ETX_Dir_TX_RX` which looking at crossfire initialization seems to indicate half duplex (on SPort pin). So external Flysky should be ok with no signal on CCPM.

**Comment by mha1** [comment]
Leaves PPM and DSM2 as LemonDSMP TX is also initialized as DSM2 (with different frame rate)

**Comment by pfeerick** [comment]
Except... this is FLYSKY on 2.8.1

![image](https://user-images.githubusercontent.com/5500713/228479911-3abd6e93-2aa3-495a-9638-992f868a7ebb.png)

vs 2.9 (and yes, a much wider time period to further highlight the point) 

![image](https://user-images.githubusercontent.com/5500713/228479959-d60c8bab-aa86-4639-8b79-d2c8907afe30.png)

So either 2.8.1 was wrong, or 2.9 is wrong ;)

**Comment by mha1** [comment]
My bad, you are right. 2.8.1 outputs serial data on CPPM for external Flysky, 2.9 doesn't as it seems to initialize the module port for half duplex on SPort. No clue what should be selected. Were there any complaints about external  Flysky in 2.8.1? Isn't there a Flysky guy hanging out here? He's probably best to ask.

**Comment by pfeerick** [comment]
No issues that I know of... that is why I'm hoping it's expected change... Looking at you @richardclli 🤭

**Comment by mha1** [comment]
Do external AFHDS3 modules even exist? I only found 2a modules.

**Comment by gagarinlg** [comment]
> Do external AFHDS3 modules even exist? I only found 2a modules.

Patience

**Comment by pfeerick** [comment]
There's the FRM301, FRM302 and FRM303... 

The FRM301 is the module used in the PL18 series transmitters
The FRM302 is the JR micro bay module like you found
I don't know much about the 303, other than IIRC it replaces the 302. Richard has been working on that. https://github.com/EdgeTX/edgetx/issues/2863

**Comment by richardclli** [comment]
> No issues that I know of... that is why I'm hoping it's expected change... Looking at you @richardclli 🤭

A few information for references:
1. FRM302 is not supported since 2.8.0,  as Raphael implemented the new protocol for the internal module IRM301 in EL18, the old protocol is removed completely.  And that is why FRM302 will not work since 2.8.0
2. Flysky has already discontinued FRM302, and they think it is alright to stop supporting FRM302
3. FRM 303 will be announced soon, and FRM303 is already supported in EL18 since 2.8.1 and it did not use the S.Port for half duplex but use the PPM/Heartbeat pair for full duplex instead.
4. Because of the hardware bug and forced signal inversion of other EdgeTX radios, the current implementation will not work for other radio, and we need to wait for Flysky to amend another mode that use S.Port instead.

**Comment by pfeerick** [comment]
Are you able to double-check that the FRM303 is *still* working with a recent nightly?

**Comment by richardclli** [comment]
Let me check during weekend.  It works in main sometimes ago, but well who knows.

**Comment by richardclli** [comment]
> Let me check during weekend. It works in main sometimes ago, but well who knows.

Confirmed FRM303 still works in 2.9 with EL18.
So the signal is 2.8.1 is somewhat different with 2.9?  They should be the same if it still works.

**Comment by pfeerick** [comment]
I was using the TX16S for the captures in https://github.com/EdgeTX/edgetx/issues/3413#issuecomment-1487936737, so there could be some thing different happening there. But as long as it works on the EL18, all good, as it won't work with the TX16S in that mode atm *anyway* 🤭

**Comment by richardclli** [comment]
I see, TX16S use different mappings for Flysky now, and it is not working anyway.  And why 2.8 has something, because I hhave tried to make it works in Tx16S, but not tried to do the same thing in 2.9, yet.  The Serial API changes in 2.9 need different implementation.

**Comment by pfeerick** [comment]
Ah, that explains it... Thanks  Richard :) As long as we know the reason, and it's not a 🐛, the show can go on! 😄

**Comment by richardclli** [comment]
Now the FRM303 works in TX16S with a simple mod similar to Access mod.

**Comment by pfeerick** [comment]
I'm not sure atm if #3442 is connected to this issue, so re-opening for now.

**Comment by gagarinlg** [comment]
@mha1 could you please test
https://github.com/EdgeTX/edgetx/pull/3513

**Comment by mha1** [comment]
@gagarinlg Sure, but please be aware that this PR can't be verified with just a test on a single radio. The changes made are heavily influenced by the hardware design of the radios (UARTs, inverters, software controllable inverters, GPIO assignment, etc). So I can only contribute a Horus target (TX16s) but to come to a final verdict on this change you'd at least have to get results from NV14 (sw controllable inverters), and some Taranis type radios, e.g. X9D. See also discussion here https://github.com/EdgeTX/edgetx/pull/3415#issuecomment-1500848279

Test results on TX16s with firmware obtained from merge checks of this PR (https://github.com/EdgeTX/edgetx/actions/runs/4777343713?pr=3513):

DSM2 init (going from OFF to DSM2): ok
![image](https://user-images.githubusercontent.com/5615068/235344616-81137651-713d-4a16-b6c8-958aa1bedcc3.png)

DSM2 (for all subtypes LP45, DSM2, DSMX): polarity idle high as in 2.8 -> ok
![image](https://user-images.githubusercontent.com/5615068/235344430-2c5bef2d-1654-4887-a083-ce2a033781fb.png)

LemonRx DSMP init (going from OFF to LemonRx DSMP): ok
![image](https://user-images.githubusercontent.com/5615068/235344677-c305b8a9-2a85-4fe1-8464-ee607e133f21.png)

LemonRx DSMP: polarity idle high as in 2.8 -> ok
![image](https://user-images.githubusercontent.com/5615068/235344551-b2799248-27b5-4791-8483-d1035fea1eff.png)

PPM (-) going from OFF to PPM -> **not ok**. This doesn't seem to hurt PPM modules as this only affects the first two or three frames. Yet, it doesn't look right.
![image](https://user-images.githubusercontent.com/5615068/235344257-dabfade3-18cb-459a-9134-1a6ba2ac618c.png)

PPM (-): polarity idle high as in 2.8 -> ok 
![image](https://user-images.githubusercontent.com/5615068/235343850-877c03f4-ec0c-4f17-8725-ee728a998548.png)

PPM (+): polarity idle low as in 2.8 -> ok 
![image](https://user-images.githubusercontent.com/5615068/235343980-a4501296-9d96-43a9-9b93-88cf37f10005.png)

**Comment by raphaelcoeffic** [comment]
> PPM (-) going from OFF to PPM -> not ok

I can re-check that one. And give it a try of side-by-side tests with X9D+.

**Comment by mha1** [comment]
Thanks, and before merging we need at least feedback on NV14.
