### ISSUE TITLE
X10access: no PPM output on CPPM pin 

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3418]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

No PPM output on CPPM pin on X10accessradio after selecting external module PPM.

### Expected Behavior

PPM output on CPPM pin on X10Express radio after selecting external module PPM

### Steps To Reproduce

1. X10access: flash nightly https://github.com/EdgeTX/edgetx/actions/runs/4549654336 (commit 5465984 ) 
2. select internal module OFF
3. select external module PPM
4. observe output on CPPM pin using PPM module, scope or logic analyzer

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Anything else?

x10access nightly 5465984

**Comment by ParkerEde** [comment]
I can confirm the problem exactly. Neither the MLINK nor the orangeRX DSM2 modules, which are driven by PPM, work with the current MAIN
