### ISSUE TITLE
Insta trim not working

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#342]
I can set up instatrim fine.
but it just does nothing

**Comment by pfeerick** [comment]
With what Transmitter? What firmware version? How exactly are you setting up InstaTrim? Special Function for the model, Global function? The questions in the template are so we don't need to guess those things! ;)

I can't reproduce this on RC3 with either the X9D+ or T-Lite, with Inst.Trim attached to a switch, as a model special function. 

I *can* reproduce it on the TX16S, again with Inst.Trim attached to SFdn, as a model special function (setting it up as a global function does not work either). The functions screen indicates the function is active (i.e. row goes yellow when switch in trigger position, but the channel output is not adjusted "trimmed" to match).

**Comment by Mantamatt1** [comment]
Yes tx16s, sf down, function goes yellow but trims do nothing

**Comment by Mantamatt1** [comment]
I have re commented.
It's a tx16s, sf down. Function goes yellow but no movement on trims.

Thanks for all your hard work, you have done amazing things

**Comment by Mantamatt1** [comment]
Firmware is the latest rc3

**Comment by raphaelcoeffic** [comment]
As it seems, Insta trim is meant to be enabled only when certain menus / screens are displayed:
```
#define IS_INSTANT_TRIM_ALLOWED()      (IS_MAIN_VIEW_DISPLAYED() || IS_TELEMETRY_VIEW_DISPLAYED() || IS_OTHER_VIEW_DISPLAYED())
```

Now, with the new UI, it is not known globally which view/screen is displayed, so it seems it has been disabled. Does anyone know why? Or what is the idea behind that?

**Comment by eshifri** [comment]
In functions.cpp:

          case FUNC_INSTANT_TRIM:
            newActiveFunctions |= (1u << FUNCTION_INSTANT_TRIM);
            if (!isFunctionActive(FUNCTION_INSTANT_TRIM)) {
#if defined(COLORLCD)
  #warning IS_INSTANT_TRIM_ALLOWED() is always false
#endif
              if (IS_INSTANT_TRIM_ALLOWED()) {
                instantTrim();
              }
            }
            break;

**Comment by raphaelcoeffic** [comment]
> In functions.cpp:
> 
> ```
>       case FUNC_INSTANT_TRIM:
>         newActiveFunctions |= (1u << FUNCTION_INSTANT_TRIM);
>         if (!isFunctionActive(FUNCTION_INSTANT_TRIM)) {
> ```
> 
> #if defined(COLORLCD)
> #warning IS_INSTANT_TRIM_ALLOWED() is always false
> #endif
> if (IS_INSTANT_TRIM_ALLOWED()) {
> instantTrim();
> }
> }
> break;

I'm just wondering why on b/w radios the function is limited to certain views. This is quite strange to me.

**Comment by eshifri** [comment]
I guess that if you are in the model setup views, you do not want to invoke this function by mistake.

**Comment by pfeerick** [comment]
What counts as an `IS_OTHER_VIEW_DISPLAYED` though... on X9D+ with ETX (and on OTX 2.3.12 using the sim) I can trigger Insta Trim as a global function in both radio setup and model setup... I'm not immediately aware of where it doesn't work... 

I personally think it should be enabled, enabled until it's disabled... it shouldn't be left active all the time, so having it work conditionally just adds confusion and potential for it to be mistakenly left on.

**Comment by raphaelcoeffic** [comment]
> I guess that if you are in the model setup views, you do not want to invoke this function by mistake.

Doesn't that fall into "be a responsible user"? If you do things by mistake, you need to cope with the consequences ;-) I could however understand having a sound telling you you just used "Insta. trim". Noticing which menu you are currently in with in the new UI is a non-trivial task, and would require quite some effort. So I'd advocate for letting down that "security feature" and just let it be a special function you can invoke, whatever is displayed on the screen.

**Comment by Mantamatt1** [comment]
I use insta trim all the time with otx.
I activate it by ticking the box.
I maiden the model.
When using instatrim it beeps every time you press it (that's quite
important). I land and un tick the box to deactivate it just incase I
accidentally press it it!

Its totally my responsibility if I leave it activated and accidentally
press it.

You cant fix stupid! 😁

**Comment by pfeerick** [comment]
> You cant fix stupid! 😁

I think we're all in agreement... if you insta crash it you insta to blame ;)

**Comment by raphaelcoeffic** [comment]
> > You cant fix stupid! 😁
> 
> I think we're all in agreement... if you insta crash it you insta to blame ;)

Should we post this on « Insta. Gramm »?
