### ISSUE TITLE
Failsafe not set warning do not have "Press any key to skip" message

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3421]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Switch warning will show "Press any key to skip" message, but failsafe not set do not have this message.

### Expected Behavior

Should add the same "Press any key to skip" message in failsafe not set screen for completeness.

### Steps To Reproduce

1. Ensure that the model do not have failsafe setup
2. Switch on radio
3. Failsaure not set warning screen appears (no "Press any key to skip" message)

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

### Anything else?

GIT SHA: 1f82724a9

**Comment by pfeerick** [comment]
Yes, there are a couple of the alert that don't indicate what key to press, or allow touch dismissal - the conversions and bad radio data are candidates also IIRC.
