### ISSUE TITLE
Double tap to enter app-mode

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#3425]
As we like to promote smarter widgets with app-mode awareness .
For this we need to make the entering/existing app-mode to be as simple & fast as we can.
This will encourage users to use it.
I already added double-tap as exit from app-mode on some of the widgets 

I request to add back the double-tap as it works in 2.7

**Comment by JimB40** [comment]
Double with #2629. Switching between apps is PIA without double tap
@raphaelcoeffic is the one who we should be harassing :)

**Comment by offer-shmuely** [comment]
sorry, did not find it on the search
closing as duplicated
