### ISSUE TITLE
Lost FUTABA SFHSS protocol with ETX 2.8.2 and MPM 1.3.3.20 ?

### ISSUE THREAD

**Issue by LS-67** [EdgeTX/edgetx#3434]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The receivers of models under ETX 2.8.1 and FUTABA SFHSS protocol use automatically  a "J6" protocol under ETX 2.8.2 and are no longer bindable.
When I create a new model with the FUTABA SFHSS protocol under ETX 2.8.2, this protocol disappears again after switching off/on the TX, to become "J6"

### Expected Behavior

keep the SFHSS protocol like in ETX 2.8.1

### Steps To Reproduce

1. install ETX 2.8.2
2. open a model that was previously in SFHSS
3. select "Model settings
4. select "internal RF"

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by coaster007** [comment]
similar problem with radiomaster boxer 2.8.2 (External MPM)

Selected protocol Eachine E129. 
After off/on Radio the protocol changed to JOYSWAY.
Reverted to 2.8.1 everything works again.

**Comment by mha1** [comment]
You can try this tx16s firmware based on current 2.8.2 built with PR 3435 on top of it. I'd appreciate your feedback if this fixes your problem too. 
[tx16s-2.8.2-PR Multi Single Source.zip](https://github.com/EdgeTX/edgetx/files/11151417/tx16s-2.8.2-PR.Multi.Single.Source.zip)

**Comment by mha1** [comment]
try this please [tx16s-2.8.2-PR Multi Single Source1.zip](https://github.com/EdgeTX/edgetx/files/11158074/tx16s-2.8.2-PR.Multi.Single.Source1.zip)

**Comment by LS-67** [comment]
it still does not work !

**Comment by mha1** [comment]
What exactly are you doing? You are doing everything on the radio, no Companion, correct?

I tried this but can't reproduce your problem:
- TX16s, flashed 2.8.2 release, Multi 1.3.3.20
- power up radio
- go to select model
- hit new model, select blank model
- go to model settings
- hit internal rf, select Multi, select Futaba (SFHSS comes up as RF Protocol)
- turn off radio
- turn on radio
- failsafe warning pops up, press RTN to continue
- go to model settings
- select internal rf
- Futaba SFHSS is still selected

Please post exact procedure to reproduce

**Comment by mha1** [comment]
This is odd. Where did you get the firmware? self build? language build? 

Go to radio setting, version. Please post a screen shot of the internal RF / external RF settings
Go to radio setting, version. Please post a screen shot.

go to model setup, internal RF (does ist say 1.3.3.20?)
hit Mulit and set to Off
turn of radio
turn on radio
go to model setup, internal RF
change from Off to Multi again
does a pop come up saying scanning (or similar)

**Comment by LS-67** [comment]
The firmware is tx16s-2.8.2-selfbuild (9c3c6c3e)
Date 2023-04-05
Time 11:40:19
OPTS : bluetooth, crossfire,ghost,afhds3,noheli,internalgps,internalmilti,internalaccess,multimodule,luac,cli,passthrough,cli
In the model setup, internal RF, the module status is V1.3.3.20 TAER
When i do this : 
"hit Mulit and set to Off
turn of radio
turn on radio
go to model setup, internal RF
change from Off to Multi again
does a pop come up saying scanning (or similar)"

Yes, a pop come up saying "MPM Scanning protocols"

**Comment by mha1** [comment]
I doubt it makes a difference but please use the official release and try the sequence I first posted again. 
[tx16s-03e80fb-2.8.2-release.zip](https://github.com/EdgeTX/edgetx/files/11160857/tx16s-03e80fb-2.8.2-release.zip)

**Comment by coaster007** [comment]
@mha1 the 2.8.2 version is downloaded from the edgetx homepage (official release).
I haven't see any "MPM scanning  ..." screen.
the question is why the 2.8.2 version changed the index in the multiprotocol.txt file to +1 ?

**Comment by mha1** [comment]
@coaster007 there was a change for some invaldi protocol (XK). But so far I can't reproduce your problems. I wonder what is different.

@LS-67 have you tried this:
```
    TX16s, flashed 2.8.2 release, Multi 1.3.3.20
    power up radio
    go to select model
    hit new model, select blank model
    go to model settings
    hit internal rf, select Multi, select Futaba (SFHSS comes up as RF Protocol)
    turn off radio
    turn on radio
    failsafe warning pops up, press RTN to continue
    go to model settings
    select internal rf
    Futaba SFHSS is still selected
```

please pot your your exact procedure to reproduce

**Comment by LS-67** [comment]
I do this "TX16s, flashed 2.8.2 release, Multi 1.3.3.20
    power up radio
    go to select model
    hit new model, select blank model
    go to model settings
    hit internal rf, select Multi, select Futaba (SFHSS comes up as RF Protocol)
    turn off radio
    turn on radio
    failsafe warning pops up, press RTN to continue
    go to model settings
    select internal rf
    Futaba SFHSS is still selected"

Now, it's OK for a blank model (v2.8.2"FlyingDutchman") (even after turn off/on TX)

But still not OK with a model which was SFHSS before with ETX 2.8.1!

**Comment by coaster007** [comment]
o.k. the same test here (radiomaster boxer external MPM) new model with protocol E129 power off/on protocol still E129.
But existing E129 protocol changed to JOYSWAY

**Comment by mha1** [comment]
please post the 2.8.1 model.yml file of the model with Futaba/SFHSS selected

**Comment by LS-67** [comment]
How should I do to post it ? Drag and drop doesn't support the file type yml ?

**Comment by mha1** [comment]
zip it?

**Comment by mha1** [comment]
Thanks, this looks ok. If you can, please post the yml file showing the wrong protocol in 2.8.2

**Comment by LS-67** [comment]
Here it is
[NewFOKONG2.zip](https://github.com/EdgeTX/edgetx/files/11161355/NewFOKONG2.zip)

**Comment by mha1** [comment]
Well, at least it confirms what you are seeing:
moduleData:

before
```
  0:
    type: TYPE_MULTIMODULE
    subType: 21,0
```

after
```
  0:
    type: TYPE_MULTIMODULE
    subType: 22,0
```
means:
21,Futaba,SFHSS
22,J6PRO

I can reproduce your problem in the simulator. Let me see if I can find the root cause

**Comment by LS-67** [comment]
Thank's for your help !

**Comment by mha1** [comment]
please try this tx16s 2.8.2+ firmware and check if your problem still persists: [tx16s-2.8.2+.zip](https://github.com/EdgeTX/edgetx/files/11169958/tx16s-2.8.2%2B.zip)

**Comment by LS-67** [comment]
It seems to work...perfectly ! Thank you for the time you spent to solve my problem. (vers 2.82-selfbuild 03e80fb7)
