### ISSUE TITLE
Splash screen and welcome audio

### ISSUE THREAD

**Issue by audio98** [EdgeTX/edgetx#3438]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Is it possible to have the welcome splash screen and welcome audio come on at the same time and last for 7 seconds. Similar to OpenTX. Thanks

**Comment by Kevltan** [comment]
Agree with that 👍👍

**Comment by philmoz** [comment]
PR #3451 addresses this; however it is not possible to start playing the welcome sound immediately when the splash screen loads. This is due to other initialisation that needs to happen before the startup sound plays.
