### ISSUE TITLE
Voice seconds countdown mixed up

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#344]
Tx16s 
Firmware rc3
Timer count down voice seconds 5s 10s 20s 30s is mixed up eg... 30s= 5s countdown. 5s = 30s countdown etc

**Comment by jogybaer0815** [comment]
TX16S RC3 - not for me - i have installed sound pack rc3

**Comment by Mantamatt1** [comment]
I am using my original sounds from opentx. Would this be causing the
problem? As I was aware it's just a basic wav file. Suppose the naming of
the system files could be mixed? Simple fix if that's all it is as I'll
just rename the files to suit

**Comment by pfeerick** [comment]
Seems like the voice files must be wrong somehow... I got the correct 30, 20, 5, 4,3,2,1, timer one elapsed sounds... using the ETX voice pack. However, checking the files on both ETX and OTX voice packs suggests there should be no difference, and I don't know of any a changes to the SD card pack that would explain that difference. 

2.4.0-RC3, TX16S

**Comment by MervDale** [comment]
Countdown timer call settings are back to front

Eachine TX16S  Timer 2 settings

set 5 = time counter call starts at 30

set 10 = time counter call  starts at 20

set 20 = time counter call starts at 10

set 30 = time counter  call starts at  5

**Comment by pfeerick** [comment]
The above seems to be a different issue (so is in its own issue), but I can repeat that on the TX16S.

**Comment by Mantamatt1** [comment]
Yes it's the same issue, maybe I worded it badly!

**Comment by Mantamatt1** [comment]
Mine was doing it on timer 1. Never tried timer 2

**Comment by pfeerick** [comment]
Ah, sorry I thought you mean it was saying the wrong numbers! 🤦‍♂️ 

In that case, I can repeat it, and it's on both Timer 1 and Timer 2.

**Comment by rotorman** [comment]
Plz test #362 - that should fix it.

**Comment by Mantamatt1** [comment]
Just tested and is working as it should

**Comment by Mantamatt1** [comment]
On tx16s

**Comment by rotorman** [comment]
Thx for testing, closing.

**Comment by pfeerick** [comment]
It may be a style thing, but please leave issues open until the PRs are merged. As long as you use the keywords Fixes, Closes, Resolves #issue-id in your commit msg or PR, github will auto-close the issue WHEN the issues is actually fixed ;) If something goes wrong and the PR isn't merged, well, this isn't fixed and still open, isn't it ;)
