### ISSUE TITLE
Zorro Splash Screen brightness/contrast

### ISSUE THREAD

**Issue by mixMugz** [EdgeTX/edgetx#3455]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have a custom Splash Screen in my Zorro TX. When I turn TX on, I see my splash, but it's very bright, and seems like the contrast is set to a minimum. If I set the contrast in TX to the maximum, my splash screen keeps the same (low bright) behavior.

How I can control my contrast values for boot splash? Why it not used TX values?

Look second screenshot.

![image](https://user-images.githubusercontent.com/17923916/230848590-ccc3e940-a6c4-4e8f-a109-6d09a36ad41a.png)
![image](https://user-images.githubusercontent.com/17923916/230848604-3d37d144-3865-4e7f-a4a4-c5eaf83c5921.png)
![image](https://user-images.githubusercontent.com/17923916/230848627-a2a6688c-f50b-400e-b360-e6a01cbff786.png)

### Expected Behavior

The splash screen uses the main contrast value of TX.

### Steps To Reproduce

1. Set a custom splash screen with lots of blacks
2. Set contrast in TX to maximum value
3. Turn off TX
4. Turn back TX to ON
5. Look the splash screen

### Version

2.8.2

### Transmitter

Radiomaster Zorro

### Operating System (OS)

Windows

### OS Version

Window 10 22H2

**Comment by pfeerick** [comment]
Contrast value will be the firmware default, as at the time the splash screen is shown, the SD card hasn't even been mounted yet.

**Comment by mixMugz** [comment]
> Contrast value will be the firmware default, as at the time the splash screen is shown, the SD card hasn't even been mounted yet.

How do I change the default value of firmware (if I wish to build custom firmware)? For now, it seems like the default value is set to a minimum.

**Comment by mixMugz** [comment]
I think it will be a good idea if the default value will be middle between min and max.

**Comment by pfeerick** [comment]
It basically is, but it tweaked slightly for different radio screens. For the zorro, it's probably set to 15 (where the range is 10 to 30). 

If you're up for building a custom firmware, try adding ` || defined(RADIO_ZORRO)` to line 848 and see if that is enough... maybe it just needs to be lifted just that little bit more. 

https://github.com/EdgeTX/edgetx/blob/745c465bedbaea3657bfd453c6e60469be775ba8/radio/src/targets/taranis/board.h#L834-L859

**Comment by mixMugz** [comment]
> It basically is, but it tweaked slightly for different radio screens. For the zorro, it's probably set to 15 (where the range is 10 to 30).
> 
> If you're up for building a custom firmware, try adding ` || defined(RADIO_ZORRO)` to line 848 and see if that is enough... maybe it just needs to be lifted just that little bit more.


So, this workaround worked great! Now the Splash screen looks like all other screens, but now I have a boot problem. It's too dark =( There is any place in the code where I can set contact for the initial boot (dots)??

![image](https://user-images.githubusercontent.com/17923916/230948197-4f2558a9-6157-49b3-85d7-32646677d767.png)
![image](https://user-images.githubusercontent.com/17923916/230948224-463ee2c4-ae84-4682-a778-37d2ea1dc19a.png)
![image](https://user-images.githubusercontent.com/17923916/230948248-59ae1a20-0267-4f6b-80d2-8672cc0f5f0f.png)
![image](https://user-images.githubusercontent.com/17923916/230948266-6fd2acef-253a-421e-a7f1-b91d22f11df1.png)

**Comment by pfeerick** [comment]
> There is any place in the code where I can set contact for the initial boot (dots)??

Unfortunately, not anything that has been specifically designed for that... you'd probably have to fudge with the contrast in the startup animation function to make that look nicer. As good as the B&W screens for normal usage, they also seem somewhat ... cheap and nasty for want of a better description. While there seems to be something a bit weird about how we use them as the "contrast" changes depending on how much content there is on the screen, to be honest, I've not looked at the B&W lcd driving code so it may just be a function of how these screens work.
