### ISSUE TITLE
Failsafe not saved properly in model settings

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3462]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Failsafe is not persist properly in model settings.  Change settings -> switch another model -> switch back to the original model and the failsafe information is not saved.

I cannot figure when it will safe and when it will not.  It is a bit strange, sometimes it can safe, but sometimes cannot.

### Expected Behavior

Failsafe should persist properly.

### Steps To Reproduce

1. Create a new model
2. Internal module -> MPM -> WFLY2
3. Set custom failsafe Ch1-Ch8 -100, +100, -100, + 100 etc
4. Switch to another model
5. Switch back original model
6. Only ch1-ch5 has proper values, ch6-8 all shows 0

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by toglide** [comment]
I'm having the same problems when power cycling the radio TX16s / TX16MK2  

https://youtu.be/v7V3p5gZSHE
