### ISSUE TITLE
Tx16S Use Roller to Setup FRM303, UI components not follow the order of display

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3477]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

External RF Setuo, when setting up the FRM303, hard to address the type using the roller:

Mode: FLYSKY -> AFHDS3 ->Channel Range CH1 (skipped the type fields) ->CH18 ->Failsafe mode -> Receiver ID -> bind -> Type (wrong order) .....

### Expected Behavior

Mode: FLYSKY -> AFHDS3 ->Type -> Module Options -> Channel Range CH1 ->CH18 ->Failsafe mode -> Receiver ID -> bind

### Steps To Reproduce

1. Model Settings
2. External RF
3. Walk with roller to different fields

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by philmoz** [comment]
The FlySkySettings class deletes and re-creates all the controls in the module options section (between Mode and Channel Range). This causes the order of the controls on the page to change when scrolling.

It needs to be rewritten to show/hide the controls instead.

I can look at this in the next couple of days if no one else is fixing it.

I also noticed that pressing the 'Module options' will crash the simulator.

**Comment by richardclli** [comment]
> The FlySkySettings class deletes and re-creates all the controls in the module options section (between Mode and Channel Range). This causes the order of the controls on the page to change when scrolling.
> 
> It needs to be rewritten to show/hide the controls instead.
> 
> I can look at this in the next couple of days if no one else is fixing it.
> 
> I also noticed that pressing the 'Module options' will crash the simulator.

Yes, please help to check.  Module options is updated by Flysky to bring setup features for PWM output for each channel.  You can check this PR to see what they have changed.  https://github.com/EdgeTX/edgetx/pull/3443

**Comment by richardclli** [comment]
Reverted the PR, will work out the fix again.
