### ISSUE TITLE
Home screen after selecting model

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#348]
Tx16s
Rc3
After selecting a model it just goes to the beginning of the list. Just seems to be a strange unnecessary thing to do!
Would be nice to just exit to my home screen so I can see the model I've chosen.

**Comment by jogybaer0815** [comment]
That should olso be the behavior for a long click...

**Comment by raphaelcoeffic** [comment]
If this is consensus, no problem with that. Please vote with „thumb up“ or „thumb down”.

**Comment by eshifri** [comment]
Exit to the home screen can be achieved by adding the following line 
this->onEvent(EVT_KEY_FIRST(KEY_EXIT));
to model_select.cpp at line 248.
It does not bring warnings or model notes though.
