### ISSUE TITLE
Cannot build installer for EdgeTX companion in Windows 10 (MSYS2)

### ISSUE THREAD

**Issue by RomanVlg** [EdgeTX/edgetx#3490]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

All steps done from here https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-%28MSYS2%29,
and all successful except one- building installer. (I've not using script all in one)

 The error is in the end of building windows installer
![image](https://user-images.githubusercontent.com/67912010/232870618-78b46e23-aa54-4537-8a77-54c391c49fbc.png)

Beside Companion and Simulator doesn't start without installer or missing QT.
![image](https://user-images.githubusercontent.com/67912010/232872567-cfd1ca38-d27d-466a-8c9c-b46081a0ec2d.png)

### Expected Behavior

Some mess in building path (QT)

### Steps To Reproduce

Just do step by step manual
https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-%28MSYS2%29

### Version

Nightly (Please give date/commit below)

### Transmitter

Jumper T-Pro

### Operating System (OS)

Windows

### OS Version

11

### Anything else?

commit 54e0d35

**Comment by RomanVlg** [comment]
So I reinstall all staff,  repeat manual  and it'all right

**Comment by pfeerick** [comment]
Gotta love computers, eh? Glad it's working for you now. :)
