### ISSUE TITLE
Mechanism for Updating UI by INT/EXT Modules

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3500]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There are a few Issues required such a mechanism, I list out all of them here so that we can handle these together:

- [x] https://github.com/EdgeTX/edgetx/issues/3491
- [x] https://github.com/EdgeTX/edgetx/issues/2713
- [x] https://github.com/EdgeTX/edgetx/issues/3046

### Expected Behavior

After packet received by the modules, if the module options screen is displayed, it need to be refreshed.

### Steps To Reproduce

Screen just not refreshed properly.

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18, Flysky NV14, Radiomaster TX16S / TX16SMK2

**Comment by mha1** [comment]
Please retest #2713 with #3504

**Comment by richardclli** [comment]
This placeholder is now all finished.
