### ISSUE TITLE
Global var precision is ignored in telimetry LUA script

### ISSUE THREAD

**Issue by oloendithas** [EdgeTX/edgetx#3525]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Setting GV1: Unit = -, Precision = 0.0, FM0 = 10,5
Call getValue("gvar1") from telemetry LUA script and get 105

### Expected Behavior

Setting GV1: Unit = -, Precision = 0.0, FM0 = 10,5
Call getValue("gvar1") from telemetry LUA script and get 10.5

### Steps To Reproduce

Setting GV1: Unit = -, Precision = 0.0, FM0 = 10,5,
Create telemetry LUA script and call getValue("gvar1") from it

### Version

2.8.2

### Transmitter

BetaFPV LiteRadio3 Pro

### Anything else?

Also on 2.8.3

**Comment by mha1** [comment]
I can confirm this issue and put in PR to fix this. Please fetch test firmware at https://github.com/EdgeTX/edgetx/actions/runs/4832905350?pr=3540 under Artifacts and report if this solves your issue.
