### ISSUE TITLE
More bugs with Czech language Radiomaster Zorro 2.8.3

### ISSUE THREAD

**Issue by japanel** [EdgeTX/edgetx#3526]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Maybe bad translation or bad display of Czech characters with diacritics. First character with diacritics on line missing. Pls see attached pictures. Red text is correct.

### Expected Behavior

Right Czech translation, correct displaying characters with diacritics.

### Steps To Reproduce

Scroll through the menu with CZ firmware.

### Version

Other (Please specify below)

### Transmitter

Radiomaster Zorro

### Anything else?

![IMG20230424101254](https://user-images.githubusercontent.com/123984406/234039071-b8ca744c-f9d5-4c28-9925-2c0059e459cd.jpg)
![IMG20230424101337](https://user-images.githubusercontent.com/123984406/234039077-3194778e-886c-40ad-bf0b-48cbf3c2cd41.jpg)
![IMG20230424101350](https://user-images.githubusercontent.com/123984406/234039078-7e1d5453-9329-4ed6-abad-f26f11b1871b.jpg)
![IMG20230424101426](https://user-images.githubusercontent.com/123984406/234039079-7ff4fcaa-8d45-44fd-bf6d-e6e6e1d44500.jpg)
![IMG20230424101503](https://user-images.githubusercontent.com/123984406/234039081-4a4468cc-1f4b-4817-9b8d-e381fc94ada6.jpg)
![IMG20230424101544](https://user-images.githubusercontent.com/123984406/234039083-e563abfe-39f8-47d3-b636-a7c18d00f3bc.jpg)
![IMG20230424101638](https://user-images.githubusercontent.com/123984406/234039085-ac049956-73eb-4412-90a0-8a6772ef4e55.jpg)
![IMG20230424101652](https://user-images.githubusercontent.com/123984406/234039087-e3db1675-83ff-4529-9482-99b5d41e210e.jpg)
![IMG20230424101727](https://user-images.githubusercontent.com/123984406/234039090-742bd1b5-12e1-40fe-8d89-c35e74225e97.jpg)
![IMG20230424101744](https://user-images.githubusercontent.com/123984406/234039097-4256cf19-fbfc-4823-9199-760144c926bb.jpg)
![IMG20230424101853](https://user-images.githubusercontent.com/123984406/234039100-8b0a3ea7-e05c-4033-8945-d6ec82b237d7.jpg)
![IMG20230424100928](https://user-images.githubusercontent.com/123984406/234039105-31f97d25-e483-4b3e-ad75-28445011db61.jpg)
![IMG20230424100946](https://user-images.githubusercontent.com/123984406/234039108-c3f628b6-9f34-4d5a-acfb-c2cae1085145.jpg)
![IMG20230424101042](https://user-images.githubusercontent.com/123984406/234039111-d4fb4ce5-d10d-4d92-a8ac-162c637a39c8.jpg)
![IMG20230424101111](https://user-images.githubusercontent.com/123984406/234039114-41cccfd1-5392-4832-9a06-7d5f4f42d039.jpg)
![IMG20230424101122](https://user-images.githubusercontent.com/123984406/234039115-97a51a00-1dd4-4791-b420-d2b8db661f0f.jpg)
![IMG20230424101136](https://user-images.githubusercontent.com/123984406/234039118-ded3c23d-5f75-4868-a0d1-aba541e5dabd.jpg)

**Comment by japanel** [comment]
Hi, I would like to ask, if will be edgetx functional CZ language. Every 2.8 version is bad. It was  fine in OpenTx but it is unusable in EdgeTx. Will be it ok in 2.9 or no? Or I must go back to Open? Thank you so much.

**Comment by japanel** [comment]
> https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/common/stdlcd/utf8.cpp
> 
> Sind the upper case characters seem to be missing, a mapping of the upper case UTF code point to the lower case character from EdgeTX has to be added

Is some cases lower case characters are bad too. Maybe extra problem with "ž".
![IMG_20230719_173229](https://github.com/EdgeTX/edgetx/assets/123984406/401d978b-90f5-4775-aeae-f70d0adeb3c3)

**Comment by 3djc** [comment]
> https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/common/stdlcd/utf8.cpp
> 
> Sind the upper case characters seem to be missing, a mapping of the upper case UTF code point to the lower case character from EdgeTX has to be added

At least for the French issue, that is not the right solution, it needs to map the missing character to its 'master' upper case

**Comment by mha1** [comment]
I don't know the Czech language at all but just looked at one of your examples above. The text displayed for Radio Setup is defined as  `#define TR_RADIO_SETUP  "NASTAVENÍ RÁDIA"`

The extended ASCII code (like Windows 1250) knows the letter "Í" (Latin capital letter I with acute) but the Czech _utf8_lut doesn't define "'Í ", it only defines "í" (Latin small letter I with acute). Same for the letter "Á". 

I think Czech language requires the same exercise @3djc went through for the French language. Change all capital letters with diacritics to lower case letters with diacritics in cz.h. The z issue might be a different problem which needs looking into. 

Example: `#define TR_RADIO_SETUP  "NASTAVENí RáDIA"`

@3djc correct?

**Comment by gagarinlg** [comment]
The issue here is the readability on the B&W when you are trying to display capital letters with the extras above them. There is just not enough room.

**Comment by Eldenroot** [comment]
I am a Czech guy... yes, we need same treatment - we use special symbols - ĚŠČŘŽÝÁÍÉÓÚŇ (I hope that I have covered all :) and non-capitals as well)

**Comment by mha1** [comment]
@eldenroot I'm not sure but there might be no visible difference in a capital or lower special symbol. So converting the upper case characters with diacritics to lower case characters with diacritics should solve all problems apart the z problem which needs some analysis. You agree? 

If so I'll do the case conevrsion and make a private build for you and @japanel to check.

Btw: other languages like PL, ES might be affected too

**Comment by Eldenroot** [comment]
Unfortunately I cannot test it. I do not have working X9D+2019 anymore (SD card issue, cannot boot up the radio - sd card is inserted but it still displays no sd card... tested with at least 10 others cards, formated many way but without any luck). I have now only T16S MKii

**Comment by mha1** [comment]
"no visible difference in a capital or lower special symbol." Strike that, of course there is a difference. But I was looking at @japanel's proposal which has a lower case e special symbol in an otherwise all caps word.

![image](https://github.com/EdgeTX/edgetx/assets/5615068/4f2e6d96-11ae-4397-908d-a0b9c1c9fbf8)

**Comment by mha1** [comment]
It would be the same language file for the TX16s, so texts apart from the ones with short/long versions are the same

**Comment by mha1** [comment]
Example:
now: `#define TR_FSW_RESET_TIMERS          "Čas1","Čas2","Čas3"` --> not working
then: `"čas1","čas2","čas3"`

**Comment by gagarinlg** [comment]
Maybe it would be better to convert the characters on the fly to lower case on the B&W radios and keep them in upper case on color LCD?

**Comment by japanel** [comment]
> @Eldenroot I'm not sure but there might be no visible difference in a capital or lower special symbol. So converting the upper case characters with diacritics to lower case characters with diacritics should solve all problems apart the z problem which needs some analysis. You agree?
> 
> If so I'll do the case conevrsion and make a private build for you and @japanel to check.
> 
> Btw: other languages like PL, ES might be affected too

Hello, if needed I can flash my Zorro with your build and test it.

**Comment by philmoz** [comment]
In radio/src/gui/common/stdlcd/utf8.cpp the CZ mapping array is missing the 'Á' character, so the subsequent font offsets are wrong.

It should be:
```
#elif defined(TRANSLATIONS_CZ)
static wchar_t _utf8_lut[] = {
  L'á', L'č', L'é', L'ě', L'í', L'ó', L'ř',
  L'š', L'ú', L'ů', L'ý', L'Á', L'Í', L'Ř',
  L'Ý', L'ž', L'É',
};
```

**Comment by philmoz** [comment]
> The issue here is the readability on the B&W when you are trying to display capital letters with the extras above them. There is just not enough room.

Not necessarily - the characters Ř, Ý, Á, Í, and É are already in the CZ font for B&W radios as capitals.

**Comment by mha1** [comment]
looking at @Eldenroot's list there are still quite a few special characters missing. Adding the accented A is booked. What's the best strategy for the rest of the missing ones? E.g. capital C is used, see example above.

**Comment by 3djc** [comment]
> Maybe it would be better to convert the characters on the fly to lower case on the B&W radios and keep them in upper case on color LCD?

Why ? It has never been needed before, there is no reason for that. As said above, it was perfect in Otx, we just have to match that

**Comment by 3djc** [comment]
> I think Czech language requires the same exercise @3djc went through for the French language. Change all capital letters with diacritics to lower case letters with diacritics in cz.h. The z issue might be a different problem which needs looking into.
> 
> @3djc correct?

I cannot comment for Czech, but for French, the issue is there is a new english bashing trend that recommend using accented capital that nobody uses (I actually have no clue how to make those with my french keyboard, thats how unused they are). So all the non existing  upper case accented capital need to be moved to their parent upper case value. So É, È, Ê (there are others but there where no example to copy paste from) need to be mapped to E, same goes for the other voyels and C (with ç)

**Comment by mha1** [comment]
@3djc you did the mapping by changing texts in fr.h, correct?

For CZ:
Adding Á to the utf lookup table should fix some of the problems (thanks @philmoz). 

But there are still special characters left with no representation in cz fonts to deal with:
- Ě,Š,Č,Ž,Ú,Ů, - used in cz.h -> could be replaced in cz.h with their existing lower case counterparts
- Ó - not used in cz.h - could be replaced in cz.h with its existing lower case counterparts
- Ň - not used in cz.h - no replacement possible, needs font 

Better ideas?

**Comment by 3djc** [comment]
Yes, but that was wrong, I have now added an substitution routine, much better imho

**Comment by 3djc** [comment]
Fixed this issue as part of  #3827. thanks @philmoz for https://github.com/EdgeTX/edgetx/issues/3526#issuecomment-1642901806

**Comment by mha1** [comment]
The substitute table should take care of all missing capital letters:

```
static wchar_t _utf8_substitution_lut[] = {
    L'Ě', L'ě',
    L'Š', L'š',
    L'Č', L'č',
    L'Ž', L'ž',
    L'Ú', L'ú',
    L'Ů', L'ů',
    L'Ó', L'ó',
    L'Ň', L'N'
};
```
The last entry is replaced with a standard N because there is no lower case n with hat avilable, all other missing capital letters have a lower case counterpart.

**Comment by Eldenroot** [comment]
But we use lower case ň in Czech

**Comment by mha1** [comment]
I guessed so. Maybe I'm wrong but there is no ň in the CZ fonts. And you are right, ň is used on two occasions in cz.h.#

Until ň is part of the CZ font ň should also be replaced by a standard n.

@3dj update:
```
static wchar_t _utf8_substitution_lut[] = {
    L'Ě', L'ě',
    L'Š', L'š',
    L'Č', L'č',
    L'Ž', L'ž',
    L'Ú', L'ú',
    L'Ů', L'ů',
    L'Ó', L'ó',
    L'Ň', L'N'
    L'ň ', L'n'  
};
```

**Comment by 3djc** [comment]
@Eldenroot are some of this list unused ?

**Comment by Eldenroot** [comment]
Ň could be replaced by N, ň by n

**Comment by mha1** [comment]
static wchar_t _utf8_substitution_lut[] = {
    L'Ě', L'ě',
    L'Š', L'š',
    L'Č', L'č',
    L'Ž', L'ž',
    L'Ú', L'ú',
    L'Ů', L'ů',
    L'Ó', L'ó',
    L'Ň', L'N'
    L'ň', L'n'  
};

This was my proposal as long as the special N's are not in the fonts

**Comment by philmoz** [comment]
Adding 'ň' to the font is easy enough; but when I opened the 5x7 font image source for CZ there is 'speaker' icon in the image??? It also exists in the PL font; but no others.

Anyone know if this is used anywhere?

![Screenshot 2023-07-21 at 7 55 30 am](https://github.com/EdgeTX/edgetx/assets/9474356/96eea3ad-cf89-4033-98f6-ac1127913d5a)

**Comment by japanel** [comment]
Hello guys, I would like to ask if there is a version to test or not, if so I can do it. Thank you.

**Comment by 3djc** [comment]
What radio do you use ?

**Comment by 3djc** [comment]
bootloader flashing is fine, any sd content for 128 is fine, just copy your current one for example

**Comment by 3djc** [comment]
It should

**Comment by japanel** [comment]
> It should

@3djc I flash your version and quick look and czech language look amazing, very good job thank you. Only I found problem with contrast on some pages, I tried make fotos. In reality it looks even worse than in the picture. This is how bad the contrast is on pages that don't contain many characters.
Maybe I can report it like new issue? What you mean? I dont see this issue in previous version. Thank you for your time.
![IMG20230726214703](https://github.com/EdgeTX/edgetx/assets/123984406/0ca92711-c2ee-4d83-bad3-eed4b91cfa54)
![IMG20230726214651](https://github.com/EdgeTX/edgetx/assets/123984406/6e341ee3-42ef-471f-84f0-a08c83768848)

**Comment by japanel** [comment]
@mha1 @philmoz Good evening guys, I find one more czech symbol is missing Ď and ď. I thing not used now, but maybe in futuru it will be needed.

**Comment by Eldenroot** [comment]
Good catch

**Comment by 3djc** [comment]
Nothing can be done on our end for the screen contrast issue, it is a hardware issue on screen themselves, that cannot drive power correctly depending on what is displayed

**Comment by japanel** [comment]
> Nothing can be done on our end for the screen contrast issue, it is a hardware issue on screen themselves, that cannot drive power correctly depending on what is displayed

Ok, thank for your reply.
