### ISSUE TITLE
Boxer Debug Keys

### ISSUE THREAD

**Issue by Shouldercannon** [EdgeTX/edgetx#3533]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the Switches menu, some of the button names do not correspond to the description and the functionality is mixed up.
![Defect](https://user-images.githubusercontent.com/94894541/234941180-6242083f-46ad-4baf-baa8-49f09f1128eb.png)

### Expected Behavior

The Switches menu should look something like this.
![Normal](https://user-images.githubusercontent.com/94894541/234941387-3948107e-a1a5-4436-90ac-698973299bf2.png)

### Steps To Reproduce

1. Push button SYS.
2. Go to page 6 (Hardware).
3. Go to the bottom of the menu and press Keys.

### Version

2.8.2

### Transmitter

Radiomaster Boxer

### Operating System (OS)

Windows

### OS Version

Win10 x64 22H2

### Anything else?

This problem has been observed since version 2.8.1 and was inherited until version 2.8.3.

**Comment by pfeerick** [comment]
Thanks for the report :)
