### ISSUE TITLE
TX16S Hang with Sound+Vibration Loop when Switching Models with Rx Connected

### ISSUE THREAD

**Issue by ssvv123** [EdgeTX/edgetx#3534]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When a quad is connected to my Radiomaster TX16S radio, and I attempt to change to a different model profile via the touchscreen, the radio will refuse any new inputs, and begin vibrating constantly while repeating "receiver still connected" for approximately 10 seconds before rebooting. It will then be in Emergency Mode until power cycled again. If the battery pack is removed during this tantrum, it will be in Emergency Mode the next time it is powered on, until power cycled again. The profile will not have changed.

### Expected Behavior

The radio will change to a different model profile seamlessly without throwing an error, or will prompt to override with a warning.

### Steps To Reproduce

1. Power on radio with external ELRS module
2. power on quad which is bound with radio
3. tap once on touchscreen to show menu
4. tap on model select button
5. tap on any other model profile than the currently active one
6. brace yourself

### Version

2.8.1

### Transmitter

Radiomaster TX16S

### Anything else?

This is using an external ELRS module (Happymodel ES24TX Pro)
No Model ID is set for any of my profiles
This has been reproduced on a Mobula 7 1S w/ SPI ELRS and a 5" SpeedyBee DIY with Happymodel EP2 Rx
The quad is no longer connected to the radio after this crash, so if this were done while flying that would mean a failsafe for sure.
This happens every time these steps are followed without variation

**Comment by ssvv123** [comment]
Video of bug can be found at https://vimeo.com/821821520

**Comment by philmoz** [comment]
This should be fixed in 2.8.2. Please give 2.8.2 or 2.8.3 a try,

**Comment by ssvv123** [comment]
Whoops, you're correct! 
Fixed by flashing 2.8.3 

Thanks <3
