### ISSUE TITLE
Companion simulator startup data load error on exported model

### ISSUE THREAD

**Issue by icebreaker-ch** [EdgeTX/edgetx#3537]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

Version: EdgeTx_Companion_2.8.3-x86_64.AppImage

When exporting 1 Model and open the model file afterwards, the simulation of this model aborts with an error box "Data Load Error, Error occurred while starting simulator". 
The last lines of the terminal output:
`screenData:
  0:
    LayoutId: Layout2P1
    layoutData:
      options:
        0:
          type: Bool
          value:
            boolValue: 1
        1:
          type: Bool
          value:
            boolValue: 1
        2:
          type: Bool
          value:
            boolValue: 1
        3:
          type: Bool
          value:
            boolValue: 1
        4:
          type: Bool
          value:
            boolValue: 0
view: 0
modelRegistrationID: ""
[D] StorageFormat::setError():80 - [sdcard] error: Error opening file /tmp/etx-gJKmxH/MODELS//home/sro/Docume in write mode:
No such file or directory.
`

### Expected Behavior

SImulator should open and run.

### Steps To Reproduce

1. Open EdgeTX Companion
2. Select a model from the List and choose "Export 1 model"
3. Save the model to an arbitrary yml-file
4. Open the yml-file or drag and drop the file to the companion
5. Press OK for the warning, that appears
6. Run the simulator from the model in the new window
7. The "Data Load Error" box appears
8. Simulation does not start

### Version

Other (Please specify below)

### Transmitter

FrSky X10 / X10S (ACCST)

### Operating System (OS)

Linux

### OS Version

Linux Mint 21.1 Cinnamon

### Anything else?

![Screenshot from 2023-04-28 00-46-21](https://user-images.githubusercontent.com/3645375/235006827-f6ff6bd7-e957-4776-ab79-c5b797ea86da.png)

**Comment by elecpower** [comment]
Confirmed bug

> [sdcard] error: Error opening file /tmp/etx-gJKmxH/MODELS//home/sro/Docume in write mode: No such file or directory.

The cause is the temporary path is a mash up of 2 directory paths (notice // after MODELS). Occurs when the models and settings have not been saved to etx before launching simulator.
