### ISSUE TITLE
Add EL18 radio name for 2.9, now only in v2.8

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3538]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Since we decided to go for unifying targets, therefore the PR that help to do show EL18 naming in firmware is not merged in main.  We need to do this because unifying targets are not ready yet.

### Expected Behavior

EL18 firmware should shows EL18.

### Steps To Reproduce

1. System
2. Info
3. Firmware shows NV14 instead of EL18.

### Version

Nightly (Please give date/commit below)

### Transmitter

Flysky EL18

**Comment by gagarinlg** [comment]
this cann be fixed after creating the 2.9 branch
