### ISSUE TITLE
Incorrect display of the crosshair vertically

### ISSUE THREAD

**Issue by Shouldercannon** [EdgeTX/edgetx#3551]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When checking the touch screen operation, a crosshair showing the place of touch is displayed.
The crosshair vertically is not displayed correctly.
![IMG_20230430_081426](https://user-images.githubusercontent.com/94894541/235352423-c78192f5-f83b-46c1-a060-3475c53ad665.png)

### Expected Behavior

The crosshair should be horizontal and vertical together touching.

### Steps To Reproduce

1. Push Sys and go to Hardware menu.
2. Go to the bottom of the Hardware menu and select Analogs.

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Win10 x64 22H2

### Anything else?

This problem has been observed since version 2.8.0 and was inherited until version 2.8.3.

**Comment by ggoraa** [comment]
one of those rare cases when debug helpers are the ones that actually malfunction

**Comment by philmoz** [comment]
This is fixed in PR #3240 which I believe is scheduled for the 2.9 release.

**Comment by pfeerick** [comment]
Indeed it is - #3240 is merged so it's present in the nightly builds leading up to 2.9
