### ISSUE TITLE
EL18 - SWH/SWE switch when 3POS not triggering special functions

### ISSUE THREAD

**Issue by llwingok1** [EdgeTX/edgetx#3560]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

SWH, the original factory switch is a 2-stage switch, I replaced it with a 3-stage switch, In the system, I have already changed the SWH from a two-stage switch to a three-stage switch.In the monitoring, I can see that the output state of the SWH is normal: -100, 0, 100.
However, in the special functions, I set 3 entries for the three values of this switch, -100, 0, 100, each triggering different sounds. I found that the correspondence is incorrect, and the entry with a value of 0 cannot be triggered.The output value of this switch has always been normal

 Could an expert please help take a look?

### Expected Behavior

Fix this issue

### Steps To Reproduce

There is no need to replace the switch. You can use a two-stage switch for testing. During the testing process, keep the two-stage switch in the middle to simulate a three-stage switch.
1、Change the SWH in the system to a 3-stage switch.
2、In the monitoring, test whether all three stages of the switch are working properly.
3、In the special function settings, select the SWH switch and set three special function entries for the three states of the switch.
4、When the switch is operated, it cannot correspond to the set special function entries.

### Version

2.8.2

### Transmitter

Flysky EL18

**Comment by pfeerick** [comment]
This sounds somewhat similar to #3101

**Comment by philmoz** [comment]
What does the keys debug page show for SWH (Radio Settings, Hardware tab, Debug section).

Does it show the correct up, middle and down icons like the other three pos switches?

**Comment by llwingok1** [comment]
> SWH的按键调试页面显示什么（无线电气设置、硬件选卡、调试部分）。
> 
> 它是否像其他三个位置一样显示正确的上、中、下图标？

swh可以显示上、中、下，而且该通道对应的输出值也是正常的，能正常输出-100、0、100这三个值。我用这个通道，在bf固件里映射一些功能时，也是正常的，比如自稳模式、半自稳模式、手动模式，可以正常切换。
但是这个拨杆在edgetx里，设置特殊功能时，无法正常选中“中”的状态，当开关到“中”时，显示的是上，所以对应的逻辑条目会被选中，比如用这个摇杆控制声音。

**Comment by llwingok1** [comment]
> 这个听起有点像#3101

我在系统中，已经将这个开关已经改成3POS了，但是还是不行。
![1741683256036_ pic](https://user-images.githubusercontent.com/56796808/236370061-93531104-2c6a-40e8-8b43-6f1c1f0ae906.jpg)
![1751683256157_ pic_hd](https://user-images.githubusercontent.com/56796808/236370091-4e8457aa-5322-44c8-a536-f48caa69efe1.jpg)

**Comment by pfeerick** [comment]
Please try going to Radio Settings -> Hardware -> Debug / Keys (at the very bottom). Does SWH show an up arrow when up, a dash when in the middle position, and a down arrow when down? i.e. Does it behave like SWB?

**Comment by llwingok1** [comment]
> 请尝试转到 Radio Settings -> Hardware -> Debug / Keys（在最底部）。SWH 是否在向上时显示向上箭头，在中间位置时显示破折号，在向下时显示向下箭头？即它的行为是否像 SWB？

yes,

> Please try going to Radio Settings -> Hardware -> Debug / Keys (at the very bottom). Does SWH show an up arrow when up, a dash when in the middle position, and a down arrow when down? i.e. Does it behave like SWB?



> Please try going to Radio Settings -> Hardware -> Debug / Keys (at the very bottom). Does SWH show an up arrow when up, a dash when in the middle position, and a down arrow when down? i.e. Does it behave like SWB?

yes,it like swb。SWH show an up arrow when up, a dash when in the middle position, and a down arrow when down


https://user-images.githubusercontent.com/56796808/236414846-4246c285-6cff-40d1-9e7c-7e28ba6d1dce.mp4

**Comment by pfeerick** [comment]
Thanks for that - that should narrow down where the fault in the code could be.

**Comment by richardclli** [comment]
你用其他3段開關可以做到嗎?  是不是只有改了的3段有問題?
Did you have problem using other 3 pos switch?  Or only the modded switch not working?

**Comment by llwingok1** [comment]
> 你用其他3段打开可以做到吗？是不是只有改了的3段有问题？ 您在使用其他 3 位开关时遇到问题吗？或者只有修改后的开关不工作？

原装的哪个是三段的？我已经不记得我换过几个开关了，我回去试试

**Comment by richardclli** [comment]
> > 你用其他3段打开可以做到吗？是不是只有改了的3段有问题？ 您在使用其他 3 位开关时遇到问题吗？或者只有修改后的开关不工作？
> 
> 我查了下，EL18原厂的SWB、SWF、SWG是3段开关，我一会去试试看

SWF是3段的，我試不到你說的問題

**Comment by pfeerick** [comment]
On both of my EL18, it still has SWB, SWF and SWG as three pos like the NV14, and I can use all three to trigger SFs in all three positions. 

However, in the production models, it appears SWC changed to 3 pos (from a momentary) and SWE changed to 2pos (from a momentary). I'm not sure how SWH would actually work as a 3pos - didn't know that sort of mod was supported.

**Comment by llwingok1** [comment]
> > > 你用其他3段打开可以做到吗？是不是只有改了的3段有问题？ 您在使用其他 3 位开关时遇到问题吗？或者只有修改后的开关不工作？
> > 
> > 
> > 我查了下，EL18原厂的SWB、SWF、SWG是3段开关，我一会去试试看
> 
> SWF是3段的，我試不到你說的問題

我刚才做了个全面测试，发现了具体故障问题点：
1、故障复现条件：在特殊功能中，新建后，动作选择“播放声音”模式，工作异常，无法选择开关的中间状态“-”。选择“教练”模式，工作正常，可以正常选择到上、中、下三个状态。其余模式没有测试
2、故障涉及开关：SWE、SWH（原厂的3段开关SWB、SWF、SWG均正常，无问题）
3、故障复现方法：在复现故障的时候，不需要将SWE、SWH的物理开关更换为3段开关，可以使用原厂的2段开关模拟3段开关。只需要在系统中，改变需要测试的开关为3段，拨动的时候，在开关拨动的行程中间，用手扶住，强制停留，就可以测出中间状态“-”。

**Comment by llwingok1** [comment]
> On both of my EL18, it still has SWB, SWF and SWG as three pos like the NV14, and I can use all three to trigger SFs in all three positions.
> 
> However, in the production models, it appears SWC changed to 3 pos (from a momentary) and SWE changed to 2pos (from a momentary). I'm not sure how SWH would actually work as a 3pos - didn't know that sort of mod was supported.

感谢，我也测试了，原厂的3段开关SWB、SWF、SWG均正常，无问题。出问题的是SWE和SWH，具体内容见上述回复

**Comment by pfeerick** [comment]
Thanks for that tip, yeah, I can reproduce that with SWC configured as a 3POS

**Comment by llwingok1** [comment]
> Thanks for that tip, yeah, I can reproduce that with SWC configured as a 3POS

EL18正面的部分SWA~D，我没有测试2POS——SWA、SWC、SWD，我只测试了正面的3POS——SWB，SWB是没问题的
EL18背面的开关SWE~H，这4个开关我都测试了，出问题的只有SWH和SWE
再次感谢大佬，希望能尽快修复该问题

**Comment by llwingok1** [comment]
> Thanks for that tip, yeah, I can reproduce that with SWC configured as a 3POS

EL18正面的部分SWA~D，我没有测试2POS——SWA、SWC、SWD，我只测试了正面的3POS——SWB，SWB是没问题的
EL18背面的开关SWE~H，这4个开关我都测试了，出问题的只有SWH和SWE
再次感谢大佬，希望能尽快修复该问题

**Comment by richardclli** [comment]
Interesting that not all the switches has problem.  The code should be common.............  Maybe I am wrong.

**Comment by richardclli** [comment]
@pfeerick I think I found the problem, it seems the switch definitions are all hardcoded.

https://github.com/EdgeTX/edgetx/blob/f800447cd5299dfec62f5e2c459ad49f762e15b7/radio/src/switches.cpp#L216-L237

**Comment by pfeerick** [comment]
Oh, that again... that puzzled me when I first saw it... since you can change some switches between 2 and 3 pos... 🤪

**Comment by richardclli** [comment]
> > Thanks for that tip, yeah, I can reproduce that with SWC configured as a 3POS
> 
> EL18正面的部分SWA-D，我没有测试2POS——SWA、SWC、SWD，我只测试了正面的3POS——SWB，SWB是没问题的 EL18背面的开关SWE-H，这4个开关我都测试了，出问题的只有SWH和SWE 再次感谢大佬，希望能尽快修复该问题

@llwingok1 你有在我的QQ群嗎?  我可以發你測試固件

**Comment by richardclli** [comment]
I have tested, my PR works now.

**Comment by llwingok1** [comment]
> > > 谢谢你的提示，是的，我可以用配置为 3POS 的 SWC 重现它
> > 
> > 
> > EL18正面的部分分SWA-D，我没有测2POS——SWA、SWC、SWD，我只测了正面的3POS——SWB，SWB是没有问题的EL18背面的开SWE-H，这4个开关我都测了，出问题的只有SWH和SWE 再次感谢大佬，希望能尽快修复该问题
> 
> @llwingok1你在我的QQ群里吗？我可以发你测试固定件

Edgetx开源控交流群。我在这个QQ群里，不知道大佬说的是这个吗？

**Comment by richardclli** [comment]
> > > > 谢谢你的提示，是的，我可以用配置为 3POS 的 SWC 重现它
> > > 
> > > 
> > > EL18正面的部分分SWA-D，我没有测2POS——SWA、SWC、SWD，我只测了正面的3POS——SWB，SWB是没有问题的EL18背面的开SWE-H，这4个开关我都测了，出问题的只有SWH和SWE 再次感谢大佬，希望能尽快修复该问题
> > 
> > 
> > @llwingok1你在我的QQ群里吗？我可以发你测试固定件
> 
> Edgetx开源控交流群。我在这个QQ群里，不知道大佬说的是这个吗？

是的，我是IQ博士
