### ISSUE TITLE
[B&W] Timers: Can't get to timer countdown time setting

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#358]
Once changing the timer countdown setting from silent to either beep, voice or haptic, I can't get to the time setting to change it from 10 seconds. 

![image](https://user-images.githubusercontent.com/5500713/123538359-e6e85d00-d777-11eb-9385-f2c2721cf7c9.png)

![image](https://user-images.githubusercontent.com/5500713/123538434-40e92280-d778-11eb-8afb-ee2ee3c52970.png)

**Comment by raphaelcoeffic** [comment]
@pfeerick is it only 128x64, or 212 as well?

**Comment by pfeerick** [comment]
Whoops, I gave the screenshots but forgot to lost names ... Affects t-lite and X9D+.
