### ISSUE TITLE
PPM: first channel omitted in PPM stream

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3597]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The first channel is not output in PPM streams. E.g. PPM set to CH1-CH8 will output 7 channels (CH2-CH8).

### Expected Behavior

All channels are output in PPM stream

### Steps To Reproduce

PPM settings for external module:

![image](https://github.com/EdgeTX/edgetx/assets/5615068/f7ddfc07-65b9-4561-b651-180be0ff76dd)

PPM stream with internal RF set to OFF and external RF set to PPM with above settings - `NOK`
All sticks at neutral. Channel monitor confirms alls channels 1 to 8 at 1500us. Notice there is only 7 channels transmitted.
![image](https://github.com/EdgeTX/edgetx/assets/5615068/9147a590-ff27-4848-9744-6926bad7107a)

Channel 2 stick set to minimum, channel monitor confirms 988us. Notice The first channel in the PPM stream reflects channel 2. Channel 1 is missing in the PPM stream
![image](https://github.com/EdgeTX/edgetx/assets/5615068/35cce7f8-40c4-4bf2-b544-799bcf056ed6)

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

nightly tx16s-d6e9472.bin

**Comment by koaxheli** [comment]
Channel 2 stick and channel 8 stick set to minimum, channel monitor confirms 988us. Note: The first channel and channel 7 in the PPM stream correspond to channel 2 and channel 8. 
Channels in PPM stream are shifted.
[IMG_021.ZIP](https://github.com/EdgeTX/edgetx/files/11496569/IMG_021.ZIP)

**Comment by mha1** [comment]
@koaxheli can you please test https://github.com/EdgeTX/edgetx/suites/12931660122/artifacts/698676182

**Comment by koaxheli** [comment]
@mha1,
Have tested the firmware tx16s-a3b5000.bin everything OK.
But when I rebuild my new FW with Github
then the error with the shift at the External RF
with PPM is still present.

**Comment by mha1** [comment]
Thanks for your fedback.

This is an issue, no solution. I offered a solution (PR https://github.com/EdgeTX/edgetx/pull/3598) which you tested ok as it seems. The PR is waiting to be merged. As long as it isn't  merged into main you'll still see the problem when building main. Just wait.
