### ISSUE TITLE
Use Global Variables names everywhere in the GUI instead of certain places only

### ISSUE THREAD

**Issue by Neutral67fr** [EdgeTX/edgetx#3623]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I often have problem to set up a Special Function or Widget using a global Variable, because those functions don't show the names of the GV but their standard number (GFx) instead.
When we have many GV it becomes complicated to remember what GV is what...
In some settings the system use the GV names (such as Input, Mixes...) which is convenient to identify each GV.

### Describe the solution you'd like

I would simply like that the system uses the GV names when they are set, each time we have to refer to a GV, everywhere in the GUI.
Exactly as the source inputs (switches, sliders, pot.) when they have been renamed in the radio settings. 

### Additional context

![GV names lack](https://github.com/EdgeTX/edgetx/assets/34441826/1978dd13-9e9e-4181-84ed-dd62d977752d)

**Comment by pfeerick** [comment]
This will partially/mostly be implemented by #2219 when merged.

**Comment by Fortesque0** [comment]
Hello,
Yes, it's necessary to see GV assigned name. For example to view value of GV using widgets, it's pretty crazy view on screen for example  GV1- GV2....instead assigned names.
