### ISSUE TITLE
Selecting POTS menu in causes radio to go into Emergency Mode

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#3633]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

It was reported to me in the Facebook group that selecting the POTS menu in the Hardware tab causes radio to go into Emergency Mode in Polish and French language versions in 2.8.0 thru 2.8.4 of the TX16s firmware. I have tested it as well (2.8.4) and can confirm that it happens in the PL version. The German (DE) version and English version does not do this (I did not try the french version). 

### Expected Behavior

It should not go into Emergency Mode.

### Steps To Reproduce

1. Install PL language version of EdgeTX on Radio
2. Go to Hardware tab in Radio Setting
3. Press the POTS button to access the POTS menu.
4. See the radio go into Emergency Mode.

### Version

2.8.4

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?

I did not test on any 2.9. nightlies to confirm as I do not have a PL version handy to test with.

**Comment by pfeerick** [comment]
I can repo the PL crash - it's due to a missing translation for "None". Can't repo the French one (on 2.8 head, at least, with no appreciable changes since 2.8.4, or with `main` will need more information for that one). Will be fixed momentarily in `2.8` and `main`, for inclusion with 2.8.5.)
