### ISSUE TITLE
Lost Models when adding PNG for Model Profile

### ISSUE THREAD

**Issue by picklebeijing** [EdgeTX/edgetx#3644]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Literally added a PNG for model profile, now i'm missing models.

### Expected Behavior

Models not missing

### Steps To Reproduce

nothing

### Version

2.8.4

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

macOS

### OS Version

13.4 Ventura

**Comment by pfeerick** [comment]
@picklebeijing Need "Steps To Reproduce" please... *how* are you adding images to the model... via Radio Settings -> SD Card? via Model Settings? Manually? Are you using Companion? 

Is this still present in 2.9?
