### ISSUE TITLE
ExpressLRS Joystick bluetooth cannot be used for simulators on PC for jumper t pro (and v2)

### ISSUE THREAD

**Issue by gumileeev** [EdgeTX/edgetx#3646]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I go to the script express lrs and activate the BLE Joystick. Then I find the device in the computer and connect it. But no simulator sees it. How to connect to the simulator via bluetooth? This function is not implemented for this?

### Expected Behavior

I'm looking to use bluetooth to connect. No need to use usb cable.

### Steps To Reproduce

I go to the script express lrs and activate the BLE Joystick. Then I find the device in the computer and connect it.

### Version

2.8.4

### Transmitter

Jumper T-Pro

### OS Version

win10

**Comment by pfeerick** [comment]
This is an ELRS issue... EdgeTX has nothing to do with the Bluetooth simulator functionality. Best to ask on the [ExpressLRS discord](https://discord.gg/expresslrs) and see what the folks there say. 

I've never used the BLE joystick capability before, but I just grabbed a ELRS TPro running 2.8.0, started the bluetooth joystick via ELRS Lua, connected to it on the computer (ExpressLRS Joystick) and it showed up when I checked the windows "game controller" control panel. I was then able to select and calibate it in Liftoff.
