### ISSUE TITLE
Companion Curve Labels allow 6 chars but truncated to 3 in radio

### ISSUE THREAD

**Issue by plarkinjr** [EdgeTX/edgetx#3674]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When creating curves in Companion, it is possible to give it a name 'abcdef' and save it, but when it is written to the Boxer radio, and read back, it is truncated to just 'abc'.   The radio only supports 3 characters in curve names.

### Describe the solution you'd like

On the curves names in companion, limit the number of characters allowed (3) to match that of the radio.

**Comment by elecpower** [comment]
Curve names are limited to 3 characters on all radios
