### ISSUE TITLE
Incorporate Sub_protocol C186 in E129 protocol on RadioMaster Boxer (module 1.3.3.20)

### ISSUE THREAD

**Issue by plarkinjr** [EdgeTX/edgetx#3677]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm on a Boxer and messing around with trying to use the E129 protocol subprotocol C186, but it is not an option. EdgeCompanion shows "Eachine E129" with subprotocol "Default" and a series of entries "???"  My radio is on edgetx-boxer firmware v 2.8.4 with "Int.Module "V1.3.3.7 AETR" 

I'm told that v 1.3.3.20 has it.
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#e129---83

I upgraded radio to 1.3.3.20, but Companion does not know about it.

### Describe the solution you'd like

Companion should have all the options in 1.3.3.20

**Comment by mha1** [comment]
PR #3435 merged into main 3 weeks ago fixed this. Recommend closing this issue.

![image](https://github.com/EdgeTX/edgetx/assets/5615068/221d77d4-4599-45a9-bf56-d4d749a600f4)
