### ISSUE TITLE
Add Sbus In feature for External module

### ISSUE THREAD

**Issue by pierrotm777** [EdgeTX/edgetx#3678]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

NO, i should like just to use the Sport Pin for use it as SbuS Input pin, inverted or not .

### Describe the solution you'd like

NO, i should like just to use the Sport Pin for use it as SbuS Input pin, inverted or not .

### Additional context

Use this SBUS input possiblity for use a Sbus output from a receiver.
It's possible with the Taranis before.
https://www.instructables.com/Simple-Taranis-X9D-Wireless-Trainer-Using-SBUS-Rec/

**Comment by 3djc** [comment]
What radio ?

By the way, it is NOT possible on Taranis using Sport pin, but another pin (sport pin is not a standard io pin)

**Comment by pierrotm777** [comment]
Hello 3djc, on a Radiomaster TX16S MkII .

**Comment by pierrotm777** [comment]
If you can add this feature for transmitters witch accept, I should like that.
Thanks,
Pierre

**Comment by Helipro** [comment]
> If you can add this feature for transmitters witch accept, I should like that. Thanks, Pierre

This feature works with a sbus receiver as a trainer and is under Radio Settings>Hardware> SBUS trainer

With aT16s you can also use a Bluetooth trainer
https://headtracker.gitbook.io/head-tracker/getting-started/wiring/option-2-wired/serial-bus-sbus/radio-master-tx16s-setup
