### ISSUE TITLE
CPN W64: simulator crashes on selection of SBUS external module

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#3680]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

W64 simulator crashes if SBUS is chosen as external RF module.

### Expected Behavior

Don't crash

### Steps To Reproduce

1. standalone simulator
- start Firmware Simulator 2.9
- goto model settings and select external RF module
- select SBUS

2. from Companion
- start Companion 2.9
- select File/New then click on +Model
- press cancel to exit the wizard
- double click on the newly created MODEL01
- select SBUS as external radio module
- press simulate

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### OS Version

Windows 10

### Anything else?

Companion W64 build:  Actions, main branch, Windows Companion 64-bit, chore: Translation catchup (#3619) - https://github.com/EdgeTX/edgetx/suites/13479597982/artifacts/740096546

Note: 
This crash was introduced with commit d80adcbc (#3055)

**Comment by pfeerick** [comment]
Ah, #3055... the PR that just keeps on giving 😆

**Comment by mha1** [comment]
pure bliss
