### ISSUE TITLE
battcheck (analog) widget not saved

### ISSUE THREAD

**Issue by stevempotter** [EdgeTX/edgetx#3684]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have tried 5 times to create a Battcheck (analog) widget on my screen. It creates fine, it works fine...Except that it vanishes when the TX radio is switched off. I have to re-create the widget every time I turn on the radio. I made sure I used the Back button enough times to remove the dotted line around the widget after creating it. I thought that would save it. Is there some other thing I need to do to make this widget persist across power-down of the TX?

### Expected Behavior

I expect all widgets to still be there each time I turn on the radio. I have not had this problem with any other widget. 

### Steps To Reproduce

1. Create a new Battcheck (analog) widget.
2. Enjoy using it for one flight.
3. turn off transmitter.
4. Turn transmitter back on.
5. Widget is gone, leaving a blank rectangle with no widget in it.
6. Go back to Step 1.

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by pfeerick** [comment]
Can you double check you're using a recent version of the widget/sdcard pack - I think there may have been a version of the widget that had too long a name, so wasn't saved.
