### ISSUE TITLE
crossfire 6.19 will not work at 400k

### ISSUE THREAD

**Issue by ror1948** [EdgeTX/edgetx#3688]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

TX16x with edgetx-firmware-nightly-ba56166f
TBS micro Crossfire module V2 with 6.19 and TBS crossfire nano Rx pro
unable to bind with a baudrate of 400k.
It binds at 115K but the output map never populates in the Lua script.
Using LUA script TBS Agent Lite 0.96

### Expected Behavior

bind with baudrate at 400k

### Steps To Reproduce

Tx(micro Tx module V2 installed in bay) 
Press MDL
Press External RF
Select baudrate 400k
Press RTN several times
press SYS button
select TBS AGENT LITE Lua script
Select Tx module
Select bind

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

edgetx-firmware-nightly-ba56166f

**Comment by ror1948** [comment]
works as expected with edgetx 2.8.4

**Comment by pfeerick** [comment]
I should be able to test this myself also in about two weeks as will be getting a crossfire set then.

**Comment by ror1948** [comment]
thanks
________________________________

**Comment by 3djc** [comment]
Cannot reproduce (compiled main as of today):

![image](https://github.com/EdgeTX/edgetx/assets/5167938/1e9b4b15-b7e6-48bb-9eef-5e1891ebdf15)

![image](https://github.com/EdgeTX/edgetx/assets/5167938/2c4804ca-89a7-47f7-9920-73fa10b7e736)

![image](https://github.com/EdgeTX/edgetx/assets/5167938/2cc41290-35f1-4504-a09b-30031dce0d4b)

**Comment by pfeerick** [comment]
Not so fast... there's two parts to this JC 😆 

> It binds at 115K but the output map never populates in the Lua script.

He wasn't able to bind at 400k, but was at 115k, but then can't do channel/output remapping in the Lua (not sure at what baud rate - it will probably never work at 115k). 

> works as expected with edgetx 2.8.4

Was that @ 400k baud rate?

**Comment by 3djc** [comment]
like so ?

![image](https://github.com/EdgeTX/edgetx/assets/5167938/4fc7a957-f991-46bd-9d06-3c3f1489d330)

**Comment by pfeerick** [comment]
That's the one :)

**Comment by ror1948** [comment]
Yes all worked at 400k with 2.8.4At 115k output map never populated .But it bound ok.On Jun 19, 2023 3:45 a.m., Peter Feerick ***@***.***> wrote:
Not so fast... there's two parts to this JC 😆

It binds at 115K but the output map never populates in the Lua script.

He wasn't able to bind at 400k, but was at 115k, but then can't do channel/output remapping in the Lua (not sure at what baud rate - it will probably never work at 115k).

works as expected with edgetx 2.8.4

Was that @ 400k baud rate?

**Comment by 3djc** [comment]
All done at 400k, binding and all those screenshots

**Comment by ror1948** [comment]
my CF Tx info
![CF-TX-micro](https://github.com/EdgeTX/edgetx/assets/98917767/1479d80e-964f-4f6b-b072-9ce57f96cb47)

**Comment by JimB40** [comment]
Reflash CRSF microTX with same 6.19 and chceck if problem still exist

**Comment by ror1948** [comment]
will do
does the version of boot loader matter?
i am using boot loader 2.8.0

________________________________

**Comment by ror1948** [comment]
OK good news

reflashed Tx with 6.19
Flashed RM with bootloader 2.9.0
Flashed RM with nightly Jun 18 2023

set at 400k baudrate


IT ALL WORKS fine
CRSF Rx output map etc populates quickly

Thanks to all

OK to close this issue

________________________________

**Comment by pfeerick** [comment]
Damn... that really is quite annoying... it's intermittent bugs like this that are the most frustrating. Fingers crossed it behaves now! :)

**Comment by JimB40** [comment]
#@pfeerick just to recap as this issue pops up frequently wit CRSF

1. "115k and output not loading".
Output channeles page have a lot of data 'behind'. One output option needs 3-4 CRSF chunk frames. Other features needs just 1 often. So with 115k which is too slow timeout is thrown because all chunks can't be read. Typical behavior of TBS Agent or Crossfire LUA with too low speed.

2. "Can't connect with 400k"
That is more puzzling. 
This re-flash (refresh) tbs firmware is old trick I've learned writing Agent. Not sure why it behaves like that. But it seems flashing process is not 101% proof.
Nevetheles with serial there are two parties that talk and few weeks ago we had some bug in etx fw that caused problems with CRSF. Seems it is gone now with latest nighlty.

**Comment by ror1948** [comment]
it may have been the bootloader version that i was using?
i was using 2.8.0 when i had the problem
now 2.9.0 and it is working.

maybe?

________________________________

**Comment by JimB40** [comment]
You did both at the same time so we can't pin point. You can flash back 2.8.4 bootloader (as this is 10 sec task) and check.
But I'd bet on CRSF FW reflash.

**Comment by kamik2** [comment]
https://github.com/EdgeTX/edgetx/issues/3688#issuecomment-1598064542

there are a few posts on facebook etc with the same issue. for some, it loses binding after power cycling the radio on the next day, and some loose binding mid-flight/ ion the ground after some time.
when those people flash their radio back to an older etx version or opentx, the issue is instantly fixed.

to me, it sounds like the model id gets lost/changed with some unknown trigger

**Comment by ror1948** [comment]
I did an update to nightly on a friend’s TX16S and it worked at 400k.
I updated bootloader  to 2.9.0 and nightly jun18 2023


- Ralph

**Comment by pfeerick** [comment]
> to me, it sounds like the model id gets lost/changed with some unknown trigger

The model id should not change unless you 1) change models (and the new model has a different model id), or 2) change the id manually (or possibly via a Lua script? - but in that case, it's self-inflicted). There is an edge case when switching models with some RF modules, whereby the the model ID is sent before the transmitter module is ready, but this would only result in no connection to the receiver (unless it's id is 0). If you power cycled the radio, or set the model id again once changing models (i.e. change it to something else, and then change it back), it should reconnect instantly. 

Outside of these specific cases, I would instead be suggesting there is a bug in the TBS firmware somewhere.

**Comment by Ddraig62SPD** [comment]
Thx for the insight & recommendations guys. Have just migrated from OpenTx 2.3.15 and was getting the exact same issue on all my X9D models. Running V2.8.4 Edge, V6.19 V1/V2 TX, V6.19 Nano RX. 
Reflashed the V6.19 CRSF V2 TX f/w then set 400K baud. Binds were all good and both Output & Channel maps are now displayed in the V0.96 TBS Agent Lite LUA. Much obliged :)

**Comment by kamik2** [comment]
> Outside of these specific cases, I would instead be suggesting there is a bug in the TBS firmware somewhere.

that was just an idea why some users could have experienced this issue. - even it would be super weird.
they all had in common, that they switched to etx/ the latest public version of etx, with no update on the crossfire/tracer fw. 

so far I could not reproduce these issues with my old x9d+ on any crossfire fw which makes the bug hunting extremely hard.

**Comment by ror1948** [comment]
Take note the last guy switched to 2.8.4 and had the problem.He reprogrammed  TBS TX and all is well.On Jun 25, 2023 6:00 a.m., kamikatze ***@***.***> wrote:

Outside of these specific cases, I would instead be suggesting there is a bug in the TBS firmware somewhere.

that was just an idea why some users could have experienced this issue. - even it would be super weird.
they all had in common, that they switched to etx/ the latest public version of etx, with no update on the crossfire/tracer fw.
so far I could not reproduce these issues with my old x9d+ on any crossfire fw which makes the bug hunting extremely hard.
