### ISSUE TITLE
instant trim feature

### ISSUE THREAD

**Issue by pds59** [EdgeTX/edgetx#369]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - EdgeTX version (e.g. 2.4.0 or nightly and #commit number)
 - Hardware (e.g. Frsky X9D+ or RM TX12S)

**Comment by pds59** [comment]
instant trim is set on momentary swich command looks like is working but no effect on actual trim

**Comment by pds59** [comment]
firmware v2.4.0-rc3 radiomaster t16

**Comment by pfeerick** [comment]
I take it you've found it's been fixed (which is why https://github.com/EdgeTX/edgetx/issues/342 is closed) but a new nightly / RC with the fix wasn't out yet? It is working in the nightly that was build about two hours ago.

**Comment by pds59** [comment]
Got It i try and did work the second time After i reset the functionTksPaolo de scagliaIl 29 giu 2021 06:24, Peter Feerick ***@***.***> ha scritto:
I take it you've found it's been fixed (which is why #342 is closed) but a new nightly / RC with the fix wasn't out yet? It is working in the nightly that was build about two hours ago.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
Il 29 giu 2021 06:24, Peter Feerick ***@***.***> ha scritto:
I take it you've found it's been fixed (which is why #342 is closed) but a new nightly / RC with the fix wasn't out yet? It is working in the nightly that was build about two hours ago.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
Il 29 giu 2021 06:24, Peter Feerick ***@***.***> ha scritto:
I take it you've found it's been fixed (which is why #342 is closed) but a new nightly / RC with the fix wasn't out yet? It is working in the nightly that was build about two hours ago.
