### ISSUE TITLE
2.9 - When writing the firmware on external module sentence is wrong

### ISSUE THREAD

**Issue by robustini** [EdgeTX/edgetx#3695]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I just noticed today that when I write the firmware of the FrSky R9M module with ELRS during the flash at the bottom the words "module reset" remains even while writing as seen in the image, when it should only appear initially and then write "writing in progress".

### Expected Behavior

It should do what I wrote above, I tried it with an older EdgeTX firmware (2.8) and in fact it works.
I don't think the problem is in the language, IT is correct, here the two different sentences, the second one should appear while writing:

#define TR_DEVICE_RESET                 "Resetto dispositivo..."
#define TR_WRITING                         "Scrittura..."

### Steps To Reproduce

1. Flash the latest master (2.9)
2. Write ELRS firmware to external module

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Windows 10 Pro x64

### Anything else?

![immagine](https://github.com/EdgeTX/edgetx/assets/3864712/f68309d9-107b-40a0-b2d1-2fdc0cc3787b)

**Comment by pfeerick** [comment]
It's not unique to ELRS... it's the same for all. We'd noticed it before, but I didn't realise it was correct in 2.8, so will see what changed there - thanks for pointing that out! :)

**Comment by robustini** [comment]
@pfeerick thanks Peter for your feedback.
In the TX16S I have firmware compiled in November 2022, actually quite dated, and it works there.
