### ISSUE TITLE
You can left "empty" source for an imput but you can´t select "---"(empty) on simulation or radio

### ISSUE THREAD

**Issue by Fortesque0** [EdgeTX/edgetx#3706]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

For an input, you cant left "empty" source data. When you edit this imput on simulation or on radio, you have not "empty" choice. 

### Expected Behavior

Has "empty" selection on simulation and radio to.

### Steps To Reproduce

On companion, edit or create new imput
Let empty source
Start simulation or transfer to radio
Go to simulation/radio imput menu and edit input.
Select one kind of source or try to find "---" if you select some source and accept, you can´t let empty again.

### Version

2.8.4

### Transmitter

FrSky X12

### Operating System (OS)

Windows

### OS Version

Windows 10

### Anything else?

![WithoutEmpty](https://github.com/EdgeTX/edgetx/assets/17238988/67950f51-9e95-4a14-a384-cbb14cb6da30)
![Source Empty](https://github.com/EdgeTX/edgetx/assets/17238988/84d61211-6f94-466b-96b9-96f25f490791)

**Comment by Fortesque0** [comment]
![Input](https://github.com/EdgeTX/edgetx/assets/17238988/d68b61fd-6cf6-4b6c-8ec8-fc04768a7332)

**Comment by philmoz** [comment]
I think the issue is that Companion allows the source to be empty when it should not do so.

**Comment by elecpower** [comment]
Empty source can also occur in radio conversions where the source does not exist on the current profile radio.
Pilots want the row kept so all they have to do is fix the source and not have to re-enter all the other details.

**Comment by elecpower** [comment]
Also empty source required for copy and paste and drag and drop between multiple open model and settings files.

**Comment by Fortesque0** [comment]
Hello,
I am new user and my be I am wrong, but, I think empty source it's absolutely necessary. 
I need a constant value (GVAR) active with switch position, and assigned to an output.
@

**Comment by Fortesque0** [comment]
Sorry, y closed by mistake

**Comment by pfeerick** [comment]
> I need a constant value (GVAR) active with switch position, and assigned to an output.

Why though? An input *needs* to have a source - this is why the radio won't let you set it, but Companion just happens to let you (for its own technical reasons).  Why not set it to MAX, and then work from that known state? 

Maybe explain what it is you're trying to achieve, and we can see why you think empty needs to be an option. Perhaps you're approaching the problem you're trying to solve the wrong way? Or you're seeing a use case we haven't thought of. i.e. if you're trying to make it so, a 3POS switch has one value in the middle position, and another when it is up and down, I do something similar, but I use a curve instead to control that. No need for the GVs, no need for an "empty" input source. The switch used as the input source, and I use the curve to change what is done with that input.

**Comment by Fortesque0** [comment]
Hello,
The functionality it's set giro values for helicopters.
I want to assign to output 5 two different values using one interrupt. This values can be increased or decreased (linked to interrupt position) using trim.
For me, source selection must be included GV as option, because source philosophie should be any input.
You can see on my last uploaded  image this configuration for Input 5 Gyro.
Regards

**Comment by 3djc** [comment]
MAX with weight in GV is the way to do it

**Comment by Fortesque0** [comment]
😱😱 I say I am new😅😅 thanks in advance, I will try it.

**Comment by Fortesque0** [comment]
Hi,
Yes, using MAX and modifying weight  with GVAR I can do it.
But, as philosophy, I think GVAR should be a source input too as MAX is. 
MAX it's a 100% value. GVAR can be any value, included 100%.
Please, considere this option.
Thank you for your help and developers, close this issue if you considered it's done.
Nice flights!!

**Comment by pfeerick** [comment]
To do that, you would use GV as the source for an INPUT, and then use that input in a mix. You have a wider selection of sources when you define stuff at the input stage. ;)

**Comment by Fortesque0** [comment]
> To do that, you would use GV as the source for an INPUT, and then use that input in a mix. You have a wider selection of sources when you define stuff at the input stage. ;)

Hello pfeerick,

Perhaps i am wrong ,but, you say that i can select GVAR as the source for an INPUT??? Just i am saying that there is not choice to select a GVAR  on input menu.. i think it´s good idea to select GVAR as an input source, like MAX is,

![image](https://github.com/EdgeTX/edgetx/assets/17238988/9fa9b1cc-5551-4cc5-8602-2fc676205afd)

**Comment by mha1** [comment]
Deselect all icons on the left side for the full list and scroll down.

![image](https://github.com/EdgeTX/edgetx/assets/5615068/a343d417-4c88-42c9-877e-781f12a99208)

**Comment by Fortesque0** [comment]
Hello MHA1,

Thaks for your reply. I have been testing again and i have found some discrepances. 

1.- Yes, you can deselect icons and GVx appears, but without "labeled name"
![Source without name](https://github.com/EdgeTX/edgetx/assets/17238988/0a99ffb7-5593-4190-9ef4-b3fd915e6efe)


1.1-.....but, using companion to program your radio, you haven´t this option:
 
![NO GV Companion](https://github.com/EdgeTX/edgetx/assets/17238988/ce8bf8b2-116c-488d-b735-851b9c46759a)

2.- GVAR are labeled if you select ass weight or offset
![Weight with GVAR Name](https://github.com/EdgeTX/edgetx/assets/17238988/1e235f40-f667-448f-b522-bd351055e618)


3.- You don´t think should be better to include labeled GVx with MAX? 

![INPUT GVAR missed 2](https://github.com/EdgeTX/edgetx/assets/17238988/2b323445-2999-4c4d-9cbd-37ec23ce84bc)

So i think this should be reopen. My be on a new one issue?
What dou you think Team?
Regards

**Comment by mha1** [comment]
2.9 Companion will let you define GVARs as Input:
![image](https://github.com/EdgeTX/edgetx/assets/5615068/caca5f97-b698-46e6-a928-61eef8a759be)

As for the label I recall a discussion about that. Maybe @philmoz can speak about the GVAR label status and your proposal to cluster GVARs with MAX.

**Comment by pfeerick** [comment]
The question of whether to group GVAR with MAX really depends on *what* that category was meant to organise... i.e. GVARS probably should be in a category of their own. I did a PR to add the GVAR names if set, but put that off until 2.10. 

> So i think this should be reopen. My be on a new one issue?

If you're talking about something different to the initial issue (which you are, aren't you?), it belongs in a new issue ;) But I think from M's replay you can already see you can do it in Companion, just hadn't scrolled down far enough (looks like they're not in exactly the same order).

**Comment by mha1** [comment]
2.9rc1 firmware and Companion allow to have GVAR's as input. Nothing to do here I guess. If GVAR labels are a low hanging fruit for 2.9 why not. No issue required, am I right?

**Comment by pfeerick** [comment]
no, No, nO, NO! No more substantive changes to 2.9! I said this over a
month ago! 🤣🤣

**Comment by mha1** [comment]
Time's flying, I remember it just like yesterday. I suppose it's not that low hanging then.
