### ISSUE TITLE
Incorrect display of six position switch operation

### ISSUE THREAD

**Issue by Shouldercannon** [EdgeTX/edgetx#3711]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The six-position switch shows the wrong values in the positive direction.
![Not correct](https://github.com/EdgeTX/edgetx/assets/94894541/0da072aa-d49f-4812-8f1d-72e6045e144f)
![Minus one division](https://github.com/EdgeTX/edgetx/assets/94894541/bc50069a-9a8b-4c18-9d3c-cf1d78e6bfb9)

### Expected Behavior

It should be like this
![Correct](https://github.com/EdgeTX/edgetx/assets/94894541/28e586a4-e414-4f35-9530-d92d757c6194)
![Normal](https://github.com/EdgeTX/edgetx/assets/94894541/914d6975-0c12-46de-bdbd-31abb1f65044)

### Steps To Reproduce

1. Push Sys
2. Go to the sixth tab of the menu
3. Go to Anas
4. Switch to position 4, 5, 6.

### Version

2.8.4

### Transmitter

Radiomaster Boxer

### Operating System (OS)

Windows

### OS Version

Win10 x64 22H2

### Anything else?

This problem has been observed for a very long time.

**Comment by philmoz** [comment]
What are the actual RAW numeric values for A7 at each position?

**Comment by pfeerick** [comment]
I see this on mine also -> 

![screen-2023-06-23-104857](https://github.com/EdgeTX/edgetx/assets/5500713/cd6244b7-3a0e-4164-a21c-40f6b8e18499)
![screen-2023-06-23-104859](https://github.com/EdgeTX/edgetx/assets/5500713/08e4f678-ed4a-4b5b-af7d-c9545a6b9901)
![screen-2023-06-23-104900](https://github.com/EdgeTX/edgetx/assets/5500713/d29ec09c-2980-4c27-9f97-d26666ce664a)
![screen-2023-06-23-104902](https://github.com/EdgeTX/edgetx/assets/5500713/db27d950-070f-40ab-89df-d4b4cbfcd15a)
![screen-2023-06-23-104903](https://github.com/EdgeTX/edgetx/assets/5500713/cd032868-3b91-492e-981f-dc8fb98468fc)
![screen-2023-06-23-104936](https://github.com/EdgeTX/edgetx/assets/5500713/31f613ab-78bf-4d15-bc84-d63ae7653449)
![screen-2023-06-23-104843](https://github.com/EdgeTX/edgetx/assets/5500713/15ce4681-fe4e-43c4-9b35-5f0853954fcd)
![screen-2023-06-23-104856](https://github.com/EdgeTX/edgetx/assets/5500713/26898ac1-7ab0-4474-b368-6a9b3bb81439)

**Comment by philmoz** [comment]
Does the 6POS switch have to be calibrated on this radio?

**Comment by pfeerick** [comment]
No, but even after calibration it is out slightly.

**Comment by pfeerick** [comment]
I doubled the last screenshot I noticed A6 was still showing 100 regardless of whether it was raw value of 2046 or 2047... 🤔

**Comment by philmoz** [comment]
What are the RAW values?

**Comment by pfeerick** [comment]
![screen-2023-06-23-110730](https://github.com/EdgeTX/edgetx/assets/5500713/c57ba905-5fe6-4618-af9e-ffef176b1163)
![screen-2023-06-23-110732](https://github.com/EdgeTX/edgetx/assets/5500713/ee2d29f6-9716-47b4-9d8c-a4056a6e289e)
![screen-2023-06-23-110735](https://github.com/EdgeTX/edgetx/assets/5500713/7fb7d260-5f64-43d2-9b05-8e133210e271)
![screen-2023-06-23-110737](https://github.com/EdgeTX/edgetx/assets/5500713/303b8894-d754-4c72-b06b-f706dd8223fd)
![screen-2023-06-23-110739](https://github.com/EdgeTX/edgetx/assets/5500713/9204acdd-5dcf-463d-883f-ba91896f3636)
![screen-2023-06-23-110744](https://github.com/EdgeTX/edgetx/assets/5500713/9878b6cb-d87e-4326-ac0a-fffce04a6aa3)

**Comment by philmoz** [comment]
Thanks. My TX16S does the same :(

**Comment by pfeerick** [comment]
It's also present in main, so unless the ADC refactor branch happens to touch on this somehow, it's still a current bug. 

@3djc Any ideas? Maybe `src/switches.cpp` -> `getSwitchesPosition()` is off by one past the zero or something when determining the steps? As it seems a bit od it is off by one for the last three positions

**Comment by philmoz** [comment]
It looks like a rounding problem with the way the 6POS values are being calculated - still trying to understand all the code though so could be wrong.

**Comment by 3djc** [comment]
I'll have a look in ADC branch, we reviewed some of that (but not specificaly looking at that)

**Comment by pfeerick** [comment]
I just had a quick look, and the equivalent lines changed in #3713 appear to be the be the same there

https://github.com/EdgeTX/edgetx/blob/c8e9437cd23349630de3c6fb4e5e4fd2c57fe177/radio/src/hal/adc_driver.cpp#L403-L413

So unless it is fixed elsewhere, if you're happy with the fix in #3713, I can merge that into 2.9 only, and you can apply it in the ADC branch once Malte pushes that rebase...

**Comment by 3djc** [comment]
Sure sure

**Comment by philmoz** [comment]
Can this be closed?

**Comment by pfeerick** [comment]
I think so ... my Boxer is showing all correct values on 2.10.2, so well past the prospective fixes being merged.
