### ISSUE TITLE
VCP mode does not work properly on the TX16S

### ISSUE THREAD

**Issue by DiehardFPV** [EdgeTX/edgetx#3714]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Other (Please specify below)

### Current Behavior

I previously used the telemetry-mirror of the zorro remote to connect with the telemenry-viewer of Android and worked fine,
But when I used telemetry-mirror on the TX16S and connected the phone with VCP mode, the remote screen went into bootloader，when i reopened it ，it entered the emergency mode

### Expected Behavior

It should work just like my ZORRO radio

### Steps To Reproduce

1.Plug USB wire in, select the VCP mode
2.Open the telemenry-viewer on my Android phone
3.Connect the radio to my phone
4.The screen went off and i have to reopened
5.it entered emergency mode

### Version

2.8.4

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

no

### Anything else?

no

**Comment by pfeerick** [comment]
Did you ever get any further with this? i.e. hardware, software, cable issue?
