### ISSUE TITLE
LiteRadio 3 Pro - not compiling Betaflight script

### ISSUE THREAD

**Issue by odixxx** [EdgeTX/edgetx#3725]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

when trying to compiling Betaflight Setup script - Syntax Error
![20230627_100823](https://github.com/EdgeTX/edgetx/assets/12283233/0c3293df-f111-42bc-b0d2-05bae129cedd)

### Expected Behavior

My setup:
Betaflight TX Lua Scripts 1.7.0
Betaflight 4.4.2
EdgeTX v2.8.4

ps. on another radio X9D Plus everything works fine!

### Steps To Reproduce

Syntax Error

### Version

2.8.4

### Transmitter

BetaFPV LiteRadio3 Pro

### Operating System (OS)

Windows

### OS Version

11

**Comment by pfeerick** [comment]
I've just tried this on v2.8.4, with a fresh copy of the Betaflight Lua v1.7.0, and it compiled just fine. Given the actual error is "file not found", have you tried copying the betaflight lua pack onto the radio again (and making sure you "safely remove" the radio USB device before unplugging the USB) just in case not all the files were copied on properly?

**Comment by odixxx** [comment]
I just tried formatting the card and everything is new - without result!
can you give me your file - bf.luac

**Comment by pfeerick** [comment]
[BF-SCRIPTS.zip](https://github.com/EdgeTX/edgetx/files/11935946/BF-SCRIPTS.zip)

This is my SCRIPTS directory from the LR3P minus extra baggage.

**Comment by odixxx** [comment]
thanks, everything worked!!!
in the files "betaflight-tx-lua-scripts_1.7.0.zip" - apparently something is missing

**Comment by pfeerick** [comment]
Something strange going on anyway... that is what I used when trying to repo this. Anyway, glad it's working for you now. 

![image](https://github.com/EdgeTX/edgetx/assets/5500713/7e2a36ae-1c5f-4e47-bd50-c4977fb212c9)

**Comment by VisualGadget** [comment]
I had the same error on a different TX and problem was the faulty microSD card.
