### ISSUE TITLE
v1 in logical switches is shifting with next 2 steps on each boot

### ISSUE THREAD

**Issue by ivan-ef** [EdgeTX/edgetx#3732]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

v1 in logical switches shifts with next 2 parameters on each boot. 
it changes to T5+/- then T6, L1 etc.

![IMG_5693](https://github.com/EdgeTX/edgetx/assets/67600440/1fae0a3c-8ae1-4340-bf51-f2934b6ecae7)

![IMG_5695](https://github.com/EdgeTX/edgetx/assets/67600440/2d46beb6-fc0a-4107-b8bd-66e40ef199a4)

### Expected Behavior

Correct v1 parameters in logical switches after transmitter reboot.

### Steps To Reproduce

1.set V1 of logical switch to rudder trim + and -
2. reboot.

### Version

Other (Please specify below)

### Transmitter

Jumper T-Pro

### Operating System (OS)

macOS

### OS Version

monterey

### Anything else?

[model02.yml.zip](https://github.com/EdgeTX/edgetx/files/11900515/model02.yml.zip)

Model file may be corrupted during connection of transmitter in sd-card USB storage mode. Transmitter drops USB connection often and just turns off. Can't eject USB storage correctly on Mac, it says storage is used in few apps. 

Stock firmware version:
![IMG_5694](https://github.com/EdgeTX/edgetx/assets/67600440/43ccf05b-679f-4756-9880-af02c6401611)

**Comment by 3djc** [comment]
Please try lastest nightly, I think I fixed this some time ago

**Comment by 3djc** [comment]
Tested your file, not showing the issue, please update your firmware version with a nightly

**Comment by ivan-ef** [comment]
Updated to nightly, looks ok now.

**Comment by ivan-ef** [comment]
Updated to nightly, looks ok now.
