### ISSUE TITLE
Switch warning not active at model change

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#374]
EdgeTX nightly 2aa5296
TX16S

please have a look at the behavior: 
Switch warnings are only active when transmitter is switched on - a modelchange does not recognize 
preflight checks / Switch positions

in respect for your great work, Jörg

**Comment by pfeerick** [comment]
Repeatable, TX16S on latest nightly. Also doesn't check the throttle state even if checkbox ticked. X9D+ correctly shows stick and switch warnings.

**Comment by pfeerick** [comment]
May tie into implementing https://github.com/EdgeTX/edgetx/issues/348 also, since the end user experience was as if it had jumped out of the menu when selecting the model, show the pre-flightwarnings, then you'd be at the main screen/panel for the model.

**Comment by raphaelcoeffic** [comment]
@pfeerick didn't we fix that one already?

**Comment by pfeerick** [comment]
Yes, through #428. Thank you! :)
