### ISSUE TITLE
Bluetooth Settings missing in Hardware menu for Taranis QX7S

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3752]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Compared to the QX7, the Taranis QX7S has a built-in Bluetooth module. However, this is not displayed under SYSmenu/Hardware for configuration. This means that it cannot be activated for the trainer function and cannot be selected in modelsettings under DSC BTMaster or BTSlave.
This setting is already offered in Companion.

With the Taranis QX7S ACCESS, on the other hand, it is already correct.

### Expected Behavior

QX7S should offer BT settings in Hardwaremenu

### Steps To Reproduce

1. Enter Hardwaremenu
2. try to edit BT settings
3. observ, the BT settings are not offered

### Version

Other (Please specify below)

### Transmitter

FrSky Q X7 / Q X7S (ACCST)

### Operating System (OS)

Windows

### Anything else?

2.9.0 RC1

**Comment by pfeerick** [comment]
Was this the case in 2.8 also?

**Comment by ParkerEde** [comment]
I have never tested this before, as I have only had the radio since yesterday. If the test is of great importance, I can still do it.

**Comment by pfeerick** [comment]
Ah, ok. I suspect it was then, as I don't think some elements of Bluetooth have worked properly for a while now. The only "importance" is in trying to determine whether it is new or pre-existing behaviour ;)

**Comment by ParkerEde** [comment]
Okay. The BT settings are also missing in 2.8.4. I have just checked it. So it seems to have always been missing.

**Comment by ParkerEde** [comment]
That was my first thought too and I tried it out with that. Unfortunately, that doesn't work either.

`cmake -G "MSYS Makefiles" -Wno-dev -DCMAKE_PREFIX_PATH=$HOME/5.12.9/mingw73_64 -DSDL2_LIBRARY_PATH=/mingw64/bin/ -DPCB=X7 -DDEFAULT_MODE=2 -DBLUETOOTH=YES -DGVARS=YES -DHELI=YES -DLUA=YES -DINTERNAL_GPS=NO -DTRANSLATIONS="DE" -DCMAKE_BUILD_TYPE=Release ../`

**Comment by pfeerick** [comment]
What is *actually* needed, is for this to finally happen https://github.com/EdgeTX/edgetx/issues/1390. i.e. the runtime configurable bluetooth that has been waiting to happen.

**Comment by 3djc** [comment]
Code seems sound : https://github.com/EdgeTX/edgetx/blob/8f0ad3fca829f68a0051f12708e29dfba969ec86/radio/src/targets/common/arm/stm32/bluetooth_driver.cpp#L130

**Comment by philmoz** [comment]
The function BT_USART_IRQHandler in bluetooth_driver.cpp is not compiled into the firmware (#if _OBSOLETE_). So the btChipPresent flag can never be set.

For X7ACCESS the IS_BLUETOOTH_CHIP_PRESENT macro defaults to true so does not need the btChipPresent flag.

**Comment by 3djc** [comment]
ok, so another victim of the serial rework :) Should be an easy fix

**Comment by pfeerick** [comment]
It explains why there could be a problem for 2.9 onwards, but not for 2.8.4. Something else must be going on there.

**Comment by 3djc** [comment]
> It explains why there could be a problem for 2.9 onwards, but not for 2.8.4. Something else must be going on there.

Indeed. My x7 unfortunalty isn't an S version

**Comment by philmoz** [comment]
If I force IS_BLUETOOTH_CHIP_PRESENT to true in bluetooth_driver.h and build the X7 firmware then I get the bluetooth settings on my X7S.

If I then change the mode on the radio it finds a bluetooth address.

The Frsky app on iOS detects the radio when BT is set to telemetry (other than that the app is useless).

**Comment by 3djc** [comment]
@ParkerEde Could you try : https://github.com/EdgeTX/edgetx/tree/3djc/fix-x7s-bt-detection

**Comment by ParkerEde** [comment]
@3djc Yeah, that works. Tested Trainer funktion with my X10S Express. Well done

**Comment by ParkerEde** [comment]
@pfeerick can we have this fix in 2.9?

**Comment by pfeerick** [comment]
Not until Raphael has reviewed the PR to see if this is the way we want to fix this going forward. If that isn't the case, this doesn't necessarily prevent it from going into 2.9 though as a temporary fix.

**Comment by Zwaubel** [comment]
Hi,
I'm currently facing the same issue on a Taranis QX7s running EdgeTX 2.10.4.
The Bluetooth menu entry in the hardware settings panel (where it used to be) is still absent.
Is this issue still unsolved?

**Comment by pfeerick** [comment]
SYS => VERSION => Firmware options screen... does it list "bluetooth" as an option? If so, the code actually probes for a response from the bluetooth module, so either that is not responding, or isn't present... as it was confirmed to be functioning again in 2.9 (after being broken in 2.8).

**Comment by Zwaubel** [comment]
Yes, it's there, and I can find my X7s as a Bluetooth device via a phone. 
I can even change the advertisement name via the desktop companion ap. 
It is just to present via the UI of the transmitter itself.

**Comment by Zwaubel** [comment]
So... When using EdgeTX 2.9.4 the Bluetooth settings option is there. Everything works as expected. But when switching back to 2.10.4 that settings option is gone again. That to me indicates that on 2.10.4 something broke again for the x7s and its Bluetooth module.

**Comment by Zwaubel** [comment]
I now went through 2.10.0, 2.10.1, 2.10.2 and 2.10.3 without success regarding Bluetooth on the x7s. Seems like something changed in the way 2.10.x probes and communicates with the Bluetooth module.

**Comment by oilytin** [comment]
Same issue for me, bluetooth setting there in 2.9.4 but missing in 2.10.6

**Comment by turibiusrozario** [comment]
For anyone in the future who stumbles on this like I did: I went to EdgeTX Companion, connected my transmitter and read settings, and then edited radio settings. In the radio settings, I could see the Bluetooth settings set as "OFF"; I switched it to "Trainer". From there, Bluetooth functionality was restored for trainer. This was with EdgeTX 2.10.5.

**Comment by pfeerick** [comment]
Prior to that,  was there not a ```Bluetooth   --- ``` line present in SYS -> Hardware (just under the Internal RF settings)? You should have been able to select that line, and change it from the `---` (OFF) position to either Telemetry or Trainer.

**Comment by adazmx** [comment]
Hello, I've looked into the problem and concluded that the Bluetooth detection method is incorrect.

Code:

```
if (bluetooth.localAddr[0] != '\0')
   btChipPresent = 1;
```
This will always be false because the Bluetooth data processing process hasn't been started yet. The process will only be started later, after edgeTxInit is initialized (in mixerTask -> execMixerFrequentActions -> bluetooth.wakeup()).

I propose two solutions to the problem:
1. The simplest solution (removing the detection code and assuming Bluetooth is always present: btChipPresent = 1) is to remove the BLUETOOTH_PROBE definition, e.g., in the radio file radio/src/targets/taranis/CMakeLists.txt, and change the line 'add_definitions(-DBLUETOOTH_PROBE)' to '# add_definitions(-DBLUETOOTH_PROBE)'. Alternatively, remove fragments of the detection code. If there is no Bluetooth module, the module address will always be empty. Edgetx works on Frsky x-lite without detecting the bluetooth module.

or

2. change detection code in edgetx.cpp:

```
#if defined(BLUETOOTH_PROBE)
    extern volatile uint8_t btChipPresent;
    auto oldBtMode = g_eeGeneral.bluetoothMode;
    g_eeGeneral.bluetoothMode = BLUETOOTH_TELEMETRY;
#endif
```

to 

```
#if defined(BLUETOOTH_PROBE)
    extern volatile uint8_t btChipPresent;
    uint8_t byte;

    // Bluetooth is initialised in board.cpp -> bluetoothInit(BLUETOOTH_DEFAULT_BAUDRATE, true); and my BT answare "Peripheral:..."
    if(bluetoothRead(&byte)) // if any answer, BT exist...
       btChipPresent = 1;
#endif

```

and delete code:

```
#if defined(BLUETOOTH_PROBE)
    if (bluetooth.localAddr[0] != '\0')
      btChipPresent = 1;
    g_eeGeneral.bluetoothMode = oldBtMode;
#endif
```

Both solutions have been tested and work on my x7s with BT  [EdgeTX v2.11.4].
