### ISSUE TITLE
Jumper T-Lite switch locations

### ISSUE THREAD

**Issue by FelixSchreiber** [EdgeTX/edgetx#3756]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the radio's Main View the switch locations are not ordered according to the real hardware switch locations.

On the radio, C and A are left to the antenna, B and D are right to it; C is the leftmost and D the rightmost switch. C and D are located more to the back whereas A and B are located more to the front of the radio.
In the main view, A and B are left to the left stick, C and D are right to the right stick.
![grafik](https://github.com/EdgeTX/edgetx/assets/94545140/9013ee11-cba4-432f-8a1c-0350b8f77951)
(picture is from OpenTx 2.3.14, where I also found this issue: https://github.com/opentx/opentx/issues/8780)

### Expected Behavior

A more intuitive order would e.g be :
Left to the left stick: First Switch A and below switch C
Right to the right stick: First Switch B and below switch D

### Steps To Reproduce

switch the radio on and look on the Main View

### Version

2.8.4

### Transmitter

Jumper T-Lite

**Comment by pfeerick** [comment]
This is not specific to the T-Lite, and historically has always been the case with OTX and also ETX until recently (as in, going forward in 2.10)... The switches were simply listed A-Z, left to right, regardless of physical position. i.e. Frsky X9D+2019 with SA, SB, SE and SF on the left side of the handset would have two shown on the left side, two on the right. TPro is even weirder in ordering, as SA and SB are the two pos switches, and SC and SD are the toggle switches... so top left button (SC Toggle) triggers the top right entry, middle left (SA 2POS) triggers top left, middle right (SB 2POS) triggers bottom left, and top right button (SD toggle) bottom right entry. 

As of 2.10, physical positions will be taken into account as well when displaying them. If you're game, backup your current radio settings, and see what the currently nightly is like.
