### ISSUE TITLE
r9 External access mod is no longer able to compile in 2.9.0-rc1

### ISSUE THREAD

**Issue by Helipro** [EdgeTX/edgetx#3757]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

A compile warning when attempting to compile R9 external access mod on the t16 and t16s MII.  The software was not compiled with the requested cmake:
-DHARDWARE_EXTERNAL_ACCESS_MOD=Y
Previous versions 2.8.4 worked flawless.

### Expected Behavior

Compile the software with features I want.

### Steps To Reproduce

Web Page:
https://gitpod.io/#https://github.com/edgetx/edgetx/tree/v2.9.0-rc1
Cmake line:
cmake -Wno-dev -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES  -DPPM_UNIT=US -DBLUETOOTH=YES  -DHARDWARE_EXTERNAL_ACCESS_MOD=ON    -DLUA=ON  -DOVERRIDE_CHANNEL_FUNCTION=OFF  -DHELI=NO  -DCMAKE_BUILD_TYPE=Release ../

### Version

Other (Please specify below)

### Transmitter

Jumper T16, Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

2.9.0-RC1

### Anything else?

![1](https://github.com/EdgeTX/edgetx/assets/119552818/e77838d1-d59d-4bbd-b2e6-9320765f15f3)

**Comment by pfeerick** [comment]
`HARDWARE_EXTERNAL_ACCESS_MOD` is no longer a valid option, hence why you are getting the warning (and most likely a compile failure afterwards). 

As of https://github.com/EdgeTX/edgetx/pull/2562, external acccess mod / external module is a built-in run-time option. Goto the Radio Settings -> Hardware page and set AUX1 to "external module". Done.
