### ISSUE TITLE
Feature Request: SYS "Tools" Lua Script Page

### ISSUE THREAD

**Issue by CorruptName** [EdgeTX/edgetx#376]
Hello and thanks for sharing your awesome work.
On the first page, when you hold SYS key, You get the Lua Scripts which are in the "SCRIPTS/TOOLS" folder.
For these Scripts, can we get larger buttons? Maybe square, the size of your finger? Then can we get assignable Images? Almost like an app drawer with "App Sized" Icons? Would be awesome.
Just an idea.
Thanks for considering.

**Comment by raphaelcoeffic** [comment]
> Hello and thanks for sharing your awesome work.
> On the first page, when you hold SYS key, You get the Lua Scripts which are in the "SCRIPTS/TOOLS" folder.
> For these Scripts, can we get larger buttons? Maybe square, the size of your finger? Then can we get assignable Images? Almost like an app drawer with "App Sized" Icons? Would be awesome.
> Just an idea.
> Thanks for considering.

Thanks, this is already planned for next release. We will increase the size of quite some fields to make it more compatible with “bigger fingers” ;-)

**Comment by JimB40** [comment]
This became more obvious with NV14 release.
In SD Browser or Tools lines are so tiny that error rate is like 60-70%
