### ISSUE TITLE
Power screen not color

### ISSUE THREAD

**Issue by Loupy01** [EdgeTX/edgetx#3799]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Power off screen is in Black and white, 
Is this happening because of change to 2.8.2 ?

### Expected Behavior

color icons / image

### Steps To Reproduce

Turn radio off

### Version

2.8.2

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by pfeerick** [comment]
Since 2.6 (https://github.com/EdgeTX/edgetx/pull/1182), the shutdown screen is 
1) black and white if using the default theme
2) otherwise, if follows the primary colours of the user set theme
