### ISSUE TITLE
LUA widget visual glitch / flicker

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#38]
Test report by @rotorman:
Running (my MavSDK enhanced) Yaapu LUA screen (https://www.rcgroups.com/forums/showthread.php?3840599-Blog-6-Modified-Yaapu-telemetry-widget-to-support-MavSDK-native-MAVLink-on-OpenTX), I see elements sometimes flicker to foreground that should be on background behind other elements drawn on top - likely an issue with graphics library.

**Comment by rotorman** [comment]
https://www.youtube.com/watch?v=UESoQ_J8zmU

**Comment by rotorman** [comment]
The strips seem to be only with @olliw42 fork. I compiled today's vanilla ETX and flashed it to my TX16S. With it I see no white stripes as in the video above. So flashed back to @olliw42 fork (with VCP support, thus latest) as I see white stripes again.

**Comment by raphaelcoeffic** [comment]
I don’t think this has anything to do with the MAVlink PR. Seems like something not working properly in the double-buffering mechanim.
