### ISSUE TITLE
(feat) Flysky Gimbal Support for T20

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#3829]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Flysky gimbals can be installed properly in T20, now is time to enable the firmware support.

### Describe the solution you'd like

Flysky gimbal support for T20.

**Comment by raphaelcoeffic** [comment]
On `main` this should be only about adding a few defines to `hal.h` and `FLYSKY_GIMBAL` to `CMakeLists.txt`.

**Comment by richardclli** [comment]
Yes, I know.  Trying to.work this out.

**Comment by rotorman** [comment]
You need to define also FLYSKY_HALL_* as e.g. here: https://github.com/EdgeTX/edgetx/blob/5386fe92adf03f8990cfe13e3714f4ffb217eb3a/radio/src/targets/taranis/hal.h#L2706-L2723
