### ISSUE TITLE
radiomaster zorro spash screen bug

### ISSUE THREAD

**Issue by LexFPV** [EdgeTX/edgetx#3830]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

i just updated to edgetx 2.9.0 rc1 and im having an issue with the splash screen.

when i power on and the edgetx logo is shown it looks like it tries to put a black background onto the screen while its white
(see screenshots)

this did not happen when i was on 2.8.4.!

![Screenshot_20230719-1324272](https://github.com/EdgeTX/edgetx/assets/139972544/26d66f3d-fc9b-4544-afb0-0505c124514c)

### Expected Behavior

that it boots up normally without the black backdrop.

### Steps To Reproduce

power radio on and look at the splash screen

### Version

2.9.0

### Transmitter

Radiomaster Zorro

### Operating System (OS)

Windows

### OS Version

Windows 11, version 22H2

**Comment by pfeerick** [comment]
Check your displays contrast setting, it's probably a fraction too high.

**Comment by 3djc** [comment]
Pfeerick is completely right, but I must add that there is no settings that will make it right for all screen. If it is perfect for this one, it will worse in others. This is not a software issue, it is down to the lcd panel power driver circuit (and there I must also add that is is not a Radiomaster issue, all similar radio, including FrSky x7 suffer the very same issue)

**Comment by LexFPV** [comment]
> Pfeerick is completely right, but I must add that there is no settings that will make it right for all screen. If it is perfect for this one, it will be worse in others. This is not a software issue, it is down to the lcd panel built in power driver circuit (and there I must also add that is is not a Radiomaster issue, all similar radio, including FrSky x7 suffer the very same issue)

yeah okay. the thing is that even on contrast level 10 it is still there. and it wasnt there before i updated to 2.9.0(was on 2.8.4 before)

**Comment by 3djc** [comment]
In addition I checked lcd_driver_spi.cpp where this is happening, there no change between 2.8 and 2.9 branches

**Comment by LexFPV** [comment]
> In addition I checked lcd_driver_spi.cpp where this is happening, there no change between 2.8 and 2.9 branches

huh.. so this is just the lcd?

**Comment by LexFPV** [comment]
> No you are right, there seems to be a difference, trying to narrow it down

okay.!

**Comment by 3djc** [comment]
Got it, submitting fix PR

**Comment by 3djc** [comment]
As a side note @pfeerick , boot logo is displayed before radio data is loaded so using LCD_CONTRAST_DEFAULT

**Comment by pfeerick** [comment]
No, that's not quite true... otherwise, the radio wouldn't know to apply the startup delay, or how long to show the logo (if at all). There is a pre-load of the settings to get those values, before choosing to run the animation / show splash screen. 

https://github.com/EdgeTX/edgetx/blob/2ab21da86622d08a917af99b58ea8b84664d22f1/radio/src/opentx.cpp#L1445-L1467

I think the issue now is that lcdSetContrast isn't called again after board initalisation using `LCD_CONTRAST_DEFAULT` until later in startup. 

https://github.com/EdgeTX/edgetx/blob/2ab21da86622d08a917af99b58ea8b84664d22f1/radio/src/opentx.cpp#L1591-L1593
