### ISSUE TITLE
Missing Module Options with Compile options for internalaccess (isrm) 

### ISSUE THREAD

**Issue by brainbubblersbest** [EdgeTX/edgetx#384]
Cannot switch from external to internal antenna. 
![16252250321827863457795312408980](https://user-images.githubusercontent.com/48190425/124267600-c124d480-db38-11eb-956c-41a6f8299765.jpg)

**Comment by brainbubblersbest** [comment]
![95105874-0e098500-0738-11eb-8b2c-f7dc07246fb1](https://user-images.githubusercontent.com/48190425/125279597-6cd9db80-e314-11eb-870e-0bc595f82785.jpg)
How it should be.
Options <-> [SET]

ISRM and Also R9M ACCESS

**Comment by brainbubblersbest** [comment]
#260

**Comment by raphaelcoeffic** [comment]
Implemented in #991
