### ISSUE TITLE
Companion Soundpack Download, loads always the same file

### ISSUE THREAD

**Issue by Shonkonray** [EdgeTX/edgetx#3841]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

The soundpack download via companion downloads always the same .zip file, regardless which soundpack option is selcted.
Same behavior on V2.8.4 and V2.9.0 RC1

### Expected Behavior

The selected soundpack(s) (multi selection option is great, but doesnt work either), for example after selecting GB_RYAN, than only this should be downloaded. When selecting ryan and sara, both should be downloaded.

### Steps To Reproduce

Try and download different soundpacks via companion.

### Version

2.9.0

### Transmitter

FrSky X10 / X10S (ACCST)

### Operating System (OS)

Windows

**Comment by elecpower** [comment]
Bug confirmed

**Comment by pfeerick** [comment]
Oops... sorry! Fix one problem, create another! 🤦

**Comment by elecpower** [comment]
I wasn't going to name names to protect the guilty.
The available releases are determined by the github release status and the companion release filter. Doesn't do a version check due to a number of factors.

**Comment by pfeerick** [comment]
Jesus... need to have a word with the dude responsible for these namings ... 👀 
![image](https://github.com/EdgeTX/edgetx/assets/5500713/c8682b12-d608-473a-95e5-9d931400fa4e)

**Comment by elecpower** [comment]
Lucky companion doesn't use descriptions but the release metadata to get version info

**Comment by Shonkonray** [comment]
I am not sure if it is clear what i was talking about, or put another way, i am confused about what you are talking about. 😂
To add to the confusion i made a screenshot of what i was talking.
The selection popup "Choose language package" is downloading always the same file. In case that this was clear to you, sorry for double post. 😄 

![Sounds](https://github.com/EdgeTX/edgetx/assets/35926350/817320d2-3301-4c5e-8396-17dd340975ca)

**Comment by elecpower** [comment]
@Shonkonray we know the issue from your perspective and it is caused by a 'behind the scenes' change. @pfeerick and I have been having a bit of devs banter.
