### ISSUE TITLE
Screen layouts can be overlapped

### ISSUE THREAD

**Issue by Shonkonray** [EdgeTX/edgetx#3842]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If during widget setup the button "TELE" on the tx (or companion simulator) is pressed the layout selection screen pops up. There a new layout can be selected and if then the "setup widgets" option is pressed the old and the new layout are overlapped.
This can be repeated many times and widgets can be selected until at some point the system crashes. If one wants to abort setting up widgets, he has to cycle back with the return button as many instances as were prior "opened" with the tele button.

### Expected Behavior

I think best would be that the TELE button behaves like the RTN button, unless there is a good reason that it needs to be like this.

### Steps To Reproduce

1) Add telemetry screen
2) Press setup widgets
3) Press TELE button
4) Press setup widgets
5) Repeat as desired or until crash :)

### Version

2.9.0

### Transmitter

FrSky X10 / X10S (ACCST)

### Operating System (OS)

Windows

### Anything else?

Tested on 2.8.4 and 2.9.0_RC1, companion simulator behaves the same as TX.
![screenshot_x10_23-07-22_17-41-06](https://github.com/EdgeTX/edgetx/assets/35926350/592cca34-9da0-45ce-a68b-3e54770b94cb)

**Comment by Shonkonray** [comment]
Thank you for linking, and sorry that i have overlooked that there was already a pull request.

**Comment by pfeerick** [comment]
I think the PR was in response to your report, so thanks for finding the
glitch in the machine ;)
