### ISSUE TITLE
Timer Issue

### ISSUE THREAD

**Issue by Mikey1968** [EdgeTX/edgetx#386]
The issue I'm seeing is if I go to count down . When I put it on 10s it's giving me 20s count down. 

Also I decided to try 5s and now it counts even higher. Not sure what's going on

**Comment by raphaelcoeffic** [comment]
> The issue I'm seeing is if I go to count down . When I put it on 10s it's giving me 20s count down.
> 
> Also I decided to try 5s and now it counts even higher. Not sure what's going on

I believe this one has been fixed a couple of days ago. Can you please check which version you are on?

**Comment by Mikey1968** [comment]
I have the lastest version . I downloaded the firmware a few days ago.

**Comment by raphaelcoeffic** [comment]
> I have the lastest version . I downloaded the firmware a few days ago.

Aha! A few days ago might mean a world difference right now. Could you please re-try with the latest nightly build?

**Comment by Mikey1968** [comment]
Do you have the link

**Comment by Mikey1968** [comment]
Where do you download those at.

**Comment by TramALot** [comment]
The flasher

**Comment by pfeerick** [comment]
If you're using the flasher, try the branch name ending in 'nightly'. Otherwise, check the 'nightly' release on the releases page. 

There was a fix done for this four days ago.

**Comment by pfeerick** [comment]
@Mikey1968 Is this still an active issue, or can it now be closed?

**Comment by Mikey1968** [comment]
I will give it a try today and let you know what happens

**Comment by Mikey1968** [comment]
The problem was fixed. Thanks so much for the help
