### ISSUE TITLE
Gas reversal no longer works in v2.10.0

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#3869]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When I switch throttle reverse it always stays on standart.
With v2.10.0 selfbuild

### Expected Behavior

Throttle direction should be inverted.

### Steps To Reproduce

1.throttle up
2.throttle down
3.once with reverse switch once without reverse switch
4.result is always the same

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

new firmware is:
![screen-2023-07-28-110537](https://github.com/EdgeTX/edgetx/assets/92114465/7fd6dc7e-d532-4723-bc41-f008163f2ab2)

Switch position is:
![screen-2023-07-28-105504](https://github.com/EdgeTX/edgetx/assets/92114465/7e0634c4-3626-415c-8b7b-04f3b8221591)

**Comment by pfeerick** [comment]
https://github.com/EdgeTX/edgetx/pull/3864
