### ISSUE TITLE
Assan protocol not showing 

### ISSUE THREAD

**Issue by kaindub** [EdgeTX/edgetx#3876]
I have a Radiomaster TX16s. Newly installed Edge tx 2.8. 
Never installed previous versions.
I use some Assan receivers.
On the radio, if I select internal tx, and multi, Assan is not a protocol I can select.
If I go into Edge tx companion, I can select Assan, and upload  it to the radio.
The radio then binds with receiver.
But there is no indication that Assan protocol has been selected on the radio.

I migrated all my models from Open tx. The models using Assan protocol migrated successfully and receivers remained bound to transmitter. But again no indication on setup page that Assan is protocol being used.

**Comment by pfeerick** [comment]
If you've migrated from OpenTX, have you [updated the MPM for your radio](https://downloads.multi-module.org/?rmtx16s) recently? If so, it is probably running an outdated version of the MPM firmware, and isn't telling EdgeTX what protocols it support. 

What does this line say on your radio? 

![companion_DwBu30jTlh](https://github.com/EdgeTX/edgetx/assets/5500713/820c530e-e51a-4206-8e37-39ee6f65d21c)
