### ISSUE TITLE
Cannot install latest Multi Module Firmware Update

### ISSUE THREAD

**Issue by MervDale** [EdgeTX/edgetx#389]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - EdgeTX version (e.g. 2.4.0 or nightly and #commit number)
 - Hardware (e.g. Frsky X9D+ or RM TX12S)

**Comment by MervDale** [comment]
Using the latest nightly build for the TX16S on the Eachine radio unable to install the latest Multi Module 4 in 1 firmware.
Radio reports not a valid firmware file .
![failed install](https://user-images.githubusercontent.com/30642754/124339226-4f0fc680-dbf0-11eb-8c0d-82a5880839c6.jpg)

**Comment by pfeerick** [comment]
I think you're trying to install it the wrong way, as I've never updated the MPM via the bootloader. In the past, I've used the SD browser when running the radio normally... It should give you an option to flash the internal module when you select the firmware file.

**Comment by pfeerick** [comment]
I was able to update my the MPM on my Radiomaster TX16S just now, with a recent EdgeTX build. You're after this option, after located the file and selecting it on in the SD card browser... 
![image](https://user-images.githubusercontent.com/5500713/124342424-3a8af880-dc07-11eb-8613-f5adda18cba5.png)

**Comment by pfeerick** [comment]
Issue has been resolved (Discord)
