### ISSUE TITLE
Cannot run the latest nightly firmware on my Horus X12S

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#3891]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Loaded latest firmware and locks up on restart. Have to disconnect battery and load older firmware from STM32 cube programmer to re-initiate and get back to working condition. I have tried loading bootloader for the latest but this does not work either. I have tried a few times now and always with the same result. I am re-loading firmware from the V2.9.0  (ebef94d9) 2023-03-27 and this works fine. 
Have tried loading latest firmware from STM32 cube programmer same results - no startup. I have to disconnect internal radio battery again in order for USB communication to function again to load original firmware via STM32.

### Expected Behavior

 Latest firmware to run after being installed from bootloader.

### Steps To Reproduce

1. load latest firmware on to disk
2. power off and into bootloader
3. load latest firmware
4. Exit and to start
5. No blue start light
6. Unable to connect to USB until internal battery disconnected
7. Then, I am able to load old firmware from STM32 and TX restarts as before

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### Anything else?
Latest firmware build tested and failed for me and also last before expiry #782 failed too. I have not loaded new firmware into radio since the end of March. This latest build does not work on my radio. As I have not loaded new firmware onto my radio for a few months I am not sure at what point the firmware build stopped working or if there is a change to how this firmware needs to be loaded correctly.
V2.9.0  (ebef94d9) 2023-03-27 runs fine when reloaded.

**Comment by raphaelcoeffic** [comment]
Can you please re-try with the latest build from #3810 ?

**Comment by Kevltan** [comment]
Yes will try later today👍

**Comment by Kevltan** [comment]
This PR works for my X12s. 😊

**Comment by Kevltan** [comment]
Can you please put the same edit in the firmware that allows the splash
screen to load, without being influenced by stick or switch position
notifications until the time delay has elapsed. As done by philmoz #3887
for the TX16S? 😊

**Comment by pfeerick** [comment]
Wait for #3810 and #3887 to get merged, then you'll have that functionally
in the following nightly build.
