### ISSUE TITLE
Unable to force shutdown when receiver still connected

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#39]
Test report by @rotorman:
When telemetry link is active (RSSI bar shows signal), cannot nicely shut down the radio. No dialog to confirm shut-down, or possibility to exit the Shutdown screen. Deadlock, need to hard-cut power/pull battery.

**Comment by rotorman** [comment]
Tested radio was RM TX16S.

**Comment by pfeerick** [comment]
Reproducible for me, also RM TX16S, I get the voice-over for 'receiver still connected', the shutdown squares, and then it locks up. No blind stabbing in the dark of `RTN` or `ENTER` just in case the screen isn't shown would unstick it.

**Comment by raphaelcoeffic** [comment]
No problem, I‘ll take care! Probably something with the UI loop not handled properly in the pop-up screen.
