### ISSUE TITLE
Fix proper focus 

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#3901]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

![screen-2023-08-04-083224](https://github.com/EdgeTX/edgetx/assets/46420768/03adbfe7-98a0-4d53-9ff4-3b686761963f)

Focus on variuos UI interactive elements is now tiny frame.
@philmoz have you changed anything in global LVGL UI elements style definitions? 

### Expected Behavior

![232181445-be0970ee-2042-42e0-898a-bccc71aa2c87](https://github.com/EdgeTX/edgetx/assets/46420768/ae892a66-c0ae-4a98-a5cc-2785c04191b4)

### Steps To Reproduce

Flash 2.10 nightly

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by philmoz** [comment]
Focus was changed in the libopenui refactor PR to be more consistent (along with size, border and rounded corners).

Controls that can be both active and focused used the border color to show focus. 
That meant there were two types of focus - border or fill.

**Comment by philmoz** [comment]
Keep in mind one of the main reasons for the libopenui refactor is to set up a better framework for 3.0.

**Comment by JimB40** [comment]
Bit confused Phil.
There are style-sheets for UI elements prepared that include NORMAL, FOCUSED, ACTIVE and ACTIVE-FOCUSED states.
in case of above mentioned elements. https://github.com/EdgeTX/edgetx/issues/3225

As principal UX rule consistency can't override visibility.
Focus as inversed field is well defined and visible while tiny frame is not.
If there are tougher cases like Lists items or groups that uses tiny frame we shoud find a way to change those cases and not to equalize everything to worse case.

AFAIU libopenui now is under our full control so I can't see the point.

If there are implementation (because of how code is written)  I'm ready to discuss it to find best solution but not to sacrifice principals.

**Comment by pfeerick** [comment]
Before we could even contemplate looking at the stylesheets, the code needed to be unified so things weren't been formatted and modified on every other page. Now that that has been done, starting to implement the stylesheet and progressing on to the 3.0 UI should be easier. 

Your job @JimB40 is to be starting to pull out these details, and pointing to the stylesheet to show how you want it to look, and it'll either happen or you'll be told it's not feasible. ;)

**Comment by JimB40** [comment]
Hmm... Never seen case in my UX/UI career that "code unification" made styling not feasible.
But then okay. Wait and see.

At least EDIT state was reclutant to "refactor" or whatever and is no lookin like this
![Input Edit packed](https://github.com/EdgeTX/edgetx/assets/46420768/f6e7945d-7e54-47e7-ac8a-e5586c71be9c)

**Comment by pfeerick** [comment]
> Hmm... Never seen case in my UX/UI career that "code unification" made styling not feasible. 

🤣 And who said that, other than you? 😛 You'll be told it's not feasible because of resource constraints like memory, processing time, ease of implementation, etc. But remember, baby steps... can't get to the style stuff, until the foundations are ready to actually do it. ;)

> At least EDIT state was reclutant to "refactor" or whatever and is no lookin like this

It depends on what you call "EDIT state" - it helps if you're just going to pull screenshots out to highlight a specific area of interest - do you mean the entire dialog? The input field for "input name" seems to be in focus, but not being edited? If you mean the latter, then I thought that was almost exactly what it looks like...

![image](https://github.com/EdgeTX/edgetx/assets/5500713/b79fccc7-a445-4d64-be7a-62a3d6576d8a)

If you mean the entire edit dialog, no, the refactor was **_not_** related to that at all. For that, you need to work on trying to get https://github.com/EdgeTX/edgetx/pull/2939 how you want it. I stress *try* ... you will not necessarily get it exactly how you want it.

**Comment by JimB40** [comment]
EDITED state is how UI input elements looks when user does editing. 
It's desctibed in UI element styling sheet (if UI element has EDITED state) like #3223
So FOCUSED in now tiny frame around while EDITED remained green inversion after "refactor" or whater it was done.

**Comment by philmoz** [comment]
Border focus indicator is not something new I have added. I've just made it more consistent.

I'm not sure why this is causing so much angst.

Examples from 2.8:
![Screenshot 2023-08-04 at 9 08 36 pm](https://github.com/EdgeTX/edgetx/assets/9474356/8129536b-3ea3-4a50-92da-e10ffb5b8690)
![Screenshot 2023-08-04 at 9 08 51 pm](https://github.com/EdgeTX/edgetx/assets/9474356/075641d5-136a-495f-9690-b8ddcc914f8e)
![Screenshot 2023-08-04 at 9 09 09 pm](https://github.com/EdgeTX/edgetx/assets/9474356/a691f2d2-4507-4f9c-b0ab-ad0db6bb4d43)
![Screenshot 2023-08-04 at 9 09 15 pm](https://github.com/EdgeTX/edgetx/assets/9474356/dfb13e98-7c38-4eb1-aa52-9a35cf8d5ef1)
![Screenshot 2023-08-04 at 9 09 27 pm](https://github.com/EdgeTX/edgetx/assets/9474356/bda57b7b-4e06-4bce-aaec-487e3f00fa18)
![Screenshot 2023-08-04 at 9 09 40 pm](https://github.com/EdgeTX/edgetx/assets/9474356/be7a339c-a0ab-4df1-9281-1d5939c80e2d)
![Screenshot 2023-08-04 at 9 09 54 pm](https://github.com/EdgeTX/edgetx/assets/9474356/ab63efe1-e969-4f79-a2e7-459156371d06)
![Screenshot 2023-08-04 at 9 10 05 pm](https://github.com/EdgeTX/edgetx/assets/9474356/d5a7f108-bf6a-4da6-8296-bc95d422e501)
![Screenshot 2023-08-04 at 9 10 11 pm](https://github.com/EdgeTX/edgetx/assets/9474356/486faec2-c159-4a92-8a16-b64496feb084)
![Screenshot 2023-08-04 at 9 10 20 pm](https://github.com/EdgeTX/edgetx/assets/9474356/4cb2575b-23fa-4441-8de6-9b56dd595ada)

**Comment by JimB40** [comment]
Because inversion is far better visible in direct sun, and that is where I often use radio.

**Comment by pfeerick** [comment]
OK, so you meant "Text Input field EDIT state" ... gotcha. 
![image](https://github.com/EdgeTX/edgetx/assets/5500713/fb7583f9-a9a8-43f7-a926-77aa3fb6d858)

So, if we focus on just the one input field type... what you are calling "Text Input field", it currently looks mostly like the example ENABLED state. 

But when it's in the edited state it's filled with EDIT color, border is EDIT color and text color is PRIMARY2. And when it's FOCUSED, rather than it just being an outline, you want the entire control filled with the FOCUS color, border also FOCUS color and TEXT PRIMARY2? Correct?

**Comment by JimB40** [comment]
Yep.
Have idea that would be good to have half and hour in next dev-hour. So I can explain EdgeTX UI System. 
So if I write later just a name from UI world we both know meaning. So I don't have to explain what UI Atom is :)
![Screenshot 2023-08-04 at 13 10 55](https://github.com/EdgeTX/edgetx/assets/46420768/7488089c-e3d1-4fff-90be-0adcba2a9715)

**Comment by pfeerick** [comment]
Or perhaps you could learn the names of the UI controls that we use all the time, so we don't need to know two lots of terminology 🤪 But yes, that would be a good idea for the next one, as things are getting to a state where this can start happening. 

It's more... keep in mind... how would you explain it if you were face to face... wouldn't you point at what you are talking about? :wink: After all, pulling up a screenshot of the whole screen, and then babbling about EDIT state when in fact you're talking about a particular control isn't quite conveying the message you intended.

**Comment by JimB40** [comment]
Somehow to communicate well in ETX project  I've learned what is behind "commit" or "rebase" to understand, not asking to use "my language". Learned also how to use GitHub even it was not on my "fun to do" list. 
Ussualy worked with front-end devs who knew terminology, so it wasn't my task to check if property for padding is actually named "padding" in CSS or whatever they used. 

If this is going to be boring-half-an-hour-I-dont-need scratching idea now.
After 50 "price" of hour of my life skyrocketed. So I try not make any waste. :)

PS.
Have to think over attitude, maybe @philmoz is right I'm causing too much. This is RC hobby project, not commercial one for big brand.
Cheers :)

**Comment by pfeerick** [comment]
> I'm causing too much

That I can't agree with at all... as much as I would like to get hold of you and shake you at times (still sure you want that face-to-face meet? 🤣 ) ... it's just about trying to find that common terminology that we all understand. As you say, this is hobby/open source, not a commercial project, so gotta be more flexible ;)

**Comment by pfeerick** [comment]
I'mma gonna stomp on this issue for now. Bring it up again as part of the 3.0 UI if still want it changed. IMO, this made things more consistent though...

i.e. **Before**
https://github.com/EdgeTX/edgetx/assets/5500713/1e20074e-6a5f-4462-86bd-680708e7c895


**After**
https://github.com/EdgeTX/edgetx/assets/5500713/732e5e1f-f5d9-429e-a980-3c4a785fae9e
