### ISSUE TITLE
LUA REQUIRE function broken in 2.9 RC1 and RC2

### ISSUE THREAD

**Issue by TakeToTheSky** [EdgeTX/edgetx#3904]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

LUA REQUIRE function is not working in 2.9 RC1 and RC2.  This is working correctly on 2.8.4.

It appears that the 'package' entry is not defined.   I use package.path to define the paths that contain my LUA libraries.

This has been observed on both the transmitter and companion.  The debug output log in companion shows 'attempt to index global 'package' (a nil value)'.

Based on conversations on Discord it appears to have been omitted in 2.9.  Can this please be reinstated?

### Expected Behavior

package.path should return '!\lua\?.lua;!\lua\?\init.lua;!\?.lua;!\?\init.lua;.\?.lua' by default when queried.

package.path should be able to be assigned a path to overide the default search location.

### Steps To Reproduce

Widget with REQUIRE function is not being initialised and is not selectable in widget list.

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by pfeerick** [comment]
Will be fixed in 2.9 final / RC3... Missed including https://github.com/EdgeTX/edgetx/pull/3786 in 2.9 branch.
