### ISSUE TITLE
Lua-Scripts in direct SYS access orderless

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#392]
TX16S Nightly d878efb

please output a alphanumerical order in the list of scripts (direct access via SYS)
Big Thanks

**Comment by raphaelcoeffic** [comment]
> TX16S Nightly [d878efb](https://github.com/EdgeTX/edgetx/commit/d878efb376a64ea440e8b0c0e7c8cda1eb843d9f)
> 
> please output a alphanumerical order in the list of scripts (direct access via SYS)
> Big Thanks

I guess you mean the “TOOLS” page, right?

**Comment by jogybaer0815** [comment]
Yes

**Comment by pfeerick** [comment]
It's probably to do with the order they were added to the file system... they're in alphabetical order on my screen, but I've just copied them on after updating the MPM firmware... but yes, if it doesn't sort then that would be a nice touch indeed.

**Comment by jogybaer0815** [comment]
Okay i am able to rearrange order by delete and recopy files (but have to do this every time a script was updated)

**Comment by pfeerick** [comment]
Thanks for the confirm... so it is obviously just adding in file system order at the moment and needs 'sorting' before it's displayed.
