### ISSUE TITLE
BetaFPV Lite Radio 3 Pro boot stuck on black screen

### ISSUE THREAD

**Issue by atagunov** [EdgeTX/edgetx#3945]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Looks identical to this closed bug report https://github.com/EdgeTX/edgetx/issues/1565 but for a different radio.
Cannot switch on BetaFPV Lite Radio 3

When I press and hold power button
- Led lights green indicating that it is booting (good)
- No haptic feedback, no sound, screen remains black (bad)

Here's what I tried:
- Held button for 75 seconds
- Disconnected for 30 minutes and then re-connected the back side of the radio (that hopefully removes power from the main board)
- updated firmware to 2.8.5 (I can still boot into bootloader and then all works as expected)

No luck. The issue started on stock EdgeTX. I had my ExpressLRS updated via ExpressLRS Configurator possibly to version 3.0.1 a few months before issue started. The radio was always used connected to a PC. The radio did develop a nasty issue where USB connection would be very wonky.

### Expected Behavior

I am wishing that when I hold power button for several seconds BetaFPV Lite Radio 3 would switch on as normal:

- led would light green
- after several seconds holding button there would be haptic feedback
- "welcome to EdgeTX" would sound
- the screen would switch on

### Steps To Reproduce

Push and hold power button

### Version

2.8.5

### Transmitter

BetaFPV LiteRadio3 Pro

### Operating System (OS)

Windows

### OS Version

10

### Anything else?

Exactly same behaviour is show in in a video here: https://www.reddit.com/r/drones/comments/14gt9on/betafpv_literadio_3_pro_doesnt_power_on Some of the comments under that video are from me - so we have two people with same issue.

Discussion of PR https://github.com/EdgeTX/edgetx/pull/2210 contains the following comment:

> [raphaelcoeffic](https://github.com/raphaelcoeffic)
> from what I know, this is more related to the card itself rather than anything else
> This fix is however only for radios using SDIO (as opposed to SPI)

It doesn't look like BetaFPV LiteRadio 3 Pro has a card, don't see it. It seems to be using some chip instead.

**Comment by atagunov** [comment]
After sitting without power (disconnected from the back board) for over 12 hours the radio started booting again.

**Comment by pfeerick** [comment]
Ouch! I don't remember if that radio has a RTC battery off-hand, but it sounds like that was the "something stuck in RTC memory" that sometimes affects the TX16S, and you need to yank both the main battery and the RTC battery, and it will probably be ok after being left like that for 30 mins. 

The LR3 does have a microSD btw, but it's on the other side of the mainboard... meaning you need to completely disassemble the radio to get at it. 🤦

Closing the issue as it seems like it's resolved, or may be a hardware gremlin.
