### ISSUE TITLE
Companion name for 6 POS switch / simulator GPS default value is displayed incorrectly

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3959]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

with 2.9RC2 the name for the 6POS switch (Horus X10) , as well as in the telemetry simulator the default GPS data is displayed incorrectly.
The 6POS switch is called everywhere : 5x {6P?}
![image](https://github.com/EdgeTX/edgetx/assets/15068446/73744a86-5568-4b42-a9f3-4cca52b43ecf)

The default GPS data in the telemetry simulator: 5x {25.9973,-97.1572?}
![image](https://github.com/EdgeTX/edgetx/assets/15068446/aafb2b37-2ed7-4108-901b-d4be84394f78)

### Expected Behavior

6POS Switch defaultname should be: 6P (like in Radiofirmware)
default GPS data in the telemetry simulator: 25.9973,-97.1572

### Steps To Reproduce

open companion
edit radio setting
observe the name of 6P switch

run Simulator
open telemetry simulator
observe the default GPS Value

### Version

2.9.0

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Windows 11

### Anything else?

Etx 2.9 rc2

**Comment by elecpower** [comment]
In English looks okay

![hw6posensml](https://github.com/EdgeTX/edgetx/assets/15316949/40c137f6-a5c4-4932-9ab7-0ea962ab7fa8)

Simulator telemetry

![simtelegpssml](https://github.com/EdgeTX/edgetx/assets/15316949/2da77b96-97d9-4e0d-82a7-d4ff9849d189)

**Comment by elecpower** [comment]
I checked a couple of other languages (French, Italian, Dutch) and they display 6P so it looks like we have a translation corruption.
