### ISSUE TITLE
CPN: wrong labels management assignment display after sorting the models by name (double click on column name)

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3960]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

If the models are sorted by name in the Companion (double-click on column name), the displayed label assignments are no longer correct.

### Expected Behavior

If the models are sorted by name in the Companion (double-click on column name), the displayed label assignments are no longer correct. 
After sorting the models by names, the labels in the column are also sorted, but the wrong checkboxes are set at the bottom of the label management (i.e. the way the models were before sorting).

### Steps To Reproduce

create like this:
![image](https://github.com/EdgeTX/edgetx/assets/15068446/e261e968-6ace-4820-a402-fadf055df0be)

and now, sort by name:
![image](https://github.com/EdgeTX/edgetx/assets/15068446/9cff27ec-08ff-410f-b982-0570815a8782)

### Version

2.9.0

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Windows 11

### Anything else?

etx 2.9 rc2

**Comment by elecpower** [comment]
Confirmed the sort breaks the index used by Labels Management
