### ISSUE TITLE
Confirmation for duplicate model like there is for delete model

### ISSUE THREAD

**Issue by mshonak** [EdgeTX/edgetx#3976]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm always frustrated when I press on duplicate model by mistake and it duplicate it without asking me for confirmation like it does when I try to delete model . 

### Describe the solution you'd like

It should ask me if I am sure before making a duplicate model or even make the duplicate but give it a new name ( or just add to the new duplicate model name a number ) .

**Comment by offer-shmuely** [comment]
I am also find sometimes duplicated models that come from no where, looks like sometime i press the incorrect button, and it duplicates

**Comment by pfeerick** [comment]
For what radio, and what ETX version? ColorLCD since 2.8 does have a confirmation on duplicate.

**Comment by mshonak** [comment]
> For what radio, and what ETX version? ColorLCD since 2.8 does have a confirmation on duplicate. Duplicating (copy) on B&W is a two step process, so I suspect you're still running an older ETX version on colorlcd.

I am using edge tx 2.8.5 on tx16s  and there is no confirmation when duplicate model .

**Comment by mshonak** [comment]
Sorry - I checked and it did ask if i want to duplicate model on my radio TX16s EdgeTX 2.8.5  -  I got this request from friend and didn't check myself this issue,  i just remember that it was duplicate the model without asking  .

**Comment by mshonak** [comment]
Sorry - I checked and it did ask if i want to duplicate model on my radio TX16s EdgeTX 2.8.5 - I got this request from friend and didn't check myself this issue, i just remember that it was duplicate the model without asking .

**Comment by mshonak** [comment]
Sorry - I checked and it did ask if i want to duplicate model on my radio TX16s EdgeTX 2.8.5 - I got this request from friend and didn't check myself this issue, i just remember that it was duplicate the model without asking .
