### ISSUE TITLE
Text boxes can't be tapped to edit

### ISSUE THREAD

**Issue by jmil-dev** [EdgeTX/edgetx#398]
All controls (apart from textboxes) can be tapped twice to edit - first tap selects, second tap enables editing.

Text boxes can be tapped to select, but then the Enter button has to used to enable editing.

**Comment by pfeerick** [comment]
It seems to vary by text box also, or model settings -> trainer channel edit boxes can be two tapped and edited... As can radio setup --> date fields... But not model setup -> model name, or model setup -> timer 1-> name

**Comment by JimB40** [comment]
still valid?

**Comment by pfeerick** [comment]
I don't think so... I suspect that it was resolved in 2.5 in through something to do with the on screen keyboard.

**Comment by JimB40** [comment]
but now single tap on text box opens keyboard. Can be closed.
