### ISSUE TITLE
CPN: LS and RS not set correctly after reading Model and settings from radio

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#3982]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

in Companion in the hardware settings the sliders LS and RS not set correctly after reading Model and settings from radio

Radio:
![image](https://github.com/EdgeTX/edgetx/assets/15068446/34798541-f259-4e8e-982f-f8d2d1377095)

Companion:
![image](https://github.com/EdgeTX/edgetx/assets/15068446/8846a6f4-bc00-4963-9e38-fc99a6767407)

### Expected Behavior

in the Comapnion the settings from the radio profile should be taken over correctly after reading the model and radio settings

### Steps To Reproduce

- build companion with RM TX16S with current main 
- make sure that in the radio under Hardware/Sliders LS and RS is assigned correctly and is no longer set to "none"
- start companion
- read modell and radio settings
- observe Radio Settings/TAB Hardware
- both Slider LS and RS are set to "none"

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Win11

### Anything else?

current main

**Comment by pfeerick** [comment]
Thanks for reporting this... I hit it the other day myself when preping
companion support for another radio but wasn't sure yet if I'd screwed up
something in the implementation or not. 😅

**Comment by 3djc** [comment]
Sound like the return of the vengeance of adc refactor part II

**Comment by elecpower** [comment]
and #3870 will completely break it again

**Comment by 3djc** [comment]
Indeed, no point in fixing before 3870 gets in

**Comment by elecpower** [comment]
The Companion refactor will parse the hw json files for 2.10 onwards but as usual the biggest pain point is data mapping from the earlier hard coded definitions.

**Comment by 3djc** [comment]
We are currently generating json on the fly per radio, with much more info than you need. We probably should try to make one file for companion use that gives all the info for all radio at once

**Comment by elecpower** [comment]
It is my understanding that on the fly is only a temporary method.
I have some code that handles a permanent json file per radio and ignores the entries that Companion does not care about.
I'm not in favour of an all radios config file as differences will inevitably occur in maintenance.
