### ISSUE TITLE
Jumper T20 function switches like Jumper T-Pro

### ISSUE THREAD

**Issue by jappyjan** [EdgeTX/edgetx#3984]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The Jumper T-Pro as well as the Jumper T-20 both have 6 switches on the front that act together like a big multipos switch.
The difference is that one the T-Pro we can change this behaviour and make each button a standalone toggle button,
this is currently not possible for the T20.

### Describe the solution you'd like

Enable the Function-Switches behaviour/config for the T20.
I could do this on my own, but i cannot find any documentation on how to develop EdgeTX or change the radio definition and just poking around in the code left me clueless...

**Comment by 3djc** [comment]
Make sure you have the latest firmware available: https://edgetx.org/supportedradios/

![image](https://github.com/EdgeTX/edgetx/assets/5167938/11a95d0c-a835-43d6-b01f-944a8038ab43)
