### ISSUE TITLE
Wrong visualization of switches on 9XD

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#3995]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On main page switches are visualized wrong like attached picture
Firmware is self compiled (2.9)
On companion simulator the visualization is correct but not in the mode as displayed in the attached image

### Expected Behavior

Correct visualization of all switches

### Steps To Reproduce

go to main page and scroll with PAGE key

### Version

2.9.0

### Transmitter

FrSky X9D

### Operating System (OS)

Linux

### OS Version

Linux Mint 20

### Anything else?

![screen-2023-09-03-091258](https://github.com/EdgeTX/edgetx/assets/6508436/2a3e78d4-1fec-4079-82c9-75396656f73e)

**Comment by pfeerick** [comment]
Is this really 2.9, or is this main (which is 2.10 - as will be indicated on the version page).

**Comment by MicheleVilla** [comment]
Screenshot was take in main, but in recompiled firmware from 2.9 the
visualization remains the same
If you want I can post the screenshot from right version (2.9)



Il dom 3 set 2023, 11:19 Peter Feerick ***@***.***> ha
scritto:

**Comment by pfeerick** [comment]
No, that's great... means the issue really should be fixed by #3996 as it will be due to the new hardware abstraction layer in 2.10 / main. Thanks for reporting it! :)
