### ISSUE TITLE
Reversed Pots on display:

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#40]
Test report by @rotorman:
On the calibration screen, on TX16S, the pot S1 and S2 state are IMHO shown on the screen horizontally mirrored - turning the pots clockwise make the needle wonder to left and vice-versa. I believe it should be CW movement -> needle to the right.

**Comment by pfeerick** [comment]
Agreed... this would make it consistent with the actual channel output visualization 😉

**Comment by raphaelcoeffic** [comment]
Fixed by #45
