### ISSUE TITLE
Power on delay

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#400]
Tx16s
Rc3
option to choose seconds to hold power button when turning on and a haptic or audio alert when you have held the button long enough. I'm finding the power on button press is too long and in sunlight I cant see the lights so I tend to let go of the power button too soon. Some times it takes me multiple attempts to turn on. Frustrating!

**Comment by pfeerick** [comment]
I believe the power on delay on these radios T16 is in the hardware - i.e. it's not deliberate and configurable delay.

**Comment by pfeerick** [comment]
This is also a duplicate of https://github.com/EdgeTX/edgetx/issues/237
