### ISSUE TITLE
HW -> Analogs -> screen clipping and cross position...

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#401]
Low priority...

On the SYS => Hardware => Analogs screen, the X for the touchscreen gets clipped when it's on the right, and is not indicative of the actual position being touched... the actual touched position is the top left corner of the X, not he middle of the X - as can been seen if touchging the far right of the screen and getting the X nearly off screen, with co-ordinates of around 472+ pixels on a 480 pixel wide screen. 

Any substantive touchscreen 'testing'  (i.e. anything more than "is it alive and reporting sane co-ordinates relative to the screen") isn't ideal on that screen at present, as it also seems like the header bar can't be drawn over, and has a 5px or so margin underneath. 

Reported by Risto on Discord, with some accompanying text and photos. 
https://discord.com/channels/839849772864503828/839895574244229152/861167038893129758

**Comment by gagarinlg** [comment]
fixed by #3240
