### ISSUE TITLE
The mixes screen doesn't have realtime feedback of changes

### ISSUE THREAD

**Issue by jmil-dev** [EdgeTX/edgetx#404]
Similar to #307 the new UI doesn't have any way to see the values on the screen, on either:
- [x] overview screen (#2226)
- [x] mix detail/edit screen (#1074)

**Comment by pfeerick** [comment]
As a suggestion, when editing a mix, would pressing/long pressing MDL (and adding a button somewhere for touch) and bringing up the channel monitor be an appropriate resolution?

Or bar on the mix screen that shows the current mix output, similar to that shown for the channels?

Any other suggestions?

**Comment by raphaelcoeffic** [comment]
> As a suggestion, when editing a mix, would pressing/long pressing MDL (and adding a button somewhere for touch) and bringing up the channel monitor be an appropriate resolution?
> 
> Or bar on the mix edit screen that shows the current mix output, similar to that shown for the channels?
> 
> But yes, i think we need to look at adding something similar to this to the mix screen proper...
> 
> ![image](https://user-images.githubusercontent.com/5500713/125375607-aec65880-e3cc-11eb-806f-6ebc82e225a9.png)
> 
> Any other suggestions?

I would like this as a "bottom status bar". @JimB40 any comments on that?

**Comment by JimB40** [comment]
Bottom Bar overlay is better.
1. Channel name is not displayed as we know it's selected one
2. Output bar id not displayed as we don't know if this mix is bound to any output
So basically just a bar. I would add % and us values n a way it's implemented in channel monitor
This mini-monitor can be visible in edit mode too so we can check changes without going back to mixer list

**Comment by pfeerick** [comment]
1 & 2 and generall points all sound good.

3 - Huh? Since when can mixes not be bound to an output? (Inputs, sure, but mixes are CH specific). However, I still agree it's not needed - especially if it is made possible to access the channel monitor quickly again, via a second press of the MDL button (whilst in the model setup screen).

**Comment by jmil-dev** [comment]
I like the bottom mix bar.

If space is a problem it could be at the left/right

**Comment by Moksh-2000** [comment]
> I like the bottom mix bar.
> 
> If space is a problem it could be at the left/right

Yepppp i like too when you do something new or crazy add or multiply or something new then you should to know how's your pwm value react at specific point , i always use this for making something else @pfeerick hope you understand and @jmil-dev are right if problem with space then adjust somewhere but bottom is sure

**Comment by pfeerick** [comment]
A Channel monitor button was added in 2.7 (now gone again :-O), and with 2.8 there is a toggle option at the bottom to show a mixer bar on demand for each mix.
