### ISSUE TITLE
Outdated link to Multilingual Builds on https://edgetx.org/getedgetx/

### ISSUE THREAD

**Issue by Ralf-W** [EdgeTX/edgetx#4042]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Other (Please specify below)

### Current Behavior

The link to Multilingual Builds at the bottom of the page https://edgetx.org/getedgetx/ is linking to the outdated version V2.8.4.
[EdgeTX 2.8.4 Multilingual builds](https://github.com/pfeerick/lang-firmwares/releases/tag/v2.8.4)

### Expected Behavior

This link should always point to the latest release - at the moment to V2.9.0
[EdgeTX Latest Multilingual builds](https://github.com/pfeerick/lang-firmwares/releases/tag/v2.9.0)

### Steps To Reproduce

Go to bottom of page https://edgetx.org/getedgetx/ 

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by pfeerick** [comment]
Thanks for that. Also updated some of the other links on that page for 2.9.0. 

https://github.com/EdgeTX/edgetx.github.io/commit/c8bb0fb1136a15393f85914096106084c4f3d7bf
