### ISSUE TITLE
Build FW in Browser with gitpod currently not possible

### ISSUE THREAD

**Issue by 3DRacer** [EdgeTX/edgetx#4053]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Build system

### Current Behavior

![grafik](https://github.com/EdgeTX/edgetx/assets/42546574/b3f71022-d23f-4acf-883d-105e05fb2ea1)

Oh, no! Something went wrong!

supervisor run error with unexpected exit code: IDE failed to start: exit status 1

### Expected Behavior

site starts without error

### Steps To Reproduce

try to open https://gitpod.io/#https://github.com/edgetx/edgetx/tree/main

https://github.com/EdgeTX/edgetx/wiki/Building-radio-firmware-in-a-webbrowser-with-Gitpod

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

11

### Anything else?

![grafik](https://github.com/EdgeTX/edgetx/assets/42546574/d7b7866a-470f-40d3-ba1d-80efed89db29)

**Comment by koaxheli** [comment]
I have the same error since the day before yesterday.

Oh, no! Something went wrong!
supervisor run error with unexpected exit code: IDE failed to start: exit status 1

 
edgetx-edgetx-ltm7g3kmul2

https://github.com/EdgeTX/edgetx/tree/main

**Comment by koaxheli** [comment]
Error message is not yet removed.
Still exists when compiling under Gitpod.

![image](https://github.com/EdgeTX/edgetx/assets/92114465/aabe3c17-31b3-47dd-862e-f1a5660c4d05)

**Comment by raphaelcoeffic** [comment]
Guys, please test using #4065.

**Comment by 3DRacer** [comment]
> Guys, please test using #4065.

compiling FW for the RM TX16S and download ..... success

**Comment by koaxheli** [comment]
Tested: 
EdgeTX version 2.9 is OK. Tested with #4065

But the latest version 2.10.0 still kept the bug.

The call on Gitpod is the following, which has always worked so far.

https://gitpod.io/#https://github.com/EdgeTX/edgetx/tree/main

**Comment by koaxheli** [comment]
I have a request, can you still provide an update for the main development branch 

https://gitpod.io/#https://github.com/edgetx/edgetx/tree/main

as you did for

https://gitpod.io/#https://github.com/edgetx/edgetx/tree/2.9-gitpod-workspace

As for the v2.10.0 on Github also runs into the same error.

Thanks

**Comment by pfeerick** [comment]
Of course. #4065 need to be merged first ;)
