### ISSUE TITLE
Frsky ACCST telemetry sensor lost and Lua scripts not working

### ISSUE THREAD

**Issue by chrisleprince** [EdgeTX/edgetx#4054]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Following update on ETX 2.9.0 on TX16S, all the telemetry sensors are lost with ACCST V2 EU LBT. 
Furthermore, LUA scripts to setup frsky hardware aren't working anymore.

### Expected Behavior

recover full bidirectional telemetry link with ETX 2.9.0 to get proper frsky lua scripts working again. 

### Steps To Reproduce

launch RB30/RB40 setup LUA scripts available from FRSKY website. 
Keep saying "waiting for hardware version"
[RB30 LUA script.zip](https://github.com/EdgeTX/edgetx/files/12641170/RB30.LUA.script.zip)

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by raphaelcoeffic** [comment]
Duplicate, please check https://github.com/EdgeTX/edgetx/discussions/4052
