### ISSUE TITLE
QX7 restarts or glitching on 2.9.0 , no problem on 2.8.5

### ISSUE THREAD

**Issue by zigg1312** [EdgeTX/edgetx#4073]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Occasional restarts even when idle. Not full reboot.  
background.  
Upgrade to 2.9.0 and system rebooting fully occasionally. 
Downgrade to 2.8.5 and was able to use without incident for multiple hours in liftoff using internal xjt and frsky rx (XSM-SIM) 
Facebook group suggested clearing sdcard which I replaced and dl 2.9 sdcard contents and reloading models and settings from OPENXT backup 
reflashed to 2.9.0 and will glitch - screen blanking and speaker click and loss of connection but not full reboot like previously 

### Expected Behavior

No - expect it to work as well as 2.8.5

### Steps To Reproduce

Just sitting idle it restarts about every minute

### Version

2.9.0

### Transmitter

FrSky Q X7 / Q X7S (ACCST)

### Anything else?

Willing to do anything to debug - just need instructions. However will be reflashing to 2.8.5 to escape this problem, but can reflash if requested. 
Have done the crossfire mod to transmitter , but everything in 2.8.5 works as expected for multiple hours , just 2.9.0 is problematic.

Many thanks and great work !

**Comment by zigg1312** [comment]
Just noticed flashing exclamation mark in top left corner (!) - cannot find explanation of what this is signalling

**Comment by philmoz** [comment]
Can you zip up you MODELS and RADIO folders plus any Lua scripts being used and post them here please.

**Comment by philmoz** [comment]
> Just noticed flashing exclamation mark in top left corner (!) - cannot find explanation of what this is signalling

This means the radio crashed and rebooted into emergency mode.

**Comment by zigg1312** [comment]
[modelsradioscripts.zip](https://github.com/EdgeTX/edgetx/files/12682021/modelsradioscripts.zip)

Thanks Philmoz!

**Comment by zigg1312** [comment]
model i was using is called sim uses the xjt internal d16 with telemetry but not discovered or use sensors, but all models probably all use xjt except for one with r9

**Comment by philmoz** [comment]
Can you please try the attached model file on your radio.

Rename the file to model09.yml (from model09.txt) and replace the model file on your SD card.

[model09.txt](https://github.com/EdgeTX/edgetx/files/12696408/model09.txt)

**Comment by zigg1312** [comment]
Tried that model, no change. Interesting development - I bound using irange 4in1 instead of XJT and internal module off and everything fine, no crash or emergency mode. which suggests differences in radio communication between versions

**Comment by philmoz** [comment]
> Tried that model, no change. Interesting development - I bound using irange 4in1 instead of XJT and internal module off and everything fine, no crash or emergency mode. which suggests differences in radio communication between versions

Very strange. Your model09.yml file crashes my X7S consistently; but it is ok with the changes I made.

**Comment by zigg1312** [comment]
maybe flash to 2.8.5 to see if it crashes you on that version?  Anyway will create a new model in 2.9 and see where I get. with that - I dont mind if I have to recreate all models as I am just getting back into it after giving up a few years ago when opentx was at 2.2 something

**Comment by philmoz** [comment]
There's definitely something crashing in the code; but at least now we can reproduce it (at least I can).
That's a big step towards finding and fixing the cause.

**Comment by raphaelcoeffic** [comment]
It seems the actual issue is the SBUS trainer which setup in this model (see #4086)

**Comment by raphaelcoeffic** [comment]
@zigg1312 @philmoz would you mind trying this firmware?

[firmware.zip](https://github.com/EdgeTX/edgetx/files/12698013/firmware.zip)

**Comment by philmoz** [comment]
I tried a build of main (2.10) with your patch and no crashes so far (previously it would crash very quickly).
