### ISSUE TITLE
Error assigning trainer Sticks Ail-Ele-Thr-Rud 

### ISSUE THREAD

**Issue by Xavitorradas** [EdgeTX/edgetx#4089]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

As I assign a Special Functions for Trainer with individual chanels the label when assigning is different when it appears in special functions. Nigthly last versions.
I have done a video with this issue.
  This function is usefull if I wnat to send only some chanels to the alumn transmiter and increasing this chanels as soon the alumn is growing in hability.

### Expected Behavior

I select a stick and this stick must appears in Special Functions

### Steps To Reproduce

1- Select Special Functions
2- Select new SF
3- Select SH down
4- Select Trainer
5- Select a Stick ( Ail, Ele, Thr or Rud )
6- back to SF and see the label is not the selectet item

### Version

2.9.0

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

https://github.com/EdgeTX/edgetx/assets/82335501/ef94d845-25da-459b-add9-f8c2b3633e20

**Comment by pfeerick** [comment]
Thanks for the report... should be resolved in the next nightly thanks to Phil's quick fix of the culprit ;)
