### ISSUE TITLE
Companion - Calibration is not read correctly

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#4099]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

with latest Companion nightly `0aff002c` the calibration is not read correctly

see the Rudder on screenshot - S1 and S2 are ok, these have been deactivated

![Screenshot 2023-09-24 091157](https://github.com/EdgeTX/edgetx/assets/29702171/634dde7a-0631-4987-acda-bf8bb64c5095)

### Expected Behavior

Correct calibration values when reading out the transmitter

### Steps To Reproduce

...

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster Zorro

### Operating System (OS)

Windows

### OS Version

11

**Comment by pfeerick** [comment]
@TheIsotopes Can you double-check something for me on another issue... does the edit button on the toolbar (and/or the context menu) work for you? If not, I need to open an issue for that, as can only edit by double-clicking on the model atm. 🤪 

![image](https://github.com/EdgeTX/edgetx/assets/5500713/d0168a8e-4818-4a4a-b013-23fddb8cb26a)

**Comment by TheIsotopes** [comment]
@pfeerick You are right, the button has no function.

**Comment by elecpower** [comment]
Companion Nightlies are broken again with the latest adc refactor on the radio side.

**Comment by pfeerick** [comment]
Now that you're back, https://github.com/EdgeTX/edgetx/pull/3870 is going to be merged in the next couple of days, so expect more stuff to break 😆 This is the last expect breakage for this cycle.
