### ISSUE TITLE
Edit button / context menu entry not working in Companion

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#4100]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

In Companion, neither clickong on the Edit icon in the toolbar, nor using the "Edit Model" option in the context menu work.

![companion_0mKpUYCnLd](https://github.com/EdgeTX/edgetx/assets/5500713/8a81953e-208b-4c82-bd84-19a8faf1a5b3)

![companion_dsNMBi60KB](https://github.com/EdgeTX/edgetx/assets/5500713/dce08e11-61ac-452b-b3bb-40c0b55cea16)

When running a Companion build under WSL, I got this warning when I tried either option, not sure if it is related, but it also didn't work there, so doesn't appear to be OS specific. 

```
[W] unknown():0 - QSortFilterProxyModel: index from wrong model passed to mapToSource
```

Affects both main and 2.9, not 2.8. 

### Expected Behavior

For me to not have to reach for the Enter key or double click to be able to edit a model! 🙈 

### Steps To Reproduce

Open or create a new model settings file, and try to edit a model using the toolbar or context menu options. 

### Version

2.9.0

### Transmitter

Other (Please specify below)

### Operating System (OS)

Windows

### OS Version

11 22H2

**Comment by elecpower** [comment]
I broke these functions when I added the sort and your debug msg let me know that I am the cause and thus the fixer.
