### ISSUE TITLE
No Fail-Safe Setting in Companion

### ISSUE THREAD

**Issue by Hartinger** [EdgeTX/edgetx#4106]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

With Companion 2.9.0 the settings for the internal RF module do no longer contain any fail-safe settings.

![FS](https://github.com/EdgeTX/edgetx/assets/22352021/b4e9c525-2e6e-4e60-9762-93034bd841c1)

### Expected Behavior

Fail-safe can be configured as part of the settings for the internal module, as per Companion 2.8.5.

![FS_old](https://github.com/EdgeTX/edgetx/assets/22352021/d82ca332-e394-4f67-aee2-7b5993f8976a)

### Steps To Reproduce

1. Start Companion
2. Load an etx file

### Version

2.9.0

### Transmitter

FrSky X9D+2019, FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

Windows 11

**Comment by msun12000** [comment]
I can confirm exactly the same issue with my Transmitter X9 Lite S. The failsafe settings are accessible on the TX and the settings are preserved when writing to and then reading from Companion 2.9.0

**Comment by pfeerick** [comment]
The missing USB joystick config was a todo from #2277 that I missed when it was taken over into #3111
