### ISSUE TITLE
Fix UI Slider Styling

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#4119]
Now UI slider is bit overwhelming in comparison to previous styling
![ext210_slider_comp](https://github.com/EdgeTX/edgetx/assets/46420768/442de0b7-6c4f-4518-8ade-74172637d189)

### Describe the solution you'd like

![ext210_slider_new](https://github.com/EdgeTX/edgetx/assets/46420768/14ef537b-e5db-4787-b0f9-2d1f16aaa885)

Normal State

1. Change TRACK height back to 8px
2. Increase KNOB border to 2px as other elements

Focused State
TRACK color and KNOB border color changes to FOCUS color

Edited state
TRACK color changes to EDIT color while KNOB border color stays in FOCUS color to give separation

**Comment by JimB40** [comment]
![Screenshot 2023-09-28 at 09 12 27](https://github.com/EdgeTX/edgetx/assets/46420768/66d996c4-624b-4034-932a-435c68c27401)

Alternative version of EDIT state.
IMHO changing track color is better. What you think @philmoz?

**Comment by philmoz** [comment]
Probably worth combining this with #4118 - can you please provide feedback on the tick mark concept.

**Comment by philmoz** [comment]
Something else to consider - the slider knob does not have to be round.

![Screenshot 2023-09-28 at 7 18 19 pm](https://github.com/EdgeTX/edgetx/assets/9474356/884d9166-fcf6-4dbe-9d33-f35138a2876f)

**Comment by JimB40** [comment]
Indeed in fact in initial design #3258 I've made slider knob rectagular with round edges, leaving circle for Switch only.
![Screenshot 2023-09-28 at 11 44 28](https://github.com/EdgeTX/edgetx/assets/46420768/4eb4d00b-e5e6-478e-bb18-d2fdbbb0f503)
Should be slightly wider.

Are those tick marks LVGL standard feature?

**Comment by JimB40** [comment]
3 different styles as propsal
![Screenshot 2023-09-28 at 12 07 48](https://github.com/EdgeTX/edgetx/assets/46420768/602db2f4-ced1-4a5d-bb18-8260dada24c9)

**Comment by philmoz** [comment]
The tick marks are being drawn manually - not an LVGL feature.

The knob can be either a rectangle with round corners or a circle - so the 'Beep length' option in the image above is only one that could be done.

**Comment by JimB40** [comment]
I think dots as John mentioned look more clean
![Screenshot 2023-09-28 at 12 17 28](https://github.com/EdgeTX/edgetx/assets/46420768/dcecfaa5-bb61-49aa-8c62-603ffa2d61d3)


and there is certain level of granulatity at which dots shoul not be displayed.
To my eye more than 15-16 levels.. but this depends on track size.

**Comment by philmoz** [comment]
I can't draw between the slider and knob - I can only draw custom lines underneath the whole slider object.

**Comment by JimB40** [comment]
![Screenshot 2023-09-28 at 12 31 12](https://github.com/EdgeTX/edgetx/assets/46420768/95b5fa98-810c-40ea-ac38-582f38c5abe5)
From what I can test, hotspot is a track not knob.
But hotspots are strangely defined.
It looks they follow Beep volume pattern rather than Beep lenght (which is proper UI method)

Can you confirm?
Have you got any control over hotspots?

**Comment by philmoz** [comment]
> From what I can test, hotspot is a track not knob. But hotspots are strangely defined. It looks they follow Beep volume pattern rather than Beep lenght (which is proper UI method)
> 
> Can you confirm? Have you got any control over hotspots?

Sorry, I don't understand the question.

**Comment by JimB40** [comment]
> > From what I can test, hotspot is a track not knob. But hotspots are strangely defined. It looks they follow Beep volume pattern rather than Beep lenght (which is proper UI method)
> > Can you confirm? Have you got any control over hotspots?
> 
> Sorry, I don't understand the question.

Try to slide you finger on the track and observe when knob changes position. It follows first hotspot layout (marked orange) rather then desired second layout.

**Comment by JimB40** [comment]
![Screenshot 2023-09-28 at 12 52 08](https://github.com/EdgeTX/edgetx/assets/46420768/242cfe07-2f62-4d26-9a14-b3b8b1ff91f9)
Conept with 2px dots over track

**Comment by philmoz** [comment]
> Try to slide your finger on the track and observe when knob changes position. It follows first hotspot layout (marked orange) rather then desired second layout.

That's all controlled by LVGL.

**Comment by philmoz** [comment]
Aligning the dots to the center of the knob looks like this. I think it looks better without the end point dots.

![Screenshot 2023-09-28 at 9 17 32 pm](https://github.com/EdgeTX/edgetx/assets/9474356/67c99441-29ba-4baa-a2d9-6d38884abb5e)

**Comment by JimB40** [comment]
Yes, end-points are obvious

**Comment by JimB40** [comment]
> > Try to slide your finger on the track and observe when knob changes position. It follows first hotspot layout (marked orange) rather then desired second layout.
> 
> That's all controlled by LVGL.

Then we have to live with what LVGL guys coded.
