### ISSUE TITLE
No mixer scripts on TX16s

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#412]
**Describe the bug**

no mixer scripts are available, the tab for the scripts does not show up in the icon bar

**To Reproduce**

cmake -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X10 -DPCBREV=TX16S -DINTERNAL_MODULE_MLLTI=YES -DGVARS=YES -DLUA=YES -DALLOW_TRAINER_MULTI=ON -DCROSSFIRE=OFF -DXJT=ON  -DOVERRIDE_CHANNEL_FUNCTION=OFF ..

**Comment by lshems** [comment]
You need to compile with Lua option. I will check if they work for me this evening

**Comment by lshems** [comment]
Is there a typo on the MLLTI part. That might ruin things

**Comment by wimalopaan** [comment]
> Is there a typo on the MLLTI part. That might ruin things

its not, was wrong copy-paste

**Comment by wimalopaan** [comment]
it is simply not implemented

**Comment by lshems** [comment]
Fun. Only for colour or also missing for B/W.

**Comment by lshems** [comment]
Someone must have decided to take it out. Either before or after the fork, that's the question. Lol

**Comment by raphaelcoeffic** [comment]
> Someone must have decided to take it out. Either before or after the fork, that's the question. Lol

Really nothing intentional: it has just been forgotten, and that was before forking.

**Comment by lshems** [comment]
I forget my own birthdays, so no big deal. I do wonder if it can be brought back in a more reliable way. Lol

**Comment by wimalopaan** [comment]
> > Someone must have decided to take it out. Either before or after the fork, that's the question. Lol
> 
> Really nothing intentional: it has just been forgotten, and that was before forking.

I hope you can get it in very soon ;-) 
This is basic functionality and should be supported by etx in 2.4.0.

**Comment by sfjuocekr** [comment]
There were a lot of things on the 2.3 master branch that had not trickled down into the 2.4 branch yet before it got forked!
