### ISSUE TITLE
Date resets when year reaches 2038

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#4120]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter Firmware

### Current Behavior

https://youtu.be/nVDchdRzFIc

When scrolling the year in Radio Setup, and the year rolls over, the day and month are reset.

### Expected Behavior

For the day and month to not change. 

### Steps To Reproduce

watch video

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

2.10 nightly

**Comment by pfeerick** [comment]
"Fix" doesn't mean much... I presume you want the day and month to not be reset/change? This would probably need for the UI to be de-coupled from the hardware, as it is the RTC that you are setting live (as is the case for most fields that don't pop up) while editing the date that is saying the date is invalid, and resetting to 1-1-1970. This applies across the board - B&W and color.

**Comment by philmoz** [comment]
Set an upper limit on the year value that does not overflow?

**Comment by pfeerick** [comment]
Yeah, we might as well join the party... 2038 is a big year for everyone... 🤣 https://en.wikipedia.org/wiki/Year_2038_problem
