### ISSUE TITLE
UI - RADIO/Trainer screen fix 

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#4121]
![screenshot_tx16s_23-09-28_09-41-19](https://github.com/EdgeTX/edgetx/assets/46420768/e06fc674-bcd7-4818-b510-e2b0abb1ea48)

1. Unecessary scrollbar
2. 'Cal' button name is enigmatic

### Describe the solution you'd like
             
![screenshot_tx16s_23-09-28_09-41-19-2](https://github.com/EdgeTX/edgetx/assets/46420768/0d3bfbe1-2e45-44e7-9178-b0ccc7461a03)

1. Move 'Multiplier group' up so scrollbar is not displayed.
2. If 'Cal' stands for 'Calibrate' button name shoulld be 'Calibrate' or 'Adjust' to be self explanatory.

**Comment by pfeerick** [comment]
"Calibrate"... "Adjust" would imply there is some user input in the matter (such as a popup), rather than calibrating the center-point for trainer input.
