### ISSUE TITLE
since 2.9.1 the mixers can no longer be inserted correctly via lua

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#4128]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

since 2.9.1 the mixers can no longer be inserted correctly via lua. 
On the one hand the lines are no longer correct and on the other hand only one line is inserted, although several lines were specified in the script.

in 2.9.0 the lua script works as expected

### Expected Behavior

mixes should be inserted correctly

### Steps To Reproduce

1. try to insert mixes via lua script like this:
	
model.insertMix(8,0, {name="Gain9M", switch=19, source=118, weight=80, multiplex=0, speedDown=0, speedUp=0, delayDown=0, delayUp=0, carryTrim=true, offset=0, flightModes=0, curveValue=0, curveType=0})

model.insertMix(8,1, {name="Gain9+", switch=20, source=110, weight=30, multiplex=0, speedDown=0, speedUp=0, delayDown=0, delayUp=0, carryTrim=true, offset=0, flightModes=0, curveValue=0, curveType=0})

model.insertMix(8,2, {name="Gain9", switch=21, source=110, weight=25, multiplex=0, speedDown=0, speedUp=0, delayDown=0, delayUp=0, carryTrim=true, offset=0, flightModes=0, curveValue=0, curveType=0})

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS), Radiomaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Win11

### Anything else?

tested with 2.9.1 TAG 50b0dd7

**Comment by pfeerick** [comment]
This should also affect main as it was added at the same time.
