### ISSUE TITLE
iFlight Commando 8 - after update to 2.9.0 - Random Sounds Play on Page 1/7 

### ISSUE THREAD

**Issue by TonyNJFPV** [EdgeTX/edgetx#4130]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Just flashed new firmware. After upgrade, sound is playing when on page one of menu. Just a high rate, very low volume string of digital beeps repeating. 

### Expected Behavior

No random sound playing. 

`<iframe width="560" height="315" src="https://www.youtube.com/embed/8pDMORqVDF4?si=t-EAYHFMwWLrE6yB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

### Steps To Reproduce

1. Turn on TX
2. Go to page 1 of menu
3. Listen

### Version

2.9.0

### Transmitter

iFlight Commando8

### Operating System (OS)

Windows

### OS Version

10

### Anything else?

No.

**Comment by pfeerick** [comment]
This is not a bug. As mentioned in https://github.com/EdgeTX/edgetx/issues/4059#issuecomment-1740126506, you need to turn off the audio.
