### ISSUE TITLE
Splash screen backround  ... must leave

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#4134]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

![screenshot_tx16s_23-09-29_06-04-28](https://github.com/EdgeTX/edgetx/assets/46420768/0b2fce2d-7b07-4e2e-b63d-70f378e6b9f6)

Guys I know we use what we have but...
This bkg looks: outdated, ugly, incompatible with Eddie ... pick watever you want
It's like to buy new car and put old worn out tyres ...

### Describe the solution you'd like

As there was infinite discussion about new backround ie "I like, I dont like, maybe this maybe that" ...
Just make background PRIMARY3 (dark blue) like on our EdgeTX banner and it will look awesome.

Then disscusion can be continued ...

**Comment by philmoz** [comment]
I think black looks better.

![Screenshot 2023-09-29 at 3 38 15 pm](https://github.com/EdgeTX/edgetx/assets/9474356/0ad30695-9498-4d86-9ac1-e99a29e9daca)

![Screenshot 2023-09-29 at 3 40 58 pm](https://github.com/EdgeTX/edgetx/assets/9474356/4e1389cc-edd3-4d23-8bb5-ea4cfb4d295d)

**Comment by raphaelcoeffic** [comment]
@philmoz I'm good with both!

**Comment by philmoz** [comment]
Or dark grey. IMO there is too much blue with the blue background.

![Screenshot 2023-09-29 at 3 47 15 pm](https://github.com/EdgeTX/edgetx/assets/9474356/fa9f1c92-b604-414a-b45e-82edad203b4f)

**Comment by raphaelcoeffic** [comment]
> Or dark grey

Not bad either, it allows for seeing the black shadow.

**Comment by philmoz** [comment]
> Not bad either, it allows for seeing the black shadow.

Actually the shadow annoys me a tiny bit as it's not unidirectional - it spreads out in all different directions (not realistic).

**Comment by JimB40** [comment]
Hahah I love when it comes to colors.
Whichever you choose it will be better.
IMHO simple black is the best.. preserving battery life ;)

**Comment by gagarinlg** [comment]
> > Not bad either, it allows for seeing the black shadow.
> 
> Actually the shadow annoys me a tiny bit as it's not unidirectional - it spreads out in all different directions (not realistic).
> 

There is an invisible light source between you and the logo, so it is realistic.

**Comment by philmoz** [comment]
> There is an invisible light source between you and the logo, so it is realistic.

Where can I buy an invisible light source :)

**Comment by pfeerick** [comment]
Any particular reason the images are like twice actual size? Just it's making things distorted 👀 

![image](https://github.com/EdgeTX/edgetx/assets/5500713/6833cae8-5650-4308-98ec-43575b33df1d)

The grey is nice as it shows the shadowing, but it's not crucial. Power consumption isn't an issue here, but making it black opens up adding something else and making it stand out ;)

Since it seems like we're finally in agreement over #638, how about make the background for both the bootloader and the splash screen black, and add a  box underneath Eddie (push him up if needed) - maybe with a white outline and that blue colour to fill it, which shows the current version (or commit hash if it's not a tagged release)? Which then closes off this issue and #638.

**Comment by philmoz** [comment]
> Any particular reason the images are like twice actual size? Just it's making things distorted 👀

Screen capture on retina display (iMac Pro).

**Comment by philmoz** [comment]
Applying a bit of color theory - the average color of the logo is a light blue:
![Screenshot 2023-09-29 at 7 17 46 pm](https://github.com/EdgeTX/edgetx/assets/9474356/c7c0da8c-cf09-4d85-ac1a-2aa1859ec60a)

So applied a complementary muted orange as the background (looks better on the radio than the screenshot):
![Screenshot 2023-09-29 at 5 25 40 pm](https://github.com/EdgeTX/edgetx/assets/9474356/91c1497f-84ed-41d7-b0e7-96fd49f46fba)

**Comment by pfeerick** [comment]
That I can understand... my only gripe there is that's not one of the colours we use anywhere else 🤣 But I'll leave the final decision on that in Roberts hands.

**Comment by JimB40** [comment]
Black

**Comment by pfeerick** [comment]
I bumped into this the other day ... `#000000`
```
`#000000`
```

**Comment by JimB40** [comment]
.. or blue? 
I really can't decide... feeling blue today ;)

**Comment by JimB40** [comment]
![etx210-splash-black](https://github.com/EdgeTX/edgetx/assets/46420768/451b29a8-ba52-4733-99be-2e67cf0b79eb)
![etx210-splash-blue](https://github.com/EdgeTX/edgetx/assets/46420768/c9c7da15-64f5-4a7e-b8f7-d403de37e544)

**Comment by pfeerick** [comment]
Black overall seems better, but blue does make the logo stand out a bit
better. Pick one! We could also do a different colour for each major
version? 🤷

**Comment by JimB40** [comment]
Black then.
Second later full-colorful UI appears

Black: 
is classy - you can take radio to dinner with your spouse
makes slimer - perfect for a fat boy as TX16S
preserves battery - for 3 seconds only... but we can say later "carbon footprint matters".

last but not least today is Friday and the best Friday is Black

**Comment by philmoz** [comment]
Putting the version and codename under the logo requires reducing the size of the logo.
Do you really want to do that?

If so, can you provide resized logo image.

**Comment by philmoz** [comment]
There is room to the left and right of the current logo for the version and codename on landscape layout.

**Comment by philmoz** [comment]
![Screenshot 2023-09-29 at 10 04 30 pm](https://github.com/EdgeTX/edgetx/assets/9474356/6838042f-7856-4f1e-a22b-ede5862eabde)

**Comment by pfeerick** [comment]
That's better. Make use of the unused space on horizontal format. It can be
under on the portrait layout.

**Comment by philmoz** [comment]
Do we want to remove the background from the boot loader as well?

**Comment by pfeerick** [comment]
Yes please, unless Robert can give a reason it should stay ;) IMO it the background just makes it harder to read.

**Comment by JimB40** [comment]
> Putting the version and codename under the logo requires reducing the size of the logo. Do you really want to do that?

Yes .  It's about composition I've been practicing for over 15 yeras as photographer :)

> If so, can you provide resized logo image.

![EdgeTX_SplashLogo_Color](https://github.com/EdgeTX/edgetx/assets/46420768/a92d36cb-f8bc-4a75-9ccf-257faff05be4)

Here is Splash Logo. 
- size 210x200
- it has black stroke so if we ever use different background color it will have nice separation
- EdgeTX logo is placed to right side so exact position of whole image is:  x=130, y=15

Text lines are CENTERED
- version: font=SMLSIZE, y=218, color=0xFFFFF
- codename: font=NORMAL (capitalized), y=236, color=0x808080 (you may try also SECONDARY1)

**Comment by JimB40** [comment]
An if you are able to code this 'magic' it would be very helpful in every-day testing, and providing support

1. Release version - we display codename for end-users (if this is RC we add this info)
![etx210-splash-release](https://github.com/EdgeTX/edgetx/assets/46420768/ad1bd24d-a2db-4798-8894-d19ff26a90c4)
![etx210-splash-release-candidate](https://github.com/EdgeTX/edgetx/assets/46420768/13d52576-f241-4abf-8a20-098a8c9caf55)

2. Nighly - we display date (there is only one nighly every day)
![etx210-splash-nighly](https://github.com/EdgeTX/edgetx/assets/46420768/cb64d154-c4ae-4c4c-8554-87e5517d1f69)


3. PR - we display PR number and build ID, so it's easy to find it in GitHub and be sure we test right version.
![etx210-splash-PR](https://github.com/EdgeTX/edgetx/assets/46420768/99fa04bf-3f9d-465a-8c40-579f267818aa)

**Comment by philmoz** [comment]
I don't like the small logo on portrait screen.
This is a splash screen not a competition photograph entry - I think it is better to keep the large logo and use the space on the sides as Peter said.

**Comment by JimB40** [comment]
It not about photography but composition and providing future proof space for data.
Finishing packing myself for the race day as we leave at 6am
If you need anything else GFX-wise I'll be back tomorrow.

**Comment by philmoz** [comment]
> * version: font=SMLSIZE

One of the future changes will be to move the fonts to SD storage to free up FLASH space and, hopefully, have all tanslations in one build. 

So only the STD font will be available for the splash screen (also no BOLD font available).
