### ISSUE TITLE
Widget Settings Include display of Widget Name

### ISSUE THREAD

**Issue by kdmurray1982** [EdgeTX/edgetx#4183]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When a widget is already placed on the screen it is not always easy to remember which widget it is by name.  Select widget brings up the complete list and there isn’t a flag symbol of any kind to indicate which widget it is. Nor is there any help in the Widgets settings.

### Describe the solution you'd like

Recommend Widget settings dialog pop-up window include the widget name (either in the window title bar or at the top of the options list).  

### Describe alternatives you've considered

1. In the Select widget pop-up list, if a widget is already configured, have it sorted to the top of the list for easy access so it can be identified by name.

**Comment by offer-shmuely** [comment]
Good idea!
