### ISSUE TITLE
cursor rectangles border markers difficult to recognize

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#419]
TX16S Vers. 2.4.0 / 052f605

i have difficulty seeing the input field on the airfield. when I edit modelsettings. it's this thin blue frame.
Yes, the left field is highlighted in dark blue, but if there are several options through switch positions e.g. I often cannot find the frame in the sunlight and edit the wrong line.
An inversion would be clearer than a line mark.
Many Thanks

**Comment by JimB40** [comment]
Solved with custom themes
