### ISSUE TITLE
Touch is accepted with the backlight off

### ISSUE THREAD

**Issue by jmil-dev** [EdgeTX/edgetx#420]
If the backlight is off a touch will turn the backlight on and be registered as an interaction with the UI.

Since the current touch screens are unreadable with the backlight off there is no way to know what you have touched.

Ideally a touch is required to turn the backlight on and then a second touch is needed to interact with the UI

**Comment by gagarinlg** [comment]
My backlight solution can be found here:
[https://github.com/gagarinlg/edgetx]
in the main branch.
It does work on TX16s and should work on NV14, at least it compiles and it is not to many changes.
Compilation for non color lcd/non touch radios is also OK.
If this is an acceptable solution, I would create a pull request from it.

**Comment by MervDale** [comment]
Please don't take this as criticism but it seems to me that there would be more pressing issues that would benefit from programmers time.

To me that this does not seem to be a major issue in that I would say that the main concern of having the back light off is to conserve battery power when flying and reactivating it without affecting the touch screen. 

This can all be done with the current OTX options as I see it. Please correct me f I am wrong.

I have mine set to 50 sec to off and back on to half power "approx" with keys so just a roll of the wheel on the TX16S brings it back on with the option of turning it up or down with a GF on S2.

Not being a programmer could you explain how you option works please.

**Comment by gagarinlg** [comment]
Feel free to say what you think. I very mich prefer an open discussion. As for the reasoning:
1. it is a hobby, not a job, so I decide what I do with my time 😜
2. I just started participating in this project, so I selected an issue with little to no impact on the real rc stuff, to get to know the software internals. 
I do dim my backlight faster, but that is a personal preference. 
The main concern is, that e. g. on the NV14, there is no way to activate the backlight without creating an input event, as there are no buttons.
When you are in certain lighting conditions it can be very hard to discern what is on your screen and then it is helpful to not create an input event.

**Comment by MervDale** [comment]
By all means go for it, I have no issues with your option. I was just thinking out aloud,  it seems Australian English doesn't  convey the same thoughts as other versions, my bad.

**Comment by gagarinlg** [comment]
😂 There are a few distinct differences between german and australian English... 
As I said, I like an open discussion. So no offence taken.

**Comment by raphaelcoeffic** [comment]
> Please don't take this as criticism but it seems to me that there would be more pressing issues that would benefit from programmers time.
> 
> To me that this does not seem to be a major issue in that I would say that the main concern of having the back light off is to conserve battery power when flying and reactivating it without affecting the touch screen.
> 
> This can all be done with the current OTX options as I see it. Please correct me f I am wrong.
> 
> I have mine set to 50 sec to off and back on to half power "approx" with keys so just a roll of the wheel on the TX16S brings it back on with the option of turning it up or down with a GF on S2.
> 
> Not being a programmer could you explain how you option works please.

What do you think of what is proposed here: https://github.com/EdgeTX/edgetx/issues/420#issuecomment-954643823 ?

**Comment by gagarinlg** [comment]
> What do you think of what is proposed here: #420 (comment) ?
If I am right, this is essentially, what is there now, except for being able to set the backlight timeout to 0, which, in combination with setting the dimmed brightness to 0 leads to an unusable state.
So I will change the minimum backlight timeout to 5.
Also I will try to disable unused control elements, so when backlight is set to be always on, everxthing but the on brightness control element will be disabled.
