### ISSUE TITLE
Internal GPS not available

### ISSUE THREAD

**Issue by stefaanbolle** [EdgeTX/edgetx#421]
**Describe the bug**
I modified my TX16S Radio with an Internal GPS (BN-220) on AUX2. In openTX 2.3.13 this works and displays correct values with the 3djc GPS test script. (had to enable internalgps when selecting firmware)
With EdgeTX the 3djc GPS test script, the widget remains blank. Or there is a problem with the script in EdgeTX or with internal GPS (I did not find a possibility to enable this in the firmware or downlaod a fw with internalgps enabled)

**To Reproduce**
create a widget using the 3djc GPS test script

**Expected behavior**
The 3djc GPS test script should reveal internal GPS info

** Info **
 - EdgeTX version (e.g. 2.4.0 nightly 7f472ff)
 - RM TX16S

**Comment by pfeerick** [comment]
You probably need a build that supports the internal GPS, as you would have had to tick the "Internal GPS" option in the OpenTX companion in order to get a GPS supported build of the OpenTX firmware.

**Comment by rotorman** [comment]
To see if your firmware has internalgps option baked in or not, you can also check under SYSTEM -> VERSION.
The OPTS line should list `internalgps`.

**Comment by pfeerick** [comment]
This is a build of [firmware_7f472ff_TX16S_internalgps.zip](https://github.com/EdgeTX/edgetx/files/6784168/firmware_7f472ff_TX16S_internalgps.zip) #7f472ff with `INTERNAL_GPS=YES` as the nightlies don't have it enabled ... do you want to give that a try and see if it works... for you?

**Comment by stefaanbolle** [comment]
Thanks! will try the pfeerick build and install build environment in a VM

**Comment by stefaanbolle** [comment]
Works like a charm now, thanks!

**Comment by pfeerick** [comment]
Fantastic! If you setup up a docker build environment, you'll find it pretty easy to build your own firmware on demand, if you need specific options (like `internal-gps`, or tweak some of the other settings).
