### ISSUE TITLE
Boxer build error

### ISSUE THREAD

**Issue by kobakirill** [EdgeTX/edgetx#4240]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Error when assembling the firmware. Error there is not enough flash memory. Although Boxer, unlike all STM 32F407, has 1MB of flash. There is a processor in it  STM32F407VGT6 with 1MB Flash and 192KB RAM.

### Expected Behavior

Firmware build up to 1MB

### Steps To Reproduce

For example, to build a firmware with a Russian translation.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster Boxer

### Operating System (OS)

Windows

### Anything else?

![image](https://github.com/EdgeTX/edgetx/assets/39222879/8f39f751-e103-4b49-99dd-7d35b7356ec8)

**Comment by pfeerick** [comment]
Correct. A new linker script is needed for 1MB B&W due to that radio.

**Comment by rotorman** [comment]
I just saw this Issue, related to https://github.com/EdgeTX/edgetx/issues/4243
