### ISSUE TITLE
Delay doesn't work in interaction with Flight Modes

### ISSUE THREAD

**Issue by sande005** [EdgeTX/edgetx#4254]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When Delay is set on any mixer line, if any Flight Mode is unchecked, Delay won't work, no matter what the currently active Flight Mode actually is.

### Expected Behavior

Delay should work kor any assigned flight mode, even if not assigned for all flight modes.

### Steps To Reproduce

In this example, CH1 responds to a change in the source value two seconds after that value changes, as expected. But CH2, which is the same as CH1 except that it has one or more flight modes excluded, ignores the Delay setting and changes immediately.

Code:
```
CH1     SF Weight(+100%) Delay(u2:d2)

CH2     SF Weight(+100%) Flight modes(FM0:FM0, FM2:FM2, FM3:FM3, FM4:FM4, FM5:FM5, FM6:FM6, FM7:FM7, FM8:FM8) Delay(u2:d2)
```

### Version

2.9.1

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### Anything else?

This is a port over from an OpenTX discussion found starting here:[https://www.rcgroups.com/forums/showpost.php?p=51655957&postcount=10106](https://www.rcgroups.com/forums/showpost.php?p=51655957&postcount=10106)

Confirmed as an issue with Edge here:[https://www.rcgroups.com/forums/showpost.php?p=51658113&postcount=5860](https://www.rcgroups.com/forums/showpost.php?p=51658113&postcount=5860)

Thanks to user MiamiMike for "Steps to Reproduce" clipped from his post on RCGroups.

**Comment by Miami-Mike** [comment]
Links fixed:

This is a port over from an OpenTX discussion found on RCGroups starting [here](https://www.rcgroups.com/forums/showthread.php?p=51655957&postcount=10106).

Confirmed as an issue with EdgeTX [here](https://www.rcgroups.com/forums/showthread.php?p=51657693&postcount=5859).

**Comment by raphaelcoeffic** [comment]
Thx gentlemen for the detailed descriptions and isolation of issue! I’ll look into this ASAP.

**Comment by raphaelcoeffic** [comment]
@sande005 @Miami-Mike we will need a lot of tests on the #4256. Not sure how to proceed from here.

@MikeBland may I kindly ask you for a review? It's really hard to see the intent of the original code...

**Comment by raphaelcoeffic** [comment]
Please note that the same issue occurs if you have *any* switch selected in the same mix line. And yes, even with the `ON` switch.
