### ISSUE TITLE
Font size of LUA settings is set to default set

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#4278]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

With the new edgetx-tx16s-2.10.0-selfbuild (4655c56f), font sizes such as DBLSIZE, MIDSIZE, SMLSIZE are no longer supported.

### Expected Behavior

With v2.9.1 the font size was still OK.

### Steps To Reproduce

With v2.10.0 fonts are set to default

### Version

2.9.1

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by philmoz** [comment]
Large fonts have been moved to the SD card.
Update to the latest SD card content and make sure the FONTS folder is on the SD card.
