### ISSUE TITLE
fr translation

### ISSUE THREAD

**Issue by Pat6874** [EdgeTX/edgetx#4295]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

better translation Fr to fill fields in color screen

### Describe the solution you'd like

#define TR_SELECT_MODEL                "Sélection Modèle"
#define TR_TTL_WARNING                 "Attention: utiliser valeur logique 3.3 V"
#define TR_BATT_CALIB                  "Calib. batterie"
#define TR_ENABLED_FEATURES       TR("Fonctions activées", "Fonctionnalités")
#define TR_STICK_NAMES                 "Dir", "Prof", "Gaz", "Ail"
#define TR_USE_THEME_COLOR              "Utiliser couleur du thème"
#define TR_STACK_MIX                   "Mixeurs: "

**Comment by raphaelcoeffic** [comment]
@Pat6874 please make a PR for this, issues are not really meant for proposed code changes.

**Comment by pfeerick** [comment]
I'll do a PR for this shortly for you Patrick

**Comment by Pat6874** [comment]
Thanks...
Patrick 

Le 10 nov. 2023, 11:51, à 11:51, Peter Feerick ***@***.***> a écrit:

**Comment by pfeerick** [comment]
- `TR_STICK_NAMES`  these are limited to three characters, so no.
- `TR_USE_THEME_COLOR` appears to already have been done. 
- `TR_BATT_CALIB` I had to keep the existing string for smaller screens as they are limited to 11 characters where that is shown.

Sorry for not sorting this out sooner.

**Comment by Pat6874** [comment]
Hello Peter,
Thanks for your reply.

OK for the limitation of 3 caracters. I suggest:
#define TR_STICK_NAMES "Dir", "Prf", "Gaz", "Ail"
Merry Christmas
Patrick



Le dim. 24 déc. 2023 à 02:51, Peter Feerick ***@***.***> a
écrit :
