### ISSUE TITLE
Companion 2.10 - Index column is blank for B&W radios.

### ISSUE THREAD

**Issue by philmoz** [EdgeTX/edgetx#4305]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

The Index column is blank for B&W radios:
![Screenshot 2023-11-11 at 1 46 40 pm](https://github.com/EdgeTX/edgetx/assets/9474356/46014203-86a6-41bc-92eb-cc44a82dc77e)

### Expected Behavior

Should show the model index number.

### Steps To Reproduce

Load a B&W .etx file into Companion 2.10.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky Q X7 / Q X7S (ACCST)

**Comment by ChrisQuadFPV** [comment]
My QX7 Access has 2.9.4 When I update to 2.10.0 the bootloader takes but shows "no SD card"

**Comment by pfeerick** [comment]
> My QX7 Access has 2.9.4 When I update to 2.10.0 the bootloader takes but shows "no SD card" 

Please create a new issue, or search first, because this does not relate to this issue. If you search for sd card, you should find a couple of issues, whereby some slow to initialise off-brand cards which used to work are not working with 2.10.
