### ISSUE TITLE
Horus X12S (nightly). Sound and Lua script text sizing now broken.

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#4323]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Loaded latest Firmware
Sound now echoes from stereo speakers.
My fulscreen widget no longer recognises "value output" digit size coding (SMLSIZE, MIDSIZE, LRGSIZE, XXLSIZE etc.) and defaults to normal size digits on screen.
Have had to return back to 2.9.2
Also when reverting back to this have to reload SD card contents as stick outputs are corrupted.

### Expected Behavior

None of the above

### Steps To Reproduce

Loaded latest nightly

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

**Comment by ParkerEde** [comment]
You have to use FONTS folder of SD card content. This is new.

**Comment by ParkerEde** [comment]
Calibration of current main  is not compatible wirh 2.9.x

**Comment by Kevltan** [comment]
Calibration of current main is not compatible wirh 2.9.x
What does this mean?

**Comment by ParkerEde** [comment]
The calibration of the main is not backwards compatible

**Comment by pfeerick** [comment]
In the latest version of the SD card pack.

**Comment by Kevltan** [comment]
A link please for nightly SD contents?

**Comment by ParkerEde** [comment]
https://github.com/EdgeTX/edgetx-sdcard/releases

**Comment by Kevltan** [comment]
Yep that works thanks
