### ISSUE TITLE
Horus X12S echo/reverb on sound after loading nightly.

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#4325]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There is now an echo (reverberation) on the sound system of my X12S having loaded the latest nightly. The sound is like it's in a big auditorium, there's probably a few milliseconds of delay between stereo channels. It does not do this in the 2.9.2 firmware.
 I loaded a nightly about 2 months ago, and the issue was there then, but due to other issues and commitments, I returned back to 2.9.0 firmware. I was hoping that someone else would've spotted this, and it would be ok the next time I loaded a nightly, but it seems unresolved and has gone under the radar.
My TX16S does NOT exhibit the same problem on latest nightly firmware.

### Expected Behaviour 

No echo/reverb (Horus has stereo capabilities), so there may be a delay of a few milliseconds between the stereo channels.

### Steps To Reproduce

 When a sound is called.

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### Anything else?

latest nightly

**Comment by pfeerick** [comment]
@raphaelcoeffic Maybe https://github.com/EdgeTX/edgetx/pull/3957 is responsible?

**Comment by Kevltan** [comment]
Anybody had a chance to look at this problem please??

**Comment by richardclli** [comment]
Let me do a test to see if I can repeat the problem, I got a X12S.

**Comment by richardclli** [comment]
I got your point, it seems the sound effect is quite different between these 2 versions.  I checked the source code, the audio driver didn't changed between these 2 versions, so......

**Comment by richardclli** [comment]
This is the 2.9 sound
https://github.com/EdgeTX/edgetx/assets/18414861/cef3fd61-2950-40bc-b1f2-427a47e34715

This is the 2.10 sound
https://github.com/EdgeTX/edgetx/assets/18414861/d269bb61-23d6-48e5-946b-51e3f86cd34e

**Comment by richardclli** [comment]
I check the source code and the change is to merge the horus audio driver with nv14 audio driver and in which both uses the same audio chip.

**Comment by Kevltan** [comment]
Sounds good, please let me know how you get on and if it resolves the issue.

**Comment by Kevltan** [comment]
Has anybody had any luck yet with resolving this problem with the sound on the X12S ??

**Comment by richardclli** [comment]
No luck, the new driver didn't changed much.  And both X12S and EL18 uses the same driver, but didn't spot any problem in EL18.

**Comment by Kevltan** [comment]
Does the EL18 have stereo capabilities like the X12S?

**Comment by Kevltan** [comment]
Looks like a mono speaker output on the back of the EL18. There are 2
independently driven stereo speakers on the X12S which is where I think the
problem is caused. I think there is posdibly a delay in sound between the 2
channels.

**Comment by richardclli** [comment]
I do not have the schematic of X12S, it is hard to tell what would be the differences.  But the driver didn't change anything special, maybe I will see if I can revert the old driver for X12S build to see if there are any differences.  Do you know how to build a firmware from a branch?

**Comment by pfeerick** [comment]
Don't know if this helps you at all @richardclli 
https://github.com/opentx/opentx/issues/8054#issuecomment-717622677

There is also some PCBX12S specific code in the vs1053b driver file. I would be curious to know if we can pin down #3957 as being responsible for this change... as then at least we'd know there to start.

**Comment by raphaelcoeffic** [comment]
> This is the 2.9 sound https://github.com/EdgeTX/edgetx/assets/18414861/cef3fd61-2950-40bc-b1f2-427a47e34715
> 
> This is the 2.10 sound https://github.com/EdgeTX/edgetx/assets/18414861/d269bb61-23d6-48e5-946b-51e3f86cd34e

Am I the only one to not hear any difference between the two?

**Comment by 3djc** [comment]
> > This is the 2.9 sound https://github.com/EdgeTX/edgetx/assets/18414861/cef3fd61-2950-40bc-b1f2-427a47e34715
> > This is the 2.10 sound https://github.com/EdgeTX/edgetx/assets/18414861/d269bb61-23d6-48e5-946b-51e3f86cd34e
> 
> Am I the only one to not hear any difference between the two?

You are not the only one

**Comment by Kevltan** [comment]
Only on the X12S does issue exist. Sounds like the radio has been put and a
large biscuit tin!!

**Comment by richardclli** [comment]
> > This is the 2.9 sound https://github.com/EdgeTX/edgetx/assets/18414861/cef3fd61-2950-40bc-b1f2-427a47e34715
> > 
> > This is the 2.10 sound https://github.com/EdgeTX/edgetx/assets/18414861/d269bb61-23d6-48e5-946b-51e3f86cd34e
> 
> Am I the only one to not hear any difference between the two?

Yes, no differences in these 2 samples.  The "echo" effect only present in my first flash, but not recorded.  May try to test again this weekend.

**Comment by richardclli** [comment]
I have made a branch with old audio driver, please see if this resolves the problem first so that we can see if we can figure out what cause the problem mentioned.

https://github.com/EdgeTX/edgetx/tree/x12s-old-audiodrv

**Comment by richardclli** [comment]
I spot the softReset code is different for nv14 and x12s target and the new driver did not follow either nv14 nor x12s, not sure if this maybe the cause.

**Comment by Kevltan** [comment]
There doesn't seem to be an option of a bin file download to test the firmware branch - or am I doing something wrong here?

**Comment by pfeerick** [comment]
> There doesn't seem to be an option of a bin file download to test the firmware branch - or am I doing something wrong here?

Since it is a branch, rather than a PR, you  would either need to use gitpod to build it, or wait for someone to build it for you.

**Comment by Kevltan** [comment]
How do I carry this branch across to the GitHub ready to code environment so that I can build this branch? Or do I have to carry across the edits/changes to the environment and then build?

**Comment by pfeerick** [comment]
From the wiki instructions:
> To start building EdgeTX firmware for your radio, open the following link with the web browser of your choice:
> https://gitpod.io/#https://github.com/edgetx/edgetx/tree/main

notice the end of the url says `/tree/main`? Try changing that to `/tree/x12s-old-audiodrv` ;)

**Comment by richardclli** [comment]
I think the driver in 2.9 and main intentionally init the audio chip with minimal spatial effect (SM_EARSPEAKER_LO), however maybe the old driver in 2.9 somewhat failed to init the audio chip in this mode and the new driver in main will ensure the init is done.

**Comment by Kevltan** [comment]
Yep!! the above works just remove 
         | SM_EARSPEAKER_LO 
from the driver and build.....
It works all spatial effect now gone! 😊👍👍

**Comment by richardclli** [comment]
Cahnge in line 54 is not necessary.

**Comment by Kevltan** [comment]
Just did it to reduce binary size a tiny bit if not used.

**Comment by richardclli** [comment]
#define will not affect binary size anyway, the compiler just did string replacement in the source file before compilation.

**Comment by Kevltan** [comment]
Ok thanks for letting me know that and thanks for all your help😊👍

**Comment by raphaelcoeffic** [comment]
Ok, so bottom line is: we should remove `SM_EARSPEAKER_LO` from the init code? Assuming that it was actually never in effect with the X12 as the first init failed somehow and was never retried?

**Comment by Kevltan** [comment]
Edit works fine with my X12S and resolves the "spatial reverb" effect and
makes the sounds "clean" again as in 2.9.2. So from me it is a YES.👍
