### ISSUE TITLE
Telemetry sensors lost when switching from ETX 2.8.5 FR to ETX 2.9.2 FR

### ISSUE THREAD

**Issue by LS-67** [EdgeTX/edgetx#4349]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On an electric glider model equipped with a FrSky G-RX8  :

With ETX 2.8.5 FR : all telemetry sensors  work correctly (RSSI, TRSS, TQly, RxBt, Vspd, Alt, A2)

After  installing ETX 2.9.2 FR :  only the TRSS and TQly sensors exist and work : The other sensors are lost...

(in both cases with MPM  1.3.3.33)

### Expected Behavior

By installing ETX 2.9.2 FR, all sensors should be retained and working properly

### Steps To Reproduce

1- With ETX 2.8.5, create a model with FrSky G-RX8
2- Discover telemetry sensors
3- Install ETX 2.9.2 and open the telemetry page 
4-Look at telemetry sensors

### Version

2.9.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

10

**Comment by koaxheli** [comment]
Hello,
Delete and re-insert the sensors and all sensors should be found again.

**Comment by LS-67** [comment]
Thank's but 20 models affected, some with vario, GPS and ESC telemetry and all SF to be reprogrammed ? t's not cool...

**Comment by pfeerick** [comment]
Can you backup a model, do sensor rediscovery on it (let us know if it does indeed work), and upload the model yml for both the old and the new state, so we can see what is changing?

**Comment by LS-67** [comment]
[Alpina.zip](https://github.com/EdgeTX/edgetx/files/13455446/Alpina.zip)
Hello,
Here it is :
Alpina v1 : model version ETX 2.8.5
Alpina v2 : model version ETX 2.9.2 (before having rediscovered the sensors)
Alpina v3 : model version ETX 2.9.2 (after having rediscovered the sensors)

**Comment by raphaelcoeffic** [comment]
Just use the `ignore instance` option on these models. No sensor re-discovery needed.

**Comment by raphaelcoeffic** [comment]
This issue has already been discussed here: https://github.com/EdgeTX/edgetx/issues/4044#issuecomment-1719373614

**Comment by LS-67** [comment]
OK, Thank's !
