### ISSUE TITLE
Some Mixes no longer work in v2.9.2

### ISSUE THREAD

**Issue by claudevandaele** [EdgeTX/edgetx#4361]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When updating from v2.9.1 to v2.9.2, I notice that several mixes no longer fully work under v2.9.2. . I have a rescue mode that skips a line and a spinfix mix that no longer works.
When reinstalling back to 9.1, everything works normally again. Anyone else having such problems? 

           
![Logical switch](https://github.com/EdgeTX/edgetx/assets/98773531/9d146665-ca47-434c-8413-2fe61b341004)
                                                                                                                                                                                 

![Rescue mix](https://github.com/EdgeTX/edgetx/assets/98773531/70414cea-ee56-44c1-94d7-63697055618f)

![spinfix](https://github.com/EdgeTX/edgetx/assets/98773531/e1031a96-4e35-4adf-9759-485dd39214b1)

### Expected Behavior

Mixes work in v.2.9.1 not in v.2.9.2 !

### Steps To Reproduce

1. Switch SH
2. R0 L04 R0 active (9.1) -> 9.2 not working
3. R1 L05 R1 active
4. ....

1.Switch SG or SF activate SpinFix (9.1) -> 9.2 not working 

### Version

2.9.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by philmoz** [comment]
Please upload a copy of the affected model file and your radio.yml file.

**Comment by claudevandaele** [comment]
[MODELS.zip](https://github.com/EdgeTX/edgetx/files/13466920/MODELS.zip)

**Comment by claudevandaele** [comment]
Model and Radio file in comment.

**Comment by claudevandaele** [comment]
Solution in v.2.9.3 ?

**Comment by philmoz** [comment]
> Solution in v.2.9.3 ?

Hopefully. The PR needs to be reviewed and tested.

**Comment by claudevandaele** [comment]
Thanks for the reply, and maybe a quick solution. Grz. Claude

**Comment by ParkerEde** [comment]
I've tested the PR. It's okay.
