### ISSUE TITLE
[TX12 MKII] Power on no longer works

### ISSUE THREAD

**Issue by Nels885** [EdgeTX/edgetx#4377]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After updating with the latest version Nightly 5153aaee my radiomaster TX12 MKII no longer turns on.
Power button and LCD screen remain off.

### Expected Behavior

The power button lights up in blue and the EdgeTX logo appears on the LCD screen.

### Steps To Reproduce

1. Radiomaster TX12 MKII updated with Nightly version 5153aaee
2. Disconnecting USB cable
3. Press the power button

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2

### Operating System (OS)

Windows

### OS Version

Windows 10

**Comment by pfeerick** [comment]
Can confirm... and that it works with e18a2a90a4c16f666ebc30f84c04c471f75b573c, so is related to #3846
