### ISSUE TITLE
Model name without bmp

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#438]
Tx16s
Rc3
Cant have model name without bmp.
Is it possible to allow model name in a small box widget as I rarely use the bmp images. I have to select a large box to have the model name which takes up a lot of real estate if not displaying an image.

**Comment by pfeerick** [comment]
I'll have to look at the widget to find out, but in principle I don't see why it couldn't 
1) be renamed and have an options like:
show name [ ] 
show model img [ ]
2) Another widget added to show the name. Should be a piece of cake for @lshems to whip a lua one up in ... 10 seconds... just needs to read the model name and show it! :-P
