### ISSUE TITLE
Widgets to reflect box size

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#439]
Tx16s
Rc3
If I put image in a small box nothing is displayed. Not even model name. Also if I put the timer in a larger box it is still the same size as in a smaller box, be nice to have a larger timer so I can see it better at a glance
Same applies to other widgets

**Comment by raphaelcoeffic** [comment]
Some built-in widgets would need some tweaking, indeed. Could you please make some screenshots of which “small box” you are writing about?

**Comment by pfeerick** [comment]
I'm guessing ModelBmp is the "image" one... and when anything smaller than a 1x2 layout is used, the model name isn't shown, just the model image. Meaning if you don't have an image at all, it will just be a white box. 

i.e. each of the white boxes that follows is a ModelBMP widget that did work, until I deselected the image. 

![image](https://user-images.githubusercontent.com/5500713/125403130-7f2d4580-e3f8-11eb-8a56-f003ad945284.png)
![image](https://user-images.githubusercontent.com/5500713/125403163-8bb19e00-e3f8-11eb-9daf-77e6168342c4.png)
![image](https://user-images.githubusercontent.com/5500713/125403175-92401580-e3f8-11eb-953b-5c200ecc67f8.png)

Timer certainly needs to get bigger. i.e. timer is perfect in a 4x4 and also smaller I think, as it's fine as a top bar widget, but doesn't get any bigger if you have have it in say a 1x2 layout (or the bigger of the 2+1 layout).

**Comment by Mantamatt1** [comment]
Exactly that

**Comment by offer-shmuely** [comment]
The widget **_"Timer2"_** is more aware to to the box area 
so the size is more adptive

https://github.com/EdgeTX/edgetx-sdcard/tree/master/sdcard/horus/WIDGETS/Timer2

**Comment by pfeerick** [comment]
Indeed. I have no immediate plants of making any changes to the built in Timer widget since Timer2 is much better at adapting.

**Comment by offer-shmuely** [comment]
I think that the best plan should be to move all(!) the widgets to LUA, (thing that currently still cannot be done)
this way the LUA API will match more rich, and the widget will be more customizable

**Comment by pfeerick** [comment]
There will probably always be a few widgets (basically just the ones that exist now) that will be baked into the firmware, but no major changes to them as Lua can generally do a better job or be more flexible in allowing changes to be made. I think there are just one or two minor modifications needed and then I think they will probably remain as they are. I reserve the right to be proven entirely wrong as there are some major GUI backend rework efforts afoot! 😁

**Comment by offer-shmuely** [comment]
We have a larger timer, 
So can this be closed?

**Comment by pfeerick** [comment]
I think so - as I mentioned before I have no intentions of altering the built in timer, and no-one else has stepped up to do so. Plus, Timer2 is a perfectly valid alternative if you want a larger timer, especially since Lua widgets can override built-in ones if given the same name ;)
