### ISSUE TITLE
Loss of Chinese characters

### ISSUE THREAD

**Issue by norulers** [EdgeTX/edgetx#441]
![20210713100236](https://user-images.githubusercontent.com/5206964/125379199-aec15b00-e3c2-11eb-8671-bb68c8eda102.jpg)
![20210713101006](https://user-images.githubusercontent.com/5206964/125379204-aff28800-e3c2-11eb-83cb-2a6e4190406c.png)

**General information**
 - EdgeTX version (2.4.0 RC4)
 - Hardware (T18)

**Comment by raphaelcoeffic** [comment]
This quite unfortunate, but the biggest fonts do not include the localized characters. This is more or less on purpose to avoid blowing the flash memory up. The best fix would be to use a smaller font.

**Comment by MervDale** [comment]
Would not blowing up the flash memory be also an issue of the huge number of characters need in some languages even despite using a smaller font?

**Comment by raphaelcoeffic** [comment]
> Would not blowing up the flash memory be also an issue of the huge number of characters need in some languages even despite using a smaller font?

ATM, only the characters used in translations are included in the font, thus massively reducing the size of the fonts. But there are still quite a few left.

**Comment by richardclli** [comment]
> 
> 
> This is quite unfortunate, but the biggest fonts do not include the localized characters. This is more or less on purpose to avoid blowing the flash memory up. The best fix would be to use a smaller font.

But if you only include those characters that is required in big font, then it will not blow up memory.  I think in general,  both translations size should be used to select what characters are required and included during build.  I think this will works.

**Comment by raphaelcoeffic** [comment]
> > This is quite unfortunate, but the biggest fonts do not include the localized characters. This is more or less on purpose to avoid blowing the flash memory up. The best fix would be to use a smaller font.
> 
> But if you only include those characters that is required in big font, then it will not blow up memory. I think in general, both translations size should be used to select what characters are required and included during build. I think this will works.

We cannot afford to have a mapping that depends on font size, really, nor can we safely detect which characters are used in which font size.

**Comment by richardclli** [comment]
Or can we make use of images instead.

**Comment by richardclli** [comment]
Chinese problems:
- character missing, wrong encoding, etc.

Will work on a fix.

**Comment by gagarinlg** [comment]
@richardclli is this still a problem in the current nightlies?
