### ISSUE TITLE
Incorrect name of 6-position switch in Russian translation

### ISSUE THREAD

**Issue by Shouldercannon** [EdgeTX/edgetx#4421]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

In the companion with the Russian language, the 6-position switch has incorrect position names.
![6P](https://github.com/EdgeTX/edgetx/assets/94894541/4ad52bd6-8a6e-4aa8-9152-c4e7c23d9991)

### Expected Behavior

In the companion with English, the 6-position switch has the correct position names.
![6P en](https://github.com/EdgeTX/edgetx/assets/94894541/f0528a27-25f9-4d37-9f0e-5e17f1418fd7)

### Steps To Reproduce

![Untitled-3](https://github.com/EdgeTX/edgetx/assets/94894541/42a98577-86ab-4280-836d-b24f416b2bd1)

### Version

2.9.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Win10 x64 22H2

**Comment by kobakirill** [comment]
Fix 6p.
 https://github.com/EdgeTX/edgetx/pull/4451

**Comment by Shouldercannon** [comment]
The translation problem has not been resolved. Now it is in version 2.9.3.

**Comment by pfeerick** [comment]
The fix is in 2.10, not 2.9.3. I can add it to the 2.9 branch though, and it will be present in 2.9.4 if there is a future release.
