### ISSUE TITLE
Issues after remapping Hardware Switches

### ISSUE THREAD

**Issue by mrac1** [EdgeTX/edgetx#4422]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After remapping the Switches SH <-> SF (SH is now 2-Way and SF is now Toggle), the Preflight Checks Switches are displayed incorrectly. SF = 0 and SH is without flags until you exit and re-enter the menu. Then SH is correct but SF remains at 0. From time to time, switching to the Preflight Checks menu also causes crashes with Emergency Reboot.

### Expected Behavior

SF = SF with Flags + SH = SH with Flags

### Steps To Reproduce

Swap Switch SH and SF in the Hardware Menu, goto Preflight Checks.

### Version

2.9.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

-

**Comment by wombats-kode** [comment]
I have a related issue where I have also swapped SH to a two position toggle that I use to arm/disarm all models.  Preflight check does not permit high/low flags selection on SH switch, only option is high which in my case is 'armed' so I have to disable completely.  Would be great to have ability to select SH(low) to prevent inadvertant arming when changing model.  Thank you

**Comment by 3djc** [comment]
Not sure I understand the issue. if you swap switches, there is no way for the radio setup to adapt itself. You need to first change your switch settings in hardware screen to match the new physical implementation, you need then to check your model  settings to take into account those changes, this is to be expected. In your case, preflight checks need to be redefined to match hardware. Tested on 2.10, cannot find an issue with it

**Comment by wombats-kode** [comment]
I have remapped the hardware to account for the change of switch role, I guess that is why I am having an issue as it knows it is now a two position switch but preflight checks only allows me to select one position to display a warning. The other option is no warning.  Just so happens I would prefer to set the warning for the other switch position.  This is on v2.9.2.

**Comment by 3djc** [comment]
I'm sorry but this is inaccurate:

Photo taken with 2.9.2

![image](https://github.com/EdgeTX/edgetx/assets/5167938/46228e8f-6942-4909-b0a2-43c4400e2c56)

![image](https://github.com/EdgeTX/edgetx/assets/5167938/0f136872-6491-4f77-be8a-ac91698eec78)

![image](https://github.com/EdgeTX/edgetx/assets/5167938/5470a18b-4362-4bdd-a90a-a05954cb1368)

**Comment by mrac1** [comment]
Set SF to Toggle an the issue appears. You can also trace the error in the Companion.
![preflight](https://github.com/EdgeTX/edgetx/assets/34960764/5cc3c6e3-465a-4b2a-a4ef-23e7c6fb3bd3)
![SF_Toggle](https://github.com/EdgeTX/edgetx/assets/34960764/58dab71b-5045-4670-a698-cdf1e6c471bc)

**Comment by 3djc** [comment]
I was responding to [wombats-kode](https://github.com/wombats-kode)

As far as your issue is concerned, I do not understyand what your issue is

**Comment by philmoz** [comment]
> Set SF to Toggle an the issue appears. You can also trace the error in the Companion.

@mrac1 this has been fixed in 2.10.

**Comment by mrac1** [comment]
Perfect, thank you!

**Comment by wombats-kode** [comment]
> I was responding to [wombats-kode](https://github.com/wombats-kode)
> 
> As far as your issue is concerned, I do not understyand what your issue is

@3djc It looks like your version is doing what I need.  I do not get the option of setting two states for SH, I just get the option to set SH(arrow down).  I get no option to set SH(arrow up).  Hardware is set as you indicate in the image and flag debug show the states switching correctly.

I do also get the problem where entering pre-flight checks causes the radio to crash regularly.
