### ISSUE TITLE
GPS poorly displayed on Jumper T20 

### ISSUE THREAD

**Issue by theysp** [EdgeTX/edgetx#4427]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

GPS value in telemetry is not well displayed:
![b812036a4d2d4b1f3a544470ec9ff66](https://github.com/EdgeTX/edgetx/assets/5262537/b6a4dc76-1df8-4d74-b499-52d8c675e3aa)

### Expected Behavior

Bellow is the same GPS value of the same quad now displayed on tx12.
![d3417a54a8e2e0b14404fd7da047917](https://github.com/EdgeTX/edgetx/assets/5262537/e5609806-4fbe-45d7-8b6f-362608e7e68a)

![1a47fdabb833163d27ffb83aa79bbee](https://github.com/EdgeTX/edgetx/assets/5262537/13918eb4-40ee-4542-b5a6-51a549f49ad9)

### Steps To Reproduce

1. connect to quad
2. go to telemetry screen in its model
3. discover new
4. look for GPS row

### Version

Nightly (Please give date/commit below)

### Transmitter

Other (Please specify below)

**Comment by 3djc** [comment]
Have you tried a 2.10 nightly on tx12 ? Because they run the same code

**Comment by theysp** [comment]
> Have you tried a 2.10 nightly on tx12 ? Because they run the same code

Thank you, I would try it on tx12, and go back to you this weekends.

**Comment by theysp** [comment]
> Have you tried a 2.10 nightly on tx12 ? Because they run the same code

Unfortunatly, this nightly build cannot work on my tx12. After flashing, it went dead, cannot respond to interactivity such as pushing buttons or so.

![408381da730def8bbdebd583872470a](https://github.com/EdgeTX/edgetx/assets/5262537/88a4374b-e572-46f7-9199-64fa6439e7ca)

**Comment by 3djc** [comment]
Seems to be working fine here

![image](https://github.com/EdgeTX/edgetx/assets/5167938/4f6f6354-3136-463c-bc87-37b0bf1d341c)

**Comment by theysp** [comment]
I am now using SD cards contents from edgetx 2.9.0 from EdgeTX Buddy.

The previous not working tx12 (not mk2, just tx12) was with 2.4.2 SD card contents. After I tried 2.9.0 SD card contents, it failed to boot with NO SD CARD warning on screen. Where can I get the correct SD card contents for 2.10.0-nightly?

Is the formating of GPS info related to the contents in SD card?

By the way, I got the detailed info of the firmware on t20 as follows:
![6b65c56215464d8cb35e73785241e7f](https://github.com/EdgeTX/edgetx/assets/5262537/def8d2fc-dab1-46c0-949e-e5a21ea328dc)

**Comment by 3djc** [comment]
sd card content is irrelevant, it doesn't affect GPS display in any way. You need a more recent nightly to get rid of the sd card error

**Comment by theysp** [comment]
> sd card content is irrelevant, it doesn't affect GPS display in any way. You need a more recent nightly to get rid of the sd card error

It's ok to leave tx12 where it was. I flashed edgetx 2.9.2 to tx12, the GPS info is displayed well. If nothing has changed since then, the error may be caused by the radio jumper t20 itself.
