### ISSUE TITLE
TX16S: cannot flash MPM anymore (stuck at reset)

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#4430]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When trying to flash external MPM, radio gets stuck at reset

### Expected Behavior

Normal flashing

### Steps To Reproduce

Try to flash MPM

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by swissfreek** [comment]
Tried to flash one with an MT12 a few days ago, same issue.
