### ISSUE TITLE
[X10Express] strong screen flickering

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#4441]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

with the current nightly version for the X10Express I now get a strong screen flickering.

### Expected Behavior

there should no screen flickering

### Steps To Reproduce

1. flash current nightly on X10 Express
2. PowerOn and observ Screen

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### Anything else?

current nightly from today

**Comment by pfeerick** [comment]
Please try https://github.com/EdgeTX/edgetx/pull/4433 or tomorrows nightly.

**Comment by ParkerEde** [comment]
yes, it is okay now. Thx
