### ISSUE TITLE
[MT12] Global sys menu, some items not selectable

### ISSUE THREAD

**Issue by fiechr** [EdgeTX/edgetx#4443]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There seems to be a small bug when trying to disable the "Global Functions" and/or "Trainer" tab globally.

When moving the cursor down it vanishes and pressing enter won't do anything for these two options. When scrolling down further, the cursor reappears and everything works as expected for the rest of the menu again.

I'm using the stock firmware the radio came with and did not update or change it.

### Expected Behavior

These two menu options should be reachable and changeable.

### Steps To Reproduce

Push SYS button,
Go to Radio Setup page/tab,
Scroll down to the mentioned two menu options.

### Version

Other (Please specify below)

### Transmitter

RadioMaster MT12

### Operating System (OS)

Linux

### OS Version

n/a

**Comment by pfeerick** [comment]
I see this also on a nightly build from two days ago.
