### ISSUE TITLE
False triggering of 'activity' resetting backlight and cancelling splash screen.

### ISSUE THREAD

**Issue by philmoz** [EdgeTX/edgetx#4454]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

On my TX16S I occasionally see the splash screen being cancelled early and the backlight randomly coming back on after the inactivity timeout has turned it off.

### Expected Behavior

There splash screen should not close early and the backlight should stay off unless actual user input is detected.

### Steps To Reproduce

Let the backlight inactivity timeout dim the LCD and then wait.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

This appears to be coming from noise on unconnected pots/sliders.

On my TX16S the POTS config popup shows ETX1 - EXT4 as options - all set to NONE.
I do not have any of these installed.

I modified the analog diagnostic page to show all pot/slider values including those set to none and I see noise on the EXT1 and EXT2 lines.
This is probably triggering the false activity detection.

One fix is to ignore pots/sliders set to NONE in the activity check code; but I wonder if we should also stop trying to read the ADC inputs for them as well?

**Comment by pfeerick** [comment]
Sounds good... if they're `NONE` we're not interested in them. Don't know about changing the ADC read behaviour... that partially depends on if multiple inputs are read in a single pass or they are read individually... plus if there is any linkage to UI and ADC there already.
