### ISSUE TITLE
MT12 Trim5 direction

### ISSUE THREAD

**Issue by chofchop** [EdgeTX/edgetx#4460]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Trim 5 of MT12 subtracts when pushed, and adds when pulled.
This is the opposite direction of operation of a typical surface radio.

### Describe the solution you'd like

The surface radio's grip dial (Trim 5 on MT12) should generally be pushed to add and pulled to subtract.

**Comment by 3djc** [comment]
I'll check with RM that they are ok, and do it if that's the case
