### ISSUE TITLE
[MT12]  Can't switch between CHANNELS MONITOR and MIXERS MONITOR

### ISSUE THREAD

**Issue by chofchop** [EdgeTX/edgetx#4467]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

After starting MT12, the display on the mixers monitor screen is incorrect.

https://www.dropbox.com/scl/fi/m8p30or93bgvzw99hqj9j/VID_20231226_201326.mp4?rlkey=6siq120uyq0rmyvnn271tavyf&dl=0

Once, go to the setup screen, it will be displayed correctly.

### Expected Behavior

It should display correctly even after startup.

### Steps To Reproduce

Go to the setup screen.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster MT12

### Anything else?

Firmware : mt12-fbe06b3.bin

**Comment by chofchop** [comment]
The video has been replaced.

https://www.dropbox.com/scl/fi/7tsznhjy40g3v1xtrtbrd/VID_20231226_204925.mp4?rlkey=mdy0kkza0whx4bwlhcvog3kv7&dl=0

**Comment by 3djc** [comment]
Are you talking about « inv » notifications ? Because one time you are in mixer monitor (where they are rightfully not displayed, another in output monitor (where they are)

**Comment by chofchop** [comment]
Sorry, I couldn't distinguish between mixers monitor and channels monitor.

However, is it normal for MT12 to forcibly switch to mixers monitor after startup? X9 Lite (ETX 2.8.1) becomes a channels monitor after startup.

**Comment by 3djc** [comment]
Maybe a 2.10 thing, cannot remember

**Comment by chofchop** [comment]
It seems strange after all.

After startup, it will forcibly switch to mixer monitor, but in this state it will not switch to channel monitor even if press the rotary button.

Once I enter the setup screen and switch to channel monitor, I can use the rotary button to switch between mixer monitor and channel monitor.

**Comment by 3djc** [comment]
Yes the navigation is different in main view than it is when using the shortcut. I'll have a look at the possibility of making the closer, but not sure it will possible
