### ISSUE TITLE
Fatfish F16 Radio Support

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#4484]
Fatfish F16 Radio Support:
- based on horus target
- special function that can switch LCD to video of EdgeTX UI

**Comment by mha1** [comment]
what is a Fatfish F16?

**Comment by pfeerick** [comment]
You'll find out when it's released. 😛

**Comment by mha1** [comment]
![image](https://github.com/EdgeTX/edgetx/assets/5615068/9b6cd89f-83c4-4dc0-9457-08d537d505e9)
