### ISSUE TITLE
Inconsistencies in Color UI - Grouping of elements

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#451]
There are still some inconsistencies in the UI.

For example in the MDL > MODEL SETUP screen timer settings are grouped when using the scroll wheel:
![screen-2021-07-15-183746](https://user-images.githubusercontent.com/485436/125662815-4159f8c5-5b92-47bf-ad81-885b5906d135.jpg)
but in SYS > RADIO SETUP "grouped" variables aren't grouped for example Sound. Grouping this makes the overall UI experience more consistent. Something like this:
![screen-2021-07-15-183738](https://user-images.githubusercontent.com/485436/125663112-cabc4be0-88f9-42c3-a27b-76fba1e224e2.jpg)

Not part of the inconsistencies but also, in SYS > HARDWARE, grouping the items that for example has a name and a dropdown (like the switches), will make scrolling will the wheel so much faster. The TX16S has like 17 of these groups. Something like this:
![screen-2021-07-15-183804](https://user-images.githubusercontent.com/485436/125663465-6c4fcacf-50c5-45f5-b1f0-1527d12e1db6.jpg)

**Comment by pfeerick** [comment]
LVGL has touched all of these areas and more, and these are in most cases these grouped settings are on their own screen, which you access via a button.
