### ISSUE TITLE
colorlcd: Global Variable popup missing

### ISSUE THREAD

**Issue by BompaBert** [EdgeTX/edgetx#4511]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Companion allows to enable Global Variable popup under Flight Modes however the X10S UI does not have that feature.

### Describe the solution you'd like

Add a "popup enable' feature for each GV in the model setup Global Variable page.  Enabled GV's will then briefly popup in the main screen when adjusted / changed. Refer to  Frsky Taranis X9D screenshot.

### Additional context

![popup enabled](https://github.com/EdgeTX/edgetx/assets/152647971/cfa39962-9d66-4c8f-a4b8-88f554c9b6c8)
![X9D screen](https://github.com/EdgeTX/edgetx/assets/152647971/98053db0-1f14-4ad4-952c-fc87a556ab90)
![X10S GV setup](https://github.com/EdgeTX/edgetx/assets/152647971/374e6ae4-0a5b-4ec7-ac3a-f784114fc377)

**Comment by pfeerick** [comment]
This applies to all colorlcd radios, not just the FrSky X10, and appears to also have been never implemented in OTX, so was a B&W feature only. Given the ability to show popups now, I see no reason this couldn't be brought to colorlcd as well.
