### ISSUE TITLE
Checklist not shown when switching model

### ISSUE THREAD

**Issue by stefaanbolle** [EdgeTX/edgetx#452]
Using the latest code, when switching models on TX16S, the txt checklist is not displayed. The text checklist is only being displayed when powering on the radio.

To reproduce, create and copy a text file for two models in the Models folder on the SD.
Power on the radio => checklist for last used model is shown
Change model to other model with checklist => no checklist is displayed

**Comment by pfeerick** [comment]
Will be fixed by #428.
