### ISSUE TITLE
X10 widgets --  GaugeRotary disappears from radio model setup after reading / writing a model in Companion

### ISSUE THREAD

**Issue by BompaBert** [EdgeTX/edgetx#4528]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

From some reason Companion can only handle less characters in the name, than the firmware itself.
An option is to change the Widget Name to lesser characters (1 less), but many users already use it. Offer Smuely requested to open a bug for this issue - Ref: offer-shmuely/edgetx-x10-widgets#13

### Expected Behavior

Reading from and writing models to the radio using Companion without losing the GaugeRotary Widget.

### Steps To Reproduce

1) Create a model with widget GaugeRotary
2) Read model into Companion
3) Write model back into radio.

### Version

2.9.2

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

### OS Version

W10

**Comment by elecpower** [comment]
Confirmed field size 10 in Companion and 12 in firmware.
Also discovered number of top bar zones max 4 Companion and 6 (landscape) & 4 (portrait) firmare
