### ISSUE TITLE
MPM DSM missing switch to deactivate Telemetry

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#4534]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the MPM DSM setting, the option to "deactivate telemetry" is missing in the current main. This option switch is still available in 2.9.2

### Expected Behavior

switch to activate/deactivate telemetry should available as in 2.9.2

### Steps To Reproduce

1. open int. or ext. RF Settings for MPM
2. Choose DSM
3. observe there is no longer the switch "deactivate telemetry

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
You'll have to take that up with the author... it's no accidental. https://github.com/EdgeTX/edgetx/pull/3637

**Comment by 3djc** [comment]
Why do you need it ?

**Comment by ParkerEde** [comment]
okay. I understand. There are many warnings with telemetry "Reception low".
To avoid this warning I thought. But then I can also deactivate the alarms on the sensor side

**Comment by 3djc** [comment]
Simply don't scan the sensors for that model
