### ISSUE TITLE
DSM Telemetry: Add RemoteID/FAA sensors to EdgeTX

### ISSUE THREAD

**Issue by frankiearzu** [EdgeTX/edgetx#4535]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Support for new type of sensor..

Device:
Spektrum SkyID: https://www.horizonhobby.com/product/sky-remote-id-module/SPMA9500.html

The first batch of Spektrum SkyIDs are already out,  SkyID current can send via telemetry the standard GPS data, but also is sending new information. The parts  that we have reverse engineered is FAA-ID and Owner-ID.

### Describe the solution you'd like

Add New Sensor:
RID (Text) Remote ID  --  If we will show only one, probably this will be the most generic

Discarted options:
FAA (Text): The FAA ID of the device  --- Probably too specific for the USA
UASI (Text) Unmanned Aircraft System ID   --- Not very readable/understandable

Same sensor naming can be used once we identify more brands/protocols RemoteID devices.

FYI: Im already started with the coding in EdgeTX

### Additional context

This is what i know so far:
The ID 16/17 is the standard GPS BCD, no data on message 26 (GPS binary).
The first bytes of the new RID frame are I2C_ID (0x27), Instance (00), Status (00,01,02), FrameType

Status:
00, 01: ??  Initializing, ground??
02: Ready

Where FrameType:
00 - First part of OperatorID string and other info
20 - 2nd part of OperatorID+Info string
40- 3rd and Final part of OperatorID string (Ascii, zero terminated)
60- First Part of FAA ID/UAS_ID
80- 2nd part and final of FAA ID/UAS_ID (Ascii, zero terminated)
A0-Device Model Info???

XX and YY are placeholders for the OperatorID, FAA ID
ZZ i think is the serial number of the device (when you register with Spektrum)
(to protect the identify of the innocent :-)

--------- Capturing I2C_ID 27
27 00 02 00 53 53 33 31 30 46 4F ZZ ZZ ZZ ZZ ZZ       ....SS310FOZZZZZ
27 00 02 20 6F 4F 44 53 74 78 41 41 52 2F XX XX       ....oODStxAAR/XX
27 00 02 40 XX XX XX XX XX XX 00 00 00 00 00 00     ....XXXXX... (XX is OperatorID after the /, zero terminated)
27 00 02 60 YY YY YY YY YY YY YY YY YY YY YY YY     YY is FAA ID/UAS_ID in Ascii, first 12 chars
27 00 02 80 YY YY YY YY YY YY YY 00 00 00 00 00     YY is FAA ID/UAS_ID in Ascii, remaining chars, zero terminated)
27 00 02 A0 4B 00 01 00 00 41 39 35 30 30 00 00      ....K...A9500.. (Device Model 9-15, zero terminated)

DEVICE MODEL: A9500

**Comment by f2knpw** [comment]
yes @frankiearzu, I have indeed modified my TX16s so that it can broadcast remoteid.
But:
- it's a french remoteid not the FAA one (although I don't exactly know the difference (if any))
- It's my radio which broadcast the Wifi signal (not the drone). This not allowed by the FAA (I have read all the official discussion and the question has been asked...). In France it is not officially written that broadcasting from ground (by Tx) is forbidden (so it's probably allowed !)

Have a look here to see all the details (open source) : https://hackaday.io/project/192752-variometer-gps-tracker-remoteid-for-rc-glider

**Comment by frankiearzu** [comment]
If we can send an RemoteID from the Plane/Drone, what do you think of the sensor naming?  RID??

**Comment by f2knpw** [comment]
yes why not RiD !

**Comment by frankiearzu** [comment]
New Firmware:  TX16S 2.9.3 + SkyID:  https://github.com/frankiearzu/DSMTools/blob/main/EdgeTx_Firmware/edgetx_2.9.3-SkyId.bin

**Comment by frankiearzu** [comment]
Just cleanup.. i think is not needed. We can display it with a LUA script.
Unless someone request it to be a proper edgetx sensor to write it to Telemetry logs or display somwerhere, will hold on checking in this.
