### ISSUE TITLE
Taranis Qx7 crash when set input offset to high positive value

### ISSUE THREAD

**Issue by GalacticGreg** [EdgeTX/edgetx#4544]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

If I edit an input, (test with AIL to see this) and change the offset in the positive direction, once I get to about 60, the transmitter crashes and reboots.

### Expected Behavior

I can set the offset without crashing.

### Steps To Reproduce

See above.

### Version

2.9.2

### Transmitter

FrSky Q X7 / Q X7S (ACCST)

### Operating System (OS)

Windows

**Comment by 3djc** [comment]
Confirmed

**Comment by philmoz** [comment]
In drawFunction make this change (in addition to your changes):

```c
  for (int xv = -CURVE_SIDE_WIDTH; xv <= CURVE_SIDE_WIDTH; xv++) {
    coord_t yv = -(fn((xv * RESX) / CURVE_SIDE_WIDTH) * (CURVE_SIDE_WIDTH*2+1) / (RESX*2));
    if (yv < -CURVE_SIDE_WIDTH) yv = -CURVE_SIDE_WIDTH;     <<---- add this line
    if (yv > CURVE_SIDE_WIDTH) yv = CURVE_SIDE_WIDTH;        <<---- add this line
    if ((xv > -CURVE_SIDE_WIDTH) && (abs((int8_t)yv-prev_yv) > 1)) {
      int len = 0;
      if (yv > prev_yv) {
```

I was going to add to your PR; but SourceTree is misbehaving at the moment.

**Comment by 3djc** [comment]
Well, that produces a probably unwanted horizontal line

![image](https://github.com/EdgeTX/edgetx/assets/5167938/ca4e7e55-80ad-45fb-bd31-bbb38f9e0e6b)

How about:

`  for (int xv = -CURVE_SIDE_WIDTH; xv <= CURVE_SIDE_WIDTH; xv++) {
    coord_t yv = -(fn((xv * RESX) / CURVE_SIDE_WIDTH) * (CURVE_SIDE_WIDTH*2+1) / (RESX*2));
    if (yv < -CURVE_SIDE_WIDTH || yv > CURVE_SIDE_WIDTH) continue;
    if ((xv > -CURVE_SIDE_WIDTH) && (abs((int8_t)yv-prev_yv) > 1)) {`

**Comment by philmoz** [comment]
> Well, that produces a probably unwanted horizontal line (unsure, maybe we want the line)

The fix I posted now matches the color LCD curve display.

**Comment by 3djc** [comment]
matching is good, lets do that then !

**Comment by GalacticGreg** [comment]
Thanks for looking into this. Can this be closed?

**Comment by 3djc** [comment]
It  will be done automagically when PR gets merged
