### ISSUE TITLE
Trimmer settings differ FM0 FM1

### ISSUE THREAD

**Issue by mrperno** [EdgeTX/edgetx#4570]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Different trim settings in different FM. FM0 and FM1 differ from the rest. 2.9.3 and dayly 2.10,0

### Expected Behavior

Same parameter in all FM

### Steps To Reproduce

Will show up during model setup

### Version

2.9.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

![IMG_4522](https://github.com/EdgeTX/edgetx/assets/44539810/c66a2b9b-eedf-42e9-9af6-796a92b3adf0)
![IMG_4523](https://github.com/EdgeTX/edgetx/assets/44539810/51cae50b-1b80-41e6-aa62-b91fcb492ce2)

**Comment by 3djc** [comment]
FM0 is different by design as some of the options that exist for other FM are based on FM0, where FM0 doesn't have another FM to base on

**Comment by pfeerick** [comment]
This is not a big or a mistake, but by design. As JC said, FM0 **is** different. It is the base/default FM from which all the other FMs derive from.
