### ISSUE TITLE
Frsky SRx series receivers Stab setup LUA script does not cover the second group of stabilized channels in ACCESS mode

### ISSUE THREAD

**Issue by BompaBert** [EdgeTX/edgetx#4574]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Frsky added a second group of stabilized channels in ACCESS mode as from firmware version v1.0.5. So far, the latest LUA stab setup script does not let us set, enable or disable the second group of channels what potentially turns those channels unusable - the stab function for those channels is enabled by default.

### Describe the solution you'd like

Update the LUA script so it allows to control the second group of stabilized channels. The Ethos LUA script has another page that allows you to do just that.

### Additional context

LUA script version v2.04 and SR10+ firmware version v1.-.10       https://www.frsky-rc.com/archer-plus-sr10/

**Comment by pfeerick** [comment]
You need to contact FrSky if they have added new features to the RX firmware, but not updated their Lua scripts to suit. This is not something EdgeTX can do or fix.

**Comment by BompaBert** [comment]
I believe some in this community did create some great LUA scripts for
Frsky receivers. I was hoping to get their attention. Frsky is focusing on
Ethos - am still waiting for a reply.

**Comment by pfeerick** [comment]
That's why we need Frsky customers to complain (or compliment, where relevant), in order to get them to provide the necessary support... now that I look myself though, it seems like it is missing for the Taranis X9D+2019 also, yet is mentioned in the manual so should have been available as an option right from the start... so I will probably be emailing them about it also 😢. Offer has done a great job of enhancing the SRx Lua scripts provided by FrSky (for colorlcd) in https://github.com/EdgeTX/edgetx-sdcard/pull/113 (included in the 2.9.0 sd card pack onwards) - but depending on what Frsky did this may or may not work with the new capabilities, and may not be (easily) possible to be made to work without knowing what changes they may to the API to support this feature. 

Given it's CH1-6 and then CH7-11, probably "just" needs a second page?

**Comment by BompaBert** [comment]
To my knowledge, any radio not running Ethos wont be able to control the
SRx+ receivers second group of channels.  only the Ethos LUA script covers
the second stabilized group with a second page see also
https://www.youtube.com/watch?v=gzc1VwEPfCE - jump 13.44 mins further to
see both pages.

**Comment by BompaBert** [comment]
@PFeerick, I got it working by adjusting the existing Frsky script (https://www.frsky-rc.com/archer-plus-sr10/). Everything on 1 page. Am glad I can now control everything. Not sure though if there is any infringement by grabbing their LUA and adjusting it.
Any help welcome in educating me as I do not mind publishing the script here.

**Comment by pfeerick** [comment]
@offer-shmuely What do you think? ;)

**Comment by offer-shmuely** [comment]
well let me try to answer it step by step
1. are you talking about SR10-Pro? or SR10_plus, by looking in the scripts, it looks like the firmware between the two is not compatible
2. are you sure that the script I post on edgeTx-sdcard is working on the plus receivers???
3. I do not have such receivers, so even if liked to, I can not test it.

I downloaded the setup scripts for both receivers
4. the name of the script of the old one, the pro, is FrSky_STAB_RX_2.03, and it is for openTx/edgeTx, on the new one, similar name FrSky_STAB_RX_v2.06 the ethos script, and the openTx script is now named AP_SRx_Lua_v2.04, if you can confuse the users, so why not ;-)
5. so if you have both SR10-Pro & SR10-plus, what script do you put on your transmitter? it is not clear at all
6. the script for the pro & the script for the plus, use different command codes, so they does not look compatible at all, did you note that on the video you send, he could not operate the script!!!
7. so it is a total mess. for the plus it will need a totally new script  
8. this is why I named the script S6R_S8R, so there will be no misunderstood

**Comment by pfeerick** [comment]
[As per the link](https://www.frsky-rc.com/archer-plus-sr10/), this is in relation to the SR10+... the SR10 Pro is a completely different beast (and uses STAB_RX_2.03 -> FrSky SxR_R9S lua to configure it). And yes, just a few things confusing about this whole thing... like the need to downgrade the receiver and use older Lua script for the initial calibration :-/ 

The underlying issue is that you use the AP_STAB_RX_v2.04 (AP Stab Rx_OPTX, AP Stab Rx Cali_OPTX) scripts as provided by Frsky to configure it on OpenTX/EdgeTX, but the second group of stabilisation options mentioned in the manual are not available to be configured in the OTX script, only the Ethos one. Yet it seems like there is only a *minor* modification needed to make it all work... https://github.com/EdgeTX/edgetx/issues/4574#issuecomment-1913589133

I can't say if the S6R_S8R script works for the SR10+ as only I use X9D+ with ACCESS ;)

**Comment by BompaBert** [comment]
Also confirmed that - with latest firmware -  the SRx PRO script does not
work for SRx PLUS receivers and vice versa.
The latest script (v2.06) added roll/pitch angle. I'll test that soon.

**Comment by BompaBert** [comment]
Your  S6R_S8R script only works for ACCST receivers. Wont work for ACCESS -
SRx PRO or SRX PLUS.

**Comment by offer-shmuely** [comment]
If i had the receivers, I could try to add it, at least for the pro.

It is very strange!! that the script that we put on the edgeTx sd card is working with the plus receiver, i did not expect it will.

**Comment by BompaBert** [comment]
Just very confusing indeed. The SxR series are ACCST only. Then the SRx
PRO's  uses ACCESS. Both are discontinued and seems to work with your
script or the FrSky SxR_R9S / FrSky_STAB_RX_2.03 scripts. The SRx PLUS does
not. It would be great if you could take a look at what was attached
earlier - make it nicer and maybe publish?

**Comment by offer-shmuely** [comment]
I saw the attached script you sent, and the original sr10+ scripts, they both use different command codes than my script.
Are **sure** my script ever worked on the SR10+?
That would be very surprising

**Comment by offer-shmuely** [comment]
@BompaBert, can we move to discord for that discussion?

**Comment by BompaBert** [comment]
Yours does not work for the plus series. Sent from my iPhoneOn Feb 3, 2024, at 2:12 AM, Offer Shmuely ***@***.***> wrote:﻿
@BompaBert, can we move to discord for that discussion?

**Comment by offer-shmuely** [comment]
try this code
I remind you, that I have no way to test it, I do NOT have this receivers!!

[FrSky_SR10_plus_setup_v2.05-etx-SR+.zip](https://github.com/EdgeTX/edgetx/files/14154542/FrSky_SR10_plus_setup_v2.05-etx-SR%2B.zip)

**Comment by GerritErpenstein** [comment]
> try this code I remind you, that I have no way to test it, I do NOT have this receivers!!
> 
> [FrSky_SR10_plus_setup_v2.05-etx-SR+.zip](https://github.com/EdgeTX/edgetx/files/14154542/FrSky_SR10_plus_setup_v2.05-etx-SR%2B.zip)

I have tested the script with an Archer Plus SR8. It gave me the following error:
```
Script syntax error
TOOLS/FrSky_SR10_plus/setup.lua:327: bad argument #4 to 'sportTelemetryPush' (number expected, got nil)
```

**Comment by BompaBert** [comment]
Indeed -syntax error.
@offer, you can test this using the etx companion - grab a model and run a
simulation...

**Comment by BompaBert** [comment]
@Gerrit, could you test attached. It works on the SR10+. It would be good
to try the SR8+

**Comment by GerritErpenstein** [comment]
> @gerrit, could you test attached. It works on the SR10+. It would be good to try the SR8+

I would love to test the script, but I can't find it here in the GitHub web UI. Seems like it is only available via E-Mail? It would be great if you could upload it here again.🙂

**Comment by BompaBert** [comment]
Here you go.

**Comment by GerritErpenstein** [comment]
Still no script attached. Please see the original issue: [4574](https://github.com/EdgeTX/edgetx/issues/4574)

**Comment by BompaBert** [comment]
here you go. Forgot it does not work via email.  [SRxPLUS_setup.zip](https://github.com/EdgeTX/edgetx/files/14157953/SRxPLUS_setup.zip)

**Comment by offer-shmuely** [comment]
I do use the companion, 
I added some mock so I can see the screens, but anything that is actual read/write to the RX is not working.
anyway, try this one, maybe I could guess the bug

[FrSky_SR10_plus_setup_v2.05b-etx-SR+.zip](https://github.com/EdgeTX/edgetx/files/14158353/FrSky_SR10_plus_setup_v2.05b-etx-SR%2B.zip)

**Comment by GerritErpenstein** [comment]
Crap, I just realized that the configuration of the second gyro page only works with ACCESS. However, I use ACCST. I should have read the title more carefully.
This makes the receiver with ACCST practically useless. What was FrSky thinking? 😞 Then I will probably send the receiver back again.

**Comment by offer-shmuely** [comment]
could you understand why, when using the 2 group, it have 2 mount types?
and 2 plane-type?
how can you put a single receiver in two different orientation?

**Comment by pfeerick** [comment]
You would have to ask frsky that, as they clearly know that is the case as it is outlined in the setup steps in the manual 🤣

Given the second stabilisation group when turned on controls CH7-11, maybe it's so that you can swap it between planes? As the second group also has independent calibration. I can't offhand think of any other reason why you would want duplicated controls with different control mix/orientation, unless maybe for some form of camera stabilisation through inversion?

**Comment by BompaBert** [comment]
@offer, you nailed it. It's working! Feel free to add it to the etx sdcard.
Just we all agree, this version does not cover the latest features. As
mentioned, FrSky recently added v2.06 -  are roll/ pitch angle. I tried to
add them but they return no values on the sr10+ I tested it with.

**Comment by BompaBert** [comment]
The second group has its own self-check, not calibration as far I know. A
second group can be useful in more complex setups like jets with tailerons.
One group stabilizes the ailerons and a second group stabilizes the
elevators in a delta setup (ail+ele).

**Comment by pfeerick** [comment]
It actually says calibration in the manual, but it probably doesn't mean that (or our interpretation of calibration is wrong).

**Comment by BompaBert** [comment]
Yes sir, confusing indeed. the calibration happens using a different script.

**Comment by 3djc** [comment]
The calibration for sxr allows to do initial calibration of accelerometers. It should be done once in receiver lifetime, and before installation in a craft, since it need flat leveled reference surface. It is not part of receiver config per say

**Comment by pfeerick** [comment]
Actually, no it isn't. You have calibration of the IMU "gyro", which is done in the seperate script, and appears to be one time (unless it needs resetting), and calibration of channel travel/centering, so the stabiliser knows how each bank is set up. That's the self-check calibration.

**Comment by 3djc** [comment]
Oh  yes, the channels calibration, yes, there are two different ones. One should be renamed really, but since frsky docs are what they are , not surer what can be done

**Comment by offer-shmuely** [comment]
the script have different command-id for each of the wing-type & and plane-type
it is not a mistake in the documentation

![image](https://github.com/EdgeTX/edgetx/assets/7026911/5cd2eb9b-4a3a-4d54-ac5d-44f2ef7ee1aa)

**Comment by offer-shmuely** [comment]
try this for the roll/ pitch angle
[FrSky_SR10_plus_setup_v2.05c-etx-SR+.zip](https://github.com/EdgeTX/edgetx/files/14158675/FrSky_SR10_plus_setup_v2.05c-etx-SR%2B.zip)

**Comment by BompaBert** [comment]
The roll/pitch values can be altered from 0 to 80 however I do not see any
change in servo movement. Followed instructions per TD R10 manual: " This
feature will not be activated if the degree value is set to 0-9. The
setting with the Roll/Pitch degree between 10 to 80 can have the feature
work, and it's not recommended to be set with the degree values too small."
So it says "can" - makes me unsure...
Also on 3th page, self check can't be selected and am getting intermitted
crash with message:
?.0: attempt to index field '?' (a nil value)

**Comment by pfeerick** [comment]
> the script have different command-id for each of the wing-type & and plane-type
> it is not a mistake in the documentation

Never said it was a mistake, but that would need to ask frsky about the rationale... Then again, they also clearly state these are two separate stabilisation systems, so it stands to reason everything is just duplicated. 

But as Boompa pointed out, it starts to makes sense when using more complex setups, I.e. the second bank for delta mixing (with no mixing for the first bank).

**Comment by BompaBert** [comment]
Lets hope for the best. So far, a lot of progress was made. Thanks much for
that.
Btw, on page 3  of your script, you've got a typo. Ch10 represents AIL4 and
is still controlled by the gyro. Am referring to the sr10+ manual.

**Comment by offer-shmuely** [comment]
I do not understand the mistake
> on page 3  of your script, you've got a typo. Ch10 represents AIL4 and is still controlled by the gyro

as far as I understand, if you like the CH10 to be controlled by the gyro as AIL4, you turn this ON
![image](https://github.com/EdgeTX/edgetx/assets/7026911/06c5d88c-1df6-4e37-8d91-7202cdead61c)

if you like to use CH10 for something, lets say "gears" then you need to turn it OFF, same as CH5/6



 Roll/Pitch degre
I see it only on the manual of the SR6+, not on the SR8+/SR10+/SR12+

> attempt to index field '?' (a nil value)

for that, I need you to delete from the sd card the luac file \SCRIPTS\TOOLS\FrSky_SR10_plus\setup.luac 
not the lua itself, run it again, and we will see a m ore detailed error.

**Comment by pfeerick** [comment]
The manual is out out date somewhat (and is itself inconsistent... it is v1.0, yet, mentions something about the 1.07 firmware :thinking: )... this is from the firmware log for the SR10+:

![image](https://github.com/EdgeTX/edgetx/assets/5500713/36efa12c-7d6d-49a0-abaf-644448bb69b7)

**Comment by BompaBert** [comment]
No errors since removing the .luac file. In regards CH 5-6 and 10-11. Your comment just confused me -sorry about that. Reason is that FrSky calls it "AUX" mode since the time they came out with stabilized receivers. In attached, I made a few changes in regards to that, fixed the self-check choice and uncommented the roll/pitch feature in group2. Albeit I do not see any changes in roll/pitch behavior changing the degrees on the bench but everything else works. I'll test the roll/pitch behavior in flight - maybe it is acceleration depended.
[setup_v2.zip](https://github.com/EdgeTX/edgetx/files/14167265/setup_v2.zip)
...

**Comment by offer-shmuely** [comment]
there is no real meaning tor AUX.
openTx & edgeTx does not name the channel as AUX (and good that they don't!)
on betaflight AUX1 is actually CH5
on rotor-flight AUx1 is actually CH6 (since there is a pitch as well in addition to AIL/ELE/THR/RUD)
I do not see any reason to continue and use the AUX naming

e.g.
if I like to config lights on AUX11, what channel I need to use on the transmitter? 
on betaflight it will be 11+4=CH15
on rotorflight it will be 11+5=CH16
and after configure it, there still will be no reference for that in edgeTx at all

if the first text is confusing, lets find another one that not contain AUX

**Comment by BompaBert** [comment]
What about       { "AIL2", "stab off" }

**Comment by pfeerick** [comment]
> on betaflight AUX1 is actually CH5
> on rotor-flight AUx1 is actually CH6 (since there is a pitch as well in addition to AIL/ELE/THR/RUD)

... except we're talking about Frsky, not Betaflight or Rotorflight... what language/phraseology does Frsky use? As this is what the end user will expect. The same as I  would (and do) expect Betaflight scripts/tools to reference AUX1 as CH5... that's the language of *that* system.

Also, consider the option(s) in context... 
```
CH5  mode = [AIL2|AUX]
CH6  mode = [ELE2|AUX]
CH10 mode = [AIL4|AUX]
CH11 mode = [ELE4|AUX]
```
it seems pretty clear that, for example, CH10 is either being used as AIL4, or as an auxiliary channel, not a *specific* channel. I'm not sure there is any benefit in expanding the option text out to "CH10 as AIL4" since we're only looking at CH10... and only has those two options. If you were remapping channels, sure, but not for what amounts to an stablise/user control option.

Maybe something more like this if you want to make it more explanatory?
`{ "AIL4", "AUX (Not stabilised)" }`

I was going to suggest
`{ "AIL4 (Stabilised)", "AUX (Not stabilised)" }`
but I'm not sure what happens when you turn one of the stabiliser groups off... i.e. I would expect the channel assignment to remain, but the channel to not be stabilised, so that text would be wrong in that instance.

**Comment by offer-shmuely** [comment]
The "AUX (Not stabilized)" } sound good to me (as long as the AUX does not have number) 

changing the ON string to "stabilized as AIL2"

[FrSky_SR10_plus_setup_v2.05d-etx-SR+.zip](https://github.com/EdgeTX/edgetx/files/14173268/FrSky_SR10_plus_setup_v2.05d-etx-SR%2B.zip)

**Comment by BompaBert** [comment]
I have been using the FrSky receivers sine they came out. Being used to
AUX1 AUX2 etc...so initially, Offer's description throwed me off.
Personally I would not add any comments and stick with the Frsky way of
doing things. FrSky receivers can be complex to handle and  if you don't
want to get in trouble, reading / understanding the available manuals and
release notes is a must and tools like this one should not replace or
change that. Adding stabilization comments or descriptions in a
stabilization tool is in my opinion overkill. And a Peter mentioned,
disabling a group removes all stabilization in that group. All do respect,
I would go with the FrSky way or what Peter suggested:

CH5  mode = [AIL2|AUX]
CH6  mode = [ELE2|AUX]
CH10 mode = [AIL4|AUX]
CH11 mode = [ELE4|AUX]

**Comment by 3djc** [comment]
That will also help consistency with BW

**Comment by BompaBert** [comment]
The AIL stab functionality fails when the receiver is mounted vertical or vertical reverse. It works ok horizontally or reverse mounted. Rolling a bit to one side, lets say the left, throws the servo to max. Rolling to the right, stabilization is ok. Will update on further testing and findings.

**Comment by offer-shmuely** [comment]
can you compare it to the original script?

**Comment by BompaBert** [comment]
Here is my version. Am using 2 pages. On page for each stabilization group. You can switch the pages back and forth. Everything seems to work on the SR10+ with v1.0.10 firmware except the roll and pitch angle. Am not 100% sure the roll/pitch angle script values are ok neither do I have a clue what it supposed to do. Playing with different angle values does not changes anything, at least not on the bench. Any comments welcome.
[SRxPLUS_setup.zip](https://github.com/EdgeTX/edgetx/files/14250808/SRxPLUS_setup.zip)

**Comment by Ralf-W** [comment]
> Here is my version. Am using 2 pages. On page for each stabilization group. You can switch the pages back and forth. Everything seems to work on the SR10+ with v1.0.10 firmware except the roll and pitch angle. Am not 100% sure the roll/pitch angle script values are ok neither do I have a clue what it supposed to do. Playing with different angle values does not changes anything, at least not on the bench. Any comments welcome. [SRxPLUS_setup.zip](https://github.com/EdgeTX/edgetx/files/14250808/SRxPLUS_setup.zip)

Thanks a lot for your significantly improved LUA script "SRxPLUS_setup.zip". I installed it into my TX16S, running EdgeTX 2.9.3, using ACCST mode, FrSkyX2 LBT(EU), MPM Version v1.3.3.33.
Page 1/2 now allows to input those roll and pitch limit values - and I can report that this feature does work correctly:

As an example I have set the roll limit to 60 degrees. For the bench test, I keep the SR10+ receiver horizontally and do not move it, while I control the aileron stick of my Tx to +100%. This moves the roll servo nearly into one end position. Now I tilt the Rx slowly into the desired roll direction. This reduces the deflection of the roll servo continuously, reaching it's neutral position exactly when the telemetry displays a roll ange of 60°. 
In flight the full +100% aileron stick command will make the airplane roll into the desired direction - but the stabilizer mode of the Rx will reduce the aileron deflection continuously until the model has reached a bank angle of 60 degrees. Then the aileron servo is back to its neutral position, where it will be kept and stabilized by the Rx - though the aileron stick at the Tx is still fully deflected to +100%.

I tried different settings for the target roll angle, keeping the Rx fixed to the bench: As stated in the manual, there is no bank angle limiting between 0° and 9°. For small bank angle limits (beginning at 10°) the maximum servo movement that can manually be controled by the aileron stick is significantly reduced. It nearly reaches full servo deflection for the maximum allowed bank angle of 80 degrees. In flight the Rx will be rotated together with the airplane and the stabilization will reduce the manually controled  servo deflection immediately until the target bank angle is reached.

Thus, your improved LUA script activates the bank angle limit feature for me. 

However, I do see the second page with all the parameters for the second "Stable System 2" - but the values there don't get populated. Therefore I cannot switch off the stabilizing for channels 7-11.
Yes - I updated the Rx to firmware version V.1.0.10. Nevertheless, some of my settings are not correct.

What are your successful firmware selections (EdgeTx , multimodule , Rx) to be able to readout and change the values of "Stable System 2"?

**Comment by BompaBert** [comment]
@Ralf-W , you will need to run in ACCESS mode to get the second stab group to work -thanks for the testing though. My setup is the Frsky Horus X10S Express, running EdgeTX 2.9.3 with a SR10+.
Am attaching the complete directory here -it includes the calibration script using custom pictures -the Frsky script can be confusing. And comments are welcome.
[SRx_PLUS_v2.05.zip](https://github.com/EdgeTX/edgetx/files/14268523/SRx_PLUS_v2.05.zip)

**Comment by BompaBert** [comment]
FYI. Tested roll/pitch angle in flight and it works fine - in auto level mode the roll/pitch angle can be reduced by settings the degrees in the setup script from 10 - 80. No limitation when leaving the setting to 0 - 9 degrees.

**Comment by crogersqx7** [comment]
Has this working script with pitch and roll angle been added to the sd card contents??

**Comment by offer-shmuely** [comment]
No, it is not
There is no one that can really support it

**Comment by offer-shmuely** [comment]
You can find the last version on my repo, but I cannot support it, since i do not have the hardware

**Comment by BompaBert** [comment]
[SRx_PLUS_v2.05.zip](https://github.com/EdgeTX/edgetx/files/14268523/SRx_PLUS_v2.05.zip) is working fine. Pitch, Roll and both stabilization groups- tested on the SRX series of receivers. It has been made public via RCGroups and so far, no issues. This is my version though but feel free to take a look and eventually add to the SD card.

**Comment by BompaBert** [comment]
@pfeerick , FYI - above script is partially failing with EdgeTX version 2.10 (Hedgehog). The second page can't be chosen anymore.

**Comment by pfeerick** [comment]
What radio? I can't test on a colorlcd Frsky radio (only have the X9D series radios), but the TX16S is able to page back and forwards between the two pages in SRxPLUS_setup (with 2.10.0-rc3). If you're still running RC1 or RC2, you probably need to update to RC3 as some missing EVT_PAGEDN_ events were re-added, which is probably why it isn't working for you.

**Comment by BompaBert** [comment]
Peter, indeed RC3 doesn't have the problem anymore. What still happens
after the upgrade is that ( Frsky X10 ACCESS) the special functions repeat
sets to 1 second all over the line. Also in mixes and logical switches, the
sliders and rotary knobs disappear. This was also the case upgrading from
2.9.4 to 2.10 RC2.

**Comment by BompaBert** [comment]
Peter, disregard previous remarks and the special instructions and logical
switches. Upgrading from 2.9.4 to 2.10 RC3 works fine. No changes in the
setup this time so please accept my apology.
There is 1 thing though, not related to the upgrades. The Logical Delta
switches d>=x and  [d]>=x work for all trims except the throttle trim.
Maybe worth taking a look at?

**Comment by ALACVDO** [comment]
Hello,
I am trying to configure the FRSky Archer SR10+ using my TX16S with the LUA script shared by @BompaBert. I can calibrate the receiver, but the changes I make in the radio are not saved in the receiver. Any suggestions?

**Comment by AndyWBing** [comment]
I am having the same issue with my Archer Plus SR6 mini. I can calibrate it but the setup lua script on my TR16S (edgeTX) does not seem to change anything on the receiver e.g I can not reverse the ailerons and rudder, which I need to do. I make the changes on the transmitter but they are not transferred to the receiver. I have tried the script from the FrSky website and from this thread.

**Comment by 3djc** [comment]
Just to confirm your understanding, inversing in the LUA does not invers channel response, it does only invers receiver generated correction

**Comment by AndyWBing** [comment]
Yes, I only want to correct the receiver stabilisation responses, the transmitter responses are all correct.

**Comment by galosre** [comment]
Working on it for 2 days what I found for the SR10+ I you update to the latest FW V1.0.11 from Frsky the script is broken nothing got save but if you go back to V1.0.10 the script is working!

**Comment by BompaBert** [comment]
Version 1.0.11 needs the Ethos v3.0.0 stab tools as also mentioned in the notes and Stab Config Instructions manual. The last firmware version for OTX or ETX am aware that works with the SRx series is indeed 1.0.10. Am adding the files here, this time completed with the bmp / img files. Extract SRx_PLUS_v2.04 to /scripts/tools and copy the img (Horus)

[SRx_PLUS_v2.04.zip](https://github.com/user-attachments/files/20615032/SRx_PLUS_v2.04.zip)

 / bmp (Taranis) directory to /scripts/tools as well.

**Comment by p-yro** [comment]
I found that the lua scripts work on ETX 2.10.6, but doesn't work on any 2.11.X (Jolly Mon) firmware versions. Any way we can get an update? Or is there something I can change in the code to get it to work? Thanks!

**Comment by rcrajka-Mirko** [comment]
- ![Screenshot_20260602_173613_com.anthropic.claude.jpg](https://github.com/user-attachments/assets/77e2d98d-e9a0-41a3-8b93-eccf068a3591)

**Comment by rcrajka-Mirko** [comment]
Hello. Any idea why you can't run the script? 
Thank you

**Comment by offer-shmuely** [comment]
It intended to color screens

**Comment by rcrajka-Mirko** [comment]
Thank you.
