### ISSUE TITLE
Rolling release

### ISSUE THREAD

**Issue by yds** [EdgeTX/edgetx#46]
[Betaflight Configurator Nightlies](https://github.com/betaflight/betaflight-configurator-nightlies) looks like a perfect method to offer EdgeTX rolling releases.. could that be done for EdgeTX builds? :thinking:

**Comment by pfeerick** [comment]
This should be resolved now - https://github.com/EdgeTX/edgetx/releases/tag/nightly  - appears to be up and running now.
