### ISSUE TITLE
Protocol option value still missing for Bayang?

### ISSUE THREAD

**Issue by aheyer** [EdgeTX/edgetx#4606]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

According to the [documentation of the multiprotocol module](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#bayang---14) there is an option value for the protocol Bayang, sub protocol "Standard". When binding an Eachine H8S 3D with custom Silver13 firmware I'm unable to see and set this option value. There is no UI control for this option to set to 1 for Silverxxx telemetry. But even without setting this value telemetry works as expected.

### Expected Behavior

According to [my request to the multiprotocol devs](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/937), this option value should be displayed. OpenTX is reported to work as expected on that point. And even [EdgeTX should be fixed](https://github.com/EdgeTX/edgetx/issues/2713)?

### Steps To Reproduce

Bind a model with Bayang protocol, sub "Std". Model settings tab is missing an (adjustable) option value in the internal RF section.

### Version

2.9.3

### Transmitter

RadioMaster Zorro

**Comment by pfeerick** [comment]
Check the "Telemetry" entry... that has your four  options for Bayang:

![image](https://github.com/EdgeTX/edgetx/assets/5500713/b77027f6-f8a7-487a-91fd-19f83ca13347)

**Comment by aheyer** [comment]
Okay, I saw it before but did not associate it with the numerical option values. Instead I stumbled across: Why is there a no-telemetry-option and a no-telemetry-checkbox? I know there isn't much space on the BW screens but how about to add some indication that this setting is the option value from the multiprotocol documentation?

**Comment by pfeerick** [comment]
The "No telem" checkbox is for the MPM telemetry and is a global MPM
option... as is the bind CH and low lower option.

Given the MPM references the options as

14,Bayang,Bayang,H8S3D,X16_AH,IRDRONE,DHD_D4,QX100

I'm not sure it can be made clearer on our side given space... the MPM
documentation probably needs to be improved to indicate how the options
will be displayed

**Comment by aheyer** [comment]
Pascal of MPM updated the documentation when I told him EdgeTX's wording of the values. So everything is fine now.

**Comment by pfeerick** [comment]
Thanks for the update :)
