### ISSUE TITLE
Allow . (dot, period) in MT12 model names

### ISSUE THREAD

**Issue by kmf123kmf** [EdgeTX/edgetx#4618]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Many cars and trucks, especially race vehicles, have dots in their names (examples: SC6.4, B74.2).  Currently this character is excluded when editing model names from within the transmitter.  

### Describe the solution you'd like

Add '.' to the list of allowable model name characters when editing within the radio

**Comment by pfeerick** [comment]
This is somewhat related to https://github.com/EdgeTX/edgetx/issues/1858

**Comment by kmf123kmf** [comment]
> This is somewhat related to #1858

After reading it, implementation of #1858 would be my preferred fix if possible.
