### ISSUE TITLE
INav Lua colors are incorrect

### ISSUE THREAD

**Issue by mwilson007** [EdgeTX/edgetx#462]
Here is a pic of what it should look like with the white text and what it looks like when running EdgeTX.

![inav1](https://user-images.githubusercontent.com/8064855/125902645-d5853694-b64e-43a2-9fab-0f0e4c08cb18.jpg)
![IMG_5293](https://user-images.githubusercontent.com/8064855/125902707-758f586d-2099-4faa-8879-b4cf30779029.JPG)

As discussed in the lua discord channel.  I'm opening a bug report for this issue.

TX is a RadioMaster TX16s running EdgeTX RC3 latest nightly build.

**Reply from Risto on this issue.**

I had a look at LUA color handling and compared it with OpenTX. Well the enum is different. I got it to work with EdgeTX (here screenshot from EdgeTX simulator24), but you are not gonna like the solution unfortunately or the details - as I guess either iNav devs must rework their script or EdgeTX needs to match the enum order with color order of OpenTX 2.3 (details below):

![inav_fixed](https://user-images.githubusercontent.com/8064855/125903453-a94e0f18-beee-4bdb-a64d-2f87fa9cf98c.png)

In EdgeTX and OpenTX, text in LUA is output using luaLcdDrawText() https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/lua/api_colorlcd.cpp#L217-L260
It's color (line 236 in the previous link) is taken from a lcdColorTable: https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/gui/colorlcd/colors.cpp#L23 that uses enum index.
EdgeTX uses following index: https://github.com/EdgeTX/edgetx/blob/6ded23f26bc01580ab7d506941bf72eaee7d77a9/radio/src/gui/colorlcd/colors.h#L28-L75
In OpenTX there is the same enum, but the list is differently populated: https://github.com/opentx/opentx/blob/c6e8ed866c48cef2ef34c335dea093ab9198ce43/radio/src/gui/480x272/colors.h#L50-L83
Thus when the raw index values are used (as iNav LUA widget apparently does), the output is different. The first index in OpenTX is TEXT_COLOR_INDEX, whereas in EdgeTX ALARM_COLOR_INDEX.
In order to get the white text in iNav LUA, I reshuffled the order in colors.h and made DEFAULT_COLOR_INDEX the first entry instead of red ALARM_COLOR_INDEX, rebuilt EdgeTX simulator and voila the screenshot above with white text as it should...

**Comment by JimB40** [comment]
Yeah do it. 
Most of basic LUA use lcd.drawText() without specifying color so TEXT_COLOR_INDEX should be used.
Besides this red is hurting my eyes ;)
