### ISSUE TITLE
Incorrect switch settings in Companion 2.10.

### ISSUE THREAD

**Issue by philmoz** [EdgeTX/edgetx#4640]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

The default switch settings in radio config are incorrect in the latest 2.10 Companion update.

- SH - is set to 2POS, not 2POS toggle
- SI - is set to 2POS, not None
- SJ - is set to 2POS, not None

Also, changing SI & SJ setting to None does not stick on save. Reloading the .etx file in Companion will show SI and SJ set back to 2POS switches,

### Expected Behavior

SH, SI and SJ should have the correct defaults.
Changes to SI & SJ should remain after reloading .etx file.

### Steps To Reproduce

1. Using TX16S radio profile, create a new .etx file.
2. Edit radio settings and select Hardware tab
3. Note incorrect defaults for SH, SI and SJ
4. Change SI and SJ to none, save .etx file
5. Close .etx file and re-open it - SI & SJ are set back to 2POS.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

Current main branch.

**Comment by elecpower** [comment]
Confirmed. I've got it.
