### ISSUE TITLE
USB joystick configuration  for CH26 is shown but not configurable

### ISSUE THREAD

**Issue by ThomasKuehne** [EdgeTX/edgetx#4643]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The on-contoler menu to show and modify the advanced USB joystick configuration shows channels 1 to 26. However only channels 1 to 25 are reachable via scrolling. Channel is not reachable and thus can't be configured.

### Expected Behavior

All channels shown in the advanced USB joystick configuration  are configurable.

### Steps To Reproduce

1. open model configuration
2. go to page SETUP
3. set USB Joystick mode to Advanced
4. open [Channel Setting]
5. scroll to channel 25

### Version

2.9.3

### Transmitter

Jumper T-Lite

### Anything else?

![screen-2024-02-15-224736](https://github.com/EdgeTX/edgetx/assets/2562574/de94792d-4e02-41f7-9b61-3d9de1f64b59)

**Comment by pfeerick** [comment]
Can't reproduce this on Pocket, can reproduce on TLite - possibly 9X navigation issue. Seems like there is a one row offset somewhere.
