### ISSUE TITLE
Model Select Page Simplification

### ISSUE THREAD

**Issue by schlamon** [EdgeTX/edgetx#4646]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It is frustrating and slow to scroll through the image tiles in the 'Model Select' page

### Describe the solution you'd like

It would be great to have a selectable option to turn this page into a text based list or grid, so that much more models can be displayed on the screen at any one time, and scrolling between models is fast.

### Describe alternatives you've considered

1. A simple numerically ordered list like Open TX for LCD Displays
2. A list where you can hide/show models under a certain category
3. A list of categories. Categories can be selected with the scroll wheel or touch screen to open up a list of models in that category

**Comment by pfeerick** [comment]
This has already been implemented in https://github.com/EdgeTX/edgetx/pull/4524 for 2.10 :smile:
