### ISSUE TITLE
Using "Spectrum (INT)" Modifies Model

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#465]
I have a model setup with the internal MPM set to off and the external ELRS set to CRSF.

When using the Spectrum Analyser, it modifies my model by enabling the internal MPM.

I don't know if this is possible but what I would expect is that it gets the state of the internal MPM for the model, turn it on if it is not on and on exit restores it to what is was. Or maybe create a temporary model while using the spectrum analyser and revert to my model when done.

**General information**
 - EdgeTX version (2.4.0 RC4)
 - RM TX16S

**Comment by pfeerick** [comment]
I was able to reproduce this on basically yesterdays nightly and TX16s, with Internal RF: OFF, and External RF: XJT. After opening the spectrum analyser the Internal RF was MULTI, and External RF still XJT, and no apparent change to the XJT status.
