### ISSUE TITLE
jumper t20 firmware messes the icons up on screen

### ISSUE THREAD

**Issue by Trentfpv24** [EdgeTX/edgetx#4657]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

after installing the firmware listed the icons on the screen are overlaping and missing some of the icons..
![IMG_20240217_073433351](https://github.com/EdgeTX/edgetx/assets/160346386/3ed1c9c1-b671-4483-b973-58daeb65256b)

### Expected Behavior

the icons should show the other switches and not overlap

### Steps To Reproduce

turn on the radio

### Version

2.9.3

### Transmitter

Jumper T20

### Operating System (OS)

Windows

### Anything else?

![IMG_20240217_073433351](https://github.com/EdgeTX/edgetx/assets/160346386/c982edd7-b049-4204-8b41-e1619e284093)
[bw128x64 (2).zip](https://github.com/EdgeTX/edgetx/files/14319813/bw128x64.2.zip)

**Comment by pfeerick** [comment]
Are you sure that's a T20 firmware on 2.9.3? It's not supported by 2.9.x *at all* ;) Please either install the factory firmware per https://edgetx.org/supportedradios/ or install a [nightly firmware for it](buddy.edgetx.org/#/flash?version=nightly&target=t20) if you want something newer.
