### ISSUE TITLE
Wrong entries in the logical switch function popup-menu

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#469]
The function popup display for the logic-switches functions shows some strange entries. The below picture is for translation DE.

The "sticky" should be labeled "SRFF" and the other entries are also somewhat weird.

![screenshot_tx16s_21-07-18_07-46-23](https://user-images.githubusercontent.com/8696319/126057289-69be4964-b570-47e4-9021-73cb8eb23f60.png)

**Comment by pfeerick** [comment]
Last four entries are all a bit off.

**Comment by raphaelcoeffic** [comment]
Fixed by b553713527e22a94
