### ISSUE TITLE
LUA: special function repeat parameter missing for model.setCustomFunction

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#4692]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the current main, no value can be set for "Repeat" via lua model.setCustomFunction. I think this has happened since there is now a separate activation switch
![image](https://github.com/EdgeTX/edgetx/assets/15068446/8e6212fe-242a-41ff-8245-cc4afac21a9d)

### Expected Behavior

repeat like  !1x, 1x, 1s, 2s and so on should be setable for model.setCustomFunction

### Steps To Reproduce

try to set repeat like  !1x, 1x, 1s, 2s and so onwith  model.setCustomFunction in a lua script

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

current main

**Comment by philmoz** [comment]
Repeat and active used to share the same data field in the custom function. Now they are separate.

There was never a 'repeat' entry in the table so you would have had to set it using the 'active' property in the Lua script.

I can add a 'repeat' entry to the table - you will need to update any scripts though.

**Comment by ParkerEde** [comment]
Yes, exactly. Before, for example, activate=255 => !x1 
Since this is now split up, it would be super helpful if we could introduce a new attribute, e.g. "repeat".

**Comment by pfeerick** [comment]
Does the link PR do what you want?

**Comment by ParkerEde** [comment]
Basically, it has been implemented as I imagined. Unfortunately, SET does not yet work. I have described it in more detail in the PR
