### ISSUE TITLE
LED turn red on error

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#470]
Had OpenTx on my radio recently. What a horrible experience coming from EdgeTX.

Anyway, one thing that OpenTX did was when I turned the radio on and the sticks or throttle was in an invalid position, it showed the error on the screen like EdgeTX but also turned the LED red until the fault was rectified or cleared. Doesn't happen on EdgeTX Thought it looked pretty cool.

RM TX16S

**Comment by raphaelcoeffic** [comment]
> Had OpenTx on my radio recently. What a horrible experience coming from EdgeTX.

😜
