### ISSUE TITLE
PLAY TRACK SF audio track selection borks if >256 sound files exist

### ISSUE THREAD

**Issue by TodWulff** [EdgeTX/edgetx#4711]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

As stated, if more than 256 sound files exist in the en folder, when configuring a PLAY TRACK SF, the file picker becomes blank.  Only way I've found to restore proper operation is to mount the uSD to a host PC and prune the files to <(=?)256.

### Expected Behavior

Have file picker display the list of sound files, even if more than 256 sound files exist in the /SOUNDS/en/ folder.

### Steps To Reproduce

Put additional sound files into the /SOUNDS/en/ folder, so the total sound file count exceeds 256, and then attempt to instantiate a PLAY TRACK SF and attempt to select an audio track to be played when the SF fires.

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster MT12

### Anything else?

MT12 2.11.0-nightly 03/06/2024

**Comment by philmoz** [comment]
I cannot reproduce this - I have tested on X7S, MT12 and T14 using a SOUNDS/en folder with 928 sound files.

Can you zip up your SOUNDS folder and upload here in case the problem is specific to your sound folder content.

**Comment by 3djc** [comment]
Scanned briefly through the code yesterday, and could not find any obviously suspicious, no uint8_t either, everything seems to be 16 bits there

**Comment by TodWulff** [comment]
Hola.  As info, I too am not able to reproduce this now.  I may have been on an old nightly (one that came with the unit from the factory.?.).  Regardless, I replaced the files I had previously pruned from the MT12 and the file picker is now working like it should.  I'm closing this issue at this time.  Thanks for looking gents.  Sorry to spin y'all's wheels.  ~MHz
