### ISSUE TITLE
Telemetry: add constants to calculated telemetry and enable negative Ratio

### ISSUE THREAD

**Issue by blopa1961** [EdgeTX/edgetx#4732]
This request replaced by #4785 please close it.

**Comment by frankiearzu** [comment]
@blopa1961 ratio can be use to decrease the value.  Any value lower than 25.5 (or 255 on some GUI with no decimal) decreases the value. That's 100%, if you want / 10 (or 10%), use ratio 2.5 (25 on GUI with no decimal).

**Comment by blopa1961** [comment]
Well, it seems I din't read thoroughly on Ratio, but you have to admit that 25.5 is not a very clear way to show 100%... in fact, the "unknown" sensor returned by my Matek gyro was configured for a Ratio of 0. I should change it to 25.5, right?
My Matek gyro is connected to an Archer S6 via F.PORT (TX3 in the G474) and using Access protocol.
I just corrected the Roll and Pitch values to the "correct" -180.0 to 180.0 by changing Precision to 1 decimal. Still have to test iNav, since I swear I saw the "900" value in the .lua, maybe they use some kind of module function on the values, but the horizon works ok without changing the precision.
Answering your questions here are the IDs for the G474-HELI:
Pitch: 5230-0 (range -90.0 to 90.0 with 0 level, with precision to 1 decimal)
Roll: 5240-0 (range -180.0 to 180.0, with precision to 1 decimal)
VFAS (LiPo): 0210-0
Hdg (it has an onboard compass): 840-0 (range 0.00 to 359.99 has 2 decimals)

I also have a Pixhawk which works perfectly with the Yaapu script out of the box, would you like me to get IDs for it?

**Comment by blopa1961** [comment]
I tested iNav with the G474 and the horizon is wrong (barely moves) with the precision to 1 decimal, it actually expects -1800 to 1800 and -900 to 900.

**Comment by frankiearzu** [comment]
Ratio=0 (or --) means skip the scaling logic, so is the same as 100%

**Comment by blopa1961** [comment]
I'll post a new enhancement request, closing this one.
