### ISSUE TITLE
bw - unable to copy/move certain mixer lines

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#4739]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

A present for you @3djc ... like the gift that keeps on giving, it seems like copying and moving mixer lines (input lines are ok) is broken... again.

https://github.com/EdgeTX/edgetx/assets/5500713/6d42088e-c9ef-4f0f-b864-d72ea9bd5d84

Just try to move or copy a mix more than two lines... and watch what happens :confounded: 

Affects both bw128 and bw212, radio and simulator. 

### Expected Behavior

er... that I should be able to copy and move mixer lines? duh!

### Steps To Reproduce

1. Load up a model
2. Go to to mixes page
3. Pick a mixer line, long press enter
4. Choose either copy or move
5. Try to move the sucker... it will fight you!

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X9D+2019, Jumper T-Lite, RadioMaster Zorro

### Anything else?

Nightly as well as 2.10.0-rc1. v2.9.4 appears to be fine.

**Comment by 3djc** [comment]
Interesting as the same code is used in 212 and 128 !

will look into it after Starship launch

**Comment by pfeerick** [comment]
I believe that was backported to 2.9 so while I would normally agree with you (on principle, due to the author of said PR :hand_over_mouth: ) maybe not... :zany_face: 

Fingers crossed... https://www.space.com/spacex-starship-flight-3-launch-what-time

**Comment by 3djc** [comment]
No no no nothing to do with the author, but the number is 3999, if you rotate it, a 666 becomes obvious ! Devil at work ! (ok, not the greatest lame excuse ever :D)

Anyway, it works fine if you revert that commit :D :D :D

**Comment by 3djc** [comment]
Looks like my instinct was not far off :D

**Comment by pfeerick** [comment]
Indeed it was... just one itty bittly little gremlin is all it takes ...

So, did you enjoy the show? looks like they checked most of the boxes they wanted for this launch. :)

**Comment by 3djc** [comment]
Yeah, those plasma pictures where awesome. Still way to go to get back the ship and the booster, but good progress anyway
