### ISSUE TITLE
Radio freezes when updating internal ELRS via USB-VCP

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#4740]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

With the Zorro and T14, updating internal ELRS via USB-VCP locks the radio up hard, requiring removal of the battery. The ELRS pass through update is successful, the radio UI simply stops updating from the moment the update starts. I've not tried this on colorlcd yet to see if this is present there also, implying a common lower level issue. 

### Expected Behavior

That the radio not require a hard power off when using passthrough updating. 

### Steps To Reproduce

1. Connect USB, select USB-VCP
2. Perform passthrough update using ExpressLRS Configurator
3. Witness successful update, unresponsive radio

### Version

Other (Please specify below)

### Transmitter

RadioMaster Zorro

### Anything else?

v2.10.0-rc1

**Comment by philmoz** [comment]
Possibly related to #4731

**Comment by pfeerick** [comment]
Yes, sounds very similar.

**Comment by KondratokGK** [comment]
Same issue, but ELRS is not flashed
