### ISSUE TITLE
UA translation missing some text

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#4743]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The UA translation is broken on color radios:
  
<img width="1227" alt="Screenshot 2024-03-14 at 16 24 15" src="https://github.com/EdgeTX/edgetx/assets/1050031/16b0a794-8271-4eaa-9322-482cc0fe566f">
<img width="1231" alt="Screenshot 2024-03-14 at 16 24 38" src="https://github.com/EdgeTX/edgetx/assets/1050031/2c6d9e35-4a1c-4b2e-8568-064f3539d29b">

### Expected Behavior

Missing text need to be filled with something.

### Steps To Reproduce

Compile any color radio with `-DTRANSLATIONS=UA`.

### Version

Other (Please specify below)

### Transmitter

Flysky EL18, Flysky PL18/PL18EV, RadioMaster TX16S / TX16SMK2

### Operating System (OS)

macOS

**Comment by pfeerick** [comment]
Missing translations are present in #4613 which will probably be merged today.
