### ISSUE TITLE
Value widget - Time - Top Bar : doubles stamps the time & it doesn't look good

### ISSUE THREAD

**Issue by JWKillTime** [EdgeTX/edgetx#475]
The TX16s on Screen Settings when setting the time in the top banner it doubles stamps the time & it doesn't look good.

![TX16s Screen settings Time Double (1)](https://user-images.githubusercontent.com/45085856/126239062-ff05687a-2d07-4db5-bd9c-c5cba66bef61.jpg)
![TX16s Screen settings Time Double (2)](https://user-images.githubusercontent.com/45085856/126239071-b24fedec-853e-4141-b0c3-6fa9599a02c1.jpg)

**Comment by eshifri** [comment]
This is a new problem: it worked OK at least prior to RC1.

**Comment by eshifri** [comment]
And it happens with time and timers on all widgets.

**Comment by eshifri** [comment]
The problem occurs if Timer or Time are selected as value->timer. In this case two different font sizes are used to output the time.
If widget is created as timer  - not a value - everything is OK. Unfortunately in this case timer name is not available (only index) and Time is not available either.

**Comment by JWKillTime** [comment]
Updated to newest Flasher & firmware & all is sorted. Thanks
