### ISSUE TITLE
'Edit GVAR' screen should display FM numbers as well as names

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#4762]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Users of my glider templates are having issues with the GVAR menus. These are due to an inconsistency between the main grid and the edit menu:

The main grid displays flight modes by their number only, no mention of FM names:
![screenshot_tx16s_24-03-18_10-15-40](https://github.com/EdgeTX/edgetx/assets/6317479/53da6405-f9c3-40e1-825f-7132295e3be1)

However, in the Edit menu, the FM names are displayed, but _not the flight mode numbers_. 
Also, there's no visual separation between the header block and the first FM line.
![screenshot_tx16s_24-03-18_10-12-26](https://github.com/EdgeTX/edgetx/assets/6317479/0eb6aed1-217c-4749-a4b7-be2436cfb8bb)

This is really confusing for first time users.  

### Describe the solution you'd like

In the GV edit screen, all flight modes should prefixed by the number FMn: for example:

FM0:Thermal
FM1:---
FM2:---
FM3:Cruise

I've only looked at this for the colour LCD screens, but I think the same should apply to the mono screen radios. If there's a choice of displaying the FM name or the number, IMO the number is more important, to make it consistent with the grid view.

**Comment by pfeerick** [comment]
It says GV4=FM0 in the page header... does that correctly update when you
change flight modes? I don't disagree though, index should be shown for
consistency as well as name (since now have space to show it).

**Comment by RC-SOAR** [comment]
Yes, the top line updates correctly when the active flight mode is changed.

>  I don't disagree though, index should be shown for
> consistency as well as name (since now have space to show it).

It would be great if the index could be included :-)  IMO consistency, even in small details, can make all the difference for those using EdgeTX for the first time.
