### ISSUE TITLE
Companion cannot download multiprotocol updates

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#4773]
The issue is logged on behalf of Pascal 'Multi' Langer, who reported it to me.
The issue exist since the air/surface change introduced multi side . (There is now air and surface version of multi firmware since the flash cannot hold enough protocols to handle both)

### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When trying to update components, it fails on multiprotocol

### Expected Behavior

You can update components

### Steps To Reproduce

Set your update settings to include multiprotocol
Try to update components.
You will be greeted by:

![image](https://github.com/EdgeTX/edgetx/assets/5167938/5d46c619-41fd-40d3-9a88-2f8fcf871f5e)

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?

Reproduced on 2.10RC1 and 2.9.4

**Comment by 3djc** [comment]
Totally unrelated to the issue itself, but very related to Pascal, if someone is aware of "Jarvis" sound pack, please let me or Pascal know, he is looking for one for his Iron Man theme TX16S Max.

**Comment by elecpower** [comment]
Caused by the number of assets exceeding the results per page. The latest release has almost doubled the number of assets.

**Comment by 3djc** [comment]
Makes sense. I guess as we don't support MT12 yet on companion, we choose air stuff

**Comment by teradactyal** [comment]
Got the same problem trying to update 2.9.4 to 2.10

**Comment by elecpower** [comment]
You need to update Companion to 2.10 first then update multi protocols from Companion 2.10

**Comment by teradactyal** [comment]
> You need to update Companion to 2.10 first then update multi protocols from Companion 2.10

Thanks mate
