### ISSUE TITLE
LUA: "playnumber" no longer plays UNIT 14 (milliampere hours)

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx#4786]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the simulator, as well as in the radio firmware, the unit 14 "milliamperehours" is no longer played for a LUA widget with the command "playnumber". However, 13 percent and 15 watts work correctly.

![image](https://github.com/EdgeTX/edgetx/assets/15068446/d82cf701-51a9-41c7-bc2a-13b82067a71b)

The wave file "mamph0.wav" is located in SYSTEM folder.
### Expected Behavior

14 Milliamp Hour should be played

### Steps To Reproduce

try to play 14 Milliamp Hour in LUA widget

### Version

2.9.4

### Transmitter

FrSky X10 / X10S (ACCST), RadioMaster TX16S / TX16SMK2

### Anything else?

current main

**Comment by philmoz** [comment]
Can you play the sound file from SD CARD file browser on the radio?

**Comment by philmoz** [comment]
Also do you have both mamph0.wav and mamph1.wav on the SD card.

**Comment by ParkerEde** [comment]
Sorry. I was not aware that this unit is now differentiated between single and multiple numbers. it works with mamph1.wav. Thank you
