### ISSUE TITLE
More brightness settings for OLED screen

### ISSUE THREAD

**Issue by KondratokGK** [EdgeTX/edgetx#4789]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I want for full brightness on OLED when i use it. But OLED screen wear out on high brightness.

### Describe the solution you'd like

It should change low brightness value, inactivity time from to low brightness and condition for full brightness(All/buttons/trims/alarm etc.). Just copy same menu from monochrome lcd and add some modifications.

### Describe alternatives you've considered

1. Use knob for brightness

### Additional context

Now i use jumper t20 gemini v1 or v2 IDK and v2.10.0-rc1.

**Comment by 3djc** [comment]
So what exactly are you missing??? What you described is already part of t20 firmware since the beginning

**Comment by 3djc** [comment]
Ok, I see what you mean, the feature is there, but the settings have disappeared, will make sure they are back before next RC
