### ISSUE TITLE
Warning: radio settings file version 2.10.0 is not supported by this version of companion!

### ISSUE THREAD

**Issue by PeterJBurke** [EdgeTX/edgetx#4790]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Brand new Radiomaster Pocket out of the box.
Try to connect to companion, up pops this warning:
Warning: radio settings file version 2.10.0 is not supported by this version of companion!

### Expected Behavior

Should connect to radio to enable download settings etc.

### Steps To Reproduce

See "current behavior"

### Version

2.9.4

### Transmitter

RadioMaster Pocket

### OS Version

WIn11

**Comment by 3djc** [comment]
As expected. Pocket is a 2.10 minimum radio, so older versions cannot work with it. Please use a 2.10 (rc) version of companion
