### ISSUE TITLE
In Companion v 2.10.0 and in the newer v.2.11.0 the selection of PPM and SBUS have been lost

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#4800]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

The selection of PPM is not retained in the Companion.
It is present in all previous versions, only since v.2.10.0 it is no longer present.

### Expected Behavior

Mode options
Off - RF module is not used

PPM - Pulse Position Modulation used by many generic JR compatible modules.

### Steps To Reproduce

Install version > 2.10.0

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

**Comment by elecpower** [comment]
Updated title as I found SBUS is also missing
