### ISSUE TITLE
PT support: Missing special characters support

### ISSUE THREAD

**Issue by zandorsp** [EdgeTX/edgetx#4803]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

![msg71610786-903215](https://github.com/EdgeTX/edgetx/assets/53715440/6e28a07e-4c63-4ea1-8bd1-c6240f39b821)

There is no support for special characters in Portuguese. The radio replaces with a space character.

### Expected Behavior

The Portuguese( PT ) needs the following special characters: 
Á, á
Ã, ã
Â, â
Ç, ç
Ê, ê
É, é
Í, í
Ó, ó
Ô, ô
Õ, õ
Ú, ú
À,à  (rarely  used)

EDIT: Revoved î and û ... not used
added à

### Steps To Reproduce

Try to translate the PT.h file with special characters

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX12 / TX12MK2

### Anything else?

no

**Comment by philmoz** [comment]
It looks like this was started at some point;  but never completed.

To support special characters on B&W radios there needs to be image files with the special characters drawn into them.
These are in the radio/src/fonts/std and radio/src/fonts.sqt5 folders.

For PT these would be he font_pt_04x06.png, font_pt_05x07.png, font_pt_08x10.png and font_pt_10x14.png files.
The numbers are the font dimensions in pixels.

The 4x6 font file is empty. The others contain some of the characters you listed; but not all of them.

**Comment by 3djc** [comment]
Think they are in 
![](https://github.com/EdgeTX/edgetx/blob/main/radio/src/fonts/std/font_pt_05x07.png)

but yes, 4x6 is empty

**Comment by zandorsp** [comment]
Yes the font_pt_05x07.png, font_pt_08x10.png are right and contain all needed characters

**Comment by 3djc** [comment]
@zandorsp could you check: https://github.com/EdgeTX/edgetx/pull/4806 ? I think it fixes your issue
