### ISSUE TITLE
Bootloader back drop as home screen background

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#484]
Tx16s
Rc4
When in boot loader the back drop looks cool.
 can it be used as a background?

**Comment by pfeerick** [comment]
This is the image used for the bootloader - it's basically just tiled to fit the fill screen. So you should be able to use it to make your own 480×272 px PNG image, and shove it into /IMAGES/EdgeTX/background.png

https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/bitmaps/480x272/bootloader/bmp_background.png

**Comment by rotorman** [comment]
Here the background in 480x272 pixels:
![EdgeTX splash background](https://user-images.githubusercontent.com/21011587/126865881-ecc508c9-ec42-4e8b-86e3-7020a0dddcd7.png)

**Comment by Mantamatt1** [comment]
Thanks for that. I just couldn't find the image in the sd content

**Comment by Mantamatt1** [comment]
> This is the image used for the bootloader - it's basically just tiled to fit the fill screen. So you should be able to use it to make your own 480×272 px PNG image, and shove it into /IMAGES/EdgeTX/background.png
> 
> https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/bitmaps/480x272/bootloader/bmp_background.png



> Here the background in 480x272 pixels:
> ![EdgeTX splash background](https://user-images.githubusercontent.com/21011587/126865881-ecc508c9-ec42-4e8b-86e3-7020a0dddcd7.png)
> 
> I originally had the idea to match the bootloader background with the startup splash background in PR #262
> Should we go with it?

Yes👍

**Comment by Mantamatt1** [comment]
> This is the image used for the bootloader - it's basically just tiled to fit the fill screen. So you should be able to use it to make your own 480×272 px PNG image, and shove it into /IMAGES/EdgeTX/background.png
> 
> https://github.com/EdgeTX/edgetx/blob/2.4/radio/src/bitmaps/480x272/bootloader/bmp_background.png

Themes/edgetx/background.png

**Comment by pfeerick** [comment]
Argh! sorry, yes, `/THEMES`, not `/IMAGES` ;)
