### ISSUE TITLE
MT12 v2.10.0-rc3 (03Apr24) G(V)9 MIA on DM0 UI

### ISSUE THREAD

**Issue by TodWulff** [EdgeTX/edgetx#4848]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The title says it all.  G(V)9 is missing on DM0 UI.  It is selectable as an operand, and exists on other DM UIs, but is mia on DM0.

### Expected Behavior

For it to be present... ;)

### Steps To Reproduce

Drill down into DM0 and the G9 option for config'g the GV is Missing.

### Version

Other (Please specify below)

### Transmitter

RadioMaster MT12

**Comment by 3djc** [comment]
Affects BW radio with more than 4 trims (so MT12, T20)
