### ISSUE TITLE
Start up splash screen delay conditionally broken

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#4855]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Start up splash screen (including sound file) delay seems to be broken in the latest nightly. Also shutdown theme now defaults to black and not as set - has field or parameters changed for this?

### Expected Behavior

Splash screen (including sound file) delay up to 15s

### Steps To Reproduce

Start up with splash delay entered

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by philmoz** [comment]
It works on my TX16S - what exactly is the problem?

**Comment by pfeerick** [comment]
> Start up splash screen (including sound file) delay seems to be broken in the latest nightly. 

Delay possibly being skipped by starup errors i.e. switch, stick warnings. If there are no startup errors, it waits approx 15 seconds for me. 

> Also shutdown theme now defaults to black and not as set - has field or parameters changed for this?

Confirmed... it no longer follows the theme colours as intended.

**Comment by Kevltan** [comment]
On my previous nightly 2.11 the startup delay would be the set time
regardless of switch positions or warnings - something has changed.
I agree that when there are no active alarms there is the set delay time,
but is this right and why has it changed?
