### ISSUE TITLE
Sd card version warning

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#486]
Tx16s 
#ea48a9c (2001-07-21T18:37:04Z)
I get sd card version warning !
There's no other version for sd card??

**Comment by jogybaer0815** [comment]
just overwrite Version in the edgetx.sdcard.version file

**Comment by raphaelcoeffic** [comment]
> just overwrite Version in the edgetx.sdcard.version file with 2.5V0037

I will remove the version checking soon anyway, we don't need it, IMHO.

**Comment by Mantamatt1** [comment]
Sounds good! To be fair I didnt get the version thing even with otx, i used to just copy the version txt file on to my sd card when I updated the radio firmware.
