### ISSUE TITLE
Radioking  TX18 can not boot after flash 2.10 rc(1, 2, 3) via edgetx buddy

### ISSUE THREAD

**Issue by Curious-r** [EdgeTX/edgetx#4926]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Jumper T18 can not boot after flashed 2.10 rc(1, 2, 3) via edgetx buddy. But if I flash it by bootloader method, it works well. Maybe this has something to do with the changes in the bootloader in 2.10.

### Expected Behavior

Boot normally

### Steps To Reproduce

Flash 2.10rc3 to T18 via edgetx buddy and then boot it.

### Version

Other (Please specify below)

### Transmitter

Jumper T18

### Operating System (OS)

Windows

### OS Version

Windows 11 23H2

**Comment by 3djc** [comment]
Just tested it, working fine here

**Comment by Curious-r** [comment]
@3djc Hello!
Is your radio flashed via edgetx buddy?
In my radio, after press and hold the power button, the led will flash a while and then just stop.

**Comment by 3djc** [comment]
Yes, flashed with buddy

https://github.com/EdgeTX/edgetx/assets/5167938/1c3f9343-f697-4e59-b9f7-e62eaf669b5e

![image](https://github.com/EdgeTX/edgetx/assets/5167938/b3c671e6-3c3e-43d1-b2dc-df5a78c1b266)

**Comment by 3djc** [comment]
Sorry but this radio is not supported, cannot help since we don't have any information or samples of this radio

**Comment by Curious-r** [comment]
![IMG_20240501_193619](https://github.com/EdgeTX/edgetx/assets/19733878/c26731e9-5303-47b4-b13b-42f9c64bf667)
Is this debug port? Maybe I can try with my jlink

**Comment by pfeerick** [comment]
Unfortunately it seems that is only one of the two necessary IOs for SWD. It seems the pad labelled CLK is PA14 (SWCLK), but the one marked IO is PI3, whereas you want PA13 for SWDIO. Just waiting to hear back if that is available somewhere else.

**Comment by pfeerick** [comment]
Actually, it seems like IO is actually SWDIO/PA13, so that should be usable as a SWD header.

**Comment by Curious-r** [comment]
Thanks for help.
I have connected the SWD port to jlink, but there is nothing can be read via jlink CDC UART port currently. I'm checking what went wrong. I'll let you know if I get more information.

**Comment by rotorman** [comment]
You are on the wrong path with UART. Let a debug build run e.g. via Segger Ozone with your J-Link and magic will happen.
