### ISSUE TITLE
weird display on MIXES page (t-pro v2) 2.10 RC3 mismatched 3rd column

### ISSUE THREAD

**Issue by arkarkark** [EdgeTX/edgetx#4928]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I have a model (attached) that when I display the mixes page, as I scroll up and down the wrong values seem to be displayed in the 3rd column. when I have row 1 selected it says "ele ele" on row 2, but if I select row 2 it now says just "ele" and row 1 mysteriously says "ail rud". I think only [a video](https://imgur.com/a/ypcugjf) will do this justice. I tried and it shows in the simulator too.

[model2.yml.txt](https://github.com/EdgeTX/edgetx/files/15103439/model2.yml.txt)

### Expected Behavior

i'm not sure what the 3rd column even. means but I expect it to say the same thing as column 2. so only show ele ele or rud rud. but maybe I'm misunderstanding what it's trying to display?

### Steps To Reproduce

1. in companion start a jumper t-pro v2 profile
2. load the model file I provide
3. start the simulator on my model file
4. goto the mixes page (menu button, then `</>` button 5 times
5. scroll up and down and notice the weird display

this also happen on my jumper t-pro v2 running 2.10 RC3

### Version

Other (Please specify below)

### Transmitter

Jumper T-Pro V2

### Operating System (OS)

macOS

### OS Version

sonoma

### Anything else?

I'm running 2.10 RC3 on both my radio and companion.

**Comment by pfeerick** [comment]
No, it's not a bug, You'd see the same thing if you were running older firmwares. What is happening is simply that there is not enough room to show all information at once. There are at least four of information that could be shown... the mix line name, the mixer source, what switch is used to enable that line, and what flight modes it is active on. the latter two are not present, the line won't change, as that information doesn't need to be shown. If the switch is set, the mix line name will move to the top of the screen, and the switch will be shown in it's place. If the mix line is not active for **all** flight modes, AND a switch is configured, the line will  alternate between showing the switch and the flight modes the mix line is active for, etc. 

![Screenshot 2024-04-25 13:50:02](https://github.com/EdgeTX/edgetx/assets/5500713/a4e0755c-9ee5-40c9-8646-c49070bf4792)

https://github.com/EdgeTX/edgetx/assets/5500713/92fd7c40-6dc2-4879-9e18-c610dc0fadcd

![Screenshot 2024-04-25 13:54:48](https://github.com/EdgeTX/edgetx/assets/5500713/a5aaf533-8b9b-49d2-bef8-5f9315489a32)

https://github.com/EdgeTX/edgetx/assets/5500713/778591a4-16e8-4665-b623-4c1a4c72e05c
