### ISSUE TITLE
Screens Settings: create (setup) a new screen accompanied by flashing

### ISSUE THREAD

**Issue by jogybaer0815** [EdgeTX/edgetx#493]
TX16S - Endeavour (2.4.0) 09a6580

often but not always the creation of a new screen is accompanied by blinking areas that appear to be random.
The blinking (inverting) of different areas also remains while the widgets are selected.
Only when I leave the 'Screen Settings' will the flashing stop.
Unfortunately I have not noticed any regularity, but will continue to monitor the problem.
Best regards

**Comment by gagarinlg** [comment]
Closed, because of the switch to LVGL. If this is happening again, it is a new bug.
