### ISSUE TITLE
Ability to see and select images and audio tracks continously moving up and down the list in all menus (i.e File Manager and Special Functions) 

### ISSUE THREAD

**Issue by Luznatural** [EdgeTX/edgetx#4941]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I normally create Special Functions to play tracks for making the radio announcing me things like: Flight mode cruise, gear up or down, flaps down, touchscreen locked, crow on, etc.
When you try selecting the adequate audio file to create any play track, you can only search alphabetically from the first one to downwards. So, if you want a sound that starts with w (i.e. wpnstr.wav) you have to loose much time going all the way downwards to reach for the file, especially when you have a lot of sounds.
Also happens when using the file manager to sort through them to localize the correct file you like.
Similar issue happens with the images folder, to select any image for your model.

### Describe the solution you'd like

It would be nice if you could also navigate from the first file (starting with a, or 1) upwards to reach immediatelly the last file (starting with z) in counter alphabetically order to reach the one you like.

### Describe alternatives you've considered

1. Selecting images or sounds the screen shows you [..] followed by the first sound starting with 1, or a.
2. If you use your finger or the roller, you can only start moving downwards to reach files, going to b, then c, etc.
3. I you could also move upwards with your finger or the roller, from [..] to reach the files starting with z, then y, etc... you could save a lot of time when selecting the adequate file
4. This movement should be continous: as you reach the last file, you should be able to reach the first one if you continue moving.

**Comment by inventor7777** [comment]
I second this request as a RadioMaster MT12 user.

**Comment by philmoz** [comment]
PR #4867 implements this for the scroll wheel. It will be available when the PR is merged.
Not implemented for touch scrolling yet.

**Comment by philmoz** [comment]
> I second this request as a RadioMaster MT12 user.

B&W radios already do this.

**Comment by pfeerick** [comment]
Unless this has changed, it is already like this on mt12 B/W generally -
this is specific to colorlcd, and should be resolved in a pending PR.
Although it may only apply to roller navigation, as it probably relies on
the rollover.
