### ISSUE TITLE
CPN: flex switches don't seem to be supported at all

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#4950]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Flex switches don't seem to be handled companion side

### Expected Behavior

Flex switch support

### Steps To Reproduce

TX16S with 2,10 RC3
Go to hardware menu
Assign in Pots EXT1 and EXT2 to switch
In Switches, assign FL1 and FL2 to respectively EXT1 and EXT2, define a type (2 or 3 pos)
Create a special function triggered by either FL1 or FL2

With companion, read radio and models, go to check the special functions: empty

### Version

Other (Please specify below)

### Transmitter

RadioMaster TX16S

### Operating System (OS)

macOS

### OS Version

Sonoma

**Comment by elecpower** [comment]
I thought I did have this working in Companion but seems I need to recheck. Could be reading models and settings that is broken.

**Comment by 3djc** [comment]
To save you time, this is my test model

[model2.yml.zip](https://github.com/EdgeTX/edgetx/files/15176240/model2.yml.zip)

**Comment by elecpower** [comment]
@3djc I also need your radio.yml please

**Comment by elecpower** [comment]
Companion has the hardware configuration so on to yaml....

**Comment by 3djc** [comment]
Here you go. Done with  2.10RC3 on a TX16S

[MODELS+RADIO.zip](https://github.com/EdgeTX/edgetx/files/15184634/MODELS%2BRADIO.zip)

**Comment by elecpower** [comment]
Loaded your latest zip and it all looks okay to me. What am I missing?

![hw1](https://github.com/EdgeTX/edgetx/assets/15316949/9755d9ed-13ea-4561-b298-e7b37e321ec8)

![hw2](https://github.com/EdgeTX/edgetx/assets/15316949/dd2e63fb-9298-42cf-84d2-8d8c4586c7cf)

![sfs](https://github.com/EdgeTX/edgetx/assets/15316949/d408e1a8-8796-4144-8bfb-a6a158713b3d)

**Comment by 3djc** [comment]
omg, what an unlikely scenario ! Here is what happened:

- before trying this I was working on companion support for yet unannounced radio (in corresponding branch). Ra dio type was set to this radio
- i switched to 2.10 branch to test the above
- build tx16s libsimu, companion, launched it
- was greated by (to be expected)
![image](https://github.com/EdgeTX/edgetx/assets/5167938/5cccdc2a-51f2-4ec5-b2bb-0fb2a20815aa)
- then downloaded model and settings, and look two things: SF are missing, and title bar says TX16S
![image](https://github.com/EdgeTX/edgetx/assets/5167938/2ce0071d-1360-4214-9a82-c79963e179c5)
- but I did find out that I also have this
![image](https://github.com/EdgeTX/edgetx/assets/5167938/c0b2c1da-597f-4233-a7ac-5bef389ba2c9)

After selecting the TX16s as radio model, it does indeed work
![image](https://github.com/EdgeTX/edgetx/assets/5167938/6fa58ae0-6244-417a-b169-47da0b9a4d02)

**Comment by 3djc** [comment]
So conclusion reported work did not exist, a different (much smaller, and only affecting developers) issue exists

**Comment by pfeerick** [comment]
> So conclusion, reported issue did not exist, a different (much smaller, and only affecting developers) issue exists

Not just developers... Neil has mentioned in the past that if a radio doesn't exist, for historical reasons Companion falls back to assuming TX16S... we're just unlucky enough to encounter it more often (and not read the instructions in bold).

**Comment by 3djc** [comment]
I did, but since the title bar said TX16S, which is what I wanted anyway, I assumed that it defaulted to TX16S.  Ideally, it should be either blank, or show what it defaulted to. But a minor thing I agree

**Comment by elecpower** [comment]
I'll see what I can do to improve.
However when you use an app in bleeding edge mode you have to expect things to go pear shaped from time to time 🤣

**Comment by 3djc** [comment]
> I'll see what I can do to improve. However when you use an app in bleeding edge mode you have to expect things to go pear shaped from time to time 🤣

Couldn't agree more, and clearly RTFIIB should also apply to me !!!!

**Comment by pfeerick** [comment]
It is clearly trying to confuse and befuddle... and has succeeded on more than one occasion! :hand_over_mouth: 

Even if you add a flashing neon light... I guarantee you'll me complaining about this again also :zany_face: 

Maybe make it fall back to a definite UNKNOWN_BOARD type state, if not going to basically hard fail till the user provides sensible input? :innocent:
