### ISSUE TITLE
The center position of the S1 button on the screen does not correspond to its actual center

### ISSUE THREAD

**Issue by pierrotm777** [EdgeTX/edgetx#4961]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The center position of the S1 button on the screen does not correspond to its actual center.
Even if I use the control setting menu, the center is shifted on the screen.

I use 2.10 RC3 version !!!

### Expected Behavior

Correct this difference between position of the S1 button and that on the screen

### Steps To Reproduce

Always

### Version

Other

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

![20240503_110417](https://github.com/EdgeTX/edgetx/assets/8189970/09f7cfbb-c239-45d7-91ad-933af050218f)

**Comment by pfeerick** [comment]
So you did Radio Settings -> Hardware -> Calibration, and you centred the pots, sliders and sticks, and then moved them full range, as prompted?

**Comment by rotorman** [comment]
Also check if Pot with detent is checked, or just Pot, as with just Pot, only 2 end positions are used for calibration and with Pot with detent, 3 positions - ends and center.

**Comment by pfeerick** [comment]
Radio Settings => Hardware => Pots

**Comment by pierrotm777** [comment]
I have tried to use Calibration with the same result, the index isn't centred.

**Comment by pierrotm777** [comment]
Sorry for this delay.
These are my models.
[MODELS.zip](https://github.com/EdgeTX/edgetx/files/15209182/MODELS.zip)

**Comment by 3djc** [comment]
and RADIO ?

**Comment by pierrotm777** [comment]
TX16S MKII

**Comment by 3djc** [comment]
RADIO folder please

**Comment by pierrotm777** [comment]
[RADIO.zip](https://github.com/EdgeTX/edgetx/files/15209215/RADIO.zip)
I had found that 3 models was in 2.11.0 but i use the 2.10.0 RC3 firmware.
model31.yml
model23.yml
model21.yml

**Comment by 3djc** [comment]
Just to be sure, on what model are you seen it ?

**Comment by 3djc** [comment]
I think you are not calibrating correctly.
I loaded your fiels and I had the issue
Redid calibration, worked fine

You need to ensure your center pots and slider when displaying "Center stick...."
and move them all to both extremes when displaying "Move axis..."

**Comment by pierrotm777** [comment]
I use S1 for change the VOLUME.
So i had defined a Global Function
![image](https://github.com/EdgeTX/edgetx/assets/8189970/27ec8835-2809-4e08-9580-b7fb69019bad)

**Comment by 3djc** [comment]
Please read my message above, you are likely not calibrating correctly

**Comment by pierrotm777** [comment]
Ok, my tx16s battery is empty :-(.
I try that as soon as possible

**Comment by pierrotm777** [comment]
I had used the calibration incorrectly.
It's now ok :-(

Thanks for your help !!!

Pierre
