### ISSUE TITLE
Switch indicator location on b/w displays

### ISSUE THREAD

**Issue by Camo55** [EdgeTX/edgetx#4975]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Misaligned arrows

### Describe the solution you'd like

![20240505_100857](https://github.com/EdgeTX/edgetx/assets/17286162/0849f7de-c9c9-4065-910e-0c635c514866)

### Describe alternatives you've considered

Leaving it alone / using maximum 2 letters for switch name

**Comment by philmoz** [comment]
The arrows are always displayed immediately to the right of the name so this is not going to change.

PR #4976 adjusts the switch label position so it will fit long names.

**Comment by Camo55** [comment]
Center-justified text will work
