### ISSUE TITLE
Companion Telemetry Simulator does not support ELRS/CRSF Telemetry

### ISSUE THREAD

**Issue by icebreaker-ch** [EdgeTX/edgetx#4983]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

I am using a Radiomaster 2.4 GHz ELRS-Module and a Radiomaster ER8GV Receiver having a Vario).
I was not able, to simulate telemetry values for this configuration.
Screenshots of the Telemetry page of the Transmitter and the Telemetry Simulator screen are  attached in this report. It seems, that the Telemtry Simulator is limited to FrSky Telemetry values. ELRS uses the Crossfire protocol and all telemetry values appear as "Custom" on the Radio.
![Telemetry-Screen](https://github.com/EdgeTX/edgetx/assets/3645375/ea668f76-d5d1-4c8f-976a-440e228cb00d)
![Telementry-Simulator](https://github.com/EdgeTX/edgetx/assets/3645375/a5fd6c90-8ea5-4e05-bf81-551456657f73)

### Expected Behavior

I would like to have possibility, to configure custom sensors for the Telemetry Simulator or some kind od automatic recognition of the telemetry values.

### Steps To Reproduce

- Configure a radio for an ELRS receiver
- Discover all sensors
- Save configuration to Companion
- Start a Simulation
- Modify Values (e.g. Vario Alt)
Sensors do not match the ones in the radio

### Version

2.9.4

### Transmitter

FrSky X12

### Operating System (OS)

Linux

### OS Version

LMDE 6 Faye

**Comment by elecpower** [comment]
also refer #3047

**Comment by 3djc** [comment]
Same can be said to any non FRSKY telemetry (Spektrum, HoTT,....)

**Comment by rotorman** [comment]
https://edgetx.org/contest_crsf_telem_simulation/
