### ISSUE TITLE
Improve customisable switches with automatic "source "

### ISSUE THREAD

**Issue by 3djc** [EdgeTX/edgetx#4989]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently, customisable switches are only switches, and if you want say have it work like a 6POS, it does create a lot of work

### Describe the solution you'd like

Creation of 3 sources (GR1 to GR3) that match the customisable switches groups
Those source will be managed by the system without user intervention.
They will range from -100 to 100 with as many steps as there are switches in the group. If 0 switches in group, then source value is set to 0

If you have model default, all customisable switches are in group 1 and "always on' not enable, you will have
GR1: -100 to 100 in 7 steps
GR2: always 0
GR3: always 0

If you have model default, all customisable switches are in group 1 and "always on' enabled, you will have
GR1: -100 to 100 in 6 steps
GR2: always 0
GR3: always 0

If you have 4 switches in group1 and 2 in group 2 and both groups "always on" disabled:
GR1: -100 to 100 in 5 steps (all off = -100, sw1 = -50, sw2 = 0 , sw3 = 50, sw4 = 100)
GR2 : -100 to 100 in 3 steps (both off = -100, sw5 = 0, sw6 = 100) 
GR3: always 0

If you have 4 switches in group1 and 2 in group 2 and group 1 "always on" enabled:
GR1: -100 to 100 in 4 steps (sw1 = -100, sw2 = -33 , sw3 = 33, sw4 = 100)
GR2 : -100 to 100 in 3 steps (both off = -100, sw5 = 0, sw6 = 100) 
GR3: always 0
### Describe alternatives you've considered

Use SF like today

**Comment by philmoz** [comment]
Sounds good.

Although if the group is set to always on then you would get one less step as you can't turn off all the switches in the group.

**Comment by pfeerick** [comment]
That's what I'm hoping will happen here... in using this I would want this to simply replace a 6POS properly, so only 6 positions, not 7! :rofl:

**Comment by 3djc** [comment]
> That's what I'm hoping will happen here... in using this I would want this to simply replace a 6POS properly, so only 6 positions, not 7! 🤣

yes, simply declare group1 always on, and remember also to set your start position either to remember or decide and initial position

**Comment by CapnBry** [comment]
You magnificent son of a bic. Just got the T15 and thought, man this functional switch groups 6POS is so amazing and so close to perfect but all I need is a GRPx source that behaves **exactly** like you've described. I was browsing the code here trying to figure out where it would need to go and was confused how it already seemed to exist, then the `git blame` lead me here.

A-mazing, everyone is going to be begging for more handsets with hardware that supports this.

**Comment by pfeerick** [comment]
> A-mazing, everyone is going to be begging for more handsets with hardware that supports this.

1000% agree... this was really the missing piece since customisation switches were first added... i.e. how to make them make them act like a traditional 6POS without a gazillion mixer lines, logical switches, etc, if you *don't* want the extra functionality offered. It will be disappointing if future radios designs that have a 6POS button implementation don't come with customisation switches as standard, now that this pain point is gone - and in point of fact is far superior to that since you could quite easily have two 3POS, three 2POS switches just by grouping them how you want them!

**Comment by 3djc** [comment]
You can even have two 4POS since groups don't have to be always on

**Comment by 3djc** [comment]
Next step is user controlled led color when using ws2812, but it is a UI chalenge :)
