### ISSUE TITLE
EdgeTx 2.10 TARANIS X9E strange input source list and data corrupted

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#5000]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Upgrading Taranis X9E from 2.9.4 to 2.10 data models became corrupted, input source list show partial and wrong list
same behavior in Companion radio simulation also starting with new model

### Expected Behavior

By updating the firmware the models data must not be corrupted and in source input list all input must be showed correctly
In radio and in companion radio simulation also

### Steps To Reproduce

Upgrade firmware from 2.9.4 to 2.10
use companion simulator
go to input or mixer menu and choose an input source

### Version

Other (Please specify below)

### Transmitter

FrSky X9E / X9E Hall

### Operating System (OS)

Linux

### OS Version

Linux Mint 20

**Comment by 3djc** [comment]
Confirmed, affects all 212 radio in some way

**Comment by MicheleVilla** [comment]
Please check also the custom screen display visualization
sometimes number cover the string description

**Comment by 3djc** [comment]
I found an issue, but I'm not too sure it is the one you mentioned, since your description lacks precision.

If there are other issues, please open separate issues, and please include screenshot or photo, so we can see exactly what you are referring too

**Comment by 3djc** [comment]
Could you check this fixes fixes the issue you found ?

[X9E-TEST-5000.zip](https://github.com/EdgeTX/edgetx/files/15305048/X9E-TEST-5000.zip)

**Comment by MicheleVilla** [comment]
Tested
it work but apparently LR seems to be swapped with S2 and LS with S1

**Comment by pfeerick** [comment]
TR# are trainer channels
