### ISSUE TITLE
MT12 - Telemetry Screen of Type "Values" has too much fields

### ISSUE THREAD

**Issue by jasc76** [EdgeTX/edgetx#5003]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When choosing values as telemetry screen there are 8 slots, but radio only has 6 slots (2 columns, 3 rows)

### Expected Behavior

Reduce number of fields in config dialog

### Steps To Reproduce

Configure a telemetry screen
last row of values is not shown

### Version

Other (Please specify below)

### Transmitter

RadioMaster MT12

### Operating System (OS)

Windows

### OS Version

2.10

**Comment by pfeerick** [comment]
7th and 8th telem screen items are shown on the bottom row, like pictured
on https://manual.edgetx.org/bw-radios/model-select/display
