### ISSUE TITLE
EdgeTx 2.10 Taranis X9E F3 F4 missing in Hardware configuration

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#5006]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In hardware configuration menu F3 and F4 Pot Input have disappeared while they are physically present on the PCB

### Expected Behavior

F3 and F4 must be visualized in Hardware Menu

### Steps To Reproduce

Go to Hardware menu by long press key Menu
check if F3 anf F4 Pot are visualized

### Version

Other (Please specify below)

### Transmitter

FrSky X9E / X9E Hall

### Operating System (OS)

Linux

### Anything else?

![screenshot_x9e_24-05-14_20-16-58](https://github.com/EdgeTX/edgetx/assets/6508436/b1549be2-ff8b-40a6-acaa-16334bc974ac)

**Comment by pfeerick** [comment]
Also in Companion, so may simply be the hwdef that is missing entries.

![image](https://github.com/EdgeTX/edgetx/assets/5500713/d9f6770b-351b-4e83-88c3-1eb69d1870c6)
![image](https://github.com/EdgeTX/edgetx/assets/5500713/4a101d8e-ba92-40ba-934c-84ff307f3998)

**Comment by MicheleVilla** [comment]
as I have already had the opportunity to point out when I choose an input by moving the slider LR displays S2 and LS displays S1
By installing 2.10 the programs already present show malfunctions regarding these definitions
This can be seen using the radio
Could it be a HARDWARE DEFINITION problem (or only my problem)?

**Comment by MicheleVilla** [comment]
> And I told you to open another issue. Adding issues in comments is the best way to get those NOT sorted.
> 
> Anyhow, could you try this: [X9E-TEST-5006.zip](https://github.com/EdgeTX/edgetx/files/15317594/X9E-TEST-5006.zip)
I thought it was related to this issue, for the future I will open a new issue for every single problem as you suggest
I will test your solution this evening

Thank you

**Comment by 3djc** [comment]
[X9E-TEST-5006-2.zip](https://github.com/EdgeTX/edgetx/files/15317756/X9E-TEST-5006-2.zip)
