### ISSUE TITLE
Companion - Pots Settings not saving

### ISSUE THREAD

**Issue by TheIsotopes** [EdgeTX/edgetx#5018]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

With the current release, the pots settings are not saved in the Companion.

### Expected Behavior

save settings correctly

### Steps To Reproduce

- load Settings from PC
- Edit Radio Settings / Hardware
- set Pots S1/S2 to None
- save Settings
- close Companion
- open again Companion
- load Settings from PC
- back to Edit Radio Settings / Hardware
- you will see the Pots enabled again

### Version

2.10.0

### Transmitter

RadioMaster Zorro

### Operating System (OS)

Windows

### OS Version

11 23H2

**Comment by elecpower** [comment]
The hardware definition default value is used if not found in radio settings.
The same issue exists for switches.
In both case, should set to None.
