### ISSUE TITLE
Ransomware Alert

### ISSUE THREAD

**Issue by orstratcat** [EdgeTX/edgetx#5032]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Malwarebytes alerts to Companion 2.10.0 exe as Malware.
[MalwareRansom Detection.odt](https://github.com/EdgeTX/edgetx/files/15366001/MalwareRansom.Detection.odt)
Ransom.Agent.Generic

### Expected Behavior

Malwarebytes deletes EDGETX.exe file and logs the file as Malware.Ransom.Agent.Generic
Downloaded from GITHUB

### Steps To Reproduce

Click on edgetx shortcut Icon

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

win11

### Anything else?

[MalwareRansom Detection.odt](https://github.com/EdgeTX/edgetx/files/15366026/MalwareRansom.Detection.odt)

**Comment by 3djc** [comment]
Duplicate #5033
