### ISSUE TITLE
Companion opening some OpenTX dot bin files crashes the application

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#5034]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

The issue manifests itself when the current radio profile's associated hardware definition has more features than those supported in the bin file trying to be opened.

### Expected Behavior

Application opens file

### Steps To Reproduce

Try to open a bin file

### Version

2.10.0

### Transmitter

Other (Please specify below)

### Operating System (OS)

Linux, macOS, Windows

### OS Version

All

### Anything else?

When reading binary files the code loops through every radio type attempting to find a supported radio and decodes the whole file  for each tested radio type.
The ADC refactor changed hardware definitions from static to dynamic and this old looping behaviour is not triggering loading of the loop's current radio hardware definition.
The result is the current radio profile hardware definition is being used as the reference. Therefore if the profile hardware has more features eg pots than supported in the bin file radio type an array out of bounds condition occurs and the application crashes.

**Comment by 3djc** [comment]
If users are blocked by this issue trying to Otx eeprom file to version 2.10, they can use Companion 2.9.4 to convert the eeprom, save etx file, and then open that etx file with Companion 2.10 until this gets resolved
