### ISSUE TITLE
Flysky digital hall gimbals on NV14 not working with centurion

### ISSUE THREAD

**Issue by brocciu** [EdgeTX/edgetx#5057]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

hall gimbals on NV14 not working

### Expected Behavior

hall gimbals working

### Steps To Reproduce

flash from old firmware, 

### Version

2.10.0

### Transmitter

Flysky NV14

**Comment by 3djc** [comment]
Have you recalibrated?

**Comment by brocciu** [comment]
sorry, it is all good now
