### ISSUE TITLE
LABEL extra word added

### ISSUE THREAD

**Issue by oldnansome** [EdgeTX/edgetx#5071]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Updated RM TX16 to Centurion. Also updated 4 in 1 module.
On the Manage Models Page  The Listing reads: Favorites, Int Mod, ELRS Mod and Unlabeled. I f tick the ELRS MOD label i get the word AND added to Int Mod title, if i touch on Int Mod the extra word disappears but then reappears when checking ELRS MOD.
I tried deleting then adding label but no change. In addition if I move the ELRS MOD label up the extra word appears on checking it but the repositioned Int Mod does not.

### Expected Behavior

Aside from the check tick appearing not having the extra word

### Steps To Reproduce

Just turn on TX and go to Manage Models

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

![1000002594](https://github.com/EdgeTX/edgetx/assets/117780440/c718025e-30e7-4730-9a9c-17e202317741)

**Comment by pfeerick** [comment]
This is related to the UI appending "AND" to show which labels are active when you are in multi-label mode (i.e. as configured in Radio Settings -> Radio Setup -> Manage Models. i.e. in your screenshot manage models is trying to show models are are labled INTERNAL MODULE **AND** ELRS MOD. #5073 should make this look better - i.e. as shown in the screenshot there.
