### ISSUE TITLE
Decompress failed when to process updates for firmware ("固件类型") in Simplified Chinese ("简体中文")

### ISSUE THREAD

**Issue by michael080808** [EdgeTX/edgetx#5076]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When I set menu language to "Simplified Chinese" and do "Process Updates", firmware can not be decompressed.
![image](https://github.com/EdgeTX/edgetx/assets/17961659/b33d657f-affc-4b0e-99f2-f55adc3f8442)
However when I set menu languate to "American English" and do "Process Updates", firmware update processes well.
![image](https://github.com/EdgeTX/edgetx/assets/17961659/b9519f37-c72c-4a40-a253-bb695023c9e1)
I guess that there are some path setting bugs with "Simplified Chinese" and some other languages.
![image](https://github.com/EdgeTX/edgetx/assets/17961659/92a662ea-43df-47e0-84db-76d7278adf9d)
As shown above, it seems when use "Simplified Chinese", Companion would create a "固件类型" folder to download
and to found "zip" file in "Firmware" Folder.

### Expected Behavior

Companion can process update normally.

### Steps To Reproduce

1. Make sure the `EdgeTX/downloads/Firmware` folder is deleted. (In my case is `C:\Users\<USERNAME>\Documents\EdgeTX\downloads\Firmware`)
3. Set menu language to "Simplified Chinese" ("简体中文")
4. Restart Companion
5. Process Updates and select "Firmware" ("固件类型”) and proceed update.

### Version

3.10.0

### Transmitter

FrSky X9D+

### Operating System (OS)

Windows

### OS Version

Windows 11 23H2 22631.3593

**Comment by elecpower** [comment]
The translated component name does not always generate a valid folder name
