### ISSUE TITLE
Switches G and H displayed on Zorro Monitor page wrongly 2.10

### ISSUE THREAD

**Issue by AlexandruIspas89** [EdgeTX/edgetx#5084]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

I just upgraded to Edge TX 2.10 from 2.94 and I have 2 radios so i could instantly compare and spot the bug. I observed that the monitor switches/gimbals page now shows G and H switches also but since the screen is small the graphics cannot display proper and it looks weird. 
![Bug](https://github.com/EdgeTX/edgetx/assets/6001930/8b560ad8-65f5-4f68-ae9e-c1af59756922)
![Compare](https://github.com/EdgeTX/edgetx/assets/6001930/ce8006a0-8450-498d-98c2-a2a69ceb3d1d)

Also companion 2.10 shows the same issue:
![Companion](https://github.com/EdgeTX/edgetx/assets/6001930/dbb6ce66-c8df-45a0-ae5a-e2e0c44df723)

### Expected Behavior

Either adjust the graphics to make these 2 switches fit or remove them like before

![expected](https://github.com/EdgeTX/edgetx/assets/6001930/f9b722b3-31a8-486d-aa4b-4b1eb2111353)

### Steps To Reproduce

Power up the radio with 2.10 and go to the monitor switches screen. 

### Version

2.10.0

### Transmitter

RadioMaster Zorro

### Operating System (OS)

Windows

### OS Version

2.10

**Comment by pfeerick** [comment]
This has been fixed already through #4997, and will be released in a few
days in 2.10.1
