### ISSUE TITLE
Stick, Pot, and Trim names are missing from pop-up lists (TX16s Mk2 2.10)

### ISSUE THREAD

**Issue by HippoDan** [EdgeTX/edgetx#5085]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

When selecting an input, a pot, or a trim switch, many of the items appear in the list with no names, and are impossible to tell apart.  For some reason T5 and T6 still have names.

### Expected Behavior

Selectable lists of inputs should show either the names given to them, or the default names.  (Trim switches don't seem to be nameable.)

### Steps To Reproduce

In the model editing pages, choose a source for throttle, or a trim switch for same.  Same problem on mixer pages.

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

macOS

### Anything else?

![Screen Shot 2024-05-29 at 4 50 49 PM](https://github.com/EdgeTX/edgetx/assets/33069267/ee692e14-6be8-4b68-a0a4-4f36d97a5e38)
![Screen Shot 2024-05-29 at 5 01 14 PM](https://github.com/EdgeTX/edgetx/assets/33069267/4b7a257a-77dd-4cd1-bd69-dd6641e9411b)
![Screen Shot 2024-05-29 at 4 51 03 PM](https://github.com/EdgeTX/edgetx/assets/33069267/3bf3c0de-5116-41cf-b434-8ef6cf0cef86)

**Comment by pfeerick** [comment]
Check your Radio Settings -> Hardware -> Pots configuration - the names are probably spaces `   ` instead of blank `---`.

**Comment by HippoDan** [comment]
Thanks, that was it. I see the trims took the names of the sticks they were near. Is there any way to get them to show up with their correct numbers?

Either way, I think this problem can be marked as solved.

**Comment by pfeerick** [comment]
I don't think so, no. The four next to the sticks take on the name of the axis/stick they normally configure, and the remainder keep their stock/factory numbering since they don't belong to any particular axis.
