### ISSUE TITLE
getFieldInfo() does not return info for switchs

### ISSUE THREAD

**Issue by offer-shmuely** [EdgeTX/edgetx#5100]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

si = getFieldInfo(131) -- 131==SF
si is returned as nil

### Expected Behavior

si = getFieldInfo(131) -- 131==SF
si have the info of the switch, especially it's name
l

### Steps To Reproduce

run the following code on 2.10 show the problem
running it on 2.9, no issue

    local swi = getFieldInfo(wgt.options.switch1)
    if swi ~= nil then
        local txt = string.format("switch id: %s, name: %s", wgt.options.switch1, swi.name)
        lcd.drawText(10,10, txt)
    else
        local txt = string.format("switch id: %s, getFieldInfo returned nil", wgt.options.switch1)
        lcd.drawText(10,10, txt)
    end

### Version

2.10.0

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?
attach a widget that simulate the issue:
[main.lua.txt](https://github.com/user-attachments/files/15522966/main.lua.txt)
[WIDGETS.ZIP](https://github.com/user-attachments/files/15522972/WIDGETS.ZIP)

**Comment by pfeerick** [comment]
Thanks for including the widget, made testing the PR for this quick and easy, and hopefully helped debugging the issue also
