### ISSUE TITLE
Boxer and Zorro: Missing spaces, letters are overlapped in certain places

### ISSUE THREAD

**Issue by bernd25** [EdgeTX/edgetx#5106]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In some menus e.g. in Logical switches I add the following parameters:  
a=x TPWR  7mW
Back in the list it looks like this "a=x TPWF7mW", whereby the 'R' is no longer recognizable as such.  It could also be an 'F'.
In other cases a letter disappear completely. 

![Boxer LS menu](https://github.com/EdgeTX/edgetx/assets/105021446/437fccec-89e5-428a-82d5-842e293da80b)

### Expected Behavior

In the LS list it should look like:
a=x TPWR 7mW
as in older versions prior v. 2.30.0 

### Steps To Reproduce

Add a logical switch with same parameters and switch back to the list.

### Version

2.10.1

### Transmitter

RadioMaster Boxer

### Anything else?

Due to the lack of spaces, some menus are almost unreadable. 
This applies equally to RM Boxer and Zorro.

**Comment by philmoz** [comment]
2.9 did not show the source type symbol at the start of the name.
![screenshot_x7_24-06-02_20-21-59](https://github.com/EdgeTX/edgetx/assets/9474356/615432c1-fa4b-4388-868d-3737809a0860)

Due to the limited space we should probably remove the source type symbol to avoid overlap.

**Comment by pfeerick** [comment]
Indeed... only enough space for 4 characters there...
