### ISSUE TITLE
GF not displayed

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#512]
Global Functions are not displayed/shown on the Global Functions screen.

**To Reproduce**
Radio Settings->GF. Create a new GF, Go back. The screen does not show a new function.

**Expected behavior**
New function should be visible

**General information**
 - EdgeTX version: current code
 - Hardware NV14

**Comment by eshifri** [comment]
The problem is due to non-accessible ON switch

**Comment by pfeerick** [comment]
"non-accessible"? Is there something other than the "---" that triggers this?

**Comment by eshifri** [comment]
Yes: all switches are displayed, but the list is not scrollable.

**Comment by pfeerick** [comment]
ouch! :laughing:
