### ISSUE TITLE
Models transfer looses settings moving from OpenTX to EdgeTX

### ISSUE THREAD

**Issue by jtapernoux** [EdgeTX/edgetx#5126]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

I have migrated my Jumper T16 from OpenTX to Edge TX.  I converted my model.otx file using EdgeTX Companion to a model.etx file, and loaded it on the transmitter.  Models are there now, but several settings in the Logical Switches and Special Functions pages are either missing or have different values.  Is this expected, and I have to manually make corrections, or have I followed a procedure incorrectly?
Thanks,
John

### Expected Behavior

I did not expect to find missing or altered values in my model files.

### Steps To Reproduce

load model.otx into edgetx companion, then save as model.etx, then load model.etx to transmitter

### Version

2.10.1

### Transmitter

Jumper T16

### Operating System (OS)

Windows

### OS Version

Windows 11

### Anything else?

Tried the same thing using a Radioking TX18S, with the same results.

**Comment by pfeerick** [comment]
Can you upload the OTX file so we can see what is going on? That is basically the expected process... i.e. load OTX file with EdgeTX Companion, let Companion do it's conversion changes, etc.  Generally, Companion should be able to convert everything over, but sometimes not everything is able to be converted over automatically... don't think there is anything in logical switches that should be a problem there, so probably a bug.

**Comment by jtapernoux** [comment]
Thanks Peter, I’ll upload the file.  I’ll point out a couple settings that converted wrong.JohnSent from my iPadOn Jun 4, 2024, at 5:45 PM, Peter Feerick ***@***.***> wrote:﻿
Can you upload the OTX file so we can see what is going on? That is basically the expected process... i.e. load OTX file with EdgeTX Companion, let Companion do it's conversion changes, etc.  Generally, Companion should be able to convert everything over, but sometimes not everything is able to be converted over automatically... don't think there is anything in logical switches that should be a problem there, so probably a bug.

**Comment by jtapernoux** [comment]
Not finding where I can upload the OTX file...

**Comment by jtapernoux** [comment]
ETX File "Models OpenTX 24-06-03" model "Spitfire":   L01 missing "And Switch: 6P_6", L02 missing "V2: 6P_5
                                                                                                                 SF1 and SF2 completely blank, also involving 6P_6 and 6P_5
ETX File "Models EdgeTX May, Active" model "Spitfire":  Special Functions "Repeat Value" changed from "No Repeat" to "Repeat 1S"


________________________________

**Comment by 3djc** [comment]
Try transfering using EdgeTX companion 2.9.4 first, save to .etx, open then etx with EdgeTX companion 2.10, it should be better

**Comment by pfeerick** [comment]
With a zip file extension, you should be able to upload it using this option ;)

![image](https://github.com/EdgeTX/edgetx/assets/5500713/f923bde6-755f-41c6-a8cc-bfa3975bac37)

**Comment by elecpower** [comment]
I would appreciate getting a copy of the otx to see what I missed.

**Comment by jtapernoux** [comment]
[Models EdgeTX May, Active.zip](https://github.com/user-attachments/files/15592405/Models.EdgeTX.May.Active.zip)

**Comment by jtapernoux** [comment]
Hi,
Using Edge Companion 2.9 to convert OTX to ETX, then Edge Companion 2.10 to load radio worked!  I had to enable the 6 position switches in the hardware calibration menu too.
Thanks!!!

**Comment by elecpower** [comment]
Thank you for uploading the files. Checked and confirmed the 6 position switch does not convert from otx.

**Comment by elecpower** [comment]
What was the sequence to change the No Repeat to Repeat 1S as it is not altered in the otx conversion?
PS fix for multi position switch awaiting approval and merging
