### ISSUE TITLE
Bootloader not seeing .bin files in firmware folder on SD card

### ISSUE THREAD

**Issue by AlanP10** [EdgeTX/edgetx#5127]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Attempting to upgrade Taranis x9d plus from EdgeTx 2.9.4 to 2.10.1
Upgrade the bootloader to 2.10.1
Enter the bootloader by powering on with trims selected, 'Edge TX Bootloader - v2.10.1' is displayed on top line.
Select 'Write Firmware' the TX displays 'Directory is empty' even though there are bin files in the folder.
There is no way to select the required bin file

### Expected Behavior

The bootloader should display the .bin files in the FIRMWARE folder on the SD card.
This works on 2.9.4 

### Steps To Reproduce

1. Copy x9dp-839b60f.bin file to the FIRMWARE folder on SD card using PC
2. Disconnect PC 
3. Navigate to the FIRMWARE folder on the SD CARD using the TX menu
4. Select x9dp-839b60f.bin file and flash bootloader
5. Start-up TX in bootloader using trims.
6. Select 'Write Firmware' the TX displays 'Directory is empty'

### Version

2.10.1

### Transmitter

FrSky X9D+

### Anything else?

![IMG2-10-1](https://github.com/EdgeTX/edgetx/assets/70864491/0b87c7eb-197b-42d3-a21b-9698438290c0)
![IMG2-9-4](https://github.com/EdgeTX/edgetx/assets/70864491/662594f4-5d80-4c70-8278-2f923c249bfe)

**Comment by 3djc** [comment]
Have you tried another sd card ? Some cards that where compatible with 2.9 are not compatible with 2.10 (and vice versa)

**Comment by AlanP10** [comment]
Changing to another SD card has fixed the problem.
The SD card fitted was a 1GB card FAT format which probably came with the TX.
I have changed to a 2GB card FAT format which works fine.
Having loaded 2.10.1 on the TX if you go back to the original SD card then it displays 'No SD card' at power up.
