### ISSUE TITLE
Using the " symbol in model name causing SD card error when enabling SD logging.

### ISSUE THREAD

**Issue by Woofie1010** [EdgeTX/edgetx#5128]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

While using a model name: Laser V3 67" I receive an SD card error message when logging the flight. After removing the " symbol the SD card error did not happen.

### Expected Behavior

If the symbol is not aloud it should not be a possibility. 

### Steps To Reproduce

1.Put the symbol " in the model name. 2. Enable SD Loggin in special functions

### Version

2.10.1

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
While it can't be entered from the colorlcd radio keyboard, I think `"` was supposed to be an allowed character. #4670 verifies that only valid characters are permitted in model and label names when entered via Companion, so we either need to drop it from the list of valid characters, or hunt down why this happening.

**Comment by philmoz** [comment]
Double quote is an allowed character in the model name on the radio.
It is not an allowed character in a filename - the logs code is trying to create a file using the model name so the file create fails.

Replacing the double quote with an underscore in the log filename fixes it.

**Comment by pfeerick** [comment]
>  the logs code is trying to create a file using the model name so the file create fails.

ouch... it needs to be restricted to only valid file-system characters then!!

**Comment by Woofie1010** [comment]
Peter, Thanks for the update. I will not be using the " symbol in a model name.
Dave
    On Wednesday, June 5, 2024 at 07:01:23 PM CDT, Peter Feerick ***@***.***> wrote:  
 
 


While it can't be entered from the colorlcd radio keyboard, I think " was supposed to be an allowed character. #4670 verifies that only valid characters are permitted in model and label names when entered via Companion, so we either need to drop it from the list of valid characters, or hunt down why this happening.

**Comment by Woofie1010** [comment]
Thanks for the update. I will not be using the " symbol in a model name.
Dave

    On Wednesday, June 5, 2024 at 07:18:27 PM CDT, philmoz ***@***.***> wrote:  
 
 


Double quote is an allowed character in the model name on the radio.
It is not an allowed character in a filename - the logs code is trying to create a file using the model name so the file create fails.

Replacing the double quote with an underscore in the log filename fixes it.

**Comment by pfeerick** [comment]
No problem. It shouldn't be an issue as of 2.10.2 or later though.

**Comment by Woofie1010** [comment]
Peter,
Big thanks to you and the team for your work. 
I love this stuff.Dave
    On Thursday, June 6, 2024 at 07:18:02 PM CDT, Peter Feerick ***@***.***> wrote:  
 
 


No problem. It shouldn't be an issue as of 2.10.2 or later though.
