### ISSUE TITLE
Add 0.5 second power off delay.

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#5133]
### Discussed in https://github.com/EdgeTX/edgetx/discussions/5130

<div type='discussions-op-text'>

<sup>Originally posted by **inventor7777** June  6, 2024</sup>
Hi all! (Again)

When you select a power off delay in EdgeTX, you have the options for 1s and up. However, an option would be really nice for 0.5 seconds (nice balance between accidentally turning it off and having to wait for a whole second before shutdown). 

_One unrelated thing: when I have a feature request do I put it in Issues-Feature Request or here in Discussions? What changes between both options?_</div>

**Comment by inventor7777** [comment]
Thank you :)
