### ISSUE TITLE
Companion 2.10.1 - Profile conversion broken

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#5137]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Attempting to import my DLG6S template using Companion 2.10.1. The template was designed for X9D, importing into Zorro profile.  It worked fine in 2.9, now the process is broken.
Problems:
1. The Radio settings > Hardware tab is overwritten with X9D switch definitions which are not relevant to the Zorro.
2. The conversion messages contain several irrelevant and confusing messages as a result of (1) above.

![2024-06-08_161652](https://github.com/EdgeTX/edgetx/assets/6317479/c4316206-cc71-4152-9e4c-b14f5e22dc09)
![2024-06-08_161554](https://github.com/EdgeTX/edgetx/assets/6317479/65b40b60-7eea-40de-bf83-ea2e35c916c9)

### Expected Behavior

Works correctly in Companion 2.9 - the switch definitions for the Zorro profile are preserved, and the single error message is meaningful.
![2024-06-08_161515](https://github.com/EdgeTX/edgetx/assets/6317479/1a98c98f-fe9a-43e4-ab62-266a16265669)
![2024-06-08_161453](https://github.com/EdgeTX/edgetx/assets/6317479/036a207b-d94e-4a27-a27a-082b55fcc73b)

### Steps To Reproduce

Import the DLG6S template (attached) into Companion 2.10.1
[DLG6S_200.otx.txt](https://github.com/user-attachments/files/15748651/DLG6S_200.otx.txt)

### Version

2.10.1

### Transmitter

RadioMaster Zorro

### Operating System (OS)

Windows

### Anything else?

Critical issue for my sailplane templates.

**Comment by elecpower** [comment]
Many thanks for the file. I will have a look.

**Comment by elecpower** [comment]
Confirmed. On my TODO list
