### ISSUE TITLE
Taranis X-Lite Pro ISRM not selectable on TX

### ISSUE THREAD

**Issue by druckgott** [EdgeTX/edgetx#5153]
If I want to select ISRM on the TX it´s not possible.
On the TX I only get all other ones, but on ISRM.
If I select in in Compainion its possible an If I take a look on the TX is selected if I write the config.
Then I go again to the TX select something als and the ISRM dissapears again. Then I have to reactivate it again over Companion.

![grafik](https://github.com/EdgeTX/edgetx-sdcard/assets/18383738/c738b4fd-896b-4203-b7a8-0b5906b7c9f9)

**Comment by pfeerick** [comment]
This was opened in the wrong place.

What version of EdgeTX are you running? And why are you trying to change it in the hardware settings? 

I can reproduce this in simulator for 2.10.0 FWIW.

**Comment by druckgott** [comment]
I use 2.10.0
