### ISSUE TITLE
Able to disable Touch Screen

### ISSUE THREAD

**Issue by ror1948** [EdgeTX/edgetx#5163]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We have RC members who are in their senior years and they tend to be touching the touch screen on Tx16s unknowingly changing the setup.
They do not know how to setup Tx16s and it is done by someone else.

### Describe the solution you'd like

A sequence of button pushes to enable or disable touch screen 

### Describe alternatives you've considered

1) A sequence of button pushes to enable or disable setup changes on touch screen. This would allow the basic function of the touch screen

**Comment by pfeerick** [comment]
Using the "No Touch" special function to disable the touch screen depending on the state of a switch or even some logic condition  isn't sufficient in this case?

**Comment by 3djc** [comment]
You could easily have a touch disabled by default, and enable it with a combination of t5/t6 position for example, just a logical switch and a special function

**Comment by ror1948** [comment]
sorry i did not know there was a no touch option...thanks

**Comment by ror1948** [comment]
ok but no logic switches available under SYS that i can see. running 2.10.1how do you disable it by default?thanks
    On Wednesday, June 12, 2024 at 09:06:08 a.m. EDT, 3djc ***@***.***> wrote:  
 
 


You could easily have a touch disabled by default, and enable it with a combination of t5/t6 position for example, just a logical switch and a special function

**Comment by pfeerick** [comment]
You can't use logical switches in global functions as they are model
specific. If you wanted to use a logical switch, you would have to add this
as a special function for each existing model. And maybe include it in a
new model template.
