### ISSUE TITLE
AUX1 powered at startup with AUX1 power set to off

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#5189]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

At the instance of pressing the power button AUX1 is powered even if AUX1 port power is set to off. AUX1 stays powered for the entire life cycle unless you set AUX1 port power to on and off again. 

Example: receiver connected and powered with port power set to off

![image](https://github.com/EdgeTX/edgetx/assets/5615068/ec6a1f46-19c8-474e-a5b3-6ac8f9b49b81)

### Expected Behavior

AUX not powered if port power set to off.

### Steps To Reproduce

1. make sure AUX1 port power is set to off
2. turn on radio
3. measure voltage between AUX1 GND and VCC pins

### Version

2.10.1

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by 3djc** [comment]
Not happening here: https://photos.app.goo.gl/8aHWFDqhVtUyzKsw8

**Comment by philmoz** [comment]
If the port is set to OFF then the power state is not updated in serialInit() (serial.cpp).

**Comment by 3djc** [comment]
Ok, port role need to be OFF and port power, understood
