### ISSUE TITLE
NV14 bootloader crashes on exit

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#519]
**Describe the bug**
When exiting NV14 bootloader the screen is covered with vertical colored lines and radio switches off.

**To Reproduce**
Enter bootloader either with left trim down or selecting EXIT with right trim the TX screen goes into typical crash color pattern and the radio switches off.

Not a big deal, since all operations can be performed, but...

**Expected behavior**
Similar to RM TX16 go to TX boot.

**General information**
 - EdgeTX current.
 - Hardware NV14

**Comment by Syncmasterklop** [comment]
The problem was not solved.

**Comment by pfeerick** [comment]
Sorry? If you are running a nightly bootloader from within the last 26 days then it is correctly exiting to the firmware for me. If you are running at 2.5.0 bootloader then it will still be broken for you.

**Comment by Syncmasterklop** [comment]
I have updated the last nightly build, the problem remains. Am I doing something wrong?
https://1drv.ms/v/s!AlG8PMfhz1cTqRxJ-sDLEFnpwX_i

**Comment by raphaelcoeffic** [comment]
> I have updated the last nightly build, the problem remains. Am I doing something wrong?
> https://1drv.ms/v/s!AlG8PMfhz1cTqRxJ-sDLEFnpwX_i

This is showing the firmware installed, not the bootloader. The question is: did you update with DFU mode, or not?

**Comment by Syncmasterklop** [comment]
No, I "updated" the bootloader through the file manager with the command "flash bootloader". Now I will try through DFU.

**Comment by raphaelcoeffic** [comment]
> No, I "updated" the bootloader through the file manager with the command "flash bootloader". Now I will try through DFU.

Well, it should be equivalent. But what do you consider “crashing”. When you hit exit: does it reboot or not?

**Comment by Syncmasterklop** [comment]
I showed it in the video, and in the first message there is an exact description "When exiting NV14 bootloader the screen is covered with vertical colored lines". This does not bother me much, I just wanted to point out that the problem is not fully resolved.

**Comment by raphaelcoeffic** [comment]
> I showed it in the video, and in the first message there is an exact description "When exiting NV14 bootloader the screen is covered with vertical colored lines". This does not bother me much, I just wanted to point out that the problem is not fully resolved.

Well, this is not "the crash", it's just the screen not being cleared before reboot ;-) Before it was fixed, it would not reboot at all and needed to be powered ON again after exiting.
