### ISSUE TITLE
RTC Check seems not to work on TX16s 1st generation (maybe others)

### ISSUE THREAD

**Issue by ProfDrYoMan** [EdgeTX/edgetx#5203]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

My RTC battery did run low (0.3 V shown), RTC check was on and still there was no alarm when turning on the TX.
The model that was selected did show a pre-flight screen. Maybe this is the cause for the missing RTC alarm message.

### Expected Behavior

RTC check warning message.

### Steps To Reproduce

Select a model with a pre-check file setup.
Select RTC check in system config.
Remove RTC battery.
Power up TX.
=> No warning. Pre-check screen is shown.

### Version

2.10.1

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
Was about to reproduce and will be resolved in 2.10.2. RTC check wasn't working at all for 2.10 or main.
