### ISSUE TITLE
2.10 branch - getFieldInfo(<number>) returns nil instead of table

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#5210]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

There is  nasty bug introduced in 2.10 branch that will affect many LUA scripts

getFieldInfo() can take as argument field name or source list index number.
In case argument is source list index function returns nil instead of table

TX16S as example
getFieldInfo('sa') is returning proper table
getFieldInfo(126) is returning nil

 

### Expected Behavior

getFieldInfo(<number>) has to return table

### Steps To Reproduce

Testing script

```
local toolName = "TNS|Sources|TNE"

return {
  run = function(e)
    lcd.clear()
    local swID = getSourceIndex(CHAR_SWITCH..'SA')
    lcd.drawText(0,0,swID,0)
    local swName = getSourceName(swID)
    lcd.drawText(0,20,swName,0)
    local swValue = getSourceValue('sa')
    lcd.drawText(0,40,tostring(swValue),0)

    lcd.drawText(0,80,'getFieldInfo('..swID..')',0)
    local fieldInfo = getFieldInfo(swID)
    if fieldInfo ~= nil then
      lcd.drawText(0,100,fieldInfo.id,0)
      lcd.drawText(0,120,fieldInfo.name,0)
      lcd.drawText(0,140,fieldInfo.desc,0)
    else
      lcd.drawText(0,100,'field info is nil',0)
    end

    lcd.drawText(200,80,'getFieldInfo("sa")',0)
    local fieldInfo = getFieldInfo('sa')
    if fieldInfo ~= nil then
      lcd.drawText(200,100,fieldInfo.id,0)
      lcd.drawText(200,120,fieldInfo.name,0)
      lcd.drawText(200,140,fieldInfo.desc,0)
    else
      lcd.drawText(200,100,'Field info is nil',0)
    end

    return 0
  end,

}
```

Output on 2.9.4
![screenshot_tx16s_24-06-22_09-55-04](https://github.com/EdgeTX/edgetx/assets/46420768/cbddd439-3412-485f-9db1-6bd6534fd9fd)

Output on 2.10 and 2.10.1
![screenshot_tx16s_24-06-22_09-54-25](https://github.com/EdgeTX/edgetx/assets/46420768/127a5a5f-6db8-417c-bf7d-c87c895e577e)

### Version

2.10.1

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

macOS

**Comment by philmoz** [comment]
Already fixed in PR #5108
