### ISSUE TITLE
Companion - reversed S1 and S2

### ISSUE THREAD

**Issue by sande005** [EdgeTX/edgetx#5213]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

S1 and S2 do not increment from -100 to +100 when rotated clockwise in Companion simulator.  Instead scale from +100 to -100.

### Expected Behavior

Rotating knob clockwise should increase value, as it does in OpenTX 2.3.15

### Steps To Reproduce

Create basic 4ch model.
Add S1 or S2 as a source for Ch5 in Mixer.  Leave all else at default, including Outputs.
Open simulator.  Open monitor
Rotate knob on simulator clockwise.
Observe values decrease as rotation increases.

### Version

2.10.1

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### OS Version

Windows 11

### Anything else?

Behavior in actual radio is correct.
Have not tested sliders or switches for similar reversed behavior in Companion.
Current calibration and hardware data was saved to Companion profile, to verify that this was not causing the issue.

**Comment by pfeerick** [comment]
It appears the default settings in Companion are wrong for the X10 Express... both S1 and S2 are marked as inverted by a default blank config. 

![image](https://github.com/EdgeTX/edgetx/assets/5500713/277cdb82-a736-430a-b496-fd1deae25749)

Looks like #5160 is needed for 2.10 also.
