### ISSUE TITLE
ISRM mit X9 Lite S

### ISSUE THREAD

**Issue by Fredflar** [EdgeTX/edgetx#5234]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Sender lässt sich nicht auf Modul ISRM einstellen.
Sender cannot be adjusted to Module ISRM.

### Expected Behavior

Beim wechsel von OTX zu EdgeTX kein Ausfall des Moduls. Bei meiner X9D+2019 ohne Fehler des Moduls.
When changing from OTX to EdgetX, no failure of the module. With my X9D+2019 without mistakes in the module.

### Steps To Reproduce

Mehrmals das Modell, die Hartware Einstellung geändert kein Erfolg. Radio Firmware.bin neu aufgespielt und Bootloder aktualisiert ohne Änderung. Neu aus Internet heruntergeladen.
Several times the model, the hardware setting changed no success. Radio firmware.bin re -played up and updated boot looder without a change. New down from the Internet.

### Version

2.10.1

### Transmitter

FrSky X9 Lite / Lite S

### Operating System (OS)

Windows

### Anything else?

![20240630_Fi-Options](https://github.com/EdgeTX/edgetx/assets/34328797/ebf908b1-654b-458c-85bc-17b779c752af)
![20240630_SH-CRSF2](https://github.com/EdgeTX/edgetx/assets/34328797/6bf18126-917c-4281-bb50-98f027666f54)
![20240630_SH-MoOFF](https://github.com/EdgeTX/edgetx/assets/34328797/36474916-c1ca-43e9-9e6f-fd637f13ce82)
![20240630_SH-Multi](https://github.com/EdgeTX/edgetx/assets/34328797/e3a30174-8c52-4a75-a7fb-1a3f7a38e8b2)
![20240630_SM-CRSF1](https://github.com/EdgeTX/edgetx/assets/34328797/9140ead2-b84d-40fd-bcad-253c742271ee)
![20240630_SM-ExMultiDSM](https://github.com/EdgeTX/edgetx/assets/34328797/485e9518-5e79-4f6d-9a04-11cd7189b5a9)
![20240630_SM-ExMultiFlySky](https://github.com/EdgeTX/edgetx/assets/34328797/b78914b5-0467-48c0-9514-f1cbbc50ff75)
![20240630_SM-OffOff](https://github.com/EdgeTX/edgetx/assets/34328797/11e591d9-0d3f-4378-877e-73377976e222)
![20240630_VeFi](https://github.com/EdgeTX/edgetx/assets/34328797/2b8dcdf3-5941-4fc2-915e-ccce4b0cb407)

**Comment by pfeerick** [comment]
It appears there is a bug where you can only select between CRSF and MULTI if ISRM is not already set. 

Edit your `RADIO/radio.yml` file (on the radio's SD card) and change `internalModule` to `TYPE_ISRM_PXX2` and you should be able to select ISRM in your model settings now (you will need to toggle it off and on again if internal RF was turned on).

**Comment by raphaelcoeffic** [comment]
> you can only select between CRSF and MULTI if ISRM is not already set

I just verified: by default, ISRM is selected (starting with empty SD card). However, as soon as something has been selected, no way to go back to ISRM.

**Comment by Fredflar** [comment]
Danke
