### ISSUE TITLE
R9SX receiver with R9M module, Horus x10s

### ISSUE THREAD

**Issue by jetfanZK** [EdgeTX/edgetx#5275]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

To be honest - I'm not sure if this is a bug:

![IMG_9860](https://github.com/EdgeTX/edgetx/assets/159617375/44ec2b32-12e8-4361-97b2-abc28a34de24)
![IMG_9861](https://github.com/EdgeTX/edgetx/assets/159617375/eb08049f-64c3-4fcc-9853-2358019c3559)
![IMG_9862](https://github.com/EdgeTX/edgetx/assets/159617375/6c29b2d9-2af0-419c-bf0f-d6f164253e11)
![IMG_9863](https://github.com/EdgeTX/edgetx/assets/159617375/2e535e78-5c7c-4745-ae1b-662779764c63)
![IMG_9864](https://github.com/EdgeTX/edgetx/assets/159617375/28330cb1-9bba-4c87-b192-59a586db53cd)

I can't bind R9SX receiver with R9M module in Horus x10s transmitter with IRSM module and Edge 'Centurion' 2.10.1
R9M module and R9SX receiver are after flashing in LBT ACCESS version. I try to bind the receiver: select 'Bind' in the module setup and power on the R9SX receiver with the F/S button pressed. I release the button, turn receiver off and on and... nothing happens. I tried many combinations - no results. What am I doing wrong? I have not found solution on the web, can you help me please?

### Expected Behavior

Binding with receiver

### Steps To Reproduce

Described above

### Version

2.10.1

### Transmitter

FrSky X10 Express / X10S Express (ACCESS)

### Operating System (OS)

Windows

**Comment by 3djc** [comment]
This module is not a R9M, it is a R9M 2019 module. R9M 2019 is only offered as a choice on X10Express radio (if I remember correctly, X10 hardware doesn't support it (but I'm not fully sure))

![image](https://github.com/EdgeTX/edgetx/assets/5167938/12517566-d5ae-4110-a100-efd615839d17)

**Comment by pfeerick** [comment]
Simulator suggests not... not presented as an option there. 

Looks like it would need the [externalaccessmod](https://github.com/opentx/opentx/wiki/Externalaccessmod#frsky-x10) done, then it would be possible to enable it by setting AUX1 in Radio Settings -> Hardware to External Module, o
