### ISSUE TITLE
There is no way to exit widget setup using touch interface

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#529]
**Describe the bug**
The only way to exit widget setup except RTN buttom=n. Not a big deal if button exists, but a disaster on NV14. :-).

**To Reproduce**
Screen Setup->Screen 1->widgets setup. Icon in the left top corner turns into EdgeTX and the only way to exit is by RTN button.

**Expected behavior**
Screen setup icon in the left top corner and it should take user to the previous screen. 

**General information**
 - EdgeTX version 2.4.0 and later
 - Hardware RM TX16S and NV14

**Comment by raphaelcoeffic** [comment]
Not really the fix of all fixes, but I added support for Enter/Exit keys on the trim click to ease the process a bit.
