### ISSUE TITLE
Trims still visible after being set to off in model setup page

### ISSUE THREAD

**Issue by alant101** [EdgeTX/edgetx#5291]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Unable to remove trims from display

### Expected Behavior

Not to be visible

### Steps To Reproduce

select option for trims not to be displayed

### Version

2.10.2

### Transmitter

FrSky X9D+2019

**Comment by 3djc** [comment]
What option did you exactly use ? I think you misunderstood what it does, since there is none in model settings to do that

**Comment by alant101** [comment]
What I was hoping to achieve is to remove the trims for the display 
[X9D 2019.zip](https://github.com/user-attachments/files/16196498/X9D.2019.zip)

**Comment by 3djc** [comment]
Trims will be removed from display only of deactivated in flight mode

**Comment by alant101** [comment]
Okay thank

**Comment by pfeerick** [comment]
> I think you misunderstood what it does, since there is none in model settings to do that. The closest is trim values.

That is easily done, since the text is "Display Trims", not "Display Trim **Value**".

**Comment by alant101** [comment]
Hi, what I'm trying to achieve is, remove trims from display. As I wish to
use the Inav lua script and hence no trims visable. If you're able to help
me with that, I would be very grateful

**Comment by 3djc** [comment]
Unrelated, the lua script run out an empty screen anyway

**Comment by alant101** [comment]
Just like to say thank you, I now understand what you were referring to

**Comment by 3djc** [comment]
But again, that does not affect AT ALL inav lua scripts
