### ISSUE TITLE
Lua:  getFieldInfo using "Min" or "Max" always return min.

### ISSUE THREAD

**Issue by frankiearzu** [EdgeTX/edgetx#5292]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

While using the Flights Widget, noticed that regardless if i choose MIN or MAX for the source, it reports "min" for MAX, and "--" for min.

### Expected Behavior

Should properly report the source name.

### Steps To Reproduce

1. Setup the Flights widget.
2. Choose MAX as the source for the ARM
3. go to full screen to see the name of the source/switch  (is showing "min", but should be "max")

### Version

2.10.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Anything else?

![image](https://github.com/user-attachments/assets/0b1cc1e3-5347-44f9-8fb4-4906711172ee)
![image](https://github.com/user-attachments/assets/029f1ba4-e280-4d59-860e-8eec53c74c24)

**Comment by frankiearzu** [comment]
The problem is here:   Mistyped constant...  (Ill do the PR to fix it).
![image](https://github.com/user-attachments/assets/de7068f3-d8b8-41fb-8e09-169712b1b344)

**Comment by mha1** [comment]
I blame copy/paste. Thanks for making this right. And obviously not the most used LUA constant. No complaints since 08/23.
