### ISSUE TITLE
Edgetx 2.10.1 X9E forgot the installed sensor

### ISSUE THREAD

**Issue by MicheleVilla** [EdgeTX/edgetx#5297]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In telemetry page search and visualize the installed telemetry sensor (sensor cels, altimeter GPS etc)
When switch off and switch on the transmitter the sensor in subject are missing and Is necessary to make another search sensor operation.

### Expected Behavior

Once the sensors installed on the receiver have been searched for and memorized, they should remain available even after restarting the transmitter.

### Steps To Reproduce

Go in telemetry page
search the installed sensors
switch off the transmitter
switch on trasmitter and go in telemetry page
sensors are missing

### Version

2.10.1

### Transmitter

FrSky X9E / X9E Hall

**Comment by 3djc** [comment]
Have you simply not toggled the arrow?

**Comment by MicheleVilla** [comment]
Oppssss....
You are right
I think this issue can be closed
