### ISSUE TITLE
Companion Log Viewer (2.10) no longer highlights selected trace

### ISSUE THREAD

**Issue by silicongarage** [EdgeTX/edgetx#5298]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Log Viewer (2.10) no longer highlights the trace of a displayed field when clicked (selected).   Worked properly in previous versions of Log Viewer (2.9).

### Expected Behavior

Click on plot trace or trace name in plot legend and have trace highlighted.

### Steps To Reproduce

1. Load `.csv` log file
2. Select a trace from the list on left
3. Click on trace in plot  or trace name in plot legend

### Version

2.10.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

macOS

### OS Version

13.6.7

### Anything else?

previous (2.9)
<img width="261" alt="Screenshot 2024-07-15 at 8 34 12 AM" src="https://github.com/user-attachments/assets/3de0288e-d941-417f-8803-b091e881826e">

current (2.10) 
<img width="246" alt="Screenshot 2024-07-15 at 8 32 34 AM" src="https://github.com/user-attachments/assets/6d5f4075-78e6-4b3a-a790-5012629b4a7c">

**Comment by pfeerick** [comment]
I can reproduce this when switching between Companion 2.9.4 to Companion 2.10.1 & 2.10.2 on Linux.
