### ISSUE TITLE
protocols are changed

### ISSUE THREAD

**Issue by tonims1** [EdgeTX/edgetx#5300]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In 2.11 the protocols are changed in several models. I usually do it more in Frsky, going back to 10.2 doesn't happen

### Expected Behavior

that protocols are maintained

### Steps To Reproduce

select a model go to internal rf . the protocol has changed

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by pfeerick** [comment]
Changed from *what*? To *what*? Is it consistent? Have you updated the MPM firmware in the meantime, to a version of the firmware that doesn't support those protocols?

**Comment by tonims1** [comment]
I only have Frsky and Flysky receivers. Those who are in Frsky change to Flysky but if you click to change it, the first option is the correct protocol. If you select it, change the receiver number to 0 as if you changed the protocol. If the protocol is Flysky 2, it becomes Flysky alone. Also, changing the model in the status module comes up randomly. no multi telemetry detected. until I turn it off and on again it doesn't detect it again. I have the latest version of Multi, 1.3.4.0 Air. if I go back to Edgetx 2.10. everything works fine again.
Being on the same model, I turn off the transmitter and turn it on again, it does a protocol scan and it is fine again, but if I leave the internal rf menu and come back in, it has changed again.

**Comment by koaxheli** [comment]
Hello, I have the same problem with v2.11.0. The log is displayed with the wrong content when I select it.
If I go back to v2.10.2, everything is displayed with the correct names again.
v.2.11.0
![screen-2024-07-18-123819](https://github.com/user-attachments/assets/9d35652e-1a18-4c3c-bb17-16e53c43634e)
Here is the 2.10.2
![screen-2024-07-18-125014](https://github.com/user-attachments/assets/e1408460-c3df-407b-a2d0-b2d0b7d65741)

**Comment by TomasJot** [comment]
I will ty to explain this bug further... After setting MULTI protocol and sub protocol in internal module configuration screen after  exit and entering again protocol and subprotocol displays incorrect names (eg. Hubsan instead of FrkskyV2). I traced this bug to  be introduced at commit b8dc505 - fix(color): wrong file chooser icon, portrait layout and other (https://github.com/EdgeTX/edgetx/pull/5201) (actually - more bugs was introduced, as inability to select protocol with scroll wheel, those was fixed at commit 0d9215a)

**Comment by pfeerick** [comment]
Thanks for reports... the main part  - "protocols changed" is reproducible, and should be fixed now. The "no multi telemetry detected" is separate, and we'll have to see if it affects anyone else, otherwise it is most likely hardware or firmware specific.
