### ISSUE TITLE
DSM Forward programing errors

### ISSUE THREAD

**Issue by orstratcat** [EdgeTX/edgetx#5323]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Need a DSM forward programming Lua script for AS3X+ that actually works on the RadioMaster TX16S MK II.
DSM forward programming v0.57 (color) errors on AR631 V3

### Describe the solution you'd like

Need a DSM forward programming Lua script for AS3X+ that actually works on the RadioMaster TX16S MK II.

### Describe alternatives you've considered

1. Don't use DSM receivers solves the problem but No Safe, only Stabilization.

**Comment by JimB40** [comment]
This LUA APP is maintaned by @frankiearzu.
https://github.com/frankiearzu/DSMTools
He just published 0.58 that may solve your problems, so head over there.
