### ISSUE TITLE
Cant flash any frsky receivers

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#541]
Tx16s
Latest etx main firmware.
Cant flash any frsky receivers.
I have set external bay to ppm (and everything else) and set up to flash like I always do but...
It trys to flash then a message pops up saying "firmware update error data refused"
Receiver goes from flashing red indicating power.
Then off. Then flashing green and that's when the message pops up.
Receivers I have tried are s6r. Rxsr and r9mm.
I put the receiver flash files in a qx7 running otx and flashed straight away.

**Comment by raphaelcoeffic** [comment]
> I have set external bay to ppm (and everything else)

This is not necessary at all! You can just leave it OFF. Flashing from the module bay should turn the power on when required (it needs to reset the receiver to trigger the bootloader).

**Comment by Mantamatt1** [comment]
I had also set to off and still have the same message
