### ISSUE TITLE
X12S screen gone crazy after latest nightly update

### ISSUE THREAD

**Issue by Kevltan** [EdgeTX/edgetx#5432]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Screen flickering, trims bouncing all over the place, eraneous voice calls, battery voltage warnings to name just a few. What was added or removed from the last nightly update possibly "H7 SPI support" change has very seriously upset the X12S user interface. Returning back to previous nightly [2df817f](https://github.com/EdgeTX/edgetx/commit/2df817fbf0e51b76b113b64e7a39a6bf71551502) removes all of these issues.

Last running good firmware main:-
[2df817f](https://github.com/EdgeTX/edgetx/commit/2df817fbf0e51b76b113b64e7a39a6bf71551502)

X12S does NOT like firmware main:-
https://github.com/EdgeTX/edgetx/commit/3bdec2f347742478cfdb28e8aa2f44460023bab3

Does NOT seem to effect the TX16S!

### Expected Behavior

None of above!

### Steps To Reproduce

As soon as transmitter boots into an active model

### Version

Nightly (Please give date/commit below)

### Transmitter

FrSky X12

### Anything else?

Latest nightly

**Comment by Kevltan** [comment]
Latest H7 SPI support seems to effect TX12S adversely.
@raphaelcoeffic
@pfeerick

**Comment by 3djc** [comment]
Could you please try a firmware out of this PR: https://github.com/EdgeTX/edgetx/pull/5433 ?

**Comment by Kevltan** [comment]
83d663b2

**Comment by pfeerick** [comment]
> TX12S does NOT like firmware main:-
3bdec2f

typo, or do you have a TX12 also? If so, this is the only radio of the three mentioned that #5433 will help with (i.e. b&w)

**Comment by Kevltan** [comment]
Typo 🤣😂🤣

**Comment by raphaelcoeffic** [comment]
Also worth mentioning: the X12S and its ADC is the only target to make use of SPI word (16 bit) transfers.

**Comment by Kevltan** [comment]
@raphaelcoeffic 
Yes this fixes the X12S. Thanks 👍😊😊👍
