### ISSUE TITLE
Inverted mix switch not saving

### ISSUE THREAD

**Issue by gapster15** [EdgeTX/edgetx#5434]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Inverting a switch on the mixes screen will not be saved upon rebooting my MT12. 
![1](https://github.com/user-attachments/assets/76e6b9ea-bbe7-4195-a871-5420bb274a84)
After reboot
![2](https://github.com/user-attachments/assets/a17071ef-cbc2-4e51-b6b3-693dcb08bb59)

### Expected Behavior

Save the setting

### Steps To Reproduce

1) In mixes, select a channel using a switch
2) Set the switch to inverted and save
3) Reboot TX and the switch is no longer inverted

### Version

2.10.3

### Transmitter

RadioMaster MT12

**Comment by pfeerick** [comment]
I was able to reproduce this on MT12, and on Zorro. The MT12 appeared to loose the plot one time, and change the source and drop the inverted switch completely, and the Zorro initially appear to work, but after swapping the SRC, it also lost the inverted switch on reboot.

**Comment by pfeerick** [comment]
Ah, ok, I think I just spotted what is happening... using the popup menu to invert is not triggering model settings dirty... so it doesn't save... if you instead use cursor, or edit *some other* setting 'normally', it does save. ;)

**Comment by philmoz** [comment]
Looks like an old issue - happens in 2.9 as well (simulator).

**Comment by pfeerick** [comment]
Couldn't repo this on as easily on the the X9D+ I have that is still on 2.9.2, so maybe there was a radio navigation element to it? Either way, #5435 indeed seems to resolve this.
