### ISSUE TITLE
In Companion 2.11.0 Simulation Mixes GV...SRC no selection

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#5444]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

In Companion 2.11.0 [run 2292 from today](https://github.com/EdgeTX/edgetx/actions/runs/10399015083), the switches GV --> SRC in the Mixes menu are not available for selection in the simulation.

### Expected Behavior

Should behave like in Companion 2.10.3.

### Steps To Reproduce

If you go to 2.10.3, go to Mixes and GV can be updated.
Go to 2.11.0 and the new switch SRC does not work.

### Version

2.10.3

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?

![2 10 3](https://github.com/user-attachments/assets/3a234a80-6083-4e8f-8b87-646d6dc55103)
![2 11 0](https://github.com/user-attachments/assets/bcb7b6bb-b148-47d1-9135-3e446a014866)
![2 11 0-Companion](https://github.com/user-attachments/assets/d5d954c6-5565-4bb3-9368-665f46a109ba)

**Comment by pfeerick** [comment]
This appears to be a bug in the only the windows simulator... confirmed by three separate people now. Linux, and presumably MacOS (given who made the SRC/GV changes 😆) are both working as expected.

**Comment by koaxheli** [comment]
Take this file under Windows and when you open the mixer in the simulation it says SRC and does not work.
The GV switches are still present for the servo outputs OK.
![2 11 0-exe](https://github.com/user-attachments/assets/a37ded24-9f15-41f1-a574-a28459781ffc)
