### ISSUE TITLE
Channel Overrides are allowed to go past outputs

### ISSUE THREAD

**Issue by craigywsm** [EdgeTX/edgetx#5446]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

[test model.zip](https://github.com/user-attachments/files/16641569/test.model.zip)
With the above model I have set the low throttle to -83.0 on the outputs (1075us)
![image](https://github.com/user-attachments/assets/350a8278-344a-4292-acde-658043990410)

If I set a special function (sa - middle) to override channel to -100
![image](https://github.com/user-attachments/assets/3fd49bba-4dc0-42c5-a1ac-cafb4354fd55)
It sets the the output to 988us
![image](https://github.com/user-attachments/assets/5c6d541d-2e0e-424e-a8bf-3aa92e7d848a)

### Expected Behavior

Outputs are there to restrict servo binding e.g. total output limits
Why are special functions (override channels) allowing a channel to be over driven?

### Steps To Reproduce

1. with model attached
2. on outputs page set sa -

### Version

2.10.3

### Transmitter

FrSky X9D+2019

### Operating System (OS)

Windows

### OS Version

Windows 10 x64

**Comment by pfeerick** [comment]
If I had to guess, I would guess it was in the name... It is an override...
Not a fake input, not a default. This is one of the reasons using a
additional mixer line controlled by a switch is preferred. They each have
their place. It's really up to you to configure them correctl.

**Comment by 3djc** [comment]
By design

**Comment by craigywsm** [comment]
Fair enough
