### ISSUE TITLE
SD Logs: Value cannot be cleared

### ISSUE THREAD

**Issue by twistedwings** [EdgeTX/edgetx#5451]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Special Functions:
SD Logs: Value cannot be cleared (0 = off), min is 0.1

### Expected Behavior

Special Functions:
SD Logs: Value can be cleared (0 = off),

### Steps To Reproduce

1. Modell Settings
2. Special Functions
3. Create new
4. SD Logs
5. Set value to 0

### Version

2.10.3

### Transmitter

RadioMaster TX16S / TX16SMK2

**Comment by 3djc** [comment]
You can disable the SF , you can delete it, but a sd log with a 0 sec interval means nothing.

What are you trying to achieve?

**Comment by twistedwings** [comment]
I want to switch logging off.
The [manual](https://manual.edgetx.org/bw-radios/model-select/special-functions) says:
"The value options are 0.0s - 25.5s (Note: 0.0 effectively disables this option)."

In companion I can set a value of 0.

**Comment by 3djc** [comment]
Simply disable the trigger for the sf or the sf itself

**Comment by twistedwings** [comment]
that's a little bit tricky while flying...

**Comment by 3djc** [comment]
No, simply put the trigger for sd log on a switch or something like this

**Comment by twistedwings** [comment]
I have done that.
But I want to switch logging on and off.
Therefore I have to set the parameter to 0 (for switching off)

![image](https://github.com/user-attachments/assets/31bd452a-821e-4836-8229-f5b01e193bae)
![image](https://github.com/user-attachments/assets/905cb695-cff4-4bdf-b90c-868de600836a)

That works in companion but not on the radio.

**Comment by 3djc** [comment]
This makes no sense, if L13 is not true, there will be no logs, therefore your second line is useless

**Comment by twistedwings** [comment]
OK, than it was a misunderstanding on my part.
Sorry, I will close the issue.

**Comment by 3djc** [comment]
I think there is an issue companion (and documentation) side, so please leave open
