### ISSUE TITLE
Add USB telemetry mirror (Opentx PR #8650)

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#546]
Add the PR https://github.com/opentx/opentx/pull/8650

**Comment by raphaelcoeffic** [comment]
Not bad! But I think we can make this better by leaving this as-is and adding settings to map serial ports to functions. So as you can choose now to have telemetry mirror on a normal serial port, you could assign the function “telemetry mirror” also to the usb serial. We will need this capability for mavlink as well.

**Comment by raphaelcoeffic** [comment]
> Not bad! But I think we can make this better by leaving this as-is and adding settings to map serial ports to functions. So as you can choose now to have telemetry mirror on a normal serial port, you could assign the function “telemetry mirror” also to the usb serial. We will need this capability for mavlink as well.

These assignment should be per model, of course, as you might want different things depending on the model.

**Comment by wimalopaan** [comment]
You mean, we have in all radios the function "usb serial" to which one can assign "SBus in", "Telem mirror", "LUA", etc?

Wow, that would be real cool. One has to compile the firmware with USB_SERIAL=YES?

Looks like I missed the USB_SERIAL option complety ... what can I do with that in the current state of the project? Only debug?

**Comment by raphaelcoeffic** [comment]
> You mean, we have in all radios the function "usb serial" to which one can assign "SBus in", "Telem mirror", "LUA", etc?
> 
> Wow, that would be real cool. One has to compile the firmware with USB_SERIAL=YES?
> 
> Looks like I missed the USB_SERIAL option complety ... what can I do with that in the current state of the project? Only debug?

That is a plan, it does not work yet ;-) But you can today have debug via USB serial by enabling it, yes. It's just, you cannot choose what it is used for, whereby you can for the normal serial ports.

**Comment by wimalopaan** [comment]
> > You mean, we have in all radios the function "usb serial" to which one can assign "SBus in", "Telem mirror", "LUA", etc?
> > Wow, that would be real cool. One has to compile the firmware with USB_SERIAL=YES?
> > Looks like I missed the USB_SERIAL option complety ... what can I do with that in the current state of the project? Only debug?
> 
> That is a plan, it does not work yet ;-) But you can today have debug via USB serial by enabling it, yes. It's just, you cannot choose what it is used for, whereby you can for the normal serial ports.

Simply awesome!!!

**Comment by Meldinov** [comment]
CMON, OpenTX now offiaclly adopted this! :P

**Comment by rotorman** [comment]
@Meldinov Have you tried latest EdgeTX already?

![grafik](https://user-images.githubusercontent.com/21011587/165170186-50a1e5d6-3b73-46e6-92e0-2c7589d9ee90.png)

**Comment by Meldinov** [comment]
> @Meldinov Have you tried with latest EdgeTX?
> 
> ![grafik](https://user-images.githubusercontent.com/21011587/165170186-50a1e5d6-3b73-46e6-92e0-2c7589d9ee90.png)

then why is this still an open issue?
