### ISSUE TITLE
Radio settings and calibration should be separated

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#5470]
I think it would be a good idea to split the calibration and hardware settings into a separate file, thus effectively making the `RADIO/radio.yml` less radio hardware specific, and more transferable between handsets. This would also effectively be the "factory hardware settings" that you would want to be able to backup to EEPROM/SPI flash. ;)

**Comment by elecpower** [comment]
Refer #381

**Comment by pagrey** [comment]
Does the voltage calibration belong in settings? Does the number and type of switches belong in settings? If you can't answer in a concrete way which thing is a setting and which is a calibration then maybe splitting them doesn't make sense.

The radio.yml file will always depend on the hardware configuration so why split it up? Seems like the UI in companion for managing the calibration settings is the main issue.

**Comment by pfeerick** [comment]
Thanks Neil, was bugging me as I was sure I had created or seen an issue
for this before.

**Comment by pfeerick** [comment]
> Does the voltage calibration belong in settings? Does the number and type of switches belong in settings? If you can't answer in a concrete way which thing is a setting and which is a calibration then maybe splitting them doesn't make sense.

It depends on what you mean by "settings". Settings UI? There is nothing wrong with the current UI. Settings file - it should be split, so that the radio settings is seperate to the hardware settings. i.e. consider the situation where you have two TX16S - you currently can't just copy the radio.yml between them... you need to calibrate afterwards. Wouldn't be necessary if you had a seperate `calib.yml` or `hardware.yml` file the RADIO folder. Or a EL18 and TX16S (which have completely different switch configurations)... again, not an issue if they are broken into a seperate file. 

> The radio.yml file will always depend on the hardware configuration so why split it up? Seems like the UI in companion for managing the calibration settings is the main issue.

No, it won't... how does the screen brightness, audio levels, or configured general functions (ok, I know this is the murkey middle ground) specifically depend on hardware? Note, the murkey middle ground could be resolved with virutal/assignable controls, which is itself another request around here. (i.e. rather than configuring your arm switch as SF, you configure it as ARM, and you then assign that on a per radio basis). 

Duplicate of #381

**Comment by elecpower** [comment]
> Thanks Neil, was bugging me as I was sure I had created or seen an issue
> for this before.

Forgiven as it was 5000 issues ago
