### ISSUE TITLE
Companion Sim still not OK lat , lon is output without a comma

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#5481]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

When simulating the csv file, there is a space between lat and lon in the GPS column and is therefore not recognized as a comma is expected.

### Expected Behavior

In the old version 2.10.3 the space was replaced by a comma which has now been removed.

### Steps To Reproduce

Load a logged csv table and view the result 

### Version

2.10.3

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### Anything else?

Two pictures attached showing how the data from the GPS sensor is logged in the model and incorrectly analyzed in the Companion simulator.
![GPS_lat_lon_2](https://github.com/user-attachments/assets/cc922cb2-f6b6-4fb9-9c69-f9a7dd19f40b)
![GPS_lat_lon_3](https://github.com/user-attachments/assets/f5af2500-dbc9-4c6b-89b1-d50c226b70af)

**Comment by pfeerick** [comment]
What version / build of Companion are you actually running now? As that is not a screenshot from 2.10.3 ;)

I am unable to reproduce the error with the comma with the [latest build of Companion for Win64](https://github.com/EdgeTX/edgetx/actions/runs/10558436236/artifacts/1854483014) (nor on the Linux version I tested this morning)... and I specifically tested for presence and absence of the comma, and it works fine for both with no error message.

![image](https://github.com/user-attachments/assets/057ec9b9-f858-4d8b-87fb-796beac60613)

**Comment by koaxheli** [comment]
Version 2.11.0 latest feat(cpn): update telemetry simulation to include FrSky Hub (#5475)
The error occurs when I load a cvs log file and go to playback then the file is played back without a comma.

**Comment by koaxheli** [comment]
Output of the simulation is all at GPS with zeros
![GPS_lat_lon_4](https://github.com/user-attachments/assets/2ea8b45c-adc7-40a2-aeb0-5f4a47c87d42)

**Comment by nrw505** [comment]
Have you tried with the latest `main` branch? I don't believe a nightly build with the fix has happened yet.

**Comment by koaxheli** [comment]
Sorry, I had the wrong version.
Now the right one and it works
chore(cpn): Stop SimulatedGPS refactoring, fix GPS latitude/longitude errors ... #2325

**Comment by pfeerick** [comment]
Yeah, it was the next build (or any after) that you wanted for the GPS telemetry fix.  Glad to hear it's working for you now :)
