### ISSUE TITLE
customizable button do no reset/stop inactivity alarm

### ISSUE THREAD

**Issue by TGS78** [EdgeTX/edgetx#5489]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Pressing any of the six customizable buttons do not reset the inactivity timer, also do not stop inactivity alarm.

### Expected Behavior

Should behave like all other physical inputs.

### Steps To Reproduce

-/-

### Version

2.10.3

### Transmitter

Jumper T20 V2

**Comment by 3djc** [comment]
Agreed !
