### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#553]
copiright-header.txt
assigns copyright to OTX - not edgeTX for new files. :-)

**Comment by pfeerick** [comment]
Are you referring to this?

https://github.com/cloudposse/copyright-header

**Comment by eshifri** [comment]
https://github.com/EdgeTX/edgetx/blob/main/tools/copyright-header.txt

**Comment by raphaelcoeffic** [comment]
> https://github.com/EdgeTX/edgetx/blob/main/tools/copyright-header.txt

Good catch, thx!
