### ISSUE TITLE
Quick search in long lists via page key(s)

### ISSUE THREAD

**Issue by froqstar** [EdgeTX/edgetx#5542]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Especially with large sound packs it is very cumbersome to scroll through potentially 100s of tracks to find the right one. 
So a "fast scroll" functionality would be awesome to have. 

### Describe the solution you'd like

Could we use the "page" button(s) of the radio to jump to the entries starting with the next/previous alphabet letter when having a scrollable list open? 

### Describe alternatives you've considered

Would a press-and-scroll with the scroll wheel work as well? 
For Color UI maybe a second list "column" with all the first letters present in the list (or just all of them?) could be helpful as well, similar to how sources can be browsed by category.

**Comment by philmoz** [comment]
2.11 file selector:
![screenshot_tx16s_24-09-16_21-57-14](https://github.com/user-attachments/assets/83bf2be9-c757-4ef2-8e63-01e82c0c3136)

**Comment by froqstar** [comment]
Nice! 
But for B&W it's still the same long list even in 2.11, correct?

**Comment by 3djc** [comment]
B&W don't enough memory to load long list

**Comment by 3djc** [comment]
That assumes that files are sorted in the directory, not sure they are necessarily

**Comment by 3djc** [comment]
They might be because you copied them all at once and they were sorted on pc. What happens if you add new ones ?

**Comment by froqstar** [comment]
Okay, reading up on it with my very limited C++ skills I now see what the problem is. Thanks for that. 
So we can't assume that the files will be sorted in 100% of cases so we can't do something fancy and obvious like on color UI because it might not work in all cases. 

Still in most cases they should be, because people usually copy full sound packs or SD card contents onto their cards, at which point they are sorted until the order is changed manually (e.g. adding single files later).
So it might be doable on a best-effort basis if that is acceptable for the project - worst case the fast skip will become "unordered" at the end of the list and the user can still scroll through every list entry like right now, best case the search time for files can be cut to 1/10th or so. 

Thanks a lot for your patience.

**Comment by 3djc** [comment]
Function that work only in best case scenario don't look like a great idea to me

**Comment by pfeerick** [comment]
Even if you copy entire sound pack at once, that is unfortunately no
guarantee... Windows likes to do things at random at times... Like copy the
last file first... But only sometimes... :-/

The only way I can see this working is if instead the folder was
specifically loaded one letter at a time "on demand"... rather than a
single scrollable list... but that will still chew into the memory
significantly in some cases, so I think this really isn't an viable option
for current generation b&w radios.

**Comment by froqstar** [comment]
Thanks for the explanation
