### ISSUE TITLE
cannot add model images and Theme only changes perimeter color...2.10.2 TX16s

### ISSUE THREAD

**Issue by jkoz29693** [EdgeTX/edgetx#5543]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

cannot add model images and Theme only changes perimeter color...2.10.2 TX16s. Used Buddy to update...did not work w/ 2.10.4 either

### Expected Behavior

Theme should fill entire background (works on my other TX16S; same config)
Should be able to select an image to go with Model info; cannot display image to Model. Images were copied from other working TX16S 

### Steps To Reproduce

See above; notice blue sky in first pic, should be "Greenfields"

You can see problem unit is Carbon Fiber, second working unit is just plain black...
![PXL_20240915_174644384](https://github.com/user-attachments/assets/ba5eee07-2d83-47f9-ba9d-1a7f676111a3)
![PXL_20240915_175000536](https://github.com/user-attachments/assets/d76b4624-8d1a-4653-acc4-190fa26f6f1c)
![PXL_20240916_151036097](https://github.com/user-attachments/assets/65d3572d-54cc-4e46-98b3-29ac7ee6a888)

### Version

2.10.2

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

10

**Comment by pfeerick** [comment]
Theme on your second radio is probably missing the wallpaper images for the theme, hence why they are not being shown. i.e. copy the THEME folder from your good radio to the other, to make sure all the files are there. Or install the themes from the themes directory - I'll add the link later. 

For the model images, I'm not sure... Have you doube checked the image for that model is present in the IMAGES folder, and is configured on that model?

**Comment by jkoz29693** [comment]
thanks for your response

Not really certain what was causing my issues; I had done several updates w/o problems. 

I went back to bootloader (instead of Buddy; was first time I used) 

as well a I think I had a sketchy USB port on my PC 


I'm all set; we can close/delete this.
Thanks again!
