### ISSUE TITLE
In companion-windows-2.11.0, the Gas timer source field is deleted for all models in the document when saving.

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx#5551]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

If the transmitter is loaded in Companion and I adjust something for testing and click on Save when exiting, the throttle entry is empty or the model file line thrTraceSrc: “!ch(10)”.
Transmitter is TX16S with v2.11.0 
Companion is the latest 2.11.0

### Describe the solution you'd like

The old status was in the line thrTraceSrc: Thr

### Additional context

![Gas_1](https://github.com/user-attachments/assets/c6127794-0186-4fbc-affd-70f93da70735)
![Gas_2](https://github.com/user-attachments/assets/ac817f58-995c-49f2-9300-6c5dcfe29da2)
![Gas_fehler](https://github.com/user-attachments/assets/7bd18899-250d-48f3-8a3b-4bcb6fe04fac)
![Gas_OK](https://github.com/user-attachments/assets/ec01cca1-1d65-4517-9dca-d7f6e0f863c7)

**Comment by elecpower** [comment]
Found and fixed during testing in #5381
