### ISSUE TITLE
companion program crashes when edit intern HF module at Pocket radio

### ISSUE THREAD

**Issue by meyer1111** [EdgeTX/edgetx#5560]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Companion program crashes when edit intern HF module (4in1, not CC2500!) at Pocket radio.

Internal RF 4in1 works very well. (ELRS has been replaced by 4in1 module)
But when i create a new model, the program crashes when edit intern HF module.
When i create a new model in the transmitter, the transmitter does not crash.
After this it can then be edited in Companion without any problems.
![ETX_Pocket_4in1_Comp_Bug](https://github.com/user-attachments/assets/7de8fb8e-5e97-4656-ac09-d6a9791ee629)

### Expected Behavior

Protocol selection without crash (4in1 internal HF-Module).

### Steps To Reproduce

1. create new model with companion
2. Protocol selection (internal HF module)

### Version

2.10.4

### Transmitter

RadioMaster Pocket

### Operating System (OS)

Windows

### OS Version

Win11 64bit, Win7 32bit

**Comment by meyer1111** [comment]
Supplementary information: transmitter profile: language = de !!!
Maybe that's the problem?

Companion program crashes when edit intern HF module, regardless if CRFS or 4in1 module default setting.

**Comment by pagrey** [comment]
It works for me. Be sure you change the radio profile settings to specify the internal module before you create the etx file. The module type is stored in the file. You can't open an existing etx file and change the internal module type. The setting only applies when the etx file is created.

**Comment by elecpower** [comment]
I cannot reproduce in Win 10 64 bit.

**Comment by elecpower** [comment]
> It works for me. Be sure you change the radio profile settings to specify the internal module before you create the etx file. The module type is stored in the file. You can't open an existing etx file and change the internal module type. The setting only applies when the etx file is created.

To clarify, in Companion you can change the radio profile Default Int. Module and each Models and Settings file Hardware Internal RF type at any time. 

The radio profile Default Int. Module is used to set the Hardware Internal RF type for New Models and Settings files. When you select New Model, the Hardware Internal RF determines which internal module types are available for the new model.

Changing the radio profile Default Int. Module will only apply to new Models and Settings files.

Changing the Hardware Internal RF of an existing Models and Setting file will trigger an update to the Internal RF of all models within that file. Should a model's Internal RF be incompatible with the new Hardware Internal RF then the model's Internal RF will be set to OFF.

**Comment by elecpower** [comment]
@meyer1111 I would suggest you delete and recreate the Pocket radio profile and retry. There maybe some unrelated values that are triggering the crash.

**Comment by elecpower** [comment]
@pagrey what version and radio profile are you using for your tests?

**Comment by pagrey** [comment]
I compiled a version of 2.10.4 with the Pocket simulator module to test this issue, I haven't tried with any other radio just because I wanted to get a clean build to test this particular issue. It's running on Linux.

**Comment by elecpower** [comment]
Thanks for the info. I'll recheck with this combo when I have some time.

**Comment by meyer1111** [comment]
I delete and recreate the Pocket radio profile and retry.
With default setting: Multi.
Now: everything is fine! :-)

Thank you very much! :-)




![herz1](https://github.com/user-attachments/assets/7937feb4-ebb4-4eda-99ef-b78eb032cd26)

**Comment by pagrey** [comment]
Great you got it all working.
