### ISSUE TITLE
Special functions get turned off when converting from OTX file.

### ISSUE THREAD

**Issue by Larry3215** [EdgeTX/edgetx#5570]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

I opened an OTX file and Companion 2.10.4 converted it to EdgeTx, but all the special functions got turned OFF. They were supposed to be ON.

### Expected Behavior

Special functions should have stayed ON.

### Steps To Reproduce

Opened E-Soar Plus from https://rc-soar.com/

### Version

2.10.4

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Windows

### OS Version

Windows 11 Home 23H2

**Comment by elecpower** [comment]
Only selected OTX SF Actions have Enabled flag whereas as of 2.10 all ETX Actions do https://github.com/EdgeTX/edgetx/pull/3601
OTX SF Actions with enabled flag get converted to ETX with enabled on/off.
OTX SF Actions without an enabled flag get converted to ETX with enabled off.

The release notes for 2.10 https://github.com/EdgeTX/edgetx/releases/tag/v2.10.0 had this stated limitation:
"When updating, the following special and/or global functions may need to be re-enabled: Instant Trim, BG Music Pause, Vario, Screenshot, Racing Mode, Disable Touch, and Audio Amp Off"

**Comment by RC-SOAR** [comment]
Just to add: the o/p raised this in relation to a setup in OTX 2.3 format targetting the X9D. This has a number of PlayTrack special functions which were disabled after conversion to ETX 2.10.4. 

It would be really nice if this could be fixed as all [my sailplane templates](https://rc-soar.com/edgetx/) are in OTX format (there are still a few OTX users out there, and the ability to import into EdgeTX means that only one master file needs to be maintained). 

Thanks for all the hard work, BTW, EdgeTX rocks!

**Comment by 3djc** [comment]
Otx is irrelevant here, he was just saying more (all) SF have enable field, the one where it was added need to be manually activated if desired. Coming from Otx or older Etx is the same

**Comment by elecpower** [comment]
Fixed in 2.10.5

**Comment by RC-SOAR** [comment]
Many thanks 😀
