### ISSUE TITLE
Companion: Crashes when editing model

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#5619]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When testing recent PRs, Companion crashed when trying to edit a model. It has happened with several PRs now, on both Windows and Linux, and I have only been able to reproduce this with a profile configured for the RM Pocket - other targets appear to be fine. First encounted it when trying to read from radio, but also happens with a "blank" model config. 

### Expected Behavior

For Companion to not crash when attempting to edit a model :astonished: Looks like I was unlucky pulling the Pocket out as the test subject today :rofl: 

### Steps To Reproduce

1. Create a new profile for RadioMaster Pocket
2. Create a new document
3. Crete a new model - I skip the wizard and just use an empty one. 
4. Attempt to edit the newly created model - double click, via the toolbar, or pressing Enter.
5. Companion will crash 'n burn

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster Pocket

### Operating System (OS)

Linux, Windows

### OS Version

Windows 11 24H2, Linux Mint 22

### Anything else?

#5418 biuld (Aug 13th #f44221c9) didn't
#5317 build (Aug 29th #4ad4ef95) didn't 
#5497 build (Sept 12th #3b7d7bf9) crashed (?!)
#5381 build (Sept 19th #e38edf3e) didn't

Maybe that gives some idea were it stems from...

**Comment by elecpower** [comment]
Win debug confirms subscript out of bounds
