### ISSUE TITLE
Companion: switching radio profiles can corrupt an open models and settings file hardware custom names

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#5621]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

Where the new radio profile has more hardware than the previous one the extra hardware custom name will be '000'.

This does not occur if the file is saved under the previous profile and reopened with the new profile. You are prompted to convert but there is no corruption.

### Expected Behavior

No corruption

### Steps To Reproduce

1. Select profile eg RM Pocket
2. Create a new models and settings file
3. Add a model
4. Select another profile eg RM TX16S
5. Accept all the conversion prompts
6. Click Edit Radio Settings
7. Observe '000' in the custom name fields of Pots and Switches

### Version

2.10.5

### Transmitter

Other (Please specify below)

### Operating System (OS)

Linux, macOS, Windows

### OS Version

All

### Anything else?

![Screenshot from 2024-10-18 08-13-13](https://github.com/user-attachments/assets/6a112d61-d0ff-4fad-8ac1-fe676a1ca54c)

**Comment by pfeerick** [comment]
Ouch!
