### ISSUE TITLE
Is RadioMaster Pocket CC2500 compatible with EdgeTX Companion V2.8?

### ISSUE THREAD

**Issue by chobson303** [EdgeTX/edgetx#5631]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I have a new Radiomaster Pocket CC2500 and I'm trying to setup a new Radio in Companion V2.8.0. I don't see a selection in the "Radio type" for my Radiomaster Pocket.  Is there another transmitter I can use as an option?

### Describe the solution you'd like

I just need a selection in the "Radio Type" to match my Radiomaster Pocket CC2500.

### Describe alternatives you've considered

Is there another transmitter in the "Radio Type" that is compatible with the Radiomaster pocket CC2500?

**Comment by elecpower** [comment]
V2.10 is required for RM Pocket
