### ISSUE TITLE
Option to open the telemetry screen on startup based on the current selected model

### ISSUE THREAD

**Issue by nikbg3** [EdgeTX/edgetx#5634]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I sometimes forget to open the telemetry when I start up the radio, and after flying a model, it's usually the first thing I check once I take off my goggles.

### Describe the solution you'd like

Add an option in the model settings to enable telemetry by default when powering on the radio.

### Describe alternatives you've considered

1. Manually pressing the button each time at power-up.  
2. An audio reminder to check the button manually each time I start up, configurable at the model level.

### Additional context

I am using a BW Radiomaster Boxer radio with the latest version. I am not certain if it is possible on colored radios

**Comment by pfeerick** [comment]
See what you think of https://github.com/EdgeTX/edgetx/pull/5589

**Comment by nikbg3** [comment]
Thank you, Peter! You are correct. This can be marked as a duplicate. I apologize that I was not able to find the one in question despite I tried to search it.

**Comment by nikbg3** [comment]
duplicate of #5589

**Comment by pfeerick** [comment]
That feature is present in nightly firmware, so if you are game enough you
can try it out now ;) Otherwise, it will be part of v2.11

**Comment by nikbg3** [comment]
I have tried it on my Boxer and it it covers this case with a One logic rule. Thank you! I will roll back to latest stable before flying just in case and wait for the official :)

**Comment by 3djc** [comment]
If you installed a 2.11 and come back to 2.10, you can likely corrupt your model/radio data

**Comment by nikbg3** [comment]
Thank you for the reminder! I have full backup of the old firmware and also models :) I am a bit cautious because I have failed-saved previously and almost lost the gear because of a faulty script (that I have written 😁)
