### ISSUE TITLE
Pocket: please add custom scripts to firmware

### ISSUE THREAD

**Issue by P-I-Engineer** [EdgeTX/edgetx#5636]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

the feature is not enabled for pocket builds and not an option in cloud builds

### Describe the solution you'd like

please enable it or add to cloud build options

### Describe alternatives you've considered

building myself in vsc or gitpod

### Additional context

it's needed for rotorflight telemetry

thank you

**Comment by 3djc** [comment]
Isn't that already addressed in https://github.com/EdgeTX/edgetx/pull/5303 ?

**Comment by P-I-Engineer** [comment]
looks like it is. 

thanks for the link
