### ISSUE TITLE
Trainer Settings: Multiplier has no effect in wireless Trainer setup

### ISSUE THREAD

**Issue by icebreaker-ch** [EdgeTX/edgetx#5639]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Multiplier setting in Trainer Settings has no effect. The documentation says:
Multiplier - This value changes the weight of all the sticks together. 
But regardless of the value set for Multiplier, the weight of the sticks is the same.

### Expected Behavior

I expected, to set multiplier for example to 0.5 and the input of the students transmitter weights only by 50%

### Steps To Reproduce

- Setup a trainer configuration by using a Multimodule in the Trainers transmitter.
- Change the value of Multiplier in the Sys->Trainer Settings.
- The weight of all sticks from the student transmitter do not change

### Version

2.10.5

### Transmitter

RadioMaster Zorro

**Comment by 3djc** [comment]
Unsure what your issue actually is. I did setup a wired trainer, and as you can see, multiplier does indeed affect values

![image](https://github.com/user-attachments/assets/d819fe11-65fe-44b1-a098-fe6adcc73684)

![image](https://github.com/user-attachments/assets/0ca488fc-bd94-446b-8258-a20ca1d471e2)

**Comment by icebreaker-ch** [comment]
And here the same pictures for my wireless Trainer setup:
![edited_20241025_163132](https://github.com/user-attachments/assets/e680ca00-cbe2-428a-9bf7-cb47b66143fc)
![edited_20241025_163149](https://github.com/user-attachments/assets/9a7ba6ba-85ab-412f-b0d2-63cfd6e7d998)

**Comment by 3djc** [comment]
Ok so a wireless trainer specific issue. Is that multi trainer ?

**Comment by icebreaker-ch** [comment]
I can confirm, that it works in a wired trainer setup, but not in my wireless setup.
I used the following combination: Trainer: Radiomaster Zorro 4in1 with a IRangeX IRX4 LITE Multi Protocol Module. Student: Radiomaster T8 Lite.

**Comment by 3djc** [comment]
In the current code, the value set in this multiplier field is called "PPM_Multiplier" and is applied **only** to DSC (training wire) port. So it does not apply to wireless, SBUS or any other trainer methods. So

1) we can change the UI to only display  this multiplier when DSC input is selected (and use mixer weight if you want to adjust it, which would make sense since you probably don't want the same weight for all control surfaces)

2) we change the code so it is applied for all forms of trainer (at teh risk of breaking existing setup)

**Comment by icebreaker-ch** [comment]
I leave it to you, how to solve this issue. Both variants are acceptable to me, because the use case I had (reducing the weight of the students input) can be achieved by setting the weights of the involved channels as well.
To have this in a single setting would have been just a convenience and probably is some kind of abuse of the multiplier factor either.
