### ISSUE TITLE
Model Timer 1 changes from On to Start when moving from OpenTX

### ISSUE THREAD

**Issue by sohamsp14** [EdgeTX/edgetx#566]
**Describe the bug**

When a timer is set in OpenTX as On with a switch. After conversion to EdgeTX model, the setting changes to "Start" and timer keeps counting down until it's changed to "Start" again. Also the Persistent option gets filled with gibberish. 

**To Reproduce**

Create Timer 1 on a model in OpenTX. 
Set name
Set mode = ON and a switch position. 
Set time
Set countdown = haptic , 30s
Set persistent = Manual Reset

Now flash EdgeTX and let the models get converted. In the new EdgeTX model, Mode becomes Start and sometimes there is gibberish in the Persistent field. 

**Expected behavior**

Timer settings should remain consistent after moving to EdgeTX

**Screenshots**

**General information**
 - EdgeTX version
2.4.0
 - Hardware
 RM TX16S

**Comment by pfeerick** [comment]
Similar to #403

**Comment by elecpower** [comment]
@pfeerick could be that bit shift in data conversion

**Comment by pfeerick** [comment]
Yup... #403 was the issue I had in mind when you first mentioned that, and this now suggests it is not radio family specific...

**Comment by elecpower** [comment]
Just checked the code and the 219 to 220 timer data conversion is not radio specific.
If you like I'll make a PR and then the theory can be checked?

**Comment by elecpower** [comment]
> When a timer is set in OpenTX as On with a switch

In OpenTX setting to ON does not also allow setting a switch eg SAup as they are in the same list so I'm a bit confused.

Confirmed bug in the data conversion for some fields but ON is not one I can reproduce.

Also I have found a display issue on color radios where the timer counts down then appears to count up but really it is a negative value but not displayed with a negative sign. On B&W radios displays with negative sign and flashes.

@sohamsp14 what version of OpenTX are you converting from and is it the version that came with the radio or one you downloaded and installed? Also could you please attach an unconverted OpenTX file so I can try to reproduce what you are seeing.

**Comment by elecpower** [comment]
@sohamsp14 do not worry about the OpenTX file as I have sorted it out. Thanks for reporting the issue
