### ISSUE TITLE
Trainer Mode Master/Serial turns Off when reading models and settings from radio to Companion

### ISSUE THREAD

**Issue by clarke-john** [EdgeTX/edgetx#5676]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Companion

### Current Behavior

When I ‘Read Models and Settings from Radio’ to Companion the setting for the ‘Trainer Mode’ changes from ‘Master/Serial’ to ‘Off’.
‘Write Models and Settings to Radio’ from Companion works fine and the Trainer Mode setting is not lost in this transfer.
I noticed this bug in February (version 2.9.4) but didn't report it.

### Expected Behavior

I would expect the Trainer Mode setting on the radio to be transferred to Companion.

### Steps To Reproduce

On a model in the radio, set 'Trainer Mode’ to ‘Master/Serial’.
Open Companion and connect radio to PC.
In Companion click on ‘Read Models and Settings from Radio’.
Open the model.
Check the setting for the ‘Trainer Mode’ and note that it has changed from ‘Master/Serial’ to ‘Off’.

### Version

2.10.5

### Transmitter

FrSky X10 / X10S (ACCST)

### Operating System (OS)

Windows

### OS Version

W11

**Comment by pfeerick** [comment]
I am able to reproduce this on TX16S also. 
- Set AUX1 to "SBUS Trainer", to enable the "Master/Serial" trainer option. 
- Configure Trainer Modeto be Master/Serial on handset
- Companion reads as OFF, although "Master/Serial" is in the list of options.

Also, "Master/SBUS Module" is missing as a trainer option in Companion, and results in a blank (not OFF) field.

**Comment by elecpower** [comment]
Thanks @pfeerick more work lol

**Comment by pfeerick** [comment]
Yeah, I know... that todo list never gets any shorter! 😆

**Comment by pfeerick** [comment]
Hm... #4266 is at least part of the reason for this, as it dynamically checks if the radio has hardware capabilities (which allowed a few more radios to have SBUS/CPPM option and also checks if it is in use by something else...

**Comment by clarke-john** [comment]
Thank you all very much for fixing this bug.  I look forward to it in the next release.

 

I also appreciate all the work and dedication the devs put into giving us this superb firmware for our radios.

 

Best wishes

 

John

**Comment by pfeerick** [comment]
Oh fiddlesticks, I think I forgot to include that fix in 2.10... it looks like it is only in for 2.11 :-/

**Comment by clarke-john** [comment]
Thanks Peter, I really appreciate what you guys do for us.  It is a brilliant system.

**Comment by pfeerick** [comment]
You'll be able to download a 2.10 Companion build with this fixed shortly:
- Linux - https://github.com/EdgeTX/edgetx/actions/runs/13042188324
- MacOS - https://github.com/EdgeTX/edgetx/actions/runs/13042188303
- Windows - https://github.com/EdgeTX/edgetx/actions/runs/13042188300
