### ISSUE TITLE
Invalid GPS coordinates

### ISSUE THREAD

**Issue by willannison** [EdgeTX/edgetx#568]
Using ghost telemetry. Gps coordinates are fine on the osd and on the oled screen of the ghost module but what is in the telemetry page is not a valid GPS coordinate. 
![IMG_20210806_082807](https://user-images.githubusercontent.com/40773221/128605318-075ceae9-85eb-43d7-b3af-d05250c6aa34.jpg)

**Comment by pfeerick** [comment]
Interesting... the Latitude is spot on... but longitude is wrong... 

![image](https://user-images.githubusercontent.com/5500713/128617895-55dab291-3055-4dfe-ab65-cfb273e97793.png)

Maybe a signing error, since that's a negative longitude...

**Comment by rotorman** [comment]
> Maybe a signing error, since that's a negative longitude...

Indeed, seems unsigned int is used:
https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L277-L278

https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L151-L157

**Comment by raphaelcoeffic** [comment]
> > Maybe a signing error, since that's a negative longitude...
> 
> Indeed, seems unsigned int is used:
> 
> https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L277-L278
> 
> https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L151-L157

Make sense to use an unsigned to assemble bits together. The question is: is the conversion to the value used at the end for angle computation properly converted?

**Comment by rotorman** [comment]
I guess it should be:
```
processGhostTelemetryValue(GHOST_ID_GPS_LAT, (int32_t)(getTelemetryValue_s32le(3) / 10));   
processGhostTelemetryValue(GHOST_ID_GPS_LONG, (int32_t)(getTelemetryValue_s32le(7) / 10)); 
```

as the processGhostTelemetryValue expects int32_t value field:
https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L99

Due to lack of hw, cannot test if that solves the issue though

**Comment by raphaelcoeffic** [comment]
> I guess it should be:
> 
> ```
> processGhostTelemetryValue(GHOST_ID_GPS_LAT, (int32_t)(getTelemetryValue_s32le(3) / 10));   
> processGhostTelemetryValue(GHOST_ID_GPS_LONG, (int32_t)(getTelemetryValue_s32le(7) / 10)); 
> ```
> 
> as the processGhostTelemetryValue expects int32_t value field:
> 
> https://github.com/EdgeTX/edgetx/blob/f5dec4e31edd8181e6a9925c31a03fa2cb659eef/radio/src/telemetry/ghost.cpp#L99
> 
> Due to lack of Ghost hw, cannot test if that solves the issue though

I should be able to check, as I have a ghost module. However, no GPS. Maybe this can be simulated.

**Comment by pfeerick** [comment]
If you have an Arduino handy, you might be able to mock it up...

This is the a dummy dataset for the TinyGPS library... if you just `Serial.println` each NMEA sentence and fed it in via serial connection that would probably do the trick. 

https://github.com/mikalhart/TinyGPSPlus/blob/cfb60e5e381c025ff7e52838897edab8a6e7d449/examples/BasicExample/BasicExample.ino#L9-L15

**Comment by raphaelcoeffic** [comment]
In fact, it might be even easier to fix if I would have some sample telemetry packets showing the issue, so I could “unit test it”.

**Comment by raphaelcoeffic** [comment]
> processGhostTelemetryValue(GHOST_ID_GPS_LAT, (int32_t)(getTelemetryValue_s32le(3) / 10));   
> processGhostTelemetryValue(GHOST_ID_GPS_LONG, (int32_t)(getTelemetryValue_s32le(7) / 10));

Possibly even this (conversion before division):
```
processGhostTelemetryValue(GHOST_ID_GPS_LAT, (int32_t)(getTelemetryValue_s32le(3)) / 10);   
processGhostTelemetryValue(GHOST_ID_GPS_LONG, (int32_t)(getTelemetryValue_s32le(7)) / 10); 
```

**Comment by raphaelcoeffic** [comment]
@willannison would you mind testing #625 ? I think this should be it.

**Comment by willannison** [comment]
Tested and it's working just fine! Thanks.
![IMG_20210823_160528](https://user-images.githubusercontent.com/40773221/130471538-8511944c-edb1-4c89-b829-8ee11f65860c.jpg)
