### ISSUE TITLE
LVGL line should supported dashed lines

### ISSUE THREAD

**Issue by arunh** [EdgeTX/edgetx#5680]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The new LVGL Lua API coming in 2.11 does not support a way to draw dashed lines. This is a useful graphical device and used by a number of widgets, and makes it hard to port a widget to the new library if it needs this functionality.

### Describe the solution you'd like

The LVGL library itself has support for dotted and dashed lines so this just needs to be exposed in the EdgeTx Lua API.

https://docs.lvgl.io/8/overview/style-props.html#line-dash-width
https://docs.lvgl.io/8/overview/style-props.html#line-dash-gap

**Comment by philmoz** [comment]
In LVGL dash gap and dash width only work for horizontal and vertical lines.

If that limitation is acceptable I can add these as properties to the 'hline' and 'vline' types.

**Comment by arunh** [comment]
Horizontal and vertical is acceptable. Thank you.
