### ISSUE TITLE
NV14 does not boot

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#569]
**Describe the bug**
NV14 does not boot with the current SW.

**To Reproduce**
Flash the FW.
Switch the TX ON.
Observe the screen giving a single flash and TX hangs.
After removing the batteries it  is possible to get into the bootloader screen.

**General information**
 - EdgeTX version current code
 - Hardware NV14

**Comment by raphaelcoeffic** [comment]
@eshifri do you have an idea when it started not working? Maybe which commit did this?

**Comment by eshifri** [comment]
@raphaelcoeffic 
I'm not sure. It was either change in the Cmake version or, more likely, unified ADC driver.
On the other hand I have spent a couple of hours on the ADC driver code and I had not found anything suspicious enough.

It was definitely not working after the CMake games, but I'm not sure I was building it after the ADC changes.

**Comment by eshifri** [comment]
I rebuild the FW with -DUNEXPECTED_SHUTDOWN=NO and it works now.
Weird.

**Comment by pfeerick** [comment]
I've noticed after the CMAKE update some options _seem_ to act differently at times... but it could just be my imagination or I hadn't noticed it before. Also, when you set a flag with CMAKE, you specifically need to turn it off again (unless you clean your build directory out)... i.e. explicitly setting `-DUNEXPECTED_SHUTDOWN=NO` on one build, and then not specifying it when re-running CMAKE means it will still be set to no... you actually have to set it to `YES` to make it toggle back.

**Comment by raphaelcoeffic** [comment]
> I've noticed after the CMAKE update some options _seem_ to act differently at times... but it could just be my imagination or I hadn't noticed it before. Also, when you set a flag with CMAKE, you specifically need to turn it off again (unless you clean your build directory out)... i.e. explicitly setting `-DUNEXPECTED_SHUTDOWN=NO` on one build, and then not specifying it when re-running CMAKE means it will still be set to no... you actually have to set it to `YES` to make it toggle back.

This is normal, the settings are cached in CMakeCache.txt.

**Comment by pfeerick** [comment]
Yeah, the settings caching is normal... it was more things like what was happening with internalgps... not taking... or at least I think it was... it eventually seemed to do what it was told in the end...

**Comment by eshifri** [comment]
Looks like it fixed itself. At least i do not see this problem any more.
