### ISSUE TITLE
Enhancement - some menus don't jump to first entry

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#57]
As a concrete example, with a TX16S, if you go to the 'select models' screen, and press enter, the popup menu (select model, create model, duplicate model, delete model - or just create model and duplicate model if you select the active model) will appear, but you will need to roll the scroll wheel to highlight the first item on the menu. Which gets annoying if you scrolled to select your model, and then have to roll the scroll wheel to highlight select rather than just press enter the second  time. 

Whilst it would be counter-intuitive for a touch screen only interface, given that most of the transmitters are a hybrid of both button and touch-screen interaction - or can be - the first item should be 'jumped to' automatically. Somewhat similar to a combo box that will highlight the currently selected item automatically (i.e. Radio Setup -> Mode -> jumps to the currently selected 'NoKey' when the list shows). 

It's possible this is on the only menu that does this... I'll edit this if I encounter another.

So far, it is:
* Select model -> menu for active or inactive model
* Insert USB lead -> USB menu
* Widget setup -> setup widgets (top menu or panel) -> touch a box for a widget -> actions menu  (minor secondary issue - when selecting a empty widget box, menu background sizing suggests there would be two entries, but there is only one)
* Following on from last point -> the widget selection menu shown when you choose 'select widget'
* Model setup => Inputs, Mixes, and Outputs, Curves, Global Variables, Logical Switches, Special function line item menus (once entry exists)

**Comment by raphaelcoeffic** [comment]
@pfeerick please make a list of any other you find, so I can batch-fix them.
