### ISSUE TITLE
sqt5 font option

### ISSUE THREAD

**Issue by timemaster5** [EdgeTX/edgetx#570]
Hi guys, I wanted to try EdgeTx and realised that there are no build options like we used to have in OpenTx. I assume everything is enabled for now, which is perfectly fine. I am only wondering about that alternative font, I know its probably a lowest priority, but for me on a small 128px display, it is for some reason much more readable font than the original one. Can I somehow enable it?

**Comment by pfeerick** [comment]
Is that the sqt5 font? I think it can be for the B&W transmitters... What one are you using... T-Lite? I can do a custom build for that if you want it...

**Comment by timemaster5** [comment]
Yes, it is. Sorry, I could swear, I saw it somewhere called "alternative".
Never mind. If you could do that, it would be awesome.

**Comment by pfeerick** [comment]
Yeah, when you hover over the option in opentx companion it says it's the 'alternative sqt5 font', so that is probably what you are thinking of ;)

I assumed the following for the build settings (looks like S and Pro are the same build)... let me know if you need/want something different:

```
-DPCB=XLITES -DHELI=NO -DGVARS=YES -DLUA=YES -DFONT=SQT5
 ```

[edgetx-f5dec4e-xlites-noheli-gvars-lua-sqt5font.zip](https://github.com/EdgeTX/edgetx/files/6951680/edgetx-f5dec4e-xlites-noheli-gvars-lua-sqt5font.zip)

**Comment by timemaster5** [comment]
Thank you very much, I checked my settings, and OpenTX reporting these: Bluetooth, crossfire, ghost, frexr9m, noheli, internallaccess, multimodule, lua, luac. Currently, I use all of it with different models. Maybe except Bluetooth which is only for a trainer mode in my case.

**Comment by pfeerick** [comment]
Man... was the sqt5 font not enough for you? 😆 

`simu` is giving me this, so it should be everything you're after...
![snapshot_01](https://user-images.githubusercontent.com/5500713/128793713-77823f8d-1221-4541-8213-54471cbbed3e.png)

```
cmake -Wno-dev -DPCB=XLITES -DHELI=NO -DLUA=YES -DGVARS=YES -DFONT=SQT5 -DMODULE_PROTOCOL_FLEX=YES -DAFHDS3=NO ../
```

[edgetx-f5dec4e-xlites-noheli-lua-gvars-sqt5font-flexr9m-noafhd3s.zip](https://github.com/EdgeTX/edgetx/files/6958275/edgetx-f5dec4e-xlites-noheli-lua-gvars-sqt5font-flexr9m-noafhd3s.zip)

**Comment by timemaster5** [comment]
Haha, it's well-used radio I guess :) Thank you very much, I will test and try to be more useful :)

**Comment by pfeerick** [comment]
No problem, hope it works for you!

**Comment by timemaster5** [comment]
Just tested, and works perfectly!
