### ISSUE TITLE
UI overlay at radio shutdown

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx#5704]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

![WhatsApp Image 2024-12-11 at 18 37 07_a201194a](https://github.com/user-attachments/assets/acaeaf52-c550-468e-b30a-7784370e5fea)

### Expected Behavior

Black background

### Steps To Reproduce

1. Power radio and connect to receiver
2. Edit SF and bring up trigger selection
3. Shutdown radio with receiver still connected and trigger selection menu still on screen

### Version

Nightly (Please give date/commit below)

### Transmitter

Other (Please specify below)

### Anything else?

T15 - current nightly t15-3d1e7a9.bin

**Comment by philmoz** [comment]
There can be any content and number of layers present when a warning dialog like this pops up.
At the moment the code assumes a single layer and tries to hide it - which of course does not work in this case.

Simplest solution is to make the warning dialog background opaque:
![IMG_2058](https://github.com/user-attachments/assets/c9679cf6-4b51-4fdb-aa26-8420ed7b6845)

**Comment by pfeerick** [comment]
Something similar happened again the other day with the failsafe warning.
Full screen alert should always take exclusive control of the full
screen/view so opaque background would work. Wasn't there an image shown
there at some point?

**Comment by philmoz** [comment]
Current warning will show the theme background if there is only one layer to hide.
