### ISSUE TITLE
Timers Not Incrementing In Synchronized Manner

### ISSUE THREAD

**Issue by unklstewy** [EdgeTX/edgetx#571]
While configuring a new quad model I was setting up some timers on my main screen when I noticed that the timers appear to be out of sync.

Timer2 Lagging:
[Youtube: Timers Out of Sync](https://youtu.be/z5PVKw-6qhk) 

Setup:
Radio: Radio Master TX16S Max
EdgeTX: 2.4.0

TIMER1:
![16283656713616338685255109149191](https://user-images.githubusercontent.com/18333704/128612287-33f4c8f6-f2ab-4a1c-8c13-fa8d2277cd85.jpg)

TMER2:
![16283657364994115367715663798741](https://user-images.githubusercontent.com/18333704/128612306-1252079b-940c-415b-a006-b5c9aa4f722f.jpg)

TIMER1:
Starts with First Arm (SF FWD) and Pauses with Disarm (SF BACK). Reset Configured with:

Logical Switch:  L02 
![16283659419481902738652265887536](https://user-images.githubusercontent.com/18333704/128612376-e35b0139-c457-4d48-9371-fd28f0f882c5.jpg)
&
Special Function: SF2
![16283660547043842481312556799920](https://user-images.githubusercontent.com/18333704/128612410-b54c0bb8-dec5-4f51-8a28-8976e935951f.jpg)

TIMER2: Stars with Arm Switch (SF FWD) and Stops+Resets with Special Function: SF1
![16283661629718317989000700106999](https://user-images.githubusercontent.com/18333704/128612445-4416ba8a-b5de-4249-baa6-213df2c55952.jpg)

Are these timers running sequential interrupts, or is the use of special functions and logical switches causing TIMER2 to have a delay in the GUI?

-Casey

**Comment by raphaelcoeffic** [comment]
@unklstewy I think this might be caused by the widget refresh on screen not being synced. They refresh with the same frequency, but not at the same moment.

**Comment by unklstewy** [comment]
I imagine that be something in LUA's sequential processing.  I guess I wasn't expecting a 300ms -500ms delta in the display times.

**Comment by raphaelcoeffic** [comment]
> I imagine that be something in LUA's sequential processing. I guess I wasn't expecting a 300ms -500ms delta in the display times.

In this case it's not LUA, it's one of the C++ Widgets. We might try to refresh whenever the value has changed instead of some fixed (non-synced) pace.

**Comment by unklstewy** [comment]
@raphaelcoeffic 

Thank you for taking the time to look into it and get back with me.  You guys are killing it with the development pace!  Kudos.

**Comment by gagarinlg** [comment]
This does not happen in main
