### ISSUE TITLE
GX12/ETX 2.11.0 (factory build): cannot set mixer weight to a GV

### ISSUE THREAD

**Issue by RC-SOAR** [EdgeTX/edgetx#5710]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

In the mixer editor, when attempting to set the weight or offset of a mix to a GV, the mixer editor inserts a large (>100%) weight. 

### Expected Behavior

The editor should accept a GV as weight and display it.

### Steps To Reproduce

Create a mix, and try to set the weight to say GV1.

### Version

Other (Please specify below)

### Transmitter

RadioMaster GX12

### Anything else?

2.11.0-selfbuild d5552c80 (supplied with review system)

**Comment by 3djc** [comment]
Could try latest nightly ? Seems ok here

![image](https://github.com/user-attachments/assets/4e3d0fb0-0557-496a-bc5f-928fe4e4995b)
