### ISSUE TITLE
Simulator on Linux: SEGV every time the simu reloads a modified widget

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#5737]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Simulator

### Current Behavior

Reloading a modified widget crashes the simu

### Expected Behavior

No crash

### Steps To Reproduce

1) Start simu
2) load a widget
3) modifiy the widget
4) reload

-> crash

### Version

Nightly (Please give date/commit below)

### Transmitter

RadioMaster TX16S / TX16SMK2

### Operating System (OS)

Linux

### OS Version

Arch Linux

**Comment by philmoz** [comment]
Already fixed in PR #5732 - just waiting for it to me merged.
