### ISSUE TITLE
Radiomaster TX16 - Internal Bluetooth

### ISSUE THREAD

**Issue by IdefixRC** [EdgeTX/edgetx#574]
Hi there,

OpenTX provides a version of the firmware which enables the TX-16 internal Bluetooth port.
I could not find any info in the documentation regarding BT for TX16 so I assume it is not included in the EdgeTX FW.
Would it be possible to release a version of the EdgeTX firmware with BT enabled?

Thanks !

**Comment by pfeerick** [comment]
When we have the online build system in place, you'll be able to pick options like this for yourself (this is what is happening when you hit the download option in OpenTX companion - it's looking to see if there is a cached build already of the firmware you've requested, or it will task their build server to build it on demand). 

I've assumed these build options, and built off the latest commit firmware - let me know if you want a different configuration or version:

``` -DBLUETOOTH=Y -DGVARS=Y -DHELI=N -DLUA=Y```
[edgetx-tx16s-f5dec4e-bluetooth-gvars-noheli-lua.zip](https://github.com/EdgeTX/edgetx/files/6951797/edgetx-tx16s-f5dec4e-bluetooth-gvars-noheli-lua.zip)

**Comment by IdefixRC** [comment]
Thanks a lot. Could you drop one with the same settings but heli enabled
please? Thanks a million

**Comment by pfeerick** [comment]
lol... What... ... you actually *use* heli? grrr! It'll cost you! 😝 

[edgetx-tx16s-f5dec4e-bluetooth-gvars-heli-lua.zip](https://github.com/EdgeTX/edgetx/files/6951894/edgetx-tx16s-f5dec4e-bluetooth-gvars-heli-lua.zip)

**Comment by IdefixRC** [comment]
Haha, thanks!

**Comment by pfeerick** [comment]
No problem. Let me know if you need anything else ;)

**Comment by IdefixRC** [comment]
Thanks 👍🏻

**Comment by SilentZen** [comment]
Tested this build and compiled it myself. Bluetooth discover seems to be missing under model/trainer on both.

**Comment by pfeerick** [comment]
That for that @SilentZen ... we'll track it in https://github.com/EdgeTX/edgetx/issues/583

**Comment by Millerboy3** [comment]
Tested your custom build and it works like a charm to show things in menu's on my tx16s. Good work.  Will be awesome when the build server is up and we can enable it that way.   Thanks for this!

**Comment by SilentZen** [comment]
Where is the source for this fix?

**Comment by pfeerick** [comment]
? No fix, Millerboy3 said it works *sans discover* (minus discover) ;) Nothing has changed here yet.

**Comment by SilentZen** [comment]
Ahh, thanks
