### ISSUE TITLE
Wrong display color for BMPs

### ISSUE THREAD

**Issue by LimitlessGreen** [EdgeTX/edgetx#582]
The review of an BMP file in the NV14 has the wrong color.
I also tested JPG and PNG and these are fine. 

**Screenshots**
I did a quick color channel swap with GNU Octave:
![color_issue_1](https://user-images.githubusercontent.com/15064073/128908712-9e972f3f-7753-4075-81aa-10dec5d756fa.jpg)
![color_issue_2](https://user-images.githubusercontent.com/15064073/128908724-5505a96c-1c98-4095-a3c8-35ff1b1f30fc.jpg)

For me, it looks like the NV14 is displaying BRG instead of RGB.

**General information**
 - EdgeTX version (2.5.0 nightly, f5dec4e31edd8181e6a9925c31a03fa2cb659eef)
 - Hardware (FlySky Nirvana NV14)
 
[sample.zip](https://github.com/EdgeTX/edgetx/files/6964237/sample.zip)

**Comment by LimitlessGreen** [comment]
I uploaded the sample bmp. Maybe jpg wasn't ideal for this case.
The color top bar from picture to picture in picture from the original: 
- #105c98 rgba(16,92,152,255)
- #d05070 rgba(208,80,112,255)
- #c8c080 rgba(200,192,128,255)

**Comment by pfeerick** [comment]
Actually, it's not NV14 specific, it is the same on the TX16s, and was something that changed a few months ago, so is possibly something to do with libopenui... https://github.com/EdgeTX/edgetx/issues/293
