### ISSUE TITLE
[TX16/T16] Bluetooth missing, Bluetooth Trainer missing Discover

### ISSUE THREAD

**Issue by Guillesan** [EdgeTX/edgetx#583]
Hello guys.  I have installed Edge 2.4 in a Jumper T16, I have a bluetooh module installed in it, with OpenTX it worked for me but in Edge there are no traces of being able to configure it or see the connection.  my question is whether the bluetooh is implemented or not.  Thanks

**Comment by SilentZen** [comment]
Trainer mode under model when selecting Master/Bluetooth seems to be missing Discover and instead has channel range options.
No option to select dist address.

**Comment by pfeerick** [comment]
Bluetooth is a compile time option, so will not be present unless you build it yourself (or get someone to build it for you) until we have the online build system up and running. And as has been pointed out by SilentZen, it seems like some options are not implemented / missing still.

**Comment by iggut** [comment]
NV14 module is also not used by the looks of it.
