### ISSUE TITLE
NV14 Bootloader up/down action will cause exit action

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#597]
Bootloader problem that works in older version.  Suspect that this is caused by the changes in keys driver.

 - EdgeTX version main nightly
 - Hardware Flysky NV14

**Comment by pfeerick** [comment]
Fingers crossed mine turns up tomorrow :) 

I can't see it, but I'm sure this was mentioned before... so it seems to be something that comes and goes! 😆

**Comment by raphaelcoeffic** [comment]
From what I can see, it seems the "Down" key is actually triggering "Exit" key 😝
