### ISSUE TITLE
Tools incorrectly populated

### ISSUE THREAD

**Issue by olliw42** [EdgeTX/edgetx#60]
this can happen every once in a while
seems to be more likely when on is pressing various keys fast

![IMG_20210520_230751](https://user-images.githubusercontent.com/6089567/119049259-9b949f00-b9c0-11eb-8c06-6aca8d3d2666.jpg)

**Comment by rotorman** [comment]
Happens on my TX16S similarly. The fields to the right of lua are filled with random stuff it seems, and not with the names of the LUA scripts from the SD card TOOLS subfolder.

**Comment by rotorman** [comment]
Here is a video showing this. I was regularly able to induce this on TX16S, by hitting:
1) System key
2) Page > key
3) Page < key

https://www.youtube.com/watch?v=RVlaJLJoL8A

**Comment by raphaelcoeffic** [comment]
Here I think it's even worst, as my SD card is full of MacOS garbage (`._whatever` files....), which seems to confuse the file scanning. I'll give it a shot.

**Comment by olliw42** [comment]
that's another thing, that I now constantly have to repair the SD card ... (even in normal operation)

**Comment by raphaelcoeffic** [comment]
> that's another thing, that I now constantly have to repair the SD card 

That's not normal. Never had that. Maybe the card is starting to fail?

**Comment by raphaelcoeffic** [comment]
Please note that the script are not yet working all correctly, as there is still some issue with the file loading. The "tools" screen is now correctly populated however.
