### ISSUE TITLE
NV14 UI Problem

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#600]
There are a lot of problems in NV14 UI, because the screen orientation is quite different with other support color radios.

Fix includes:
- protocol selector, used next line for sub-protocol
- diagnostic screen
- more layouts: 1+2, 1x2, 1x4
- better implementation of CN/TW date representation
- ..... what more, please comment.

**General information**
 - EdgeTX main nigntly
 - Hardware Flysky NV14

**Comment by zhoumigo** [comment]
博士 整个默认主题吧  得搞搞SD卡文件了

**Comment by richardclli** [comment]
If no more ideas, will stop at this point and work on others.
