### ISSUE TITLE
On NV14 exit button does not work in the new topbar layout

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#609]
**Describe the bug**
The top left icon in the top bar does not work as "Exit" button.
This happens in all screens: Model Settings, Radio Settings, Channel Monitor, Screen Settings

**To Reproduce**
Touch EdgeTX icon in the top left corner of the screen.
Select Model Setup in the carousel (or any other option).
Touch top left icon in the topbar.
Nothing happens.

**Expected behavior**
Top left button should work as exit.

**General information**
 - EdgeTX latest code
 - Hardware NV14.

**Comment by eshifri** [comment]
Actually, it does not happen all the time.
It works after reboot.
Than problems appear.
Sliding top-bar back and force restores functionality for some time.

**Comment by richardclli** [comment]
Maybe the button just too small for big fingers.  I never have this problem, well maybe my finger is small.

**Comment by eshifri** [comment]
My fingers are also small and it did happen before the changes to top bar.
So while it very possible that the problem is the small button, looks like something has changed.

**Comment by pfeerick** [comment]
Got this a few times last night - I do have to wonder if it is the size of the touch area, as the edges are really hard to get at with the bezels... have to try with a touch pen to see if that is all that it is.

**Comment by eshifri** [comment]
I think you are right: I have tried to use a touch-pen (does not work too well), but i realized I need to push a pen/ a finger into the very corner of the screen.

**Comment by richardclli** [comment]
Not sure how the touch control is implemented.  For best experience, the touch control can use some fuzzy algorithm to guess the user's intention and fire appropriate event.  i.e. Even the touch point is outside the display area of a button, we can still trigger the button based of distance between the the touch point and different touch triggerable widgets.

I guess the current implementation is the touch triggerable area = display area.

**Comment by pfeerick** [comment]
@eshifri If you're interested, I found out the *what* is happening when playing with simu... the hitbox is only about this big 😆 ... which is the *why* as to why it's so awkward on the NV14 (because of the screen bezel). Now, as the what bit of code controls that, I can't place that yet - whatever it is, it seems the same on model settings and radio settings, but the full logo/icon elsewhere...


![image](https://user-images.githubusercontent.com/5500713/135064186-d711d029-bbc3-4953-b2f5-172c36a15aa4.png)
