### ISSUE TITLE
[NV14] ExpressLRS not connecting

### ISSUE THREAD

**Issue by rentacheese** [EdgeTX/edgetx#621]
**Describe the bug**
Once in the ExpressLRS Lua script, the script does not connect to the external module anymore, I've tried rebooting and even taking out the module and putting it back in while in the connecting screen which previously worked for me.

**To Reproduce**
Happens anytime I open the lua script

**Expected behavior**
should be able to connect to the external module and display all the info about the external module

**General information**
 - EdgeTX version (nightly build, #83413a2 (2021-08-22T02:22:42z))
 - Hardware (NV14)

**Comment by LimitlessGreen** [comment]
Related to #613
Should be fixed in 9509569
Just test the latest run (https://github.com/EdgeTX/edgetx/runs/3394103619 at the moment)
