### ISSUE TITLE
Tidy Up Translations

### ISSUE THREAD

**Issue by richardclli** [EdgeTX/edgetx#628]
Translation codes are quite messy at this moment.

Will try to tidy up the translations definitions, source generations, etc.

**General information**
 - EdgeTX main nightly
 - Hardware all

**Comment by ulfhedlund** [comment]
I just ran the lupdate command on my local main branch and there were a few warnings, four of them related to context UpdateCompanion that I tried to fix (but chances are not at all correctly). A developer needs to do that, not me.

lupdate ./companion -ts ./companion/src/translations/companion_sv.ts

./main/companion/src/updates/updatecompanion.cpp:36: tr() cannot be called without context
./main/companion/src/updates/updatecompanion.cpp:41: tr() cannot be called without context
./main/companion/src/updates/updatecompanion.cpp:46: tr() cannot be called without context
./main/companion/src/updates/updatecompanion.cpp:52: tr() cannot be called without context

**Comment by richardclli** [comment]
Not relevant anymore, close it.
