### ISSUE TITLE
Logical switch function `a~x` not showing properly

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#633]
Reported via DM

Logical switch "a~x" shows as "ax" on colourlcd radios (and `a->x` FWIW on X9D+), although it is present in the translation correctly... so something is mangling the display of it. It does not effect the operation of the function. 

https://github.com/EdgeTX/edgetx/blob/7c495fba3e6f4de1317854827465ec900f26ef67/radio/src/translations/en.h.txt#L169

**Comment by eshifri** [comment]
Looks like "~" sign does not exist in the fontspecs

**Comment by eshifri** [comment]
Looks like neither TTF nor extra_NNpx.png do not have "~" symbol.

**Comment by gagarinlg** [comment]
fixed in main already
