### ISSUE TITLE
Bootloader and Startup screen background 

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#638]
So we already started this with @raphaelcoeffic but stalled waiting for 2.5 UI rework

So here is preview
1. Startup screen
![Splash](https://user-images.githubusercontent.com/46420768/130790118-0f510f33-e638-4aa8-8e99-fc683ae03faf.png)
2. Bootloader
![Bootloader](https://user-images.githubusercontent.com/46420768/130790206-e7291c70-29ac-4d34-936d-c4dc8363ab02.png)

Do here is how to do:
1. Tile (535 bytes)
![bkg_holes_tile](https://user-images.githubusercontent.com/46420768/130790406-00e77a43-78c7-48d9-96ff-af4a3dbdfaed.png)
2. Full Mask (48kB)
![bkg_holes_mask](https://user-images.githubusercontent.com/46420768/130790440-bdc03070-9118-44db-86b1-e1a30e2a7cf2.png)
3. Quarter Mask (12kB)
![bkg_holes_mask_025](https://user-images.githubusercontent.com/46420768/130790525-d37dadf5-b7b6-4863-8df8-2115ea691d45.png)

So to reduce mem usage trick is to get Quarter mask duplicate 3 times, rotate and position in right place
Should be 100% symmetrical. If not I'll replace it
@pfeerick @richardclli feasible?

**Comment by pfeerick** [comment]
This will definitely happen in 2.9, if only because we now want to better support different screen sizes! 😆

**Comment by froqstar** [comment]
That mesh background feels a bit too much like 2000 era design to me. 
Isn't the trend towards more flat design? I would even prefer a completely black/grey background TBH. But that's just me.

**Comment by pfeerick** [comment]
Radio trend seems to be more towards things like carbon fiber look and colour atm, but like everything it has its cycles... todays 2000 era "boring" is 2025's craze again.

**Comment by pfeerick** [comment]
#2764 only resolves this in part, I don't think it touched the bootloader background, only the default splash screen background.

**Comment by JimB40** [comment]
@pfeerick I dont insist on fancy background. We can go with simple black bkg. Just not that cheese :) 
Also this concept to display EdgeTX version and build under logo on splash screen has advantage. You see trouble shooting picture or video and you don't have to ask user what version he has. This should resolve many issues with wrong firmwares loaded

**Comment by pfeerick** [comment]
> We can go with simple black bkg.

I'm actually starting to think looking that second image in the first post a flat / matt background for the bootloader might be better... the honeycomb actually makes it quite noisy - the current one at stays in the background more. 

> Also this concept to display EdgeTX version and build under logo on splash screen has advantage. You see trouble shooting picture or video and you don't have to ask user what version he has. This should resolve many issues with wrong firmwares loaded

That will only apply to the default splash screen, so will invariably still need to ask the majority of users to go to the SYS -> Version page, but yes, it should help a bit.
