### ISSUE TITLE
edit one mix remove all the next mixes in the list

### ISSUE THREAD

**Issue by ishay320** [EdgeTX/edgetx#658]
**Describe the bug**
the bug is when edit the source of a mix to be nothing (-), the list from that element is removed.

**To Reproduce**
open model menu and go to mixes,
select mix from the middle of the list and edit it,
in source select nothing (-)
return

**Expected behavior**
it should keep the tag and all other mixes.

**Screenshots**
the original list:
![ecbdaf90-0120-4693-98f0-cbd9a79e7e8a](https://user-images.githubusercontent.com/65709059/131387703-4775d0e2-851b-4fda-925a-4a6d7a8e5450.jpg)

edit it to be nothig:
![5fe9176a-261c-4b0a-9c2a-096d7e62ecaf](https://user-images.githubusercontent.com/65709059/131387742-35d8d455-2d22-464c-a488-e1b00c1262ed.jpg)

the list after:
![2c0d4e75-f246-4df7-aa07-3f9e59907a82](https://user-images.githubusercontent.com/65709059/131387767-27a81228-aa47-4430-960a-a5abb3227962.jpg)

**General information**
 - EdgeTX version2.4.0
 - Hardware RM TX16S

**Comment by eshifri** [comment]
Is it the same if you just remove this mix?

**Comment by pfeerick** [comment]
On basically yesterday's nightly, if you delete a mix line, other rows are unaffected. This bug is also reproducible there, but not on B&W - perhaps partly because on B&W once you have set "a" source, it can't ever be set to "---" again.

**Comment by eshifri** [comment]
B/W does not use libopenui, so it is completely different implementation of the mixies screen.

**Comment by pfeerick** [comment]
For the UI, yes, but this does not automatically rule out an issue with shared/common functions.

**Comment by eshifri** [comment]
https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/colorlcd/model_mixes.cpp#:~:text=for%20(uint8_t%20ch,grid.getFieldSlot()%2C%20mixIndex)%3B

  for (uint8_t ch = 0; ch < MAX_OUTPUT_CHANNELS; ch++) {
    if (mixIndex < MAX_MIXERS && mix->srcRaw > 0 && mix->destCh == ch) {

      coord_t h = grid.getWindowHeight();
      auto txt = new MixLineTitle(window, grid.getLabelSlot(),
                                  getSourceString(MIXSRC_CH1 + ch),
                                  BUTTON_BACKGROUND, COLOR_THEME_PRIMARY1 | CENTERED);

      uint8_t count = 0;
      while (mixIndex < MAX_MIXERS && mix->srcRaw > 0 && mix->destCh == ch) {
        Button * button = new MixLineButton(window, grid.getFieldSlot(), mixIndex);

**Comment by pfeerick** [comment]
I'm not so sure it is this... yet as it's not cosmetic - the mixes are actually gone. If you check the channel monitor there is no output anymore :-/. i.e. if you have four channels, edit the second, set the source to `---` and then exit the page... you only have one active channel.

**Comment by eshifri** [comment]
If I fix this code, mixes are shown and preserved, but all mixes after the one without source become inactive and channel monitor does not show them.

**Comment by pfeerick** [comment]
Yes, that is what I feel is the real problem... I just haven't been able to place where exactly the mixes are being deleted/inhibited.

**Comment by eshifri** [comment]
https://github.com/EdgeTX/edgetx/blob/main/radio/src/mixer.cpp#:~:text=for%20(uint8_t%20i%3D0%3B%20i%3CMAX_MIXERS,break%3B

If this break is changed to continue, everything works.
I do not know what protection mechanisms this can break. :-)

**Comment by pfeerick** [comment]
You mean protection mechanisms can break? 😆 
https://github.com/EdgeTX/edgetx/blob/cea723c56ea52db45911e4e5cbe4485cb40c23b4/radio/src/mixer.cpp#L650-L651

At least you found the culprit, now it's just a matter of determining the ~~punishment~~ fix for it. :) 

btw, for sharing links to sections of code, it is much better if you if you can use the line number / permalink option in github... it then shares the line number in the URL, and even interpets it itself in issues like above. You can click on the line number for a single line, or click on the first line, and then shift+click to highlight a code range.

![image](https://user-images.githubusercontent.com/5500713/131602883-dfe7ae86-48d0-462e-9c23-a11f3fb33847.png)
