### ISSUE TITLE
GUI Thread crash after supplying trainer via sbus in

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#662]
I can crash the gui thread using

1) new model
2) trainer-serial
3) feed some sbus signal
4) try to calibrate the trainer signal, select calibrate
5) gui freezes
6) main thread still works: get trainer lost if sbus is pulled out
7) can't switch off, have to unplug the battery

**Comment by dlktdr** [comment]
I have a potential solution here https://github.com/dlktdr/edgetx/commit/2e5c96bf4bb4d1b2884e622e7067b497b7c6f913. 

Looks like it's trying to set the value but another update comes in and crashes the GUI. An option is to go to the way OTX did it with a calibration button to calibrate all at once which works well, disabling the events on the number edit so they just show the data.

![image](https://user-images.githubusercontent.com/281145/133028715-2729725e-8ae8-4b5f-966d-db1d0abe0b45.png)

**Comment by pfeerick** [comment]
I think the button is all that is needed... I don't think the values have ever actually been 'configurable in any way... just shown so you can see if they are crazy values or something is wrong with the trainer. You can't even edit those values in Companion - it's read-only as well.

**Comment by dlktdr** [comment]
Ok. I'll make a pull request on this one then you can review.

**Comment by pfeerick** [comment]
Do you think there is any value to having them read only NumberEdits, rather than some form of StaticText/drawText?

**Comment by dlktdr** [comment]
No I don't think so, I guess static would make more sense. Let me change that... Ignore pull for now..

**Comment by gagarinlg** [comment]
Is this fixed?
