### ISSUE TITLE
Exiting number-edit causes crash

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#666]
**Describe the bug**
After using touch-screen number edit there is no way to remove the virtual keyboard.
Touching EXIT button in the top left corner causes crash.

**To Reproduce**
Go to setup screen 
Create a widget (e.g. Value->Time).
Touch color; number-edit keyboard is open.
Change the color
Touch anywhere outside the keyboard - the keyboard does not go away.
Touch upper left corner of the screen - the system goes into emergency mode.
If exiting with RTN button everything is OK.

**General information**
 - EdgeTX version current
 - Hardware RM TX16S.
 - On NV14 the system crashes even with RTN button.
This is a new problem that was created with the latest changes to libopenui (virtual keyboard).

**Comment by pfeerick** [comment]
Will be fixed by https://github.com/EdgeTX/libopenui/pull/16, just waiting for it to be reviewed and merged.
