### ISSUE TITLE
Continuous scrolling of screens

### ISSUE THREAD

**Issue by stefaanbolle** [EdgeTX/edgetx#668]
When scrolling between the screens when reaching the last screen, scrolling right stops and at the first screen scrolling left stops. It would be great to have continuous scrolling possible. When reaching the last screen it scrolls right to the first screen and when reaching the first screen, scrolling left displays the last screen.

**Comment by raphaelcoeffic** [comment]
@stefaanbolle I think this is possible with the keys (previous page on first page will take you to the last one).

**Comment by stefaanbolle** [comment]
Would be nice if swiping would also allow for this behavior

**Comment by gagarinlg** [comment]
still missing for swiping

**Comment by gagarinlg** [comment]
I checked LVGL. Currently it is not possible to implement this.
