### ISSUE TITLE
Binding procedure doesn't work on T18 for R9M ACCESS

### ISSUE THREAD

**Issue by ViorelX** [EdgeTX/edgetx#670]
I have compiled EdgeTX for T18 target with 'externalaccessmod' feature and, of course, I have made the hardware modification.
I tried to get working a R9M module with a R9 MM-OTA receiver. I can do the 'register' procedure, it works and finally appears the 'registration OK' message, but the binding process cannot be accomplished.
I have to revert to OpenTX to do this, then I install back EdgeTX and the receiver remains bound.

**Comment by ViorelX** [comment]
Moreover, I have noticed:
-there is not the 'options set' button for the R9M transmitter;
-the 'receiver no' field is also missing;
-the transmitter does not transmit output channel data to the receiver (but it transmits telemetry).

**Comment by gagarinlg** [comment]
fixed with #991
