### ISSUE TITLE
Colourlcd - Model Outputs - GV for Subtrim, Min, Max values

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#683]
OTX allows for a Models channel Outputs subtrim, Min and Max values to be linked to a GV... i.e. 
![image](https://user-images.githubusercontent.com/5500713/132160585-15fd1f60-d636-4960-b237-bbd38de326d1.png)

Whereas this does not currently seem possible on the colourlcds at pressent... (yes, I know this is NV14 screenshot, but same applies) ... perhaps a similar long press (and long touch?) toggle? 
![snapshot_13](https://user-images.githubusercontent.com/5500713/132160651-1a543490-0cb9-4b0b-bbdb-4fecf6f21a95.png)

**Comment by eshifri** [comment]
Can't we do it just with class GVarNumberEdit?
Similar to mixes.

**Comment by eshifri** [comment]
I'm submitting PR; please take a look.
