### ISSUE TITLE
Companion - Timers

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#692]
Self-build of Companion on Windows

The switch setting for Timers is now valid for THs (Throttle Start), TH% (Throttle %) and THt (Throttle) as well, but companion disables the ability to set/change the switch setting. Spotted by @MervDale

![image](https://user-images.githubusercontent.com/5500713/132619223-3f4326da-5322-46cc-8f97-86976203e8b3.png)

**Comment by pfeerick** [comment]
i.e. if they are set:
![image](https://user-images.githubusercontent.com/5500713/132621439-7ade23f6-498a-4928-9ca4-26a89dcf5e1f.png)

**Comment by elecpower** [comment]
I'll fix it tonight
