### ISSUE TITLE
Reset ALL function missing

### ISSUE THREAD

**Issue by yds** [EdgeTX/edgetx#708]
![Reset](https://cdn.discordapp.com/attachments/839895574244229152/886226153520627782/unknown.png)

- [x] #756

- [ ] there's no option to select **All** as the target of the Reset -- very useful to be able to have a single SF to reset all Timers and Sensors which need to be zeroed before next flight.

**Comment by pfeerick** [comment]
Hm, this is a split issue... UI glitch on the NV14, and missing "All" reset option...

**Comment by pfeerick** [comment]
@yds I may have misunderstood this... is by "All", did you mean the "All" that is shown on the B&W radios - referred to as "Flight" on colour screen radios - or something different?

**Comment by yds** [comment]
@pfeerick I guess I meant "All" as in B&W radios.  is that now called "Flight" on color screen radios?

I was trying to recreate the model I had set up under FlySky-OpenTX where "All" was one of the options when selecting the Reset function -- see SF22 at the bottom of the screenshot:

![Reset All](https://i.imgur.com/6OKf565.png)

**Comment by raphaelcoeffic** [comment]
> @pfeerick I guess I meant "All" as in B&W radios. is that now called "Flight" on color screen radios?
> 
> I was trying to recreate the model I had set up under FlySky-OpenTX where "All" was one of the options when selecting the Reset function

yes, this is called “Flight” on color radios.
