### ISSUE TITLE
 Higher baud rates #640 with TBS-Crossfire issue

### ISSUE THREAD

**Issue by zyren** [EdgeTX/edgetx#711]
The latest submission Higher baud rates #640, I tested it on TX16S, except 115200 other baud rates can not use TBS Crossfire, and at 115200, crossfire configure can only get the first half of the menu, can not be displayed completely, use TBS Agent Lite this lua script can get a complete menu.
Crossfire firmware has been upgraded to V6.09
 
Images of max baud rate 115200 with Crossfire：
![cad6bc3dc70836e655b56f197a63911](https://user-images.githubusercontent.com/6081642/132972899-6c574aba-8636-45d6-a725-74f18316d000.jpg)
![c025e2f480bcf2263592fb8b5cb54aa](https://user-images.githubusercontent.com/6081642/132972903-3f789f2a-3d89-4d7d-b353-5cd92fb8d221.jpg)
![51077eff242d7a811b1f509197888c6](https://user-images.githubusercontent.com/6081642/132972907-28cbd5a4-53bf-4120-a44d-e231e762a157.jpg)

Images of max baud rate (400k, 921k, 187M, 375M) with Crossfire are not working：
![09113551c520abea80637ce3f0932b4](https://user-images.githubusercontent.com/6081642/132972989-c7cf108b-3db7-4a28-b096-841b059968ba.jpg)
![d60103e29697e8d5de09a05594ee561](https://user-images.githubusercontent.com/6081642/132972993-2ddac258-1414-46a9-a8fa-ddd7f6f57fb3.jpg)
![98e89238ebd2f926ee2ee0737390745](https://user-images.githubusercontent.com/6081642/132972996-a959187b-f2cc-490c-9ed9-94fb41a04aad.jpg)

**Comment by pfeerick** [comment]
What happens when you power cycle the radio after changing the baud rate? I just tried the latest nightly which has the PR included, and the ELRS lua also doesn't seems to respond after changing the baud rate, but if I restart the radio it seems to be fine.

**Comment by zyren** [comment]
> What happens when you power cycle the radio after changing the baud rate? I just tried the latest nightly which has the PR included, and the ELRS lua also doesn't seems to respond after changing the baud rate, but if I restart the radio it seems to be fine.

But Crossfire cannot be used no matter how it restarts.

**Comment by raphaelcoeffic** [comment]
@zyren is that only the script, or is there an issue as well with the module getting the stick values?

**Comment by zyren** [comment]
> @zyren is that only the script, or is there an issue as well with the module getting the stick values?

Only at 115200, it can be used barely. The receiver responds normally, but at 400k and other baud rates, it cannot be used normally. There is no Telemetry, and the receiver does not respond. I think it may be that the synchronization of CRSF 400k bps may have deviated. Using yesterday's firmware, you can get RC Input: CRSF Shot very well.

**Comment by raphaelcoeffic** [comment]
@pkendall64 did you notice anything? Seems to break TBS Crossfire.

**Comment by pkendall64** [comment]
With my TX16S I can use both ELRS LUA and Agent Lite with my ELRS module all the way from 115k to 3.75M with 921k not working.

**Comment by pkendall64** [comment]
@zyren Could you test this patched version with your crossfire unit. This version has a patch that only enabled 25Mhz GPIO and 8bit sampling on UART if over 400k baud is selected.
I do not think your crossfire will work with the higher baud rates, so only 115k and 400k should work.
 
[tx16s-5dd4a89eb.bin.zip](https://github.com/EdgeTX/edgetx/files/7151296/tx16s-5dd4a89eb.bin.zip)

**Comment by zyren** [comment]
> @zyren Could you test this patched version with your crossfire unit. This version has a patch that only enabled 25Mhz GPIO and 8bit sampling on UART if over 400k baud is selected.
> I do not think your crossfire will work with the higher baud rates, so only 115k and 400k should work. If this works for you, I will create a new PR with the changes.
> 
> [tx16s-5dd4a89eb.bin.zip](https://github.com/EdgeTX/edgetx/files/7151296/tx16s-5dd4a89eb.bin.zip)

Ok i test it now

**Comment by zyren** [comment]
Great, this firmware works perfectly at 400kBps and is CRSFshot.
Thank you very much!

![f263ea9a091b61e3b4230f19b1e18d8](https://user-images.githubusercontent.com/6081642/133024050-e48924de-2814-492f-af4a-3600c76988c5.jpg)
![bd99e18fba8ce871209c7fba4d04cff](https://user-images.githubusercontent.com/6081642/133024057-b8721b11-f1c1-4532-a4e6-66a581afce2a.jpg)
![9fd8a6deed6c9804ff1b085aa995bb5](https://user-images.githubusercontent.com/6081642/133024076-6d829209-1731-48c2-aa49-fac4a418caba.jpg)

**Comment by pkendall64** [comment]
Sweet, I'll make a new PR
