### ISSUE TITLE
Scale field in the Inputs tab

### ISSUE THREAD

**Issue by MrVinther** [EdgeTX/edgetx#718]
- EdgeTX 2.4.0 Flysky Hall gimbals
- Radiomaster TX16S

In the Inputs tab the field "Scale" will only go as high as 100.
Im trying to get it to read from the capacity telemetry RB1C as source with a scale up to 4500mah. This worked just fine in OTX as the first picture below. Second picture is EdgeTX which is stuck at 100.
Converted models from OTX works fine until I change the Scale value ever so slightly, jumps back to 100.

![IMG_20210830_154232](https://user-images.githubusercontent.com/42658337/133068469-bc56443d-4d44-4c4b-aa65-6c5333852b9c.jpg)
![IMG_20210912_162849_](https://user-images.githubusercontent.com/42658337/133068523-7985eca2-7ae6-41f6-884b-321dc77fb4a8.jpg)

**Comment by pfeerick** [comment]
That's OTX 2.4, isn't it? Looks like it may be a variable related error, since it jumps from 0 to 16383 then back to 100 😮 

@elecpower btw, whatever this "Scale" is, it's missing in Companion ;)

**Comment by eshifri** [comment]
https://github.com/EdgeTX/edgetx/blob/main/radio/src/gui/colorlcd/model_inputs.cpp#L245
     
/* TODO telemetry current value
      if (ed->srcRaw >= MIXSRC_FIRST_TELEM) {
        drawSensorCustomValue(EXPO_ONE_2ND_COLUMN+75, y, (ed->srcRaw - MIXSRC_FIRST_TELEM)/3, convertTelemValue(ed->srcRaw - MIXSRC_FIRST_TELEM + 1, ed->scale), LEFT|(menuHorizontalPosition==1?attr:0));
      } */
      grid.nextLine();

      // Scale
      // TODO only displayed when source is telemetry + unfinished
      new StaticText(window, grid.getLabelSlot(), STR_SCALE, 0, COLOR_THEME_PRIMARY1);
      new NumberEdit(window, grid.getFieldSlot(), -100, 100, GET_SET_DEFAULT(line->scale));
      grid.nextLine();

      // Weight
