### ISSUE TITLE
Output > 101.3% or < -101.3% switches to GV

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#722]
There are [two reports on Discord](https://discord.com/channels/839849772864503828/839895574244229152/887168111390896138) about this

> hmm, so on my TX16S on build 542213de, if an output is more than 101.3% or less than -101.3%, it turns into a GV instead of -101.3% or something

> same for me with extended limits on it puts them into the GV FW version 2.5.0 (f5c946a0)

@eshifri Any ideas, since it probably stems from #687 ?

**Comment by eshifri** [comment]
I'm sure it is related to #687: everything above 101.3% is treated as a GV. Or above 15X for extended limits.
Should we limit the MIN and MAX in numberEdit?

**Comment by pfeerick** [comment]
Hm, I think it's correctly limited already using GVarNumberEdit, and I can't actually reproduce this myself at the moment... output will only go to min -100, max +100 (-150,+150 for extended limits) and even with EL on outputs screen is still saying everything is fine... 542213d is yesterdays nightly and am running that and everything 'seems' fine? This is plain weird... need more info on how to reproduce this...

**Comment by rburrow87** [comment]
Posted this on Discord already but here's what I'm seeing:

Build 88b8ac86 where it's all good:
![tx16s-build-88b8ac86](https://user-images.githubusercontent.com/1323809/133202195-95557f8a-9672-4fc2-b8f7-c02fa53b3d6a.png)

Build 542213d where it goes wrong:
![tx16-build-542213de](https://user-images.githubusercontent.com/1323809/133202275-953e9912-9d38-4f7b-a360-fd04d0813dd9.png)

I see this happen on a freshly created model under 542213d too. 88b8ac86 was just the last nightly I had saved, not sure which nightly this appeared.

**Comment by eshifri** [comment]
This happens with EL and it is deeply rooted in the way GVs are distinguished from values.
The culprit is in the PREC1 attribute used for limits and offsets.

**Comment by jmxp69** [comment]
I can confirm same issue from my compiled version. Using extended limits and outputs > 100, when I leave the outputs page and go back, the output is changed to a gvar.

**Comment by pfeerick** [comment]
Thanks for the report. I finally realised the trick to reproducing was exiting the page, so have been able to test the fix being worked on. Preminimary rltesring shows its working, and just the cosmetics fixed now.

**Comment by pfeerick** [comment]
#726 fixes this for me, so please yell out if something still isn't right.
