### ISSUE TITLE
Battery Bar Indicator Shifted Left

### ISSUE THREAD

**Issue by jmxp69** [EdgeTX/edgetx#724]
On the top bar, the battery bar indicator does not ever show the final bar even with correct calibration. It looks like the vertical bar set is shifted one row to the left. Confirmed by multiple users on multiple versions. I'm using 2.5.0 (69efe13a) with flyskyhallsticks from Risto.

**Comment by rburrow87** [comment]
Picture for reference. This is with the normal nightly 6278335e but has been present for a while now. Not sure which one it started in.

![battery](https://user-images.githubusercontent.com/1323809/133313661-04225a6b-5c89-4c2a-ba11-f69cca48236a.png)

**Comment by rotorman** [comment]
Here on the picture 5 battery bars are shown, but drawn unfortunately a bit too much to the left.

**Comment by rotorman** [comment]
Fixed by 1eed24c
Old:
![old](https://user-images.githubusercontent.com/21011587/133320224-46314848-e33b-4e21-ad61-f378bb3f5844.png)
Fixed:
![fixed](https://user-images.githubusercontent.com/21011587/133320242-386eb613-ba7a-466a-969b-a9c7489a2889.png)

**Comment by pfeerick** [comment]
Lol... Oh my, that is one deceptive little bugger, looking like the battery symbol had positive on the left side! Nice one!
