### ISSUE TITLE
The problem of adjusting the OUTPUTS extend limit

### ISSUE THREAD

**Issue by zyren** [EdgeTX/edgetx#729]
Firmware version: newest nightly

The problem of adjusting the OUTPUTS extend limit, if the min or max adjustment exceeds -100 or +100, it will automatically become the wrong GV value and cause the channel to become unresponsive.

If GV value is used instead, for example, GV1=150, Min value=-GV1, Max value=GV1, the performance is very good and normal.
The problem now is that using the value directly will cause an error.

![image](https://user-images.githubusercontent.com/6081642/133360786-07c61c92-8f7e-47c1-81c1-2d5f4889f124.png)
![image](https://user-images.githubusercontent.com/6081642/133360818-379635bd-987b-412e-9c2c-06c6535f9f6e.png)

**Comment by rburrow87** [comment]
Which build are you on? This just got fixed today and is in the current nightly release.

**Comment by pfeerick** [comment]
Double check your version - if it doesn't say `0dac6037` as the commit after the version you're probably running yesterdays nightly still, and I can't reproduce this any more.

**Comment by zyren** [comment]
> Double check your version - if it doesn't say `0dac6037` as the commit after the version you're probably running yesterdays nightly still, and I can't reproduce this any more.

Great, I am using yesterday’s nightly version, I will update to today’s latest version, thank you very much!
