### ISSUE TITLE
Color element tweaks

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#730]
@JimB40 This one's for you... so you'd better have ideas on what needs fixing! 😝 

- [x] 1. Presumably change icon colours to white, rather than a theme colour? Otherwise, they could probably be made the same element colour used for the top bar?
![image](https://user-images.githubusercontent.com/5500713/133359563-b6c81907-74a7-4b03-9e10-a7f358933461.png)

- [x] 2. What else needs tweaking... screenshot with hilights/circles and preferably a hint as to what colour element it should be mapped to would be good ;)

**Comment by JimB40** [comment]
Doing review of other elements. Will post soon screenshots

**Comment by JimB40** [comment]
![screenshot_tx16s_21-09-16_13-58-31 copy](https://user-images.githubusercontent.com/46420768/133609468-042c998f-1f7b-430f-b783-0aa6fc076369.png)
Okay so first little changed Testing color scheme

**Comment by JimB40** [comment]
1. Wrong label text color. 
They Should be PRIMARY1 (P1) 
Two cases
a. like on **Main view 1** placed on background (field desctiption)
b. like on **LOGICAL SWITCHES** etc text label when LS is not set. We can see there is no value set so no need to dim label text 
Below places I've spotted to make this change 

![screenshot_tx16s_21-09-16_13-47-32](https://user-images.githubusercontent.com/46420768/133609661-5accf090-0ef4-4c64-b8eb-fe0f22d71bd5.png)
![screenshot_tx16s_21-09-16_13-53-25](https://user-images.githubusercontent.com/46420768/133609700-797532d7-6856-41b5-a76d-079c8a50c683.png)
![screenshot_tx16s_21-09-16_13-53-41](https://user-images.githubusercontent.com/46420768/133609721-9e0f8fdd-c4a7-4e12-ab83-27284a6589f4.png)
![screenshot_tx16s_21-09-16_13-53-58](https://user-images.githubusercontent.com/46420768/133609734-1b1fcd16-96c6-49a5-bf6e-73c9186de07b.png)
![screenshot_tx16s_21-09-16_13-54-44](https://user-images.githubusercontent.com/46420768/133609756-1bb2748e-d839-482b-a56d-70a846761d8c.png)
![screenshot_tx16s_21-09-16_13-54-51](https://user-images.githubusercontent.com/46420768/133609787-dc5c0e6f-7cc4-4873-b596-ae6c6c5cc1f4.png)
![screenshot_tx16s_21-09-16_13-57-34](https://user-images.githubusercontent.com/46420768/133609808-e1b39c17-d1c3-40f0-96bf-17c39af7a502.png)
![screenshot_tx16s_21-09-16_13-57-42](https://user-images.githubusercontent.com/46420768/133609822-6e419d1d-fc5c-4d16-8755-4d6411173bb4.png)

**Comment by JimB40** [comment]
FLIGHT MODES
Should be like other screens with ediatabe fields
Left labels - background S2, text P1
left labels focused - background FO, text P2

![FMD](https://user-images.githubusercontent.com/46420768/133612872-46795916-ff10-4fc5-b945-3dbcd7320e59.png)

**Comment by JimB40** [comment]
GLOBAL VARIABLES
Left labels - background S2, text P1
Values text color S2 (not S1)
plus all 9 FM varv should fit to one line that makes it more readable. (you can make labels column GV1, GV2 smaller)

![GV](https://user-images.githubusercontent.com/46420768/133615957-2f2f72b1-0626-4dd7-a8d1-b14abc862299.png)

**Comment by JimB40** [comment]
QUICK MENU
That's simple 
1. Make it Black & White :)
2. Set opacity of background to 70-80% so it's better readable in light enviroinment.

![screenshot_tx16s_21-09-16_13-55-36](https://user-images.githubusercontent.com/46420768/133617039-503855aa-b0f8-49e0-bc11-76ee0efee230.png)

**Comment by JimB40** [comment]
SD CARD
Ditch gray background

![screenshot_tx16s_21-09-16_13-46-55](https://user-images.githubusercontent.com/46420768/133617854-9a1a30e2-ec4d-4adb-98d7-19573ba5a744.png)

**Comment by JimB40** [comment]
POP-UP Mask 
It should be BLACK. Alternatively we can try S3 (main background color) but with light backround schemes it may not work

![screenshot_tx16s_21-09-16_15-09-52](https://user-images.githubusercontent.com/46420768/133618234-9ace6e7d-4174-4b5c-ad58-009b0b8ba1dd.png)
