### ISSUE TITLE
Telemetry/Input lists showing everything

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#731]
TX16S nightly 0dac6037 build

When going into a list of inputs and telemetry sensors and whatnot, everything possible is being listed instead of only what is set up.

For example, there are a bunch of blank telemetry sensors:

![screen-2021-09-14-195524](https://user-images.githubusercontent.com/1323809/133363311-f220818b-ad08-4637-84d8-58705517e841.png)

Also seeing L01-L64 despite only a couple being set up, inputs that are not set up, switches/sliders/knobs that don't exist, etc.

**Comment by pfeerick** [comment]
Yes, it does seem to ahve gone a bit crazy. Also a couple of `[--]` entires between 'GPS' and 'Flight'.

**Comment by wimalopaan** [comment]
This is the same for Mixer-scripts :-(

**Comment by jmxp69** [comment]
Same behavior here. Something to do with the GVAR Outputs bug just fixed?

**Comment by kevinkoenig** [comment]
Could this be related to the change made to reimplement sourcechoice recently
