### ISSUE TITLE
Companion Application Settings says OpenTX

### ISSUE THREAD

**Issue by timtuxworth** [EdgeTX/edgetx#734]
**Describe the bug**
Settings Application Settings says "Automatic check for OpenTX firmware updates" should probably say "EdgeTX"

**To Reproduce**
Start EdgeTX companion - click settings button or click Companion TX -> Preferences
Click Application Settings tab

**Expected behavior**
Prompt should read Automatic check for EdgeTX firmware updates"

**Screenshots**
![Screen Shot 2021-09-15 at 12 00 20 PM](https://user-images.githubusercontent.com/5266784/133493821-77d43048-7108-4553-8301-e7d78971de9e.png)

**General information**
 Companion 2.5 Sept 15 2021

**Comment by pfeerick** [comment]
:laughing: There are plenty of places that need the name changing still, including things like the simulator filenames, but thank you for catching this one!

**Comment by raphaelcoeffic** [comment]
> 😆 There are plenty of places that need the name changing still, including things like the simulator filenames, but thank you for catching this one!

I think we should disable anything related to firmware download for now, as it is not functional. (@elecpower do you think this can be done easily?)

**Comment by pfeerick** [comment]
If we were really lazy, it could even simply be a matter of hiding the controls from view... it might look a little "odd" but at least nothing would break and can be turned back on again easily.

**Comment by raphaelcoeffic** [comment]
> If we were really lazy, it could even simply be a matter of hiding the controls from view... it might look a little "odd" but at least nothing would break and can be turned back on again easily.

Fine for me, whatever works.

**Comment by pfeerick** [comment]
Is this enough? As I can push a PR for that now. Neil will need to do the last part if you want more, as it looks like hiding may not be as straightforward as I thought since a quick search for that goes straight to stackoverflow rather than a nice QT documentation page. 😁 

![image](https://user-images.githubusercontent.com/5500713/133564357-755129b3-5350-4c0c-b396-92df35a69030.png)

**Comment by timtuxworth** [comment]
This looks good to me. I'd say disable rather than hide is better if its intended to be functional eventually. Thanks for your efforts guys!

**Comment by elecpower** [comment]
How to hide noted on PR
