### ISSUE TITLE
Spectrum analyser freezes if MPM off on radio power up

### ISSUE THREAD

**Issue by NemesisXB** [EdgeTX/edgetx#748]
**Describe the bug**
If the MPM is on at startup the Spectrum analyser works fine. If the MPM is off on startup, the first time you launch the Spectrum analyser, it is just frozen. If you then exit and launch the spectrum analyser again it works fine.

**To Reproduce**
Turn off the MPM.
Turn off the radio.
Turn on the radio.
Go to SYS > Spectrum (INT).
Spectrum analyser should be frozen

**Expected behavior**
Expected behaviour is for the spectrum analyser to work every time you launch it.

**General information**
 - EdgeTX nightly (2021-09-16)
 - RM TX16s

**Comment by pfeerick** [comment]
Raphael has figured the protocol scanner code is the problem, and is going to fix it as part of PR#740 also. Nice catch! :)
