### ISSUE TITLE
Make channels available as source in Diff, Weight, Offset

### ISSUE THREAD

**Issue by strgaltdel** [EdgeTX/edgetx#749]
As written above, making channel values available where GV's are used would be (imho) a great step forward in model configurations.

![chDiff](https://user-images.githubusercontent.com/20392683/133749995-9306e124-2b41-4f79-bf0c-93e9f941f693.png)

This would enable edge to built a more variable configuration, dependent on the situational demand.

example for  gliders:
classic configuration is to define a fix value (GV) for differentiation which works fine in case camber is on neutral.
in case you fly in thermal condition (flaps down) or speed (flaps up), differentation should be adopted to the "new" flight condition in order to reach optimal flight behaviour.
Similar use cases could be: 
snapflap deflection dependent on camber position to prevent unnecessary drag
differentation in case of butterfly deflection
....

The actual edge design allows to use GV's and change them by SF's
You will have to "design" a channel with the "controlling" Input including an "overlay" by a curve which sets the GV dependent of the "input value"
But, at the end of the day, you need a lot of precious GV's and blow up your SF-configs

In case one would be able to "route" a channel value directly to the corrresponding objects (Dif, weight etc..) instead of using GV's the whole construct would mean a more directly and simplier approach

regards
Udo

example how it works by now:
Diff depending on camber position

CH8 = right Aileron
Ch10 = Camber 
Ch12 = controls GV1
GV1 used for Diff, SF1 sets GV1/Diff with Ch12 as Input, CV1 is "overlay"

![edgemix](https://user-images.githubusercontent.com/20392683/133751228-e1c33d80-e866-44cc-82f9-7e5cdeaffae4.png)

**Comment by philmoz** [comment]
Added in 2.11 - PR #5220
