### ISSUE TITLE
Replacement icon masks

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#752]
Replacement icons are needed for three icons used on the fullscreen dialogs, and are located in `/radio/src/bitmaps/480x272/default_theme`  (https://github.com/EdgeTX/edgetx/tree/main/radio/src/bitmaps/480x272/default_theme)

Specifically, 
- [ ] mask_asterisk.png
- [ ] mask_busy.png
- [ ] mask_question.png

But also feel free to update the following two if so desired. 
- mask_error.png
- mask_shutdown.png

Only requirement is that they must be black and white (which black being what will be drawn to screen) since they are masks. All but the last image are 105x105, with that latter image being 96x96. 

This is what we currently have (perhaps you can see the problem?) 😆 

![image](https://user-images.githubusercontent.com/5500713/133872552-7337df0f-8578-44be-b649-73d02af389e1.png)

**Comment by JimB40** [comment]
@pfeerick I’ll do it in exchange for #638 ;)

**Comment by pfeerick** [comment]
Either 105x105 for first four, and 96x96 for last, meaning they are a drop in replacement that can go in any time, or we lay this over for 2.6 and look into tidying up those dialog screens, and probably make them all 96x96 or smaller if we can get away with it for consistency... will just have to keep in mind smaller also equals harder to see at a glance when out at the field in the sun...

**Comment by JimB40** [comment]
Do we go 96x96px for all of them then. I can enlarge icon to fill 96px canvas entirely

**Comment by pfeerick** [comment]
Nothing is jumping out at me saying they need to be a specific size as it looks only the top left corner is specified, no width or height... so lets go for 96x96px for consistency and the few extra bytes of space saved ;)

**Comment by JimB40** [comment]
You're welcome

![mask_busy](https://user-images.githubusercontent.com/46420768/133962879-88440b20-f620-4e7c-9574-3abe6061e204.png)
![mask_error](https://user-images.githubusercontent.com/46420768/133962880-bff447d5-44b7-42b5-9291-b35b07e1f11e.png)
![mask_asterisk](https://user-images.githubusercontent.com/46420768/133962882-009e0bea-8891-4265-a2bf-063a914c9535.png)
![mask_question](https://user-images.githubusercontent.com/46420768/133962884-f8ba1c91-78c8-40cf-883d-f18161ef0b08.png)
![mask_shutdown](https://user-images.githubusercontent.com/46420768/133962885-fbeb9ddd-f9f3-46a9-8578-677dca096ada.png)

**Comment by JimB40** [comment]
Here is ZIP as GH changes names :)
[ETX_SYS_icons.zip](https://github.com/EdgeTX/edgetx/files/7193876/ETX_SYS_icons.zip)
