### ISSUE TITLE
EM related to Model => Inputs => Source autosense

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#759]
Found this one out at the field when trying to reconfigure a model... fun times! 🤪 

Go into model settings (new model or existing model), input, and then set your source via autodetect (i.e move a switch)... it will jump to the correct switch, and everything will seem fine, until you press ENT, touch away from it, or sometimes it will immediately EM... will segfault on `simu`, and EM on TX16S with yesterdays and todays nightly. It also seems on a three position switch, that first click is fine,and second click may cause complete radio freeze - apparently also if you flick one switch, and then another. Selecting the source *directly* from the list seems to work fine though. Only appears to effect inputs page, not mixes.

**Comment by rburrow87** [comment]
You beat me, was just about to post this one!

**Comment by pfeerick** [comment]
This also has some relationship with https://github.com/EdgeTX/edgetx/issues/758 ... looks like we all basically found aspects of this bug at the same time! :)

**Comment by raphaelcoeffic** [comment]
@rburrow87 @pfeerick I believe the same issue exists with anything using a SourceChoice / SwitchChoice, which is basically on all Input/Mixer source / switch drop-downs.

**Comment by pfeerick** [comment]
I did try input switch and mixer source and it didn't seem to misbehave. Either way, PR#760 fixes it for me. I know John will test this ASAP ;) so it'll should be in the next nightly...
