### ISSUE TITLE
TX16S FLYSKY_HALL_STICKS conflicts with Trainer in Slave mode

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#766]
If the current main branch firmware is built for TX16S with FLYSKY_HALL_STICKS option, and the trainer is set to slave mode - this disables the FlySky digital sticks due to the usage of the same DMA1 Stream2.

https://github.com/EdgeTX/edgetx/blob/66b523cf88743c1bb55017f4cdff80275229cfdf/radio/src/targets/horus/hal.h#L793-L812

https://github.com/EdgeTX/edgetx/blob/66b523cf88743c1bb55017f4cdff80275229cfdf/radio/src/targets/horus/hal.h#L952-L955

I created a page in dev. Wiki that lists the DMA mapping on TX16S, where the conflict becomes easily visible:
https://github.com/EdgeTX/edgetx/wiki/DMA-mapping-of-TX16S

~The solution could be to re-write the FlySky reception routine to use purely IRQ (the std. data telegram from FlySky digital hall gimbals is 14-bytes long).~

**Comment by raphaelcoeffic** [comment]
Other solution, IMHO more preferable: re-write Trainer slave output to use only IRQ. As the signal is really slow, it should be more suitable.

**Comment by richardclli** [comment]
> 
> 
> Other solution, IMHO more preferable: re-write Trainer slave output to use only IRQ. As the signal is really slow, it should be more suitable.

Yes, agreed, always leave DMA to faster I/O
