### ISSUE TITLE
Color UI is left in an incorrect state when entering USB mass-storage

### ISSUE THREAD

**Issue by raphaelcoeffic** [EdgeTX/edgetx#79]
And not properly reloaded after USB mass storage mode is left.

Original description from @pfeerick:
"I can finally report one seemingly new mostly cosmetic bug on current bef88d2 ... go into any menu... radio setup, model setup, etc. plug in the USB, enable storage mode, unplug the USB, and admire... looks like it needs a full screen refresh, and something about navigation is lost/broken - only way to go back seems to via the touch screen, rather than RTN button."

In fact, we're quite lucky the whole thing does not crash (pure luck).

**Comment by pfeerick** [comment]
Ouch... So don't walk under any ladders or cross paths with black cats before this is resolved? :laughing:

**Comment by raphaelcoeffic** [comment]
> Ouch... So don't walk under any ladders or cross paths with black cats before this is resolved? 😆

In fact it is resolved ;-) See 945fc95.
