### ISSUE TITLE
QX7, X9D+2019, T-Lite - reset/bootloop

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#794]
For some yet unknown reason, both my X9D+2019 and also @JyeSmith QX7 (as well as another QX7 owner) have suffered reset or bootloops which seem to require a reflash (or perhaps just EEPROM erase/re-write?) to recover from. Have also seen a report about T-Lite. I first had it a couple of weeks ago, but I have no idea what the trigger is yet. My current plan of attack is to restore an EEPROM backup via the bootloader the next time it happens to pin it down to that (will save it first if it's not when out at the field). 

https://streamable.com/6s6mw0

Report: https://discord.com/channels/839849772864503828/839849772864503832/890142933993529364

Applicable to both 2.4 nighties and 2.5-RC1.

**Comment by 0crap** [comment]
Subscribed.

**Comment by pfeerick** [comment]
@trnnwnnhe Your "Infinite boot after removing battery" issue is most likely related to this... ;) And FYI, PR is for code contribution, not questions/reporting problems ;)

**Comment by raphaelcoeffic** [comment]
Is that actually still applicable? I haven't heard any reports of something similar in a great while.

**Comment by JyeSmith** [comment]
I actually flashed a recent nightly and it came back to life!  I'll flash the RC tonight and confirm, then this issue could be closed.

**Comment by pfeerick** [comment]
Haven't heard/or experienced this in a while either (although admittedly haven't used those transmitters anywhere near as much of my others since around 2.6 onwards). So hopefully it is gone now - not that people stopped ETX with those transmitters 😮

**Comment by JyeSmith** [comment]
Tried the Flasher again and could not get the x7 to boot with 2.7 and 2.6.  Then flashed 2.7 with buddy and it worked.  Flashing nightly 0c4f0083 from the SD card also works.

Might be a Flasher issue 😐

**Comment by pfeerick** [comment]
With Flasher, are you doing DFU or SD -> bootloader flashing? As I would _hope_ Flasher behaves itself for DFU flashing 😮.

**Comment by JyeSmith** [comment]
Always dfu.

**Comment by pfeerick** [comment]
Only other thing I can think of off-hand is there was an issue with x7 and x7-ACCESS firmware selection... but IIRC that was a bug in Flasher fixed probably this time last year, so it's well and truly in the bad books if it's scrambling stuff with DFU updates... 😭

**Comment by JyeSmith** [comment]
I'll download the Flasher again for another try.  Cant remember the last time I updated it.

**Comment by JyeSmith** [comment]
Downloading a recent Flasher fixed it 👍

**Comment by pfeerick** [comment]
Thank goodness... and thank you **_very_** much for testing! :) That is one nice thing with ELRS Configurator... it told you there was a newer version and now offers to download and auto-update...
