### ISSUE TITLE
Re-arange models

### ISSUE THREAD

**Issue by Mantamatt1** [EdgeTX/edgetx#798]
Tx16s
Etx 2.6 nightly 
Now we have categories can we have an option to re-arange models to our liking with in the categories?

**Comment by pfeerick** [comment]
Nope :-P You can do that in Companion right now if you want to be able to (right click cut, right click insert).

This will most likely be implemented as part of changing from Categories to Labels ;)

**Comment by Mantamatt1** [comment]
Right 'o 👍
