### ISSUE TITLE
Potential issue with using module bay for updating receiver and module firmware

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#801]
**Describe the bug**
There have been a couple of reports now for 2.4.0 and 2.5.0-RC1, and I believe I have experienced this myself in testing a update related PR, that updating receivers (and in my case a XJT module) is currently not working. I have also not been able to update a ELRS module via the module bay. One user was able to update the receiver on the X7, but not the TX16S or X12s. 

In the case of the XJT module, I can successfully flash the same firmware file to the same module,  using the same TX16S and SD card on OpenTX, so it is definitely firmware related.

Receivers:
- Radiomaster R168 RX 
- R-XSR

TX Module:
- Frsky XJT
- Happymodel ES24
- R9M and R9 - mentions thinks it was working with 2.4 main at end of August - https://www.rcgroups.com/forums/showpost.php?p=47874391&postcount=736

Transmitters:
- RM TX16S
- X12s 

Other mentions:
- https://discord.com/channels/839849772864503828/839849772864503832/890022344196767745
- https://discord.com/channels/839849772864503828/839849772864503832/890675015534665740

**To Reproduce**
Try to apply a firmware update via the module bay. Will most likely beep and 
```
Firmware update error 
Device not responding
```

**Expected behavior**
For the firmware update to complete!

**Comment by wimalopaan** [comment]
The error on tx16s with latest main:
![Uploading WhatsApp Image 2021-09-24 at 10.18.10.jpeg…]()

**Comment by rotorman** [comment]
@wimalopaan can you please try to reload the image - the link in your post does not seem to work.

**Comment by wimalopaan** [comment]
> @wimalopaan can you please try to reload the image - the link in your post does not seem to work.

Done

**Comment by raphaelcoeffic** [comment]
> > @wimalopaan can you please try to reload the image - the link in your post does not seem to work.
> 
> Done

And also edit your post to specify which kind of firmware you were trying to upload, to which port, etc.

**Comment by pfeerick** [comment]
XJT+TX16S => attempted update with Saleae monitoring SPORT => "Device not responding"
[XJT+TX16S-EdgeTX.zip](https://github.com/EdgeTX/edgetx/files/7231058/XJT%2BTX16S-EdgeTX.zip)

**Comment by rotorman** [comment]
In both cases in Saleae Logic, the analyzer is thus 57600 baud inverted for Channel 0:
![grafik](https://user-images.githubusercontent.com/21011587/134805239-daca7224-d4ac-427d-9ab7-5d108d5573e4.png)
@pfeerick What does Channel 1 in the second trace show?

**Comment by pfeerick** [comment]
PPM
