### ISSUE TITLE
Missing ACCESS Protocol Menus

### ISSUE THREAD

**Issue by rburrow87** [EdgeTX/edgetx#804]
This was brought up in Discord but I figured it'd be good to submit it here with screenshots.

There are a few things missing/buggy when trying to use ACCESS protocol. This is with an X10S Express, it's all good on my X9D+ SE 2019. I took some screenshots in OpenTX to show what should be there.

First step for binding an RX with ACCESS is to register it to the transmitter:

![1 - register](https://user-images.githubusercontent.com/1323809/134716789-2e3abed1-2d04-49d8-ac2b-6733c030f123.png)

This is the pop up you get, which is similar to how it looks in EdgeTX currently. However the "Rx Name" field comes up blank by default in EdgeTX which does not happen in OpenTX. It usually fills with the RX model by default.

Also, on this screen in EdgeTX, you can press Page Up/Down while the pop up is open and it'll switch tabs, which I'm guessing shouldn't be possible.

![2 - registration screen](https://user-images.githubusercontent.com/1323809/134716831-5826c59f-9011-4bc7-aa27-6cea99bccbe6.png)

Once registered, you bind it in one of the 3 receiver slots:

![3 - binding to rx1](https://user-images.githubusercontent.com/1323809/134718431-e3de4514-8243-460a-ab25-22d070621d42.png)

This pop up should show the registered receiver with the Rx Name from when it was registered. I thought it worked at one point in EdgeTX but it just opens and closes and doesn't actually bind the receiver anymore for me.

![4 - selecting rx1](https://user-images.githubusercontent.com/1323809/134718466-1f7e6144-0cca-4664-bf84-eee7966c72c1.png)

Once bound, the Rx Name should show in the receiver slot it was bound to:

![5 - rx1 selected](https://user-images.githubusercontent.com/1323809/134718645-9f054df2-bd86-427e-b8a5-2e1916e9f733.png)

You should be able to select that receiver and click on it and get a menu similar to this:

![6 - rx1 menu](https://user-images.githubusercontent.com/1323809/134718698-1a3251e1-3f55-4c09-b478-99d2c3279c7b.png)

And options should give you some settings for the RX. This is how you change between S.Port/F.Port/F.Port2 with ACCESS receivers.

![7 - rx1 settings page](https://user-images.githubusercontent.com/1323809/134718868-c349a469-a5fe-4f8a-82ba-ce2138b21ed3.png)

**Comment by MRC3742** [comment]
Missing Access Protocol Menus are the same problem preventing use of the External Access Mod in EdgeTX
Problems all seem related in Issues #260, #384, #670 and this one 804.
