### ISSUE TITLE
FrSky X10 Express fw package missing

### ISSUE THREAD

**Issue by nostromo123** [EdgeTX/edgetx#809]
EdgeTX v2.4.0 lists one x10 fw package, v2.5.0-rc1 and nightly list two fw x10 packages (one with add. 'access'.)

Trying to install one of those on my X10S Express with bl 2.5 or 2.6 here both fw packages (with or without 'access') report  'Wrong PCB detected'.

Would be nice to have a working  x10-express.bin in the fw package.

br KH

**Comment by raphaelcoeffic** [comment]
@nostromo123 please use the latest builds from `2.5` and `main` branch, that has been reported to work properly.

**Comment by nostromo123** [comment]
I know. I build the fw according to the Ubuntu 20.04 building manual from edgeTX main. This works.

But it should be mentioned, that there is no ready package available for those, who don't want to build ....

br KH

**Comment by raphaelcoeffic** [comment]
Will be fixed in RC3 then.

**Comment by pfeerick** [comment]
It will be included in RC2, since the fix is already in place in the nighties, so you should actually be able to grab it from the nightly build. But thank you for the report! :)

**Comment by nostromo123** [comment]
Thank you. That is, what I wanted to bring forward here.

On that page here https://github.com/EdgeTX/edgetx/releases/tag/v2.4.0

there is this statement

![Bildschirmfoto_2021-09-26_11-24-47](https://user-images.githubusercontent.com/17964433/134801841-d7d56b9c-fbbc-4d8a-8532-02354ff2a35a.png)

No problem for the experts here, but a 'normal' user will download the fw.zip attached and be a bit disappointed.

Watched quite some YT videos and the bottom line just is, 'It is so easy to try edgeTX'.

br KH
