### ISSUE TITLE
Plane and Glider wizard throw error when executing

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx#810]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**
When executing either the plane or glider LUA, an error will be thrown. See below:
 The mulitrotor wizard works.   Plane wizard uses "DEFAULT_COLOR" while multirotor wizard uses "TEXT_COLOR". A quck test of replaceing DEFALT with TEXT and recompiling seems to make the LUA work.  Additional find when testing this, even though the LUA goes through the wizard, no actual model is created (for any type,  plane, mulitrotor or glider.)

**To Reproduce**
Run either the Plane or Glider Lua script

**Expected behavior**
It should open the wizard

**Screenshots**
![image](https://user-images.githubusercontent.com/84094746/134801324-3e4c80b8-f69e-4810-85ef-b502955743e2.png)

**General information**
 - EdgeTX version 2.5 RC1 (current Sd release from repo"
 - Hardware : RM TX12S

**Comment by pfeerick** [comment]
Updated zip files are here => https://github.com/EdgeTX/edgetx-sdcard/releases
