### ISSUE TITLE
Logical switches are messed when copying model between NV14 and companion

### ISSUE THREAD

**Issue by eshifri** [EdgeTX/edgetx#814]
**Describe the bug**
I'm using not the latest build of companion, so maybe it was fixed...
I created a new model in companion for NV14.
Setup LSs and SFs.
Copied the model to the radio.
It is difficult describe what exactly happens, but lots of LS were remapped to higher (no-defined) LS. E.g. LS04 became LS16.)

I fixed everything and copied the model from the radio back to companion - everything was wrong again: some LSs (with higher numbers) were re-mapped to inputs.

**To Reproduce**
see above.
**Expected behavior**
Exact copy of the model setup. :-)

**General information**
 - EdgeTX version current code for TX and companion 2.5
 - Hardware NV14 and Windows 10

**Comment by elecpower** [comment]
It is highly likely it is not just LS that are 'messed' up and be evident across switches and sources.

**Comment by elecpower** [comment]
I've got it
