### ISSUE TITLE
Add possibility to set logical switch via LUA-script

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#817]
Sometime it would be really handy to have a logical switch (LS) that could be set / reset via a lua-function.

The logical switch should get a "function" of kind: LUA.

Only for these logical switches a lua.setLS(id) or lua.resetLS(id) should have an effect.

**Comment by JimB40** [comment]
Can you give example of this sometime?

**Comment by wimalopaan** [comment]
The most obvious example would be to have the possibility to defined UI-buttons and UI-switches in LUA-widgets, which act the same way as other switches.
Actually I am doing something similar in my own widgets. but this would make it more usable.

**Comment by jfrickmann** [comment]
You can set a Global Variable from Lua and use that in  Logical Switch. Or you can user a Custom/Mixer Script and set a logical switch based on the output value from that.

**Comment by wimalopaan** [comment]
Thank you.
That is actually the way I do that. But both ways look weird to me. 

If we propose the GV -> LS way, then we should increase the number of GVs, say to 64, at least for the colorLCDs (may the memory of the monoLCDs is too small).

I was a bit unclear in saying LUA-script. But I really meant mostly LUA-widgets. So the mixerscript -> LS way is not possible for widgets.

Actually I increase the number of GVs in my own compilations, but that unfortunately makes the storage format incompatible.

**Comment by jfrickmann** [comment]
How about a Lua function that can set a sticky LS?
`setStickySwitch(idx, value)`, 
where `value` is boolean, and if the switch selected by `idx` is not sticky, then nothing happens.

**Comment by jfrickmann** [comment]
@wimalopaan, please check PR #1019!

**Comment by wimalopaan** [comment]
Thanks!
Looks good to me.
But I would like to change it also for non-colorlcd radios. I don't think that the 16 int's hurt so much for the smaller radios.

**Comment by wimalopaan** [comment]
Thanks!,

Looks good to me!

BTW: actually I'm using a workaround by modifying a LS from

{"a>x", MAX, 0} --> true

to

{"a=x", MAX, 0} --> false

**Comment by jfrickmann** [comment]
@wimalopaan - please check #1056!

**Comment by wimalopaan** [comment]
Thanks!
Will do.
