### ISSUE TITLE
Binding beeping don't stop after binding

### ISSUE THREAD

**Issue by CorpseGuard** [EdgeTX/edgetx#819]
After binding was complete the beep sound still beeps and doesn't stop. I have to restart the TX. 

Accst 2.0.1 with D16 
Test with radio xlite and Horus X12s

**Comment by raphaelcoeffic** [comment]
I believe #820 fixes the issue with the xlite. For the X12, I need to re-check.

**Comment by raphaelcoeffic** [comment]
@CorpseGuard regarding the Horus X12s, I seems to work properly without #820, and thus should behaves properly with 2.5.0-RC2. Could you please re-test? Regarding the Xlite, you should re-test with the binaries from #820.
