### ISSUE TITLE
bluetooth support tx16s

### ISSUE THREAD

**Issue by sgsracer256** [EdgeTX/edgetx#830]
hi, i added a bluetooth module, can it be activated in the firmware ?

**Comment by pfeerick** [comment]
You need to build a custom firmware and add the 'BLUETOOTH=Y' option.

**Comment by IdefixRC** [comment]
> hi, i added a bluetooth module, can it be activated in the firmware ?

I compiled it for my own use. Might be helpful for you as well.
(options used: -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DGVARS=YES -DPPM_UNIT=US -DHELI=YES -DLUA=YES -DBLUETOOTH=YES -DCMAKE_BUILD_TYPE=Release)
NOTE: Fresh from the compiler. Have yet to test it on my TX16

https://drive.google.com/file/d/1cYBqwtYQhXBDUsYgOQqagFYhhTAKVMUA/view?usp=sharing

**Comment by Luznatural** [comment]
Does anybody have a compilation for TX16S with bluetooth on Edgetx 2.7.1?

**Comment by pfeerick** [comment]
There's several builds for TX16S with bluetooth enabled in the by request for #1951
