### ISSUE TITLE
Simulator shows UTC time instead of local time

### ISSUE THREAD

**Issue by rotorman** [EdgeTX/edgetx#834]
Simulator does not show local time (tested here under Windows 10, in the example below simu displays 17:42 vs real local time 19:42):
![grafik](https://user-images.githubusercontent.com/21011587/135321066-ad3876c2-b5db-48cd-93ac-0e542a50e5cc.png)

![grafik](https://user-images.githubusercontent.com/21011587/135321214-d0dfbc33-9e70-4da1-af15-00915cc7007f.png)

@elecpower would you have an idea how to fix this? Thx!

**Comment by raphaelcoeffic** [comment]
Currently the code uses „localtime()“, but it would probably better work to use the window API:
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlocaltime

**Comment by pfeerick** [comment]
Simulator on Ubuntu is UTC for me also. I'm not sure this is actually using `localtime` as that should be returning a correct local time, as opposted to `gmtime()` ... are we talking about `RTC_GetTime()`  in `simpgmspace.cpp`, as it doesn't even appear to be being used.

**Comment by raphaelcoeffic** [comment]
> Simulator/simu on Ubuntu is UTC for me also. I'm not sure this is actually using `localtime` as that should be returning a correct local time, as opposted to `gmtime()` ... are we talking about `RTC_GetTime()` in `simpgmspace.cpp`, as it doesn't even appear to be being used?

Oh! I blindly assumed this is what is being used! Where is the time coming from then?

**Comment by pfeerick** [comment]
Not a clue... I set a static time, no effect, and even shoved a `exit(0)` to make it simply halt, and it just carried in...  (`simu`, in this case...
)

**Comment by elecpower** [comment]
When I get back to my computer I'll point you to the code.

**Comment by raphaelcoeffic** [comment]
> When I get back to my computer I'll point you to the code.

I think this is what is used:
https://github.com/EdgeTX/edgetx/blob/36ec9356f3f9d8a03ab51a45fed01579b0f40ea4/radio/src/targets/simu/simpgmspace.cpp#L214

**Comment by raphaelcoeffic** [comment]
@pfeerick sorry, I went for the simpler solution, especially to be able to use the existing RTC functions in `rtc.c` (see #838).

**Comment by pfeerick** [comment]
> @pfeerick sorry, I went for the simpler solution, especially to be able to use the existing RTC functions in `rtc.c` (see #838).

Why sorry, did you not read this above? 😆 

> Now you just need to improve it :-P

Anyway, it looks like `gmktime` was the magic sauce here... I was originally using the same code as you ended up with, but mktime, and it was returning UTC time, so ended up with the functions I found on stackexchange.
