### ISSUE TITLE
NV14 Internal Module protocol

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#836]
@elecpower Just noticed that for the NV14 it's showing AFHDS3 for the internal module protocol instead of AFHDS2A

Also, whilst I beleive the RF output power can be changed, that isn't exposed in the settings atm, but I don't know which side is right as far as the bin file settings (i.e. simply missing from interface, or Companion shouldn't be showing it). 

![image](https://user-images.githubusercontent.com/5500713/135440689-07dc3647-b36e-4ba3-a15a-2b4f1f1354ee.png)

**Comment by elecpower** [comment]
I haven't tackled the supported modules and protocols yet as until the NV14 sim started working with touch I had no interface to see the radio gui. I haven't checked the code recently but I have a feeling the internal protocol isn't even known to Companion so will need the whole shebang.
Anyway I'll start on a PR.
Keep checking as I'm sure there are other settings that will need adding/tweaking.

**Comment by pfeerick** [comment]
It "seems" to enable and disable it ok as it is ... I haven't tried changing the options yet, so we'll see what happens. I just suspected it was going to be more than changing the text in the dropdown, so better to let the expert look at it! 😆
