### ISSUE TITLE
enter in statistics wont reset statistics

### ISSUE THREAD

**Issue by ishay320** [EdgeTX/edgetx#841]
**Describe the bug**
in the statistics menu the "[enter] to reset" is not working, not when pressed on the screen and not when press on the enter button

**To Reproduce**
navigate to statistics(main screen press enter and choose statistics)
press enter and it wont reset

**Expected behavior**
when press enter it should reset the statistics

**Screenshots**
![WhatsApp Image 2021-10-01 at 09 39 19](https://user-images.githubusercontent.com/65709059/135576717-d6fcd7a6-90b4-47e1-af26-c963b90cbcb4.jpeg)

**General information**
 - EdgeTX version "Dauntless" 2.5.0-RC2
 - Hardware tx16s

**Comment by pfeerick** [comment]
Partly needs a wording change "Press to reset", but yes, generally still a bug 😁

**Comment by ishay320** [comment]
I'm trying to learn how to help, so have I found the line which the button setup is?
https://github.com/EdgeTX/edgetx/blob/0cbb14bc11aeae89bd11a6740d79fda73a6acea4/radio/src/gui/colorlcd/view_statistics.cpp#L138-L144

**Comment by pfeerick** [comment]
Two changes are needed IMO... the translation string for STR_MENUTORESET need changing (after verifying that it's not used somehwere else where it would be the wrong text to show) and also a handler added so the long ENT also works there - as on non-touch colour lcd there is no way to get to that button AFAICT from a check on the radio itself.

**Comment by ishay320** [comment]
I have checked and the translation show in all radio but with the same syntax
https://github.com/EdgeTX/edgetx/blob/0cbb14bc11aeae89bd11a6740d79fda73a6acea4/radio/src/translations/en.h.txt#L613
I change some stuff, now I want to compile, what's the command for tx16s?

**Comment by raphaelcoeffic** [comment]
Guys, did you verify the button is on focus?

**Comment by pfeerick** [comment]
That would be the rather unhelpful `NO_FOCUS` that can be removed if you'd like to do the honours @ishay320 ;)

https://github.com/EdgeTX/edgetx/blob/0cbb14bc11aeae89bd11a6740d79fda73a6acea4/radio/src/gui/colorlcd/view_statistics.cpp#L144

https://github.com/EdgeTX/edgetx/blob/0cbb14bc11aeae89bd11a6740d79fda73a6acea4/radio/src/gui/colorlcd/view_statistics.cpp#L238

**Comment by ishay320** [comment]
The throttle value , throttle %  and curve is not resetting, 
I have fixed it, tell me if the function in class ThrottleCurveWindow  -  resetCurve is on par (line 49).

`

`
