### ISSUE TITLE
Companion not showing all images available for use as model image

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#843]
@elecpower I have a doozy for you... and this is either a user error, or this bug is also present in OTX as well... 

In a nutshell, I was just creating a new model (new OTX file, TX16S profile), and have the SD card folder selected in Companion settings, and instead of letting me see all 12 `.png` images, it only lets me see three of them. 😮 Gimme my other 9! 😆 

![image](https://user-images.githubusercontent.com/5500713/135623994-6774625a-ed08-4da2-82cd-a72cfa766f71.png)

This happened with the same dataset on both OTX and ETX companion, and with the ETX companion on windows and linux via the test appimage build. 

Attached is the contents of my images folder at the time of the screenshot (just in case it is related to the files/and better mimic). I noticed that if I added a bunch of `*.jpg` files - probably stock ones from OTX, more files were listed, but even then, it wasn't a complete list. 
[IMAGES.zip](https://github.com/EdgeTX/edgetx/files/7267376/IMAGES.zip)

Just a further note to that - I tried opening an old OTX file on OTX companion, and whilst I can't swear it to be the case, I don't think it was showing configured model images for some models. 

Possibly related (or if not, was the reason I encountered this) is this case where the filename was corrupted, and this users file list was also suitably bare... ([discord comment](https://discord.com/channels/839849772864503828/839849772864503832/893466610898202624))

![image](https://user-images.githubusercontent.com/5500713/135624091-79ad75ff-6b25-42cf-a155-fe607754474d.png)

![image](https://user-images.githubusercontent.com/5500713/135624230-0f6342ee-896e-427b-ac3c-adcc755c30fd.png)

**Comment by elecpower** [comment]
Found it and why not resolved in OTX but need to check why the current logic as there could be a hidden gotcha.

**Comment by MervDale** [comment]
Sorry to upset the apple cart but I am not having any issues with Companion at all in this regard. 
![companion](https://user-images.githubusercontent.com/30642754/135696443-6d3078f8-3ca7-4dcb-af13-151e6995f69c.jpg)

**Comment by pfeerick** [comment]
You'll only notice it (in my experience of this so far) with small data sets, or if you actually tally up the list of all the images in a directory with those shown.

The fact Neil didn't immediately say "you're dreamin', mate" suggests there really is a bug, but thanks for the feedback
