### ISSUE TITLE
Concrete these undesirable artefact with gauge widget.

### ISSUE THREAD

**Issue by stronnag** [EdgeTX/edgetx#860]
New theme (concrete) shows an undesirable artefact with gauge widget.
The text is somewhat unreadable using the Concrete theme. It is with OK the other new themes. See image (default v. Concrete).
![theme-gauge](https://user-images.githubusercontent.com/158229/135868972-41cc7ab1-368c-41ed-9754-650d7b2e387a.png)

**Comment by JimB40** [comment]
Widgets are still to be adjusted to use properly etx color contants

**Comment by philmoz** [comment]
The gauge uses a function to invert the part of the bar corresponding to the input position.

The problem is that the invert function assumes that the background color for the bar (COLOR_THEME_PRIMARY2) is white.
If the theme changes this color then the invert function misbehaves.
