### ISSUE TITLE
NV14 is not booting when flashed with last nightly #155d55d

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#863]
Used this build
https://github.com/EdgeTX/edgetx/actions/runs/1306099483

**Comment by pfeerick** [comment]
This is probably my fault... I didn't test #852 on the NV14 before merge, and the firmware for that PR does look like it bricks on the NV14!!! Sorry boss! @raphaelcoeffic

**Comment by raphaelcoeffic** [comment]
> This is probably my fault... I didn't test #852 on the NV14 before merge, and the firmware for that PR does look like it bricks on the NV14!!! Sorry boss! @raphaelcoeffic
> 
> nv14-6c74af9.bin (immediately prior commit) works nv14-bfaf529.bin (PR#852) fails to start nv14-ba03d02.bin (merge commit) fails to start

I must admit I did not test on NV14 either..... My fault!
