### ISSUE TITLE
Bug - Emergency Mode if power off whilst 'failsafe not set' screen active

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#87]
RM TX16S, https://github.com/EdgeTX/edgetx/commit/945fc9510ae451325803b6d2c1ba2ec15b014079

Whilst testing https://github.com/EdgeTX/edgetx/issues/74, I made the mistake of trying to power off the unit whilst the 'failsafe warning: failsafe not set' screen was showing (internal multimod set to frsky, receiver not powered). The shutdown delay screen shows, but before any segments start to show, the screen goes back, then the transmitter goes into emergency mode.

**Comment by raphaelcoeffic** [comment]
@pfeerick this should be fixed now with 038b8364f685de9. Can you please re-check?

**Comment by pfeerick** [comment]
Confirmed. :) Issue is gone post https://github.com/EdgeTX/edgetx/commit/5960d0aac2c8558073268ee762b9705b2a0590ed
