### ISSUE TITLE
Shutdown animation screen

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx#874]
Following on from the discussion in #862, we need to come to a consensus as to what will happen with the shutdown screen, as this is a community driven project, so is driven by what the majority want. 

My proposal was that it use theme colours, since that is what should be determining **all** colours used on the radio. Namely, that `COLOR_THEME_SECONDARY1` would be used for the background, and `COLOR_THEME_PRIMARY1` would be used for the animation icon. 

I felt it was too close to 2.5.0-RC3 which should be the final RC, for this to be given the time it deserves to be seen and discussed, so it has been pushed back to 2.6.0. So over to the floor.

**Comment by NemesisXB** [comment]
I agree with using the theme colors. That black and white shutdown animation looks "terrible".

**Comment by rotorman** [comment]
We need some thumbs up/thumbs down voting.
How about following instructions - put a thumbs up to first post if you would favor having theme colors as shutdown colors or put thumbs down emoji if you prefer to keep it black and white (as presently).
If you favor a third option, add a comment explaining what that third option would look like.

**Comment by MervDale** [comment]
It happens so quickly, does any one really worry about this? which takes up the least resources B/W or colour?

**Comment by pfeerick** [comment]
@MervDale That really doesn't matter. This is literally a one line change which was made just before 2.5 release and pulled because of a comment out consistent system UI, and it was too late in the cycle to get feedback. I was actually going to put this up on discord this week to get the crowd to resolve it once and for all, majority rules ;) I still will, and may get into a habit of putting *something* up every couple of weeks for community engagement ;)
