### ISSUE TITLE
No TopBar Icons

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#89]
Hi,

I just have given EdgeTX initial run.
Tried builds tx16s-9691cc9 and tx16s-f97843c from 25th of May

1. Went to https://downloads.open-tx.org/2.4/nightlies/sdcard/ to get updated SD card content
- all files are named V0026
- there is no file for RM TX16S 
Downloaded  the one for Jumper T16 as closest one

2. After power up with EgdeTX I can't see single icon on Top Bar including Logo. 
EdgeTX seems to work as expected only icons are not displayed

3. There is no way to change Theme (maybe intentional) so assumed Default is used, Then checked /THEMES/DEFAULT/ folder in downloaded zip and there are only 4 files (including two mask_****.png)
Copied missing files from  /THEMES/DARKBLUE/  but still TopBar icons are not visible.

Bug or I'm doing something wrong?

![190533384_510725576725889_8756636070582667512_n](https://user-images.githubusercontent.com/46420768/119665765-fe5cbf00-be34-11eb-9a1d-451d4137293d.jpg)
![190658806_839299826936732_7417054658162947070_n](https://user-images.githubusercontent.com/46420768/119665778-01f04600-be35-11eb-9c09-e026f4c08f3d.jpg)
![191184050_929131017930600_4509508636515639493_n](https://user-images.githubusercontent.com/46420768/119665780-0288dc80-be35-11eb-9cc7-1ece10c9bd66.jpg)

**Comment by raphaelcoeffic** [comment]
@JimB40 you need to copy the EdgeTX theme located here on the repo (`radio/sdcard/horus/EdgeTX`) into `THEMES` on the SD card. That is necessary until these simple bitmaps are integrated into the firmware itself (see #15). Concerning the theme choice, it is indeed not yet implemented, but will be soon.

**Comment by JimB40** [comment]
Thank you Raphael. Now works properly. :) 

I've also tried crossfire.lua and AgentLite. None of them works. Fired up my LUA CRSF packet sniffer and seems like there is no response from microTX  (0x28 frame). 
Any changes were done in LUA crsfTelemetryPush() & crsfTelemetryPop()? Data filtering? Some frames (mainly broadcast) are not passed to Pop function in OpenTX, instead they are changed into OpenTX telemetry fields.  
![190833479_1225240891263992_2737221607417880173_n](https://user-images.githubusercontent.com/46420768/119689493-30781c00-be49-11eb-95ac-2c9e1babb9bd.jpg)

**Comment by raphaelcoeffic** [comment]
> Any changes were done in LUA crsfTelemetryPush() & crsfTelemetryPop()? Data filtering? Some frames (mainly broadcast) are not passed to Pop function in OpenTX, instead they are changed into OpenTX telemetry fields.

I don't think so. It has not been investigated. If that persists, or you think there is an issue here, please make a separate one.

**Comment by JimB40** [comment]
Okay. During radio and model setup I've spotted few minor UI bugs or quirks. Want them in separate issues? Don't want to flood :)

**Comment by raphaelcoeffic** [comment]
> Want them in separate issues? Don't want to flood :)

You can make a list of "minor UI bugs or quircks" and place that into an issue, no problem.
