### ISSUE TITLE
Companion helicopter wizard is disabled

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx#894]
Feature disabled in opentx some time ago as provided limited configuration and required lots of manual post wizard configuration.
Discord discussion has revealed there are some heli pilots that can assist in improving but first re-enable to facilitate feedback.

**Comment by pfeerick** [comment]
How do you want to run with this... just merge this into main, or continue the tweaking of the heli wizard in this PR if people are comfortable getting the builds from the  checks tab?

**Comment by lshems** [comment]
Fine by me. If there are resources to do that, perfect. But be aware in opzntx it is some sort of a hack, with in my opinion also an error in the mixer calculations. See the posts on that here.
