### ISSUE TITLE
Donation link in Companion About Screen goes to https://edgetx.org/

### ISSUE THREAD

**Issue by MartinHugh** [EdgeTX/edgetx#913]
There is a donating link on the "About" screen in Companion which redirects to https://edgetx.org/

That may or may not be the correct URL, but if it is I cant see any obvious way of making a small donation ;-)

**Comment by pfeerick** [comment]
I would firstly like to say "Thank you for wanting to donate" ;)

Unfortunately, we are not in a position where we can accept financial donations at present as a project. We are in the process of trying join the Software Conservancy, who will can manage all the "non-technical administrative tasks", meaning we don't have to have a legal entity, and can operate in an open and transparent manner. However, this is taking longer than we would like, and will probably also be contacting the Software in the Public Interest (SPI) organisation as well as investigating other options. 

So at the present time, the best donation would be in the form of being able to test stuff, making contributions to the code, doing some graphics work or just generally hanging out and helping someone if they've got an issues ;)
