### ISSUE TITLE
crashed RM TX16S with touchscreen in test lua script

### ISSUE THREAD

**Issue by MNS26** [EdgeTX/edgetx#914]
**Describe the bug**
RM TX16S touchscreen breaks lua script and reopening it crashes the radio (found out about this with ELRSv2 script)

**To Reproduce**
the most reliable way to do it is to (open ELRSv2 -> swipe around -> scroll and hear beeps -> plug in usb -> sd mode -> disconnect -> reopen ELRSv2 -> crash)

_examples_
https://drive.google.com/file/d/1tUkWwpORuFSGrMxJNBBed3axxf3IuZDo/view?usp=sharing
https://youtu.be/cJGlfYjm8DI

**Expected behavior**
for it to ignore touch event if not added to the script

**Screenshots**
(see video)

**General information**
 - EdgeTX version: 2.5.0 (28cdb40e)
 - Hardware: RM TX16S

**Comment by MNS26** [comment]
@raphaelcoeffic i have a feeling we're looking at multiple different crashes as if they are ene.

I'm sure the touchscreen issue in standalone lua scripts  is definitely one of them.
But i feel like the USB storage mode might be an issue with files/scripts being loaded and then not being closed properly when entering USB storage mode.

**Comment by MNS26** [comment]
@jfrickmann nope it still crashed (USB and touch)

**Comment by MNS26** [comment]
i also found something else on the latest master branch (not related to this problem)
im assuming its supposed to be XXhXXm 
 
![20211018_194033 1](https://user-images.githubusercontent.com/53867268/137781602-8dd5ca9c-5157-47ac-94a6-7c240cbd142d.jpg)

**Comment by pfeerick** [comment]
Keeping in mind touch support hasn't been added to standalone scripts (only widgets),  I'm not sure how that can even be a factor here! :-O Regardless, something is not working, we're just not 100% clear on the what yet.

**Comment by pfeerick** [comment]
Excellent. `[ViewMain] Focus lost` was what I was expecting to see. In the next day or so it will be a matter of running the code up again with the debugger attached and seeing why it is jumping out / losing focus...

**Comment by MNS26** [comment]
i havent been able to track down the issue with USB yet, but im very suspicious of how it handles files that are open when going into storage mode

**Comment by MNS26** [comment]
the USB craash is not related to just the ELRS script, ive crashed it with just a test one i made 

```
local function run(event)
  lcd.clear()
  lcd.drawText(0, 0, "Hello World")
  return 0
end

return { run = run }
```

**Comment by MNS26** [comment]
@pfeerick pfff... finally got it to work but using the left uart  (to keep USB SD) but all i see is garbage on the serial port
![image](https://user-images.githubusercontent.com/53867268/137963033-24989e1c-46e1-4680-9e9e-a906bfde8a0b.png)

**Comment by rotorman** [comment]
This looks like wrong baudrate. Is it TX16S? Try 400.000 baud 8N1 on PC side.

**Comment by pfeerick** [comment]
Whatever terminal or adapter you're using probably doesn't support that board rate, as 400000 baud is correct. Try putty (I use [kitty](https://github.com/cyd01/KiTTY/), a derivative of putty).

**Comment by dlktdr** [comment]
Had a bit of grift getting mine to work right away too. I also have a CP2102. Is it a recent driver?https://www.silabs.com/documents/public/software/CP210x_Universal_Windows_Driver.zip

I use terra term and it shows more available serial bauds. You can set targets/horus/board.h LN# 670 to match one of the available bauds if 400,000 isn't listed. 

Can also check this link too http://www.olliw.eu/storm32bgc-wiki/How_to_configure_CP2102_USB_adapters_for_high_baud_rates the utility link isn't working but here is a copy https://www.silabs.com/documents/public/example-code/AN721SW.zip

**Comment by MNS26** [comment]
@pfeerick the issue is that somehow the data becomes garbage so "just use putty" isnt that easy because it will only output _valid_ ascii characters but.... **if none of the data is valid.....** nothing will show

(furiously scrolled with the roller for 5 sec and.... nothing at all)
![image](https://user-images.githubusercontent.com/53867268/138259930-2303d82f-2550-4225-8ce1-e19a7b7cdb43.png)

**Comment by pfeerick** [comment]
Hm... that makes no sense... you logic analyser says the bits are the right way around, and that hterm is seeing them the wrong way around... but if putty is doing it also, it looks like your uart is somehow reading in wrong LSB/MSB order?

**Comment by MNS26** [comment]
is there a way to... oh idk.. force a low baud rate (something like 115200)?
if i use serial over usb-c it works but i cant test the usb SD crash then

**Comment by MNS26** [comment]
there we go...
![image](https://user-images.githubusercontent.com/53867268/138279633-c2f946e4-0eb4-4757-9632-e1b48d139fd9.png)

i made the firmware use 115200 for debug

**Comment by raphaelcoeffic** [comment]
This pretty old and has not been reported since then, so let's assume this has been fixed in a later release.
