### ISSUE TITLE
LUA Widget absolute position

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#916]
Since widget's zone.x & zone.y properties are not keeping widgets top left corner position on LCD screen add
zone.left & zone.top properties to zone table to pass this info to widget

**Comment by raphaelcoeffic** [comment]
Normally, the top left corner should always be 0:0. just like all the other windows in EdgeTX on the color targets.

**Comment by pfeerick** [comment]
The reason for wanting this is to be able to determine the position of a widget on the screen, in able to make the widget be able to change it's display dependent on position - i.e. it can right align or left align text depending on which side of the screen it is on. So what this wants to do is pass the zone's x/y co-ordinates to the widget.

**Comment by JimB40** [comment]
Can we add then zone.xabs & zone.yabs? :)

**Comment by jfrickmann** [comment]
> x an y should hold abs value of zone top left corner. This legacy shit. In OTX to draw inside widget you used abs lcd coordinates ( so it was possible to draw outside widget) . Jesper changed this so for draw commands inside widget 0,0 is widget's top left corner. Which is okay. But he made constant x,y = 0,0 to keep legacy. That makes widget's x,y properties dummy as we know top left corner is 0,0

No I did not. My understanding is that the change came with libopenui, and it makes perfect sense to me. Before, you could not only draw over other widgets, you could also crash the radio drawing off the screen. Of course, widgets should only be able to draw within their own zone.

**Comment by JimB40** [comment]
Jesper I understand. Someone FU as lcd.draw used in widget should offset coords by zone.x & zone.y. 
Now repaired but legacy. Devs used zone.x & zone.y to offset. Fine.
it's not about to find who & why but about data where in the LCD widget is placed. :)
I was using zone.x & zone.y find out.  
How can we get back widget LCD absolute position info?
