### ISSUE TITLE
Simulator TX16s: reload radio data reloads widgets but misses to start all

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#927]
If I have more than one widget running and use F9 (reload) then the scripts get reloaded but the last one (maybe all but the first) is not restarted. I have to setup the same widget again, then it runs again.

**Comment by philmoz** [comment]
Is this still an issue?  I can't seem to reproduce it.

**Comment by wimalopaan** [comment]
Looks like it has gone ...
