### ISSUE TITLE
No possibility to paste Logic Switch or Special Function

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#95]
**Describe the bug**
Pressing [ENTER] on empty Logic Switch or Special Function if empty goes directly to Edit Mode. If user prevoiusly copied line with data there is no possibility to paste it to empty line.

**To Reproduce**
1. Copy Logic Switch or Special Function with data
2. Go to empty line and press [ENTER]

**Expected behavior**
Menu with Edit & Paste option should be displayed

**General information**
EgdeTX version 9691cc9
RM TX16S

**Comment by raphaelcoeffic** [comment]
Fixed in a7aefb7788ed5c and cd8c7e07f7d54727e
