### ISSUE TITLE
TOOLS Tab list sorted by file name

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#950]
Now it's mystery how it's sorted (creation date?) so every time *.lua content changes. Script goes to more or less random position on the Tools list.
Actual displayed name is hidden in the script itself so this would need to open every single script to check this name and IMHO not good implementation but simple sorting by filename would allow to change let's say 'SampleToolSctipt.lua' to "1_SampleToolSctipt.lua" and force to appear as first on the list.

**Comment by philmoz** [comment]
Is this still an issue?

**Comment by JimB40** [comment]
Nope
