### ISSUE TITLE
FrSky X-Lite Pro EdgeTX 2.5 issues 

### ISSUE THREAD

**Issue by Martin1134** [EdgeTX/edgetx#960]
I recently updated my FrSky X-Lite Pro to EdgeTX 2.5. 

First thing i noticed was that my Tracer and Tracer Wifi doesn't show up on the Agent lite. 
Further I tested my Quads, they're responding just like normal. 
After waiting I noticed that it takes around 5 minutes, then my Tracer is showing up just like normal on the Agent lite but does not respond to any inputs. 
It also loses Telemetrysignal once like a minute or so.. 

If I go back to EdgeTX 2.4 everything seems to be normal. 

Hardware/Software: 
- FrSky X-Lite Pro (EdgeTX 2.5)
- TBS Tracer  (Softwareversion: 6.10)
- TBS agent lite 0.92

I've flashed through the EdgeTX Bootloader 

Update:
Also tested it with the TBS agent lite 0.95 and EdgeTX 2.6-RC2 ... same results.

**Comment by gagarinlg** [comment]
Is there any update on that with a current version of EdgeTX?

**Comment by Martin1134** [comment]
I don't know. I switched to elrs wich is working fine.

**Comment by gagarinlg** [comment]
Then I am closing this issue. If someone else has this problem, a new issue can be opened.
