### ISSUE TITLE
Make Top Bar Text Widgets able to span multiple widgets

### ISSUE THREAD

**Issue by MartinHugh** [EdgeTX/edgetx#970]
TX: Radiomaster TX16S

**Is your feature request related to a problem? Please describe.**
It is useful to be able to show text in the top bar widgets.  One such candidate for this is the model name
In order to see this more easily requires using the maximum height of text which will fit in the widget.

However - this severely limits the number of characters which will fit in the widget
For example, the largest size available without clipping the height is XL.
The word "Acrowot" displays as "Acro"

**Describe the solution you'd like**
Allow a Text Widget on the top line, to span multiple widgets.  
This was available in OpenTX, so it would seem reasonable that such functionality is carried forward.

**Comment by gagarinlg** [comment]
The solution would be to offer multiple top screen widget setups:

- 4 widgets with a span of 1
- 3 widgets
  - 2,1,1
  - 1,2,1
  - 1,2,2
- 2 widgets
  - 2,2
  - 1,3
  - 3,1
- 1 widgets
  - 4

**Comment by offer-shmuely** [comment]
Will love to see that happen

**Comment by philmoz** [comment]
Added to 2.11 in PR #5235

**Comment by offer-shmuely** [comment]
Amazing!!!
Thanks 🙏
A long waited one

**Comment by MartinHugh** [comment]
Thank you guys

**Comment by MartinHugh** [comment]
Many thanks for this
