### ISSUE TITLE
Bug in bitwise Color Flag calculations

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#973]
This script

return {
  run = function(e)
    lcd.clear(WHITE)
    lcd.drawFilledRectangle(50,50,380,172,WHITE)
    return 0
  end
}

gives this result
![screenshot_tx16s_21-10-29_12-59-02](https://user-images.githubusercontent.com/46420768/139423690-73977b5c-60aa-48f8-9cfd-ae24f85c0250.png)

**Comment by pfeerick** [comment]
This bug is no longer present in basically today's nightly, but specifically in #2218. Most likely fixed during changes as part of LVGL re-write.
