### ISSUE TITLE
LUA: model.setFlightMode() behaves weird setting trims

### ISSUE THREAD

**Issue by wimalopaan** [EdgeTX/edgetx#976]
I tried to exclude the trims 5 and 6 (index 4 and 5) of flightmode 0 and 1.
Exclude has the mode value 31. 
Doing so via model.setFlightMode(...) sets all (!) trims except index 0 (trim1) to exclude from that mode.

**Comment by lshems** [comment]
Check on the opentx GitHub. Lots of info on this bug there

**Comment by wimalopaan** [comment]
Well, if I read that correct, I have to pass the full table of trimsMode. Therefor I read the full table via getFlightMode(), change the two trims (index 4 and 5) to value 31, and then write it back. That should be ok, but isn't...

**Comment by lshems** [comment]
The bug in opentx is that they made some signed integer error, AND don't use proper array indexing

**Comment by wimalopaan** [comment]
Sounds like you have a fix for this?

**Comment by lshems** [comment]
Would love to, bit can't program in c

**Comment by wimalopaan** [comment]
It looks not to be possible to modify the table trimsModes returned getFlightMode().

As a workaroung one has to create a new table with six entries, and assign this table-ref to trimsModes and then write it back with setFlightMode().

**Comment by lshems** [comment]
This is still not fixed, and should not be much work. Any chance ....

**Comment by raphaelcoeffic** [comment]
@lshems @wimalopaan Gentlemen, please provide feedback on the PR fixing this issue (see #2567)
