### ISSUE TITLE
Text file is not viewable in SD Card browser

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx#98]
**Describe the bug**
View text does nothing

**To Reproduce**
1. Go to SD CARD & select *.txt or *lua file
2. Press [ENTER] and select 'View text'

**Expected behavior**
Full screen window with text file content should be displayed
If I may suggest - the smaller font the better :) 

**Screenshots**
![2021-05-26 21 29 45](https://user-images.githubusercontent.com/46420768/119732883-122a1480-be79-11eb-9acc-e9596e3c7694.jpg)

**General information**
EgdeTX version 9691cc9
RM TX16S

**Comment by eshifri** [comment]
I think this functionality is not implemented yet.

**Comment by pfeerick** [comment]
Resolved by #406
