### ISSUE TITLE
Split Top Bar touch functionality into 2 boxes

### ISSUE THREAD

**Issue by audiogek** [EdgeTX/edgetx#981]
For easier access to page two of the main menu.

Split the top bar touch box into two halves.
So when the right half is clicked/touched(red in picture) you go directly to page two.

![screen1](https://user-images.githubusercontent.com/68812769/139709642-ede6fb90-2f1d-4b15-83e4-c57c002999d2.jpg)

**Comment by jmxp69** [comment]
I have no influence on whether or not the developers will incorporate your request, but I thought I'd mention you can swipe from screen 1 to 2 by swiping. Just throwing that out there in case you didn't know.

**Comment by audiogek** [comment]
I'm complete noob at github but as far as I can make out it looks like my request is already coded and tested.
I think I need to thank RCVideoReviews and close it or am I misreading this?

**Comment by raphaelcoeffic** [comment]
> I'm complete noob at github but as far as I can make out it looks like my request is already coded and tested.
> I think I need to thank RCVideoReviews and close it or am I misreading this?

This will be closed auto-magically if the pull request gets merged.

**Comment by pfeerick** [comment]
Coded by @eshifri, but not tested or merged yet. And as Raphael said, the issue will auto-close when the code if and when the PR is merged ;)

**Comment by audiogek** [comment]
> Coded by @eshifri, but not tested or merged yet. And as Raphael said, the issue will auto-close when the code if and when the PR is merged ;)

Cool, thanks guys!
