### ISSUE TITLE
flysky gimbal

### ISSUE THREAD

**Issue by pds59** [EdgeTX/edgetx#986]
*add flysky gimbal option on radio build option for people not able to compile firmware

**Comment by richardclli** [comment]
You can do custom build in github.  Anyway, we are working on better support on different build options.  If you want to get pre-build firmware, please contact me or Risto at Discord group.

**Comment by pfeerick** [comment]
@pds59 For what transmitter? I have TX16S build of 2.5.0 and nightly up at https://files.portabledev.xyz/d/8e4d08b0905743cbbccb/

**Comment by pds59** [comment]
T16s tks Peter i Will download itPaolo de scagliaIl 7 nov 2021 06:08, Peter Feerick ***@***.***> ha scritto:
@pds59 For what transmitter? I have TX16S build of 2.5.0 and nightly up at https://files.portabledev.xyz/d/8e4d08b0905743cbbccb/

**Comment by pds59** [comment]
Tks a lot for your workPaolo de scagliaIl 7 nov 2021 06:08, Peter Feerick ***@***.***> ha scritto:
@pds59 For what transmitter? I have TX16S build of 2.5.0 and nightly up at https://files.portabledev.xyz/d/8e4d08b0905743cbbccb/
