### ISSUE TITLE
The CN language timer is missing characters

### ISSUE THREAD

**Issue by norulers** [EdgeTX/edgetx#990]
![20211106181322](https://user-images.githubusercontent.com/5206964/140606051-6b5daa81-2136-4089-8f7f-f6c066d56367.png)

![20211106181335](https://user-images.githubusercontent.com/5206964/140606053-24ecc567-85fc-4b22-934d-bf7eded6c561.jpg)

**General information**
 - EdgeTX version：t18-28cdb40
 - Hardware ：T18

**Comment by gagarinlg** [comment]
This should be fixed with current EdgeTX versions. If not, please open a new issue
